### ISSUE TITLE
[dev.icinga.com #7153] End user documentation

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1002]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7153

**Created by tgelf on 2014-09-09 11:19:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-10-21 12:57:58 +00:00 (in Redmine)_

---

Our documentation is currently an unsorted amount of partially outdated developer guidelines. Documentation should first of all help Icinga users to get their daily work done. Only AFTER that we want to see guidelines for module developers and the very LAST entries should target Icinga Web developers contributing to the framework itself.

Best,
Thomas

**Changesets**

_2015-06-01 17:16:35 +00:00_ by _(unknown)_ cf95994ff54b4b8bd70cb675cf3d4a6648d245c7

    Documentation: Add config overview as first draft
    
    refs #7153

_2015-09-27 15:12:24 +00:00_ by _mfriedrich_ 9a06afb1f83f214887ba996dba2a3e282fce4e48

    Doc: Restart the webserver after changing group membership
    
    refs #7153
    fixes #9484

_2015-09-27 15:32:24 +00:00_ by _mfriedrich_ e0e7fe202a4f957390691c713e2f39772f107b3d

    Move upgrading to a dedicated section and add a link
    
    refs #7153

_2015-09-29 17:50:08 +00:00_ by _mfriedrich_ 7c28a206a90859091b7395224b7c472d3542cae6

    Document example commands for installing from source
    
    That also adds all the details we use for automated deployments
    and manual installations (e.g. mysql db setup, user creation, manual
    config files).
    
    Maybe this could be split into installation-from-source.md
    somewhere in the future, but for now it should help anyone
    out there to deploy Icinga Web 2 w/o running the setup wizard
    in automated environments.
    
    fixes #8407
    refs #9595
    refs #7153

_2015-09-29 17:57:44 +00:00_ by _mfriedrich_ 0c50c847dec8c293a224201ff656a514a6b7e851

    Document example commands for installing from source
    
    That also adds all the details we use for automated deployments
    and manual installations (e.g. mysql db setup, user creation, manual
    config files).
    
    Maybe this could be split into installation-from-source.md
    somewhere in the future, but for now it should help anyone
    out there to deploy Icinga Web 2 w/o running the setup wizard
    in automated environments.
    
    fixes #8407
    refs #9595
    refs #7153

_2015-10-02 07:50:51 +00:00_ by _mfriedrich_ 48bee8d8fd1eba3eb87d6b87db1a551eed9b8255

    Doc: Restart the webserver after changing group membership
    
    refs #7153
    fixes #9484

_2015-10-02 07:50:52 +00:00_ by _mfriedrich_ 73dfb286f5141c437152fe5e80b8baf36a6de028

    Move upgrading to a dedicated section and add a link
    
    refs #7153

_2015-10-02 07:50:52 +00:00_ by _mfriedrich_ ded631b5894423d02aa68d21c3b5465afa72069e

    Document example commands for installing from source
    
    That also adds all the details we use for automated deployments
    and manual installations (e.g. mysql db setup, user creation, manual
    config files).
    
    Maybe this could be split into installation-from-source.md
    somewhere in the future, but for now it should help anyone
    out there to deploy Icinga Web 2 w/o running the setup wizard
    in automated environments.
    
    fixes #8407
    refs #9595
    refs #7153

_2015-10-02 07:51:15 +00:00_ by _mfriedrich_ 5a14a3c4eaf424e56e166d5b328f6c6a32894193

    Merge branch 'feature/doc-7153'
    
    refs #7153

_2015-10-02 08:36:39 +00:00_ by _mfriedrich_ c3b5d8ab511ec4ae668b3e13dcb3a9a0ffb538ae

    Doc: Fix typo
    
    refs #7153

_2015-10-02 08:44:33 +00:00_ by _mfriedrich_ 9a28855cc04808d6fca91876302e15048a1e8cfb

    Merge branch 'feature/doc-7153'
    
    refs #7153

---

**Subtasks**:

* [Feature 9512 - Add documentation for creating users through the UI](https://dev.icinga.com/issues/9512)
* [Feature 5519 - Make CLI documentation available to the docs module](https://dev.icinga.com/issues/5519)
* [Bug 8471 - Document how to define a custom configuration directory](https://dev.icinga.com/issues/8471)
* [Feature 8539 - Document Gravatar integration for the contact views](https://dev.icinga.com/issues/8539)
* [Feature 8789 - Document how to add custom documentation directories](https://dev.icinga.com/issues/8789)
* [Feature 8431 - Doc module should respect README.md if available](https://dev.icinga.com/issues/8431)
* [Feature 9595 - Add documentation for setup (wizard and manual)](https://dev.icinga.com/issues/9595)
* [Feature 9612 - Document LDAP filter setting in authentication.md](https://dev.icinga.com/issues/9612)
* [Bug 9227 - Missing documentation on configuring LDAP to AD backends](https://dev.icinga.com/issues/9227)
* [Feature 9648 - Document how to integrate Web 2 into NagVis](https://dev.icinga.com/issues/9648)
* [Feature 9988 - Document option to disable stack traces](https://dev.icinga.com/issues/9988)
* [Feature 10001 - Allow to link foreign documentation from modules and the framework](https://dev.icinga.com/issues/10001)
* [Feature 10810 - Document how to hide menu and header](https://dev.icinga.com/issues/10810)

**Relations**:

* relates [#7153](https://dev.icinga.com/issues/7153)

**Comment by lippserd** [comment]
I close this issue. Our documentation is still not the greatest to be honest :). If there's anything missing, please open a dedicated issue.
