### ISSUE TITLE
[dev.icinga.com #7178] Host and service group overview capable of showing tons of host and service groups within a small space

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1017]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7178

**Created by twidhalm on 2014-09-10 13:51:46 +00:00**

Assignee: _elippmann_
Status: _Feedback_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:45 +00:00 (in Redmine)_

---

Users that have lots of hostgroups (an example shown to me had &gt;700 hostgroups) could use an overview with the names and just an icon to show wether there are errors on hosts in the group like some old school monitoring tools do it. Maybe use a layout like the service matrix to get more groups on the screen. It would be good to have a link from the hostgroups to a servicematrix for this hostgroup.

**Attachments**

* [Servicegroup-Matrix.png](https://dev.icinga.com/attachments/download/2036/Servicegroup-Matrix.png) dlamers - _2014-09-12 08:38:12 +00:00_
* [Hostgroup-Matrix.png](https://dev.icinga.com/attachments/download/2037/Hostgroup-Matrix.png) dlamers - _2014-09-12 08:38:12 +00:00_

**Changesets**

_2015-05-27 16:12:52 +00:00_ by _aklimov_ 85bd38a94f31932be36cf88f113f4b23e36512d1

    Move ::addTitleTab() to the base class
    
    refs #7178

_2015-05-27 16:19:56 +00:00_ by _aklimov_ f625041fe528237109382eea5a7ddbbc47b8068e

    Move ::filterQuery() to the base class
    
    refs #7178

_2015-05-28 10:30:07 +00:00_ by _aklimov_ 6deaa950290c67ec08522f7e0a5c81e5122245c5

    Implement host group grid
    
    refs #7178

_2015-09-04 08:47:15 +00:00_ by _afuhr_ b59d138b89a1c54667dfd58245137598c180e233

    monitoring/module.less: Add grid-group styling
    
    refs #7178

_2015-09-04 08:48:03 +00:00_ by _afuhr_ bc6a8037f2e2c0f2f8fce3ac157cec477fedfca8

    HostgroupController: Update the layout and details
    
    refs #7178

_2015-09-04 08:49:31 +00:00_ by _afuhr_ c97fa3d6b5b86379147007f681352705a1100fdf

    hostgroup/grid: Update the layout and remove tables
    
    refs #7178

_2015-09-04 08:50:32 +00:00_ by _afuhr_ 745bf52f0bd9ac47fb6c80f08b21a6028a1415ad

    ServicegroupController: Implement grid action
    
    refs #7178

_2015-09-04 08:51:24 +00:00_ by _afuhr_ c2060720d99a7c1069b9fadc5e1c984f37d10a4e

    servicegroup/grid: Add layout and details
    
    refs #7178

_2015-09-04 08:51:58 +00:00_ by _afuhr_ b4d241e6def7c4ecad43e78d14133e1e8b86484f

    monitoring/configuration: Add host- and servicegroup grid to menu
    
    refs #7178

**Comment by voiprodrigo** [comment]
Is this still in the works? I noticed the screenshots are from Xymon, and this is precisely the kind of presentation I’m missing on current modern monitoring tools. high density status grid for a hierarchy of pages/groups

**Comment by nilmerg** [comment]
Played a bit around with the following results. These are two possible solutions. Not perfect, but you'll get the idea:

This is basically what is already shown above: (Consider this a bit more smooth, not as shaky as shown.)
![servicegroup-grid-proposal](https://user-images.githubusercontent.com/16668527/39575148-cc7d9266-4ed9-11e8-881c-889133549633.jpg)

This is an alternative. Way more dense. Still pretty basic though. I'd want to display a counter by default (but still only for problems!) and the alias only upon hovering with the mouse over it. (Not as popup but with a sliding animation or the like)
![hostgroup-grid-proposal](https://user-images.githubusercontent.com/16668527/39575146-c91e7c2a-4ed9-11e8-9d89-bd781370b419.jpg)

The first proposal is more informative, obviously. But we've already got such a view with the current group listings. The alternative is based on the idea that one only wants a glance at the current overall state and problem states are visualized with their proper severity.

I'd opt for the alternative. What do others think? (@dnsmichi, @widhalmt , @voiprodrigo , @lippserd   )

Note: Hostgroups are around 700 in total (on a single page!) and service groups are around 300 in total.
