### ISSUE TITLE
[dev.icinga.com #7281] Enhance the default search behavior

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1037]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7281

**Created by aledermueller on 2014-09-19 13:24:02 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-11-09 10:30:02 +00:00 (in Redmine)_

---

Hi,

If i type the string "icing memory", i want to see every service where "icing" and "memory" occur in any of the fields (Hosts and Services (and perhaps hostgroups, contactgroups....)). To make it more clear, with this query i want to find all "memory" services on any host with "icing" in the name and i don't want to any complex string like "hostname:**icing** AND servicename:**memory**". Sure this will find any Service with icing and memory in the name, too, but i think this what users expect.

Why this is better?
- less to type
- quicker filtering (narrowing down the results)
- filtering for hostnames and services names is possible
- it allows to search for a hostname and select multiple services of this host and i could perform actions on them (this would resolve ticket [\#7280,](https://dev.icinga.com/issues/7280) too)

Why the actual solution is worse?
- service names with many occurrences could not be narrowed down to a host (e.g. memory will have n occurrences, n = \#hosts)
- more to type

I think this is a real enhancement for the usability, but sure, this is much more complex to implement.
I think this is a behavior users really need, and with a fast search this will be really cool
I am used to this kind of search from other applications and i curse every time when i try to use this way in icinga web.
I think this is a really importing thing for the usability.... let's argue....

Thoughts?

---

**Parent Task:** [#9479](https://dev.icinga.com/issues/9479)

**Comment by nilmerg** [comment]
Will be part of #4094. More or less.
