### ISSUE TITLE
[dev.icinga.com #4071] Availability report

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#104]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/4071

**Created by berk on 2013-05-07 07:29:31 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2016-10-05 13:20:06 +00:00_)
Target Version: _(none)_
Last Update: _2016-10-05 13:20:06 +00:00 (in Redmine)_

---

As a user, I want to create availability reports for hosts, services, host groups and service groups because I want to know the summarized availability percentages for a given time range.

**Acceptance criteria**:

-   Allow to choose hosts, services, host groups and service groups
-   Allow to choose a time range
    -   Last Day|Week|Month|Quarter|Year
    -   Custom time range
-   Output formats should be HTML, CSV, JSON and PDF
-   Hosts should include their related service availability
-   Display pie charts for the availability

---

**Relations**:

* relates [#4096](https://dev.icinga.com/issues/4096)

**Comment by menon0906** [comment]
Is there anyway we can get the report availability from Icingaweb2? Please Help

**Comment by iDemonix** [comment]
Install the classic UI

**Comment by lippserd** [comment]
Unfortunately, we don't have a full-featured reporting module for Icinga Web 2 yet. I expect it to be ready at the end of this year or at the beginning of the next year. In the meantime you could generate your reports w/ JasperReports and the icinga-reports repository. We have a minimal documentation for Icinga 1.x here: https://docs.icinga.com/latest/en/reporting.html. Since Icinga 1.x and Icinga 2 share the same database schema, most parts of the documentation apply to Icinga 2 as well.

**Comment by cflinspach** [comment]
@lippserd If we're using the latest version of Icinga2 will the first step in that guide `/usr/bin/mysql icinga < icinga-reports-1.10.0/db/icinga/mysql/availability.sql` cause an issue with our current data?

**Comment by dnsmichi** [comment]
Look into the SQL file, it won't alter any tables but add new procedures and some temp tables afaik.

**Comment by cflinspach** [comment]
I got it up and am able to get availability reports. There were only a few differences from that guide. The wget link for jasper 5.0 doesn't work so I  signed up and download the community edition. I used 6.4.0 with tomcat 7 and the master from icinga-reports. The configure was different too, I used
 `./configure --with-jasper-server=/opt/jasperreports-server-cp-6.4.0 --with-icinga-user=nagios --with-icinga-group=nagios`

**Comment by menon0906** [comment]
@cflinspach  after downloading the tar file and copying into local icinga2 path, are we getting the PDF format report available in Icingaweb2? Thanks in Advance..

**Comment by dnsmichi** [comment]
Please continue over at the community channels, i.e. the forums or mailing lists.

**Comment by menon0906** [comment]
@cflinspach can you please show me the image of UI after you get the reporting structure available in Icingaweb2?

**Comment by cflinspach** [comment]
@menon0906 The UI can be seen at [jaspersoft](https://www.jaspersoft.com/) because it's not a module but a separate software package that uses the premade reports from this repo. You can message me on here, or my username is Red_Eagle on [monitoring-portal.org](https://monitoring-portal.org) if you wanna talk more.

**Comment by rosabenson** [comment]
@cflinspach  I would also like to get the availability reports in icingaweb2, can you help?

**Comment by cflinspach** [comment]
@rosabenson Sure thing, feel free to email me at cflinspach@protonmail.com or message me on [monitoring-portal.org](https://monitoring-portal.org), my username is Red_eagle.

**Comment by mmarodin** [comment]
Any news about the release of the reporting module for Icinga2?

**Comment by t-rex2** [comment]
The availability report feature in Icingaweb2 would be awesome. :+1:

**Comment by Noname2244** [comment]
I think the lack of this feature is stopping the use of icinga2 in many enterprises. There would be many more support contracts bought if this feature was available.

**Comment by cflinspach** [comment]
@Noname2244 I just ran through the guide at [Here](https://www.icinga.com/docs/icinga1/latest/en/reporting.html) and was able to generate reports with Icinga2 on Ubuntu 16.04. 

There's a few changes and Jasper Server 7.1.0 did not work. I used 6.4.3 from [Here](https://sourceforge.net/projects/jasperserver/files/JasperServer/JasperReports%20Server%20Community%20Edition%206.4.3/) 

I used master from the [reports repo](https://github.com/Icinga/icinga-reports) and `./configure --with-jasper-server=/opt/jasperreports-server-cp-6.4.3 --with-icinga-user=nagios --with-icinga-group=nagios`

After that everything was good and I ran some test reports.
![screenshot from 2018-10-01 10-42-20](https://user-images.githubusercontent.com/4700533/46305692-04585000-c567-11e8-9194-ccb0336f197e.png)

**Comment by iDemonix** [comment]
> **if any other way for taking availability report in icingaweb2 .**

We ended up just installing the classic UI side-by-side which still allows for the creation of availability reports - we also use them to drive business KPIs etc. In some instances we've simply binned off IcingaWeb2 for Classic until the missing features eventually make their way through.

**Comment by prabhakaran2304** [comment]
> > **if any other way for taking availability report in icingaweb2 .**
> 
> We ended up just installing the classic UI side-by-side which still allows for the creation of availability reports - we also use them to drive business KPIs etc. In some instances we've simply binned off IcingaWeb2 for Classic until the missing features eventually make their way through.

thx @iDemonix  , i used icingaweb2-reporting module [https://github.com/Thomas-Gelf/icingaweb2-module-reporting](url), its fine and cool for sla reports in icingaweb2 .

**Comment by iDemonix** [comment]
@prabhakaran2304 Looks interesting but very early days! Unfortunately if you're contractually obliged to provide SLA/KPI data that Icinga2 contributes to, you need something a bit more stable.

Glad to see some work is being done in the OSC to add reporting, but still disappointed to see such a key Icinga2 feature still missing from IcingaWeb2.

**Comment by Noname2244** [comment]
avail/sla reporting is  beeig worked on slowly, I heard that it should be released in 2019

**Comment by Thomas-Gelf** [comment]
> > thx @iDemonix , i used icingaweb2-reporting module [https://github.com/Thomas-Gelf/icingaweb2-module-reporting](url), its fine and cool for sla reports in icingaweb2 .

> @prabhakaran2304 Looks interesting but very early days! Unfortunately if you're contractually obliged to provide SLA/KPI data that Icinga2 contributes to, you need something a bit more stable.

More stable? I'm not stable? To cite a fa famous man: **I'm a very stable genius** :laughing: :rofl:

Jokes apart, that module is very old. It was already old once first pushed to GIT a couple of years ago. If you don't like it's look and feel you're not alone. I don't like it, and I wrote it. With basic SQL skills one should be able to steal it's main SLA function. You can use it in your custom reports or in your own good-looking Icinga Web 2 module.

While I already implemented it's next generation a couple of months ago, this should still be one of the fastest and most precise available functions when it gets to calculate SLAs for CIs monitored by Icinga. I'm using it for projects in large corporations, they are contractually obliged to provide SLA data.

Personally I'd love to have a reporting module providing a modern UI, offering more powerful Hooks to module writers than this one does. We already have half-working related UI prototypes and a related DB schema, with the schema allowing to configure and share Reports provided by implementations of it's Report Hook:

![reporting_preview3](https://user-images.githubusercontent.com/553008/47016066-fa317680-d14e-11e8-8b0b-73f989d7a501.png)

IDO-related code should be moved to a dedicated repository, and could then provide additional tooling like the possibility to drill down and explain SLAs:

![sla_inspection](https://user-images.githubusercontent.com/553008/47016870-23eb9d00-d151-11e8-886b-1faf3588b933.png)

But these are rough prototypes, they need to be cleaned up and some dedicated time to finish and release them. As of this writing all our developers are busy with other tasks, we're currently working on many cool new things in parallel. We tried to find sponsors for the Reporting module multiple times over the last years. This would have allowed us to prioritize it. Unfortunately we haven't been very successful.

Sooner or later there will be a cool new reporting component. As far as I know nothing has been scheduled so far.

Cheers,
Thomas

**Comment by scleronauta** [comment]
Hi Thomas , i'm trying to implement the reporting module , i succesfully imported the provided schema and now is working , but i can't get available the "configured reports view" as showed before . 

![immagine](https://user-images.githubusercontent.com/30775769/56280499-a1956300-610a-11e9-99ed-aeace0ba8179.png)

this is how appear the module inside icingaweb2 , what is missing?
