### ISSUE TITLE
[dev.icinga.com #7352] Auto-completion doesn't work for arguments

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1059]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7352

**Created by gbeutner on 2014-10-08 08:00:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-03-31 09:36:24 +00:00 (in Redmine)_

---

    root@mon:~# icingacli help show --
    :                 Available         commands          for               is                modules:          Refresh           summary
    5)                Be                commands:         Global            List              no                               There
    a                 benchmark         debug             handle            module            on                [s]               USAGE:
    [action]          --benchmark       --debug           help                        [options]         seconds           verbose
    actions           command           (default:         --help            [module]          options:          Show              --verbose
    and                        ERROR:            Help              modules           or                specific          --watch
    '--autocomplete'  command:          every             icingacli         modules,          output            such              web
    root@mon:~# icingacli help show --

I would've expected a list of arguments (--help, --benchmark, etc.).

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  We may introduce a new command class in the IPL which supports this.
