### ISSUE TITLE
Handle "special" 5xx server errors like 503 and 504 globally instead of rendering them to the containers

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1092]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7541

**Created by gbeutner on 2014-11-01 04:15:35 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:46 +00:00 (in Redmine)_

---

When the web server returns an HTTP error code for Icinga Web's requests I'd expect to see a red status bar (just like when the server is unavailable).

**Attachments**

* [http-errors.png](https://dev.icinga.com/attachments/download/2103/http-errors.png) gbeutner - _2014-11-01 04:14:24 +00:00_

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
