### ISSUE TITLE
[dev.icinga.com #7645] Move Vagrant and Puppet related code to a dedicated repository

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1129]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7645

**Created by tgelf on 2014-11-11 23:24:52 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-03-31 09:54:43 +00:00 (in Redmine)_

---

They are not required to run Icinga Web nor are they a great help in production. Vagrant helps to get a VM with sample-Daemons and config up and running. Puppet modules should know how to install Icinga Web to that box, nothing special here.

So I'd suggest to create a dedicated repository or to join efforts with icinga-vagrant.git.

Best,
Thomas

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. To be honest, we should remove this code completely and push Icinga docker containers instead.
