### ISSUE TITLE
[dev.icinga.com #7662] Define behaviour for empty filters

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1135]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7662

**Created by tgelf on 2014-11-13 17:18:29 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:47 +00:00 (in Redmine)_

---

Currently an empty filter chain is invalid. Sometimes it might make sense to just "match nothing" in that case. When building filters from dynamic sources right now we are forced to check whether Filter::isEmpty() before applying them, empty filters will fail.

We should evaluate whether the alternative "match nothing" strategy could make sense or whether it would have other side effects.

Cheers,
Thomas

NB: "not" is also a filter chain...

**Comment by nilmerg** [comment]
6 years later, I guess this is has been settled one way or another. Closing.
