### ISSUE TITLE
[dev.icinga.com #7733] Histogram for events in the history view of a host or service

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1153]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7733

**Created by aledermueller on 2014-11-19 08:26:53 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-11 07:53:25 +00:00 (in Redmine)_

---

Hi,

It would be nice to have a histogram over the events in the history view of a service. In addition it would be great to highlight a single event when i do a mouse over in the table.

Why? In the current history view it is very hard to get/understand the chronological relations of the events.

Regards,
Achim

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
