### ISSUE TITLE
[dev.icinga.com #7759] Can't select any service in the show contact view after clicking the mailto: link

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1164]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7759

**Created by jmeyer on 2014-11-20 14:11:42 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2016-10-21 12:41:21 +00:00_)
Target Version: _Backlog_
Last Update: _2016-10-25 07:48:45 +00:00 (in Redmine)_

---

Clicking such a link causes our JS to completely fail, obviously. ;-)

**Attachments**

* [mailto-error.jpg](https://dev.icinga.com/attachments/download/3727/mailto-error.jpg) jmeyer - _2016-10-25 07:48:42 +00:00_

**Changesets**

_2015-04-13 15:55:41 +00:00_ by _mjentsch_ 16b9c73436bab9318d1a09f5caaba8412fd168c2

    Do not destroy all global on mailto link clicks
    
    Only call the cleanup code on the unload event, beforeunload is only for asking for confirmation.
    
    fixes #7759

_2015-04-16 19:01:08 +00:00_ by _tgelf_ ae7d679a6a96832893a1feb51013f88ba68d6f56

    Revert "Do not destroy all global on mailto link clicks"
    
    This reverts commit 16b9c73436bab9318d1a09f5caaba8412fd168c2.
    
    As I already mentioned, this re-introduces the problem that you'll
    get ugly "lost connection to web server" notifications. Easiest way
    to reproduce this: click your browsers reload button while a request
    is pending - or just click reload a couple of times while showing the
    dashboard.
    
    refs #7759

_2015-05-19 14:35:44 +00:00_ by _mjentsch_ 94bdb8b4b072c9fadac77830325f727a14f93f85

    Abort pending AJAX requests before page unload
    
    Abort all pending requests before the page unload, to avoid confusing error messages during page reloads. Avoid rendering the site unusable in cases where the site is still being used after the beforeunload event.
    
    fixes #7759

_2015-05-19 15:06:22 +00:00_ by _mjentsch_ 54207d34275fc1bfed0adc31365c00fc98645be0

    Revert "Abort pending AJAX requests before page unload"
    
    This reverts commit 94bdb8b4b072c9fadac77830325f727a14f93f85. After the patch, Firefox shows an error message on each reload for an unknown reason.
    
    refs #7759

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
