### ISSUE TITLE
[dev.icinga.com #7858] Datetimepicker

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1199]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7858

**Created by shakalandy on 2014-11-26 15:13:15 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-08-29 05:45:44 +00:00 (in Redmine)_

---

The automatically popping up javascript calendar in the "Schedule Service Downtime" Tab is missing on Firefox & internet explorer.
It is working on chrome :)
The arrow to make it appear is also missing.

See attached screenshot.

**Attachments**

* [icingaweb2_ff.png](https://dev.icinga.com/attachments/download/2152/icingaweb2_ff.png) shakalandy - _2014-11-26 15:12:25 +00:00_

---

**Relations**:

* duplicates [#7858](https://dev.icinga.com/issues/7858)
* duplicates [#7858](https://dev.icinga.com/issues/7858)
* duplicates [#7858](https://dev.icinga.com/issues/7858)
* duplicates [#7858](https://dev.icinga.com/issues/7858)

**Comment by larsengels** [comment]
I'd also go for a simple JS Datetimepicker as a stop gap.

**Comment by lippserd** [comment]
Moved to #3416.
