### ISSUE TITLE
[dev.icinga.com #8082] Fontello icons not shown in PDF exports

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1273]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8082

**Created by jmeyer on 2014-12-15 13:00:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:49 +00:00 (in Redmine)_

---

As we are using our own font for icons, dompdf does not know anything about it and displays a question mark for every icon in PDF exports.

Adding a new font to dompdf obviously requires some work though (https://code.google.com/p/dompdf/wiki/Installation#Font\_Installation) and can't be done dynamically.

---

**Relations**:

* relates [#8082](https://dev.icinga.com/issues/8082)
* relates [#8082](https://dev.icinga.com/issues/8082)
* relates [#8082](https://dev.icinga.com/issues/8082)

**Comment by lippserd** [comment]
No progress has been made here. We'll replace dompdf in the near future which will fix this issue.
