### ISSUE TITLE
[dev.icinga.com #4100] Integrate exchange.icinga.org for packaging (and uploading), searching, installing, and updating modules

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#129]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/4100

**Created by elippmann on 2013-05-07 07:54:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2017-01-13 14:35:39 +00:00 (in Redmine)_

---

TBD.

**Comment by lippserd** [comment]
We'll implement a dedicated module for that in the future. I close this issue.
