### ISSUE TITLE
[dev.icinga.com #8189] Schema file is missing in the RPM package

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1295]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8189

**Created by gbeutner on 2015-01-12 14:17:50 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2015-01-16 16:13:57 +00:00_)
Target Version: _(none)_
Last Update: _2015-10-30 17:33:08 +00:00 (in Redmine)_

---

This causes the official Icinga 2 demo VM to fail:

    ==> default: Notice: /Stage[main]/Icingaweb2-internal-db-mysql/Exec[populate-icingaweb-mysql-db]/returns: sh: /usr/share/doc/icingaweb2-2.0.0/schema/mysql.schema.sql: No such file or directory
    ==> default: Notice: /Stage[main]/Icingaweb2-internal-db-mysql/Exec[populate-icingaweb-mysql-db]/returns: ERROR 1146 (42S02) at line 1: Table 'icingaweb.icingaweb_user' doesn't exist
    ==> default: Error: mysql -uicingaweb -picingaweb icingaweb < /usr/share/doc/icingaweb2-$(rpm -q icingaweb2 | cut -d'-' -f2)/schema/mysql.schema.sql; mysql -uicingaweb -picingaweb icingaweb -e "INSERT INTO icingaweb_user (name, active, password_hash) VALUES ('icingaadmin', 1, '\$1\$iQSrnmO9\$T3NVTu0zBkfuim4lWNRmH.');" returned 1 instead of one of [0]
    ==> default: Error: /Stage[main]/Icingaweb2-internal-db-mysql/Exec[populate-icingaweb-mysql-db]/returns: change from notrun to 0 failed: mysql -uicingaweb -picingaweb icingaweb < /usr/share/doc/icingaweb2-$(rpm -q icingaweb2 | cut -d'-' -f2)/schema/mysql.schema.sql; mysql -uicingaweb -picingaweb icingaweb -e "INSERT INTO icingaweb_user (name, active, password_hash) VALUES ('icingaadmin', 1, '\$1\$iQSrnmO9\$T3NVTu0zBkfuim4lWNRmH.');" returned 1 instead of one of [0]

**Comment by wutzkachel** [comment]
Try that:
yum install -q -y --setopt=tsflags='' icingaweb2
