### ISSUE TITLE
[dev.icinga.com #8194] Monitoring: Interpret performance data ranges (thresholds)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1298]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8194

**Created by mjentsch on 2015-01-13 09:07:02 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-07-05 15:27:31 +00:00 (in Redmine)_

---

Critical or Warning state of a perfdata set is currently only decided based on the value being smaller or bigger than the critical value and does not recognize '@' or '~' chars.

**Changesets**

_2016-04-26 14:26:06 +00:00_ by _aklimov_ 7c276a99f82b09d2cd503d338f3f2649e9ef76b7

    Implement ThresholdRange
    
    refs #8194

_2016-04-27 08:26:49 +00:00_ by _aklimov_ 7d27a079aaa0d5eb3e23814675225e768ee928dc

    ThresholdRange: trim() raw ranges
    
    refs #8194

_2016-04-27 08:30:02 +00:00_ by _aklimov_ dc6a25525134a49d86fafb76ceb70a0dcf466590

    ThresholdRange: use substr() instead of strpos() where more performant
    
    refs #8194

_2016-04-27 08:34:49 +00:00_ by _aklimov_ a0d62fdf3a685ca2f9eaaff462661654dfa1209b

    ThresholdRange: reword doc
    
    refs #8194

_2016-04-27 09:30:23 +00:00_ by _aklimov_ e76d65365704d3a1bb7e78bfe6888e46cfe701e7

    ThresholdRange::setInverted(): default to true
    
    refs #8194

_2016-04-27 09:35:44 +00:00_ by _aklimov_ f78b4ffe7424d00e9cb44a70c719239fbd540596

    Perfdata: simplify code design
    
    refs #8194

_2016-04-27 10:24:31 +00:00_ by _aklimov_ 73e404efef2afcc93e679e7b82f847a350b74d70

    ThresholdRange: trim(floatval()) -> floatval(trim())
    
    refs #8194

_2016-04-27 15:46:24 +00:00_ by _aklimov_ 1860a7c549ce2ba03cbfb055c738ff7ae632859e

    Perfdata: use ThresholdRange
    
    refs #8194

_2016-04-27 16:13:14 +00:00_ by _aklimov_ bb2a5b2d08ea818c1af1129fa3b50c6656b7504d

    Perfdata: print warn and crit human-readable if the start is -∞
    
    refs #8194

_2016-04-29 08:33:26 +00:00_ by _aklimov_ c0d33eaa2a30823e7140781b1b5717861b6a21a4

    ThresholdRange::fromString(): default to -∞:∞
    
    refs #8194

_2016-04-29 08:50:21 +00:00_ by _aklimov_ 1e4c053bc2d7d09284fa8c1a836a0dd5d679f23c

    Preserve threshold ranges in ThresholdRange, not in Perfdata
    
    refs #8194

_2016-04-29 09:13:21 +00:00_ by _aklimov_ 795cc03552f8293f2c0e206a6eec599d32e3e3da

    ThresholdRange::fromString(): drop default
    
    refs #8194

_2016-04-29 09:14:00 +00:00_ by _aklimov_ 6a5f0f5292e0789789b87a8eb0e506fad9e17b5e

    ThresholdRange::fromString(): compare non-strictly
    
    refs #8194

_2016-04-29 09:21:43 +00:00_ by _aklimov_ 3f481f54f97ade5dacd0f9c293b16420a3519dfa

    Perfdata: return ThresholdRange from getWarningThreshold() and getCriticalThreshold()
    
    refs #8194

_2016-04-29 09:34:59 +00:00_ by _aklimov_ 65faf09351f499a5e9f8b9829f67db6a0f323ae3

    Perfdata::format(): handle ThresholdRanges
    
    refs #8194

---

**Relations**:

* relates [#8194](https://dev.icinga.com/issues/8194)
* relates [#8194](https://dev.icinga.com/issues/8194)
* duplicates [#6122](https://dev.icinga.com/issues/6122)
* duplicates [#6123](https://dev.icinga.com/issues/6123)
* duplicates [#8194](https://dev.icinga.com/issues/8194)
* duplicates [#8194](https://dev.icinga.com/issues/8194)
* blocks [#12885](https://dev.icinga.com/issues/12885)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
