### ISSUE TITLE
[dev.icinga.com #8270] Add SELinux policy for Icinga Web 2

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1328]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8270

**Created by gbeutner on 2015-01-24 10:18:27 +00:00**

Assignee: _elippmann_
Status: _Resolved_  (closed on _2016-12-13 12:50:03 +00:00_)
Target Version: _2.4.0_
Last Update: _2016-12-13 12:50:03 +00:00 (in Redmine)_

---

### Requirements

-   SELinux policy
-   Package(s)
-   Documentation

### Original description

The install wizard tells me that the /etc/icingaweb2 directory is not writable:

    The current configuration directory is not writable: /etc/icingaweb2

However, by using the command the wizard gave me earlier (icingacli setup config directory --group apache) I would expect that the directory permissions are set up properly.

**Changesets**

_2016-12-12 11:48:33 +00:00_ by _dgoetz_ e6cce0837664785c812712013ed002d89e737da8

    Add SELinux policy
    
    Signed-off-by: Eric Lippmann <eric.lippmann@icinga.com>
    
    refs #8270

_2016-12-12 13:26:14 +00:00_ by _elippmann_ 0bdf4040c50056a4d7da115dc9cab000a81cb162

    RPM: Add selinux subpackage
    
    refs #8270

_2016-12-13 11:31:51 +00:00_ by _elippmann_ eed1d7ab68de59eb274f1b0d0e3ba94b798226f8

    Merge branch 'feature/selinux-8270'
    
    resolves #8270

_2016-12-13 12:24:34 +00:00_ by _elippmann_ 6c039445f252248f3762f3a8b78f82ac7b925c1c

    RPM: Fix missing scriplets dependecies for selinux
    
    refs #8270

**Comment by aneesh121** [comment]
**To make your changes permanent :** 
semanage fcontext -a -t httpd_sys_rw_content_t '/etc/icingaweb2(/.*)?'
restorecon -RFvv /etc/icingaweb2
/usr/sbin/setsebool -P httpd_can_network_connect 1
