### ISSUE TITLE
[dev.icinga.com #8315] Use Icinga 2 API to expand commands

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1344]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8315

**Created by bsheqa on 2015-01-29 15:29:40 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-07 12:35:51 +00:00 (in Redmine)_

---

As the configuration of icinga2 is getting more and more complicated, it would be nice to see the resulting command of a service in the webinterface. This feature was available in icnga-classicui, but only works for icinga1.x

---

**Relations**:

* duplicates [#6879](https://dev.icinga.com/issues/6879)
* duplicates [#8315](https://dev.icinga.com/issues/8315)

**Comment by dnsmichi** [comment]
This requires certain changes.

- Make the API resource available
- Extend the queries and views
- Add proper permissions (i.e. to forbid the default non-admin user to view such command line, could contain sensitive information)

In the meantime you can use the REST API curl requests and the icinga2 console to extract the executed command line. This is described inside the docs.

https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/troubleshooting#checks-executed-command​

**Comment by craig** [comment]
Is anyone willing to work on this? It'd be extremely helpful to be able to easily copy & paste commands as it was possible before.

**Comment by baurmatt** [comment]
I've build a simple bash script for this:

```
response=$(curl "https://icinga2-master.example.org:5665/v1/objects/services/${host_name}!${service_name}" \
     --insecure --silent \
     --user "${user}:${password}" \
     --header "Accept: application/json" \
     --request GET)

echo $response | jq -r '.results[0].attrs.last_check_result.command'
```

Perhaps this helps for the implementation.

**Comment by dnsmichi** [comment]
As mentioned before, this requires the REST API resource being available with #3035

**Comment by Thomas-Gelf** [comment]
In case you're using the Icinga Director, it hooks into the monitoring module and provides command expansion as follows:

![Icinga Director Command Expansion](https://user-images.githubusercontent.com/553008/35269452-55a1a73c-002c-11e8-9b0a-f887a5acc250.png)

This also works fine for objects not created by the Director. Using the Director is no requirement for this, but you need to enable it and to go once through the initial Connection setup/kickstart wizard. Inspected objects might contain sensitive information, so this feature is available only to users which have been granted the `director/inspect` permission.

Cheers,
Thomas

**Comment by lippserd** [comment]
This issue is kind of overrun by time. Icinga DB and the new monitoring module will provide this information. Further, there is the Director with its inspect functionality
