### ISSUE TITLE
[dev.icinga.com #8357] Paged list inputs / Autocomplete dropdowns

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1362]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8357

**Created by jmeyer on 2015-02-04 14:06:30 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:51 +00:00 (in Redmine)_

---

In case a list control of a form contains a very high amount of entries, such as the ldap-user selection in the setup wizard the required time for its validation is unacceptable.

We should provide a generic list input with paging capability or adjust Zend's default appropriately.

---

**Relations**:

* blocks [#9052](https://dev.icinga.com/issues/9052)

**Comment by lippserd** [comment]
Moved to #3416.
