### ISSUE TITLE
[dev.icinga.com #8431] Doc module should respect README.md if available

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1388]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8431

**Created by tgelf on 2015-02-12 17:29:25 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-06-29 15:22:19 +00:00 (in Redmine)_

---

Helps avoiding redundant documentation. IMHO if README is given this should be where documentation starts.

@lippser: we discussed this before, so I'll trustfully assign it to you ;-)

Cheers,
Thomas

---

**Parent Task:** [#7153](https://dev.icinga.com/issues/7153)

**Comment by lippserd** [comment]
Moved to Icinga/icingaweb2-module-doc#4
