### ISSUE TITLE
[dev.icinga.com #8539] Document Gravatar integration for the contact views

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1410]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8539

**Created by ifish on 2015-02-25 14:09:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-06-29 14:47:40 +00:00 (in Redmine)_

---

At the contacts in icingaweb2, gravatars are usable, but there's no documentation about it.

---

**Parent Task:** [#7153](https://dev.icinga.com/issues/7153)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
