### ISSUE TITLE
[dev.icinga.com #8584] Provide a "Select all" link in the monitoring list views

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1415]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8584

**Created by mjentsch on 2015-03-03 14:38:37 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-20 15:20:38 +00:00 (in Redmine)_

---

When in list view, it should be possible to select all hosts/services in the list to perform actions on them. This was already implemented some time ago but got removed again.

Note: This feature was also requested by some people during the last Webinar, and I agree that this would be a nice feature.

---

**Relations**:

* blocks [#8584](https://dev.icinga.com/issues/8584)

**Comment by lippserd** [comment]
I close this as duplicate of #2344 because there is a pending PR.
