### ISSUE TITLE
[dev.icinga.com #8595] Filter hosts and services by notification users and notification groups

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1418]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8595

**Created by mjentsch on 2015-03-04 11:51:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-08-14 13:31:21 +00:00 (in Redmine)_

---

A user wants to be able to see a list of hosts and services he gets notified about. To achieve this, we need some filter column that can select hosts and services based on the attached contacts.

This might also be useful in other places, like the detail view of the contact.

---

**Relations**:

* relates [#9548](https://dev.icinga.com/issues/9548)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
