### ISSUE TITLE
[dev.icinga.com #8609] Services are sometimes not properly rendered in the service grid

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1426]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8609

**Created by Konne on 2015-03-05 10:53:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-06-30 07:30:07 +00:00 (in Redmine)_

---

Some services are not properly displayed within the service grid. instead they are displayed at the right side (as shown in the screenshot).
The problem occurs in version "IcingaWeb2 2.0.0-1.beta2.el7.centos" as well as in the gitmaster-version from "3.3.2015, noon".

**Attachments**

* [bug](https://dev.icinga.com/attachments/download/2293/bug) Konne - _2015-03-05 10:38:05 +00:00_ - _the two checks are "disk" and "swap". they are configured at node1_

---

**Parent Task:** [#5543](https://dev.icinga.com/issues/5543)

**Comment by lippserd** [comment]
Should be fixed. If not, please open a new issue.
