### ISSUE TITLE
[dev.icinga.com #8640] Customvar-based tactical overview as in Icinga-web 1.x

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1444]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8640

**Created by tgelf on 2015-03-09 08:06:04 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-11 07:45:57 +00:00 (in Redmine)_

---

I guess we need some filter-like construct to control custom grouping logic. Would also be great for Service Grid and similar.

Best,
Thomas

**Comment by lippserd** [comment]
We have the cube module now for this.
