### ISSUE TITLE
[dev.icinga.com #8653] Load avatar from LDAP

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1452]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8653

**Created by dgoetz on 2015-03-09 12:26:50 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-11 07:40:39 +00:00 (in Redmine)_

---

Instead of providing only gravatar as image provider, storing an image in LDAP is also possible. In this way also the dependency on an external resource for this feature is removed.

Typically jpegPhoto attribute is used, but also others are possible, so please make it configurable.

Bonus would be if upload would also work, if the bind user or connected user has this permissions.

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
