### ISSUE TITLE
[dev.icinga.com #8698] Allow users to build their own packages

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1463]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8698

**Created by tgelf on 2015-03-12 08:38:55 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-04-02 10:54:33 +00:00 (in Redmine)_

---

We should provide everything one needs to build simple packages for dpkg- and rpm-based distros. We should also provide a short documentation explaining how to do so (like ln -s packages/debian; dpkg-buildpackage...). Those build helpers should not be used for our official packages in distributions as they might look different.

Cheers,
Thomas

**Comment by lippserd** [comment]
The icinga-packaging repo has all relevant stuff for building own packages. I close this one.
