### ISSUE TITLE
[dev.icinga.com #8708] LDAP resource after successful discovery is misleading

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1471]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8708

**Created by tgelf on 2015-03-12 10:00:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:52 +00:00 (in Redmine)_

---

Those two steps could IMO easily be combined in a single one.

Cheers,
Thomas

**Changesets**

_2015-03-12 15:14:58 +00:00_ by _jmeyer_ b37757ca6e096f510b54da46bad9de7c1a91c74b

    Disable the LdapDiscoveryConfirmPage
    
    As long as the discovery code does not report multiple results, as it should,
    actually, it's useless to demand the user to confirm the result.
    
    resolves #8602
    refs #8725
    refs #8708

---

**Relations**:

* blocks [#8708](https://dev.icinga.com/issues/8708)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
