### ISSUE TITLE
[dev.icinga.com #8725] LDAP discovery does not report multiple results

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1479]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8725

**Created by jmeyer on 2015-03-12 15:14:00 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-11 07:40:41 +00:00 (in Redmine)_

---

The intention of having a LDAP discovery feature was that in case a domain provides multiple services the user is able to choose a specific service instead of having the native fallback mechanism that is in effect otherwise. Currently the discovery does only provide the first result, intentionally skipping everything else.

**Changesets**

_2015-03-12 15:14:58 +00:00_ by _jmeyer_ b37757ca6e096f510b54da46bad9de7c1a91c74b

    Disable the LdapDiscoveryConfirmPage
    
    As long as the discovery code does not report multiple results, as it should,
    actually, it's useless to demand the user to confirm the result.
    
    resolves #8602
    refs #8725
    refs #8708

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
