### ISSUE TITLE
[dev.icinga.com #8732] Make dashlet width use the available space

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1484]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8732

**Created by Trefex on 2015-03-13 08:49:54 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-06-30 07:38:30 +00:00 (in Redmine)_

---

Hi,

It would be great if a Dashlet, like the Service Grid, could use all available space in the width when it is the only Dashlet on the Dashboard.
Furthermore, this could be such that if there are two Dashlets, they use 50% of the screen, if there are 3, 33%, and if there are more, multiple rows.

I believe right now the Dashlet is by default set to 33% width, regardless of the number of Dashlets that are active.

Thanks,

---

**Parent Task:** [#5543](https://dev.icinga.com/issues/5543)

**Comment by lippserd** [comment]
Should be fixed. If not, please open a new issue.
