### ISSUE TITLE
[dev.icinga.com #8789] Document how to add custom documentation directories

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1496]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8789

**Created by dgoetz on 2015-03-18 08:55:32 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-06-29 14:47:53 +00:00 (in Redmine)_

---

Can we make the doc module configurable (using GUI, Files and CLI) to add custom documentation?

One use case would be to add Icinga 2 documentation, another for documentation of your own environment without needing another web application.

And of course this needs some documentation what is required for this kind of documentation (structure, file permissions, ...).

---

**Parent Task:** [#7153](https://dev.icinga.com/issues/7153)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
