### ISSUE TITLE
[dev.icinga.com #8818] Customize dashboard items order

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1498]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8818

**Created by mfriedrich on 2015-03-19 15:11:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-03-15 15:53:17 +00:00 (in Redmine)_

---

Feedback from CeBit this week:

Similar to the search providers, but more in a static way when organizing the dashboard itself in the settings tab. I could think of "move up" and "move down" highlighting icons when editing the dashboard entries.

---

**Relations**:

* relates [#8818](https://dev.icinga.com/issues/8818)
* duplicates [#8818](https://dev.icinga.com/issues/8818)

**Comment by lippserd** [comment]
Closed as duplicate of #3398.
