### ISSUE TITLE
[dev.icinga.com #8876] Allow module developers to implement new/custom command transports

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1508]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8876

**Created by elippmann on 2015-03-27 08:17:54 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-11 07:40:42 +00:00 (in Redmine)_

---

As a module developer, I want to implement custom command transports because the monitoring module does not provide the command transport I need.

---

**Relations**:

* relates [#8876](https://dev.icinga.com/issues/8876)
* relates [#8876](https://dev.icinga.com/issues/8876)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
