### ISSUE TITLE
[dev.icinga.com #8878] Generate one hash per session for CSRF prevention

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1510]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8878

**Created by elippmann on 2015-03-27 09:21:27 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-11 07:40:42 +00:00 (in Redmine)_

---

tgelf wrote:
> \* I guess sha256(1|<session id>) is a valid token. Always.
> \* As I'm free to choose a seed, relaxing this to generating one single token per session would have the same level of security.
> \* While this still isn't bad one might ask what the extra effort of generating multiple hashes each time the "detail view" gets refreshed is useful for

---

**Relations**:

* relates [#5626](https://dev.icinga.com/issues/5626)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
