### ISSUE TITLE
[dev.icinga.com #8882] Notification view is missing the notification type, reason and command; and comment (if any)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1511]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8882

**Created by elippmann on 2015-03-27 12:16:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-10-04 12:22:01 +00:00 (in Redmine)_

---

The notification view currently only display problem notifications. Maybe it displays acknowledgement notifications too but I can't differ between problem and acknowledgement notifications because the notification type is not displayed. Further the notification command and comment (if any) is not displayed too.

All types of notification, the notification type, command and comment (if any) must be displayed. The notification view also has very limited filter functionality which will be addressed in a separate issue.

**Changesets**

_2015-05-20 14:45:03 +00:00_ by _aklimov_ ac6a1df7f5011b3a0d88c95b002bf66967dd43a7

    Make column `notification_reason' selectable
    
    refs #8882

_2015-05-20 15:17:58 +00:00_ by _aklimov_ 4e230150b1fef1fa95678005bab9f8397fb7b939

    Display the hosts/services' state names in the notifications about them
    
    refs #8882

_2015-05-21 10:21:01 +00:00_ by _aklimov_ 97c81906773b4b791f9a31ffe61aaddf63518e94

    Show a notification's reason
    
    refs #8882

---

**Relations**:

* relates [#8882](https://dev.icinga.com/issues/8882)
* relates [#8882](https://dev.icinga.com/issues/8882)
* duplicates [#8882](https://dev.icinga.com/issues/8882)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
