### ISSUE TITLE
[dev.icinga.com #8883] Filter notifications

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1512]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8883

**Created by elippmann on 2015-03-27 12:23:57 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:54 +00:00 (in Redmine)_

---

Filter functionality for the notification view is missing.

I'd like too see quick filters for:

-   Show only host or service notifications
-   Time range
-   Notification type

The filter editor has to be added too of course.

---

**Relations**:

* relates [#8882](https://dev.icinga.com/issues/8882)
* relates [#8883](https://dev.icinga.com/issues/8883)

**Comment by lippserd** [comment]
Filter editor has been added to the view. I close this issue.
