### ISSUE TITLE
[dev.icinga.com #8909] Quick filters and filter editor for the Service Grid

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1519]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8909

**Created by elippmann on 2015-03-30 15:01:08 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-05-27 08:15:23 +00:00 (in Redmine)_

---

TDB.

---

**Relations**:

* relates [#8909](https://dev.icinga.com/issues/8909)
* relates [#8909](https://dev.icinga.com/issues/8909)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
