### ISSUE TITLE
[dev.icinga.com #8910] RPM: Allow to define the PHP version

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1520]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8910

**Created by elippmann on 2015-03-30 15:11:43 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-07-15 12:49:11 +00:00 (in Redmine)_

---

Amazon Linux does provide php and php55 package. If php55 is installed on the system, Icinga Web 2 related dependencies are broken. Amazon Linux users should be allowed to define the used PHP version.

**Changesets**

_2015-05-21 15:03:51 +00:00_ by _aklimov_ a74ffb076d0f903ec47365f8e49fcee8285239c9

    Allow to define the PHP version included in the package name
    
    refs #8910

_2015-05-21 16:05:55 +00:00_ by _aklimov_ 693debee89fd91b48002bbac24210059fc8b1adf

    Allow to define the PHP version included in the package name
    
    refs #8910

---

**Relations**:

* relates [#8910](https://dev.icinga.com/issues/8910)
* relates [#8910](https://dev.icinga.com/issues/8910)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
