### ISSUE TITLE
[dev.icinga.com #8937] Render timestamps human readable in the filter "overview" and editor

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1536]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8937

**Created by elippmann on 2015-04-01 14:43:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-05-27 08:15:00 +00:00 (in Redmine)_

---

**Attachments**

* [Screen Shot 2015-04-01 at 16.42.45.png](https://dev.icinga.com/attachments/download/2374/Screen%20Shot%202015-04-01%20at%2016.42.45.png) elippmann - _2015-04-01 14:43:11 +00:00_

---

**Relations**:

* relates [#8937](https://dev.icinga.com/issues/8937)

**Comment by lippserd** [comment]
Hi,

This issue will be fixed as part of #3631.

Best,
Eric
