### ISSUE TITLE
[dev.icinga.com #8939] Crosswise mouseover highlighting in the service grid

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1538]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8939

**Created by elippmann on 2015-04-01 14:56:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:54 +00:00 (in Redmine)_

---

In order to make it easier for users to follow down columns and across rows in the service grid we should implemented crosswise mouseover highlighting to create temporary zebra striping.

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
