### ISSUE TITLE
[dev.icinga.com #8961] Create role from this filter

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1557]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8961

**Created by elippmann on 2015-04-02 08:46:34 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:55 +00:00 (in Redmine)_

---

When filtering a view it should be possible to directly create a role from the filter created.

**Comment by nilmerg** [comment]
We should think of this as part of #4094.
