### ISSUE TITLE
[dev.icinga.com #8971] Refresh permissions and restrictions automatically

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1565]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8971

**Created by elippmann on 2015-04-02 09:07:15 +00:00**

Assignee: _elippmann_
Status: _Feedback_ 
Target Version: _Backlog_
Last Update: _2016-12-20 14:54:35 +00:00 (in Redmine)_

---

Currently one has to log out and log in again before new/changed permissions and restrictions take effect.

**Changesets**

_2016-12-20 14:49:32 +00:00_ by _(unknown)_ 07d00bce5b576a821c29af0cf3ee4e8f2ef5789d

    Refresh permissions and restrictions automatically
    
    refs #8971

**Comment by Al2Klimov** [comment]
1. Permissions and restrictions may depend on group memberships as well, but I'm afraid reloading them **every** request would be too expensive, would it?
2. What about reloading all these things only e.g. every minute? (I can already imagine how to implement that)
3. @Thomas-Gelf suggested application-state.

**Comment by lippserd** [comment]
Closing in favor of #3555.
