### ISSUE TITLE
[dev.icinga.com #8977] Tactical overview by host and service groups as in Icinga Web 1.x

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1569]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8977

**Created by elippmann on 2015-04-02 10:26:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-04-02 10:26:50 +00:00 (in Redmine)_

---

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
