### ISSUE TITLE
[dev.icinga.com #8982] Customize command transport order

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1573]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8982

**Created by elippmann on 2015-04-02 11:12:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-11 07:40:45 +00:00 (in Redmine)_

---

Maybe obsolete with monitoring environments.

**Comment by lippserd** [comment]
Fixed in the current master.
