### ISSUE TITLE
[dev.icinga.com #9005] Allow to define the session name as configuration setting

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1582]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9005

**Created by mfriedrich on 2015-04-07 11:55:44 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:56 +00:00 (in Redmine)_

---

This would solve the issue with different ports but same ip address when storing session cookies.

Should be implemented as local configuration setting and then applied to the cluster vagrant boxes.

---

**Relations**:

* relates [#8778](https://dev.icinga.com/issues/8778)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
