### ISSUE TITLE
[dev.icinga.com #9035] Improve layout of deleted comments

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1597]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9035

**Created by jmeyer on 2015-04-09 11:29:21 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-04-09 11:29:21 +00:00 (in Redmine)_

---

The way how deleted comments are shown to the user provides **a lot** of space for improvements: monitoring/list/eventhistory?type=\*deleted

**Comment by lippserd** [comment]
Fixed.
