### ISSUE TITLE
[dev.icinga.com #9052] Setup wizard attempts to load entire LDAP user database

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1602]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9052

**Created by mcobden on 2015-04-13 12:13:20 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:57 +00:00 (in Redmine)_

---

For us, this results in gateway timeouts from nginx, because the requests takes ages, and might even run out of memory.

I've managed to progress by adding a filter, and constraining to a smaller set of users.

There was no indication that this was the cause, I was following a hunch, so probably some people who hit this will not guess how to get past it.

---

**Relations**:

* relates [#8704](https://dev.icinga.com/issues/8704)
* blocks [#9052](https://dev.icinga.com/issues/9052)

**Comment by lippserd** [comment]
Should be fixed. If not, please open a new issue.
