### ISSUE TITLE
[dev.icinga.com #9097] Refresh button sometime not shown

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1609]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9097

**Created by MarkusR on 2015-04-17 13:18:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-07-03 14:50:52 +00:00 (in Redmine)_

---

I'm trying the Icinga Web 2 Beta 2.

When changing the width of browser window (tested in Chrome and Firefox) sometimes the refresh button is not shown anymore.

**Attachments**

* [not_showing.png](https://dev.icinga.com/attachments/download/2406/not_showing.png) MarkusR - _2015-04-17 13:14:39 +00:00_
* [showing.png](https://dev.icinga.com/attachments/download/2407/showing.png) MarkusR - _2015-04-17 13:14:39 +00:00_

---

**Parent Task:** [#5543](https://dev.icinga.com/issues/5543)

**Comment by lippserd** [comment]
Should be fixed. If not, please open a new issue.
