### ISSUE TITLE
[dev.icinga.com #4138] Small inline charts for the hosts list and the services list

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#161]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/4138

**Created by elippmann on 2013-05-07 09:43:28 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-03-27 13:14:00 +00:00 (in Redmine)_

---

As a user, I want to see small inline charts for the hosts list and the services list for quickly analyzing trends.

**Comment by chucker** [comment]
May I ask why this is marked won't fix — the pie charts are pretty cool, and a line/area/etc. chart for recent trend data would seem quite useful?
