### ISSUE TITLE
[dev.icinga.com #9219] Show top-tray notifications for monitoring backend availability problems

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1638]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9219

**Created by afuhr on 2015-05-04 09:25:38 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-09 14:18:45 +00:00 (in Redmine)_

---

As a user, I want to see a top tray notification, if the monitoring backend is not available.

At the moment it is not so easy to implement this, in case we do not provide persistent notifications on response.

---

**Relations**:

* relates [#4139](https://dev.icinga.com/issues/4139)

**Comment by lippserd** [comment]
Close this as duplicate of #2835
