### ISSUE TITLE
[dev.icinga.com #9225] Protect custom variables based on roles

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1643]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9225

**Created by Anonymous on 2015-05-05 20:10:38 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:58 +00:00 (in Redmine)_

---

Under IcingaWeb2 -&gt; System -&gt; Modules -&gt; Monitoring -&gt; Security, there is available an option to setup protected custom variables.

This feature request is to enable on a per ROLE basis showing anything under "object.vars" on an object(regardless if host, service etc), so its possible to hide away configuration information that is sensitive to must users but not all.

**Comment by lippserd** [comment]
This feature has already been implemented.
