### ISSUE TITLE
[dev.icinga.com #9241] Filter hosts and services by combined group memberships, e.g. servicegroup=(a&b)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1649]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9241

**Created by PowellEB on 2015-05-07 14:02:27 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2015-05-07 14:44:19 +00:00_)
Target Version: _Backlog_
Last Update: _2016-12-08 10:33:54 +00:00 (in Redmine)_

---

We have servers assigned to hostgroups (Customer XXX, DB XXX, XXX Level, ......)

a single hostgroup filter works (example):
.....hosts?hostgroup\_name=prd\_level&modifyFilter=1

a multiple hostgroup filter does not work (example):
....hosts?hostgroup\_name=prd\_level&hostgroup\_name=windows-servers&modifyFilter=1 **"List Production Level servers that are Windows"**

**Comment by nilmerg** [comment]
Since that's a legacy issue I'll close this in favor of #2934.
