### ISSUE TITLE
[dev.icinga.com #9281] Problem with Icingaweb 2 after PHP Upgrade 5.6.8 -> 5.6.9

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1658]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9281

**Created by mixmegapol on 2015-05-16 20:00:27 +00:00**

Assignee: _mjentsch_
Status: _Resolved_  (closed on _2015-06-16 15:10:03 +00:00_)
Target Version: _2.0.0-rc1_
Last Update: _2015-06-16 18:13:13 +00:00 (in Redmine)_

---

Hello all

I have RHEL 7, icinga2, icingaweb2, pgsql9.4 and php5.6.8 running.
Yesterday I upgraded php 5.6.8 to 5.6.9, since then I have problems with icingaweb2.

Output:
Server error: The use statement with non-compound name 'Exception' has no effect

The use statement with non-compound name 'Exception' has no effect

    #0 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(352): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'The use stateme...', '/usr/share/icin...', 4, Array)
    #1 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(352): Zend_Controller_Dispatcher_Standard::loadClass()
    #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(271): Zend_Controller_Dispatcher_Standard->loadClass('DashboardContro...')
    #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #4 /usr/share/php/Icinga/Application/Web.php(154): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #5 /usr/share/php/Icinga/Application/webrouter.php(111): Icinga\Application\Web->dispatch()
    #6 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
    #7 {main}

Could you please investigate in that?

Kind regards
Daniel

**Attachments**

* [Auswahl_055.png](https://dev.icinga.com/attachments/download/2513/Auswahl_055.png) mfriedrich - _2015-06-16 18:13:05 +00:00_

**Changesets**

_2015-06-02 14:41:33 +00:00_ by _(unknown)_ 00ae69a694e846596bc7c179ec3867da1cf8d4f9

    Fix PHP 5.6.9 error: The use statement with non-compound name 'Exception' has no effect
    
    refs #9281

_2015-06-16 14:10:52 +00:00_ by _mjentsch_ 5bf7bbdb8b5fa4198de611acc1cc5d47e12f3599

    Remove unneeded use statements from global namespaces
    
    Use statements on global classes from the global namespace don't have any effect, prevent warnings from being displayed in php versions >= 5.6.9 and version >= 5.5.25.
    
    refs #9281

_2015-06-16 15:06:47 +00:00_ by _mjentsch_ 5b8c308679d659a66c058f5fcfecdbbac485e93a

    Merge branch 'bugfix/use-statement-error-9281'
    
    fixes #9281

**Comment by aflatto** [comment]
Am getting this issue now , using the icinga2-ansible playbook to install and configure the server 
 ubuntu@ip-172-31-39-235:~$ dpkg -l |grep php
ii  php                                  1:7.0+35ubuntu6                     all          server-side, HTML-embedded scripting language (default)
ii  php-common                           1:35ubuntu6                         all          Common files for PHP packages
ii  php-dompdf                           0.6.1+dfsg-2ubuntu1                 all          HTML to PDF converter
ii  php-font-lib                         0.2.2+dfsg-2build1                  all          read, parse, export and make subsets of different fonts
ii  php-gd                               1:7.0+35ubuntu6                     all          GD module for PHP [default]
ii  php-htmlpurifier                     4.7.0-1build1                       all          Standards-compliant HTML filter
ii  php-icinga                           2.4.1-1~ppa1604+1                   all          PHP library to communicate with and use Icinga
ii  php-imagick                          3.4.0~rc6-1ubuntu3                  amd64        Provides a wrapper to the ImageMagick library
ii  php-intl                             1:7.0+35ubuntu6                     all          Internationalisation module for PHP [default]
ii  php-ldap                             1:7.0+35ubuntu6                     all          LDAP module for PHP [default]
ii  php-mysql                            1:7.0+35ubuntu6                     all          MySQL module for PHP [default]
ii  php-xml                              1:7.0+35ubuntu6                     all          DOM, SimpleXML, WDDX, XML, and XSL module for PHP [default]
ii  php7.0                               7.0.13-0ubuntu0.16.04.1             all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.0-cli                           7.0.13-0ubuntu0.16.04.1             amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                        7.0.13-0ubuntu0.16.04.1             amd64        documentation, examples and common module for PHP
ii  php7.0-fpm                           7.0.13-0ubuntu0.16.04.1             amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.0-gd                            7.0.13-0ubuntu0.16.04.1             amd64        GD module for PHP
ii  php7.0-intl                          7.0.13-0ubuntu0.16.04.1             amd64        Internationalisation module for PHP
ii  php7.0-json                          7.0.13-0ubuntu0.16.04.1             amd64        JSON module for PHP
ii  php7.0-ldap                          7.0.13-0ubuntu0.16.04.1             amd64        LDAP module for PHP
ii  php7.0-mysql                         7.0.13-0ubuntu0.16.04.1             amd64        MySQL module for PHP
ii  php7.0-opcache                       7.0.13-0ubuntu0.16.04.1             amd64        Zend OpCache module for PHP
ii  php7.0-readline                      7.0.13-0ubuntu0.16.04.1             amd64        readline module for PHP
ii  php7.0-xml                           7.0.13-0ubuntu0.16.04.1             amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ubuntu@ip-172-31-39-235:~$ dpkg -l |grep icinga
ii  icinga2                              2.6.2-1~ppa1~xenial1                amd64        host and network monitoring system
ii  icinga2-bin                          2.6.2-1~ppa1~xenial1                amd64        host and network monitoring system - daemon
ii  icinga2-common                       2.6.2-1~ppa1~xenial1                all          host and network monitoring system - common files
ii  icinga2-ido-mysql                    2.6.2-1~ppa1~xenial1                amd64        host and network monitoring system - MySQL support
ii  icingacli                            2.4.1-1~ppa1604+1                   all          simple CLI tool for Icingaweb2 and its modules
ii  icingaweb2                           2.4.1-1~ppa1604+1                   all          simple and responsive web interface for Icinga
ii  icingaweb2-common                    2.4.1-1~ppa1604+1                   all          simple and responsive web interface for Icinga - common files
ii  icingaweb2-module-doc                2.4.1-1~ppa1604+1                   all          simple and responsive web interface for Icinga - documentation module
ii  icingaweb2-module-monitoring         2.4.1-1~ppa1604+1                   all          simple and responsive web interface for Icinga - monitoring module
ii  libicinga2                           2.6.2-1~ppa1~xenial1                amd64        host and network monitoring system - internal libraries
ii  php-icinga                           2.4.1-1~ppa1604+1                   all          PHP library to communicate with and use Icinga

**Comment by dnsmichi** [comment]
Hi, please open a new issue :)
