### ISSUE TITLE
[dev.icinga.com #9294] Provide default icon set for icon_image

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1663]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9294

**Created by mjentsch on 2015-05-19 15:27:25 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:59 +00:00 (in Redmine)_

---

We could try to provide a default icon set (device types, operating systems...), "flat" and as an icon font would of course be fantastic.

---

**Relations**:

* relates [#8665](https://dev.icinga.com/issues/8665)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
