### ISSUE TITLE
[dev.icinga.com #9339] Take notes into account when searching for host and service names

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1685]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9339

**Created by arcade on 2015-05-29 15:12:43 +00:00**

Assignee: _elippmann_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-06 21:19:01 +00:00 (in Redmine)_

---

I'd like to extend https://dev.icinga.org/issues/8241 with host/service notes.

We've a lot of information in this notes and for quick access it would be nice to search for them too. Sometimes you just know some keywords in this notes and not the actual service/host name and so users can't find their stuff.

**Attachments**

* [0001-Take-notes-into-account.patch](https://dev.icinga.com/attachments/download/2499/0001-Take-notes-into-account.patch) arcade - _2015-06-05 09:38:48 +00:00_

---

**Parent Task:** [#9479](https://dev.icinga.com/issues/9479)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue. PR with the patch plus a configuration option is welcome.
