### ISSUE TITLE
[dev.icinga.com #9358] Service list PDF export is broken

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1698]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9358

**Created by tgelf on 2015-06-02 16:51:12 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-07-15 12:33:33 +00:00 (in Redmine)_

---

Not sure, but seems to be related to pie charts. Did a few rough tests, beta1 works fine but shows not pie charts, since beta2 we get "Maximum function nesting level of '100' reached, aborting!". Had no problem when exporting lists without pie charts from current master.

Cheers,
Thomas

---

**Parent Task:** [#9359](https://dev.icinga.com/issues/9359)

**Comment by lippserd** [comment]
Should be fixed.
