### ISSUE TITLE
[dev.icinga.com #9359] PDF export needs some love

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1699]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9359

**Created by tgelf on 2015-06-02 16:51:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:11:00 +00:00 (in Redmine)_

---

We might add some more PDF-related styling to make them look better.

Best,
Thomas

---

**Subtasks**:

* [Bug 9358 - Service list PDF export is broken](https://dev.icinga.com/issues/9358)
* [Bug 9385 - Unreachable PDF export action in documentation module](https://dev.icinga.com/issues/9385)
* [Bug 9580 - Exporting PDF fails with Fatal error: Uncaught exepction...](https://dev.icinga.com/issues/9580)

**Comment by lippserd** [comment]
Moved to: https://github.com/Icinga/icingaweb2-module-pdfexport/issues/2
