### ISSUE TITLE
[dev.icinga.com #9368] Collapse & expand columns

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1703]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9368

**Created by ABauer on 2015-06-03 18:20:28 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-10-30 14:25:29 +00:00 (in Redmine)_

---

When viewing the icinga2 documentation on a device like a MacBookAir 13" (display resolution: 1440x900), most of the space used is for the first and second column, but the most intresting thing to read is the third coulmn.

I know that it is possible to close the mid column and the third column will become bigger. But once if done this, I cannot open the second one again.

In my opinion it would be helpful to be able to scale those columns manually or be able to close and open the mid column with one click.

Please consider implementing this.

Cheers
Andreas

**Attachments**

* [icingaweb2-doku-ansicht.jpg](https://dev.icinga.com/attachments/download/2496/icingaweb2-doku-ansicht.jpg) ABauer - _2015-06-03 18:13:55 +00:00_

---

**Parent Task:** [#5543](https://dev.icinga.com/issues/5543)

**Comment by lippserd** [comment]
Moved to #3416.
