### ISSUE TITLE
Store dashboards in database instead of local files (useful for HA environments)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1704]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9371

**Created by rhillmann on 2015-06-05 07:47:05 +00:00**

Customized dashboard should be stored in a database instead of local files.
When setting up multilpe frontend servers, you need to sync the config files. Storing configs in the database prevents this behavior.

Related to #2209

**Comment by stefanandres** [comment]
This issue is 2 years old and prevents any real icingaweb2 clustering. Is there any plan to implement this?

**Comment by nilmerg** [comment]
Continues with #3809. Closed.
