### ISSUE TITLE
[dev.icinga.com #4149] Module specific user preferences

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#172]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/4149

**Created by jmosshammer on 2013-05-07 14:14:27 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:43 +00:00 (in Redmine)_

---

As a user, I want to change preferences provided by modules.

**Acceptance criteria:**

-   Each module may provide its own preferences
-   A user must be able to configure the preferences

---

**Relations**:

* relates [#4066](https://dev.icinga.com/issues/4066)

**Comment by lippserd** [comment]
This is a good idea still but we don't have any requirement for this issue at the moment.
