### ISSUE TITLE
[dev.icinga.com #9395] Visually summarize services to host

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1720]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9395

**Created by bsheqa on 2015-06-09 14:55:12 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-08-04 10:09:16 +00:00 (in Redmine)_

---

When displaying multiple services, like on the dashboard or the service overview, one can not say that more than one service belongs to one single host.

Currently services are displayed like this

`myServiceName on myHost
shortSrv on myHost
otherService on yourHost
thisIsALongServiceName on myHost`

I think that it would be a big visual improvement to group somehow services to hosts. It should be possible to see that multiple services belong to one host on the very first view.

I attached a screenshot that represents the issue.

**Attachments**

* [icingaweb2_service-to-host.png](https://dev.icinga.com/attachments/download/2503/icingaweb2_service-to-host.png) bsheqa - _2015-06-09 14:53:58 +00:00_

---

**Parent Task:** [#5543](https://dev.icinga.com/issues/5543)

**Relations**:

* duplicates [#9395](https://dev.icinga.com/issues/9395)

**Comment by lippserd** [comment]
Moved to #3416.
