### ISSUE TITLE
[dev.icinga.com #9424] Alert summary shows pagination, but it doesn't seem to have effect

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1731]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9424

**Created by tgelf on 2015-06-16 09:25:05 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2015-06-17 06:59:18 +00:00_)
Target Version: _Backlog_
Last Update: _2015-11-20 13:11:01 +00:00 (in Redmine)_

---

Cheers,
Thomas

**Comment by lippserd** [comment]
We removed the alert summary. I close this issue.
