### ISSUE TITLE
[dev.icinga.com #9433] Navigation: The menu item element should be toggled

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1736]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9433

**Created by afuhr on 2015-06-17 08:11:02 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-07-16 09:28:55 +00:00 (in Redmine)_

---

The menu item element in the navigation should be toggled when I click on it.

Acutally when I click on the System it is going open the included list, but when I click again on it, it should get closed.

---

**Parent Task:** [#5543](https://dev.icinga.com/issues/5543)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
