### ISSUE TITLE
[dev.icinga.com #9458] Filter: Support filtering for NULL

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1740]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9458

**Created by jmeyer on 2015-06-19 11:43:31 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:11:02 +00:00 (in Redmine)_

---

I'd like to filter for objects which have a particular attribute set or not set.

We're currently able to interpret **`[!]column`** which is the perfect candidate for this use case. The current use case however is to translate this to check whether an attribute is TRUE or NOT TRUE, which is, strictly speaking, wrong behavior. One is for example not able to filter explicitly for FALSE as **`!column`** will be translated to **`NOT (column = '1')`** (in SQL) instead of **`column = '0'`**. Sure, NOT TRUE is equivalent to FALSE most of the time, but I think we should swap this anyhow as explicit is...

So I propose the following change:

-   **`[!]column`** should be translated to e.g. **`column IS NULL`** and **`column IS NOT NULL`** for SQL
-   Filtering for TRUE and FALSE should be changed to **`column=1`** and **`column=0`**, respectively. (We may also introduce specific keywords 'true' and 'false' for this case, as 0 and 1 are only valid for SQL and I really doubt that one is naming a host or service "true" or "false"... (even LDAP utilizes 'true' and 'false'))

**Changesets**

_2015-06-19 12:08:32 +00:00_ by _jmeyer_ 5166ede38f1d9f3d228f6bbe1cf5f3241b6b19ff

    Fix that ghost groups are shown in the host- and servicegroup summary
    
    fixes #9454
    refs #9458

---

**Relations**:

* relates [#12299](https://dev.icinga.com/issues/12299)

**Comment by nilmerg** [comment]
Will not happen. We'll think of something else related to #4094.
