### ISSUE TITLE
[dev.icinga.com #9468] Menu: Documentation entry behaves weird

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1744]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9468

**Created by jmeyer on 2015-06-22 08:07:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-06-22 08:07:09 +00:00 (in Redmine)_

---

The menu entry pointing to the documentation is somehow unresponsive. Try the following:

-   Move your cursor over the menu entry which says "Documentation"
-   Click on it and **DO NOT** move your cursor in any way
-   Notice that the sub-entries are unfolded a few seconds later (or possibly faster, doesn't matter, go on)
-   Fold the menu entry again by clicking elsewhere
-   Now move your cursor again to the menu entry which says "Documentation"
-   Click on it and **move your cursor away**
-   Notice that the sub-entries are unfolded much faster than when staying with the cursor on the entry

This does not seem to be related how fast the popup for the sub-entries appears when hovering.

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
