### ISSUE TITLE
[dev.icinga.com #9479] Improve Search

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1748]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9479

**Created by bsheqa on 2015-06-23 14:29:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-09-21 09:36:19 +00:00 (in Redmine)_

---

The search in icingaweb2 is insufficient. I have 2 proposals which would improve the search significantly:

1)
Let the user create a query. Many other tools have this and if the query language is simple enough it is way faster than selecting filters in huge dropdowns. It's important that nearly anything must be searchable, even custamvars.
Example:
`"host:app* AND service:disk AND NOT service:"disk /data" AND service.customvar.dc:dc1"`
This would result in showing all hosts that begin with 'app\*'. It would also show all services that have 'disk' included but not those that have 'disk /data'. Only services that have the customvar 'dc' set to 'dc1' will be displayed.

2)
Another good improvement for the search is just by typing keywords. Those keywords are then searched in combination.
Example:
`app disk`
The result is all 'disk' checks on 'app' servers.

Best would be to implement both solutions.

---

**Subtasks**:

* [Feature 9659 - Configureable search dashlets](https://dev.icinga.com/issues/9659)
* [Feature 6690 - Support filter expressions for searching](https://dev.icinga.com/issues/6690)
* [Feature 9339 - Take notes into account when searching for host and service names](https://dev.icinga.com/issues/9339)
* [Feature 7281 - Enhance the default search behavior](https://dev.icinga.com/issues/7281)
* [Feature 10680 - Provide virtual output column for searching for host and service output](https://dev.icinga.com/issues/10680)

**Relations**:

* relates [#9479](https://dev.icinga.com/issues/9479)
* duplicates [#9479](https://dev.icinga.com/issues/9479)
* duplicates [#9479](https://dev.icinga.com/issues/9479)

**Comment by nilmerg** [comment]
Will be part of Icinga DB Web. See #4094 for details.
