### ISSUE TITLE
[dev.icinga.com #9482] Provide custom variable prettification as view helper

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1750]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9482

**Created by mfrosch on 2015-06-24 07:50:25 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-12 15:44:25 +00:00 (in Redmine)_

---

I found this code in modules/monitoring/library/Monitoring/Object/MonitoredObject.php

It might make sense to move that code to a template helper function, so that the original customvar names are kept in the internal data.

E.g. for usage by another module.

            $customvars = $query->getQuery()->fetchAll();
            foreach ($customvars as $name => $cv) {
                $name = ucwords(str_replace('_', ' ', strtolower($cv->varname)));
                if ($blacklistPattern && preg_match($blacklistPattern, $cv->varname)) {
                    $this->customvars[$name] = '***';
                } elseif ($cv->is_json) {
                    $this->customvars[$name] = json_decode($cv->varvalue);
                } else {
                    $this->customvars[$name] = $cv->varvalue;
                }
            }

**Comment by nilmerg** [comment]
We have such a *helper* in Icinga DB Web. Custom variable *prettification* also has been reduced with #3987, so I think we can close here.
