### ISSUE TITLE
[dev.icinga.com #9520] Form: Allow to define where to redirect after success

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1776]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9520

**Created by jmeyer on 2015-06-29 11:23:04 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:11:03 +00:00 (in Redmine)_

---

Usecase:

1.  Drop all resources
2.  Try to create a new monitoring backend (while having the permission to configure resources)
3.  Define a new (database) resource
4.  Get redirected back to create a new monitoring backend

It's the fourth step this request is about. Right now the user is displayed the backend list on the left and the resource list on the right after creating the resource.

**Comment by lippserd** [comment]
Afaik we have `Form::setRedirectUrl()`. If that's not sufficient, please create a new issue.
