### ISSUE TITLE
[dev.icinga.com #9566] Allow to collapse custom variables and performance data

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1796]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9566

**Created by teclogi on 2015-07-06 15:18:45 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-13 16:06:08 +00:00 (in Redmine)_

---

tgelf wrote:
> Performance data and Icinga2 customvars waste a lot of space. We should provided a collapsible control element with an optional default maximum height for such cases. I'm still unsure whether such element should provide two (opened/collapsed) or three (just 4 lines/fully opened/collapsed) states.

**Original description:**
The custom variables section on the web side is taking to much space especially when many variables are defined!
A user normally don´t need that information.
Maybe there is an option to hide / close the whole section.

**Changesets**

_2016-03-09 09:51:22 +00:00_ by _(unknown)_ 0648527d2b5205efa3141d9b030ea8aeae89856f

    Change collapse control label to "Collapse"
    
    refs #9566

_2016-03-09 09:53:18 +00:00_ by _(unknown)_ 7dd0b25d7f46d9c1f2ed2a5488afcfd7e3a9ee15

    Move custom-var heading out of collapsible container
    
    refs #9566

_2016-03-09 09:54:14 +00:00_ by _(unknown)_ ecfa71c2f61205e00b0fc76fd081f5290a30d17f

    CSS: Add class for collapsible container collapsed state
    
    refs #9566

_2016-06-03 13:46:13 +00:00_ by _(unknown)_ b8b8e83aa5c7845df7f2cf35c6bc1c499b25dbc0

    Change collapse control label to "Collapse"
    
    refs #9566

_2016-06-03 13:46:15 +00:00_ by _(unknown)_ 52262c530d98aa0b94a6b170d5ef294feca103ec

    Move custom-var heading out of collapsible container
    
    refs #9566

_2016-06-03 13:46:15 +00:00_ by _(unknown)_ 62b5911536139958ae54ba3f16cf8fc9533a6519

    CSS: Add class for collapsible container collapsed state
    
    refs #9566

_2016-06-06 07:48:28 +00:00_ by _(unknown)_ c9fca73395db152e60ee7201331674a2ca9316b9

    JS: Add collapsible container to perf-data
    
    refs #9566

_2016-06-06 07:48:35 +00:00_ by _elippmann_ f66f4770660c0d20d62b9b2759b1e992c97b5fb5

    Update labels for collapsible ghost control
    
    refs #9566

---

**Parent Task:** [#5543](https://dev.icinga.com/issues/5543)

**Comment by lippserd** [comment]
Moved to #3416.
