### ISSUE TITLE
[dev.icinga.com #9580] Exporting PDF fails with Fatal error: Uncaught exepction...

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1804]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9580

**Created by Kaino on 2015-07-07 23:15:37 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-10-26 18:14:57 +00:00 (in Redmine)_

---

OS: FreeBSD 10.1-RELEASE

Full Error message:

Fatal error: Uncaught exception 'ErrorException' with message 'DOMNode::cloneNode(): ID page-footer already defined' in /usr/local/www/icingaweb2/library/vendor/dompdf/include/frame\_decorator.cls.php:128 Stack trace: [\#0](https://dev.icinga.com/issues/0) \[internal function\]: Icinga\\Application\\ApplicationBootstrap~~<span style="text-align:right;">Icinga\\Application\\{closure}(2, 'DOMNode::cloneN...', '/usr/local/www/...', 128, Array) \#1 /usr/local/www/icingaweb2/library/vendor/dompdf/include/frame\_decorator.cls.php(128): DOMNode</span>~~&gt;cloneNode() [\#2](https://dev.icinga.com/issues/2) /usr/local/www/icingaweb2/library/vendor/dompdf/include/page\_frame\_reflower.cls.php(105): Frame\_Decorator~~<span style="text-align:right;">deep\_copy() \#3 /usr/local/www/icingaweb2/library/vendor/dompdf/include/frame\_decorator.cls.php(711): Page\_Frame\_Reflower</span>~~&gt;reflow(NULL) [\#4](https://dev.icinga.com/issues/4) /usr/local/www/icingaweb2/library/vendor/dompdf/include/dompdf.cls.php(949): Frame\_Decorator~~<span style="text-align:right;">reflow() \#5 /usr/local/www/icingaweb2/library/Icinga/File/Pdf.php(54): DOMPDF</span>~~&gt;render() [\#6](https://dev.icinga.com/issues/6) /usr/local/www/icingaweb2/library/Icinga/Web/Controller/ActionController.php(490): Icinga\\File\\Pdf-&gt;renderControllerAction(O in /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332

---

**Parent Task:** [#9359](https://dev.icinga.com/issues/9359)

**Comment by lippserd** [comment]
Should be fixed. If you still habe problems, please open a new issue.
