### ISSUE TITLE
[dev.icinga.com #9612] Document LDAP filter setting in authentication.md

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1822]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9612

**Created by elippmann on 2015-07-14 08:14:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-30 21:11:32 +00:00 (in Redmine)_

---

The LDAP filter setting is not yet documented. When adding documentation do not forget to mention the LDAP\_MATCHING\_RULE\_IN\_CHAIN matching rule OID for nested groups.

**Changesets**

_2015-09-01 21:17:03 +00:00_ by _(unknown)_ 029aeda164a7bdd7f2092f2216d7dcf9382cafc2

    Document filter option for LDAP/AD auth
    
    refs #9612
    
    Signed-off-by: Eric Lippmann <eric.lippmann@netways.de>

---

**Parent Task:** [#7153](https://dev.icinga.com/issues/7153)

**Relations**:

* relates [#9612](https://dev.icinga.com/issues/9612)
* duplicates [#9612](https://dev.icinga.com/issues/9612)
* duplicates [#9612](https://dev.icinga.com/issues/9612)

**Comment by lippserd** [comment]
Simple example has been added to the documentation though it lacks the LDAP_MATCHING_RULE_IN_CHAIN option. If this is a missing piece for you, please open a new issue.
