### ISSUE TITLE
[dev.icinga.com #9648] Document how to integrate Web 2 into NagVis

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1841]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9648

**Created by elippmann on 2015-07-16 09:45:21 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-07-23 11:25:46 +00:00 (in Redmine)_

---

NagVis configuration (**untested**):

    [paths]
    ...
    htmlcgi="/icingaweb2/monitoring“

    [defaults]
    ...
    urltarget="_parent"
    hosturl="[htmlcgi]/host/show?host=[host_name]"
    hostgroupurl="[htmlcgi]/list/hosts?hostgroup=[hostgroup_name]"
    serviceurl="[htmlcgi]/service/show?host=[host_name]&service=[service_description]"
    servicegroupurl="[htmlcgi]/list/services?servicegroup=[servicegroup_name]"

---

**Parent Task:** [#7153](https://dev.icinga.com/issues/7153)

**Comment by lippserd** [comment]
This should be part of the Icinga Web2 NagVis module. I close this one.
