### ISSUE TITLE
[dev.icinga.com #9656] Avoid landing page redirects

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1846]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9656

**Created by elippmann on 2015-07-16 15:20:11 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:11:06 +00:00 (in Redmine)_

---

**Changesets**

_2015-08-27 11:32:35 +00:00_ by _elippmann_ af8949dde277c337e99d971b6a58744bed4a9e3c

    Add TODO in the IndexController: Avoid landing page redirects
    
    refs #9656

---

**Relations**:

* relates [#9656](https://dev.icinga.com/issues/9656)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
