### ISSUE TITLE
[dev.icinga.com #9727] RPM: Support lighttpd

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1874]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9727

**Created by elippmann on 2015-07-24 07:21:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-07-24 07:21:07 +00:00 (in Redmine)_

---

---

**Relations**:

* relates [#9669](https://dev.icinga.com/issues/9669)

**Comment by lippserd** [comment]
Duplicates #1853
