### ISSUE TITLE
[dev.icinga.com #9741] Delete downtimes action for multiple selected hosts and services

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1877]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9741

**Created by smadmin on 2015-07-27 07:58:35 +00:00**

Assignee: _elippmann_
Status: _Assigned_ 
Target Version: _Backlog_
Last Update: _2016-01-25 12:37:58 +00:00 (in Redmine)_

---

Hello guys,

we want delete all selected downtimes for services or hosts in "error view".
See picture... its possible?

greetings

sascha

**Attachments**

* [2015-07-27 09_56_23-Icinga Web .jpg](https://dev.icinga.com/attachments/download/2575/2015-07-27%2009_56_23-Icinga%20Web%20.jpg) smadmin - _2015-07-27 07:58:22 +00:00_

**Comment by lippserd** [comment]
Fixed
