### ISSUE TITLE
[dev.icinga.com #9767] Poor performance of  hostgroups and tactical overview page in large environments

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1883]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9767

**Created by bjbuijs on 2015-07-29 08:07:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-20 11:06:57 +00:00 (in Redmine)_

---

We have a pretty large distributed setup (160 hostgroups, 16.000 services):
The hostgroup page and tactical overview take more then 30 seconds to load (this on a 24 core Dell server which runs only icingaweb2):

    Description Off (ms)    Dur (ms)    Mem (diff)  Mem (total)
    Bootstrap, autoloader registered    0.003   0.003   966.59 KiB  966.59 KiB
    Action::postDispatch()  53.947  53.944  10.35 MiB   11.29 MiB
    Counting all results started    70.111  16.164  2.70 MiB    13.99 MiB
    Counting all results finished   20557.905   20487.794   3.16 KiB    13.99 MiB
    Query result iteration started  38777.027   18219.122   63.59 KiB   14.06 MiB
    Query result iteration finished 38795.545   18.518  314.03 KiB  14.36 MiB
    Response ready  38795.591   0.046   -105.32 KiB 14.26 MiB

Icinga2 version = 2.3.7-1.el6
Icingaweb2 version = 2.0.0-4.rc1.el6

I suppose the performance could be drastically improved by better queries/indexes.

**Attachments**

* [many-hosts-and-hostgroups.conf](https://dev.icinga.com/attachments/download/2729/many-hosts-and-hostgroups.conf) mjentsch - _2015-09-24 15:48:23 +00:00_

---

**Parent Task:** [#8612](https://dev.icinga.com/issues/8612)

**Relations**:

* relates [#10062](https://dev.icinga.com/issues/10062)
* relates [#10061](https://dev.icinga.com/issues/10061)
* relates [#10068](https://dev.icinga.com/issues/10068)

**Comment by marcofl** [comment]
Is there any progress in this issue? This is a real problem for us, too, with 600+ Hosts and 25000+ services. We have hostgroups where all host belong to, those are slow (10-30sec), even when directly filtering hosts with `monitoring/list/hosts?hostgroup_name=<hostgroupname`, when directly filtering in the URL to a hostgroup with just 15 hosts and 600 services  then it's usable fast.

**Comment by lippserd** [comment]
Closed in favour of #2557. We'll try to improve MySQL query performance again with our next releases Icinga Web 2 version v2.5.0 and Icinga 2 version v2.8.0 which are scheduled for the end of November.
