### ISSUE TITLE
[dev.icinga.com #9781] Setup wizard: Describe how conditional requirements are connected

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1886]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9781

**Created by jmeyer on 2015-07-30 06:50:20 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:11:08 +00:00 (in Redmine)_

---

Our requirements renderer does currently not show how conditional requirements are connected together (AND, OR) as shown in the picture. This can confuse users if there is something missing.

![requirements.jpg](https://dev.icinga.com/attachments/download/2583/requirements.jpg)

The picture, however, is of course not a design proposal.

**Attachments**

* [requirements.jpg](https://dev.icinga.com/attachments/download/2583/requirements.jpg) jmeyer - _2015-07-30 06:48:48 +00:00_

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
