### ISSUE TITLE
[dev.icinga.com #9829] Submit a form with control + enter

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1900]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9829

**Created by afuhr on 2015-08-04 14:32:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-12-18 14:49:10 +00:00 (in Redmine)_

---

It would be awesome if we could submit a form by pressing the key combo \[ control + enter\]

Actually it doesn't work in form textareas.

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
