### ISSUE TITLE
[dev.icinga.com #9833] Can't send external Icinga command to the local command file "/var/run/icinga2/cmd/icinga2.cmd": No such device or address

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1902]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9833

**Created by cnleon on 2015-08-05 01:25:31 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2015-08-05 07:14:52 +00:00_)
Target Version: _(none)_
Last Update: _2015-08-05 07:14:52 +00:00 (in Redmine)_

---

Hi

Now I click "check now" link, it will report a error like follow.

And in the /var/log/icinga2/error.log has no any error log.

Follow is the error info：
Can't send external Icinga command to the local command file [/var/run/icinga2/cmd/icinga2.cmd]() No such device or address

    #0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php(68): Icinga\Module\Monitoring\Command\Transport\LocalCommandFile->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleServiceCheckCommand))
    #1 /usr/share/php/Icinga/Web/Form.php(909): Icinga\Module\Monitoring\Forms\Command\Object\CheckNowCommandForm->onSuccess()
    #2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(62): Icinga\Web\Form->handleRequest()
    #3 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(65): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
    #4 /usr/share/php/Zend/Controller/Action.php(516): Monitoring_ServiceController->showAction()
    #5 /usr/share/php/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
    #6 /usr/share/php/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #7 /usr/share/php/Icinga/Application/Web.php(154): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #8 /usr/share/php/Icinga/Application/webrouter.php(111): Icinga\Application\Web->dispatch()
    #9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
    #10 {main}

**Attachments**

* [icinga2-cli.png](https://dev.icinga.com/attachments/download/2606/icinga2-cli.png) cnleon - _2015-08-05 01:23:47 +00:00_ - _command cli_
* [icinga2-click.png](https://dev.icinga.com/attachments/download/2607/icinga2-click.png) cnleon - _2015-08-05 01:23:47 +00:00_ - _click link_
* [icinga2-error.png](https://dev.icinga.com/attachments/download/2608/icinga2-error.png) cnleon - _2015-08-05 01:23:48 +00:00_ - _error_

**Comment by billydavies** [comment]
For anybody else who stumbles upon this thread and thinks "why didn't the OP add their solution" - I had a similar issue after running an upgrade of Icinga using apt-get upgrade.  The solution for us was to check the status of the Icinga2 service on the VPS running the Icinga web interface:

service icinga2 status

Following the upgrade the service was stopped so we manually started it using:

service icinga2 start

And the "Can't send external Icinga command to the local command file..." issue when running manual rechecks on Icinga service problems was resolved.
