### ISSUE TITLE
[dev.icinga.com #9871] Only sent notifications from active master are shown (waiting for Icinga 2)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1913]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9871

**Created by Foxeronie on 2015-08-10 17:23:02 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2016-11-15 09:34:57 +00:00_)
Target Version: _Backlog_
Last Update: _2016-11-15 10:34:36 +00:00 (in Redmine)_

---

Hello!

There are not all sent notifications shown in the Notification Area or history of a Host/Service.

For example:

    icinga2.log:
    [2015-08-09 23:25:10 +0200] information/Notification: Sending notification 'icinga-perf!NRPE Running npcd Process!icinga-perf+_All_Services_e-mail_username' for user 'username'
    [2015-08-09 23:25:10 +0200] information/Notification: Completed sending notification 'icinga-perf!NRPE Running npcd Process!icinga-perf+_All_Services_e-mail_username' for checkable 'icinga-perf!NRPE Running npcd Process

But there is no info about this in the notification area of this service, in the history or the alert summary.

This message was sent from the master who is NOT the active master. Currently there are two master in my master zone.
As I can tell so far only notifications sent from the active master are shown in the history/notification area.

Icinga v2.3.8
Icinga Web 2 commit from Mon, 10 Aug 2015 14:49:27 +0200 (14:49 +0200)

Best regards,
Patrick

---

**Relations**:

* blocks [#9871](https://dev.icinga.com/issues/9871)

**Comment by lippserd** [comment]
I close this issue because it's an Icinga 2 bug.
