### ISSUE TITLE
[dev.icinga.com #9904] Verify that it's possible to list users (and groups) from a LDAP backend

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1922]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9904

**Created by jmeyer on 2015-08-14 10:46:47 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:11:09 +00:00 (in Redmine)_

---

Since we're not checking the health of a authentication backend anymore (besides when inspecting the backend, which happens only when configuring it), Icinga Web 2 may show only empty rows or fails somehow else when listing entries from the mis-configured backend.

We should somehow handle such cases properly, log an error and display that nothing was found.

**Comment by Al2Klimov** [comment]
Haven't we already [fixed this](https://github.com/Icinga/icingaweb2/blob/f2f9ab5bc03e04c2f72d9d38ba73073743eb7283/library/Icinga/Authentication/User/LdapUserBackend.php#L458)?

**Comment by nilmerg** [comment]
You're referring to a part of the inspection, which I clearly mentioned not being relevant to this issue. So, no we did not.

This issue is about the administration listings. They may break completely with an exception or may show literally empty rows because of mis-configuration.

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
