### ISSUE TITLE
[dev.icinga.com #10001] Allow to link foreign documentation from modules and the framework

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1955]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10001

**Created by jmeyer on 2015-08-26 12:10:10 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-08-31 10:04:40 +00:00 (in Redmine)_

---

I'd like to link a \*.md file from another module and the framework in my module and vice versa.

---

**Parent Task:** [#7153](https://dev.icinga.com/issues/7153)

**Comment by lippserd** [comment]
Moved to Icinga/icingaweb2-module-doc#5
