### ISSUE TITLE
[dev.icinga.com #10026] Provide more intuitive input methos for time based filter elements

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#1965]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10026

**Created by mjentsch on 2015-08-28 08:14:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-05-06 15:39:20 +00:00 (in Redmine)_

---

Right now, you can either specify a unix timestamp or a human-readable relative time period like "-1 days". None
of this is really obvious to the user, since there aren't any hints besides an empty text field.

We need to find a way to communicate what kind of input is expected to the user, either in the form of a
Combobox that offers autocompletion or presets, or at least some "help" icon that explains the possible inputs.

---

**Relations**:

* relates [#8937](https://dev.icinga.com/issues/8937)
* relates [#10026](https://dev.icinga.com/issues/10026)
* duplicates [#10026](https://dev.icinga.com/issues/10026)
* duplicates [#10026](https://dev.icinga.com/issues/10026)
* duplicates [#10026](https://dev.icinga.com/issues/10026)

**Comment by nilmerg** [comment]
We should think of this as part of #4094.
