### ISSUE TITLE
[dev.icinga.com #10230] Respect filters in the state summaries

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2025]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10230

**Created by mzac on 2015-09-28 13:49:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-04-10 21:32:08 +00:00 (in Redmine)_

---

When filtering for a host, service, service group etc, the totals at the top of the pane show the totals for the whole system and not for the searched item.

See attached image (ignore the OID error, that is my bad :) )

**Attachments**

* [Screenshot 2015-09-28 09.47.04.png](https://dev.icinga.com/attachments/download/2736/Screenshot%202015-09-28%2009.47.04.png) mzac - _2015-09-28 13:49:10 +00:00_

---

**Relations**:

* duplicates [#10230](https://dev.icinga.com/issues/10230)

**Comment by nilmerg** [comment]
Is part of Icinga DB Web. Won't happen for the monitoring module anymore.
