### ISSUE TITLE
[dev.icinga.com #10298] Scrolling position is not preserved correctly

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2048]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10298

**Created by tgelf on 2015-10-05 08:47:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-03-29 09:31:52 +00:00 (in Redmine)_

---

On autorefresh a container MUST preserve it's scrolling position. This issue is open (and afaik known to many of us) since a while, I'm opening this issue as none of us seems to care. It got even worse with 2.0.0 as it now affects the menu behaviour: it's no fun to work with bottom menu entries any more. This is mostly because of the menu wasting more space than it formerly used to.

**Comment by Al2Klimov** [comment]
Hello @Thomas-Gelf,

This has been fixed "accidentally" by #3295.

Best,
AK
