### ISSUE TITLE
[dev.icinga.com #10306] History API seems to be half-broken

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2056]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10306

**Created by tgelf on 2015-10-05 09:18:22 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-03-29 09:31:57 +00:00 (in Redmine)_

---

This used to work. I did not dig deeper, but to me it seems that we now completely ignore the fact that form actions resulting in a redirect should never make part of the navigation history. I've been told that there might be even more "strangeness" in this feature (-&gt; ask Johannes). So please be careful and intensively test it when fixing the history API - once again.

**Comment by Al2Klimov** [comment]
Hello @nilmerg,

> I've been told that there might be even more "strangeness" in this feature (-> ask Johannes).

What is he writing about?

Best,
AK

**Comment by nilmerg** [comment]
I have no idea. That's way too old to remember for me. I'd even suggest closing this, as long as no-one else can remember what this issue is about.. (I just tried to submit a form and navigate back, nothing un-usual happened..)

**Comment by Al2Klimov** [comment]
As discussed w/ @nilmerg (offline):

If this is *still* a *real* problem, someone will re-discover it one nice day – and re-open this.
