### ISSUE TITLE
[dev.icinga.com #10395] Roles: Permit and restrict access to contact information

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2090]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10395

**Created by Foxeronie on 2015-10-19 12:40:04 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-17 14:06:36 +00:00 (in Redmine)_

---

Hi everyone!

We have servers from other groups of our company in our datacenter.
They have a separate role where they only can see their servers.
The problem is that they can see all phone (pager) numbers under "Contacts" from our IT admins who gets sms alarms to this number. A lot of them are private numbers.
Can you maybe create a filter option for this? (Role can/can't see contact informations)

Thanks!

Best regards,
Patrick

**Comment by santuari** [comment]
Hi all, @lippserd, 
we have similar requirements. In a multi-tenant enviroments, the contacts of other tenants must not be visible.
Do you have any plans on this? 
Is a working solution available to achieve this?
Thanks!

**Comment by nilmerg** [comment]
Resolved by #3973
