### ISSUE TITLE
[dev.icinga.com #10505] Acknowledgment not displayed if the service was ack'ed on other cluster member

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2115]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10505

**Created by tobiasvdk on 2015-10-31 13:04:37 +00:00**

Assignee: _elippmann_
Status: _Assigned_ 
Target Version: _Backlog_
Last Update: _2016-02-17 16:47:24 +00:00 (in Redmine)_

---

I have a distributed icinga 2 setup with one master and some slaves. If I acknowledge a service on the master, the acknowledgement is shown fine in the master's webui but on the slave I get the error (and vice versa):

    Fatal error: Call to a member function getAuthor() on null in zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/components/acknowledgement.phtml on line 20

screenshot:
![icingaweb2_ack_problem.png](https://dev.icinga.com/attachments/download/2841/icingaweb2_ack_problem.png)

The database seems to be fine:

**master**:

``` sql
icinga2idopgsql=> select * from icinga_acknowledgements where comment_data like 'ack on %';
 acknowledgement_id | instance_id |       entry_time       | entry_time_usec | acknowledgement_type | object_id | state | author_name  | comment_data  | is_sticky | persistent_comment | notify_contacts |        end_time        | endpoint_object_id 
--------------------+-------------+------------------------+-----------------+----------------------+-----------+-------+--------------+---------------+-----------+--------------------+-----------------+------------------------+--------------------
                  4 |           1 | 2015-10-31 12:10:35+00 |          255068 |                    2 |       508 |     1 | tvonderkrone | ack on master |         1 |                  1 |               1 | 2015-10-31 14:10:21+00 |                  3
                  5 |           1 | 2015-10-31 12:11:13+00 |          207911 |                    2 |       510 |     1 | tvonderkrone | ack on slave  |         1 |                  1 |               1 | 2015-10-31 14:11:01+00 |                  3
(2 rows)
```

**slave**:

``` sql
icinga2idopgsql=> select * from icinga_acknowledgements where comment_data like 'ack on %';
 acknowledgement_id | instance_id |       entry_time       | entry_time_usec | acknowledgement_type | object_id | state | author_name  | comment_data  | is_sticky | persistent_comment | notify_contacts |        end_time        | endpoint_object_id 
--------------------+-------------+------------------------+-----------------+----------------------+-----------+-------+--------------+---------------+-----------+--------------------+-----------------+------------------------+--------------------
                  4 |           1 | 2015-10-31 12:10:35+00 |          267328 |                    2 |       495 |     1 | tvonderkrone | ack on master |         1 |                  1 |               1 | 2015-10-31 14:10:21+00 |                  1
                  5 |           1 | 2015-10-31 12:11:13+00 |          189793 |                    2 |       497 |     1 | tvonderkrone | ack on slave  |         1 |                  1 |               1 | 2015-10-31 14:11:01+00 |                  1
(2 rows)
```

My setup:

-   debian jessie
-   postgresql 9.4
-   icinga 2.4 commit 1b9f0a8c77b3c00f87f9ee0e9515098c7b0ab4fb
-   icingaweb2 commit 5db8d08729b8637862da27ffa23ece0868432486

**Attachments**

* [icingaweb2_ack_problem.png](https://dev.icinga.com/attachments/download/2841/icingaweb2_ack_problem.png) tobiasvdk - _2015-10-31 13:03:35 +00:00_
* [ack2.png](https://dev.icinga.com/attachments/download/2966/ack2.png) tobiasvdk - _2015-12-17 14:58:45 +00:00_
* [ack1.png](https://dev.icinga.com/attachments/download/2967/ack1.png) tobiasvdk - _2015-12-17 14:58:45 +00:00_

**Changesets**

_2015-11-16 13:35:48 +00:00_ by _elippmann_ ba62753285fe0682185c18a53dc4bd7123dc8613

    monitoring: Fix exception if the comment of an acknowledgement is missing
    
    refs #10505

---

**Relations**:

* relates [#10505](https://dev.icinga.com/issues/10505)

**Comment by lippserd** [comment]
Should be fixed. If not, please open a new issue.
