### ISSUE TITLE
[dev.icinga.com #10600] Groups which don't have any members are not shown in Icinga Web 2

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2123]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10600

**Created by gbeutner on 2015-11-11 07:23:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:11:16 +00:00 (in Redmine)_

---

---

**Relations**:

* relates [#11744](https://dev.icinga.com/issues/11744)

**Comment by Al2Klimov** [comment]
Duplicate of #2796
