### ISSUE TITLE
[dev.icinga.com #10674] Domain support for authentication/authorization

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2153]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10674

**Created by tgelf on 2015-11-19 10:22:22 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 12:41:13 +00:00 (in Redmine)_

---

In case an environment hosts multiple distinct domains, I do not only want to try all of them in a try&error way. Icinga Web 2 should provide native support for such. I want to be able to login with either user@domain or domain\\user, internally the user should be normalized to user@domain. We need a mapping of user and group backends to domains, membership checks should be domain aware. This should also work across multiple authentication types. In case I'm doing Kerberos SSO with Apache, I expect to be assigned to the correct domain and have working group membership lookups through the related AD/LDAP backend.

**Comment by Al2Klimov** [comment]
# Done so far

LDAP resources can discover and/or store the domains a server is responsible for.

# To do

How and where to use this info?

## Possible implementation details as I understood @Thomas-Gelf

### Abstract

* username, localpart: "aklimov"
* domain
    * netbios-name: "NETWAYS"
    * default naming context, FQDN style: "int.netways.de"
* full username (login)
    * legal
        * NETWAYS\\aklimov
        * aklimov@NETWAYS
        * aklimov@int.netways.de
    * illegal by definition, but not too bad if works anyway as long as not documented
        * int.netways.de\\aklimov

### IW2\\...\\User stores

* localpart (get, set)
    * "aklimov"
* domain (get, set)
    * "NETWAYS" | "int.netways.de" (depending on how one logs in)
* username
    * get: assembles localpart "@" domain (or only localpart if domain missing)
    * set: split "localpart@domain" or "domain\\localpart" or "localpart" (if domain is missing)
    * so NETWAYS\\aklimov gets converted to aklimov@NETWAYS

### And... then?

"aklimov@NETWAYS" is only authenticated by backends responsible for "NETWAYS".

#### And just "aklimov"?

If a global default domain is configured (TODO: where?):

* backends w/o domain are implicitly responsible for that default domain
* IW2\\...\\AuthnWhatever sets user->domain (if missing/NULL) to the default domain
    * So when you try to log in as "aklimov", you actually log in as "aklimov@int.netways.de"

Else: Backends w/o domain are responsible for users w/o domain

### And... how we prevent sysadmins form accidentally breaking their whole setup?

If someone tries to configure a default domain, we offer to rename all domain-less users in the config. ("aklimov" => "aklimov@NETWAYS")

**Comment by Al2Klimov** [comment]
# Done so far

* authn backends and users have domains
    * authn backends are queried or not based on that info
* a default domain for both users and authn backends is configurable
    * once it is set (in existing setups), all domain-less users are kicked out

# Still unclear (@lippserd, @Thomas-Gelf?)

* *User* backends have domains. What about *group* backends? (especially DB)
* Even if users log in like "jdoe@example.com", in /user/list they're shown like "jdoe". This is... the opposite of being intuitive. (especially in role config)
    * Therefore a backend should (IMO) have at most one domain so that it's clear which domains the users belong to. (If an admin sets up an AD for two distinct domains, they can also set up another authn backend with the same resource as this isn't a big deal.)
* At the moment external backends can't be "responsible" for any domain because they don't ask anything "Are these credentials valid?". Instead they just check the envVars and if the user in the envVar has a domain (whichever it is) – OK. If not: fallback to the default domain. Can/Should this be let as is? Alternatives?
* At the moment the default domain is applied to all types of backends as fallback. OK or not OK? (I don't worry about this, but @nilmerg does.)

**Comment by Al2Klimov** [comment]
Also still unclear: How should we kick out users?
My suggestion:
There's a file in /etc/iw2 with an integer. Once a user logs in, that int is being copied into the session. On every request (application-state) the copy is compared with the original. If they differ, the user is being kicked out.
If someone clicks kick-out-all-users, the int gets incremented.

**Comment by Al2Klimov** [comment]
# As discussed with @mxhash

* user kick-out
    * a timestamp per user (not per session!) for the last login
    * a kick-out is done by clearing that timestamp
    * the absence of that timestamp is being checked at application-state requests
    * but we don't do this (right now) as we don't have anything that is present for every user (who had logged in at least once)
* all the other stuff
    * let it as is right now

**Comment by Al2Klimov** [comment]
# As discussed with @lippserd a few days ago

- [ ] no kick-out at all
- [ ] migration is not done by checking a box, but by CLI
- [ ] the login page is to be extended by a (configurable) drop-down with all/some domains
- [ ] group backend domains are configured the same way as user backends' ones are (no implicit association)
- [ ] Backend 1:1 Domain
- [ ] the NetBIOS name is being discovered by the ldap-capabilities
