### ISSUE TITLE
[dev.icinga.com #10681] Document CLI command web serve

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2157]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10681

**Created by aklimov on 2015-11-19 17:42:28 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2015-11-20 17:45:05 +00:00_)
Target Version: _Backlog_
Last Update: _2016-12-20 10:16:26 +00:00 (in Redmine)_

---

As a user I want not to have to read the code to understand e.g. how to use the program.

**Changesets**

_2015-11-20 17:39:38 +00:00_ by _aklimov_ 6d56a57b7e7d6062de5e4d91f2a85109515c5c40

    Document WebCommand::serveAction()
    
    resolves #10681

---

**Relations**:

* blocks [#10681](https://dev.icinga.com/issues/10681)

**Comment by lippserd** [comment]
Fixed
