### ISSUE TITLE
[dev.icinga.com #10701] Change roles simple and fast

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2161]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10701

**Created by aledermueller on 2015-11-23 08:08:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-17 17:15:26 +00:00 (in Redmine)_

---

Hi,

in our use case a user can be in several roles. Each role has an own filter (monitoring/filter/objects). It would be nice if a user can switch between his roles in a fast and simple way.

Thanks,
Achim

**Comment by nilmerg** [comment]
That's what *environments* are, or rather, will be.
