### ISSUE TITLE
[dev.icinga.com #10707] UI: Group restrictions by module

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2166]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10707

**Created by elippmann on 2015-11-23 12:35:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-24 10:52:56 +00:00 (in Redmine)_

---

**Comment by lippserd** [comment]
Moved to #3416.
