### ISSUE TITLE
[dev.icinga.com #10792] Resizeable columns

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2184]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10792

**Created by wanchai on 2015-12-07 21:17:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-12-09 14:20:15 +00:00 (in Redmine)_

---

It would be really nice if we could move the divider between the panels of the Icingaweb2 GUI. In particular when you use the Graphite module, and when you are displaying a large diagram on the right, the fixed panels become annoying.

**Comment by lippserd** [comment]
Moved to #3416.
