### ISSUE TITLE
[dev.icinga.com #10810] Document how to hide menu and header

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2190]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10810

**Created by Anonymous on 2015-12-09 19:12:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-02-17 17:39:44 +00:00 (in Redmine)_

---

It would be great if it was possible to hide Menu and Header from the view when you use Icingaweb2 to show the status in Operations Centre environments or on monitors generally as "read only".

---

**Parent Task:** [#7153](https://dev.icinga.com/issues/7153)

**Comment by lippserd** [comment]
Moved to Icinga/icingaweb2-module-doc#3

**Comment by lippserd** [comment]
Moved the wrong issue. Reopened.
