### ISSUE TITLE
[dev.icinga.com #10849] Provide more intuitive input methos for state based filter elements

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2202]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10849

**Created by mhein on 2015-12-15 11:51:34 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-19 09:20:26 +00:00 (in Redmine)_

---

Hi,

if you want to filter for Host or Service Status, you need to know the status integer value to set the filter correctly. I think it is easier to provide a selection box for status groups of host and service statuses.

Kind regards,

Marius

---

**Relations**:

* relates [#10026](https://dev.icinga.com/issues/10026)

**Comment by nilmerg** [comment]
By now anyone using Icinga probably knows about 0-1-2[-3]. Though, we may think of something as part of #4094.
