### ISSUE TITLE
[dev.icinga.com #10882] iframe action should not accept URLs as a parameter

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2212]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10882

**Created by tgelf on 2015-12-17 16:47:39 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-03-29 09:32:21 +00:00 (in Redmine)_

---

IMO this could be misused for various attacks. URLs should be configured, URL parameter should reference configured URLs by name/id/whatever.

Cheers,
Thomas

**Comment by Al2Klimov** [comment]
Hello @Thomas-Gelf,

What about #3296 instead?

Best,
AK

**Comment by Al2Klimov** [comment]
@lippserd What about #3297 instead?
