### ISSUE TITLE
[dev.icinga.com #10888] Containers with PHP fatal errors cannot be closed

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2216]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10888

**Created by tgelf on 2015-12-18 09:46:15 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-15 09:21:44 +00:00 (in Redmine)_

---

I guess &lt;?= $this-&gt;tabs ?&gt; or similar in the error controllers view script would fix this.

Thanks,
Thomas

**Comment by nilmerg** [comment]
Duplicate of #2323.
