### ISSUE TITLE
[dev.icinga.com #10911] Dynamically add top level menu entries for grouping and categories via hook

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2223]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10911

**Created by icixaos on 2015-12-24 18:59:27 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-01-05 10:21:30 +00:00 (in Redmine)_

---

Hello icinga friends.

This is my first post so I apologize for any post faux pas.
What I want to do is really quite simple, at least in concept.
However, the implications on an enterprise level are huge.
Let me explain.

On the left Pane (icingaweb2), we have "Search" "Dashboard" "Overview" etc...

What I want is the left pane to show my Server grouping by function and underneath that
the "Search" "Dashboard" "Overview" etc.

Like this:

\[+\]Servers-Function-1
\[+\]Servers-Function-2
\[+\]Servers-Function-3
\[+\]Servers-DR
\[+\]Servers-Grid-1
\[+\]Servers-Grid-2
\[+\]Master-View

When I click on the plus (on the left), I should get
the familiar list but UNDERNEATH the category.
Like this:

\[+\]Servers-Function-1
Search
Dashboard
Problems
Overview
History
Reporting
\[+\]Servers-Function-2
Search
Dashboard
Problems
Overview
History
Reporting
\[+\]Servers-Function-3
...
\[+\]Servers-DR
\[+\]Servers-Grid-1
\[+\]Servers-Grid-2
\[+\]Master-View

See how everything is in the specific category?

Now, the above tree should be created by giving a host a specific variable such as:

template Host "myhost1" {
max\_check\_attempts = 3
...
...
vars.tree\_grouping="Server-Function-1"
...
...
}

And the services could be generated as:

apply Service "test-specific" {
...
...
assign where host.vars.tree\_grouping == "Server-Function-1"
}

Simple ? I don't know...
I do know that I need this. I could even make an attempt to
create it myself. But, where do I start?

Your help is most appreciated.

I am using icinga2. and Icingaweb2 V2.1.2

George

**Comment by lippserd** [comment]
Hi,

I don't see this implemented anytime soon. So I close this one.

Best regards,
Eric
