### ISSUE TITLE
Chosen theme not visible after login until the page is manually refreshed

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2233]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10957

**Created by jmeyer on 2016-01-12 09:09:25 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-04-27 15:43:34 +00:00 (in Redmine)_

---

**Changesets**

_2016-01-18 11:56:02 +00:00_ by _elippmann_ 9968fb90118ea4bb3dfe3d88c234857fd333abbe

    Reload CSS after login because the user may have a different theme (WIP)
    
    This is just a quick fix.
    
    refs #10957

**Comment by pandian912** [comment]
I am facing the same issue where the browser keeps on making requests for the css file
