### ISSUE TITLE
[dev.icinga.com #10996] Make items per page configureable

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2241]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10996

**Created by rdesanno on 2016-01-20 18:19:40 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-18 15:46:20 +00:00 (in Redmine)_

---

Is it possible to have the default value for $itemsPerPage under /usr/share/php/Icinga/Web/Controller.php to be user configurable and not overwritten with each new release?

protected function setupPaginationControl(QueryInterface $query, **$itemsPerPage = 25**, $pageNumber = 0)

**Comment by mateusz-gozdek-sociomantic** [comment]
I think this is done in version 2.5.0 and can be closed.

**Comment by lippserd** [comment]
True. Thanks for the heads up.
