### ISSUE TITLE
[dev.icinga.com #11011] Active Directory User Groups: No permissions and error

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2250]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11011

**Created by Anonymous on 2016-01-22 09:40:52 +00:00**

Assignee: _(none)_
Status: _Resolved_  (closed on _2016-01-28 07:29:25 +00:00_)
Target Version: _(none)_
Last Update: _2016-01-28 07:29:25 +00:00 (in Redmine)_

---

Hi All,
- Ubuntu 14.04
- Icingaweb2 2.1.2
- Icinga2 2.4.1.1
I am trying to permit Icingaweb2 permissions via Active Directory Groups.
Created a new AD ressource, validation works
Created new User Backend, validation works
Created new User Group Backend (missing the validation Button)
In Authorization -&gt; Users I see all Users from the AD. Login in Icingaweb with this AD Users is possible.
When I assign a User to e.g. the role Admins, the permissions are given to the user.
Permissions, which are given via groups instead of user accounts don't work. It seems that the permissions for the group are not inherited to the users in this group.
When I search the group in "User Groups", the group is shown with it's members.
But when I click on a member, an error appears that the user cannot be found.
Please check my attached screenshots.

Regards,
Amoyensis

**Attachments**

* [adgroup.JPG](https://dev.icinga.com/attachments/download/3023/adgroup.JPG) Anonymous - _2016-01-22 09:33:38 +00:00_ - _AD User Group Config_
* [aderror.JPG](https://dev.icinga.com/attachments/download/3024/aderror.JPG) Anonymous - _2016-01-22 09:33:38 +00:00_ - _Error in Usergroup -> User_
* [ressource.JPG](https://dev.icinga.com/attachments/download/3025/ressource.JPG) Anonymous - _2016-01-22 09:33:38 +00:00_ - _AD Ressource config_
* [aduser.JPG](https://dev.icinga.com/attachments/download/3026/aduser.JPG) Anonymous - _2016-01-22 09:33:38 +00:00_ - _AD User Backend Config_

**Comment by pfried** [comment]
Had exactly the same symptoms. But i had a faulty AD resource config where i had:

`root_dn = "ad.example.com"

Issue was solved by changing to:

`root_dn = "dc=ad,dc=example,dc=com"`
