### ISSUE TITLE
Can't search for host|service_output in the event history; searching for output fails too

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2266]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11068

**Created by ClemensBW on 2016-02-02 08:05:12 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-03-29 09:32:27 +00:00 (in Redmine)_

---

Hello,

in the eventhistory it is not possible to search for "service\_output"

"Die Spalte “service\_output” ist hier nicht zum Filtern erlaubt."

/icingaweb2/monitoring/list/eventhistory?timestamp&gt;=-7 days&service\_display\_name=service123&service\_output=**foobar**&modifyFilter=1

**Comment by mdetrano** [comment]
The problem seems to be due to the use of a GROUP_CONCAT aggregate function in the WHERE clause (that's not supported).  This only seems to come into play in ..Backend/Ido/Query/HostnotificationQuery.php and .. Backend/Ido/Query/ServicenotificationQuery.php.

**Comment by mdetrano** [comment]
#3781   Just created this pull request which may be adequate to resolve this issue.
