### ISSUE TITLE
[dev.icinga.com #11081] IE 10: Memory usage is rising and rising

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2272]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11081

**Created by GuidoL on 2016-02-03 14:59:03 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2016-10-05 07:58:39 +00:00_)
Target Version: _(none)_
Last Update: _2016-10-05 07:58:39 +00:00 (in Redmine)_

---

We have a servicegrid view includes more then 500 services, displayed at the same time. When we display this the memory is rising and rising. After some hours from ~ 100 MB to 500 MB.
But the rising is not stopping. We see memory usage something &gt; 3 GB

IE Version: 10.0.9200.17609
IcingaWeb2: 2.1.2
Icinga2: v2.4.1

**Comment by kajla** [comment]
I agree with it. Not a unique problem.

Tested browsers: Google Chrome, Firefox
Icinga2: r2.6.2-1
Icingaweb2: 2.4.1
