### ISSUE TITLE
View who removed the comment, downtime or acknowledgement in the history views

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2281]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11101

**Created by ClemensBW on 2016-02-05 18:41:43 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-02-26 20:58:54 +00:00 (in Redmine)_

---

Hello,

if I (Clemens) create a host comments and a other user (wan) delete this, i don't can see that in the history. Can you plase add a mouseover for that or a detail text, who delete the comment?

(dito for acknowledgments, think this is a little bit profoundly)

**Attachments**

* [000238_Icinga Web.png](https://dev.icinga.com/attachments/download/3072/000238_Icinga%20Web.png) ClemensBW - _2016-02-05 18:40:29 +00:00_ - _delete a comment from other user (wan delete clemens)_
* [000239_Icinga Web.png](https://dev.icinga.com/attachments/download/3073/000239_Icinga%20Web.png) ClemensBW - _2016-02-05 18:40:53 +00:00_ - _history show only clemens_

---

**Parent Task:** [#11180](https://dev.icinga.com/issues/11180)

**Comment by K0nne** [comment]
Hello,
are there any plans to add this feature to the new IcingaDB?

**Comment by nilmerg** [comment]
I can't recall any concrete plans, but I've seen intriguing columns in the history tables of the aforementioned types. Take a [look](https://github.com/Icinga/icingadb/blob/master/etc/schema/mysql/mysql.schema.sql) for yourselves. :zipper_mouth_face:

**Comment by nilmerg** [comment]
Actually, since v2.12 Icinga is able to process this just fine with the API. (https://github.com/Icinga/icinga2/pull/7645) Seems to have been forgotten to consider in Icinga DB Web. Should be no problem to get this into the final release. :smiley:

Thanks for chasing this up. :+1:
