### ISSUE TITLE
[dev.icinga.com #11186] Show long output in the event history

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2306]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11186

**Created by elippmann on 2016-02-18 15:52:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-02-18 15:52:05 +00:00 (in Redmine)_

---

---

**Relations**:

* relates [#11186](https://dev.icinga.com/issues/11186)

**Comment by lippserd** [comment]
Icinga Web 2 version 2.5.1 will introduce detail areas for events where it is possible to view the long output: #3191.
