### ISSUE TITLE
[dev.icinga.com #11218] Code isolation adjustments

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2316]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11218

**Created by jmeyer on 2016-02-24 12:23:44 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-07-11 06:49:22 +00:00 (in Redmine)_

---

This is not a feature per se, but more of a request to re-design our file/package structure.

One of our main goals with Icinga Web 2 is to provide a platform that is highly customizable through modules. We mostly succeeded in this manner, (except for some parts as noted in [\#9624,](https://dev.icinga.com/issues/9624) [\#9625](https://dev.icinga.com/issues/9625) and some other probably well known aspects) but if it is about to using only our library code and nothing else, I'm afraid, we did not.

There are some hardcoded dependencies between library and application related code, which partially prevents library code from being utilized on its own. A few examples:

-   StyleSheet: Fails badly if utilized without any css files residing in public/css/icinga
-   JavaScript: Fails badly as well without any js files residing in public/js
-   Limiter: Depends on the LimiterControlForm
-   ...

Some forms may also be of use in relation to specific parts of library code but cannot be used independently because they are application related code. This is mostly about configuration forms which are designed to manage configuration files read by library code or to manage data provided by datasources which are in turn managed by library code.

Some library code has been mistakenly identified as application code:

-   ConfigForm
-   RepositoryForm

--

Considering forms as library code, if they're not abstract or meant as super-class, is probably wrong. They are, however, not of any use on its own and require application code themselves to fully work. Due to this, I suggest to consider packaging these separately. At least those which are **specifically** linked with current library code.

Hardcoded dependencies and misplaced library code should of course be fixed directly.

What I would like to accomplish here is that one can just utilize our library **without reinventing anything**. (Such as a configuration form for a database resource or a form to add new members to a usergroup.)

And ultimately, modules can not only be designed to work with Icinga Web 2 but also standalone while being maintained in a single code base. (Then it is truly a jack of all trades :P)

**Comment by lippserd** [comment]
We will replace most of the Zend Stuff and our framework with the Icinga PHP Library (ipl) which is yet to be released. The ipl itself is separated into packages which can be used independently. Closing this one.
