### ISSUE TITLE
[dev.icinga.com #11220] Monitoring: Action toolbar

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2317]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11220

**Created by elippmann on 2016-02-24 15:18:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-06-15 14:25:04 +00:00 (in Redmine)_

---

**Changesets**

_2016-02-24 15:20:05 +00:00_ by _(unknown)_ 72dabf35c2fdb35dfd514045da7b4c79a0529e90

    Monitoring: Add toolbar draft
    
    refs #11220

_2016-02-24 15:46:50 +00:00_ by _(unknown)_ fe04e049f046ff31659bee80250d1c781bf43352

    Monitoring: Move CSS into modules.less
    
    refs #11220

**Comment by lippserd** [comment]
Implemented.
