### ISSUE TITLE
[dev.icinga.com #11246] Collapse too wide tabs into an expandable "..." menu

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2323]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11246

**Created by elippmann on 2016-02-27 14:13:41 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-10-05 11:28:12 +00:00 (in Redmine)_

---

---

**Relations**:

* duplicates [#11246](https://dev.icinga.com/issues/11246)
* duplicates [#11246](https://dev.icinga.com/issues/11246)

**Comment by lippserd** [comment]
Moved to #3416.
