### ISSUE TITLE
[dev.icinga.com #11262] Allow to export Alert Summary and Timeline

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2328]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11262

**Created by Anonymous on 2016-03-01 11:20:54 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-03-15 15:17:28 +00:00 (in Redmine)_

---

Hi All,
I have noticed, that there is no Option to export the Alert Summary to PDF,CSV,JSON.
I think, espacially this part is very interesting for exporting to show the failures in a specific time (KPIs)
Can you please implement this?

**Attachments**

* [Unbenannt.JPG](https://dev.icinga.com/attachments/download/3157/Unbenannt.JPG) Anonymous - _2016-03-01 11:19:01 +00:00_ - _Screenie_

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future. If you're interested in this topic, please open a new issue.
