### ISSUE TITLE
[dev.icinga.com #11271] Form label width too small

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2334]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11271

**Created by teqqy on 2016-03-02 07:27:40 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-05-09 12:06:36 +00:00 (in Redmine)_

---

In german translation is the naming for the checkboxes too long. Error in Chrome and Safari with OS X since the new 2.2 Version.

See Screenshot

**Attachments**

* [Bildschirmfoto 2016-03-02 um 08.25.29.png](https://dev.icinga.com/attachments/download/3163/Bildschirmfoto%202016-03-02%20um%2008.25.29.png) teqqy - _2016-03-02 07:27:28 +00:00_
* [optional-form-label-width.jpg](https://dev.icinga.com/attachments/download/3364/optional-form-label-width.jpg) jmeyer - _2016-05-09 12:05:17 +00:00_

**Comment by lippserd** [comment]
Moved to #3416.
