### ISSUE TITLE
[dev.icinga.com #11324] Add "Command Expander" menu to see raw command output.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2348]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11324

**Created by xtavras on 2016-03-07 11:22:34 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2016-03-15 14:51:35 +00:00_)
Target Version: _(none)_
Last Update: _2016-03-15 14:51:35 +00:00 (in Redmine)_

---

i would have been very happy if you can add "Command Expander" menu (with option to see raw command output) in IcingaWeb2 like it was in Icinga Classic UI, it is really helpful with debugging some checks.

**Attachments**

* [icinga_Web2.png](https://dev.icinga.com/attachments/download/3186/icinga_Web2.png) xtavras - _2016-03-07 11:21:40 +00:00_ - _"Command Expander" in classic ui_

---

**Relations**:

* duplicates [#8315](https://dev.icinga.com/issues/8315)

**Comment by nojeffrey** [comment]
Was this ever added? Still can't find this functionality in 2.12.0-1
