### ISSUE TITLE
[dev.icinga.com #11492] Module::getTitle() yields the description if the title is not defined

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2375]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11492

**Created by aklimov on 2016-03-31 13:17:27 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-19 16:50:29 +00:00 (in Redmine)_

---

It should yield the name instead as otherwise /icingaweb2/doc/module/ may display strange link titles.

**Comment by Al2Klimov** [comment]
@lippserd @nilmerg @Thomas-Gelf What's your opinion on https://github.com/Icinga/icingaweb2/issues/2375#issuecomment-273147483?

**Comment by nilmerg** [comment]
Yes, it's fine as it is since half a decade.
