### ISSUE TITLE
[dev.icinga.com #11493] Module descriptions should be translatable

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2376]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11493

**Created by aklimov on 2016-03-31 14:31:45 +00:00**

Assignee: _elippmann_
Status: _Feedback_ 
Target Version: _Backlog_
Last Update: _2016-12-15 14:55:14 +00:00 (in Redmine)_

---

**Changesets**

_2016-12-15 14:39:20 +00:00_ by _(unknown)_ 6dd5f6227bf351067d819ec959ec05607a4c5044

    Make module title and description translatable
    
    refs #11493

_2016-12-15 14:52:58 +00:00_ by _(unknown)_ bd6420496a4b1758a67633f04001df6bb3c801af

    Make use of translated module descriptions (if any)
    
    refs #11493

**Comment by lippserd** [comment]
I don't see the benefit of having module descriptions translatable. In most cases this is just a short string and nothing I work with when using Web 2.

**Comment by Al2Klimov** [comment]
Just opened POEdit for [my own module](https://github.com/Al2Klimov/masif-upgrader/tree/master/icingaweb2-module-masifupgrader) and was surprised by my own changes (#2741) having no effect. 😞

@lippserd I had already implemented the changes, why did you throw them away? (Having is better than needing.) Please explain (offline). Translations are for non-English-speakers after all and the module description *is* (usually) english.

**Comment by Al2Klimov** [comment]
Damn, you're temporarily unavaliable for [censored by DSGVO]. 😞

@nilmerg Please lets have a look on this together ASAP (offline).

**Comment by Al2Klimov** [comment]
@nilmerg (offline): "Don't convince me, convince @lippserd."
