### ISSUE TITLE
[dev.icinga.com #11497] Add a view for dependency of objects

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2378]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11497

**Created by ziaunys on 2016-03-31 18:56:15 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-06-15 20:08:27 +00:00 (in Redmine)_

---

It would be nice to have a view for Dependency objects so the UI has parity with all the Icinga2 object types. I would expect to view these objects in the same way Hosts/Services are viewed. It would list all the attributes for the Dependency object and provide links to the parent/child objects.

---

**Relations**:

* duplicates [#11497](https://dev.icinga.com/issues/11497)

**Comment by Hrocc** [comment]
+1

**Comment by melaniebauer** [comment]
It would also be nice to see the applied dependencies for an object. An example: I have configured a parent-host-dependency like in icinga v1 and it shows the variable with the host name, but I cannot reach the parent host in one click. That would be possible if  the resolved dependency would be shown in the host view.

**Comment by sulicz** [comment]
+1

**Comment by sulicz** [comment]
+1

**Comment by voipmeister** [comment]
+1

**Comment by jonasboettcher** [comment]
+1

**Comment by wp-perc** [comment]
+1

**Comment by ArcherAndi** [comment]
+1
Would some sponsoring help?

**Comment by Mikesch-mp** [comment]
*blows away the dust from 4 years*, This is feature that is important for users without shell access

**Comment by yolanjoy** [comment]
+ Please add this much needed feature.  Much appreciated!!

**Comment by thomich** [comment]
+1

**Comment by FI5CHER** [comment]
pls ... thx in advance

**Comment by dwt** [comment]
Hi @devs, can you give an update what is holding this up? Perhaps some perspective on what the community can do to support the development of this feature?
