### ISSUE TITLE
[dev.icinga.com #11707] Tooltips are cut off at screen edge with mobile layout

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2412]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11707

**Created by julianbrost on 2016-05-01 15:07:04 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-10-04 10:06:43 +00:00 (in Redmine)_

---

Some tooltips are misplaced. I noticed this for the schedule downtime and add comment pages, see the attached screenshot.

I can reproduce the issue with both Chrome 50 on Android and Chromium 50 on Linux (using the "device mode" in the developer tools) but haven't checked others.
Icinga Web 2 version: 2.3.2

**Attachments**

* [icingaweb2-tooltip-mobile.png](https://dev.icinga.com/attachments/download/3342/icingaweb2-tooltip-mobile.png) julianbrost - _2016-05-01 15:03:17 +00:00_ - _Screenshot_

**Comment by lippserd** [comment]
Moved to #3416.
