### ISSUE TITLE
[dev.icinga.com #11762] Allow to save filters

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2423]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11762

**Created by shoenscheid on 2016-05-11 08:22:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-05-11 09:55:05 +00:00 (in Redmine)_

---

A nice feature would be to save filters using a specific name. These may then be loaded later on in the filter editor and used when creating dashboards.

**Comment by lippserd** [comment]
Hi,

This issue will be fixed as part of #3631.

Best,
Eric
