### ISSUE TITLE
[dev.icinga.com #11820] Check whether chosen locale is available

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2432]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11820

**Created by jaheller on 2016-05-20 11:01:16 +00:00**

Assignee: _elippmann_
Status: _Resolved_  (closed on _2016-11-17 10:25:02 +00:00_)
Target Version: _2.4.0_
Last Update: _2016-11-17 10:25:02 +00:00 (in Redmine)_

---

After installing icw2 on my ubuntu server I tried to change language to German.
It takes some time before I figured out, the needed locals weren't installed on ubuntu server. Maybe including a check/hint box for this.
Was kind of confusing, because icw2 told me settings are applied successful.

**Changesets**

_2016-05-23 09:54:53 +00:00_ by _aklimov_ 1173afaff34ff53272e809efd057c5a205f2d1a3

    Inform the user if the configured locale isn't installed
    
    refs #11820

_2016-11-17 10:21:58 +00:00_ by _elippmann_ 95cbb6198743ffd8f493fb8df38f2723a4a32fee

    Add parameter markAsError to Form::warning() and Form::error()
    
    refs #11820

_2016-11-17 10:21:59 +00:00_ by _aklimov_ 1450bc4022428c311c868e5d806c210360865adf

    Show a warning if the chosen locale by the user is not available on the system
    
    refs #11820

_2016-11-17 10:23:49 +00:00_ by _elippmann_ 3d6e804ff32bdfd70a4a69d491f9f050409fde36

    Merge branch 'feature/include-check-if-chosen-locale-is-available-11820'
    
    resolves #11820

---

**Relations**:

* duplicates [#11820](https://dev.icinga.com/issues/11820)

**Comment by Fiiti** [comment]
This issue still exists. Installed two completly different instances of icinga2 on 2 different ubuntu 16.04LTS.
I must add 
sudo locale-gen de_DE
sudo locale-gen de_DE.UTF-8
sudo update-locale

manually.
