### ISSUE TITLE
[dev.icinga.com #11821] icingaweb2/setup page is blank after new install

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2433]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11821

**Created by dewsyuff on 2016-05-20 15:11:29 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2016-10-04 09:48:29 +00:00_)
Target Version: _(none)_
Last Update: _2016-10-04 09:48:29 +00:00 (in Redmine)_

---

I've just installed Icinga2 and Icingaweb2 on a fresh 16.04 Unbuntu VM, and when trying to access the (myhostname)/icingaweb2/setup page, it only returns a blank page. I see nothing in syslog, icinga2.log, icinga2.err, the firewall logs, the php log or anywhere else I've thought to look. I've tried disabling the firewall to make sure that wasn't causing a problem. This happens directly on the host as well as a browser from a different host. I've tried the hostname, the IP address, local host, 127.0.0.1, and get the same result. The apache2 access log shows 127.0.0.1 - - \[20/May/2016:10:06:33 ~~0500\] "GET /icingaweb2/setup HTTP/1.1 304180 "~~" Mozilla/5.0 (X11; Ubuntu; Linux x86\_64; rv:46.0) Gecko/20100101 Firefox/46.0". The apache2 error log shows nothing. What else should I do to try to get this resolved?

---

**Relations**:

* relates [#12285](https://dev.icinga.com/issues/12285)

**Comment by svojmajstor** [comment]
This is still not fixed

**Comment by ComfortCurve2000** [comment]
Same here, needed libapache2-mod-php

**Comment by Napsty** [comment]
Same here - setup page was blank after a new install (new machine, new OS). Only appeared once I installed libapache2-mod-php

    apt-get -y install php7.0 libapache2-mod-php7.0

**Comment by mtdeguzis** [comment]
Just to chime in if it helps anyone out there. I had to install incingaweb2 via rpms to get the schema to install, I guess in doing so, I would only get this, even with php packages installed:

```
<?php
/*! Icinga Web 2 | (c) 2014 Icinga Development Team | GPLv2+ */
require_once '/usr/share/php/Icinga/Application/webrouter.php';
```

I reinstall the php packages and all was well:

```
yum reinstall -y bash-completion php php-ZendFramework php-ZendFramework-Db-Adapter-Pdo-Mysql php-ZendFramework-Db-Adapter-Pdo-Pgsql php-gd php-intl php-pecl-imagick
```
