### ISSUE TITLE
[dev.icinga.com #11870] side loading behavior while filter definition

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2441]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11870

**Created by mnardin on 2016-06-01 10:02:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-01 10:02:23 +00:00 (in Redmine)_

---

Hi,
I would like to understand the side loading behavior while there is a filter definition going on.
I'm experiencing the following behavior while working with filters in the history section. For example event overview:
- default loading time with no filter is around 15 seconds
- if I click the modify filter icon I have to wait 10 seconds again
- on any interaction with the filter I have to wait additional 10 seconds

Probably my mysql instance is not configured properly, but at the moment the simplest historic search "costs" me some minutes.

Would it be possible to define the filter with the various criteria and load the page only after clicking "apply"?

Best regards
Mirko

---

**Relations**:

* blocks [#11870](https://dev.icinga.com/issues/11870)

**Comment by nilmerg** [comment]
Will be tackled with #4094.
