### ISSUE TITLE
[dev.icinga.com #11920] Add to dashboard: wrong url makes whole dashboard unusable

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2452]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11920

**Created by lum3n on 2016-06-09 11:27:21 +00:00**

Assignee: _elippmann_
Status: _Resolved_  (closed on _2016-09-12 06:25:06 +00:00_)
Target Version: _2.4.0_
Last Update: _2016-09-12 06:25:06 +00:00 (in Redmine)_

---

Hello,

today we stumbled upon a situation in which a user is able to make his dashboard unusable.

When adding a page to the personal dashboards (/icingaweb2/dashboard/new-dashlet?url=selected\_page), an url is suggested in the input field. If you replace it with an external site, like http://someothersite, it will cause the .ini-entry to look like this:

    [dashboard_name.dashlet_name]
    url = ""
    title = "dashlet_name"

Afterwards accessing icingaweb2/dashboard isn't possible anymore due to the error "Cannot create dashboard dashlet "dashlet\_name" without valid URL".

Adding external icingaweb2 instances like http://anothericingaserver/icingaweb2/somesite do work. Maybe due to the feature of pasting whole urls with filter, parameter, etc.

I think there should be either a validation that prevents users from adding external sites or at least the display of an emty page / hint afterwards without breaking the whole dashboard. :)

Regards,
Ken

**Changesets**

_2016-08-31 13:11:55 +00:00_ by _aklimov_ fa113e023b658470c13756bd463d8b64d29db95b

    dashboard/new-dashlet: don't allow external URLs
    
    refs #11920

_2016-09-09 13:20:45 +00:00_ by _elippmann_ 5845d6c0cbf02040d43692e4c743dfad732a825d

    Optimize imports in DashletForm
    
    refs #11920

_2016-09-09 13:21:06 +00:00_ by _elippmann_ 1f980f92f2bafc36ba7817ec7a2459839a8b1157

    Optimize imports in InternalUrlValidator
    
    refs #11920

_2016-09-09 13:22:24 +00:00_ by _elippmann_ ef7be98e0c29eeeb4b35933adb8e98edae0c8c66

    Simplify InternalUrlValidator::isValid()
    
    refs #11920

_2016-09-09 13:22:48 +00:00_ by _elippmann_ 4398267db5e974399572dc232aefadb18d0204a0

    Merge branch 'bugfix/wrong-url-makes-whole-dashboard-unusable-11920'
    
    fixes #11920

**Comment by phenomic01** [comment]
adding a url with a "/" as prefix is leading to a crash and a non recoverable error as well.
e.g.  	"/monitoring/list/services?service_state!=0&service_acknowledged=0"

could you please reopen this ticket?

**Comment by dnsmichi** [comment]
I'd suggest to open a new issue, as it partially differs to the OP's issue.
