### ISSUE TITLE
[dev.icinga.com #11952] Allow changing default of 'sticky' in acknowledgement and other command options

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2456]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11952

**Created by davidc on 2016-06-15 22:51:33 +00:00**

Assignee: _elippmann_
Status: _Resolved_  (closed on _2016-12-08 13:30:02 +00:00_)
Target Version: _2.4.0_
Last Update: _2016-12-08 13:30:02 +00:00 (in Redmine)_

---

I would like to be able to change the default value of "sticky acknowledgement" in the "acknowledge service/host problem" pages.

Currently it appears to be hardwired to true in AcknowledgeProblemCommandForm.php

Perhaps the default choice can be made a system-wide configuration option.

(If I acknowledge a service in WARNING, I want to be alerted again if it goes CRITICAL, so in my case users have to remember to turn 'sticky' off, and they don't).

**Changesets**

_2016-12-07 10:10:07 +00:00_ by _(unknown)_ 7717e343ed002822a965f844097ddcd3a7e01737

    Command forms: make the defaults of all checkboxes configurable
    
    refs #11952

_2016-12-07 10:44:06 +00:00_ by _(unknown)_ 3416121f92dd0c8f0967b2f83d244e3d324a1b98

    Command forms: make the defaults of some checkboxes non-configurable again
    
    refs #11952

_2016-12-07 15:53:53 +00:00_ by _(unknown)_ 7253fbcfa44d0d4f2d28d31a12b8a627bb092d02

    Command forms: make the defaults of some checkboxes configurable
    
    refs #11952

_2016-12-08 11:27:45 +00:00_ by _(unknown)_ f7b7f172535d923cf1abfb96e9137ca23deab310

    Command forms: make the defaults of some checkboxes configurable
    
    refs #11952

_2016-12-08 13:23:03 +00:00_ by _elippmann_ aee4c4e6a8c09f214f5cd49b55903f6373ea0034

    Merge branch 'feature/allow-changing-default-of-command-options-11952'
    
    resolves #11952

---

**Relations**:

* relates [#11952](https://dev.icinga.com/issues/11952)

**Comment by tobiasvdk** [comment]
Documentation is missing or at least at default config.

For me it's not working with the following configuration. Therefor I opened #2644.
```
cat /etc/icingaweb2/modules/monitoring/config.ini
[settings]
acknowledge_persistent = "false"
acknowledge_notify = false
```
