### ISSUE TITLE
[dev.icinga.com #12190] Offer a way to control session expiration time

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2492]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12190

**Created by Manul on 2016-07-20 21:49:54 +00:00**

Assignee: _Manul_
Status: _Resolved_  (closed on _2016-07-21 20:29:23 +00:00_)
Target Version: _(none)_
Last Update: _2016-07-25 09:24:41 +00:00 (in Redmine)_

---

Currently, a session seems to time out after about 10-15 minutes. So, after that time users have to log in again if revisiting. Please consider adding an option to modify that timespan.

**Comment by Seb35** [comment]
I also experienced this issue and solved the same way (PHP’s gc-maxlifetime).

It can be mentionned that Icinga Web 2 deactivates the regular requests when the tab is hidden (event onvisibilitychange); it is useful to avoid unuseful requests, but it indeed has this side effect (until the "remember me" feature is not implemented).
