### ISSUE TITLE
Keep tabs in exception view

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2496]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12218

**Created by mfrosch on 2016-07-25 08:13:36 +00:00**

I noticed that the exception view is overriding every tab set by the controller.

It should be helpful to keep any tab that is set and activated, and only add an "Error" tab when there is no tab yet.

**Comment by nilmerg** [comment]
I just looked whether that's quickly possible or not. It's not. I also think this isn't worth it as there's no standard way to access a controller's tabs. Not even with the ipl now. Also, most of the time the tabs are set at runtime of an action.

So, not happening.
