### ISSUE TITLE
[dev.icinga.com #12273] IDO: not all downtime information appear in history (Icingaweb2)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2501]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12273

**Created by mnardin on 2016-08-01 13:13:40 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-07 23:10:37 +00:00 (in Redmine)_

---

Hi,
I've noticed that not all downtime relevant entries are shown in Icingaweb2. This is very confusing.

This are the entries that are shown through the web:

    host_name   host_display_name   service_description service_display_name    object_type timestamp   state   output  type
    server01    server01    CHECK01 CHECK01 State   service 1470048500  -1  [unarm] downtime-test   dt_end
    server01    server01    CHECK01 CHECK01 State   service 1470039025  -1  [unarm] downtime-test   dt_end
    server01    server01    CHECK01 CHECK01 State   service 1469776545  -1  [unarm] test-downtime-api   dt_end
    server01    server01    CHECK01 CHECK01 State   service 1470052678  -1  [unarm] Test Icingaweb2 dt_end

This are the db entries from icinga\_downtimehistory:

    downtimehistory_id,"instance_id","downtime_type","object_id","entry_time","author_name","comment_data","internal_downtime_id","triggered_by_id","is_fixed","duration","scheduled_start_time","scheduled_end_time","was_started","actual_start_time","actual_start_time_usec","actual_end_time","actual_end_time_usec","was_cancelled","is_in_effect","trigger_time","name","endpoint_object_id"
    23884,"1","1","17555","2016-07-28 00:01:19","unarm","daily-downtime-api","679","0","1","0","2016-07-29 23:00:00","2016-07-30 07:40:00","0","0000-00-00 00:00:00","0","0000-00-00 00:00:00","0","0","0","0000-00-00 00:00:00","server01!CHECK01!icingam01-p-1469656879-202","5"
    24083,"1","1","17555","2016-07-29 00:01:17","unarm","daily-downtime-api","622","0","1","0","2016-08-01 23:00:00","2016-08-02 07:40:00","0","0000-00-00 00:00:00","0","0000-00-00 00:00:00","0","0","0","0000-00-00 00:00:00","server01!CHECK01!icingam01-p-1469743277-142","5"
    24201,"1","1","17555","2016-07-30 00:01:11","unarm","weekend-downtime-api","558","0","1","0","2016-08-05 23:00:00","2016-08-08 07:40:00","0","0000-00-00 00:00:00","0","0000-00-00 00:00:00","0","0","0","0000-00-00 00:00:00","server01!CHECK01!icingam01-p-1469829671-76","5"
    24464,"1","1","17555","2016-08-01 00:01:17","unarm","daily-downtime-api","821","0","1","0","2016-08-02 23:00:00","2016-08-03 07:40:00","0","0000-00-00 00:00:00","0","0000-00-00 00:00:00","0","0","0","0000-00-00 00:00:00","server01!CHECK01!icingam01-p-1470002477-339","5"
    24103,"1","1","17555","2016-07-29 09:10:51","unarm","test-downtime-api","487","0","1","0","2016-07-29 09:10:00","2016-07-29 09:15:00","1","0000-00-00 00:00:00","0","2016-07-29 09:15:45","728555","0","0","0000-00-00 00:00:00","server01!CHECK01!icingam01-p-1469776251-1","5"
    24489,"1","1","17555","2016-08-01 09:55:49","unarm","test-downtime-api","494","0","1","0","2016-08-01 10:00:00","2016-08-01 10:10:00","0","0000-00-00 00:00:00","0","2016-08-01 10:10:25","354506","0","0","0000-00-00 00:00:00","server01!CHECK01!icingam01-p-1470038149-5","5"
    24504,"1","1","17555","2016-08-01 12:46:00","unarm","test-downtime-api","492","0","1","0","2016-08-01 14:00:00","2016-08-05 15:00:00","0","0000-00-00 00:00:00","0","2016-08-01 12:48:20","887528","1","0","0000-00-00 00:00:00","server01!CHECK01!icingam01-p-1470048360-2","5"
    24507,"1","1","17555","2016-08-01 12:55:35","unarm","Test Icingaweb2","491","0","1","0","2016-08-01 12:56:20","2016-08-01 13:57:20","0","0000-00-00 00:00:00","0","2016-08-01 13:57:58","713293","0","0","0000-00-00 00:00:00","server01!CHECK01!icingam01-p-1470048935-0","5"

Only entries where the field actual\_end\_time is set will appear in the history tab of the service.

Just out of curiosity: when will an expired downtime be purged from icinga\_downtimehistory?

Mirko

**Comment by gitmirko** [comment]
Hi,
this issue is still present in 2.6.1.
We often miss the "DOWNTIME END" entry in the history.

Mirko

**Comment by xenuser** [comment]
I second this. The end of downtimes is often not displayed within Icingaweb2, while "icinga2 object list" shows the correct scheduled downtime end. This causes a lot of confusion since users are asking wether their downtime ends correctly or if they did something wrong.

**Comment by dnsmichi** [comment]
Keep in mind that fixed downtimes will always be started (thus triggering an insert into the historical tables) and their actual_start_time and actual_end_time column is always populated. Flexible downtimes are different to that. They'll add a record for the scheduled_start_time and scheduled_time, but if the downtime is never triggered, the actual* columns are never updated. Icinga Web 2 relies on presenting downtimes which have actual_end_time populated (untriggered downtimes won't make much sense for the presenter).

Btw since you mention it - `icinga2 object list` is a static compiled version of the current configuration, it won't highlight the specific runtime state nor IDO columns being updated.

**Comment by xenuser** [comment]
Thanks for the fast reply. You are absolutely right regarding flexible downtimes. I did not mention earlier that I encounter this issue with fixed downtimes.

> Btw since you mention it - icinga2 object list is a static compiled version of the current configuration, it 
> won't highlight the specific runtime state nor IDO columns being updated.
By "highlight" you mean that "icinga2 object list" does not show runtime changes (e.g.) regarding downtimes, but after e.g. an icinga2 restart, it will?

I just want to make sure that I understand correctly, that's all.

**Comment by lippserd** [comment]
That was an Icinga 2 issue and was fixed a long time ago already.
