### ISSUE TITLE
[dev.icinga.com #12289] Search over custom vars results in SQLSTATE[42000]-Error

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2508]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12289

**Created by InTheWild on 2016-08-02 16:13:19 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-07 12:46:19 +00:00 (in Redmine)_

---

Search over custom vars results in SQLSTATE\[4200\]-Error after hitting on "apply". Tested with hosts and services. The error does not occur on search over the standard host-/service-attributes.
Example for an error-mesage (search over the "Standort"-vars with value "it"):

    SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8', query was: SELECT so.name1 AS host_name, SUM( CASE WHEN (ss.problem_has_been_acknowledged + ss.scheduled_downtime_depth + COALESCE(hs.current_state, 0)) > 0 THEN 0 ELSE 1 END ) AS unhandled_service_count FROM icinga_objects AS so
    INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id AND so.is_active = 1
    INNER JOIN icinga_servicestatus AS ss ON ss.service_object_id = so.object_id AND ss.current_state > 0
    INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = s.host_object_id
    INNER JOIN (SELECT ho.object_id FROM icinga_hosts AS h
    INNER JOIN icinga_objects AS ho ON ho.object_id = h.host_object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
    INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
    LEFT JOIN icinga_customvariablestatus AS hcv_standort ON h.host_object_id = hcv_standort.object_id AND hcv_standort.varname = 'standort' COLLATE latin1_general_ci WHERE (hcv_standort.varvalue = 'it') LIMIT 25) AS h ON h.object_id = s.host_object_id GROUP BY so.name1 HAVING (SUM(
    CASE
    WHEN (ss.problem_has_been_acknowledged + ss.scheduled_downtime_depth + COALESCE(hs.current_state, 0)) > 0
    THEN 0
    ELSE 1
    END
    ) > 0)

**Comment by XANi** [comment]
same issue here, icingaweb 2.4.1 with mariadb-server 10.1.

Is there a reason everything is collated to latin1 ? not everyone speaks (and names things) only in english....

**Comment by maniac0s** [comment]
Was send here from the cube Thread on this issue. It happens for me too, on cube as well on graphite plugin. This seems to be a huge problem as it does affect several plugins and it would be nice if this got fixed somehow.

My system installation created the table automatically with utf8mb4 charset. As a workaround I have configured in the my.cnf to use Charset latin1. This suppresses the error however that shouldn't be a permanent solution.

**Comment by vladki77** [comment]
Hello, yesterday I have upgraded icingaweb2 from 2.5.3-1.stretch to 2.6.0-1.stretch (using repository at http://packages.icinga.com/debian), but this problem is still there.

**Comment by lippserd** [comment]
If you have a utf8 database, you must specify utf8 as character set for the database resource in Web 2.

**Comment by vladki77** [comment]
OK, I did not notice that there were 3 DB connections in /etc/icingaweb2/resources.ini
And only one of them [director] had the charset specified at all. Added charset='utf8mb4' to all others. [icinga_ido] and [icingaweb_db]
