### ISSUE TITLE
[dev.icinga.com #12295] group_name_attribute should be "sAMAccountName" by default

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2509]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12295

**Created by mwaldmueller on 2016-08-03 06:21:48 +00:00**

Assignee: _jmeyer_
Status: _Feedback_ 
Target Version: _Backlog_
Last Update: _2017-01-11 10:07:37 +00:00 (in Redmine)_

---

group\_name\_attribute should be "sAMAccountName" by default not "gid"

**Changesets**

_2016-12-20 10:26:22 +00:00_ by _nhilverling_ 23f7544a4c84b5836c3233134f4ea3abf788faf6

    Use placeholder for elements instead of ignore & required
    
    refs #12295

_2016-12-20 10:33:46 +00:00_ by _nhilverling_ 69eaaec512cecca2782e6a2bf4788eeea2590d14

    Use default values while validating user backend
    
    refs #12295

_2017-01-09 15:56:18 +00:00_ by _nhilverling_ 1129a29ef7afbb36bb0660914f5c1842c5da0799

    Use default values while validating user backend
    
    refs #12295

_2017-01-09 16:03:53 +00:00_ by _nhilverling_ 277f4b0ddf7d0f495e463bcff87eb6cbd65419a5

    Form: Return values as null if element has "ignore" and "preserveDefault"
    
    refs #12295

_2017-01-09 16:06:26 +00:00_ by _nhilverling_ 594f2485e3c814494ed4393cf750ea414c409eac

    Form: Unset defaults if element has attribute "disabled" in preserveDefaults
    
    refs #12295

**Comment by nilmerg** [comment]
Will be fixed once #594 is resolved.
