### ISSUE TITLE
[dev.icinga.com #12297] How unreachable services and hosts are displayed

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2510]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12297

**Created by webx on 2016-08-03 10:14:57 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-03 10:14:57 +00:00 (in Redmine)_

---

Hi,

I have the following setup where Icinga is my master node, Host A a satellite, Host B a simple checker : \[Icinga\] ------ \[Host A\] ------ \[Host B\]
Host B is only reachable when Host A is alive, the dependencies are set on the master and, in the database, the "is\_reachable" column of Host B service is set to 0 when Host A goes down.

However, when Host B has a service in critical/warning state and Host A goes down, Host B service still appears in the service problems list with the same severity, and is counted in the problems count.

I think the service should be shown like handled services or those having the "(DOWN)" text because they are just unreachable.
This would give a clearer view on where the problem is.

I am using Icingaweb2 version 2.3.3.

Thanks.
Cyril.

**Comment by lippserd** [comment]
Duplicated by #3355
