### ISSUE TITLE
[dev.icinga.com #12321] Services with same display_name but different object names are separated in service grid

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2518]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12321

**Created by tontonitch on 2016-08-05 14:53:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-11 09:44:39 +00:00 (in Redmine)_

---

Hi,

I discovered that the services with same display\_name but different object names are separated in service grid.
I don't think this is expected, so I open this new issue.

See the screenshot named same\_display\_name\_but\_separated\_in\_grid.png

An exemple of 2 service definitions using the same display\_name:

    apply Service "Linux_cpu" {
      import "generic-service"
      display_name = "Cpu usage"
      check_command = "check_cpu"
      command_endpoint = host.vars.remote_client
      assign where host.vars.remote_client && host.vars.os == "linux"
    }

    apply Service "Windows_cpu_usage" {
      import "generic-service"
      display_name = "Cpu usage"
      check_command = "nscp-local-cpu"
      command_endpoint = host.vars.remote_client
      /*if (host.vars.nscp_cpu) {
            vars += host.vars.nscp_cpu
      }*/
      vars.nscp_arguments += [
            "warn=( load>$nscp_cpu_warning$ and time not in ('1m'))",
            "crit=( load>$nscp_cpu_critical$ and time not in ('1m'))"
      ]
      vars.nscp_cpu_time = [ "1m", "5m", "15m" ]
      vars.nscp_cpu_showall = true
      vars.nscp_cpu_warning = 80
      vars.nscp_cpu_critical = 90
      assign where host.vars.remote_client && host.vars.os == "windows"
    }

Best regards,
Yannick

**Attachments**

* [same_display_name_but_separated_in_grid.png](https://dev.icinga.com/attachments/download/3548/same_display_name_but_separated_in_grid.png) tontonitch - _2016-08-05 14:48:57 +00:00_

**Comment by lippserd** [comment]
Hi,

The criteria to separate objects is the object's name not the display name. It is perfectly valid to have the "windows_cpu" and "linux_cpu" services w/ "CPU" as display name on the very same host.
Granted, it may look a bit odd in your scenario but the uniqueness of the object names is the only thing we can rely on.

Best regards,
Eric
