### ISSUE TITLE
[dev.icinga.com #12410] Click on Host in Service Grid can cause "Invalid Filter" error

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2523]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12410

**Created by InTheWild on 2016-08-12 12:29:32 +00:00**

Assignee: _elippmann_
Status: _Feedback_  (closed on _2016-12-15 09:27:53 +00:00_)
Target Version: _(none)_
Last Update: _2016-12-15 11:18:50 +00:00 (in Redmine)_

---

When i click on a host in the "Service Grid"-Dashlet, and the host has an erroneous service with parenthesis in its name, this action causes an "Invalid Filter" error like the following:

    Invalid filter "(service_description=Oracle%20Invalid%20Objects%20ORADBC1|service_description=Oracle%20Invalid%20Objects%20ORADBP1|service_description=Oracle%20RedoLog%20Switch%20Interval%20ORADBP1|service_description=Oracle%20Rollback%20Segment%20Block%20Contention%20ORADBP1|service_description=Oracle%20Rollback%20Segment%20Header%20Contention%20ORADBP1|service_description=Oracle%20SGA%20Librarycache%20Hit%20Ratio%20(Gets)%20ORADBC1|service_description=Oracle%20SGA%20Librarycache%20Hit%20Ratio%20(Gets)%20ORADBP1|service_description=Oracle%20SGA%20Librarycache%20Hit%20Ratio%20(Gets)%20ORADBT1|service_description=Oracle%20Soft%20Parse%20Ratio%20ORADBP1|service_description=Oracle%20Tablespace%20Usage%20ORADBP1)&host_name=myserver.local.de", unexpected ) at pos 492

    #0 /usr/share/php/Icinga/Data/Filter/FilterQueryString.php(200): Icinga\Data\Filter\FilterQueryString->parseError(')')
    #1 /usr/share/php/Icinga/Data/Filter/FilterQueryString.php(247): Icinga\Data\Filter\FilterQueryString->readFilters()
    #2 /usr/share/php/Icinga/Data/Filter/FilterQueryString.php(31): Icinga\Data\Filter\FilterQueryString->parseQueryString('(service_descri...')
    #3 /usr/share/php/Icinga/Data/Filter/Filter.php(235): Icinga\Data\Filter\FilterQueryString::parse('(service_descri...')
    #4 /usr/share/php/Icinga/Web/Widget/FilterEditor.php(89): Icinga\Data\Filter\Filter::fromQueryString('(service_descri...')
    #5 /usr/share/php/Icinga/Web/Widget/FilterEditor.php(261): Icinga\Web\Widget\FilterEditor->getFilter()
    #6 /usr/share/php/Icinga/Web/Controller.php(223): Icinga\Web\Widget\FilterEditor->handleRequest(Object(Icinga\Web\Request))
    #7 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(622): Icinga\Web\Controller->setupFilterControl(Object(Icinga\Module\Monitoring\DataView\ServiceStatus), NULL, NULL, Array)
    #8 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(163): Icinga\Module\Monitoring\Controllers\ListController->filterQuery(Object(Icinga\Module\Monitoring\DataView\ServiceStatus))
    #9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ListController->servicesAction()
    #10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('servicesAction')
    #11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #12 /usr/share/php/Icinga/Application/Web.php(384): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #13 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
    #14 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
    #15 {main}

</pre>
Original name of the service is "Oracle SGA Librarycache Hit Ratio (Gets) ORADBP1".

**Changesets**

_2016-12-15 11:13:47 +00:00_ by _(unknown)_ f9f513f8c07912689e29c07683d5e774639479cc

    Query string parser: support brackets in values
    
    refs #12410

**Comment by Al2Klimov** [comment]
Note for the future myself:
`()` shall be rendered as `%28%29` (double encoding). That's the actual error.
