### ISSUE TITLE
[dev.icinga.com #12431] If CheckSource != Object, the icon is wrong when either is in a different state

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2524]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12431

**Created by TheFlyingCorpse on 2016-08-14 18:42:05 +00:00**

Assignee: _elippmann_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2017-01-10 08:11:59 +00:00 (in Redmine)_

---

If CheckSource != Object, the icon is wrong when Object is in a different state than CheckSource (and the other way).

It doesnt account for it in the code here:

    icingaweb2/modules/monitoring/application/views/scripts/show/components/checksource.phtml

**Changesets**

_2016-12-19 16:18:14 +00:00_ by _(unknown)_ 7450dd5811a885e4a1e9d1b8d984d7fabecd7eef

    Correctly show whether a check source is reachable
    
    refs #12431

**Comment by lippserd** [comment]
I close this in favor of: #2953
