### ISSUE TITLE
[dev.icinga.com #12436] More readable fonts and colors

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2525]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12436

**Created by LarsEngels on 2016-08-15 09:35:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-15 09:35:01 +00:00 (in Redmine)_

---

Some of the default fonts in Icingaweb 2 are hard to read. For example the plugin output font is small, and gray. It would be nice if it could be made a bit darker and maybe one pixel size bigger.

Also, when you select multiple Hosts / Services the turquois background is too bright. It is very hard to see which Hosts / Services are selected.

For both issues it does not matter if the stanard or high contrast theme is selected.

**Comment by lippserd** [comment]
Moved to #3416.
