### ISSUE TITLE
[dev.icinga.com #12478] Prio for display hosts down

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2528]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12478

**Created by ClemensBW on 2016-08-18 11:24:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-18 11:24:18 +00:00 (in Redmine)_

---

Hello,

is it possible to add a "prio" for some hosts in the hosts down listing or for filters?

For example "Datacenter\_Router\_xyz"

Now the filter is: /icingaweb2/monitoring/list/hosts?host\_problem=1&host\_acknowledged=0&sort=host\_severity&modifyFilter=0

host\_severity or sort=host\_display\_name is not efficiently for this (Router A is not enforced more important as Router B), for example a "cust.var.monitoring\_prio =3" for a better prio listing or a regex filter as router "router\_xyz<sup>"\\ ist\\ more\\ important\\ as\\ a\\ switch\\ "switch\_abc</sup>".

**Comment by lippserd** [comment]
Hi,

Sorting by custom variables is possible. You may use sort=_host_monitoring_prio. But unfortunately you can only specify one sort column.

Best regards,
Eric
