### ISSUE TITLE
[dev.icinga.com #12568] Add filter for server|host_problem_hard to allow user to just show hard state problems.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2535]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12568

**Created by GreenRover on 2016-08-27 18:46:47 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-27 18:47:23 +00:00 (in Redmine)_

---

Just an advantage for users the are not interested in problems which are only in soft state.

**Attachments**

* [0001-Add-filter-for-server-host_problem_hard-to-allow-use.patch](https://dev.icinga.com/attachments/download/3611/0001-Add-filter-for-server-host_problem_hard-to-allow-use.patch) GreenRover - _2016-08-27 18:46:45 +00:00_

**Comment by lippserd** [comment]
We already have the `stateType` parameter for that which may be set to `hard`.
