### ISSUE TITLE
[dev.icinga.com #12727] Host / Servicegroups not fully display in IcngaWeb2

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2555]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12727

**Created by smadmin on 2016-09-15 06:45:12 +00:00**

Assignee: _smadmin_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2017-01-11 11:51:43 +00:00 (in Redmine)_

---

In the Icinga Web2 shows not compledet the Host and Service Groups.

**Attachments**

* [web2_servicegroups.png](https://dev.icinga.com/attachments/download/3630/web2_servicegroups.png) smadmin - _2016-09-15 11:20:48 +00:00_ - _servicegroups view at icinga web2_
* [classicui_servicegroups.png](https://dev.icinga.com/attachments/download/3631/classicui_servicegroups.png) smadmin - _2016-09-15 11:20:48 +00:00_ - _servicegroups view at classic ui_

**Comment by lippserd** [comment]
Hi,

I hope that this issue has been fixed w/ one of our v2.6.x releases. If not, please open a new issue.

Best regards,
Eric
