### ISSUE TITLE
[dev.icinga.com #12847] Document how to add additional columns in the monitoring views

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2579]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12847

**Created by elippmann on 2016-10-04 10:10:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-10-04 10:10:23 +00:00 (in Redmine)_

---

---

**Relations**:

* relates [#12847](https://dev.icinga.com/issues/12847)

**Comment by dnsmichi** [comment]
#2972 fixes this issue.
