### ISSUE TITLE
[dev.icinga.com #12851] Common file storage, e.g. /var/lib/icingaweb2

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2582]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12851

**Created by elippmann on 2016-10-04 12:31:44 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-10-04 12:56:25 +00:00 (in Redmine)_

---

## Subtasks

* [x] #3022

**Comment by Al2Klimov** [comment]
blocked by #3022

**Comment by Al2Klimov** [comment]
As discussed w/ @lippserd (offline):

* one subdir in /var/lib/icingaweb2 per use case (eg TLS certs)
* no buckets
