### ISSUE TITLE
[dev.icinga.com #12899] Master Info / Status

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2593]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12899

**Created by ebisu on 2016-10-12 13:01:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-14 09:59:03 +00:00 (in Redmine)_

---

It would be nice to see directly in the Webinterface when Master Instance checks are "late".

For example. My Icinga2 Master Process crashed but there is no indication in the Webinterface.
I can only see it if I go into the details of a check and scroll down (lots of perfdata).

I have one master and two Satellite Zones reporting to the master Instance.

**Comment by Nebelwolf** [comment]
This can be closed. This is already implemented in the latest release.
When the backend is down (late) it shows a red number in front of the system menu. Like with checks.

**Comment by lippserd** [comment]
Thanks for the response.
