### ISSUE TITLE
[dev.icinga.com #12935] disabled show_stacktraces has no effect

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2595]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12935

**Created by mfriedrich on 2016-10-16 14:52:06 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-18 15:53:01 +00:00 (in Redmine)_

---

Explicitly disabling the setting in user preferences including a logout/login has no effect. Still getting those stack traces.

![icingaweb2_preferences_show_stacktraces_bug_01.png](https://dev.icinga.com/attachments/download/3704/icingaweb2_preferences_show_stacktraces_bug_01.png)

![icingaweb2_preferences_show_stacktraces_bug_02.png](https://dev.icinga.com/attachments/download/3703/icingaweb2_preferences_show_stacktraces_bug_02.png)

    [root@icinga2 icingaadmin]# cat /etc/icingaweb2/preferences/icingaadmin/config.ini
    [icingaweb]
    show_stacktraces = "0"
    show_benchmark = "0"
    auto_refresh = "1"

Can be reproduced using the latest "icinga2x" Vagrant box.

**Attachments**

* [icingaweb2_preferences_show_stacktraces_bug_02.png](https://dev.icinga.com/attachments/download/3703/icingaweb2_preferences_show_stacktraces_bug_02.png) mfriedrich - _2016-10-16 14:50:38 +00:00_
* [icingaweb2_preferences_show_stacktraces_bug_01.png](https://dev.icinga.com/attachments/download/3704/icingaweb2_preferences_show_stacktraces_bug_01.png) mfriedrich - _2016-10-16 14:50:38 +00:00_

**Comment by davbizz** [comment]
++
