### ISSUE TITLE
[dev.icinga.com #12950] ActionController::$params includes XDEBUG_SESSION_START=PHPSTORM

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2597]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12950

**Created by aklimov on 2016-10-20 16:00:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-20 16:00:09 +00:00 (in Redmine)_

---

**Comment by Al2Klimov** [comment]
Note:

This isn't a problem for me anymore as I switched to a browser addon which doesn't do such things.
