### ISSUE TITLE
Ability to evaluate dynamic custom var values on demand

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2610]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13083

**Created by tontonitch on 2016-11-08 16:06:44 +00:00**

Hi,

Looking at how the custom variables are showed in Icingaweb2, it may be interesting to make it more human readable.
Indeed:

* for dynamic values based on functions, it is only printed "Object of type 'Function' and I would expect the current value instead/in addition
* for hashes, it is printed as hashes, so understandable for IT persons but not user friendly

Attached a screenshot as an example.

Best regards,
Yannick

**Comment by AurelienFo** [comment]
Did you find a solution for this point?

**Comment by nilmerg** [comment]
No, this suggestion didn't made it yet. Chances are also rather low at this stage, at least for the monitoring module. Though, please add a comment regarding this to https://github.com/Icinga/icingadb-web/issues/117, as it falls into the same topic and there others already showed their interest.
