### ISSUE TITLE
[dev.icinga.com #13089] Improve form appearance

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2611]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13089

**Created by tgelf on 2016-11-08 21:37:10 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-12 14:29:25 +00:00 (in Redmine)_

---

Configuration forms could be improved a lot with very little CSS. Currently they only accidentally might have a fitting color depending on your browser. They do not efficiently use the available space while forcing many labels to wrap. Please have a look at the attached screen-shot, that's what it looks like on my system.

Cheers,
Thomas

**Attachments**

* [web2_screenshot_config.png](https://dev.icinga.com/attachments/download/3791/web2_screenshot_config.png) tgelf - _2016-11-08 21:30:28 +00:00_

**Comment by lippserd** [comment]
Moved to #3416.
