### ISSUE TITLE
[dev.icinga.com #13113] Erraneous rendered event triggered

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2614]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13113

**Created by tgelf on 2016-11-09 16:32:28 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-09 17:53:28 +00:00 (in Redmine)_

---

This happens in current master, v2.3.4 is fine. When a container reloads, all containers (even the unused col3) trigger a rendered event. This is wrong and hurts when you have one container refreshing fast with an overview list and another container with lots of HTML showing related details with no autorefresh but expensive onRendered handler.

**Attachments**

* [web2_rendered_events.png](https://dev.icinga.com/attachments/download/3799/web2_rendered_events.png) tgelf - _2016-11-09 17:46:36 +00:00_

**Comment by lippserd** [comment]
application-state relies on the rendered event. Blacklisting the rendered event for the menu means checking whether the container has the id menu which also consumes "some cycles". So I just leave it as it is and close this issue :).
