### ISSUE TITLE
[dev.icinga.com #13193] Update group memberships upon deleting/editing a user from the database backend

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2622]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13193

**Created by joka66 on 2016-11-15 08:45:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-11-15 08:55:27 +00:00 (in Redmine)_

---

When changing the user name, the icingaweb\_group\_membership relation is not updated. after changing the only administrator accout name and logoff/logon all the monitoring items disappeared -&gt; had to set the icingaweb\_group\_membership manually in db.
Version icinga2 web 2.3.4

---

**Relations**:

* blocks [#13193](https://dev.icinga.com/issues/13193)

**Comment by Thomas-Gelf** [comment]
@lippserd: shouldn't we fix this in our schema?

**Comment by Al2Klimov** [comment]
@Thomas-Gelf Shouldn't we support separate user/group backends?

**Comment by Thomas-Gelf** [comment]
@Al2Klimov: sure, I understand your point. Main use-case for that feature is SSO combined with LDAP/AD. It is for group memberships not under our "direct" control. I wouldn't go too far with this. Sure, someone might want to manage group membership for external users in the DB. But then I'd strongly opt for teaching our DB to learn and/or import those users. This feels a little bit dirty.

Other opinions?

**Comment by Thomas-Gelf** [comment]
@Al2Klimov: could also be evaluated in a dedicated issue, shouldn't hinder you from fixing this the way you proposed in your pull request.

**Comment by Al2Klimov** [comment]
@Thomas-Gelf Yes, it "feels a little bit dirty" to copy users "left-to-right" just to fix this "politically correctly". This brings yet another bunch of race conditions, redundancy and update delays.

**Comment by Al2Klimov** [comment]
Aren't all the LDAP directories known to be "fas as hell" compared to SQL RDBMSs? Or did I misunderstand something during my professional education?

**Comment by Thomas-Gelf** [comment]
Whether they are fat or not depends on the amount of data you put in there :D They usually have no problem with being fat, and they have been built focused on other things than RDMBSs have been. LDAP is scalable and has been designed with replication and distributed setups (even over weak/unreliable links) in mind. A distributed LDAP-setup is fail-safe and eventually consistent, optimized for read- and not for write-loads.

An RDMBS while of course being optimized for relations, puts it's focus on atomicity and various degrees of guarantees when it comes to parallel requests and transactions. Things LDAP usually doesn't bother at all. And, last but not least: LDAP is a tree, while an RDMBS is bad at building trees. But now we are more than OT.

**Comment by Al2Klimov** [comment]
Sorry @Thomas-Gelf, I made a typo (see correction above) which maybe bended my question as whole.

**Comment by Thomas-Gelf** [comment]
This definitively changes the question :laughing: Still, the answer stands. And you're right, LDAP can be fast as hell for read-intensive applications. However, it still strongly depends on how your queries look like. As soon as they're not pointing to DNs or similar, they must have fitting indexes as well. An RDMBS can easily outperform LDAP for many workloads, but will of course have no chance once tree-based lookups come into play.

So, there is no perfect data store out there. Everyone has it's use cases, it's strong sides and it's drawbacks. You have to choose the right tool for the right job. This might leave you with different tools for different jobs - and the task to somehow keep them in sync. That might then lead to compromises on the left or right, as less non-perfect tools together could be faster than more perfect tools with related glue.

So, the statement LDAP being "fast as hell" compared to an RDMBS doesn't stand a closer look, but is of course true for some specific use-cases.
