### ISSUE TITLE
[dev.icinga.com #13329] Recurring downtime

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2628]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13329

**Created by dzalewski on 2016-11-25 12:30:06 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-25 12:37:54 +00:00 (in Redmine)_

---

It would be useful to be able to add recurring downtimes via Icinga Web 2. Similar way you can do in Thruk.

**Comment by lippserd** [comment]
This is feature of the Icinga Director.
