### ISSUE TITLE
[dev.icinga.com #13383] Dashboard doesn't  reload state on the left column in auto-reload

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2632]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13383

**Created by jcarraro on 2016-12-02 09:05:08 +00:00**

Assignee: _jcarraro_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-13 13:40:16 +00:00 (in Redmine)_

---

if the state changed for CRITICAL to OK in auto-reload modi , the state doesn 't change in dashboard in the left column, see screenshot.

**Attachments**

* [5722959.jpeg](https://dev.icinga.com/attachments/download/3863/5722959.jpeg) jcarraro - _2016-12-02 09:04:20 +00:00_

**Comment by Al2Klimov** [comment]
@carraroj As far as I can remember from our investigation/discussion on this, you were going to ask the customer [the question I asked you](https://github.com/Icinga/icingaweb2/issues/2632#issuecomment-273149840). Did they answer you?

**Comment by carraroj** [comment]
@Al2Klimov No, i think you can close this issue, i haven't got a ticket to this issue anymore.
