### ISSUE TITLE
[dev.icinga.com #13425] Put anchors in documentation chapter titles

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2634]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13425

**Created by tofu00 on 2016-12-06 13:33:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-06 16:51:42 +00:00 (in Redmine)_

---

I don't know if this is a simple thing to do with your documentation process but I think that put anchors on documentation pages is good thing (make titles clickable).

Because documentation pages are long, in that way you can keep your position on the page after refresh or restarting your web browser.

This is not a big feature but I think it can make life easier.

**Comment by dnsmichi** [comment]
Should be moved to the doc module repository @lippserd
