### ISSUE TITLE
[dev.icinga.com #13427] Improve error handling when responding to non-HTML requests

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2635]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13427

**Created by medicmomcilo on 2016-12-06 15:43:52 +00:00**

Assignee: _medicmomcilo_
Status: _Feedback_ 
Target Version: _Backlog_
Last Update: _2016-12-26 00:08:41 +00:00 (in Redmine)_

---

Hi friends!

Recently in our infrastructure Nagstamon suddenly stopped working.
After some hours of troubleshooting we identified that this is due to JSON output is not being provided:
/monitoring/list/services?service\_state&gt;0&service\_state&lt;=3&service\_state\_type=1&addColumns=service\_last\_check&format=json

Our assumption is that because of number of criticals it stopped, this can also be confirmed with narrowing down the filter.

You can test this with inclusion of services in OK state if you don't have enough testing criticals. URL for that:
/monitoring/list/services?service\_state&gt;=0&service\_state&lt;=3&service\_state\_type=1&addColumns=service\_last\_check&format=json

Do let me know if there is anything else I can provide to help you investigate this issue further.

Kind regards,
Momcilo.

**Attachments**

* [patch_file.patch](https://dev.icinga.com/attachments/download/3893/patch_file.patch) aklimov - _2016-12-08 15:44:53 +00:00_
* [detect_error.patch](https://dev.icinga.com/attachments/download/3917/detect_error.patch) aklimov - _2016-12-14 12:36:45 +00:00_

**Comment by nilmerg** [comment]
Need to pause here now. Until now only JsonResponse has been adjusted but there are other usages of json_encode() which need to be handled this way.

**Comment by Al2Klimov** [comment]
@nilmerg Souldn't we adjust our Json::encode() and just use it everywhere?

**Comment by nilmerg** [comment]
@Al2Klimov Sure. But we should first verify that the behaviour the referenced commit tries to fix is still valid for PHP 5.6+. (https://github.com/Icinga/icingaweb2/commit/a23b24680c203098c0399f3f9b410fda099e5743#diff-79d5402cca911979dfd9b5217b0264fdR200)

**Comment by Al2Klimov** [comment]
@nilmerg I've taken a look at your change's effect and I'm not quite sure that it's the way(tm). Any non-UTF8 string gets NULL. What about this:

```
On failure:
  For each string (recursively):
    If string is not valid UTF8:
      string = latin1_2_utf8(string)
```

**Comment by Al2Klimov** [comment]
As discussed w/ @nilmerg (offline): `?`s are better.
