### ISSUE TITLE
[dev.icinga.com #13471] Servicegrid Landscape Mode

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2640]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13471

**Created by pooh on 2016-12-08 10:24:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-08 11:18:49 +00:00 (in Redmine)_

---

I like the servicegrid display http://whatever/icingaweb2/monitoring/list/servicegrid very much as a status summary of how all the machines are performing. I use it without "?problems" at the end, to show all machines and services, whatever the colour of the indicators.

However, I (like most people, I suspect) am monitoring more machines than I have services, so the grid ends up being tall and narrow, whereas most display monitors are wider than they are high, so it would be nice to have the facility to show the service grid with machine names across the top and services down the side, to fit more neatly onto a widescreen monitor.

**Comment by lippserd** [comment]
We introduced the restriction `monitoring/blacklist/properties - Hide the properties of monitored objects that match the filter` for that.

**Comment by lippserd** [comment]
Oops. Closed the wrong issue.
