### ISSUE TITLE
Default settings for acknowledgements

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2644]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13537

**Created by tobiasvdk on 2016-12-12 17:17:29 +00:00**

For setting acknowledgements I want to define some defaults, e.g. the expire time should be always "+1 day".

**Comment by log1-c** [comment]
i just tried editing the settings in /etc/icingaweb2/modules/monitoring/config.ini
It works for the "true" setting, but not for false.
Tried:
`[settings]`
`acknowledge_persistent = true`
`acknowledge_notify = true`
and got the options set.
Then edited the file to:
`[settings]`
`acknowledge_persistent = false`
`acknowledge_notify = false`
and now the options are still set...

**Comment by fireba11** [comment]
+1, that might also be useful to be user-specific

**Comment by lippserd** [comment]
Duplicated by #3372
