### ISSUE TITLE
[dev.icinga.com #13553] the notification bar keeps obscuring the bottom status bar [2.4.0-1~debmon8+1]

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2646]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13553

**Created by kowalskimn on 2016-12-13 21:07:29 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-13 21:07:29 +00:00 (in Redmine)_

---

As in description, doing user actions e.g. rescheduling checks pops up the bottom yellow bar that obscures the status bar with service breakdown. That is mildly annoying.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We changed the alignment of the status bar from left to right.

Best regards,
Eric
