### ISSUE TITLE
[dev.icinga.com #13557] Should we really depend on php-pecl-imagick

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2647]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13557

**Created by mfrosch on 2016-12-14 08:25:51 +00:00**

Assignee: _elippmann_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-14 08:25:51 +00:00 (in Redmine)_

---

(RHEL only)

It brings a lot of dependencies to install, do we really need it / require a user to install?

    ===============================================================================================================
     Package                             Arch        Version                      Repository                  Size
    ===============================================================================================================
    Installing:
     icingaweb2                          noarch      2.4.0-2.el6                  icinga-stable-release      1.5 M
    Installing for dependencies:
     GConf2                              x86_64      2.28.0-6.el6                 base                       964 k
     ImageMagick                         x86_64      6.7.2.7-5.el6_8              updates                    1.9 M
     ORBit2                              x86_64      2.14.17-5.el6                base                       168 k
     OpenEXR-libs                        x86_64      1.6.1-8.1.el6                base                       197 k
     apr                                 x86_64      1.3.9-5.el6_2                base                       123 k
     apr-util                            x86_64      1.3.9-3.el6_0.1              base                        87 k
     apr-util-ldap                       x86_64      1.3.9-3.el6_0.1              base                        15 k
     atk                                 x86_64      1.30.0-1.el6                 base                       195 k
     avahi-libs                          x86_64      0.6.25-15.el6_8.1            updates                     55 k
     cairo                               x86_64      1.8.8-6.el6_6                base                       309 k
     cups-libs                           x86_64      1:1.4.2-74.el6               base                       322 k
     fontconfig                          x86_64      2.8.0-5.el6                  base                       186 k
     freetype                            x86_64      2.3.11-17.el6                base                       361 k
     ghostscript                         x86_64      8.70-21.el6                  base                       4.4 M
     ghostscript-fonts                   noarch      5.50-23.2.el6                base                       590 k
     gnutls                              x86_64      2.8.5-19.el6_7               base                       347 k
     gtk2                                x86_64      2.24.23-8.el6                base                       3.2 M
     hicolor-icon-theme                  noarch      0.11-1.1.el6                 base                        40 k
     httpd                               x86_64      2.2.15-55.el6.centos.2       updates                    834 k
     httpd-tools                         x86_64      2.2.15-55.el6.centos.2       updates                     79 k
     icingaweb2-common                   noarch      2.4.0-2.el6                  icinga-stable-release      111 k
     icingaweb2-vendor-HTMLPurifier      noarch      4.8.0-1.el6                  icinga-stable-release      266 k
     icingaweb2-vendor-JShrink           noarch      1.1.0-1.el6                  icinga-stable-release      8.3 k
     icingaweb2-vendor-Parsedown         noarch      1.6.0-1.el6                  icinga-stable-release      9.8 k
     icingaweb2-vendor-dompdf            noarch      0.7.0-1.el6                  icinga-stable-release      2.6 M
     icingaweb2-vendor-lessphp           noarch      0.4.0-1.el6                  icinga-stable-release       37 k
     icingaweb2-vendor-zf1               noarch      1.12.20-1.el6                icinga-stable-release      700 k
     ilmbase                             x86_64      1.0.1-6.1.el6                base                        72 k
     lcms-libs                           x86_64      1.19-1.el6                   base                       100 k
     libICE                              x86_64      1.0.6-1.el6                  base                        53 k
     libIDL                              x86_64      0.8.13-2.1.el6               base                        83 k
     libSM                               x86_64      1.2.1-2.el6                  base                        37 k
     libXcomposite                       x86_64      0.4.3-4.el6                  base                        20 k
     libXcursor                          x86_64      1.1.14-2.1.el6               base                        28 k
     libXdamage                          x86_64      1.1.3-4.el6                  base                        18 k
     libXext                             x86_64      1.3.3-1.el6                  base                        35 k
     libXfixes                           x86_64      5.0.1-2.1.el6                base                        17 k
     libXfont                            x86_64      1.5.1-2.el6                  base                       145 k
     libXft                              x86_64      2.3.2-1.el6                  base                        55 k
     libXi                               x86_64      1.7.4-1.el6                  base                        37 k
     libXinerama                         x86_64      1.1.3-2.1.el6                base                        13 k
     libXpm                              x86_64      3.5.10-2.el6                 base                        51 k
     libXrandr                           x86_64      1.4.2-1.el6                  base                        23 k
     libXrender                          x86_64      0.9.8-2.1.el6_8.1            updates                     24 k
     libXt                               x86_64      1.1.4-6.1.el6                base                       165 k
     libcroco                            x86_64      0.6.2-5.el6                  base                       100 k
     libfontenc                          x86_64      1.1.2-3.el6                  base                        29 k
     libgsf                              x86_64      1.14.15-5.el6                base                       116 k
     libicu                              x86_64      4.2.1-14.el6                 base                       4.9 M
     librsvg2                            x86_64      2.26.0-14.el6                base                       140 k
     libthai                             x86_64      0.1.12-3.el6                 base                       183 k
     libtool-ltdl                        x86_64      2.2.6-15.5.el6               base                        44 k
     libwmf                              x86_64      0.2.8.4-25.el6_7             base                       132 k
     libwmf-lite                         x86_64      0.2.8.4-25.el6_7             base                        51 k
     mailcap                             noarch      2.1.31-2.el6                 base                        27 k
     pango                               x86_64      1.28.1-11.el6                base                       351 k
     php                                 x86_64      5.3.3-48.el6_8               updates                    1.1 M
     php-Icinga                          noarch      2.4.0-2.el6                  icinga-stable-release      304 k
     php-cli                             x86_64      5.3.3-48.el6_8               updates                    2.2 M
     php-common                          x86_64      5.3.3-48.el6_8               updates                    530 k
     php-gd                              x86_64      5.3.3-48.el6_8               updates                    111 k
     php-intl                            x86_64      5.3.3-48.el6_8               updates                     76 k
     php-pear                            noarch      1:1.9.4-5.el6                base                       393 k
     php-pecl-imagick                    x86_64      2.2.2-5.el6                  epel                        85 k
     pixman                              x86_64      0.32.8-1.el6                 base                       243 k
     sgml-common                         noarch      0.6.3-33.el6                 base                        43 k
     urw-fonts                           noarch      2.4-11.el6                   base                       3.1 M
     xorg-x11-font-utils                 x86_64      1:7.2-11.el6                 base                        75 k

    Transaction Summary
    ===============================================================================================================
    Install      69 Package(s)

**Comment by lippserd** [comment]
We'll move away from dompdf in the near future which will reduce our dependencies.
