### ISSUE TITLE
[dev.icinga.com #13563] Hamburger Icon should not waste less space

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2648]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13563

**Created by tgelf on 2016-12-14 10:41:21 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-15 08:46:40 +00:00 (in Redmine)_

---

It should be possible to completely get rid of that empty area by placing it "in" the tab bar.

**Attachments**

* [hamburger.png](https://dev.icinga.com/attachments/download/3939/hamburger.png) mfrosch - _2016-12-15 08:46:21 +00:00_

**Comment by lippserd** [comment]
Moved to #3416.
