### ISSUE TITLE
[dev.icinga.com #13575] Allow DB resource configuration for DB2 and Sqlite

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2649]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13575

**Created by tgelf on 2016-12-14 15:16:59 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-14 15:16:59 +00:00 (in Redmine)_

---

Might be used by modules like the Director as an Import Source or by custom modules for custom tasks.

**Comment by lippserd** [comment]
DB2 has been introduced w/ https://github.com/Icinga/icingaweb2/issues/2932. SQLite will be introduced w/ https://github.com/Icinga/icingaweb2/issues/3381.
