### ISSUE TITLE
[dev.icinga.com #13603] registerHook broken since Icingaweb 2.4

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2650]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13603

**Created by dupondje on 2016-12-15 09:09:17 +00:00**

Assignee: _jmeyer_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-12-16 17:04:46 +00:00 (in Redmine)_

---

Hi,

Yesterday I upgraded Icingaweb to the newest version (2.4).
Everything seems to work fine, except some users were not seeing graphite graphs anymore (from the icingaweb2-module-graphite module).

If I gave a user full permissions (\*), then they were able to see the graphs, did I give them only permissions to the following:
permissions = "module/graphite, module/monitoring, monitoring/command/\*"

Then they were not able to see anything anymore of the graphs.

After adding some debug in the code, I noticed that that in 'Icinga/User.php', the 'can()' function was called with the following argument:
"module/\\Graphite"

where it should be "module/graphite"

The 'can()' function returned false, so no permissions to see the graphs if you had permissions on "module/graphite".
It works of course if you had permissions on '\*'.

Now this seems to be easy to resolve by changing the following line in the run.php from the graphite module

    $this->registerHook('grapher', '\\Icinga\\Module\\Graphite\\Grapher');
    to
    $this->registerHook('grapher', 'Icinga\\Module\\Graphite\\Grapher');

But as almost all modules use that first method, I guess something broke :)

Can this be checked? :)

**Comment by marcofl** [comment]
Hi, 

This is also an issue with our module/grafana (which basically is the graphite module modified into a new module). We temporary worked around it as described in this issue, see: https://github.com/vshn/icingaweb2-module-grafana/pull/3/files

would be great if you could have look into this as with the workaround in place next icingaweb2 update could break it again for us. 

thank you
best regards
Marco

**Comment by mdetrano** [comment]
I came across this problem during some module development also.  Just wondering if in ..library/Icinga/Application/Hook.php , the "lcfirst" function is at all needed?  Are modules not supposed to have capitalized first letters?  Should they be all lowercase....does it matter?

**Comment by Tux12Fun** [comment]
This Problem is pain for our custom modules too. It would be very nice to see this fixed in the next release.

**Comment by lippserd** [comment]
I think we fixed that with version v2.4.1.
