### ISSUE TITLE
Show roles of a user

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2657]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13637

**Created by ClemensBW on 2016-12-16 10:38:28 +00:00**

Hello,

if I want see user details as admin, for local users are only the icingaweb2 usergroups are visable.

https://$url$/icingaweb2/user/list?page=2#!/icingaweb2/user/show?backend=icingaweb2&user=icingaadmin

Can you please add the icingaweb2 roles to this view too?
(and the option to add this user in a role too, linke the usergroup option :o))

**Comment by mtdeguzis** [comment]
Pinging on status of this. I would love to be able to validate what roles a user has.

**Comment by mwaldmueller** [comment]
ref/NC/626825
