### ISSUE TITLE
[dev.icinga.com #13639] manage authorization for custom vars at roles config

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2658]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13639

**Created by ClemensBW on 2016-12-16 10:58:58 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-16 10:58:58 +00:00 (in Redmine)_

---

Hello,

is it possible to add the "custom-vars" in the authorization config for a icingaweb2 role, like the control manage of add comments, run checks modules etcpp?

**Comment by lippserd** [comment]
We introduced the restriction `monitoring/blacklist/properties - Hide the properties of monitored objects that match the filter` for that.
