### ISSUE TITLE
[dev.icinga.com #13721] modul permissions (roles.ini) do not work

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2666]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13721

**Created by Mordecaine on 2016-12-21 16:49:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-09 08:58:28 +00:00 (in Redmine)_

---

When I give a role (in my case the role "test") permission to use the graphite module, then the users with this role are not able to see graphs.
When I change the module to a wildcard in the permission directive, the users are able to see graphs.

activated module: graphite

User can not see graphs:
\[test\]
permissions = "module/graphite, module/monitoring"

User can see graphs:
\[test\]
permissions = "module/\*"

**Comment by lippserd** [comment]
Duplicates #2686
