### ISSUE TITLE
[dev.icinga.com #13741] New, more extensible filter syntax

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2670]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13741

**Created by aklimov on 2016-12-22 15:41:05 +00:00**

Assignee: _jmeyer_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-22 15:41:05 +00:00 (in Redmine)_

---

**Attachments**

* [new-filter-syntax.md](https://dev.icinga.com/attachments/download/3971/new-filter-syntax.md) aklimov - _2016-12-22 15:40:36 +00:00_ - _0.1_

**Comment by lippserd** [comment]
@nilmerg Do you know the point of this issue?

**Comment by nilmerg** [comment]
It was meant as a proposal to integrate all operators (filter capabilities) missing in the current filter renderer/parser. It's not complete in it's current form, though.

**Comment by Thomas-Gelf** [comment]
NB: This is referenced by #2296

**Comment by lippserd** [comment]
Thanks for the details. I strongly discourage continuing w/ this issue because it's a complete was of time.
