### ISSUE TITLE
[dev.icinga.com #13755] Filter after 2 different "Hostgroup Name"

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2671]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13755

**Created by viper539 on 2016-12-23 13:34:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-23 13:34:16 +00:00 (in Redmine)_

---

Hello!

i have mulitple printers on each floor.
Each Printer has a Hostgroup for the Floor and the Devicetype (Printer) assigned.
In icingaweb2 i cannot filter after 2 different Hostgroups.
If i filter for "Hostgroup Name = Printer" AND "Hostgroup Name = 2" (for 2nd Floor) i get an empty list.
This URL is generated:
/icingaweb2/monitoring/list/hosts?hostgroup\_name=drucker&hostgroup\_name=2&modifyFilter=1

Can you help me with that?

Thank you!
viper

**Comment by lippserd** [comment]
Sorry for not responding for ages. The solution should be to replace the AND with the OR operator. This is the pipe instead of the ampersand.

**Comment by lippserd** [comment]
If this does not solve your issue, please have a look at #1649.
