### ISSUE TITLE
[dev.icinga.com #13761] Event Overview broken after Service Query

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2672]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13761

**Created by brainsht on 2016-12-25 14:18:50 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-25 14:18:50 +00:00 (in Redmine)_

---

As soon as I filter my Event Overview by Service Name (with IcingaWeb2 Version 2.4.0), I get this error message:

    Icinga\Module\Monitoring\Backend\Ido\Query\HostnotificationQuery : Got invalid column: service

    #0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(504): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireColumn('service')
    #1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(524): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireFilterColumns(Object(Icinga\Data\Filter\FilterMatch))
    #2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(535): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireFilterColumns(Object(Icinga\Data\Filter\FilterAnd))
    #3 /usr/share/php/Icinga/Data/SimpleQuery.php(272): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->addFilter(Object(Icinga\Data\Filter\FilterAnd))
    #4 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/NotificationhistoryQuery.php(109): Icinga\Data\SimpleQuery->applyFilter(Object(Icinga\Data\Filter\FilterAnd))
    #5 /usr/share/php/Icinga/Data/SimpleQuery.php(272): Icinga\Module\Monitoring\Backend\Ido\Query\NotificationhistoryQuery->addFilter(Object(Icinga\Data\Filter\FilterAnd))
    #6 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/EventhistoryQuery.php(122): Icinga\Data\SimpleQuery->applyFilter(Object(Icinga\Data\Filter\FilterAnd))
    #7 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(494): Icinga\Module\Monitoring\Backend\Ido\Query\EventhistoryQuery->addFilter(Object(Icinga\Data\Filter\FilterAnd))
    #8 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(433): Icinga\Module\Monitoring\DataView\DataView->addFilter(Object(Icinga\Data\Filter\FilterAnd))
    #9 /usr/share/php/Icinga/Web/Widget/FilterEditor.php(341): Icinga\Module\Monitoring\DataView\DataView->applyFilter(Object(Icinga\Data\Filter\FilterAnd))
    #10 /usr/share/php/Icinga/Web/Controller.php(223): Icinga\Web\Widget\FilterEditor->handleRequest(Object(Icinga\Web\Request))
    #11 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(624): Icinga\Web\Controller->setupFilterControl(Object(Icinga\Module\Monitoring\DataView\EventHistory), NULL, NULL, Array)
    #12 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(565): Icinga\Module\Monitoring\Controllers\ListController->filterQuery(Object(Icinga\Module\Monitoring\DataView\EventHistory))
    #13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ListController->eventhistoryAction()
    #14 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('eventhistoryAct...')
    #15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #16 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #17 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
    #18 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
    #19 {main}

</pre>

**Comment by Al2Klimov** [comment]
Hint: cause: fd6ae75

**Comment by phil-or** [comment]
+1 
same Problem for Hosts

**Comment by nilmerg** [comment]
Closed in favor of #3721.
