### ISSUE TITLE
[dev.icinga.com #13765] acknowledgement delete not displayed

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2673]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13765

**Created by ClemensBW on 2016-12-27 08:01:03 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-27 08:01:03 +00:00 (in Redmine)_

---

Hello,

can you please provide the information, that the acknowledgement has been deleted?
Now the old acknowledgement only disapears.

**Comment by leeclemens** [comment]
@ClemensBW, Removing an Acknowledgement displays:
ACKNOWLEDGEMENT REMOVED

This seems to have been resolved at some point and can be closed.
