### ISSUE TITLE
[dev.icinga.com #13911] Show Configured Eventhandler and Eventhandler history in Icingaweb2

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2676]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13911

**Created by MarcusCaepio on 2017-01-09 10:47:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-09 10:47:36 +00:00 (in Redmine)_

---

Hi all,
just configured my first EventHandler in Icinga2 and recognised, that there is no way to see configured eventhandler and eventhandler history in Icingaweb2.
Would be nice to have a chance to see this, because icinga\_eventhandlers is already present in MySQL.

Regards,

Marcus

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Unfortunately there's no full event handler related data in the IDO Web 2 can rely on. But we're working on a new data backend where we're taking this topic into account. I close this one for now.

Best regards,
Eric

refs #2815
refs #2786
