### ISSUE TITLE
[dev.icinga.com #13913] Author missing in /var/log/icingaweb2/icingaweb2.log

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2677]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13913

**Created by mthiel on 2017-01-09 11:09:41 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-09 11:09:41 +00:00 (in Redmine)_

---

We need to monitor any config-change implemented in/via icingaweb2-director by a SIEM-tool. In the web-based activity-log the author of any change is named, but this information is missing in the ASCII-based /var/log/icingaweb2/icingaweb2.log. It would be nice to have this info in both identically.

**Comment by lippserd** [comment]
Hi,

This is rather a director related issue. If this feature is still not implemented, please open a new issue for the director.

Best regards,
Eric
