### ISSUE TITLE
[dev.icinga.com #13945] icingaweb2 doesn't show all service groups in interface 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2679]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13945

**Created by rafifddd on 2017-01-11 11:46:05 +00:00**

Assignee: _rafifddd_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2017-01-11 12:45:06 +00:00 (in Redmine)_

---

the service groups are shown in the database and in icinga IDO
the issue is present in the latest version v2.6.0-5 of IDO and version 2.4.0 of icinga web2

**Attachments**

* [Capture.PNG](https://dev.icinga.com/attachments/download/4017/Capture.PNG) rafifddd - _2017-01-11 12:39:08 +00:00_ - _UI capture_
* [Capture2.PNG](https://dev.icinga.com/attachments/download/4019/Capture2.PNG) rafifddd - _2017-01-11 12:39:17 +00:00_ - _mariaDB capture_

**Comment by kain64** [comment]
Critical issues for us, can somebody point place in the code where we can search issue: sql/php?

**Comment by lippserd** [comment]
Hi,

I think this issue was related to IDO sync problems in Icinga 2 itself. This has been fixed in recent versions. If you still have issues, please open a new issue.

Best regards,
Eric
