### ISSUE TITLE
[dev.icinga.com #13947] Filter Editor for the Event Grid

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2680]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13947

**Created by elippmann on 2017-01-11 12:37:50 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2017-01-11 12:37:50 +00:00 (in Redmine)_

---

**Comment by lippserd** [comment]
Won't be implemented anytime soon.
