### ISSUE TITLE
[dev.icinga.com #13961] Update to icinga.com and drop wiki references

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2682]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13961

**Created by mfriedrich on 2017-01-12 11:28:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-12 11:29:39 +00:00 (in Redmine)_

---

    find . -path ./git -prune -o -type f -exec gsed -i 's/icinga.org/icinga.com/g' {} \;

except lists.icinga.org and .mailmap

**Comment by dnsmichi** [comment]
Duplicates #2687.
