### ISSUE TITLE
[dev.icinga.com #14029] translation should report failures

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2685]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/14029

**Created by tgelf on 2017-01-16 11:45:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-16 11:45:18 +00:00 (in Redmine)_

---

To reproduce this just try to refresh a catalog with a user lacking write permissions. No error is shown, no refresh takes place.

**Comment by kajla** [comment]
It's official? 
https://www.transifex.com/icinga/icinga-web-2/

**Comment by kajla** [comment]
... or this?
https://crowdin.com/project/icingaweb2

**Comment by nilmerg** [comment]
Neither of those is official. We're currently not on any platform like transifex or crowdin. For future questions like this please have a look [here](https://www.icinga.com/community/get-involved/) instead, thank you.

**Comment by kajla** [comment]
Oh, I mean. It's sad news.
Thank you!

**Comment by Thomas-Gelf** [comment]
@kajla: please find information on how to help with translations [here](https://github.com/Icinga/icingaweb2/blob/master/modules/translation/doc/translation.md). I see no benefit in using any of the mentioned platforms. We currently ship English, German, Italian Finnish, Portuguese, Arabic and Russian translations. Not all of them have the same state of completeness, but still, they're there. Also many of our add-on modules are translated.

Cheers,
Thomas

NB: it's not very friendly to hijack completely unrelated issues. This one targets missing error-handling in tools used by our translators.

**Comment by Al2Klimov** [comment]
@lippserd Errm... works 4me.

`ERROR: ErrorException in /vagrant/modules/translation/library/Translation/Util/GettextTranslationHelper.php:409 with message: file_put_contents(/vagrant/modules/monitoring/application/locale/de_DE/LC_MESSAGES/monitoring.po): failed to open stream: Permission denied`
