### ISSUE TITLE
Connection timeout listing remote refs for icingaweb2

### ISSUE THREAD

**Issue by luijar** [Icinga/icingaweb2#2690]
Hello, 

Began seeing this issue today all of the sudden. Not sure what's going on. 

 * git[/usr/share/icingaweb2] action sync
================================================================================
    Error executing action `sync` on resource 'git[/usr/share/icingaweb2]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '128'
    ---- Begin output of git ls-remote "git://git.icinga.org/icingaweb2.git" "v2.3.4*" ----
    STDOUT: 
    STDERR: git.icinga.org[0: 185.11.254.90]: errno=Connection timed out
    **fatal: unable to connect a socket (Connection timed out)**
    ---- End output of git ls-remote "git://git.icinga.org/icingaweb2.git" "v2.3.4*" ----
    Ran git ls-remote "git://git.icinga.org/icingaweb2.git" "v2.3.4*" returned 128
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/icinga2/recipes/server_web2.rb
    
     51: git node['icinga2']['web2']['web_root'] do
     52:   repository node['icinga2']['web2']['source_url']
     53:   revision node['icinga2']['web2']['version']
     54:   user node[node['icinga2']['web_engine']]['user']
     55:   group node[node['icinga2']['web_engine']]['group']
     56: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/icinga2/recipes/server_web2.rb:51:in `from_file'
    
    git("/usr/share/icingaweb2") do
      action [:sync]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      destination "/usr/share/icingaweb2"
      enable_checkout true
      revision "v2.3.4"
      remote "origin"
      checkout_branch "deploy"
      declared_type :git
      cookbook_name "icinga2"
      recipe_name "server_web2"
      repository "git://git.icinga.org/icingaweb2.git"
      user "apache"
      group "apache"
    end
    

Running handlers:
[2017-01-17T15:29:46+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-01-17T15:29:46+00:00] ERROR: Exception handlers complete
Chef Client failed. 10 resources updated in 01 minutes 30 seconds
[2017-01-17T15:29:46+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-01-17T15:29:46+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-01-17T15:29:46+00:00] ERROR: git[/usr/share/icingaweb2] (icinga2::server_web2 line 51) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '128'
---- Begin output of git ls-remote "git://git.icinga.org/icingaweb2.git" "v2.3.4*" ----
STDOUT: 
STDERR: git.icinga.org[0: 185.11.254.90]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
---- End output of git ls-remote "git://git.icinga.org/icingaweb2.git" "v2.3.4*" ----
Ran git ls-remote "git://git.icinga.org/icingaweb2.git" "v2.3.4*" returned 128
[2017-01-17T15:29:46+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

The stack trace does not have much more info than this.

**Comment by lippserd** [comment]
Hi,

Please update your Git origin to GitHub. We migrated all our public repos and issue tracker here.

Best regards,
Eric

**Comment by dgoetz** [comment]
@lippserd: Has anyone opened pull requests for the Puppet modules, Chef cookbooks and Ansible playbooks after migration? Because we should fix this at upstream and not for every single user.

**Comment by lippserd** [comment]
@dgoetz Good point 👍

**Comment by bobapple** [comment]
Good hint!

See: 
https://github.com/Icinga/puppet-icingaweb2/pull/62
https://github.com/Icinga/chef-icinga2/pull/241

Ansible has already the GitHub URL

**Comment by dnsmichi** [comment]
icinga-vagrant is safe, it already uses GitHub for a long time.

**Comment by luijar** [comment]
I noticed those pull requests are still open. Any idea of when they'll get approved/merged? Also, will this also update previous versions of chef-icinga?
