### ISSUE TITLE
Allow using display names instead of usernames 

### ISSUE THREAD

**Issue by tzafke** [Icinga/icingaweb2#2694]
Currently there is no possibility to use Displaynames in Icingaweb. This especially is not very usable in setups with central LDAP authentication having e.g. employee ids as username.

It would be nice to have the possibility to differentiate username for login and display name. Maybe this should be configurable per indivdual backend.

It should cover at least the follwing use cases
- synchronize displayname with LDAP Backend on login
- maintain Displaynames for icingaweb DB Backend
- use displayname for all actions within webfrontend (commenting, acknowledging)
- show displayname (aditionally) in authentication section
-- User-List (icingaweb2/user/list)
-- Group-Member List (icingaweb2/group/show?backend=icingaweb_db&group=Administrators)

Bonus-Level-Use-Case:
- Allow Displaynames also for LDAP-Groups, too (would e.g. allow to use SIDs for Group-Matching instead of group names. So there would be no impact renaming groups in LDAP-Backend)

**Comment by lippserd** [comment]
Hi,

Thanks for the report.

Our idea is to provide a hook for displaying user and group names in Icinga Web 2 and delegate user and group synchronisation to a module which utilises the hook.

Though we won't implement this until someone sponsors this feature.

Best regards,
Eric
