### ISSUE TITLE
icingaweb2 shows "Check Timeperiod" where actually isn't one set

### ISSUE THREAD

**Issue by cloos** [Icinga/icingaweb2#2697]
Hi,

I added to my yum service configuration ```check_period = "9to5"``` and later removed the check_period again. But Icingaweb2 still shows a Check Timeperiod (see attached screenshot).
![icingaweb2_check_timeperiod](https://cloud.githubusercontent.com/assets/165430/22324458/afee762a-e3a9-11e6-8e72-1a57c0ab4bdf.png)

Checking with the icinga api, the also isn't any check_period shown:
```bash
icinga2 object list -t host -n 'hostname' |grep check_period
  * check_period = ""

icinga2 object list -t service -n 'hostname*yum' |grep check_period
  * check_period = ""
```

**Comment by lippserd** [comment]
@Al2Klimov Please test whether this is a bug in Web 2 or Icinga 2. Icinga 2 may not update the database correctly.

Best regards,
Eric

**Comment by Al2Klimov** [comment]
@lippserd Yes, it's an Icinga 2 Core problem.
