### ISSUE TITLE
Notification type filter missing

### ISSUE THREAD

**Issue by darmagan** [Icinga/icingaweb2#2698]
Hi,

in Icingaweb2 the filter type 'Notification Type' is missing. So it's not possible to filter following types for objects:
DowntimeStart
DowntimeEnd
DowntimeRemoved
Custom
Acknowledgement
Problem
Recovery
FlappingStart
FlappingEnd

Regards

**Comment by dnsmichi** [comment]
Such a filter value is not exposed by the DB IDO backend which requires legacy notification filters.

**Comment by lippserd** [comment]
I think the filter for notification_reason is sufficient for now.
