### ISSUE TITLE
Better Explanation of Announcements Time & Date Setting

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2#2699]
The Announcement Setting has no real explanation of how to fill out the time and date setting ! So it would be very kind if there would be an real example which is prefilled in the fields for start and end.

Also an Calendar field would be nice !! for both fields.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. The issue for the date time picker is #1199. I will add a placeholder which explains the format.

Best regards,
Eric
