### ISSUE TITLE
Make User-Group-Membership available as variable in role filterstring

### ISSUE THREAD

**Issue by tzafke** [Icinga/icingaweb2#2703]
It should be possible to user the current users group memberships within the filterstring of a role definition. Find a comprehensive story at the end of the ticket.

Therefore the following config should be possible:

**Icinga2:**
- service1 
-- vars.role_owner = ["<icingaweb2_group1>"]
-- vars.role_operator = ["<icingaweb2_group2"]
-- vars.role_viewer = ["<icingaweb2_group3"]
- service2
-- vars.role_owner = ["<icingaweb2_group4>"]
-- vars.role_operator = ["<icingaweb2_group3"]
-- vars.role_viewer = ["<icingaweb2_group1", "<icingaweb2_group2>" ]

**icingaweb2**
- groups
-- icingaweb2_group1
-- icingaweb2_group2
-- icingaweb2_group3
-- icingaweb2_group4
- roles
--owner
--- filterString: _service_role_owner _contains at least one of_ \<new icingaweb2.currentuser.groups-variable>
--operator
--- filterString: _service_role_operator _contains at least one of_ \<new icingaweb2.currentuser.groups-variable>
-- viewer
--- filterString: _service_role_viewer _contains at least one of_  \<new icingaweb2.currentuser.groups-variable>

**Required Features**
- Create a "icingaweb2.currentuser.groups"-variable and make it available for monitoring/filter/objects
- Find a solution for the required "_contains at least one of_"-operator 
(currently it is possible to use leading and trailing wildcards for filtering array-type-vars, in cases you are sure having namespaces without "substring-conflicts". But for this solution it will be necessary to have an operator (or special format of $_CURRENTUSER.GROUPS$) that will return true if one of the groups the current user is member of is contained in the custom attribut array.

**Why do we need that:**
Use cases with federated stakeholders require more sophisticated rights management for different groups of services (not neccessarilybut possibly configured as a ServiceGroup). In our case we currently differenciate the upper mentioned roles (viewer, operator, owner) with different rights. We have around 400 applications (configured as serviceGroups) with different users/teams. 

Currently we work around that issue with managing roles.ini from outside, resulting in plenty of role definitions, that only differ in one string within the filterstring and the groups assigned to that role. This works fine except:
- changes of the meta Role "owner", will require management from outside --> we can not use the ui for that, because there are plenty roles with same rights (just different filters and members)
- using a single roles.ini for management from outside and via UI for special cases is not very elegant

Remark: may thats the point to think about (optionally) moving roles.ini into database?

**Comment by lippserd** [comment]
Hi,

Thanks for the report.

Custom variable values which are arrays or hashes are written to the database as JSON blob.
Therefore it's impossible for Web 2 to use this custom variables in restrictions in a performant way.

I close this as wontfix.

Best regards,
Eric
