### ISSUE TITLE
comments in .ini files will be ignored

### ISSUE THREAD

**Issue by Mordecaine** [Icinga/icingaweb2#2706]
Hello,

When I do a comment in a ini file in Icingaweb2, the comment will be ignored.

For Example:
/etc/icingaweb2/authentication.ini
[icingaweb2]
backend = "db"
resource = "icingaweb_db"
\# Test

I got the following message:
Fatal error: Uncaught exception 'Icinga\Exception\ConfigurationError' with message 'Ini parser error: File ended in unterminated state 4. (l. 3)' in /usr/share/php/Icinga/File/Ini/IniParser.php:38 Stack trace: #0 /usr/share/php/Icinga/File/Ini/IniParser.php(237): Icinga\File\Ini\IniParser::throwParseError('File ended in u...', 3) #1 /usr/share/php/Icinga/File/Ini/IniParser.php(263): Icinga\File\Ini\IniParser::parseIni('[icingaweb2]?ba...') #2 /usr/share/php/Icinga/Application/Config.php(326): Icinga\File\Ini\IniParser::parseIniFile('/etc/icingaweb2...') #3 /usr/share/php/Icinga/Application/Config.php(397): Icinga\Application\Config::fromIni('/etc/icingaweb2...') #4 /usr/share/php/Icinga/Application/ApplicationBootstrap.php(532): Icinga\Application\Config::app('authentication') #5 /usr/share/php/Icinga/Application/Web.php(95): Icinga\Application\ApplicationBootstrap->setupUserBackendFactory() #6 /usr/share/php/Icinga/Application/ApplicationBootstrap.php(336): Icinga\Application\Web->bootstrap() #7 /usr/share/php/Icinga/App in /usr/share/php/Icinga/File/Ini/IniParser.php on line 38

**Comment by lippserd** [comment]
Hi,

Please use the semicolon `;` for indicating comments in INI files. This is the de facto standard. Some software **may** support the number sign `#` for denoting comments but Web 2 does not.

Best regards,
Eric
