### ISSUE TITLE
Allow to search for the comment string in the event history

### ISSUE THREAD

**Issue by ClemensBW** [Icinga/icingaweb2#2710]
Hello,

is it possible to add at monitoring/list/eventhistory the option to search a comment string (comment_data)?

**Comment by slrcblack** [comment]
I have some end users asking for the same feature. The comment data is where we place the incident ticket number. 

Thanks

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I'm not quite sure whether this a good idea. The event history holds a very large data set and searching for text may take very long since we can't use indices here. I'll update the issue once we decided how we proceed here.

Best regards,
Eric

**Comment by lippserd** [comment]
Our new monitoring module for the Icinga DB will support this.
