### ISSUE TITLE
AWS ELB for icingaweb2 with two instances causes client browsers to crash out of memory

### ISSUE THREAD

**Issue by IkeEichenberger** [Icinga/icingaweb2#2713]
Running icinga and icingaweb2 for a while now on CentOS 6.x.  Have HA setup with master zone two nodes, and checker zone with two nodes, have icingaweb2 available on both master nodes hitting common RDS.  Individually each web2 can be configured behind the ELB and works fine, but when we put both instances in the ELB, the **clients** hitting the web2 servers, quickly run out of memory and browsers crash.  Mostly use firefox, but also issue with IE.  removing an instance from the ELB fixes the problem.

What is the proper way to configure web2 for loadbalancing in AWS using ELB?  Is it possible?  Do we need different RDS's for each web2 instance?  Have tried the couple different ELB parameter settings, with no luck.

**Comment by lippserd** [comment]
Hi,

Sorry for the late reply. I can't help you with this topic. Please head over to our [community support channels](https://www.icinga.com/about/get-involved/).

Best regards,
Eric
