### ISSUE TITLE
icingaweb2 doesn't detect browser timezone

### ISSUE THREAD

**Issue by andrewmiskell** [Icinga/icingaweb2#2716]
I have my timezone in icingaweb2 set to browser so it'll use my browser timezone settings, but it always defaults to UTC.

I checked on several sites to verify the browser timezone is correct and it shows America/Chicago which is correct.

**Comment by Al2Klimov** [comment]
Hello @andrewmiskell!

to reproduce this bug I need (1) your browser version and (2) the value of your cookie `icingaweb2-tzo'.

Best
AK

**Comment by andrewmiskell** [comment]
Safari 10.0.3 on macOS Sierra and Google Chrome 56.0.2924.87 on macOS Sierra

icingaweb2-tzo cookie in Safari:

icingaweb2-tzo	-21600-0	ops.strongmailsystems.com	/	2/8/2017, 9:08:36 AM	22 B		

icingaweb2-tzo cookie in Google Chrome:

Name:	icingaweb2-tzo
Content:	-21600-0
Domain:	ops.strongmailsystems.com
Path:	/
Send for:	Any kind of connection
Accessible to script:	Yes
Created:	Wednesday, February 8, 2017 at 8:08:57 AM
Expires:	Thursday, February 9, 2017 at 8:08:57 AM
