### ISSUE TITLE
Hide check attempt for hard states in history views

### ISSUE THREAD

**Issue by jschanz** [Icinga/icingaweb2#2718]
I'm not sure if this was reported before, but we have a very stage behaviour here, while displaying states of retries in history tab.

Hard state is shown as 1 of 2 instead of 2 of 2

![bildschirmfoto vom 2017-02-06 14-29-31](https://cloud.githubusercontent.com/assets/5750462/22648893/eef05550-ec78-11e6-869a-ee9de193d73f.png)

Also here ... Hard state is shown as 1 of 5 instead as 5 of 5.

![bildschirmfoto vom 2017-02-06 14-33-21](https://cloud.githubusercontent.com/assets/5750462/22648995/5dc4c2a4-ec79-11e6-9352-d67c0b2e1f98.png)

Maybee I'm wrong an this is ok so. Eventually someone could check this.
Thanks ...

**Comment by dnsmichi** [comment]
HARD states reset the counter, and thus are meaningless. Those counts are only important for SOFT states. In your example, 4/5 is the last SOFT state, the 5th attempt will turn into a HARD state.

**Comment by jschanz** [comment]
Is it possible to suppress the counter, if state has turned to a hard state? It looks very strange, if you count from 4 to 1. Not everyone using the interface also uses the mouse over to have a look, what the underlying icons means.

**Comment by Thomas-Gelf** [comment]
Makes sense to me. While for compatibility reasons I wouldn't touch check attempt enumeration in the IDO right now, we should try to hide this confusing fact in the front-end. Icinga Web 2 doesn't show "attempts" for the current state (in case of a hard state) for exactly this reason. Same should also be applied to historic views.
