### ISSUE TITLE
Newline in Icingaweb2 Plugin Output

### ISSUE THREAD

**Issue by darmagan** [Icinga/icingaweb2#2720]
Hi,

in Icingaweb2 newlines are not interpreted in the Plugin Output. It's possible to paste the line into a div with class 'plugin-output' to move it into a newline, but it will also be intended:
`echo '<div class="plugin-output">WARNING (1/2) blabla: (Host: DOWN/Service: CRITICAL [found SYSTEM])<span class="state-critical">[CRITICAL]</span><a href="/icingaweb2/monitoring/service/show?host=blabla&amp;service=service">blabla</a> (Host: DOWN/Service: CRITICAL [found SYSTEM])<span class="state-ok">[OK]</span><a href="/icingaweb2/monitoring/service/show?host=blablamp;service=service">blabla</a></div><div class="plugin-output">Newline<div>'`

So it would be nice if it's possible to get a clean newline in the output.

Regards

**Comment by darmagan** [comment]
the newline char '\n' works.

**Comment by nisabek** [comment]
Hi @fedepires,

Thank you for your contribution, much appreciated!

I left a comment regarding the icon chosen in the notification.

I also rearranged the code a bit, to understand the changes and make it more readable for myself. Please have a look into the changes and feel free to use them if you find this code arrangement better
I hope I didn't break any of your intended logic :)

Regards,
Nune
