### ISSUE TITLE
Enable/Disable notifications for Hostgroups, ServiceGroups

### ISSUE THREAD

**Issue by ktella** [Icinga/icingaweb2#2726]
Please implement

- Enable/Disable notifications for all services on a host when its is selected.
- Enable/Disable notifications for Hostgroups.
- Enable notifications for all services in a hostgroup.
- Enable/Disable notifications for ServiceGroups.
- Enable/Disable notifications for all hosts of a servicegroup.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I close this as duplicate of #2140.

Best regards,
Eric
