### ISSUE TITLE
Documentation: How does fallback authentication work in detail?

### ISSUE THREAD

**Issue by ronator** [Icinga/icingaweb2#2747]
Hi,

icingaweb2 version: 2.4.1
referring to this doc: https://github.com/Icinga/icingaweb2/blob/master/doc/05-Authentication.md

I tried to ask in icinga IRC channel but people are busy. I see a lot discussions going on around here on ldap authentication. The 'module' works great, I implemented it yesterday. Cool stuff!

But the documentation on it really lacks some basic info imho. It says "Authentication methods can be chained to set up fallback authentication methods or if users are spread over multiple places."

- is that 'fallback chain' defined by the order in the resources.ini or authentication.ini?
- where can you see what auth method a certain user is **actually** using while he/she is logged in?

Consider the situation where your Windows AD "has problems" and you cannot auth against it to access icingaweb2. In such cases, you want to make sure you can use local icingaweb2 DB accounts as a fallback.

Now, to keep things transparent for icingaweb2 users, I tested if it is possible to use the same name for an account in two different locations, so I have test.user in Windows AD and test.user in icingaweb2 DB. I even set the same password and tested login. To see if both login works I commented out each backend once. It works. So I left AD and DB auth both active - but with the same password and username set (and no DOMAIN@USER syntax for login) now I cannot tell **what auth method I am actually using.** Checking the icingaweb2 webserver logs didn't reveal anything to me on auth methods.

_Could you please clarify what exactly makes up the auth fallback chain and how I can prefer one backend over another (is it simply the order in resources.ini or authentication.ini)?_

_And if there aren't already any logs that I may have missed, could you please create a way to enable the icingaweb2 admin to see what logged-in accounts are actually using what auth methods?_ 

Especially (since it is possible to use the same name for two user accounts) if I have a new icingaweb2 user and provide AD auth and DB auth as a fallback and issues occur, it is important to know what auth method is causing trouble.

I hope, I explained my issue in an understandable way.

Kindest regards,
ronator

**Comment by lippserd** [comment]
Hi,

Sorry for the late reply. The authentication order is defined by the order of entries in the authentication.ini file. If the first backend files, Web 2 moves on to the second backend and so on. You should configure Web 2 to log to syslog or file in order to know whether and which backend had problems during authentication. Though there is no way at the moment for users to see the auth method they've been authenticated with.

Best regards,
Eric
