### ISSUE TITLE
API call to set Announcement Banner

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2#2749]
It would be nice to have an API Call to set the Icingaweb2 Announcement Banner

**Comment by Al2Klimov** [comment]
Note for the future myself:

Form::$isApiTarget behaves weird :/

**Comment by Al2Klimov** [comment]
`$ curl -SksLH 'Accept: application/json' -u icingaadmin -d '{"message":"lolcat","start":1,"end":1500000000}' http://localhost:8080/icingaweb2/announcements/new`

**Comment by SimonHoenscheid** [comment]
Super, danke dir!
