### ISSUE TITLE
Reset control in the search field not working consistently

### ISSUE THREAD

**Issue by gitmirko** [Icinga/icingaweb2#2753]
Hi,
we are experiencing some problems with the "X"-button (reset) in the search field.
We can reproduce the problem with the following steps:
- search for some host
- click on a host
- in the right tab change to the services tab
- reset button still works
- search again for some host
- click on a host
- in the right tab change to the services tab
- reset no longer working

Icingaweb2: 2.4.1
Browser: FF 51.0.1

In IE 11 the problem is not present.

Best regards
Mirko

**Comment by widhalmt** [comment]
I experienced this myself and a customer of mine told me they have the same problem. So +2 :-)

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Yeah, I can confirm this too.

Best regards,
Eric

**Comment by lippserd** [comment]
@Al2Klimov Please have a look.

**Comment by Al2Klimov** [comment]
Works for me w/ IW2 2.4.1.
Doesn't work even for the first host search w/ current master.

**Comment by lippserd** [comment]
I think you have to wait for the auto-refresh.

**Comment by Al2Klimov** [comment]
Yes I have, just before trying to reset the field. Then I need only one search (on Edge, too).

**Comment by Al2Klimov** [comment]
A reset button resets all form fields to their initial values as if the user didn't change anything. Well, the user didn't change anything... after the auto-refresh.
