### ISSUE TITLE
Wide dashlets overlap the next dashlet

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2#2756]
Hello,
I face an issue with large dashlets.
When a dashlet is quite large, it will be overlapped by the next dashlet.
For exemple, service grids can be quite large. See the attached screenshot for an exemple of overlapping situation. In such a situation, if a dashlet takes too much space to allow a second dashlet to be on its right, it should be moved to the next dashlet line.
Best regards,
Yannick
![dashlet_overlap_with_large grids](https://cloud.githubusercontent.com/assets/600025/22929411/c8a29590-f2bb-11e6-86c6-30a58ee40ae8.png)

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll have a look at this one.

Best regards,
Eric

**Comment by Al2Klimov** [comment]
Hello @Tontonitch,

We're working on this, but you don't have to wait for the fix until the respective version.

You could change the respective dashlet's URL to e.g. `monitoring/list/servicegrid?problems&limit=15%2C20`.

Best,
AK

**Comment by Al2Klimov** [comment]
@Tontonitch Although we have a fix now and you maybe won't have to wait very long, I'd recommend you to fix the URL anyway and forever – just for UX reasons.

**Comment by Tontonitch** [comment]
Hello Alexander,
Tested your solution, so switched the previous default limit=40%2C20 to limit=15%2C20 for the 2 dashlet's URL, and it works.
Thanks 👍
