### ISSUE TITLE
offset in PDF layout

### ISSUE THREAD

**Issue by pcasis** [Icinga/icingaweb2#2760]
Hi, 

I exported all my hosts in PDF and here is what I get as result : 

![selection_034](https://cloud.githubusercontent.com/assets/25147189/22971781/2c5f8672-f377-11e6-93dd-5c19544f6f3f.png)

As you can see there is an offset on the first line.

Regards

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I close this one in favour of icinga/icingaweb2-module-doc#6.

Best regards,
Eric
