### ISSUE TITLE
Disable auto-refresh of inactive tabs

### ISSUE THREAD

**Issue by towolf** [Icinga/icingaweb2#2761]
People here tend to have 1-10 Icinga tabs open, mostly in the background, so the tabs continue to poll the service in the background spamming some DB queries and causing unnecessary load.

Add Javascript based on `visibilityState` to suspend activity when the tab is not active. Grafana added this recently and that helped a lot.

There is no need to update the page when it is not visible.

**Comment by towolf** [comment]
http://caniuse.com/#feat=pagevisibility

**Comment by towolf** [comment]
Something like this:
```javascript
document.addEventListener("visibilitychange", function() {
  var page_visibility = document.visibilityState;
  console.log(page_visibility);
  if (page_visibility == 'visible') {
    icinga.loader.enableAutorefresh()
  } else {
    icinga.loader.disableAutorefresh()
  }
});
```

Can I submit just this as a pull request, or does this require a setting, etc?

In my eye, disabling the auto-refresh when page is not visible should work for everybody.

**Comment by Thomas-Gelf** [comment]
Hi @towolf,

the feature request absolutely makes sense, thank you. Some thoughts:
* Using en/disableAutorefresh does not conflict with a user manually disabling auto-refresh for accessibility reasons, as that is handled on server side. However, I'd still love to have those methods free for interactive use. When explicitly disabling auto-refresh from my browser console, I do not expect it to be switched on each time I shortly switch tab or window
* I'd prefer do slow down auto-refresh by factor 10 or so instead of completely disabling it, that would avoid the effect of seeing something completely outdated for a very short time when "coming back", that could be irritating
* When re-enabling normal auto-refresh we should avoid having all requests firing at once. So in case of a "temporary slow-down" I'd also love to see the last refresh being adjusted/faked accordingly

Thanks,
Thomas

**Comment by towolf** [comment]
Thanks for your ideas @Thomas-Gelf,

I'm not really a web developer and more of a sysadmin who is concerned about unnecessary load patterns on the Icinga database.

I looked at the `loader.js` file for quite a while and I don't really grok the logic there.

- Your use case (be able to use JS console to disable manually) seems a bit exotic. If you use the console in the first place, you can simply disable the `visibilitychange` listener on `document` as well, no?
- I don't think this is necessary. When coming back to the tab then the requests fire immediately and after a split second everything is up-to-date in a snap. 
- I do no see the potential for a `stampeding herd` problem here. This is only about one guys browser tab and just very few requests. Just re-launching your browser to restore the old session is much worse in that regard. Grafana recently implemented this [in the same straight-forward way](https://github.com/grafana/grafana/pull/7219/commits/d4da69483b657c66febcbfabb71db477448502be),
 and they fire off way more requests on the visibility change.

Can the please merge the current state and then we can work on adding more features later?

**Comment by Thomas-Gelf** [comment]
Your web development skills are fine :-)

> Can we please merge the current state and then we can work on adding more features later?

The problem with that approach is that "cleaning it up later on" will not happen for a loooong time because as soon as it got merge there is no more incentive for such task.

**Comment by towolf** [comment]
In that case, please help out here for implementing your ideas.

I want to work now on another bad database problem with Icinga core and submit a PR there.

*relevant screenshot after downtiming 1000 services ...*
![image](https://cloud.githubusercontent.com/assets/345210/24043088/1fe99c56-0b15-11e7-8286-54a0b5ff3d8d.png)

**Comment by Thomas-Gelf** [comment]
@towolf: sure, I will. We scheduled some other improvements for icinga.loader and will not forget this issue as soon as we're going to tackle them.

As it goes to your database problem: while there might be queries in the web interfering with what the core does, it definitively should not look like this. In case you have more related details please let us know in a dedicated issue! As there is probably "everything" overdue I guess you're running with slightly more than 1k hosts and 10k services - so, let's say 12k checks. In case you're running them once a minute this should be somewhere next to 200 queries per second, plus eventual state changes and related events. Before reaching 2k queries a second I wouldn't even care, so the load should (in theory) not be a problem. And while your graph looks more like 400 more pending queries per minute, this shouldn't be an issue unless you suffer from high latencies.

Is there anything locking some tables? Long-running queries in your DBs process list? I've seen similar graphs, but only in much larger environments. When opening a related issue please also mention the exact Icinga version you're using, there have been bugs with "looping comments" in cluster setups some time ago.

And, some related good news: with some other team members I'm currently dedicating most development time to a new/substitute data backend for Icinga 2 as a successor for the IDO. Over the last years we rewrote Core, Web, many Addons. The IDO is one of the very last artifacts from the good old Nagios times. Our new implementation is going to be very fast, tuned for all kinds of dashboards, even large environments with a lot of restrictions in place. The schema is also going to be optimized for reporting-related tasks and you'll probably fire only up to 1% of your current write queries, as we'll not persist volatile information, read: information that changes with every result.

Hammering the database with queries from lot's of tabs will be much more fun - but we'll still implement the "slow down when being in the background" feature, don't worry ;-)

**Comment by towolf** [comment]
kk.

Yesterday we disabled the reverse HTTP proxy for the frontend and just ran the downtime script to have a more isolated view what happens when we set downtimes.

```
UPDATE icinga_downtimehistory SET actual_start_time = FROM_UNIXTIME(1489674022),  actual_start_time_usec = '340641',  is_in_effect = '1',  trigger_time = FROM_UNIXTIME(1489674022),  was_started = '1' WHERE entry_time = FROM_UNIXTIME(1489674017) AND instance_id = 1 AND internal_downtime_id = '792' AND scheduled_end_time = FROM_UNIXTIME(1489684772) AND scheduled_start_time = FROM_UNIXTIME(1489673972);
```

The only thing in `mysqladmin proc` was this UPDATE, 1000 times, each taking more than 1 second. This completely locked the DB.

The filter in the `schedule-downtime` API call was basically `"my_product" in host.vars.product`.


But I will collect more relevant info and make a separate issue in the other repo for this.

This is the other PR I just submitted to reduce the load that are created by 1000 service downtimes. If we only need to do host downtimes then suddenly this problem goes away ...

https://github.com/Icinga/icinga2/pull/5079

**Comment by Thomas-Gelf** [comment]
Thats a good hint. While the query might look expensive, there should be a fitting index. Just to be on the safe side, please show the output of:
```sql
EXPLAIN SELECT downtimehistory_id
  FROM icinga_downtimehistory
  WHERE entry_time = FROM_UNIXTIME(1489674017)
  AND instance_id = 1
  AND internal_downtime_id = '792'
  AND scheduled_end_time = FROM_UNIXTIME(1489684772)
  AND scheduled_start_time = FROM_UNIXTIME(1489673972);
```

Additionally, `SELECT COUNT(*) FROM icinga_downtimehistory` would be interesting.

**Comment by hrld** [comment]
There was no useful index. Should there be more than these?

  PRIMARY KEY (`downtimehistory_id`),
  UNIQUE KEY `instance_id` (`instance_id`,`object_id`,`entry_time`,`internal_downtime_id`),
  KEY `sla_idx_dohist` (`object_id`,`actual_start_time`,`actual_end_time`)

instance_id always 1, object_id not in query. Index not helpful.
With an index on icinga_downtimehistory(instance_id,internal_downtime_id,entry_time) the performance problem is solved.

**Comment by towolf** [comment]
Continue general downtime DB issue here please:

https://github.com/Icinga/icinga2/issues/5080

**Comment by lippserd** [comment]
Hi,

I don't think that we have to slow down the auto-refresh requests. A simple disable/enable seems much more reliable. I would not want to wait until the refresh has been adjusted after switching tabs. There should be also no issue performance-wise.
But the JavaScript functions for enabling and disabling auto refresh MUST behave exactly as they have before. Why should we require web devs to call additional functions? Even worse, we would have to document the behavioural change of the functions and make sure that devs read it. No way. 😄 

I'll update your PR in a second.

Cheers,
Eric
