### ISSUE TITLE
/usr/share/icingaweb2/application/fonts/fontello-ifont/config.css is missing

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2#2764]
Hi All, 
After a fresh install of latest icinga2+icingaweb2+Documentation Module, I had an error in the doc, that the file:
/usr/share/icingaweb2/application/fonts/fontello-ifont/config.css 
was not there. Indeed it wasn't, so I had to copy the config file from my other Icinga Server to get the documentation running.

**Comment by lazyfrosch** [comment]
Please tell us about your environment:

* OS / OS Version
* Install Method
* Package source

**Comment by MarcusCaepio** [comment]
Ubuntu 16.04.2
apt-get install icingaweb2
deb http://packages.icinga.com/ubuntu icinga-xenial main

**Comment by lazyfrosch** [comment]
Put this issue to https://github.com/Icinga/icinga-packaging/issues/4

This should only appear on URL `icingaweb2/doc/style/font`, please comment the other issue if you have problems elsewhere in the webui.

**Comment by dnsmichi** [comment]
The RPMs were fixed a while ago, in case you're looking for that as well. See #2301.
