### ISSUE TITLE
Icingaweb 2 not loaded after initial install with Ansible playbook 

### ISSUE THREAD

**Issue by aflatto** [Icinga/icingaweb2#2768]
Am getting this issue now , using the icinga2-ansible playbook to install and configure the server
using ubuntu xenial:

\<?php /*! Icinga Web 2 | (c) 2014 Icinga Development Team | GPLv2+ */ require_once '/usr/share/php/Icinga/Application/webrouter.php';

dpkg -l |grep php
ii php 1:7.0+35ubuntu6 all server-side, HTML-embedded scripting language (default)
ii php-common 1:35ubuntu6 all Common files for PHP packages
ii php-dompdf 0.6.1+dfsg-2ubuntu1 all HTML to PDF converter
ii php-font-lib 0.2.2+dfsg-2build1 all read, parse, export and make subsets of different fonts
ii php-gd 1:7.0+35ubuntu6 all GD module for PHP [default]
ii php-htmlpurifier 4.7.0-1build1 all Standards-compliant HTML filter
ii php-icinga 2.4.1-1ppa1604+1 all PHP library to communicate with and use Icinga
ii php-imagick 3.4.0rc6-1ubuntu3 amd64 Provides a wrapper to the ImageMagick library
ii php-intl 1:7.0+35ubuntu6 all Internationalisation module for PHP [default]
ii php-ldap 1:7.0+35ubuntu6 all LDAP module for PHP [default]
ii php-mysql 1:7.0+35ubuntu6 all MySQL module for PHP [default]
ii php-xml 1:7.0+35ubuntu6 all DOM, SimpleXML, WDDX, XML, and XSL module for PHP [default]
ii php7.0 7.0.13-0ubuntu0.16.04.1 all server-side, HTML-embedded scripting language (metapackage)
ii php7.0-cli 7.0.13-0ubuntu0.16.04.1 amd64 command-line interpreter for the PHP scripting language
ii php7.0-common 7.0.13-0ubuntu0.16.04.1 amd64 documentation, examples and common module for PHP
ii php7.0-fpm 7.0.13-0ubuntu0.16.04.1 amd64 server-side, HTML-embedded scripting language (FPM-CGI binary)
ii php7.0-gd 7.0.13-0ubuntu0.16.04.1 amd64 GD module for PHP
ii php7.0-intl 7.0.13-0ubuntu0.16.04.1 amd64 Internationalisation module for PHP
ii php7.0-json 7.0.13-0ubuntu0.16.04.1 amd64 JSON module for PHP
ii php7.0-ldap 7.0.13-0ubuntu0.16.04.1 amd64 LDAP module for PHP
ii php7.0-mysql 7.0.13-0ubuntu0.16.04.1 amd64 MySQL module for PHP
ii php7.0-opcache 7.0.13-0ubuntu0.16.04.1 amd64 Zend OpCache module for PHP
ii php7.0-readline 7.0.13-0ubuntu0.16.04.1 amd64 readline module for PHP
ii php7.0-xml 7.0.13-0ubuntu0.16.04.1 amd64 DOM, SimpleXML, WDDX, XML, and XSL module for PHP

dpkg -l |grep icinga
ii icinga2 2.6.2-1ppa1xenial1 amd64 host and network monitoring system
ii icinga2-bin 2.6.2-1ppa1xenial1 amd64 host and network monitoring system - daemon
ii icinga2-common 2.6.2-1ppa1xenial1 all host and network monitoring system - common files
ii icinga2-ido-mysql 2.6.2-1ppa1xenial1 amd64 host and network monitoring system - MySQL support
ii icingacli 2.4.1-1ppa1604+1 all simple CLI tool for Icingaweb2 and its modules
ii icingaweb2 2.4.1-1ppa1604+1 all simple and responsive web interface for Icinga
ii icingaweb2-common 2.4.1-1ppa1604+1 all simple and responsive web interface for Icinga - common files
ii icingaweb2-module-doc 2.4.1-1ppa1604+1 all simple and responsive web interface for Icinga - documentation module
ii icingaweb2-module-monitoring 2.4.1-1ppa1604+1 all simple and responsive web interface for Icinga - monitoring module
ii libicinga2 2.6.2-1ppa1xenial1 amd64 host and network monitoring system - internal libraries
ii php-icinga 2.4.1-1ppa1604+1 all PHP library to communicate with and use Icinga

issue was fixed on the ubuntu after adding the php7.0 and libapache2-mod-php packages, and the ansible code for it was : 

- name: Install PHP requirements
  apt:
    name: "{{ item}}"
    state: present
  with_items:
    - php7.0
    - libapache2-mod-php7.0

**Comment by lazyfrosch** [comment]
So probably this is an issue with the https://github.com/Icinga/icinga2-ansible and not icingaweb2?

**Comment by aflatto** [comment]
ok, can i change the issue or close and replicate it on the ansible ?

**Comment by lazyfrosch** [comment]
Just open a new one there
