### ISSUE TITLE
Icingaweb2 should show the user's (AD) domain

### ISSUE THREAD

**Issue by xenuser** [Icinga/icingaweb2#2770]
I have an Icinga2 and Icingaweb2 installation where multiple AD backends are used:
  * DOMAIN1
  * DOMAIN2

Some users exist in both directories:
  * DOMAIN1\bob.smith
  * DOMAIN2\bob.smith
Some of the users have the same password for both AD domains, some have different ones.

When logging into Icingaweb2, they have no possibility to provide a domain or to select an existing one.
IMHO they should be able to provide one the usual way, e.g. by prefixing it to the user name:
Login: DOMAIN1\bob.smith

And, when being logged into Icingaweb2, the used/"active" domain should show whenever the user name is mentioned so everyone knows which domain this is refering to.

For me, it would be ok to make both things configurable so every Icinga2 installation can choose between the "simple" and "more informative" way of managing/displaying users.

In my eyes, this is of course a feature request, not a bug. However, in larger installations at larger companies, this scenario is very common.

**Comment by Al2Klimov** [comment]
Hello @xenuser,

thank you for your proposal.
We're already working on it. (see #2153)
I'll close this one as a duplicate.

Best,
AK

**Comment by xenuser** [comment]
Hello @Al2Klimov ,

thank you for your reply and pointing me to the other GitHub issue!
