### ISSUE TITLE
Update database permissions in documentation

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2#2772]
The required database permissions on https://github.com/Icinga/icingaweb2/blob/master/doc/02-Installation.md should be updated.

**Comment by lippserd** [comment]
Hi Markus,

What's missing?

Best regards,
Eric

**Comment by mwaldmueller** [comment]
Hi Eric,

thanks for your reply. I'm not quite sure what exactly, but at least CREATE, ALTER, REFERENCES and GRANT are missing. We switched to ALL PRIVILEGES here.

Best regards
Markus

**Comment by dgoetz** [comment]
We should not require this permissions. If you manually configure the database privileges should be fine, if you run the wizard it asks for a privileged account instead of requiring this permissions from the icingaweb2 user.

**Comment by mwaldmueller** [comment]
As discussed offline I agree with Dirk. If we don't have an user with administrative privileges it's better to create the database manually before the wizard. I will open the issue again if something's wrong with that procedure.
