### ISSUE TITLE
Use of custom variables of type array for object filtering in roles.ini 

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2#2773]
Hello, 

That would be great to be able to use custom variables of type array for object filtering in roles.ini 
Example: vars.sections = [ "Infrastructure", "Support" ]

It has been discussed by someone else at https://monitoring-portal.org/index.php?thread/36842-icingaweb2-url-filter-on-array/, in a different context but in fact it should be the same feature.

Best regards,
Yannick

**Comment by lippserd** [comment]
Hi,

Thanks for the report.

Custom variable values which are arrays or hashes are written to the database as JSON blob.
Therefore it's impossible for Web 2 to use this custom variables in restrictions in a performant way.

I close this as wontfix.

Best regards,
Eric

**Comment by mateusz-gozdek-sociomantic** [comment]
Can't [JSON operators](https://www.postgresql.org/docs/10/static/functions-json.html) be used for querying PostgreSQL for solving this? I would find it really useful.
