### ISSUE TITLE
Browser history handling buggy with multiple columns involved

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#2779]
Given Icinga Web 2 with in view (#col2 is shown) and a link in #col2 pointing to _next, navigating `back` using browser controls doesn't work as expected. It should add the full former URL to the stack only once, however it add's two single steps with the last one (the first when going back) being completely unexpected, as it shows a col1/col2 combination that has not been shown before.

**Comment by Thomas-Gelf** [comment]
Hint: you can easily reproduce this by going to `Hostgroups`, click a group, click a host, go back.

**Comment by lippserd** [comment]
Hi Tom,

Thanks for the report. I can confirm this behaviour.

Cheers,
Eric

**Comment by lippserd** [comment]
@Al2Klimov Please have a look at this one.
