### ISSUE TITLE
Exporting PDF Fails with Fatal error:   undefined function "mb_internal_encoding"

### ISSUE THREAD

**Issue by gerhro** [Icinga/icingaweb2#2782]
### Full error Message:
>Fatal error: 
> Call to undefined function Dompdf\mb_internal_encoding() in /srv/icingaweb2/library/vendor/dompdf/src/Dompdf.php on line 282

- icingaweb2 Version: 2.4.0
- Installation from Source
- OS: Centos 7
- PHP Version: 5.4.16

**Comment by dlorych** [comment]
Make sure you have installed a dependency *php-mbstring*.
```bash
sudo yum install php-mbstring
```

**Comment by gerhro** [comment]
thx, it worked
