### ISSUE TITLE
Translation bug credentials German/English mixed

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2#2783]
See Screenshot, maybe refers to eventdb frontend
![image 982679579631](https://cloud.githubusercontent.com/assets/4162281/23500832/ad3107ce-ff31-11e6-9d8e-4dc981388fe7.png)

**Comment by dgoetz** [comment]
So Module is missing translation, why not file a bug against the module?

**Comment by SimonHoenscheid** [comment]
Was not sure where the translation came from. Will close and reopen
