### ISSUE TITLE
Module Documentation should open a new tab

### ISSUE THREAD

**Issue by Hipska** [Icinga/icingaweb2#2785]
Currently when you click to open Documentation tree for a module, it opens in the same tab as the module documentation list. When you then click a title, the article opens in a different panel.

I think it will be more handy if opening the tree as a tab in the same panel is more user friendly if you would like to switch fast between documentation of different modules.

Next to that, maybe different chapters of the documentation might also be wanted to be opened in a separate tab in the right panel.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I close this in favour of icinga/icingaweb2-module-doc#7.

Best regards,
Eric
