### ISSUE TITLE
Feature request: Event Handler Icon

### ISSUE THREAD

**Issue by fir3wall** [Icinga/icingaweb2#2786]
Hello,

Can we have on Web2 interface Icon next to service or somewhere on service tab info that will inform me that I've got event handler for this service? 

And perfectly also on History tab exact time when that event handler was executed. 

Thanks
Dariusz

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Unfortunately there's no full event handler related data in the IDO Web 2 can rely on. But we're working on a new data backend where we're taking this topic into account. I close this one for now.

Best regards,
Eric

refs #2815
