### ISSUE TITLE
non ASCII character are double encoded UTF-8 character

### ISSUE THREAD

**Issue by yagee-de** [Icinga/icingaweb2#2788]
It seems like icingaweb does not handle non ASCII characters well. I noticed it in User objects, that names like "René" apear as "RenÃ©". Further test shows that this problem raises everywhere where I use non ASCII characters in the config file. `icinga2 object list` works as expected.

Installed icinga packages:
```
# rpm -qa|grep icinga
icinga2-libs-2.6.2-1.el7.centos.x86_64
icingaweb2-vendor-HTMLPurifier-4.8.0-1.el7.centos.noarch
icingaweb2-vendor-dompdf-0.7.0-1.el7.centos.noarch
icingaweb2-vendor-JShrink-1.1.0-1.el7.centos.noarch
icinga2-selinux-2.6.2-1.el7.centos.x86_64
icingaweb2-vendor-lessphp-0.4.0-1.el7.centos.noarch
icingacli-2.4.1-1.el7.centos.noarch
icinga2-bin-2.6.2-1.el7.centos.x86_64
icingaweb2-vendor-zf1-1.12.20-1.el7.centos.noarch
icingaweb2-common-2.4.1-1.el7.centos.noarch
icingaweb2-selinux-2.4.1-1.el7.centos.noarch
icinga2-common-2.6.2-1.el7.centos.x86_64
icingaweb2-2.4.1-1.el7.centos.noarch
icinga2-2.6.2-1.el7.centos.x86_64
vim-icinga2-2.6.2-1.el7.centos.x86_64
icingaweb2-vendor-Parsedown-1.6.0-1.el7.centos.noarch
icinga2-ido-mysql-2.6.2-1.el7.centos.x86_64
```

**Comment by yagee-de** [comment]
When clicking "acknowledge" and entering non ASCII text in comment those text are also affected by this issue.

**Comment by epinter** [comment]
I had the same problem, solved with **charset = "latin1"** in icinga_ido resource (resources.ini).

**Comment by lippserd** [comment]
Hi,

Thanks for the report. As mentioned, configuring the resource to use latin1 as character set should solve the issue.

Best regards,
Eric

**Comment by mahadi** [comment]
This also solved it for me
