### ISSUE TITLE
isMemberAttributeAmbiguous() might struggle with strange DNs

### ISSUE THREAD

**Issue by xenuser** [Icinga/icingaweb2#2792]
I am running Icingaweb2 2.4.1 on SLES 12 with two AD backends.

One of the AD backends stores/returns the users the following way (when Icinga2 runs ldapsearches, e.g.):

```

CN=Hoebel\, Valentin (012-Somestring),OU=Users,OU=de,DC=some,DC=addirectory,DC=net


```

When viewing users and Groups from this AD within Icingaweb2, Icingaweb2 fails to resolve the group memberships of the relevant users. 

Now there is this function isMemberAttributeAmbiguous() within LdapUserGroupBackend.php which might struggle with this CN. When I temporarily modify this function and always return 0, the group memberships are resolved within Icingaweb2.

Can you guys please tell me if this is the expected behaviour (e.g. throw out objects/attributes with nasty content) or if there might be some mistake.

Either way, the current situation gave me no clue what went wrong. There were no errors in the logs, it just seems that Icingaweb2 stops the ldapqueries which normally are run when everything works fine (e.g. continue with resolving sAMAccountName attributes after receiving group memberships).

this might relate to #2146

**Comment by tillsc** [comment]
I'm having the same problem here

**Comment by lippserd** [comment]
I think #2924 will help here.

**Comment by lippserd** [comment]
Hi guys,

Do you still have issues w/ the latest Web 2 version?

Best regards,
Eric

**Comment by xenuser** [comment]
Hi Eric,

thanks for asking. Yes, the problem still exists.

**Comment by lippserd** [comment]
Hi,

Thanks for the feedback.

@Al2Klimov Please have a look at this one.

Cheers,
Eric

**Comment by Al2Klimov** [comment]
Hello @xenuser and thank you for reporting!

Please could you share these config files:
* `/etc/icingaweb2/authentication.ini`
* `/etc/icingaweb2/groups.ini`
* `/etc/icingaweb2/resources.ini`

Best,
AK

**Comment by xenuser** [comment]
Hello @Al2Klimov ,

thanks for getting in touch.

Unfortunately, I can observe the bug on a customer system and I am not allowed to share their configs.

I will have a thought about how I can provide the requested data (e.g. replacing sensitive strings, such as customer names, with random strings etc.).

**Comment by xenuser** [comment]
Just an idea. Might it help to provide some user and group DNs which will get obfuscated by me?

I just want to add another information. What should work is that when clicking on a User in Icingaweb2 (and the User comes from an AD), the group memberships should get resolved. This doesn't work either.

**Comment by nilmerg** [comment]
If you turn on debug logging, Icinga Web 2 will log the exact ldapsearch commandline it's using to run queries. You may try that and adjust it so that's returning the same results. We then may be able to see what's going on.

**Comment by xenuser** [comment]
Thanks for the heads up. I will do that and report back.

**Comment by Al2Klimov** [comment]
Hello @xenuser,

I've added a user w/ the same CN as yours to our AD and both users listing (per group) and groups listing (per user) work as expected.

Best,
AK

**Comment by Mikesch-mp** [comment]
This can be closed, was a problem of ldap filters & wrong default domain. Works as expected.

**Comment by Al2Klimov** [comment]
@Mikesch-mp No, it can't – @xenuser discovered the problem in v2.4.1 – and there was no "default domain".

**Comment by Mikesch-mp** [comment]
The main Problem was a ldap filter which he didnt use in the ldap search on the command line. Filter was set to only allow users that are in a named group. Thats then maybe the bug, if you use such a filter, Icingaweb 2.4.x and 2.5.x still cant resolve group membership  of a users.. if you put somthing like 

```ldap
(&(objectClass=organizationalPerson)(memberOf=CN=Test,OU=Groups,OU=Company,DC=CompanyEmea,DC=net))
```
You will get an error if you click on a username in a group and some functionalty will not work with this  (valid) LDAP filter. I solved the problem by removing it (now all members of this AD can login but most will only see empty page) and also removing the not needed default domain, since there is only one.

It would be nice if we could set a filter that only allows members of a group to login without getting all the problems.

Regards,
Carsten

**Comment by Al2Klimov** [comment]
Fine.
