### ISSUE TITLE
group memberships are mixed up when having two AD backends

### ISSUE THREAD

**Issue by xenuser** [Icinga/icingaweb2#2793]
I am running Icingaweb2 2.4.1 on SLES 12 with two AD backends.

Both AD backends have different Base DCs and base DNs for users and groups, but the user names are the same. Example:

CN=Valentin,OU=Users,DC=dir1,DC=net
CN=Valentin,OU=Europe,OU=Users,DC=dir2,DC=net

When adding both ADs as user, group and auth backends to Icingaweb2, it might seem that group memberships might be mixed up. E.g. when clicking on Configuration -> Authentication -> User Backend: dir1 -> Username -> Valentin
In my case, the group memberships of both directories are shown, although I only selected "dir1" as a backend.

My questions are:
* Is this known?
* Is this only a display issue or are the permissions mixed up then?

In my tests, It looked like this is only a display issue, but I would like to know what you think or might have experienced.

This issue might also be somehow related to #2792

**Comment by lippserd** [comment]
Hi,

Thanks for the report. All user group backends are processed if a user logs in. So, if your membership attribute is just the username, you'll have the groups from backends applied.
Icinga Web 2 version 2.5.0 which is scheduled for the end of November will feature domain support for LDAP/AD auth: #2153. Maybe this will help in your case.

Best regards,
Eric
