### ISSUE TITLE
Sidebar problem counter allow filtering

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2#2795]
The Problemcounter on the left side is showing hard and softstates. Would be nice to configure a filter here

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll consider this for one of our next releases.

Cheers,
Eric

**Comment by SimonHoenscheid** [comment]
Thx Eric!

**Comment by MaBauMeBad** [comment]
We have also currently need for this. Is it currently possible to change the Filter like for the Daashboards in the configuration.php ?

**Comment by lippserd** [comment]
Hi,

No, it's not yet possible. We don't have a schedule for this feature unfortunately.

Best regards,
Eric

**Comment by lippserd** [comment]
I close this as duplicate of #3352.
