### ISSUE TITLE
mysql IDO problem on web configuration - no one seems to know how to fix this!

### ISSUE THREAD

**Issue by perskes** [Icinga/icingaweb2#2799]
I'm sorry, but I already typed this problem in 3 forums and I can't seem to find a fix, and no one else either.
I refer to my problem here: https://monitoring-portal.org/index.php?thread/40160-no-icinga-instance-writing-to-ido/

I welcome any questions and I'm willing to answer. Just ask me anything!

**Comment by lippserd** [comment]
Hi,

From your post in the monitoring-portal forum I assume that you've set up your databases wrong. 

Please answer the questions in the forum. I close this issue.

Best regards,
Eric
