### ISSUE TITLE
Leading "/" in URL makes dashboard unusable

### ISSUE THREAD

**Issue by phenomic01** [Icinga/icingaweb2#2804]
adding a url with "/" as prefix resutls in a non recoverable error.
e.g. "/monitoring/list/services?service_state!=0&service_acknowledged=0"
this issue is related to #2452

**Comment by nikkikang** [comment]
Icingaweb2 Version 2.4.1

Full url or leading slash will cause issue (http://icingaserver.example.com/monitoring/list/hosts?hostgroup_name=dmz-servers or /monitoring/list/hosts?hostgroup_name=dmz-servers)

Resulting dashboard.ini
[dashboard.newdashlet]
url = ""
title = "newdashlet"


Cannot create dashboard dashlet "test" without valid URL

#0 /usr/share/php/Icinga/Web/Widget/Dashboard.php(178): Icinga\Web\Widget\Dashboard\Dashlet->__construct('test', '', Object(Icinga\Web\Widget\Dashboard\Pane))
#1 /usr/share/php/Icinga/Web/Widget/Dashboard.php(120): Icinga\Web\Widget\Dashboard->loadUserDashboardsFromFile('/etc/icingaweb2...')
#2 /usr/share/php/Icinga/Web/Widget/Dashboard.php(88): Icinga\Web\Widget\Dashboard->loadUserDashboards()
#3 /usr/share/icingaweb2/application/controllers/DashboardController.php(34): Icinga\Web\Widget\Dashboard->load()
#4 /usr/share/php/Icinga/Web/Controller/ActionController.php(139): Icinga\Controllers\DashboardController->init()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}


Quick Fix Suggestion:  in application/locale/de_DE/LC_MESSAGES/icinga.po 
908 #: /vagrant/application/forms/Dashboard/DashletForm.php:72
909 msgid ""
910 "Enter url to be loaded in the dashlet. You can paste the full URL, including "
911 "filters."

"Enter the icingaweb2 filtering url to be loaded in the dashlet.  For example: monitoring/list/services?service_problem=1"

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll fix that.

Best regards,
Eric
