### ISSUE TITLE
CSV export should create CSV files with ending .csv

### ISSUE THREAD

**Issue by xenuser** [Icinga/icingaweb2#2808]
I noticed that CSV exports via Icingaweb2 create files such as "services", but they don't have an ending (like ".csv").

This is ok for me, but some customers/users use Windows and as you know, Windows won't open Excel or another tool if you double click on a file without file ending.

I therefore would like to suggest that CSV exports come as ".csv".
In an ideal world, one would be able to configure if .csv is wanted or not.

**Comment by cultcom** [comment]
This is a problem for chromium on linux as well. It uses xdg-open to open the file which does not open it in libreoffice but in a text editor.
With ".csv" extension it works properly.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I'll have a look at PR.

Best regards,
Eric
