### ISSUE TITLE
Icingaweb2 ignores port in LDAP resource configuration

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icingaweb2#2812]
I am currently setting up an Icingaweb 2 instance for a customer.

We are required to use the AD global catalog (LDAPS port 3269), so I provided the following configuration:

    [ldap_test_ad]
    type="ldap"
    hostname="ldap.server.host.name"
    encryption="ldaps"
    root_dn="dc=ldap,dc=server,dc=host,dc=name"
    bind_dn="cn=whatever,ou=Users,dc=ldap,dc=server,dc=host,dc=name"
    bind_pw="totally_secret_password"
    port="3269"

Parameters have been validated using ldapsearch and are working fine. 

Expected result: "Validate Configuration" succeeds with the usual validation log:

    Validation Log

    Connect using LDAPS
    LDAP bind to ldap.server.host.name:3269
    (cn=whatever,ou=Users,dc=ldap,dc=server,dc=host,dc=name / ***) successful
    Microsoft Active Directory
    Windows Server 2012 (or newer)
    Supports STARTTLS: True
    Default naming context: dc=ldap,dc=server,dc=host,dc=name

Actual result:

    Failed to successfully validate the configuration: LDAP bind to 
    ldap.server.host.name:3269 (cn=whatever,ou=Users,dc=ldap,dc=server,dc=host,dc=name / ***)
    failed: 
    Can't contact LDAP server

    Validation Log
    Connect using LDAPS
    NOTE: There might be an issue with the chosen encryption. Ensure that the LDAP-Server  
    supports LDAPS and that the LDAP-Client is configured to accept its certificate.
    LDAP bind to ldap.server.host.name:3269 
    (cn=whatever,ou=Users,dc=ldap,dc=server,dc=host,dc=name / ***) failed: 
    Can't contact LDAP server

After some investigation I found that the LDAP connection ignores the configured port (even though it is written to all the error messages), and uses the standard LDAPS port 636 instead.

As a workaround, I added the port number to the host name (which is then ldap.server.host.name:3269), which works (giving xxxx:3269:3269 in the success message) and LDAP authentication works from that point. So it's obvious that the port number, while stored and processed by Icinga Web 2, is **not** used in the actual LDAPS connection.

**Comment by peteeckel** [comment]
Oops ... forgot the version info etc.:

OS: CentOS 7.3
Icinga 2 version: 2.6.2
Icinga Web 2 version: 2.4.1

**Comment by lippserd** [comment]
Hi,

Thanks for the details. Should be fixed in the master branch. If you still have problems, please open a new issue.

Best regards,
Eric
