### ISSUE TITLE
Icinga\Repository::retrieveGeneralizedTime() does not comply w/ RFC4517

### ISSUE THREAD

**Issue by kobmaki** [Icinga/icingaweb2#2816]
The function retrieveGeneralizedTime in the library Repository.php 

https://github.com/Icinga/icingaweb2/blob/master/library/Icinga/Repository/Repository.php

fails, when parsing a timestamps as defined in the RFC4517. (Lightweight Directory Access Protocol (LDAP): Syntaxes and Matching Rules). 

An openldap backend that  delivers timestamp like 20170414172615Z or a timestamp like 199412161032Z isn't parseable by the function. This leads to an error message if debug is enabled in the icingaweb2. 

Another thing is, when you are viewing user information from Configuration -> Authentication -> Users -> (search for a user, then view) User detail information (user/show?backend=icingaweb2&user=aUserName) leads to empty information like "Created At" or "Last Modified". You see only a dash (-).

In the RFC4517 (Lightweight Directory Access Protocol (LDAP): Syntaxes and Matching Rules)

https://www.ietf.org/rfc/rfc4517.txt

you found the syntax definition in section "3.3.13.  Generalized Time".

You want a simple pull request or one that enhance the tests in the https://github.com/Icinga/icingaweb2/tree/master/test/php

**Comment by kobmaki** [comment]
The following array represents 102 diffent valid ANS.1 GeneralizedTime as describe in the RFC4517.

`$testValues=["2001020304", "2001020304Z", "2001020304+08", "2001020304+08Z", "2001020304+0809", "2001020304+0809Z", "2001020304-08", "2001020304-08Z", "2001020304-0809", "2001020304-0809Z", "2001020304.1", "2001020304.1Z", "2001020304.123456", "2001020304.123456Z", "2001020304.123456+08", "2001020304.123456+08Z", "2001020304.123456+0809", "2001020304.123456+0809Z", "2001020304.123456-08", "2001020304.123456-08Z", "2001020304.123456-0809", "2001020304.123456-0809Z", "2001020304,1", "2001020304,1Z", "2001020304,123456", "2001020304,123456Z", "2001020304,123456+08", "2001020304,123456+08Z", "2001020304,123456+0809", "2001020304,123456+0809Z", "2001020304,123456-08", "2001020304,123456-08Z", "2001020304,123456-0809", "2001020304,123456-0809Z", "200102030405", "200102030405Z", "200102030405+08", "200102030405+08Z", "200102030405+0809", "200102030405+0809Z", "200102030405-08", "200102030405-08Z", "200102030405-0809", "200102030405-0809Z", "200102030405.1", "200102030405.1Z", "200102030405.123456", "200102030405.123456Z", "200102030405.123456+08", "200102030405.123456+08Z", "200102030405.123456+0809", "200102030405.123456+0809Z", "200102030405.123456-08", "200102030405.123456-08Z", "200102030405.123456-0809", "200102030405.123456-0809Z", "200102030405,1", "200102030405,1Z", "200102030405,123456", "200102030405,123456Z", "200102030405,123456+08", "200102030405,123456+08Z", "200102030405,123456+0809", "200102030405,123456+0809Z", "200102030405,123456-08", "200102030405,123456-08Z", "200102030405,123456-0809", "200102030405,123456-0809Z", "20010203040506", "20010203040506Z", "20010203040506+08", "20010203040506+08Z", "20010203040506+0809", "20010203040506+0809Z", "20010203040506-08", "20010203040506-08Z", "20010203040506-0809", "20010203040506-0809Z", "20010203040506.1", "20010203040506.1Z", "20010203040506.123456", "20010203040506.123456Z", "20010203040506.123456+08", "20010203040506.123456+08Z", "20010203040506.123456+0809", "20010203040506.123456+0809Z", "20010203040506.123456-08", "20010203040506.123456-08Z", "20010203040506.123456-0809", "20010203040506.123456-0809Z", "20010203040506,1", "20010203040506,1Z", "20010203040506,123456", "20010203040506,123456Z", "20010203040506,123456+08", "20010203040506,123456+08Z", "20010203040506,123456+0809", "20010203040506,123456+0809Z", "20010203040506,123456-08", "20010203040506,123456-08Z", "20010203040506,123456-0809", "20010203040506,123456-0809Z"]`

The fix accepts all 102 test values, the previous one only 11.
Please accept and merge the pull request.

**Comment by lippserd** [comment]
Hi,

Your test values contain several invalid values as per RFC4517:

1) The fraction part is at most one decimal character.
2) The time zone specification is either "Z" or a GMT offset, not both.

When fixing this, our code must not accept those values. I'll add my review to your pull request in a second.

Best regards,
Eric

**Comment by lippserd** [comment]
@Al2Klimov Please have a look at this issue and the PR. We may either process the value in chunks or use a regex for parsing. I found the following regex in my stash. Maybe it helps.

`'/^(?P<year>\d{4,})(?P<month>\d{2,})(?P<day>\d{2,})(?P<hour>\d{2,})(?P<minute>\d{2,}(?P<second>\d{2,}))?(?P<fraction>[,.]\d+)?(?P<zone>[+-])$/';`
