### ISSUE TITLE
Auto refresh interval should be configurable

### ISSUE THREAD

**Issue by xenuser** [Icinga/icingaweb2#2819]
Icingaweb 2.4.1

As a user, I can enable or disable auto refresh (e.g. when viewing a service, the tab reloads every x seconds). But unfortunately I can not configure how often the tab/page is automatically reloaded.

Browsing the code, I found several hard-coded values for auto refresh settings, separated by object type (e.g. service, host..).

I would like to suggest that a user can configure the auto refresh interval for those objects within his profile settings. In addition, there should be a minimal interval, e.g. 5s, in order to prevent hundreds of users from "DoSing" the local webserver.

**Comment by towolf** [comment]
See also: https://github.com/Icinga/icingaweb2/issues/2761

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll think about a solution for this issue but I think that it's a good idea in general to have this configureable.

Best regards,
Eric

**Comment by xenuser** [comment]
Great! Thanks!

**Comment by andral** [comment]
We would also very much like this option. Working with remote (network wise) installations is almost impossible when the GUI refreshes every other second and the connection is slow.
Maybe an additional option to only enable auto refresh if the window / browser is focused? Would reduce the load.

Thanks.

**Comment by lippserd** [comment]
@andral If you want to disable auto-refresh please navigate to **Your username** -> **Preferences** in the menu. For accessibility reasons you also have the possibility to disable auto-refresh via tab navigation. Please reload the browser page to reset your focus and press tab two or three times. The option will appear in the top left corner of Icinga Web 2.

Please also follow this issue #2761 for the reduced load part.

**Comment by larsengels** [comment]
@lippserd Is there any logical reason that the refresh feature is hidden?

**Comment by lippserd** [comment]
@larsengels What do you mean with hidden?

**Comment by larsengels** [comment]
@lippserd There's no button to disable refreshing. You have to know that it exists and use the Tab-"Workaround".

**Comment by lippserd** [comment]
It is in your user preferences.

**Comment by K0nne** [comment]
Are there any news on this topic? 
This whould really improve the usability.

**Comment by Al2Klimov** [comment]
## Idea

A new option in the user preferences with a default of 1.

Every of our (hardcoded) AR intervals gets multiplied with it.

@lippserd @nilmerg Please comment.

**Comment by lippserd** [comment]
Yeah I like the idea with the multiplier.

The preference for that could also be something like `default`, `moderate`, `fast`, `slow`, ...

**Comment by Al2Klimov** [comment]
W/ or w/o `custom`?

**Comment by lippserd** [comment]
Not quite sure yet.

**Comment by nilmerg** [comment]
When I heard that the first time I considered this a joke. :rofl: 

But, on the technical side a factor might be a good thing. The user however must be presented with a dropdown of pre-chosen values if we don't invest much time. If we invest more time a slider would be nice (-----x-----, -------x, --x-----)

**Comment by Al2Klimov** [comment]
Do _you_ also think that typing in 0.25 takes "much time"?

**Comment by nilmerg** [comment]
It's not a matter of time, but one of how it's presented. A slider or simple text is easier to "grasp" than plain number

**Comment by lippserd** [comment]
That's why I opt for a combo box with readable values, e.g. fast, slow, moderate, default.
