### ISSUE TITLE
cannot enable log for icingaweb2

### ISSUE THREAD

**Issue by ruccoon** [Icinga/icingaweb2#2823]
hi,

Recently I am stuck in ldap implementation in icingaweb2. So I try to enable the debug log of icingaweb.

Here is my configs:

/etc/icingaweb2/config.ini
[logging]
log                 = "/var/log/icingaweb2/debug.log"
level               = "debug"
application         = "icingaweb2"

and I restarted icinga2 service:
service icinga2 restart

But when I try to open icingaweb2 and login with ldap user credential, I cannot see any debug log appearing in /var/log/icingaweb2

Could you help check how to enable log for icingaweb2?

Thanks

**Comment by ruccoon** [comment]
the issue is resolved

it is permission issue of log file under /var/log/icingaweb2

**Comment by DocMAX** [comment]
my debug.log gets created, but does not fill. stays at 9 bytes.
