### ISSUE TITLE
Allow for hiding downtimestart and downtimeend events

### ISSUE THREAD

**Issue by leeclemens** [Icinga/icingaweb2#2824]
We have a lot of servers which do not change state very often, but have recurring scheduled downtimes. This adds a lot of clutter to the History tab, making it very difficult to pinpoint the most recent state change.

While a more robust solution may be to add the full filter functionality to the History tab, a quick link to hide/show may prove useful for others as well. Also, the filter would require configuration upon viewing each host/service, so this works more as a saved search/quick search.

**Comment by lippserd** [comment]
Hi,

I updated the PR some time ago but did not comment this issue. It would be better to implement  a control which allows to filter for all event types. I'll close this issue.

Cheers,
Eric
