### ISSUE TITLE
Oracle oci connection: Connection failed Undefined index: port

### ISSUE THREAD

**Issue by rajo** [Icinga/icingaweb2#2826]
Hi there,

I'm having trouble creating an oracle db as a ressource in icingaweb2. Creating the resource fails with the error message

    Connection failed Undefined index: port

What have I done? Installed oracle instantclient 12 basic/devel according to "the underground php and oracle manual" by oracle. I'm using php 7.0 from dotdeb with oci8 installed by pecl. icingaweb is version 2.4.1. The Oracle db is running on a different machine.

When creating a minimalist php script like

    <?php
    $c = oci_connect('user', 'pass', '<ip>/SID');
    $s = oci_parse($c, 'select column from table');
    oci_execute($s);
    while (($res = oci_fetch_array($s, OCI_ASSOC)) != false) {
    echo htmlentities($res['column']) . "<br>";
    }
    ?>

I can successfully connect to the oracle db. Trying to create the ressource via icingaweb2, I'm stuck with the above error message. In order to verify that the same connect string is getting used, I've edited icingaweb2/library/vendor/Zend/Db/Adapter/Oracle.php in lines 121ff and manually hardcoded the connection string to 

        $this->_connection = oci_connect("user","pass","<ip>/SID");

and still receive this error message. From my perspective, the connection strings between the Oracle.php and the minimal test example are identical and I cannot figure out why icingaweb2 is failing here.

If you need further debug information, please tell. 

Best & thanks in advance,
 rajo

**Comment by rajo** [comment]
Okay, I think I'm on to something: 

when I add a 

    print_r($_POST);

to application/forms/Config/Resource/DbResourceForm.php init() I get the following:

    Array ( [type] => db [name] => mydbname [db] => oci [host] => 192.168.1.23 [port_default] => [port] => 1521 [dbname] => 192.168.1.23/mysid [username] => myuser [password] => mypass [charset] => [persistent] => 0 [formUID] => form_config_resource [CSRFToken] => sometoken [resource_validation] => Konfiguration validieren ) 

To me it seems as there is some magic port_default variable which is empty and therefore breaking the port variable. But I can not figure out where port_default is coming from. Grepping the source for this variable leads to ... no hits. *puzzled*

**Comment by rajo** [comment]
another update:

when I create the db ressource manually in ressources.ini like this:

    [myoracledb]
    type = "db"
    db = "oci"host = "192.168.1.23"
    dbname = "192.168.1.23/mySID"
    username = "user"
    password = "pass"

things work out as expected. I can use this ressource in director and read stuff from the oracle db. Hence there seems to be some bug in the validation routine.

**Comment by lippserd** [comment]
Hi,

Thanks for all the details. This should be fixed w/ https://github.com/Icinga/icingaweb2/commit/f02d631aa179dad47d54299040bcb7e8a58d1609.

If you still have problems, please open a new issue.

Cheers,
Eric
