### ISSUE TITLE
Improve select box UI with select2.js

### ISSUE THREAD

**Issue by Kels** [Icinga/icingaweb2#2827]
Hello,
It would be nice to have a better UI for select box with the following features:
- Filter : to find values quickly
- Display all selected values 

I used to work with the following js library, maybe something better exists nowadays.
https://select2.github.io/

Cheers,
Kelson

**Comment by psi-4ward** [comment]
Yay! Pls prioritize this high @lippserd :beers:

**Comment by lazyfrosch** [comment]
I tried this out within a module, actually pretty simple and would make sense in Icingaweb2 in general.

Should I offer an PR? @lippserd

**Comment by Thomas-Gelf** [comment]
Pro:
* it's a nice component
* current default select boxes look terrible, needs improvement anyways

Con:
* +15kB CSS, +66 kB JS - already minified
* it is expensive. We are refreshing DOM a lot, and would be forced to re-apply this behavior again and again - just scanning for fitting elements puts burden on rendering containers with lots of content.
* I couldn't find many select boxes where this could be applied

To get more precise, which select boxes in Web 2 are we talking about? Could someone with super urgent need for this feature please provide a concrete example?

Thanks
Thomas

**Comment by lazyfrosch** [comment]
I'd prefer this feature for director, and other modules.

It might be problematic having multiple modules providing select2...

**Comment by Thomas-Gelf** [comment]
Anything in Icinga Web 2 itself? Director will not be able to benefit from this, it will mostly move away from using classic select boxes for every choice with lots of elements. They slow things down, as you have to load A LOT of data into a form, data that is mostly not needed.

The related issue is [#606](https://github.com/Icinga/icingaweb2-module-director/issues/606). I presented a working prototype at OSMC last year, it just never made it into master :laughing:.  I don't know whether you remember the short video that hast been shown - especially in the filter component used by the assign filter this has been very powerful. So, Director is out here.  Any other specific other module?

**Comment by lazyfrosch** [comment]
Select2 supports AJAX queries on demand, so thats pretty nice...

That could be pretty useful against our API endpoints

**Comment by Thomas-Gelf** [comment]
Sure, they show it in their examples. It would require quite some customizing to get the features the Director prototype had. I absolutely agree that we need a solution here, but just throwing in Select2 doesn't solve much. We might build some prototypes to get a better understanding whether and how this could be helpful, and I'll keep Select2 in mind when working again on the Director component. In the meantime I don't see immediate need for a pull request adding Select2, supposing that it might be useful "somewhere".

Adding auto-completion to the Director was just adding a couple of lines at the time being, so throwing in 80+ kB of (minified) overhead seems a lot. Sure, Select2 comes with lots of features, but we won't use many of them. And I'm not sure whether it would solve some requirements, like working smoothly with the "ExtentsibleSet" (sortable or not). With the requirement to re-request the form from the server on re-ordering (or not, depending on element configuration). Guess at least the latter should be possible with Select2, unsure about the former. I fear that getting Select2 working the way we need would cost more than shipping our own little component.

**Comment by Thomas-Gelf** [comment]
Had a quick look: the related JS code for the Director feature at the time being already made it into master, as it mostly worked fine. Just the server-side part was never merged - so it's not gonna used anywhere. It added 2,8 kB minified JS and 2-300 Bytes of CSS.

**Comment by Kels** [comment]
@Thomas-Gelf 
> To get more precise, which select boxes in Web 2 are we talking about? Could someone with super urgent need for this feature please provide a concrete example?

The user multiple select box in New User Group Member. When the backend users are from LDAP server, the list becomes (very) long. Select2 could help to display selected values and filter the possible values.

The filter select box (Host ..., Service..., ServiceGroup...). When we work with a lot of custom vars, the list become (very) long. It's annoying to scroll a lot in order to find the desired value. Select2 could help to quickly filter on the desired value.
> it is expensive. We are refreshing DOM a lot, and would be forced to re-apply this behavior again and again - just scanning for fitting elements puts burden on rendering containers with lots of content.

Would it be less expensive to activate the select2 behavior only on the click/select trigger on the select box element ?

**Comment by Thomas-Gelf** [comment]
Hi @Kels!

> When the backend users are from LDAP server, the list becomes (very) long

That's definitively a good use-case for server-side auto-completion/suggestions.

> When we work with a lot of custom vars, the list becomes (very) long.

That's where the prototype I wrote last year for Director comes in handy. Please watch the demo at the end of [this recording](https://www.youtube.com/watch?v=T6GBsfeXIZI), the interesting part stats at 46:34. The presentation is German, from autumn 2016. It shows an example for a live filter preview with real data from 10,000+ hosts and 2,000+ different locations.

Nothing special, that kind of completion is no rocket science and you could definitively use Select2 for most of it. The Director-implementation in addition has some hard-coded "understanding" of nested properties like host.vars.*. That way it might eventually offer slightly more comfort, especially when being navigated with the keyboard.

The related [feature request](https://github.com/Icinga/icingaweb2-module-director/issues/606) has been scheduled for Director v1.4.0. Just for fun I enabled it locally right now to create another short screen-cast. It still works, here is how it looks like:

![director_autocomplete_command](https://cloud.githubusercontent.com/assets/553008/26624347/e1bdb5cc-45f0-11e7-8fa8-89197a7f9500.gif)

I'd suggest to wait for Director v1.4.0 first. In case this feature works fine, we can move it to the Icinga Web 2 framework (or the upcoming ipl) in a more generic variant. Select2 is a nice component, but to me it's not worth adding one more third-party component when something similar with much less weight is already around the corner.

Cheers,
Thomas

**Comment by Kels** [comment]
@Thomas-Gelf 
After checking a benchmark, I must admit that Select2 performance is bad comparing to some other js libs.
https://jsperf.com/chosen-select2-selectize

Your select box component looks awesome ! 👍 
I will try Director once v1.4.0 will be released.

Cheers,
Kelson

**Comment by lippserd** [comment]
We should move the director component to Web 2 once its finished. I close this one.
