### ISSUE TITLE
Feature Request: Schedule Downtime on Hostgroup

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icingaweb2#2829]
Hello,

it would be nice if it was possible to schedule downtimes on an entire hostgroup (with the option of applying the downtime to the services as well) using the web frontend. While the multi-select feature works well for a small number of hosts, it gets a bit cumbersome for bigger number of systems.

Kind regards

**Comment by Al2Klimov** [comment]
Hello @terra-nova

this (and much more) has already been implemented, but not merged #2743 yet. /cc @lippserd

Best
AK
