### ISSUE TITLE
Allow to grey out certain settings

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2#2830]
When managing Icinga Web 2 with a configuration management tool such as Puppet or Chef, it is not always clear which settings can be set on the web interface and which by the config management tool.

If we allow to grey out certain options, so web interface users cannot change them, it would be clear that they have to be set somewhere else.

This would also help if administrators want to disallow users to change certain settings (eg. the theme, language, ...).

**Comment by lazyfrosch** [comment]
Maybe allow a generic way like:

```
VARNAME_locked = 1
; or
VARNAME_readonly = 1
```

**Comment by lippserd** [comment]
Hi,

This is something we will not support. If you manage your configuration fully via Puppet or alike, you must set the access level of the INI files accordingly.

Best regards,
Eric
