### ISSUE TITLE
Provide Ubuntu Yakkety (16.10) and Zesty (17.04) packages

### ISSUE THREAD

**Issue by andreasscherbaum** [Icinga/icingaweb2#2832]
As of now, the latest supported Ubuntu version is Xenial. No packages for Yakkety are available in the repository:

http://packages.icinga.org/ubuntu/

Yakkety (16.10) and Zesty (17.04) are released Ubuntu versions.

**Comment by andreasscherbaum** [comment]
Preliminary test shows that Xenial packages work on Yakkety, but haven't had much time for additional tests.

**Comment by lazyfrosch** [comment]
This is already in the pipe for an upcoming (larger) buildserver update.

I'll update this once we can go live with that!

**Comment by lazyfrosch** [comment]
The packages are available on our build system since last week.

See:
* https://build.icinga.com/job/icingaweb2-release/
* http://packages.icinga.com/ubuntu/

**Comment by andreasscherbaum** [comment]
It's been a while, but I finally came around to this project again.

Can confirm that it works now.
