### ISSUE TITLE
Wrong URL on Graphite module

### ISSUE THREAD

**Issue by marcinkorzycki** [Icinga/icingaweb2#2834]
My Graphite Module constantly wants to go that URL when I want to show graph on host 
**icinga2.cdprs-build1.services.Drive_Usage_C:_.disk.perfdata.**
![graph](https://cloud.githubusercontent.com/assets/24276423/25560179/e35b2156-2d4c-11e7-8498-c34d4bd74e4f.jpg)

But real URL is:
![graphite](https://cloud.githubusercontent.com/assets/24276423/25560180/e6fb831e-2d4c-11e7-9064-bedef0c7ac19.jpg)

How can I fix this? Grafana works well - without any issues.

**My config.ini**

[graphite]
metric_prefix = icinga2
base_url = http://icinga2:8000/render?

legacy_mode = false
service_name_template = $HOSTNAME$.$SERVICEDESC$
host_name_template = $HOSTNAME$
graphite_args_template = "&target=alias(color($target$_warn,'yellow'),'warning')&target=alias(color($target$_crit,'red'),'critical')&target=$target$&source=0&width=300&height=120&colorList=049BAF&lineMode=connected&hideAxes=true&hideLegend=true"
graphite_large_args_template = "&target=alias(color($target$_warn,'yellow'),'warning')&target=alias(color($target$_crit,'red'),'critical')&target=$target$&source=0&width=700&height=600&colorList=049BAF&lineMode=connected"

**Comment by dgoetz** [comment]
I think you filed your issue against the wrong project as the configuration looks more like: https://github.com/findmypast/icingaweb2-module-graphite
