### ISSUE TITLE
DateTimePicker not working on Firefox 53

### ISSUE THREAD

**Issue by geotekberlin** [Icinga/icingaweb2#2836]
After years of development Firefox 53 has finally a HTML5 Date / Time Picker which must be enabled with these about:config options:

```
dom.forms.datetime;true
dom.forms.datetime.timepicker;true
```

While the new Firefox DateTimePicker works well with HTML test pages such as http://www.html5tutorial.info/html5-date.php, it still does not work with the acknowledge link in IcingaWeb 2.4.1 :-(

**Comment by Al2Klimov** [comment]
The Date**Time**Picker does *not* work, even on that test page. (Firefox 53)

**Comment by geotekberlin** [comment]
The DateTimePicker **DOES** work with the current Firefox Version 53.0.2 on the link given and on each and every HTML5 test site that I have checked, **except with Icinga2**. 

I have double checked this on several different computers and with 32bit as well as 64bit Firefox. 

Here is just one other link to check: 
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date

**Comment by lippserd** [comment]
You are referring to the date and time inputs not datetime-local which Web 2 is using. There is still no support for datetime-local in FF53.
