### ISSUE TITLE
ERROR: Zend_db_Statement_Exception 

### ISSUE THREAD

**Issue by yastic10** [Icinga/icingaweb2#2838]
HI mates,

I can't find the correct way to resolve this problem: 
![seleccion_776](https://cloud.githubusercontent.com/assets/19227939/25862635/0bf1e354-34e9-11e7-9857-9484a9038fde.png)
Can i help please? Thanks a lot.

**Comment by Al2Klimov** [comment]
Hi @yastic10

why did you cut off some of the text?
Please copy all of it and paste it here.

Please tell also:

* your Icinga Web 2's version
* how you installed it
* what did you configure (in the wizard)

Best
AK
