### ISSUE TITLE
ldap group search issue

### ISSUE THREAD

**Issue by ruccoon** [Icinga/icingaweb2#2839]
hi,

Recently I run into the ldap implemention issue with icingaweb2,

my config files are like:

```
resources.ini
[icingaweb2_ldap]
type                = "ldap"
hostname            = "*.*.*.*"
port                = "389"
root_dn             = "dc=company,dc=io"
encryption          = "starttls"

authentication.ini
[icingaweb2_auth_ldap]
backend             = "ldap"
resource            = "icingaweb2_ldap"
user_class          = "inetOrgPerson"
user_name_attribute = "uid"
base_dn             = "dc=company,dc=io"

groups.ini
[icingaweb2_ldap_groups]
resource                    = "icingaweb2_ldap"
user_backend                = "icingaweb2_auth_ldap"
group_class                 = "groupOfUniqueNames"
group_name_attribute        = "cn"
backend                     = "ldap"
base_dn                     = "dc=company,dc=io"
group_member_attribute      = "uniqueMember"
```

when I login icingaweb2, in debug logs, it cannot attache the full dn after uniqueMember, but just the uid value 'customer'

`ldapsearch -x -b "dc=company,dc=com " -H ldap://*.*.*.* "(&(objectClass=groupOfUniqueNames)(uniqueMember=customer))"`

only after I changed the base_dn in groups.ini as:
`base_dn = "ou=groupA,dc=company,dc=com"`

I can see the full dn added after uniqueMember=*

`ldapsearch -x -b "dc=company,dc=com " -H ldap://*.*.*.* "(&(objectClass=groupOfUniqueNames)(uniqueMember=uid=customer,ou=groupA,dc=company,dc=com))"`

but in this case, it is limited to ou=groupA only. Because I have other groups setup like these in ldap server:
```
ou=groupA,dc=company,dc=com
ou=groupB,dc=company,dc=com
ou=groupC,dc=company,dc=com
```

anyone has idea how to fix my config files? or is it a bug?

Thanks in advance.

Orson

**Comment by ruccoon** [comment]
**Update**

I set the base_dn to add ou=* in front, still not working

`base_dn                     = "ou=*,dc=company,dc=com"`

2017-05-11T14:45:55+00:00 - DEBUG - Issueing LDAP search. Use 'ldapsearch -P 3 -ZZ -H "ldap://*.*.*.*" -D "" -b "ou=*,dc=company,dc=com" -s "sub" -z 0 -l 0 -a "never" "(&(objectClass=groupOfUniqueNames)(uniqueMember=customer))" "cn"' to reproduce.

**Comment by dgoetz** [comment]
As a hint for developers: Other tools provide an additional config switch for member attribute being the full dn instead of one attributes value as some schema make use of this.

See AuthLDAPGroupAttributeIsDN Directive for Apache: https://httpd.apache.org/docs/2.4/mod/mod_authnz_ldap.html#authldapgroupattributeisdn

**Comment by ruccoon** [comment]
thanks dgoetz, it is great we can use AuthLDAPGroupAttributeIsDN directive to control either use full dn or just the uid  to search for groups.

unfortunately, I cannot find the similar config in icingaweb2

**Comment by lazyfrosch** [comment]
I found a nice issue that might be related: #2924 

We try to detect the membership attribute type, and adapt to it. While icingaweb2 resolves the full DN to a username.

Trying to understand your issue... Your problem is that user and groups can not be connected?

**Comment by lippserd** [comment]
Hi,

We're still interested to fix this issue but need your help. Could you please issue the following ldap search and validate whether all results are DNs. It may be the case that the first result(s) are no DNs and that's why Web 2 fails to load the groups.

`ldapsearch -x -b "dc=company,dc=com " -H ldap://*.*.*.* "objectClass=groupOfUniqueNames" "uniqueMember"`

Best regards,
Eric

**Comment by ruccoon** [comment]
hi Lippserd,

I found out a work around for this issue. That is add another OU(ou=users) on top of groupA, groupB, groupC etc.

The new groups.ini is

```
[icingaweb2_ldap_groups]
resource                    = "icingaweb2_ldap"
user_backend                = "icingaweb2_auth_ldap"
group_class                 = "groupOfUniqueNames"
group_name_attribute        = "cn"
backend                     = "ldap"
base_dn                     = "ou=users,dc=company,dc=io"
group_member_attribute      = "uniqueMember"
```
Then I can get the correct ldap authenticate in icingaweb2.

For your ldapsearch query, here are the results:
```
# extended LDIF
#
# LDAPv3
# base <dc=company,dc=com> with scope subtree
# filter: objectClass=groupOfUniqueNames
# requesting: uniqueMember
#

dn: cn=Directory Administrators,dc=company,dc=com
uniqueMember: cn=directoryadmin

dn: cn=admin_group,ou=groupA,ou=users,dc=company,dc=com
uniqueMember: uid=user1,ou=groupA,ou=users,dc=company,dc=com
uniqueMember: uid=user2,ou=groupA,ou=users,dc=company,dc=com
uniqueMember: uid=user3,ou=groupA,ou=users,dc=company,dc=com
```

So before the work around, the result will like this:
uniqueMember: uid=user1,ou=groupA,dc=company,dc=com

**Comment by lippserd** [comment]
Hi ruccoon,

Thanks for the fast reply. Web 2 automatically checks whether the member attribute is a DN or a "simple" account name. It fetches the first entry of the group backend and validates whether the entry is a DN and whether it is relative to the base DN.
In your case Web 2 tries to match cn=directoryadmin against dc=company,dc=com which fails.
With #2924 we'll relax the detection to only check whether the entry is a DN. This should solve your issue. So I close this one as duplicate.

Best regards,
Eric
