### ISSUE TITLE
Improve Add New Member form behavior when LDAP is used (it's slow)

### ISSUE THREAD

**Issue by Kels** [Icinga/icingaweb2#2844]
The current Add New Member page is not efficient:
- retrieve all users from LDAP server => slow
- difficult to find user in the select box

Today, the input users is enough for me because I know which users I will add. I never use the backend users select box.

Additionaly to the Add New Member button, it would be better to have another button dedicated to LDAP backend.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. You're right, that should be something like a autocomplete box. We'll have a look at it.

Best regards,
Eric

**Comment by lippserd** [comment]
Will be fixed with #3774. Though it may take some time.
