### ISSUE TITLE
Plugin output formatting issue

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2#2846]
Hi,

this issue is [related to this discussion ](https://monitoring-portal.org/index.php?thread/40644-plugin-output-formatting-question/) as @dnsmichi suggested.

I'm writing a new check; I get the data via a REST API, output format is JSON. I'd like to format my plugin output in a nice table, but while in Icinga Web 2 "Inspect" everything looks nice, the real plugin output has lots of newlines.

As an example, I'll show you the REST API query for PERSISTENCE_ACTIVE:
```

$ curl -s --connect-timeout 10 -X GET --header \"Accept: application/json\" "http://openhab.bafi.lan:8080/rest/persistence"
[{"id":"influxdb","label":"influxdb","type":"Queryable"},{"id":"rrd4j","label":"rrd4j","type":"Queryable"}]
```

And this one is the whole query including all my pipes:
```
$ curl -s --connect-timeout 10 -X GET --header \"Accept: application/json\" "http://openhab.bafi.lan:8080/rest/persistence" | jq . | grep id | cut -d ":" -f 2 |awk -F\" '{print $2}' | sed -e 's/^/<li>/g' | awk -v p=$p '{print $0p"</li>"}'
<li>influxdb</li>
<li>rrd4j</li>
```

And that's Icinga Web 2:
![screen shot 2017-05-02 at 10 17 02](https://cloud.githubusercontent.com/assets/11242139/26240932/236e3040-3c83-11e7-9024-292e3db42524.jpg)

Cheers,
  Marianne

**Comment by lazyfrosch** [comment]
Only some HTML elements are actually allowed in Plugin Output, the rest is purged away.

https://github.com/Icinga/icingaweb2/blob/master/modules/monitoring/application/views/helpers/PluginOutput.php#L166

You could try adding UL / LI there. Maybe others make sense too?

**Comment by dnsmichi** [comment]
Thing is, the inspect mode is provided by the Icinga Director, which renders the JSON and somehow HTML. I'd suggest to open an issue over there ;)

**Comment by lazyfrosch** [comment]
Yes, the director should escape the JSON for HTML

**Comment by Thomas-Gelf** [comment]
For the Director part, here you go: [#942](https://github.com/Icinga/icingaweb2-module-director/issues/942)

**Comment by sysadmama** [comment]
Thank you!

Okay, so with latest Director and modified HTML.Allowed (added ul,li) it looks a bit better :) Any ideas referring to these newlines?

![screen shot 2017-05-19 at 12 10 50](https://cloud.githubusercontent.com/assets/11242139/26243588/ac46b3b6-3c8c-11e7-9955-55094848d875.jpg)

**Comment by lazyfrosch** [comment]
What Icingaweb2 does is replace a literal \\n to \n (Sometimes comes out of Icinga or a plugin)

You should check the actual text inside IDO.

Also try to disable purification [here](https://github.com/Icinga/icingaweb2/blob/master/modules/monitoring/application/views/helpers/PluginOutput.php#L69). To check if the problem comes from HTMLPurifier

**Comment by lazyfrosch** [comment]
@sysadmama have you found out where the `\n` is coming from?

Do you have suggestions how to extend the Purifier settings?

**Comment by sysadmama** [comment]
Hi @lazyfrosch and sorry for delay,

when I disable purification, I get a nice strack trace ;)
![screen shot 2017-06-19 at 12 06 10](https://user-images.githubusercontent.com/11242139/27280491-6194ce60-54e8-11e7-8acd-acdacde6f853.jpg)

Check output in IDO as following:

```
MariaDB [icinga2ido]> select * from icinga_servicestatus where check_command="check_openhab" LIMIT 1\G
*************************** 1. row ***************************
             servicestatus_id: 60
                  instance_id: 1
            service_object_id: 299
           status_update_time: 2017-06-19 12:12:07
                       output: OK - System with UUID ec086d1b-3283-4a95-9ac4-d8fface383f1 running.
                  long_output: <table border="1">\n  <tr><th>Name</th><th>Value</th></tr>\n  <tr><td><b>System UUID:</b></td><td>ec086d1b-3283-4a95-9ac4-d8fface383f1</td></tr>\n  <tr><td><b>ESH Build Version:</b></td><td>0.9.0.b4</td></tr>\n  <tr><td><b>Thing Count:</b></td><td>33</td></tr>\n  <tr><td><b>Item Count:</b></td><td>503</td></tr>\n  <tr><td><b>Active Bindings:</b></td><td><ul><li>kodi</li>\n<li>hue</li>\n<li>ntp</li>\n<li>fritzboxtr064</li>\n<li>astro</li>\n<li>homematic</li></ul></td></tr>\n  <tr><td><b>Active Persistence:</b></td><td><ul><li>influxdb</li>\n<li>rrd4j</li></ul></td></tr>\n</table>
                     perfdata: openhab_items=503;;;; openhab_things=33;;;;
...
````

Hmmmm...

**Comment by sysadmama** [comment]
But I can pipe my output again (within my check shell script):

````
... | tr "\n" " "
````

Then Icinga Web 2 view is what I expected it to be.

**Comment by lippserd** [comment]
Web 2 does not fiddle with newline characters if the plugin output contains HTML. We should fix that.

**Comment by lippserd** [comment]
@nilmerg Please have a look at this one.
