### ISSUE TITLE
acknowledge_expire = 1 does not show expire time date/time picker

### ISSUE THREAD

**Issue by pinkgothic** [Icinga/icingaweb2#2848]
When setting "acknowledge_expire = 1" in `/etc/icingaweb2/modules/monitoring/config.ini`, the "Use Expire Time" checkbox is checked, but the "Expire Time" date/time-picker is not visible. (The checkbox needs to be unchecked and re-checked before it appears.)

See also https://monitoring-portal.org/index.php?thread/39979-defaults-when-acknowledging-problems-sticky-acknowledgement-expiry-time/

## Expected Behavior

I expect that when the "Use Expire Time" checkbox is ticked on initial page load, that the "Expire Time" date/time-picker is also visible.

## Current Behavior

The "Expire Time" date/time-picker is not visible, unless the checkbox is unchecked and then checked aain.

## Possible Solution

In the file `/usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/AcknowledgeProblemCommandForm.php`, change:

```
        if (isset($formData['expire']) && (bool) $formData['expire'] === true) {
```
...to:

```
        if (
           ((bool) $config->get('settings', 'acknowledge_expire', false))
           || (isset($formData['expire']) && (bool) $formData['expire'] === true)
        ) {
```

## Steps to Reproduce (for bugs)

1. edit `/etc/icingaweb2/modules/monitoring/config.ini`
2. add `[settings]` section into the file if it does not yet exist
3. add `acknowledge_expire = 1` to the file, in the `[settings]` section
4. restart icinga
5. click into a currently broken service
6. click 'Acknowledge'
7. notice that the 'Expire Time' date/time-picker is missing even though the 'Use Expire Time' checkbox is ticked

## Context

The setting `acknowledge_expire` is currently not effective for what we wanted to use it for - namely reduce the mad clicking that needs to happen if there's a larger-scale infrastructural problem (that we definitely don't want to acknowledge forever). Our desired defaults are:

```
acknowledge_expire = 1
acknowledge_sticky = 1
acknowledge_notify = 0
```

...but currently only help to a limited degree.

## Your Environment

* Version used (`icinga2 --version`): `v2.6.2`
* Operating System and version:
```
System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.10.2.el7.x86_64
  Architecture: x86_64
```
* Enabled features (`icinga2 feature list`):
```
Disabled features: compatlog debuglog gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql mainlog notification
```
* Icinga Web 2 version and modules (System - About):
** Version: 2.4.1
** Loaded modules: businessprocess, director, fileshipper, monitoring
* Config validation (`icinga2 daemon -C`): Validates.
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by lippserd** [comment]
Hi,

Thanks for providing all the details. This is indeed a bug. We'll fix it :).

Cheers,
Eric

**Comment by lippserd** [comment]
@Al2Klimov Please have a look at this one.

**Comment by Al2Klimov** [comment]
Hello @pinkgothic and thank you for both reporting and providing a possible solution!

If you have tested that solution (and it works), please create a pull request with your solution with the following changes:
1. Swap the two conditions around the `||`
2. Drop `(bool)` cast

Best,
AK

**Comment by pinkgothic** [comment]
It actually looks like you guys already fixed this in cd8d6e41dc175d5b823dda3d1be155527f83d560#diff-327ba7ffba58b73dd26958959b16a002 (which also links to https://monitoring-portal.org/woltlab/index.php?thread/39979-defaults-when-acknowledging-problems-sticky-acknowledgement-expiry-time/). I'll try to verify that in the coming days and get back to you.

**Comment by Al2Klimov** [comment]
No need to verify. This is effectively the same change. Thank you nevertheless.

**Comment by pinkgothic** [comment]
Did just get around to verifying it anyway! It works now. Thank you for the fix! :)

**Comment by lippserd** [comment]
Thanks for the feedback.
