### ISSUE TITLE
Icingaweb2 docs are out-of-date

### ISSUE THREAD

**Issue by zogness** [Icinga/icingaweb2#2852]
6.1. Configuration

## Expected Behavior

There is no config directory. Someone needs to rewrite these docs WHILE SITTING WITH AN END USER WHO IS ATTEMPTING TO FOLLOW THEM.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Icinga Web 2 version and modules (System - About):
* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by mcktr** [comment]
Hi,

could you please give some more information? 
Which docs? What are you trying to do?

You can find the config directory of icingaweb2 at /etc/icingaweb2, just as described in [03-Configuration](https://github.com/Icinga/icingaweb2/blob/master/doc/03-Configuration.md)

**Comment by dnsmichi** [comment]
Please be so kind and don't use uppercase letters. Yelling at someone doesn't help to understand your issue.

How did you manage to setup Icinga Web 2 in the first place? A little more context and environment infos will shed some light. That's why you're greeted with an issue template :)

**Comment by zogness** [comment]
https://docs.icinga.com/icinga2/latest/doc/icingaweb/chapter/authentication

**Comment by zogness** [comment]
6.1. Configuration

Authentication methods are configured in the INI file
*config/authentication.ini*.
