### ISSUE TITLE
Safari Pinned Tab Icon

### ISSUE THREAD

**Issue by spacecodeit** [Icinga/icingaweb2#2853]
Please provide a Pinned Tab Icon for the Safari Browser as described here:

https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

**Comment by lippserd** [comment]
Looks easy so why not :)

@flourish86 Could you please add this?

**Comment by lippserd** [comment]
Thanks Flo. I close this one.
