### ISSUE TITLE
icingaweb2 - Feature Commands : Can't send external Icinga command: 404 No objects found.

### ISSUE THREAD

**Issue by maelig** [Icinga/icingaweb2#2854]
I use api icinga2 to run commands on icingaweb2. Everything works except when I want to enable or disable in the "Feature Commands". Error message : `command user : Can't send external Icinga command: 404 No objects found.`

Icinga2 version : 2.6.2-1
Icingaweb2 version : 2.4.1-1

**Comment by zogness** [comment]
Me too. I tried to disable active checks and got the same error.

**Comment by dnsmichi** [comment]
Ensure that the ApiUser object has at least the following permissions:

```
permissions = [ "status/query", "actions/*", "objects/modify/*", "objects/query/*" ]
```

**Comment by maelig** [comment]
Thanks, it works since I modified the permissions of the user "web2" !

**Comment by dnsmichi** [comment]
Thought so. It is a common error, but the error message from Icinga 2 is somewhat generic. That prevents attackers from guessing object names, i.e. we do not separate from "permission denied" and "no object found".

**Comment by vlk-charles** [comment]
Are `status/query` and `objects/query/*` really necessary for anything? Feature command toggling works for me with the following:
```
permissions = [ "actions/*", "objects/modify/host", "objects/modify/service", "objects/modify/icingaapplication" ]
```
Note that that there had been a typo in the documentation before the change. See my comment at #2884.
