### ISSUE TITLE
Event Overview allows to filter for invalid columns

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2#2860]
## Expected Behavior
As a user I only want to get offered valid columns from the drop down for filters on the event overview.
 
## Current Behavior
If I select a column like `host` or `cnt_downtime_end` Icinga Web 2 throws an error `Icinga\Module\Monitoring\Backend\Ido\Query\HoststatehistoryQuery : Got invalid column:`

## Possible Solution
Only display valid columns for filter.

**Comment by lippserd** [comment]
@nilmerg Please have a look.
