### ISSUE TITLE
Create an emty Icinga.less file for the 'Icinga' theme

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2#2861]
## Expected Behavior
Following settings in `config.ini` should load the default theme without errors:

```
[themes]
default=icinga
disabled=0
```

## Current Behavior
Default theme is loaded, but an error message is logged:

```
icingaweb2[1295]: Can\t load theme /usr/share/icingaweb2/public/css/themes/icinga.less. Make sure that the theme exists and is readable
```
## Possible Solution
The correct setting would be `default=Icinga`. Checking for lowercase should solve the issue.

## Your Environment
- Icinga Web 2 `2.4.1-1~ppa1404`

**Comment by Thomas-Gelf** [comment]
Out of curiosity, why don't you write the correct name to the file? There are themes named MySpecialCustomer.less. Should we scan for all upper/lowercase variants just because someone wants to store myspecialcustomer? Sure, we could easily use `ucfirst` to catch at least some / the most common errors. But why allowing for such inconsistencies at all?

**Comment by bobapple** [comment]
It's just because all other settings are lowercase as well

**Comment by Thomas-Gelf** [comment]
:laughing: :tongue: :-1:

**Comment by Thomas-Gelf** [comment]
We talked about this, the initial irritating issue was that while other themes are visible on disk, the name "Icinga" is just hard-coded, and no related file exists. What makes sense, as there is nothing to be adjusted. To avoid confusion we should create an empty Icinga.less file, eventually with some comment in it. Those comments could state that this is the default theme and provide links to theme-related documentation. No need to load the file, it can remain hard-coded.

**Comment by lippserd** [comment]
Hi,

In my opinion we should use a case insensitive check whether the configured theme matches the default theme. If we create a file for the default theme, it will be added to drop down list of themes to choose from. Of course we could check whether the file on disk matches Icinga or icinga (or iCINga...?) and hide it but that seems a bit of a mess.

Thoughts?

Cheers,
Eric

**Comment by Thomas-Gelf** [comment]
I'd opt for not adding case insensitiveness at all, as it brings only drawbacks. Who doesn't want to set a theme just shouldn't write that line to the configuration, all done. And if one really insists, he must figure out the correct name.

**Comment by lippserd** [comment]
@Thomas-Gelf Your points make perfect sense. I close this issue as wontfix.
