### ISSUE TITLE
Wrong fastcgi_pass path when using php7.0-fpm

### ISSUE THREAD

**Issue by mcktr** [Icinga/icingaweb2#2862]
## Expected Behavior
On Debian 9 is php7.0 the default php version. The path to the fastcgi_pass socket is wrong when using php7.0-fpm. 

Correct path (for php7.0-fpm)
```
/var/run/php/php7.0-fpm.sock
```
## Current Behavior
CLI
```
icingacli setup config webserver nginx --document-root /usr/share/icingaweb2/public
```
Output
```
location ~ ^/icingaweb2/index\.php(.*)$ {
  # fastcgi_pass 127.0.0.1:9000;
  fastcgi_pass unix:/var/run/php5-fpm.sock;
  fastcgi_index index.php;
  include fastcgi_params;
  fastcgi_param SCRIPT_FILENAME /usr/share/icingaweb2/public/index.php;
  fastcgi_param ICINGAWEB_CONFIGDIR /etc/icingaweb2;
  fastcgi_param REMOTE_USER $remote_user;
}

location ~ ^/icingaweb2(.+)? {
  alias /usr/share/icingaweb2/public;
  index index.php;
  try_files $1 $uri $uri/ /icingaweb2/index.php$is_args$args;
}
```
Wrong path (for php7.0-fpm)
```
/var/run/php5-fpm.sock;
```
## Possible Solution
As far as I looked into the code, the output for the CLI command is hardcoded. Maybe a check which php version is installed could be executed before returning the config, based on the check  the output could be modified.

## Your Environment

* Icinga Web 2 version and modules (System - About): Version
2.4.1
* Version used (`icinga2 --version`): version: r2.6.3-1
* Operating System and version: 
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch
```

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I think its best to add an option to set the socket path.

Best regards,
Eric

**Comment by lippserd** [comment]
@nilmerg Please have a look at this one.
