### ISSUE TITLE
Sending a Summary Report per Service

### ISSUE THREAD

**Issue by gabrieleiannetti** [Icinga/icingaweb2#2864]
Hello there,

as far as I can see Icinga2 may send a notification mail per host.

We would like to retrieve an email which lists multiple hosts for a specific service instead of retrieving multiple notifications for each hosts (its about hundreds of machines affected).

So its not like a notification instead its more an idea of a summary report per service, which would show which hosts are in e.g. CRITICAL state and since when.

Such a summary report could do a periodical check if an interested service state is e.g. CRITICAL of the hosts and would send an proper email. As soon the hosts service state changes to OK the summary report would contain that hosts just one more time to show that its OK again (similar to the notification mechanism but just aggregating the information for multiple hosts).

Are you interested to provide such an reporting mechanism in the Icinga2 Web in the near future or will it be rather not the case?

Regards,
Gabriele

**Comment by lazyfrosch** [comment]
This is actually a feature of Icinga1/2, where we only trigger the notification.

Icinga web 2 isn't sending any notifications...

Technically we are even sending single commands to the core to do that.

**Comment by gabrieleiannetti** [comment]
Hi lazyfrosch,
all right, thank you!
