### ISSUE TITLE
Form: buttons for altering field values, but not "finishing" the form

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#2867]
In `LdapBackendForm` you may fill in all values by hand or you can discover e.g. the domain by clicking a button. To implement such buttons one has to "hack" `createElements()` like 8b43bd6.

This should be replaced by something less hacky.

**Comment by Al2Klimov** [comment]
## My suggestion

`Icinga\\Web\\Form::isValidPartial()` calls `parent::isValidPartial()` like how it is right now, but with empty values removed. This will trigger `Zend\\Form:2334` and cause non-submitted elements not to be validated.

(But @lippserd says: "It's a breaking change.")

**Comment by lippserd** [comment]
The IPL will provide this functionality.
