### ISSUE TITLE
Add further icinga2 ido backends

### ISSUE THREAD

**Issue by ralphbr** [Icinga/icingaweb2#2868]
Missing information wether it possible to use one icingaweb2 to combine multiple icinga2 IDOs and if yes. how to do it.

## Expected Behavior

I added a new ressource and assigned it to a to backend, so I expected that icingaweb2 loops over this backends. But it did'nt.

## Context

I did'nt find a solution in docs, google ...
Found equivalent older issue #2009.

## Your Environment
Icinga Web 2 Version 2.4.1
Git Commit d74124bd12f53d13b5a6ea5408e9783cc5190d1e
Git Commit Datum 2017-01-18
DB = postgreSQL 9.4

**Comment by lazyfrosch** [comment]
Icingaweb2 was never designed or build to use multiple backends in parallel.

This would be a nightmare, merging and sorting all the data in lists.

Backends are mainly meant as fallback between multiple IDOs, or other backends. (We supported others early on)

**Comment by ralphbr** [comment]
Thanks Markus, so I can stop search.

**Comment by alexizmailov** [comment]
Check-MK and Thruck developers consider it as a feature, not a nightmare...

**Comment by dnsmichi** [comment]
Still, there are no plans to support such. You have to deal with it :)
