### ISSUE TITLE
Icinga Issue

### ISSUE THREAD

**Issue by balarampaira** [Icinga/icingaweb2#2869]
Getting this error 

Fatal error: Call to a member function setDecorators() on a non-object in /usr/share/icingaweb2/modules/monitoring/application/forms/Config/TransportConfigForm.php on line 274 Call Stack: 0.0000 630616 1. {main}() /usr/share/icingaweb2/public/index.php:0 0.0001 631032 2. require_once('/usr/share/php/Icinga/Application/webrouter.php') /usr/share/icingaweb2/public/index.php:4 0.0134 1990128 3. Icinga\Application\Web->dispatch() /usr/share/php/Icinga/Application/webrouter.php:104 0.0134 1990128 4. Zend_Controller_Front->dispatch() /usr/share/php/Icinga/Application/Web.php:389 0.0141 2056136 5. Icinga\Web\Controller\Dispatcher->dispatch() /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php:937 0.0176 2508784 6. Zend_Controller_Action->dispatch() /usr/share/php/Icinga/Web/Controller/Dispatcher.php:76 0.0461 6242272 7. Zend_Controller_Action_HelperBroker->notifyPostDispatch() /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php:518 0.0461 6243640 8. Zend_Controller_Action_Helper_ViewRenderer->postDispatch() /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php:272 0.0461 6243640 9. Zend_Controller_Action_Helper_ViewRenderer->render() /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php:964 0.0466 6243896 10. Zend_Controller_Action_Helper_ViewRenderer->renderScript() /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php:925 0.0466 6243896 11. Zend_View_Abstract->render() /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php:904 0.0466 6285160 12. Icinga\Web\View->_run() /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php:877 0.0473 6383016 13. include('zend.view:///usr/share/icingaweb2/modules/setup/application/views/scripts/index/index.phtml') /usr/share/php/Icinga/Web/View.php:231 0.0523 6544448 14. Zend_View_Abstract->render() zend.view:///usr/share/icingaweb2/modules/setup/application/views/scripts/index/index.phtml:150 0.0523 6585720 15. Icinga\Web\View->_run() /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php:877 0.0525 6589376 16. include('zend.view:///usr/share/icingaweb2/modules/setup/application/views/scripts/index/parts/wizard.phtml') /usr/share/php/Icinga/Web/View.php:231 0.0525 6589376 17. Icinga\Web\Wizard->getForm() zend.view:///usr/share/icingaweb2/modules/setup/application/views/scripts/index/parts/wizard.phtml:1 0.0527 6589376 18. Icinga\Web\Form->create() /usr/share/php/Icinga/Web/Wizard.php:704 0.0527 6589592 19. Icinga\Module\Monitoring\Forms\Setup\TransportPage->createElements() /usr/share/php/Icinga/Web/Form.php:772 0.0538 6810576 20. Icinga\Web\Form->create() /usr/share/icingaweb2/modules/monitoring/application/forms/Setup/TransportPage.php:24 0.0677 7453984 21. Icinga\Module\Monitoring\Forms\Config\TransportConfigForm->addSubmitButton() /usr/share/php/Icinga/Web/Form.php:775

**Comment by Thomas-Gelf** [comment]
Duplicate issue #2842 exists, I'll close this one. 828b3e5 should fix this, please leave a note over there telling them whether it worked for you.

Thanks,
Thomas
