### ISSUE TITLE
Flexible downtime shows ending date of 1970-01

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2#2870]
Flexible downtimes in the future show and ending date of 1970-01 in Icinga Web 2.

Steps to reproduce:
* Create an flexible downtime starting some days in the future
* View this downtime in Icinga Web 2 Host details

Looks like there is a value of 0 which gets interpreted as Unix timestamp.

I talked to @Thomas-Gelf and he thinks Icinga 2 should put NULL instead of 0 into the database. Since Icinga Web 2 ususally hides this behaviour in other scenarios Icinga Web 2 should mask this, too.

This issue was opened in behalf of a customer of ours.

**Comment by leeclemens** [comment]
Seems like this may be related to https://github.com/Icinga/icinga2/issues/3575

**Comment by lippserd** [comment]
Hi Thomas,

Which version of Icinga 2 and Web 2 did you test?

Cheers,
Eric

**Comment by widhalmt** [comment]
Sadly enough I didn't note which versions had this bug. I tested again right now and it seems to work on Icinga 2 2.7.0 and Icinga Web 2 2.4.1 . I can not reproduce it anymore.

**Comment by lippserd** [comment]
Hi Thomas,

Thanks for the tests. I close this issue.

Cheers,
Eric
