### ISSUE TITLE
Redhat (AWS) problem with Icinga Installation

### ISSUE THREAD

**Issue by ghovat** [Icinga/icingaweb2#2871]
Hi,

I use the Redhat Amazon AWS OS. I have problems with the Icinga Installation. I tried the same thing in a seperate Docker Container with a regular Redhat Installation, and everything works fine.
I follow the installation instructions from here https://packages.icinga.com/epel/

I run:

`$ yum install https://packages.icinga.com/epel/7/release/noarch/icinga-rpm-release-7-1.el7.centos.noarch.rpm
`
After I tried to install:

`yum install icinga2`

I get the error that yum cant install the icinga2 package:

`
 One of the configured repositories failed (ICINGA (stable release for epel)),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:
`

**Comment by lazyfrosch** [comment]
A few problems with this issue:

1. You are trying to install icinga2, not icingaweb2 (which this repo is for)
2. Problems with repository or packages go to https://github.com/icinga/icinga-packaging as suggested on https://packages.icinga.com/
3. This looks more like a connectivity issue, or another issue with yum

Please verify that you don't have any special settings in yum.

You could re-run yum in verbose mode and send us the *full* log in a new issue against https://github.com/icinga/icinga-packaging
