### ISSUE TITLE
Increase input fields size

### ISSUE THREAD

**Issue by crsprsp** [Icinga/icingaweb2#2872]
Hello, 

Is there a way to increase the input fields in Icingaweb2? I work there with partly many groups and stuff and  there are only about 40 characters visible ....
To copy a URL for a new Dashboard and maybe conf it in some way is painful.
Even the input fields are not scaling to the resolution of my monitor.
I attach a screenshot here.

![icingaweb2short](https://user-images.githubusercontent.com/16636402/27480370-05139044-5818-11e7-8d9d-0231d5a5aae6.jpg)

**Comment by lazyfrosch** [comment]
I think thats a good idea in general, we should only keep the mobile view in mind.

But a basic CSS change should do that...
