### ISSUE TITLE
Missing dependency libapache2-mod-php for icingaweb2 on Ubuntu 16.04

### ISSUE THREAD

**Issue by b0e** [Icinga/icingaweb2#2874]
Hi,

if i follow the documentation to install icingaweb2 on Ubuntu 16.04 the package
libapache2-mod-php is not installed with the icingaweb2 dependencies. 

Version: 2.4.1

Kind regards,
b0e

**Comment by lazyfrosch** [comment]
Hey AL ;)
Please use https://github.com/icinga/icinga-packaging for packaging issues.

Also `libapache2-mod-php` is a Recommends, so its likely you did install it with `--no-install-recommends`

See https://github.com/Icinga/icinga-packaging/blob/deb/snapshot/icingaweb2/xenial/debian/control#L31

**Comment by lazyfrosch** [comment]
BTW. Our build server runs the following installation in a pretty basic Docker container:

https://github.com/Icinga/icinga-packaging/blob/deb/snapshot/icingaweb2/testing/start_test.sh
