### ISSUE TITLE
Missing dependency: php7-session in alpine edge

### ISSUE THREAD

**Issue by matthanley** [Icinga/icingaweb2#2875]
`icingaweb2` package in Alpine Linux (edge) repo is missing dependency `php7-session`.

Required steps to install (in a Docker container running PHP-FPM) are:

```
apk --update --no-cache add \
  icingaweb2 \
  php7-fpm \
  php7-session
```

**Comment by lippserd** [comment]
@fcolista Cheers mate, sorry to bother you but can you help us out here?

**Comment by lippserd** [comment]
Thanks for the report Matt.

**Comment by fcolista** [comment]
Sure. I'll take a look tomorrow 

.: Francesco
.: on mobile

**Comment by fcolista** [comment]
Hi.
Just bumped the new package icingaweb2-2.4.1-r4 containing php5-session and php7-session packages as dependencies.

**Comment by lazyfrosch** [comment]
I guess this is solved by external upstream! Thanks
