### ISSUE TITLE
RPM packaging: icingaweb2-vendor-* depend on mod_php

### ISSUE THREAD

**Issue by lesinigo** [Icinga/icingaweb2#2876]
Various current `icingaweb2-vendor-*` rpm packages have a dependency on `php`, which in RHEL7/CentOS7 land is actually mod_php, which in turn has a (correct) dependency on `httpd`.

This means that if you try to setup an Nginx + PHP-FPM system it will also bring in Apache and mod_php. This is not a real showstopper but sure is an annoyance when you don't want to run Apache.

It should be possible to install IcingaWeb2 with any working PHP implementation without bringing in unwanted ones.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We will change our packaging to PHP-FPM once we raise our PHP dependency to version 5.6. I think this will happen later this year. I'll open an issue at our [packaging-repository](https://github.com/Icinga/icinga-packaging) for this one.

Best regards,
Eric

**Comment by lippserd** [comment]
icinga/icinga-packaging#41
