### ISSUE TITLE
Search: Pass all parameter to the container

### ISSUE THREAD

**Issue by lum3n** [Icinga/icingaweb2#2877]
Hello,

in my opinion it is useful to pass all parameters calling /icingaweb2/search to its "sub"-search containers.

For example: I built a module which is displayed in the search and looks for hosts in our CMDB.
It finds and shows information of elements which contain the searched string, e.g. 
Main-search: http://icinga/icingaweb2/search?q=abc-host
My-search Container: http://icinga/icingaweb2/my_search?q=abc-host

This would result in finding these:
- abc-host
- abc-host-def
- abc-host-ghi

Next to each element I added a qlink ("data-base-target" => "_main") to do a search for exactly that element (which gives more information).
Main-search: http://icinga/icingaweb2/search?q=abc-host&id=1234&type=srv

Unfortunately only the q-parameter is passed to the container:
My-search Container: http://icinga/icingaweb2/my_search?q=abc-host

That makes it unpossible to pass e.g. a key or an id to your own searches/modules. Passing the id in the q-parameter is no option for me cause I need the type as well.

An idea to prevent an accidental passing of parameter to other containers would be using a prefix.
id => my-search_id
type => my-search_type

Regards,
Ken

**Comment by Thomas-Gelf** [comment]
Hi Ken,

how do you pass parameters other than q to /search? As far as I remember there is no such thing, /search "belongs" to the main search field and passes "q" to every "searchlet". Deciding on how to interpret q is then up to them. If you want your users to write things like id=1234 in the main search field that should be fine, just: it's passed to you in an escaped way in the "q" parameter. If you want to extend /search with custom logic I'd suggest you to clone it's logic into your module, adjust it and link to that one - it's not that much code.

I guess you would then also need to pass those additional parameters only to your searchlets - others (like those from the monitoring module) would probably fail when given an unknown parameter like "id".

Cheers,
Thomas

**Comment by lum3n** [comment]
Hi Thomas,

I iterate over my own results and simply display the following icon/link next each result.

```
foreach($result_array['srv'] as $hostname_key => $srv) {
	echo $this->qlink(null, "search", array("q" => $srv['srv_hostname'], "id" => $srv['srv_id'], "type" => $srv['type']), array("data-base-target" => "_main", "title" => "Show details", "icon" => 'search'));
}
```

This leads e.g. to:
http://icinga/icingaweb2/search?q=abc-host&id=1234&type=srv

The user does not write anything than a string in the search input (like "abc-host"). If the string has multiple results (see above) the module suggest a precise search by the id.

I build the logic in my module that it prefers the id over the q-string. So currently the id is not passed to my module but the q-string, which leads to exactly the same search as before. :)

Hm... I would have excepted (hoped) that the other modules would ignore unknown parameters. And in case the same parameters exist, a prefix-mechanism could be used (like mentioned above).

Regards,
Ken

**Comment by Thomas-Gelf** [comment]
I understood what you're doing, but I doubt we can modify the main search in that way, as what you want to achieve conflicts with what that controller should do. So, my suggestion was to just clone the SearchController into your module and link there. If required also clone the related widget, it's not that much code.

Another approach might be to not go to _main. Stay in your searchlet - or go _next.

**Comment by lum3n** [comment]
Too bad... handling with an own SearchController seems to a bit oversized for my case. ;)

Staying inside the searchlet was my first approach but has a curious effect (my-search's real name is "bits-search"):
`<?=$this->qlink(null, "bits_search", array("q" => $hostname, "id" => $srv['srv_id'], "type" => $srv['type']), array("data-base-target" => "_self", "title" => "Show details", "icon" => 'search'));?>`

The first search attempt displays this:
![1_neu](https://user-images.githubusercontent.com/11502571/27789774-047798aa-5fee-11e7-9403-39309b975f46.PNG)

Choosing one of the suggestions results in the following:
![2_neu](https://user-images.githubusercontent.com/11502571/27789802-19d08572-5fee-11e7-89b0-497cf37e25e3.PNG)

As you can see, the title of the searchlet gets messed up totally. Happens in FF ESR 52, Chrome 59 and IE 11. Do you know why this happens? If we could fix this, staying in the searchlet would be totally fine.

This is the html of the "controls"-Div:
```
    <div class="controls">
<ul class="tabs primary-nav nav">
  <li  class="active"><a href="/icingaweb2/search?q=host1" title="Show Search" aria-label="Show Search">Search</a></li>

  
  <li>
  <a class="refresh-container-control spinner" href="/icingaweb2/search?q=host1" title="Refresh the Search" aria-label="Refresh the Search">
    <i aria-hidden="true" class="icon-cw"></i>
  </a>
</li>
  <li style="float: right;">
  <a href="#" title="Close container" aria-label="Close container" class="close-container-control">
    <i aria-hidden="true" class="icon-cancel"></i>
  </a>
</li>
</ul></div>
```

Thanks and regards,
Ken

**Comment by Thomas-Gelf** [comment]
Dashlets / Searchlets need to be aware of the fact that you might want to render them this way. CSS for "controls" is not prepared for controls inside a Dashlet, as per default, they are expected to be hidden. BUT: this is not enforced, as some module still might want to show parts of their controls. What other modules usually do is nesting the controls-div the following way:

```php
<?php if (! $this->compact): ?>
<div class="controls">
<?= $this->tabs ?>
...
</div>
<?php endif ?>
```

Not the best example of how to apply hidden magic, I know. But for legacy reasons, that's how it works. Hope this helps to resolve your issue.

Cheers,
Thomas

**Comment by lum3n** [comment]
Ahh... I forgot about this block. Removing it (due to no need, even in !compact) solved the issue.

Thanks a lot and regards,
Ken

**Comment by Thomas-Gelf** [comment]
You're welcome!
