### ISSUE TITLE
application-state should not actively log out

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#2882]
When visiting a controller with `$requiresAuthentication = false` I'm forcibly being logged out once `application-state` fires next time. This should be fixed by silently ignoring unauthenticated requests, giving them an empty response or similar when visiting `application-state`.

**Comment by Al2Klimov** [comment]
1. No, you aren't forcibly being logged out. (IW2 v2.5.0)
2. If you're "being logged out", you was logged in. And how can your requests be unauthenticated while you're logged in?

**Comment by lippserd** [comment]
Hi Alex,

I think @Thomas-Gelf refers to the following scenario. You are not logged in but visit a URL which does not require authentication. The application-state request requires auth though. Thus you are redirected to the login page.

Cheers,
Eric
