### ISSUE TITLE
Service groups with non-alphanumeric characters in the name do not display in the UI

### ISSUE THREAD

**Issue by iDemonix** [Icinga/icingaweb2#2883]
I'm setting up service groups, but unlike other objects I can't use a hyphen or underscore in the object name, or it does not display in IcingaWeb2.

## Works as expected
```
object ServiceGroup "ciscohardware" {
  display_name = "Cisco Hardware"
  assign where service.name == "cisco-hardware"
}
```

## Does not work
```
object ServiceGroup "cisco-hardware" {
  display_name = "Cisco Hardware"
  assign where service.name == "cisco-hardware"
}
```

## Context
If I remove the hyphen and reload the config, the service group appears again in IcingaWeb2. I can't see any errors in the logs, it just seems to silently fail.

## Your Environment
* Icinga Web 2 version and modules (System - About): v2.4.1
* Version used (`icinga2 --version`): v2.6.3
* Operating System and version: CentOS 7.3
* Config validation (`icinga2 daemon -C`): Validates fine either way

**Comment by lippserd** [comment]
Hi,

Thanks for your report. I tested your config and both scenarios worked well. Could you please use a hyphen again and query your Icinga 2 database after you've restarted Icinga 2:

`SELECT * FROM icinga_objects WHERE name1 = "cisco-hardware" OR name2 = "cisco-hardware"\G`

Best regards,
Eric
