### ISSUE TITLE
Icinga Web2 v2.4.1 - missing php-curl API after fresh install from package repos

### ISSUE THREAD

**Issue by lenrico** [Icinga/icingaweb2#2886]
## Expected Behavior

Rescheduling of Services should not result in a exception, like this...

`Fatal error: Uncaught Error: Call to undefined function Icinga\Module\Monitoring\Web\Rest\curl_init() in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Rest/RestRequest.php:199 Stack trace: #0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Command/Transport/ApiCommandTransport.php(201): Icinga\Module\Monitoring\Web\Rest\RestRequest->send() #1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Command/Transport/ApiCommandTransport.php(232): Icinga\Module\Monitoring\Command\Transport\ApiCommandTransport->sendCommand(Object(Icinga\Module\Monitoring\Command\IcingaApiCommand)) #2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Command/Transport/CommandTransport.php(125): Icinga\Module\Monitoring\Command\Transport\ApiCommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleServiceCheckCommand), NULL) #3 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php(70): Icinga\Module\Monitoring\Command\Transport\CommandTra in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Rest/RestRequest.php on line 199`

## Current Behavior

Icinga Web2 under Debian Stretch (maybe also other Debian derivates affected too) should depend on php-curl, which is currently not the case.

## Possible Solution

Adding a dependency on package `php-curl' in package `icingaweb2'

## Steps to Reproduce (for bugs)

1. install a Debian Stretch and add the official packages.icinga.org repositories to your APT sources.list
2. then head to the Web Installer and proceed with any step as long you reach the PHP Modules Site, as you can see, there is no php-curl check.
3. proceed as long if it comes to the step where you are able to chose to use the API instead the Command Pipe, use the API, then finish your setup process.
4. Login to the fresh installed Icinga Web2 and reschedule a service, you would be faced with the error message above. 

## Your Environment

* Icinga Web 2 version and modules (System - About): Modules: monitoring - Version: v2.4.1
* Version used (`icinga2 --version`):  r2.6.3-1
* Operating System and version:  Debian GNU/Linux 9 (stretch) - Kernel version: 4.9.0-3-amd64
* Enabled features (`icinga2 feature list`): api checker ido-mysql mainlog
* Config validation (`icinga2 daemon -C`):

> information/cli: Icinga application loader (version: r2.6.3-1)
> information/cli: Loading configuration file(s).
> information/ConfigItem: Committing config item(s).
> information/ApiListener: My API identity: hades
> warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
> information/ConfigItem: Instantiated 1 ApiUser.
> information/ConfigItem: Instantiated 1 ApiListener.
> information/ConfigItem: Instantiated 1 Zone.
> information/ConfigItem: Instantiated 1 FileLogger.
> information/ConfigItem: Instantiated 1 Endpoint.
> information/ConfigItem: Instantiated 2 NotificationCommands.
> information/ConfigItem: Instantiated 13 Notifications.
> information/ConfigItem: Instantiated 201 CheckCommands.
> information/ConfigItem: Instantiated 1 Downtime.
> information/ConfigItem: Instantiated 1 Host.
> information/ConfigItem: Instantiated 1 IcingaApplication.
> information/ConfigItem: Instantiated 2 HostGroups.
> information/ConfigItem: Instantiated 1 UserGroup.
> information/ConfigItem: Instantiated 1 User.
> information/ConfigItem: Instantiated 12 Services.
> information/ConfigItem: Instantiated 3 TimePeriods.
> information/ConfigItem: Instantiated 3 ServiceGroups.
> information/ConfigItem: Instantiated 1 ScheduledDowntime.
> information/ConfigItem: Instantiated 1 CheckerComponent.
> information/ConfigItem: Instantiated 1 IdoMysqlConnection.
> information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
> information/cli: Finished validating the configuration file(s).

**Comment by lippserd** [comment]
Hi,

Thanks for providing all the details. php-curl is not a hard dependency for Icinga Web 2 because it is only used in the monitoring module if you use the Icinga 2 API as command transport. Our setup wizard and documentation tells you that you have to install php-curl in this case.
Maybe it's a good idea to add php-curl as hard dependency for deb and RPM packages because why not :).
For the moment deb packages should at least recommend php curl: Icinga/icinga-packaging#25

Cheers,
Eric

**Comment by dgoetz** [comment]
@lippserd: Perhaps we could also extend the setup wizard to show this as a possible requirement? It is also a hard requirement for the director.

**Comment by lippserd** [comment]
I'm not sure if this requirement made it to the v2.4.1 release, but the current master shows this as requirement.
