### ISSUE TITLE
 disk-windows not working in icingaweb2

### ISSUE THREAD

**Issue by passboltUser** [Icinga/icingaweb2#2889]
## Expected Behavior
Seeing a correct `check_disk.exe` output in `/icignaweb2`.

## Current Behavior
The output of `disk-windows` in `/icingaweb2` seems to be cut off after the `:`:
![disk-windows_not_working](https://user-images.githubusercontent.com/29798595/28207692-e8baf058-688a-11e7-84e8-0c2d6d50950a.png)

## Possible Solution
The `/icingaweb2` should print/parse the correct full output as shown when it's called from the PowerShell directly:
![disk-windows_not_working_2](https://user-images.githubusercontent.com/29798595/28207713-facfb5ee-688a-11e7-8a77-bffdb7f30d2b.png)

## Steps to Reproduce (for bugs)
This one is hard. I installed and removed the server and the clients several times, also did many config edits. So, unfortunately I don't know what exactly causes this error.

## Your Environment

* Version used (`icinga2 --version`):
<pre>
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.3-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 17.04 (Zesty Zapus)
  Kernel: Linux
  Kernel version: 4.10.0-26-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: a295cf04d827
</pre>

<pre>
# apt policy icinga2
icinga2:
  Installiert:           2.6.3-1.zesty
  Installationskandidat: 2.6.3-1.zesty
  Versionstabelle:
 *** 2.6.3-1.zesty 500
        500 http://packages.icinga.org/ubuntu icinga-zesty/main amd64 Packages
        100 /var/lib/dpkg/status
     2.6.0-2 500
        500 http://de.archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
</pre>

<pre>
# apt policy icingaweb2
icingaweb2:
  Installiert:           2.4.1-1.zesty
  Installationskandidat: 2.4.1-1.zesty
  Versionstabelle:
 *** 2.4.1-1.zesty 500
        500 http://packages.icinga.org/ubuntu icinga-zesty/main amd64 Packages
        500 http://packages.icinga.org/ubuntu icinga-zesty/main i386 Packages
        100 /var/lib/dpkg/status
     2.4.1-1 500
        500 http://de.archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu zesty/universe i386 Packages
</pre>

* Operating System and version:
* Enabled features (`icinga2 feature list`):
<pre>
# icinga2 feature list
Disabled features: compatlog debuglog gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql mainlog notification
</pre>
* Icinga Web 2 version and modules (System - About):
* Config validation (`icinga2 daemon -C`):
<pre>
# icinga2 daemon -C
information/cli: Icinga application loader (version: r2.6.3-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: Icinga2
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 4 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 4 Endpoints.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 36 Notifications.
information/ConfigItem: Instantiated 208 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 4 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 2 Users.
information/ConfigItem: Instantiated 32 Services.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
</pre>
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
<pre>
# icinga2 object list --type Endpoint
Object 'SERVER03.DOMAIN.LOCAL' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 21:1-21:42
  * __name = "SERVER03.DOMAIN.LOCAL"
  * host = "192.168.1.11"
    % = modified in '/etc/icinga2/zones.conf', lines 22:3-22:23
  * log_duration = 86400
  * name = "SERVER03.DOMAIN.LOCAL"
  * package = "_etc"
  * port = "5665"
  * templates = [ "SERVER03.DOMAIN.LOCAL" ]
    % = modified in '/etc/icinga2/zones.conf', lines 21:1-21:42
  * type = "Endpoint"
  * zone = ""

Object 'SERVER05.DOMAIN.LOCAL' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 13:1-13:42
  * __name = "SERVER05.DOMAIN.LOCAL"
  * host = "192.168.1.13"
    % = modified in '/etc/icinga2/zones.conf', lines 14:3-14:23
  * log_duration = 86400
  * name = "SERVER05.DOMAIN.LOCAL"
  * package = "_etc"
  * port = "5665"
  * templates = [ "SERVER05.DOMAIN.LOCAL" ]
    % = modified in '/etc/icinga2/zones.conf', lines 13:1-13:42
  * type = "Endpoint"
  * zone = ""
<
Object 'server07.DOMAIN.LOCAL' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 29:1-29:42
  * __name = "server07.DOMAIN.LOCAL"
  * host = "192.168.1.9"
    % = modified in '/etc/icinga2/zones.conf', lines 30:3-30:22
  * log_duration = 86400
  * name = "server07.DOMAIN.LOCAL"
  * package = "_etc"
  * port = "5665"
  * templates = [ "server07.DOMAIN.LOCAL" ]
    % = modified in '/etc/icinga2/zones.conf', lines 29:1-29:42
  * type = "Endpoint"
  * zone = ""
</pre>

<pre>
# icinga2 object list --type Zone
Object 'SERVER03.DOMAIN.LOCAL' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 24:1-24:38
  * __name = "SERVER03.DOMAIN.LOCAL"
  * endpoints = [ "SERVER03.DOMAIN.LOCAL" ]
    % = modified in '/etc/icinga2/zones.conf', lines 25:3-25:44
  * global = false
  * name = "SERVER03.DOMAIN.LOCAL"
  * package = "_etc"
  * parent = "Icinga2"
    % = modified in '/etc/icinga2/zones.conf', lines 26:3-26:19
  * templates = [ "SERVER03.DOMAIN.LOCAL" ]
    % = modified in '/etc/icinga2/zones.conf', lines 24:1-24:38
  * type = "Zone"
  * zone = ""

Object 'SERVER05.DOMAIN.LOCAL' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 16:1-16:38
  * __name = "SERVER05.DOMAIN.LOCAL"
  * endpoints = [ "SERVER05.DOMAIN.LOCAL" ]
    % = modified in '/etc/icinga2/zones.conf', lines 17:3-17:44
  * global = false
  * name = "SERVER05.DOMAIN.LOCAL"
  * package = "_etc"
  * parent = "Icinga2"
    % = modified in '/etc/icinga2/zones.conf', lines 18:3-18:19
  * templates = [ "SERVER05.DOMAIN.LOCAL" ]
    % = modified in '/etc/icinga2/zones.conf', lines 16:1-16:38
  * type = "Zone"
  * zone = ""

Object 'server07.DOMAIN.LOCAL' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 32:1-32:38
  * __name = "server07.DOMAIN.LOCAL"
  * endpoints = [ "server07.DOMAIN.LOCAL" ]
    % = modified in '/etc/icinga2/zones.conf', lines 33:3-33:44
  * global = false
  * name = "server07.DOMAIN.LOCAL"
  * package = "_etc"
  * parent = "Icinga2"
    % = modified in '/etc/icinga2/zones.conf', lines 34:3-34:19
  * templates = [ "server07.DOMAIN.LOCAL" ]
    % = modified in '/etc/icinga2/zones.conf', lines 32:1-32:38
  * type = "Zone"
  * zone = ""
</pre>

See also https://monitoring-portal.org/index.php?thread/41288-disk-windows-not-working-in-icingaweb2/&postID=252467#post252467.
One related bug I could find is this one: https://github.com/Icinga/icinga2/issues/3159

**Comment by passboltUser** [comment]
Closed. See https://github.com/Icinga/icinga2/issues/5414

**Comment by lippserd** [comment]
Thanks for the update.
