### ISSUE TITLE
Performance problem on service detail page for services generating lots of performance data

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2#2894]
## Expected Behavior

When showing the details of a service in icingaweb2, I'm expecting a navigation without any hang. 

## Current Behavior

However, on that particular page (service (detail) page), in case the service (using the plugin netapp-cdot-nagios-volume.pl ( https://github.com/aleex42/netapp-cdot-nagios )) generates a lot of performance data, the interface hang each 1-2 seconds for a few seconds, I guess loading updated data (?). In my case, I'm facing the issue with a plugin returning 754 performance data. This page is consequently almost unusable.

## Steps to Reproduce (for bugs)

1. find a plugin generating lots of performance data. For exemple netapp-cdot-nagios-volume.pl (https://github.com/aleex42/netapp-cdot-nagios)
2. 
3.
4.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga2 Version used (`icinga2 --version`): 2.6.1
* Operating System and version: RHEL 7.3
* Enabled features (`icinga2 feature list`): api checker command ido-mysql livestatus mainlog notification perfdata
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: v2.6.1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: monitorsrv1.communication1.ntld
information/ConfigItem: Instantiated 4 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 70 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 68 Endpoints.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1930 Notifications.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 266 CheckCommands.
information/ConfigItem: Instantiated 21 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 339 Hosts.
information/ConfigItem: Instantiated 9 Comments.
information/ConfigItem: Instantiated 10 Users.
information/ConfigItem: Instantiated 5 UserGroups.
information/ConfigItem: Instantiated 4185 Dependencies.
information/ConfigItem: Instantiated 13 TimePeriods.
information/ConfigItem: Instantiated 8 ServiceGroups.
information/ConfigItem: Instantiated 4185 Services.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 LivestatusListener.
information/ConfigItem: Instantiated 1 PerfdataWriter.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by Tontonitch** [comment]
Also, I have a custom version of the netapp-cdot-nagios-volume.pl plugin that:
* generates performance data in check_multi format (for a better view in pnp)
* generates a small HTML table as extended plugin output which is visible in the service details in icingaweb2

Unfortunately, the slowness to generate / update the service details page in icingaweb2 makes almost unusable the HTML table as it is difficult to scroll the service details page.

If the slowness problem comes from the high number of performance data, one solution might be to only print let's say the first 20 performance data and to allow to expand them to see all of them.

**Comment by lippserd** [comment]
Hi,

Thanks for providing all the details. If your performance data does not contain sensitive information, could you please provide some screenshots of the two scenarios? Does Web 2 render the small pie charts for you, i.e. does your performance data provide min and max values?

Cheers,
Eric

**Comment by Tontonitch** [comment]
Hello Eric,

I'm checking if I'm allowed to provide you more accurate info / screenshots or if I need to anonymize some data.

Pie charts are well rendered. My perfdata have min/max values and most of the time warn/crit values.

Exemple of plugin output:
```
OUTPUT blablabla|Volume_count::check_cdot_volume_count::count=175;;;0;; Vol1::check_cdot_volume_usage::space_used=263514980352B;239175991296;287011189555;0;318901321728 inode_used=5433703;6744747;8820053;0;10376534 snap_used=8290304B;;;0;3221225472 data_total=318901321728B snap_total=3221225472B Vol2::check_cdot_volume_usage::space_used=639963136B;12884901888;15461882265;0;17179869184 inode_used=146280;728423;952554;0;1120652 snap_used=4108288B;;;0;4294967296 data_total=17179869184B snap_total=4294967296B Vol3::check_cdot_volume_usage::space_used=239852449792B;237162725376;284595270451;0;316216967168 inode_used=1969064;6272613;8202648;0;9650175 snap_used=5502791680B;;;0;16642998272 data_total=316216967168B snap_total=16642998272B [.......] vol175::check_cdot_volume_usage::space_used=66677297152B;112742891520;135291469824;0;150323855360 inode_used=2289;3540983;4630516;0;5447667 snap_used=4338180096B;;;0;37580963840 data_total=150323855360B
HTML table
```

Looking deeper, I thing the perfdata are truncated... 

The plugin output have 51733 characters currently
* 629 for the standard output
* 41337 for the perfdata
* 10394 for the extra output containing HTML code

**Comment by Tontonitch** [comment]
Hello Eric,
I guess the problem is related to the amount of performance data anyway.
So, as one of my other plugin generating lots of perfdata (interface_table_v3t), i've added an option to redirect the perfdata to a file. However, this will only support pnp as graphing backend.

**Comment by lippserd** [comment]
Hi,

Thanks for the information. We'll have look at it.

Best regards,
Eric

**Comment by lippserd** [comment]
@nilmerg Please have a look at this one.

**Comment by lippserd** [comment]
@Al2Klimov Now it is your issue 😆 . Please have a look.

**Comment by Al2Klimov** [comment]
Hello @Tontonitch and thank you for reporting!

Does the above PR solve your problem?

Best,
AK

**Comment by Tontonitch** [comment]
> Do you use any modules which extend your host/service detail view (e.g. graphing integrations)? They could cause your problem.

I have the pnp module. 
But if I understand correctly it only take the first graph related to the service (source=0) so it should not produce any performance issue even if there are plenty of other graphs related to the service.

BR,
Yannick

**Comment by Al2Klimov** [comment]
Please

1. Try 2.4.1 again (and reload via Ctrl/Cmd-Shift-R!) and ensure that you still/again have the problem you reported here
2. Disable all extensions/integrations
3. Do you still have that problem?

**Comment by Tontonitch** [comment]
I've adapted check_interfacetable_v3t.pl (interfacetable_v3t) and check_cdot_volume.pl (netapp-cdot-nagios) to directly write most of the performance data in a spool file in the pnp input directory. So I don't face the issue as it doesn't appear in icingaweb2 anymore. But I now that some users of these plugins have graphite as graphing solution, and for that I have not provided a similar solution yet, and the icingaweb2 perfdata go through icinga2 and showed in icingaweb2.

In order to test, I will need to create a fake check. I will let you know.

**Comment by Al2Klimov** [comment]
```
root@ubuntu-16:~# cat /usr/lib/nagios/plugins/check_lolcat
#!/usr/bin/perl

print " |";
for (my $i = 1; $i <= 1000; ++$i) {
	print " lolcat$i=$i;;;0;1000"
}
root@ubuntu-16:~#
```
