### ISSUE TITLE
Display custom variables of Icinga 2 users (contacts)

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2#2895]
## Expected Behavior
As a user I also want to see custom attributes of users / contacts in the details view of the web interface. Also search and filtering based on custom variables would be nice.

## Current Behavior
Details view only displays object_name, display_name, email, pager and notification options.

## Possible Solution
Query the also the table `icinga_customvariables` for custom variables of the corresponding `contact_object_id` from the table `icinga_contacts` and display `varname` and `varvalue`.

## Context
In an environment with many users in many locations more information about a user are required to identify correctly.

**Comment by Nathaniel-Donahue** [comment]
Hi,
are and if when are you planing to implement this?

regards,
Nathaniel

**Comment by nilmerg** [comment]
Actually, no. Icinga DB Web shows them, and is out now. So, I'll close here.
