### ISSUE TITLE
OpenLDAP Authentication config successful, but unable to login

### ISSUE THREAD

**Issue by naisanza** [Icinga/icingaweb2#2899]
Installer script: [install-icinga.sh.txt](https://github.com/Icinga/icingaweb2/files/1179166/install-icinga.sh.txt)
OpenLdap script: [install-openldap.sh.txt](https://github.com/Icinga/icingaweb2/files/1179171/install-openldap.sh.txt)

It's able to connect to the ldap server and read the groups and users, however, after finishing with the wizard, you're not able to log in

![screenshot from 2017-07-27 03-55-45](https://user-images.githubusercontent.com/1614425/28660047-80cb736a-727f-11e7-9edd-a9f2b95104f0.png)

![screenshot from 2017-07-27 03-56-22](https://user-images.githubusercontent.com/1614425/28660063-951cfe24-727f-11e7-9e1d-187c8797a44d.png)

![screenshot from 2017-07-27 03-58-45](https://user-images.githubusercontent.com/1614425/28660152-ed7802ee-727f-11e7-9cca-b333629dd35e.png)

![screenshot from 2017-07-27 03-57-34](https://user-images.githubusercontent.com/1614425/28660225-2a5698ec-7280-11e7-9bef-1b2f41691423.png)

![screenshot from 2017-07-27 03-57-56](https://user-images.githubusercontent.com/1614425/28660122-cabf072a-727f-11e7-95f7-1578e92e5cca.png)

![screenshot from 2017-07-27 04-01-06](https://user-images.githubusercontent.com/1614425/28660281-5e4c650a-7280-11e7-98c8-14bb4b60c5b6.png)

![screenshot from 2017-07-27 04-02-29](https://user-images.githubusercontent.com/1614425/28660309-738136c6-7280-11e7-895a-2305d602e87d.png)

![screenshot from 2017-07-27 04-05-09](https://user-images.githubusercontent.com/1614425/28660411-cfc98f14-7280-11e7-826f-4a38e217c671.png)

![screenshot from 2017-07-27 04-05-28](https://user-images.githubusercontent.com/1614425/28660428-da247faa-7280-11e7-9a29-b8c9eb401628.png)

**Comment by lazyfrosch** [comment]
This is not a help forum, this is an issue tracker for Icinga 2

Please use the community channels for help:
https://www.icinga.com/support/ (Section: Community Support)

**Comment by naisanza** [comment]
@lazyfrosch There isn't any information from icingaweb2 why it isn't authenticating

**Comment by naisanza** [comment]
Solved, icingaweb2 uses SHA-1 hashed passwords

**Comment by lippserd** [comment]
Hi,

Just for the records, how did you solve your issue? Are you using a database backend for authentication? For AD/LDAP backends the hashing and password comparison is done by the server not Web 2.

Cheers,
Eric

**Comment by naisanza** [comment]
@lippserd OpenLdap for the authentication

When changing the Ldap user password to a SHA hashed password, the user authenticates and logs in

![screenshot from 2017-07-28 06-32-39](https://user-images.githubusercontent.com/1614425/28713893-06fd52de-735f-11e7-962b-9dfd0845ace0.png)
