### ISSUE TITLE
API request failed: Stage creation failed. (RestApiResponse.php:92)

### ISSUE THREAD

**Issue by shellscriptcode** [Icinga/icingaweb2#2905]
Hi Lippserd,

         I came back after long time, but situation is even after changing permissions , my issue is not resolved.
Below are the permissions that i have set.

permissions = [ "" , "objects/console/" , "actions/*", "objects/modify/hosts", "objects/modify/services", "objects/modify/icingaapplications" ]

When i remove i get JSON parses error , otherwise i get message "API request failed: Stage creation failed. (RestApiResponse.php:92)" . Can you please really help out here ? I have configured port 8080 behind tcp so i can access from company environment. So it is behing LB. I have also seen that socket is establishing when i send request over director GUI web to icinga2 server. So only issue seems api request not working, I am using root user with some password and permissions mentioned above. I get the same issue .

**Comment by shellscriptcode** [comment]
Opened new discission related https://github.com/Icinga/icingaweb2/issues/2700

**Comment by lippserd** [comment]
Hi,

Please try the following permissions and restart Icinga 2 afterwards:

```

[ "status/query", "actions/*", "objects/modify/*", "objects/query/*" ]
```

Best,
Eric

**Comment by lippserd** [comment]
Just realized that you are using director. Your API user needs the `*` permission, i.e.

```
permissions = [ "*" ]
```

If you need more information, please read the [docs](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/04-Getting-started.md#create-an-api-user).
