### ISSUE TITLE
doc module sends wrong Content-Type for images

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#2918]
The wrong content-type is going to be sent. You can easily compare the current behavior with an attempts to place exit; at the end of `ModuleController::imageAction()`. Guess something changed at postDispatch time, at least the module makes a wrong assumption here. Might have been introduced with af5c578 or similar. This affects content caching and Proxy servers might ship no/broken content.

**Comment by lippserd** [comment]
Hi Tom,

Thanks for the issue. I can confirm this behaviour.

Cheers,
Eric

**Comment by lippserd** [comment]
@theFeu Did you already create a pull request for this issue?
