### ISSUE TITLE
New Hook: MonitoredObject Detail Area

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2#2921]
I made a prototype for a user of mine to display CMDB information on every host and service (as long as there is some available)

* Offer hook similar to Grapher, to allow adding content sections
* Offer multiple sections to add stuff to (above, below)
* Allow multiple hooks to work (not just first like Grapher)

Currently it is build on base of the Grapher hook and looks like this:

![bildschirmfoto von 2017-08-11 08-49-10](https://user-images.githubusercontent.com/121874/29203547-ffc76ebe-7e71-11e7-8ca1-8838dbf2c361.png)

Issues out of scope (needs to be solved by Hook user):

* Loading times / local data caching (for me all CMDB data is cached in a local database)
* use of iframe to asynchronously loading stuff

Sponsored feature, will build it.

Opinions @lippserd @Thomas-Gelf @nilmerg

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: #2771

**Comment by lazyfrosch** [comment]
Oh right, my bad. Thanks!
