### ISSUE TITLE
Close mobile search upon submit

### ISSUE THREAD

**Issue by crsprsp** [Icinga/icingaweb2#2922]
Hello,

As i'm on the road at the moment, i use Icingaweb2 from my mobile. I recognize that the search is not working.

Browser: Safari on iOS 10.3.3 and Chrome.
Icingaweb2 Version 2.4.1.

In the Director it is working and Icingaweb2 itself is very handy to operate from the mobile phone.

Greets.

Rico

**Comment by widhalmt** [comment]
I got a screenshot of this. (see attached image)
![screenshot_mobile_safari](https://user-images.githubusercontent.com/504849/29413348-5db53d50-835c-11e7-8ff8-6b1273181f20.png)

**Comment by lazyfrosch** [comment]
I don't think that's a Safari problem.

You have to manually close the menu to see search results.

This could be solved by:
* Moving search to the top bar
* Reacting to enter / search request to close the menu

**Comment by crsprsp** [comment]
It is definitely not a Safari problem. I tested it with Chrome on iOS and it's the same behavior.

Cheers, Rico

**Comment by lippserd** [comment]
Hi Rico,

Thanks for the report. We should close the mobile menu upon submit.

@flourish86 Could you have a look please?

Cheers,
Eric
