### ISSUE TITLE
Expand dashboard columns to fill the remaining space

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2#2927]
It would be great to add the ability to set the number of columns to use for a dashlet

For exemple, in the following pan, I have 2 dashlets. For the 2nd one, I would like to use the 2 remaining columns.
![dashboard_1](https://user-images.githubusercontent.com/600025/29660130-c510b7cc-88c0-11e7-8b37-ccbc0c8264a8.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.4.1
* Version used (`icinga2 --version`): r2.7.0-1
* Operating System and version: RHEL 7.4
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by lazyfrosch** [comment]
This scales based on the general width of the website, it's adjusted to some default values for responsive display.

You can always tune this with a custom theme. The default values are here:
https://github.com/Icinga/icingaweb2/blob/master/public/css/icinga/responsive.less#L85

**Comment by Tontonitch** [comment]
Hello Markus,

The "problem" i face is with the rendering of the module "business process" on a dashlet / dashboard.

While remotely connected this morning (so it might be different when using a normal workstation), I've played a bit with the browser zoom.

Having the browser zoom sets at 100% (default), the view only shows one column of tiles in the dashlet. There's lots of wasted space on the right of each tiles.
Having the browser zoom sets at 90%, the view shows 2 columns of tiles. No wasted space, but only 2 columns is not enough and consequently there's many rows. So the rendering is not great.
Having the browser zoom sets at 80% or 75%, the view shows 1 columns of tiles. There's lots of wasted space on the right of each tiles, inside the dashlet. And wasted space at the right of the dashlet.
Having the browser zoom sets at 67%, the view shows 2 columns of tiles. No wasted space inside the dashlet. But wasted space at the right of the dashlet, as there is now enough space for a 3rd dashlet column. This is the case where allowing the dashlet to use that 3rd dashlet column would be nice.
It may be also a problem with the size of the tiles.

Hope I am understandable.

I need to check at the office on monday how it is rendered on a normal workstation.

**Comment by lazyfrosch** [comment]
Okay, you want the 2nd column to fill the rest of the content area. The Dashboard is currently build to show 1-3 columns, based on screen width.

I guess the layout should be more flexible in terms of how many dashlets are actually present...

Not sure how to improve this best

**Comment by Tontonitch** [comment]
> Okay, you want the 2nd column to fill the rest of the content area.

Exact. In case there are 2 dashlets in a dashboard, I would expect the 2 dashlets to at least share all the dashboard space, half of the space for each dashlet.
In case of 3 dashlets, it would be shared 33% each (as it is now).
In case of 1 dashlet only, it should take all the space (100%)
The limit of 3 dashlets per row is good I think.

BR,
Yannick

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I thinks it's a good idea to improve the scaling of our dashboard columns. I can't tell you when this is going to be implemented though.

Best regards,
Eric

**Comment by lippserd** [comment]
Moved to #3416.
