### ISSUE TITLE
Command expander like Icinga 1 classic UI

### ISSUE THREAD

**Issue by emveebee** [Icinga/icingaweb2#2928]
Icinga 1 classic provided the option to use a command expander which is quite useful when troubleshooting service checks. Icingaweb 2 provides the 'inspect' option but does not work as fast imho. Especially the 'raw commandline' being used would be a nice feature to have in Icingaweb2.

**Comment by dnsmichi** [comment]
There's already an issue for this, please add your findings there: #1344

Keep in mind that the `inspect` hook is provided by the Director module but not Icinga Web 2 itself.
