### ISSUE TITLE
allow regexp for monitoring/filter/objects in roles.ini

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2#2929]
Would be nice to allow regexp for monitoring/filter/objects in roles.ini

## Expected Behavior

As asked by one of my colleague, it would be interesting to be able to filter using more elaborate regexp 
i.e.
`monitoring/filter/objects = "host_name=^Mail[1-4]$"`

## Current Behavior

Currently it is only possible to use negations and wildcards for monitoring/filter/objects filtering
i.e.
`monitoring/filter/objects = "host_name=*win*"`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.4.1
* Version used (`icinga2 --version`): r2.7.0-1
* Operating System and version: RHEL 7.4
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by lippserd** [comment]
Hi,

I'm sorry but we can't allow such a feature. Using a regex here makes it impossible for the database to use indices and thus greatly reduces performance. We only allow columns in the restriction where it is actually possible for the database to use indices.

Best regards,
Eric
