### ISSUE TITLE
Problem with add services to hosts

### ISSUE THREAD

**Issue by darkerm** [Icinga/icingaweb2#2930]
## Expected Behavior

I try attach service to host in services tab.
![0](https://user-images.githubusercontent.com/27417510/29801063-eaeac05c-8cb0-11e7-8427-77a77349eb44.JPG)

## Current Behavior

Appears error message:
![default](https://user-images.githubusercontent.com/27417510/29801198-dd4ece06-8cb1-11e7-9bf0-927966a3f8ef.JPG)
![2](https://user-images.githubusercontent.com/27417510/29801200-e0c5bb6c-8cb1-11e7-995a-157b755dace1.JPG)

## Steps to Reproduce (for bugs)

1. Open Icinga Director - Hosts - Hosts
2. Choose any host
3. Open tab services
4. Choose button add service

Logfile:
ERROR - ErrorException in /usr/share/icingaweb2/modules/director/application/forms/IcingaAddServiceForm.php:10 with message: Dec$
#0 /usr/share/icingaweb2/modules/director/application/forms/IcingaAddServiceForm.php(10): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closu$
#1 /usr/share/php/Icinga/Application/ClassLoader.php(306): require('/usr/share/icin...')
#2 [internal function]: Icinga\Application\ClassLoader->loadClass('Icinga\\Module\\D...')
#3 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(49): spl_autoload_call('Icinga\\Module\\D...')
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\HostController->serviceAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('serviceAction')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga$
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}

## Your Environment

* Icinga Web 2 version and modules (System - About): 
2.4.1

* Version used (`icinga2 --version`):
version: r2.7.0-1

Build information:
  Compiler: GNU 4.9.2
  Build host: smithers

director version:  master

* Operating System and version: 
Debian 8.9 jessie 

* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql mainlog notification

* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.7.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: srv-icinga-01.dvfu.ru
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 2 Notifications.
information/ConfigItem: Instantiated 207 CheckCommands.
information/ConfigItem: Instantiated 2 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 3 HostGroups.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 1 Service.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by dgoetz** [comment]
Issue is on the wrong project, should be https://github.com/Icinga/icingaweb2-module-director.
