### ISSUE TITLE
Feature Request: Store Button in head area

### ISSUE THREAD

**Issue by Fiiti** [Icinga/icingaweb2#2942]
Hi,

we are missing the STORE Button near the Deploy Button.

Background:
We must change a lot of settings. The page is longer as the screen. The Value is changed above.
To store the changes we must scroll down every server. This is odd.
For a much quicker editing and a higher comfort the store button directly near the deploy link would be fantastic.

May it sounds interesting?!

Thanks
Fi

**Comment by dgoetz** [comment]
I think you are talking about the director module, so this issue should be at https://github.com/Icinga/icingaweb2-module-director/
