### ISSUE TITLE
Preference documentation outdated

### ISSUE THREAD

**Issue by baurmatt** [Icinga/icingaweb2#2950]
The preference documentation seems to be outdated. As far as i understand from @bobapple's comment in https://github.com/Icinga/puppet-icingaweb2/issues/166#issuecomment-327772662 it should be now configured by setting config_(backend|resource) in /etc/icingaweb2/config.ini

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Indeed, this has to be fixed.

Best,
Eric

**Comment by dnsmichi** [comment]
#2972 fixes this issue.
