### ISSUE TITLE
Monitoring module not working after automated installation

### ISSUE THREAD

**Issue by unix0r** [Icinga/icingaweb2#2959]
Hey guys,
i'm trying to install icingaweb2 via an automatic script following this guide: 
https://github.com/Icinga/icingaweb2/blob/master/doc/20-Advanced-Topics.md#automating-the-installation-of-icinga-web-2-

I tried it on a clean installation of debian and at the end of the installation after the login there is no dashboard available. If im doing the web setup the dashboard is available.
So i just followed the step by step guide.

I also tried to add a dashboard by hand but it says:
 

> No permission for module/monitoring
#0 /usr/share/php/Icinga/Web/Controller/ModuleActionController.php(31): Icinga\Web\Controller\ActionController->assertPermission('module/monitori...')
#1 /usr/share/php/Icinga/Web/Controller/ActionController.php(138): Icinga\Web\Controller\ModuleActionController->prepareInit()
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#6 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#7 {main}

A compare between a working installation (by the web setup) and the installation with no dashboard does not show any differences in the configuration or file permissions.

The monitoring module is enabled via:
`sudo icingacli module enable monitoring`

Looking for help to get a normal installation of icingaweb via an automated script so service partners do not need to go through the setup wizard and install an instance by hand.

Thanks

**Comment by dnsmichi** [comment]
Are you the same user who is writing here? https://monitoring-portal.org/index.php?thread/41787-no-dashboard-after-automatic-installation/

**Comment by unix0r** [comment]
yes, hoping for more comments here.

**Comment by dnsmichi** [comment]
So it is not a bug, but a configuration issue of yours. I'll comment into the forum post and close here.

**Comment by isaaclw** [comment]
The forum is broken. Can you comment here?

**Comment by zsebacsi** [comment]
any solutions on this?
