### ISSUE TITLE
History shown for downtimes and notifications can be confusing

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2#2963]
## Current Behavior
Sort order in the history view seems to be only based on the timestamp, so can be confusing if you get something like this:
![grafik](https://user-images.githubusercontent.com/3658213/30586298-d26462ce-9d2f-11e7-930c-e8b39426fa8f.png)
User thought something is wrong because it displays notification during downtime.

## Expected Behavior
View should show entries more logical. In this case it would be "Downtime End" -> "Critical Event (Hard)" -> "Notification".

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.4.1
* Version used (`icinga2 --version`): 2.6.3
* Operating System and version: RHEL7

**Comment by lippserd** [comment]
Hi Dirk,

Thanks for the report. Your example makes sense if the view displays the events in the following order `Notification -> State Change -> Downtime End` from top to bottom. I can't tell when this issue is going to be scheduled though.

Best regards,
Eric
