### ISSUE TITLE
Minimised search terms in the filter editor expand upon auto-refresh

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2#2964]
While minimizing search terms in Overview the next refresh cycle re-opens the whole view

## Expected Behavior
When clicking the minus or plus field beside the operator it would be expected to stay in that state of minimized or maximised.

## Current Behavior
If minimized the next browser auto reload makes the search term tree pop up again.
 
## Possible Solution
---

## Steps to Reproduce (for bugs)
Firefox 52.3 and IE11 show the same behaviour.

## Context
With a lot of search items the field of view gets suddenly smaller , when you have a lot of items in the search.

## Your Environment
* Icinga Web 2 version and modules (System - About): icingaweb2 2.4.1 , cube 1.0 , pnp 1.0.1 
* Version used (`icinga2 --version`): 2.6.3 -1 
* Operating System and version: 14.04.5 LTS
* Enabled features (`icinga2 feature list`): 
disabled features: command compatlog debuglog gelf influxdb livestatus opentsdb statusdata syslog
enabled features: api checker ido mainlog notification perfdata
* Config validation (`icinga2 daemon -C`): 
icinga2 daemon -C
information/cli: Icinga application loader (version r2.6.3-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Commiting config item(s).
information/Apilistener: My API Listener identity: irgendwas
information/ConfigItem: 2 ApiUsers. 
information/ConfigItem: 1 ApiListener. 
information/ConfigItem: 11 Zones. 
information/ConfigItem: 1 FileLogger. 
information/ConfigItem: 11 Endpoints.
information/ConfigItem: 260 CheckCommands. 
information/ConfigItem: 10659 Hosts. 
information/ConfigItem: 1 IcingaApplication. 
information/ConfigItem: 3 HostGroups. 
information/ConfigItem: 1000 UserGroups. 
information/ConfigItem: 11128 Services. 
information/ConfigItem: 1 TimePeriod. 
information/ConfigItem: 1 CheckerComponent. 
information/ConfigItem: 1 IdoMysqlConnection. 
information/ConfigItem: 1 NotificationComponent. 
information/ConfigItem: 1 PerfdataWriter. 
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars' 
information/cli: Finished validating the configuration file(s).
 
Attached gif from from Issue happening.
![search_pop_up](https://user-images.githubusercontent.com/7203835/30588248-480e287e-9d36-11e7-8a97-a76f3bcd436d.gif)

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I can confirm this behaviour.

Best regards,
Eric
