### ISSUE TITLE
icingaweb uses /var/icingaweb2 as config dir (which fails for selinux) and I am unable to change

### ISSUE THREAD

**Issue by hlovdal** [Icinga/icingaweb2#2969]
## Expected Behavior

When running through the http://localhost/icingaweb2/setup wizard, it should use `/etc/icingaweb2`  as value for configDir since this is hard coded into the SELinux policy.

## Current Behavior
When running through the setup wizard, it uses `/var/icingaweb2`

## Steps to Reproduce

Yesterday I upgraded icinga from something installed May earlier this year I think (not properly configured and set up), and configured it using the web wizard. After finishing configuring icinga with hosts and checks, everything was working fine (although at one point I disabled selinux).

Today, after a reboot, the web frontend does not work and displays errors like

```
No backend has been configured

#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(78): Icinga\Module\Monitoring\Backend\MonitoringBackend::loadConfig(NULL)
#1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/MonitoringBackend.php(219): Icinga\Module\Monitoring\Backend\MonitoringBackend::instance(NULL)
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Controller.php(28): Icinga\Module\Monitoring\Backend\MonitoringBackend::createBackend(NULL)
#3 /usr/share/php/Icinga/Web/Controller/ModuleActionController.php(28): Icinga\Module\Monitoring\Controller->moduleInit()
#4 /usr/share/php/Icinga/Web/Controller/ActionController.php(138): Icinga\Web\Controller\ModuleActionController->prepareInit()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}
```

for every view. Trying to run the web setup again displays an error message

```
Cannot validate token: /var/icingaweb2/setup.token (FileObject::__construct(/var/icingaweb2/setup.token): failed to open stream: Permission denied)
```

when entering the setup token. This error is due to selinux (`setenforce 0` makes the error go away) and /var/log/audit/audit.log contains entries like

```
type=AVC msg=audit(1506024154.666:7619): avc:  denied  { getattr } for  pid=5465 comm="httpd" path="/var/icingaweb2/config.ini" dev="dm-0" ino=13763605 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=file
```

Since `/etc/icingaweb2` is a symlink to `../var/icingaweb2` and 
`/usr/share/doc/icingaweb2-selinux-2.4.1/icingaweb2.fc` contains a line with
    /etc/icingaweb2(/.*)?           gen_context(system_u:object_r:icingaweb2_config_t,s0)
and not
    /var/icingaweb2(/.*)?           gen_context(system_u:object_r:icingaweb2_config_t,s0)
this explains the behaviour.

So how did I end up `/var/icingaweb2` as config dir? When running the web setup `modules/setup/application/views/scripts/form/setup-welcome.phtml` suggest

    <span><?= $cliPath ? $cliPath : 'icingacli'; ?> setup config directory --group icingaweb2<?= $configDir !== '/etc/icingaweb2' ? ' --config ' . $configDir : ''; ?>;</span>

which is displayed as

    icingacli setup config directory --group icingaweb2 --config /var/icingaweb2;

which I ran yesterday. How did setup-welcome get /var/icingaweb2 as a configDir value? I do not know which is why I report this issue.

## Context

Trying to resolve this manually with

```
systemctl stop icinga2 httpd
rm /etc/icingaweb2
mv /var/icingaweb2 /etc/icingaweb2
restorecon -R /etc/icingaweb2
icingacli setup config directory --group icingaweb2 --config /etc/icingaweb2
systemctl start icinga2 httpd
```

does solve all the selinux related issues as far as I can tell.

However, setup-welcome still want to use `/var/icingaweb2`, and this does the normal frontend as well. All modules are disabled, and trying to enable the monitoring module
(http://localhost/icingaweb2/config/modules#!/icingaweb2/config/moduleenable?name=monitoring) fails with

```
Could not enable module "monitoring"
While operation the following error occurred:
Failed to create enabledModules directory "/var/icingaweb2/enabledModules" (mkdir(): Permission denied)
```

_So how do I make icingaweb use /etc/icingaweb2 and not /var/icingaweb2?_

## Environment

* Icinga Web 2 version and modules (System - About):
Version 2.4.1
Git commit d74124bd12f53d13b5a6ea5408e9783cc5190d1e
Git commit date 2017-01-18
* Version used (`icinga2 --version`):
icinga2-2.7.0-1.el7.icinga.x86_64
icingaweb2-2.4.1-1.el7.centos.noarch
* Operating System and version:
CentOS Linux release 7.4.1708 (Core) 
* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-pgsql mainlog notification
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.7.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: ..............................
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 7 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 7 Endpoints.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 207 CheckCommands.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 8 Hosts.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 4 TimePeriods.
information/ConfigItem: Instantiated 13 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

----------------

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Why is /etc/icingaweb2 a symlink in your environment? How did you install Icinga Web 2 in the first place? Please have a look at the Icinga Web 2 web server config for a possible override of the ICINGAWEB_CONFIGDIR directive.

Best regards,
Eric
