### ISSUE TITLE
Server error: The filter column "showFullscreen" is not allowed here.

### ISSUE THREAD

**Issue by thomas99p** [Icinga/icingaweb2#2970]
Hi,
so I´m trying to hide the menubar
![grafik](https://user-images.githubusercontent.com/32258435/30796721-a02f199a-a1d3-11e7-93c8-f392dcedb65f.png)

but when i add "?showFullscreen&showCompact"

I get this error:
Server error: The filter column "showFullscreen" is not allowed here.

`

The filter column "showFullscreen" is not allowed here.

#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(346): Icinga\Module\Monitoring\DataView\DataView->validateFilterColumns(Object(Icinga\Data\Filter\FilterMatch))
#1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/DataView/DataView.php(321): Icinga\Module\Monitoring\DataView\DataView->validateFilterColumns(Object(Icinga\Data\Filter\FilterAnd))
#2 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(673): Icinga\Module\Monitoring\DataView\DataView->applyFilter(Object(Icinga\Data\Filter\FilterAnd))
#3 /usr/share/icingaweb2/modules/monitoring/application/controllers/ListController.php(127): Monitoring_ListController->filterQuery(Object(Icinga\Module\Monitoring\DataView\HostStatus))
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Monitoring_ListController->hostsAction()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(303): Zend_Controller_Action->dispatch('hostsAction')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/icingaweb2/library/Icinga/Application/Web.php(158): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(111): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#10 {main}

`
What can i do ?

**Comment by nbuchwitz** [comment]
Which Version of icingaweb2 do you use? Your screenshot looks like an "older" one.

**Comment by dnsmichi** [comment]
Please provide the exact URL from that view.

**Comment by thomas99p** [comment]
@dnsmichi 
http://xxx.xxx.xxx.xxx/icingaweb2/monitoring/list/hosts?host_problem=1&sort=host_severity&dir=desc&view=compact&showFullscreen&showCompact

**Comment by nbuchwitz** [comment]
Should be ```showFullscreen=1&showCompact=1```

**Comment by thomas99p** [comment]
@nbuchwitz 
<div data-id="iframe" data-view="Iframe" data-url="http://xxx.xxx.xxx.xxx/icingaweb2/monitoring/list/hosts?host_problem=1&sort=host_severity&dir=desc&view=compact&showFullscreen=1&showCompact=1"></div>

not working :/

**Comment by Thomas-Gelf** [comment]
@nbuchwitz: `=1` also works - but is not required. `showFullscreen&showCompact` is perfectly valid - and looks better.
@thomas99p: as @nbuchwitz pointed out, your Icinga Web 2 seems to be very (very!) old. That feature might not have been available at the time being.

**Comment by dnsmichi** [comment]
Works for me.

![screen shot 2017-09-25 at 10 43 32](https://user-images.githubusercontent.com/382049/30799833-7396541a-a1de-11e7-9b52-a6bcca5f4549.png)

Please share your Icinga Web 2 version as requested in the issue template.

**Comment by nbuchwitz** [comment]
@Thomas-Gelf I had a quick look into changelog: addFullscreen was added with ``` 2.0.0-rc1```

**Comment by thomas99p** [comment]
@Thomas-Gelf  @nbuchwitz 

we have 2.6.3 but it´s not working :/

**Comment by Thomas-Gelf** [comment]
@thomas99p: that's your Icinga 2 Core version, not Icinga Web 2. Web v2.1.0 already looks completely different than your screen-shot, latest released version should be v2.4.1.

**Comment by thomas99p** [comment]
@Thomas-Gelf  how do i check it ? 

Sorry, I´m new and like in deep water :/

**Comment by thomas99p** [comment]
![grafik](https://user-images.githubusercontent.com/32258435/30801952-48a0f178-a1e5-11e7-9dcf-5ff2bb176ee4.png)
This is what i get when i use yume list installed

**Comment by Thomas-Gelf** [comment]
I do not see `icingaweb2` in this list, so you eventually installed it from it's sources and not as a package.

**Comment by thomas99p** [comment]
@Thomas-Gelf 

i have installed it again and its working

Thanks to all of you :)
