### ISSUE TITLE
Schema will not install on postgres

### ISSUE THREAD

**Issue by TonyHoyle** [Icinga/icingaweb2#2976]
The schema file for postgres just errors out, breaking the installation - error:

"Migration 0 failed (SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "icinga_host" does not exist) while running CREATE TABLE icinga_host_template_choice ( id serial, object_name character varying(64) NOT NULL, description text DEFAULT NULL, min_required smallint NOT NULL DEFAULT 0, max_allowed smallint NOT NULL DEFAULT 1, required_template_id integer DEFAULT NULL, allowed_roles character varying(255) DEFAULT NULL, CONSTRAINT host_template_choice_required_template FOREIGN KEY (required_template_id) REFERENCES icinga_host (id) ON DELETE RESTRICT ON UPDATE CASCADE, PRIMARY KEY (id) ) (Migration.php:50)"

In pgsql.sql there's a create table for icinga_host_template_choice that references icinga_host that does not exist yet.
If you move that create below the creation of icinga_host, the creation of icinga_host errors out because it has a constraint on icinga_host_template_choice that doesn't exist.

It appears these tables have mutually conficting constraints, and there appears to be no way to reconcile them.

**Comment by dnsmichi** [comment]
This sounds like a Director issue to me. Please open it in icinga/icingaweb2-module-director and include how you've downloaded/installed it, (git) version and so on.

**Comment by Thomas-Gelf** [comment]
@TonyHoyle: sorry for breaking this, and thanks for reporting it. Wouldn't have got uncaught, all our tests where failing :p I created (and closed) [#1204](https://github.com/Icinga/icingaweb2-module-director/issues/1204) for this.
