### ISSUE TITLE
Ability to group/filter contacts by notification type under host/service.

### ISSUE THREAD

**Issue by yoshi314** [Icinga/icingaweb2#2986]
When inspecting various services, i briefly thought that there were many more users assigned to be notified compared to actual config.

This was due to additional notification logger that was applied to everyone (which was intentional), which would log messages to files on disk instead of sending them out (it's something i use to make sure notifications work correctly with custom email scripts etc). 

Unfortunately, this cluttered the display in icingaweb2 under host or service.

It would be useful to be able to filter out specific notification type or group users by notification method under host/service for a more clear view of the situation. Similarily in service/host history.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. The same notification should not be shown twice even if it is sent out to multiple users. Can you share a screenshot of your problems?

Best,
Eric

**Comment by yoshi314** [comment]
I'll look into that next week.
