### ISSUE TITLE
Sort announcements by date

### ISSUE THREAD

**Issue by ClemensBW** [Icinga/icingaweb2#2987]
## Expected Behavior
for the new icingaweb2/announcements feature the order by date will be nice

## Current Behavior
order will be done by the id (announcements/update?id=599c53165c8c9)

## Your Environment
* Icinga Web 2 version 2.4.2

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll include this in our v2.5.0 release.

Best regards,
Eric
