### ISSUE TITLE
Installation from git missing

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icingaweb2#2988]
There used to be [documentation for installing icingaweb2 from git](https://github.com/Icinga/icingaweb2/blob/ec60f15f09e381f4c622088f16918bfb88e17fa0/doc/installation.md)

This was useful for developers but is now missing :(

Could we re-introduce this as a section in the CONTRIBUTING.md?

**Comment by lippserd** [comment]
We moved this to the **Advanced Topics** chapter.
