### ISSUE TITLE
Can't create resources and command transports which require a port

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2#2998]
It's not possible to create a new Command Transport for the monitoring module using the Icinga 2 API via GUI:

![bildschirmfoto 2017-10-06 um 15 39 16](https://user-images.githubusercontent.com/3973350/31280488-c94b02c6-aaac-11e7-9801-46a9cdda3a8f.png)

![bildschirmfoto 2017-10-06 um 11 27 02](https://user-images.githubusercontent.com/3973350/31280519-dfcad594-aaac-11e7-91ad-b518409bf567.png)

## Environment
* Icinga Web 2 version and modules (System - About): 2.4.2
* Version used (`icinga2 --version`): r2.7.1-1
* Operating System and version: CentOS Linux release 7.4.1708 (Core)

**Comment by nbuchwitz** [comment]
Same error (port) here while adding a new ressource.

# Environment

Icinga Web 2 version and modules (System - About): 2.4.2
Version used (icinga2 --version): r2.7.1-1
Operating System and version: CentOS Linux release 7.4.1708 (Core)

**Comment by lippserd** [comment]
Hi,

I included eb343009bb696e155897dda4decef532242cf9fa in v2.4.2 and didn't recognize this issue in our final tests. Will be fixed asap.

@nilmerg Please take care of this issue.

Cheers,
Eric

**Comment by dnsmichi** [comment]
https://monitoring-portal.org/index.php?thread/42126-ldap-ad-binding/
