### ISSUE TITLE
LDAP port being erased

### ISSUE THREAD

**Issue by ProjectPatatoe** [Icinga/icingaweb2#3000]
under http://server/icingaweb2/config/resource#!/icingaweb2/config/createresource
I'm trying to add a LDAP resource but my port keeps getting erased when I submit it. However, I found that if I put in port 388 (as opposed to 389), it seems to try (and by the way... never actually times out?)
## Expected Behavior
not erase my port

## Current Behavior
clicking validate or save erases the port that was there... sometimes
## Steps to Reproduce (for bugs)

1. try to add LDAP resource
2. fill info in
3. press validate or save
4.
![image](https://user-images.githubusercontent.com/27925441/31299189-1c636558-aaa2-11e7-9e65-3a2aee2083e4.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.4.2
* Version used (`icinga2 --version`): r2.7.1-1
* Operating System and version: Ubuntu 17.04 (lubuntu)
* Enabled features (`icinga2 feature list`): api checker ido-mysql mainlog notification

**Comment by lazyfrosch** [comment]
This should have been fixed with #2923

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I close this as duplicate of #2998. We'll fix this issue asap.

Best regards,
Eric
