### ISSUE TITLE
Add option "host_display_name" for monitoring/filter/objects

### ISSUE THREAD

**Issue by ClemensBW** [Icinga/icingaweb2#3014]
## Expected Behavior
support host_display_name

## Current Behavior
host_display_name isn't supported for monitoring/filter/objects at icingaweb2/role/edit

## Steps to Reproduce (for bugs)
try to add filter "host_display_name" at role filter objects

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I'm open for PRs/discussions on this topic.

Cheers,
Eric

**Comment by lippserd** [comment]
Hi,

I'll close this issue now because there seems to be nothing much of interest. Further, this would add extra joins in some of our views.

Best,
Eric
