### ISSUE TITLE
Icingaweb2 depends on PHP5.3, which is EOL!

### ISSUE THREAD

**Issue by sighupper** [Icinga/icingaweb2#3015]
Good Day,

I tried to install icingaweb2 today. But, it failed because Icingaweb2 depends on php5.3, php-intl, and other packages. Are there plans on updating icingaweb2 to use a current version of php, perhaps something that is also supported by PHP? php5.3 is EOL for 3+ years.

Frustrated,

Sighupper

**Comment by Thomas-Gelf** [comment]
This statement is not true:

* Icinga Web 2 supports all PHP versions from 5.3 up to 7.1
* Our test suite always run on 5.3, 5.4, 5.5, 5.6, 7.0 and 7.1
* Additional internal tests run on various Linux flavors with their respective default PHP versions
* The packages we ship depend on the default versions shipped by the respective operating system

If what your OS provides is not what you like, nothing hinders you from using one of the alternative installation methods and use a custom-build PHP. So, no idea what you're complaining about.

**Comment by lippserd** [comment]
Thanks for the quick response Tom. I close this one.
