### ISSUE TITLE
 Icingaweb2 on RHEL7.4 on EC2 Instance, install package issues

### ISSUE THREAD

**Issue by sighupper** [Icinga/icingaweb2#3021]
Hi, this is a continuation of the issues I was having in 3019:

[root@ip-172-31-4-62 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)
[root@ip-172-31-4-62 ~]# rpm -qa | grep php
[root@ip-172-31-4-62 ~]# yum repolist
Loaded plugins: amazon-id, replace, rhui-lb, search-disabled-repos
repo id                                          repo name       status
epel/x86_64                                      Extra Packages  11,988
icinga-stable-release/7Server                    ICINGA (stable     267
ius/x86_64                                       IUS Community P    402
ius-archive/x86_64                               IUS Community P  5,147
ius-archive-debuginfo/x86_64                     IUS Community P    473
ius-archive-source                               IUS Community P      0
remi-safe                                        Safe Remi's RPM  2,518
rhui-REGION-client-config-server-7/x86_64        Red Hat Update       6
rhui-REGION-rhel-server-releases/7Server/x86_64  Red Hat Enterpr 17,255
rhui-REGION-rhel-server-rh-common/7Server/x86_64 Red Hat Enterpr    228
repolist: 38,284
[root@ip-172-31-4-62 ~]# yum install php71u
Loaded plugins: amazon-id, replace, rhui-lb, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package mod_php71u.x86_64 0:7.1.9-2.ius.el7 will be installed
--> Processing Dependency: php-common(x86-64) = 7.1.9-2.ius.el7 for package: mod_php71u-7.1.9-2.ius.el7.x86_64
--> Running transaction check
---> Package php71u-common.x86_64 0:7.1.9-2.ius.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================
 Package            Arch        Version                 Repository
                                                                  Size
=======================================================================
Installing:
 mod_php71u         x86_64      7.1.9-2.ius.el7         ius      3.0 M
Installing for dependencies:
 php71u-common      x86_64      7.1.9-2.ius.el7         ius      1.1 M

Transaction Summary
=======================================================================
Install  1 Package (+1 Dependent package)

Total download size: 4.1 M
Installed size: 17 M
Is this ok [y/d/N]: y
Downloading packages:
(1/2): php71u-common-7.1.9-2.ius.el7.x86_64.rpm   | 1.1 MB   00:00     
(2/2): mod_php71u-7.1.9-2.ius.el7.x86_64.rpm      | 3.0 MB   00:00     
-----------------------------------------------------------------------
Total                                     7.6 MB/s | 4.1 MB  00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : php71u-common-7.1.9-2.ius.el7.x86_64                1/2 
  Installing : mod_php71u-7.1.9-2.ius.el7.x86_64                   2/2 
  Verifying  : php71u-common-7.1.9-2.ius.el7.x86_64                1/2 
  Verifying  : mod_php71u-7.1.9-2.ius.el7.x86_64                   2/2 

Installed:
  mod_php71u.x86_64 0:7.1.9-2.ius.el7                                  

Dependency Installed:
  php71u-common.x86_64 0:7.1.9-2.ius.el7                               

Complete!
[root@ip-172-31-4-62 ~]# yum install icingaweb2
Loaded plugins: amazon-id, replace, rhui-lb, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package icingaweb2.noarch 0:2.4.2-1.el7.icinga will be installed
--> Processing Dependency: icingaweb2-vendor-lessphp = 2.4.2-1.el7.icinga for package: icingaweb2-2.4.2-1.el7.icinga.noarch
--> Processing Dependency: icingaweb2-common = 2.4.2-1.el7.icinga for package: icingaweb2-2.4.2-1.el7.icinga.noarch
--> Processing Dependency: icingaweb2-vendor-Parsedown = 2.4.2-1.el7.icinga for package: icingaweb2-2.4.2-1.el7.icinga.noarch
--> Processing Dependency: icingaweb2-vendor-JShrink = 2.4.2-1.el7.icinga for package: icingaweb2-2.4.2-1.el7.icinga.noarch
--> Processing Dependency: icingaweb2-vendor-HTMLPurifier = 1:2.4.2-1.el7.icinga for package: icingaweb2-2.4.2-1.el7.icinga.noarch
--> Processing Dependency: icingaweb2-vendor-dompdf = 2.4.2-1.el7.icinga for package: icingaweb2-2.4.2-1.el7.icinga.noarch
--> Processing Dependency: php-Icinga = 2.4.2-1.el7.icinga for package: icingaweb2-2.4.2-1.el7.icinga.noarch
--> Running transaction check
---> Package icingaweb2-common.noarch 0:2.4.2-1.el7.icinga will be installed
---> Package icingaweb2-vendor-HTMLPurifier.noarch 1:2.4.2-1.el7.icinga will be installed
---> Package icingaweb2-vendor-JShrink.noarch 0:2.4.2-1.el7.icinga will be installed
---> Package icingaweb2-vendor-Parsedown.noarch 0:2.4.2-1.el7.icinga will be installed
---> Package icingaweb2-vendor-dompdf.noarch 0:2.4.2-1.el7.icinga will be installed
---> Package icingaweb2-vendor-lessphp.noarch 0:2.4.2-1.el7.icinga will be installed
---> Package php-Icinga.noarch 0:2.4.2-1.el7.icinga will be installed
--> Processing Dependency: icingaweb2-vendor-zf1 = 2.4.2-1.el7.icinga for package: php-Icinga-2.4.2-1.el7.icinga.noarch
--> Processing Dependency: php-pecl-imagick for package: php-Icinga-2.4.2-1.el7.icinga.noarch
--> Processing Dependency: php-gd for package: php-Icinga-2.4.2-1.el7.icinga.noarch
--> Processing Dependency: php-intl for package: php-Icinga-2.4.2-1.el7.icinga.noarch
--> Running transaction check
---> Package icingaweb2-vendor-zf1.noarch 0:2.4.2-1.el7.icinga will be installed
---> Package php-gd.x86_64 0:5.4.16-42.el7 will be installed
--> Processing Dependency: php-common(x86-64) = 5.4.16-42.el7 for package: php-gd-5.4.16-42.el7.x86_64
--> Processing Dependency: libjpeg.so.62(LIBJPEG_6.2)(64bit) for package: php-gd-5.4.16-42.el7.x86_64
--> Processing Dependency: libpng15.so.15(PNG15_0)(64bit) for package: php-gd-5.4.16-42.el7.x86_64
--> Processing Dependency: libXpm.so.4()(64bit) for package: php-gd-5.4.16-42.el7.x86_64
--> Processing Dependency: libjpeg.so.62()(64bit) for package: php-gd-5.4.16-42.el7.x86_64
--> Processing Dependency: libpng15.so.15()(64bit) for package: php-gd-5.4.16-42.el7.x86_64
--> Processing Dependency: libt1.so.5()(64bit) for package: php-gd-5.4.16-42.el7.x86_64
---> Package php-pecl-imagick.x86_64 0:3.1.0-0.6.RC2.el7 will be installed
--> Processing Dependency: /usr/bin/pecl for package: php-pecl-imagick-3.1.0-0.6.RC2.el7.x86_64
--> Processing Dependency: /usr/bin/pecl for package: php-pecl-imagick-3.1.0-0.6.RC2.el7.x86_64
--> Processing Dependency: libMagickWand.so.5()(64bit) for package: php-pecl-imagick-3.1.0-0.6.RC2.el7.x86_64
--> Processing Dependency: libMagickCore.so.5()(64bit) for package: php-pecl-imagick-3.1.0-0.6.RC2.el7.x86_64
---> Package php71u-intl.x86_64 0:7.1.9-2.ius.el7 will be installed
--> Running transaction check
---> Package ImageMagick.x86_64 0:6.7.8.9-15.el7_2 will be installed
--> Processing Dependency: libtiff.so.5(LIBTIFF_4.0)(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libHalf.so.6()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libICE.so.6()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libIex.so.6()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libIexMath.so.6()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libIlmImf.so.7()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libIlmThread.so.6()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libImath.so.6()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libSM.so.6()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libXext.so.6()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libXt.so.6()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libcairo.so.2()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libgdk_pixbuf-2.0.so.0()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libgs.so.9()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libjasper.so.1()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libltdl.so.7()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libpango-1.0.so.0()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libpangocairo-1.0.so.0()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: librsvg-2.so.2()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libtiff.so.5()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
--> Processing Dependency: libwmflite-0.2.so.7()(64bit) for package: ImageMagick-6.7.8.9-15.el7_2.x86_64
---> Package libXpm.x86_64 0:3.5.12-1.el7 will be installed
---> Package libjpeg-turbo.x86_64 0:1.2.90-5.el7 will be installed
---> Package libpng.x86_64 2:1.5.13-7.el7_2 will be installed
---> Package php-common.x86_64 0:5.4.16-42.el7 will be installed
---> Package php-pear.noarch 1:1.9.4-21.el7 will be installed
--> Processing Dependency: php-cli for package: 1:php-pear-1.9.4-21.el7.noarch
--> Processing Dependency: php-posix for package: 1:php-pear-1.9.4-21.el7.noarch
--> Processing Dependency: php-xml for package: 1:php-pear-1.9.4-21.el7.noarch
---> Package t1lib.x86_64 0:5.1.2-14.el7 will be installed
--> Running transaction check
---> Package OpenEXR-libs.x86_64 0:1.7.1-7.el7 will be installed
---> Package cairo.x86_64 0:1.14.8-2.el7 will be installed
--> Processing Dependency: libEGL.so.1()(64bit) for package: cairo-1.14.8-2.el7.x86_64
--> Processing Dependency: libGL.so.1()(64bit) for package: cairo-1.14.8-2.el7.x86_64
--> Processing Dependency: libXrender.so.1()(64bit) for package: cairo-1.14.8-2.el7.x86_64
--> Processing Dependency: libpixman-1.so.0()(64bit) for package: cairo-1.14.8-2.el7.x86_64
---> Package gdk-pixbuf2.x86_64 0:2.36.5-1.el7 will be installed
---> Package ghostscript.x86_64 0:9.07-28.el7_4.2 will be installed
--> Processing Dependency: lcms2 >= 2.6 for package: ghostscript-9.07-28.el7_4.2.x86_64
--> Processing Dependency: urw-fonts >= 1.1 for package: ghostscript-9.07-28.el7_4.2.x86_64
--> Processing Dependency: ghostscript-fonts for package: ghostscript-9.07-28.el7_4.2.x86_64
--> Processing Dependency: poppler-data for package: ghostscript-9.07-28.el7_4.2.x86_64
--> Processing Dependency: libcups.so.2()(64bit) for package: ghostscript-9.07-28.el7_4.2.x86_64
--> Processing Dependency: libcupsimage.so.2()(64bit) for package: ghostscript-9.07-28.el7_4.2.x86_64
--> Processing Dependency: liblcms2.so.2()(64bit) for package: ghostscript-9.07-28.el7_4.2.x86_64
---> Package ilmbase.x86_64 0:1.0.3-7.el7 will be installed
---> Package jasper-libs.x86_64 0:1.900.1-31.el7 will be installed
---> Package libICE.x86_64 0:1.0.9-9.el7 will be installed
---> Package libSM.x86_64 0:1.2.2-2.el7 will be installed
---> Package libXext.x86_64 0:1.3.3-3.el7 will be installed
---> Package libXt.x86_64 0:1.1.5-3.el7 will be installed
---> Package librsvg2.x86_64 0:2.40.16-1.el7 will be installed
---> Package libtiff.x86_64 0:4.0.3-27.el7_3 will be installed
--> Processing Dependency: libjbig.so.2.0()(64bit) for package: libtiff-4.0.3-27.el7_3.x86_64
---> Package libtool-ltdl.x86_64 0:2.4.2-22.el7_3 will be installed
---> Package libwmf-lite.x86_64 0:0.2.8.4-41.el7_1 will be installed
---> Package pango.x86_64 0:1.40.4-1.el7 will be installed
--> Processing Dependency: harfbuzz(x86-64) >= 1.0.3 for package: pango-1.40.4-1.el7.x86_64
--> Processing Dependency: libXft(x86-64) >= 2.0.0 for package: pango-1.40.4-1.el7.x86_64
--> Processing Dependency: libthai(x86-64) >= 0.1.9 for package: pango-1.40.4-1.el7.x86_64
--> Processing Dependency: libthai.so.0(LIBTHAI_0.1)(64bit) for package: pango-1.40.4-1.el7.x86_64
--> Processing Dependency: libXft.so.2()(64bit) for package: pango-1.40.4-1.el7.x86_64
--> Processing Dependency: libharfbuzz.so.0()(64bit) for package: pango-1.40.4-1.el7.x86_64
--> Processing Dependency: libthai.so.0()(64bit) for package: pango-1.40.4-1.el7.x86_64
---> Package php-cli.x86_64 0:5.4.16-42.el7 will be installed
---> Package php-process.x86_64 0:5.4.16-42.el7 will be installed
---> Package php-xml.x86_64 0:5.4.16-42.el7 will be installed
--> Running transaction check
---> Package cups-libs.x86_64 1:1.6.3-29.el7 will be installed
--> Processing Dependency: libavahi-client.so.3()(64bit) for package: 1:cups-libs-1.6.3-29.el7.x86_64
--> Processing Dependency: libavahi-common.so.3()(64bit) for package: 1:cups-libs-1.6.3-29.el7.x86_64
---> Package ghostscript-fonts.noarch 0:5.50-32.el7 will be installed
--> Processing Dependency: xorg-x11-font-utils for package: ghostscript-fonts-5.50-32.el7.noarch
---> Package harfbuzz.x86_64 0:1.3.2-1.el7 will be installed
--> Processing Dependency: libgraphite2.so.3()(64bit) for package: harfbuzz-1.3.2-1.el7.x86_64
---> Package jbigkit-libs.x86_64 0:2.0-11.el7 will be installed
---> Package lcms2.x86_64 0:2.6-3.el7 will be installed
---> Package libXft.x86_64 0:2.3.2-2.el7 will be installed
---> Package libXrender.x86_64 0:0.9.10-1.el7 will be installed
---> Package libthai.x86_64 0:0.1.14-9.el7 will be installed
---> Package mesa-libEGL.x86_64 0:17.0.1-6.20170307.el7 will be installed
--> Processing Dependency: mesa-libgbm = 17.0.1-6.20170307.el7 for package: mesa-libEGL-17.0.1-6.20170307.el7.x86_64
--> Processing Dependency: libdrm.so.2()(64bit) for package: mesa-libEGL-17.0.1-6.20170307.el7.x86_64
--> Processing Dependency: libgbm.so.1()(64bit) for package: mesa-libEGL-17.0.1-6.20170307.el7.x86_64
--> Processing Dependency: libxshmfence.so.1()(64bit) for package: mesa-libEGL-17.0.1-6.20170307.el7.x86_64
---> Package mesa-libGL.x86_64 0:17.0.1-6.20170307.el7 will be installed
--> Processing Dependency: mesa-libglapi = 17.0.1-6.20170307.el7 for package: mesa-libGL-17.0.1-6.20170307.el7.x86_64
--> Processing Dependency: libXdamage.so.1()(64bit) for package: mesa-libGL-17.0.1-6.20170307.el7.x86_64
--> Processing Dependency: libXfixes.so.3()(64bit) for package: mesa-libGL-17.0.1-6.20170307.el7.x86_64
--> Processing Dependency: libXxf86vm.so.1()(64bit) for package: mesa-libGL-17.0.1-6.20170307.el7.x86_64
--> Processing Dependency: libglapi.so.0()(64bit) for package: mesa-libGL-17.0.1-6.20170307.el7.x86_64
---> Package pixman.x86_64 0:0.34.0-1.el7 will be installed
---> Package poppler-data.noarch 0:0.4.6-3.el7 will be installed
---> Package urw-fonts.noarch 0:2.4-16.el7 will be installed
--> Running transaction check
---> Package avahi-libs.x86_64 0:0.6.31-17.el7 will be installed
---> Package graphite2.x86_64 0:1.3.10-1.el7_3 will be installed
---> Package libXdamage.x86_64 0:1.1.4-4.1.el7 will be installed
---> Package libXfixes.x86_64 0:5.0.3-1.el7 will be installed
---> Package libXxf86vm.x86_64 0:1.1.4-1.el7 will be installed
---> Package libdrm.x86_64 0:2.4.74-1.el7 will be installed
--> Processing Dependency: libpciaccess.so.0()(64bit) for package: libdrm-2.4.74-1.el7.x86_64
---> Package libxshmfence.x86_64 0:1.2-1.el7 will be installed
---> Package mesa-libgbm.x86_64 0:17.0.1-6.20170307.el7 will be installed
---> Package mesa-libglapi.x86_64 0:17.0.1-6.20170307.el7 will be installed
---> Package xorg-x11-font-utils.x86_64 1:7.5-20.el7 will be installed
--> Processing Dependency: libXfont.so.1()(64bit) for package: 1:xorg-x11-font-utils-7.5-20.el7.x86_64
--> Processing Dependency: libfontenc.so.1()(64bit) for package: 1:xorg-x11-font-utils-7.5-20.el7.x86_64
--> Running transaction check
---> Package libXfont.x86_64 0:1.5.2-1.el7 will be installed
---> Package libfontenc.x86_64 0:1.1.3-3.el7 will be installed
---> Package libpciaccess.x86_64 0:0.13.4-3.el7_3 will be installed
--> Processing Conflict: php71u-common-7.1.9-2.ius.el7.x86_64 conflicts php-common < 7.1.9-2.ius.el7
--> Finished Dependency Resolution
Error: php71u-common conflicts with php-common-5.4.16-42.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by lippserd** [comment]
Just for the records, this is the third issue you've opened regarding the very same non-problem. It is your system so it is your responsibility to fix your system. If you are unable to install Web 2 with the PHP version provided by the community repository IUS just disable it.

**Comment by sighupper** [comment]
Yes, please ignore this one. I thought the other one was closed.I will now only work through case: 3019. Sorry! Thank you :)
