### ISSUE TITLE
Having multiple module paths creates a chain of symbolic links instead of a direct one to the module directory

### ISSUE THREAD

**Issue by theFeu** [Icinga/icingaweb2#3023]
If you have more than just the default module path enabled, then Icingaweb2 should link the modules to enabled modules.

Right now it will create a link in enabled modules which points to the default module path and which then points to the custom module path.

**Comment by lippserd** [comment]
Hi Feu,

How did you test this? I've never heard of this issue nor can I reproduce it.

Cheers,
Eric

**Comment by lippserd** [comment]
We were unable to reproduce this issue. I'll close it.
