### ISSUE TITLE
Uncaught exception only on services with downtime

### ISSUE THREAD

**Issue by kam1sh** [Icinga/icingaweb2#3028]
Icingaweb2 throws an exception when I open info window only on services that have downtimes.
For example, in default Icinga 2 configuration service "load" have downtime.

There's error info:
```
Warning: Uncaught exception 'ErrorException' with message 'require_once(HTMLPurifier/Bootstrap.php): failed to open stream: No such file or directory' in /usr/share/icingaweb2/modules/monitoring/application/views/helpers/EscapeComment.php:26 Stack trace: #0 /usr/share/icingaweb2/modules/monitoring/application/views/helpers/EscapeComment.php(26): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'require_once(HT...', '/usr/share/icin...', 26, Array) #1 /usr/share/icingaweb2/modules/monitoring/application/views/helpers/EscapeComment.php(26): Zend_View_Helper_EscapeComment::escapeComment() #2 [internal function]: Zend_View_Helper_EscapeComment->escapeComment('Scheduled downt...') #3 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(346): call_user_func_array(Array, Array) #4 /usr/share/php/Icinga/Web/View.php(250): Zend_View_Abstract->__call('escapeComment', Array) #5 /usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/components/downtime.phtml(106): Icinga\Web\View->_ in /usr/share/icingaweb2/modules/monitoring/application/views/helpers/EscapeComment.php on line 26

Fatal error: Zend_View_Helper_EscapeComment::escapeComment(): Failed opening required 'HTMLPurifier/Bootstrap.php' (include_path='/usr/share/icingaweb2/library/vendor:.:/usr/local/lib/php') in /usr/share/icingaweb2/modules/monitoring/application/views/helpers/EscapeComment.php on line 26
```
Btw, file mentioned in exception info exists:
```
# ls -l /usr/share/php/HTMLPurifier/Bootstrap.php 
-rw-r--r-- 1 www-data www-data 4613 Oct 20  2014 /usr/share/php/HTMLPurifier/Bootstrap.php
```

## Expected Behavior

If i open service "icinga" (`/icingaweb2/dashboard#!/icingaweb2/monitoring/service/show?host=...&service=icinga`) or anything else without downtime config -- everything OK. I see all info like `Plugin Output`, `Problem handling`, `Performance data`, `Notifications`, `Check execution` etc.

## Current Behavior

if I open info for service "load" (`/icingaweb2/dashboard#!/icingaweb2/monitoring/service/show?host=...&service=load`) on any host, it shows only `Plugin Output` and `Problem handling`.  After `Problem handling` info it shows warning and fatal error. 

## Possible Solution

I solved it by adding this string into php-fpm config:
`php_admin_value[include_path] = /usr/share/icingaweb2/library/vendor:/usr/local/lib/php:.:/usr/share/php`

## Steps to Reproduce (for bugs)

1. Add service with downtime. For example, load in default configuration:
```
apply Service "load" {
  import "generic-service"
  check_command = "load"
  /* Used by the ScheduledDowntime apply rule in `downtimes.conf`. */
  vars.backup_downtime = "02:00-03:00"
  assign where host.name == NodeName
}
```
2. Add ScheduledDowntime object:
```
apply ScheduledDowntime "backup-downtime" to Service {
  author = "icingaadmin"
  comment = "Scheduled downtime for backup"

  ranges = {
    monday = service.vars.backup_downtime
    tuesday = service.vars.backup_downtime
    wednesday = service.vars.backup_downtime
    thursday = service.vars.backup_downtime
    friday = service.vars.backup_downtime
    saturday = service.vars.backup_downtime
    sunday = service.vars.backup_downtime
  }

  assign where service.vars.backup_downtime != ""
}
```
3. Select that service in Icingaweb2.
4. ???

## Context

I'm going to use downtimes in the future, so I want to know is there a solution. Also, i'm curious. At first i thought there's not enough php-fpm modules, but in this case i wouldn't open any service at all! So i decided that's strange and better for you to know about that weird behaviour.

## Your Environment

* Icinga Web 2 version and modules: Icingaweb2 -- 2.4.2, module `monitoring` -- 2.4.2
* Version used: r2.7.1-1
* Operating System and version: Icinga2 -- CentOS 7, Icingaweb2 -- Debian 8
* Enabled features: api checker command ido-pgsql mainlog notification
* Config validation: All ok.
`information/cli: Finished validating the configuration file(s).`

**Comment by kam1sh** [comment]
OK, I made it work and updated *solution* paragraph above. But I don't know is it fine solution or not. And was it my problem?...

**Comment by lippserd** [comment]
Hi,

Thanks for the report. `/usr/share/php` is the correct default include path and Debian should have this as default. This is no issue on our end. The changes you've made are perfect.

Cheers,
Eric
