### ISSUE TITLE
Uncaught exception related to missing PHP DOM extension

### ISSUE THREAD

**Issue by cite** [Icinga/icingaweb2#3030]
Trying to view service `DBPROXY` on host `tor1pro-be-1` yields an uncaught exception:

```

Fatal error: Uncaught Error: Class 'DOMDocument' not found in
--
/usr/share/icingaweb2/modules/monitoring/application/views/helpers/PluginOutput.php:105
Stack trace:
#0 /usr/share/icingaweb2/modules/monitoring/application/views/helpers/PluginOutput.php(86):
Zend_View_Helper_PluginOutput->processHtml('<a href="https:...')
#1 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(345):
Zend_View_Helper_PluginOutput->pluginOutput('<a href="https:...')
#2 /usr/share/php/Icinga/Web/View.php(250):
Zend_View_Abstract->__call('pluginOutput', Array)
#3 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/components/output.phtml(2):
Icinga\Web\View->__call('pluginOutput', Array)
#4 /usr/share/php/Icinga/Web/View.php(231):
include('zend.view:///us...')
#5 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#6 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/partials/object/detail-content.phtml(2):
Zend_View_Abstra in /usr/share/icingaweb2/modules/monitoring/application/views/helpers/PluginOutput.php on line 105
```
Service check output is: `0: OK`

This is "fixed" by installing the PHP DOM extension, however:

* I didn't find any documentation mentioning that I'd actually need the PHP DOM extension
* the corresponding code section suggest that this is just code for backward compatibility with the Icinga 1 Classic UI;  the problem, however, was reproducable with plain Icingaweb 2

Versions: icingaweb2, 2.4.2, running on PHP 7.1.10 (fpm).

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I assume that you did not use our packages for installing Web 2 right? Else this would be a packaging issue. I'll add the dom/xml dependency to our installation doc.
The code is not just for backward compatibility.

Best regards
Eric
