### ISSUE TITLE
Allow disabling user password changes

### ISSUE THREAD

**Issue by olasd** [Icinga/icingaweb2#3033]
Hi,

I'm running infrastructure for [a Free Software project](https://www.softwareheritage.org), and we want to be running as transparently as possible. To that end, we're publishing all our puppet manifests, and we're starting to open up our monitoring.

One of the steps towards this is opening up our icingaweb2 instance to a read-only user.

Unfortunately, we're using the "db" authentication backend, and our guest user can change its own password, which is somewhat of a problem.

I'm not sure where the config knob should be (a permission, a field in the authentication backend, or something else entirely...) but I'd be happy to contribute a patch if you think the feature is worthwhile.

Thanks!

**Comment by Al2Klimov** [comment]
Hello @olasd,

is it just the password you worry about or should the user be *completely* read-only? (preferences, navigation...)

Best,
AK

**Comment by Al2Klimov** [comment]
"I'm not sure where the config knob should be (...)" – I'm neither. Maybe we should even introduce an "anonymous" user which is default-provided by a new auth-backend type (w/ configurable name) – so we can assign permissions like monitoring mod. usage to this "user". But maybe @lippserd, @Thomas-Gelf or @nilmerg know it better.

**Comment by Al2Klimov** [comment]
Note: Maybe we should even introduce hooks for custom auth backends?

**Comment by Thomas-Gelf** [comment]
@Al2Klimov: you can use `provideUserBackend()` from your module. Still, that should be overkill for this simple use-case. Assigning "every" user a specific role can be accomplished with `users = *`. As far as I know this should have been broken since v2.2 or similar, but should now be fixed with v2.5.0. In case you need only one Read-Only user it can be simplified even more, I'd then suggest to use `external` authentication, `SetEnv REMOTE_USER` to "some username" and grant that user specific permissions.

Cheers,
Thomas

**Comment by Al2Klimov** [comment]
@Thomas-Gelf And what about "I'm not sure where the config knob should be (...)"?

**Comment by Thomas-Gelf** [comment]
No config know needed as long as you're using external authentication. In case you need that feature for db-based authentication, I'd not make a global config knob at all. It would then belong to a flag in the DB, stored with every single user.

**Comment by Al2Klimov** [comment]
And for preferences, etc.?

**Comment by olasd** [comment]
> Hello @olasd,
> 
> is it just the password you worry about or should the user be completely read-only? (preferences, navigation...)

Hi,

Now that I've played around a bit more, I think we would need all preferences, navigation, etc. to be read-only. Which means that we would need a way to 1/ set the settings somehow; 2/ lock them down.

Thanks for the feedback!
Nicolas

**Comment by lippserd** [comment]
Hi,

You could combine external auth for the guest mode and internal auth for admin mode. The URLs must be different though. If you're using apache, just set `SetEnv REMOTE_USER guest` in the config for Web 2. Then set the permissions and restrictions for the `guest` user. I think you can't disable the guest to be allowed to change preferences, add custom dashboards and navigation items. You could reset them once every night though. If you want this to be configureable, please open a new issue.

Best,
Eric
