### ISSUE TITLE
Auto-detaching DOM elements

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#3039]
... which are attached back on autorefresh.

**Comment by friesoft** [comment]
This sounds like it could help with #2820 ?

**Comment by friesoft** [comment]
Could you test the iframe usecase as well? Wouldn't it be cool to have grafana iframes embedded to have really live graphs which are fully interactive?
To be honest I have my doubts this will work as your code uses detach which will reload an iframe to my understanding :(

**Comment by Al2Klimov** [comment]
Oh, iframes? Then I misread the issue. No, as @lippserd already said, we can't not reload an iframe that way.
