### ISSUE TITLE
Provide more differentiation between rows in list views

### ISSUE THREAD

**Issue by OllyMason** [Icinga/icingaweb2#3049]
Enhancement request: Service and host lists might be more easily understood if each line is slightly more distinguishable from the next, especially where objects in the adjacent rows are in the same state. 

## Possible Solution
outline rows in a style similar to the folder view in github, or zebra stripe with e.g.
```
@color-odd: #eeeeff;
@color-even: #fdfdff;
table.state-table tr:nth-child(odd) td{
  background-color: @color-odd;
}
table.state-table tr:nth-child(even) td{
  background-color: @color-even;
}
```
(The above is not in a pull request, as it interferes with mouseover highlighting.)

### Environment
* Icinga Web 2 version: 2.4.2

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We thought about similar solutions in the past but did not find anything which made most of us happy. I'm open for good ideas here which do not interfere with current the user experience.

**Comment by lippserd** [comment]
Moved to #3416.
