### ISSUE TITLE
icingacli monitoring list does not show host without services

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2#3050]
## Expected Behavior

```
[root@icinga2-node1 ~]# icingacli monitoring list

   DOWN  down: CRITICAL: Check was successful.
```

## Current Behavior

Hosts without services are not listed.

## Steps to Reproduce (for bugs)

1. Create a single host in Icinga 2

```
object Host "down" {
  check_command = "dummy"
  vars.dummy_state = 2
}
```

2. Run icingacli command

```
[root@icinga2-node1 ~]# icingacli monitoring list

[root@icinga2-node1 ~]#
```

## Context

If you'll define a service object for that host, it works again.

```
object Host "down" {
  check_command = "dummy"
  vars.dummy_state = 2
}

object Service "critical" {
  host_name = "down"
  check_command = "dummy"
  vars.dummy_state = 2
}
```

```
[root@icinga2-node1 ~]# icingacli monitoring list

   DOWN  down: CRITICAL: Check was successful.
   PEND  └─ critical (For 4m 10s)

```

## Your Environment

* Icinga Web 2 version and modules (System - About): v2.4.2
* Version used (`icinga2 --version`): Icinga 2 v2.7.1
* Operating System and version: CentOS 7
* Enabled features (`icinga2 feature list`): `checker command ido-mysql mainlog notification`

**Comment by Al2Klimov** [comment]
Confirmed. (Latest master & latest Icinga 2 Core)
