### ISSUE TITLE
Permissions: Add a view which lists the permissions and assigned/affected users

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2#3053]
## Possible Solution

Traverse the roles.ini defined users and collect that into permissions with an array of users/usergroups.

## Context

If you happen to have many users with different fine granular permissions, it is really hard to determine which users have just "read only" permissions, others may view specific modules, and so on. 

This could be made sort of an inspect/overview/inventory view which helps analyze Icinga Web 2 further. Could also help with troubleshooting, e.g. to see if one permission is not there for one user.

Currently the interface for selecting permissions for a role is a long list, and you might accidentally forget one in between. Or assign one too much.

**Comment by lippserd** [comment]
Hi Michi,

This is a good addition and should be implemented in one of our next releases.

Cheers,
Eric
