### ISSUE TITLE
Featuer Request: Filtering on Notification Type in Notification History

### ISSUE THREAD

**Issue by robertkrenn** [Icinga/icingaweb2#3054]
In greater environments there are many entries in the historical view of notifications in icingaweb2. We are using different types of notifications for alerting different services. SMS and voice call for really high priority services, mail notifications for less important services. All these notifications are listed in the historical view, but it would be very useful to be able to filter on the exact notification type, for example to get a quick view on which SMS for high priority services where sent during the last x days, as a report to the team leader.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Unfortunately we don't have any data related to the type of a notification in our database. But we will definitely consider this when redesigning our whole data storage which will happen this year.

Cheers,
Eric
