### ISSUE TITLE
Hook for resource locking

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#3055]
## Current Behavior

* If I try to delete an SQL DB resource used by an IDO backend, nothing prevents me from doing that.
* If I rename an SQL DB resource used by an IDO backend, nothing prevents me from doing that and nothing updates the backend config.

## Expected Behavior

* If I try to delete an SQL DB resource used by an IDO backend, something prevents me from doing that.
* If I rename an SQL DB resource used by an IDO backend, something updates the backend config.

## Possible Solution

A new hook which is used by module components which use resources.

* Before every resource deletion it is asked if something uses the respective resource. If yes, the deletion shall fail w/ a message provided by the hook.
* Before every resource renaming it is asked if something uses the respective resource and whether that *something* can cascade the name change. If cascading isn't possible, the renaming shall fail w/ a message provided by the hook. After renaming it cascades the name change.

**Comment by Al2Klimov** [comment]
This could also be interesting for #3035.

**Comment by nilmerg** [comment]
Resources are managed by administrators which are expected to know what they're doing. If that's not the case, well...
