### ISSUE TITLE
`Port is required and must not be empty` when adding new resource

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [Icinga/icingaweb2#3056]
Trying to add a database resource for director and encountered error

## Expected Behavior

Successfully validate/add resource

## Current Behavior

Unable to add a new resource

## Steps to Reproduce (for bugs)

Configuration / Application / Resources and create a new database resource

1. Select SQL Database, PostgresSQL
2. Port 5432 auto populated
3. fill remaining fields and click Validate Configuration/Save Changes
4. Port field cleared and red error `Port is required and must not be empty`
5. Enter 5432 into Port field and submit again
6. Port field cleared and red error `Port is required and must not be empty`

## Context

Sounds similar to Bug 9306, which should have been fixed long ago

## Your Environment

* Icinga Web 2 version and modules (System - About):
* Version used (`icinga2 --version`):  2.4.2-1.xenial
* Operating System and version: Ubuntu 16.04.3 LTS
* Enabled features (`icinga2 feature list`): api checker ido-pgsql mainlog notification
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

```
$ sudo icinga2 daemon -C
information/cli: Icinga application loader (version: r2.7.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: icinga2.home.nohdmi.com
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 13 Notifications.
information/ConfigItem: Instantiated 207 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 1 Host.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 12 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

**Comment by dnsmichi** [comment]
This is a regression in v2.4.2 and should be fixed in git master for the next release. Please check #2998 and #3010.

**Comment by buggsdummy** [comment]
Still happening, glad this has been reported... Thanks!

**Comment by vkafed** [comment]
any workaround? can't add ldap :-(
