### ISSUE TITLE
Erros with graphite and fresh icinga2 installtion

### ISSUE THREAD

**Issue by habib-the-sweet** [Icinga/icingaweb2#3057]
I trying to install graphite on fresh icinga2 instance. When I trying to create any graphic I've got an error:

> Warning: Exception caught by form: Plugin by name 'Date' was not found in the registry; used paths: Icinga\Web\Form\Element\: /usr/share/php/Icinga/Web/Form/Element/ Zend_Form_Element_: Zend/Form/Element/ Stack Trace: #0 /usr/share/php/Zend/Form.php(1111): Zend_Loader_PluginLoader->load('Date') #1 /usr/share/php/Icinga/Web/Form.php(932): Zend_Form->createElement('date', 'start_date', Array) #2 /usr/share/php/Zend/Form.php(1040): Icinga\Web\Form->createElement('date', 'start_date', Array) #3 /usr/share/php/Zend/Form.php(1165): Zend_Form->addElement('date', 'start_date', Array) #4 /usr/share/icingaweb2/modules/graphite/application/forms/TimeRangePicker/CustomForm.php(78): Zend_Form->addElements(Array) #5 /usr/share/php/Icinga/Web/Form.php(772): Icinga\Module\Graphite\Forms\TimeRangePicker\CustomForm->createElements(Array) #6 /usr/share/php/Icinga/Web/Form.php(1535): Icinga\Web\Form->create() #7 /usr/share/php/Zend/Form.php(2920): Icinga\Web\Form->render() #8 /usr/share/icingaweb2/modules/graphite/library/Graphite/Web/Co in /usr/share/php/Zend/Form.php on line 2925

Environment:
Icinga Web 2  2.1.0 modules: doc 2.1.0, graphite 0.0.0, monitoring 2.1.0
Icinga2 r2.4.1-1
Ubuntu 16.04.3 LTS
Enabled features: checker graphite ido-mysql mainlog notification

**Comment by kirjastojk** [comment]
@habib-the-sweet what was the solution? I have the same problem.

**Comment by habib-the-sweet** [comment]
@kirjastojk some instructions recommend to clone with "maxdepth" argument. You must do full clone of the plugin repo

**Comment by kirjastojk** [comment]
@habib-the-sweet Thanks for helping. I cloned the master branch of https://github.com/Icinga/icingaweb2-module-graphite with all of its commits (```git clone https://github.com/Icinga/icingaweb2-module-graphite.git graphite```). Did you use some different repository? I didn't quite get what fixed this for you. And what is the maxdepth argument? In the man page for git-clone there is --depth, but using this parameter shouldn't make any difference.

**Comment by lippserd** [comment]
@kirjastojk I think you're using a very old Icinga Web 2 version.

**Comment by kirjastojk** [comment]
@lippserd yes, I used 2.4.1, works with 2.5. It would be nice if some real person could sign the key 0xC6E319C334410682 that is used for the Debian packages.
