### ISSUE TITLE
using icinga director, remove hosts (with empty zone as result) doesn't work

### ISSUE THREAD

**Issue by tlo8640** [Icinga/icingaweb2#3059]
Hello
coming from

https://github.com/Icinga/icingaweb2-module-director/issues/1219

Don't know if this is a Icingaweb2 Director Problem or an Icinga2 Problem.
Tried it on different icinga2 setupups and ran always into this problem.

Using Icinga Director for configuring icinga2. When you try to remove hosts, wich would lead into an empty zone. The hosts will be removed from Director, but they still exist in icinga2 config after deploying the director config.

## Expected Behavior
Host should be from cinga2 config, too.

## Current Behavior
When you are using Icinga Director for configuring Icinga2 and you want to remove some hosts and after removing a zone would be empty, these hosst aren't removed from icinga2, but they are removed from Icinga2 Director.

## Possible Solution
Don't know how Icinga Director deploys its config. When deploying the new config with the empty zone, no hostz config for the empty zone is created (seem to me) and therefore this zone will not be touched and keeps it former config?

## Steps to Reproduce (for bugs)

    1.setup icinga2 with director
    2.create one or more zones
    3. deploy one or more hosts into the zone(s), only hostchecks are ok
    4. remove all hosts from one zone so that the zone should be empty
    5. deploy new config with director
    6. voila: the removed hosts still exist in icinga2, but are removed from director

## Context
First we ran into this problem when we tried configuration with Icinga Director, because not so many Hosts where in the testing environment and they were often added and removed.
Also in production the problem could be a problem, for instance, when you redesign your zones infrastructure or something like this and you have to move servers between zones.

## Your Environment
* Director version (System - About): 1.4.1
* Version used (`icinga2 --version`): 2.7.1.1
* Operating System and version: RHEL 7.4

**Comment by tlo8640** [comment]
I must be drunk...
This ticket is completely wrong here, could you close it, please.
I will open a new one in the Icinga2 project, where it should belong.
Thanks, Thomas

**Comment by dnsmichi** [comment]
You can close tickets you've created by yourself :)

**Comment by tlo8640** [comment]
Now I see it, definitely to early.. ;-)
Thanks for this advice
Thomas

**Comment by tlo8640** [comment]
Ticket closed because it was the wrong place, belongs to icinga2:
https://github.com/Icinga/icinga2/issues/5722
