### ISSUE TITLE
Documentation for Single Sign-on

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2#3069]
Hi,

I've heard that Single Sign On is possible with icingaweb2 and Apache using AD, Kerberos or ADFS. Can you provide a documentation chapter for that?

**Comment by dnsmichi** [comment]
Can you or anyone else who successfully has setup this, provide a documentation PR? :)

**Comment by lazyfrosch** [comment]
Have a look at https://gist.github.com/lazyfrosch/0a29bd04e1734865d6ca4de8029ed596

You need to either get the keytab from an AD admin, or create it yourself.

**Comment by lazyfrosch** [comment]
Added an example for keytab.

The principal including the HTTP domain name must be set in AD.

There are lots of special configs and corner cases here. Have a look for other guides on the net.

Icingaweb2 itself will just trust the local username from Apache.

**Comment by cstegm** [comment]
In addition you have to enable Autologin by adding the following to "/etc/icingaweb2/authentication.ini" 

```
[autologin]
backend = external

```

**Comment by kobmaki** [comment]
Using the kerberos-libs from the OS is helpful. Some older libs are buggy (RH6 e.g.).
All authentication methods that are supported by the apache, are useable with backend = external.

**Comment by kobmaki** [comment]
With the patch from https://github.com/Icinga/icingaweb2/issues/3095 it is possible to run a simple icingaweb2 configuration without the requirement of an user or user group backend from an ldap. 

Here an example of roles from /etc/icingaweb2/roles.ini that everybody is allowed who is "authorized" from external:

```
[Guests]
users = "*"
permissions = "application/share/navigation,  module/businessprocess, module/cube, module/doc, module/globe, module/graphite, module/monitoring"
```

**Comment by lippserd** [comment]
This is good candidate for a blog post or our community discourse but not Web 2's documentation.
