### ISSUE TITLE
Can't modify dashlet

### ISSUE THREAD

**Issue by frayber** [Icinga/icingaweb2#3070]
Hello, when I try to delete the "Recently Recovered Services" from "Current Incidents" Dashboard , after clicking on Confirm I still see the dashlet in the list. Same thing if I try to modify dashlet url, nothing happens.
The strange thing is that this happens only in my language (italian), if I try in english it works.
I also checked /etc/icingaweb2/dashboards/admin/dashboard.ini and it seems modify is written:

 [Disservizi in Corso.Servizi Ripristinati Recentemente]
url = "monitoring/list/services?service_state=0&limit=10&sort=service_last_state_change&dir=desc"
title = "Servizi Ripristinati Recentemente"
disabled = "1"

I think it is something related to translation but I don't know what should I check.

Icingaweb2 2.4.2
Icinga 2.7.1
Centos 7.4.1708

**Comment by frayber** [comment]
Finally I found the problem: there was a space at the end of italian translation of "Recently Recovered Services":

"Servizi Ripristinati Recentemente "

and so the overrided values in the dashboard.ini file were not loaded.

please update the monitoring.po translation.

**Comment by frayber** [comment]
I've just upgraded to 2.6.2 and the problem is present again. I attach the correct .po translation, please update it.
[monitoring.zip](https://github.com/Icinga/icingaweb2/files/2754835/monitoring.zip)

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This will be fixed with #3542 

Best,
Eric
