### ISSUE TITLE
Nagvis integration "nagvis/map/filter"

### ISSUE THREAD

**Issue by ivzquez** [Icinga/icingaweb2#3071]
Hi all,

I'm trying to limit the view of each user on my platform, so they can see only their own objects on Nagvis. I'm using the Nagvis integrated module for icingaweb2.

But, im not able to use the "nagvis/map/filter" on Roles configuration. I tried multiple filters.

How does it work?

![index](https://user-images.githubusercontent.com/33484708/32547055-43a0fc36-c481-11e7-9c26-5b4c0a4b720e.png)

I have the only_permitted_objects directive enabled on nagvis.ini.php

Thanks

**Comment by lazyfrosch** [comment]
This issue should go be opened at [icingaweb2-module-nagvis](https://github.com/Icinga/icingaweb2-module-nagvis)

The base icingaweb2 has nothing todo with the nagvis module.
