### ISSUE TITLE
Comment deletion to wrong instance

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2#3076]
I still have a multi instance setup here.

When try to deleting a comment, the command is sent to the wrong instance (the first only)

Also it seems `DEL_HOST_COMMENT` is the wrong command here :wink: 

```
[1510215688] EXTERNAL COMMAND: DEL_HOST_COMMENT;401584
```

**Comment by lazyfrosch** [comment]
Running on pre 2.5.0 b7639651e80e85b81d9fb92c1db77e90c3754d2d

**Comment by lippserd** [comment]
Hi Markus,

Will you send a PR for this?

Cheers,
Eric

**Comment by lazyfrosch** [comment]
Yes, you can always expect that when I assign myself 😊

**Comment by lazyfrosch** [comment]
Ugh this looks like a bigger problems with instances, objects and commands.

Will try my best to send a PR next week

**Comment by lazyfrosch** [comment]
Pushed my work so far to `bugfix/command-instances-3076`

This still needs work regarding the controllers, so that the involved object is passed over.

And especially for the ListController comment/downtime, where we find a way to get the object relation.

(Objects are used in commands to get the instance to send to)

Alternative would be to directly add instance context to those commands, instead of object relation.

**Comment by lazyfrosch** [comment]
(Delay past 2.5)

**Comment by nilmerg** [comment]
Since command transports are instance aware and the external command feature is about to fade away I'll close this.
