### ISSUE TITLE
icinga2: Can't send external Icinga command: 401 Unauthorized. Please check your user credentials.

### ISSUE THREAD

**Issue by rodrigoselau** [Icinga/icingaweb2#3080]
Hi all,

I'm experiencing this problem when I try to update host status:

![capturar](https://user-images.githubusercontent.com/5107680/32608187-b0ee7298-c542-11e7-820b-944dca24a315.PNG)

**Comment by dnsmichi** [comment]
This has been asked here already: https://monitoring-portal.org/index.php?thread/42310-check-now-error-on-icinga-web/
