### ISSUE TITLE
Problem distinguishing between identically spelled service names with only case difference

### ISSUE THREAD

**Issue by cite** [Icinga/icingaweb2#3085]
Icinga Web 2 has problems distinguishing between `service` (lower case) and `SERVICE` (upper case - and if you ask "but why?", it's an ancient thing for distinguishing between active and passive services). In the current case it is not possible to display `euwax_adapter` on `fra1pro-be-feed-7`. Instead `EUWAX_ADAPTER` is shown. Interestingly, acknowledgements for `euwax_adapter` are also shown for `EUWAX_ADAPTER`.

Is this a bug, or is it something that's not supported and will force us to rename our services?

![icingaweb2_case_insensitive](https://user-images.githubusercontent.com/115994/32718693-27106e54-c85e-11e7-9f81-8fbbdbecadc0.png)

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Are you using PostgreSQL or MySQL? I did not verify all queries but the host and service detail areas should be case sensitive. Also the filter columns `host_name` and `service_description` are case sensitive in list views.

Which results do you get from the following URL: `monitoring/list/services?host_name=fra1pro-be-feed-7&service_description=euwax_adapter``

Best regards,
Eric

**Comment by cite** [comment]
I get both services as a result, `EUWAX_ADAPTER` and `euwax_adapter`. Database backend is a MySQL Galera 5.6 cluster.

**Comment by cite** [comment]
@lippserd I noticed this still has the "needs-feedback" label - anything else you need?

**Comment by cite** [comment]
Hi, are there any more data that we can provide?

**Comment by cite** [comment]
Is there anything else you need?

**Comment by lippserd** [comment]
No, thanks. Sorry for not removing the needs-feedback label. We'll analyse this issue further during the next week.

**Comment by lippserd** [comment]
@Al2Klimov Please have a look at this one.

**Comment by Al2Klimov** [comment]
Hello @cite and thank you for reporting!

I'm afraid
1. our filters are case insensitive by default
2. that is bad practice anyway (please consider renaming to "XY (active)" / "XY (passive)" at least for the sake of readability)

> Is there anything else you need?

Yes, your Icinga Web 2 version.
Please also test on the latest one and share the results.

Best,
AK

**Comment by cite** [comment]
`fcom-icingaweb2-2.5.0-0.el6.noarch` - I will let you know how testing this with the latest version worked out.
