### ISSUE TITLE
Contacts from Director are only visible for administrators

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2#3089]
Icinga 2 Contacts (Users), that are generated with Icinga Director are only visible for Icinga Web 2 users when they belong to the role "Administrators". Even if the other roles have "Allow everything (*)", the Icinga Web 2 users of the role are not allowed to see contacts from Icinga Director in the overview menu.

## Environment

* Icinga Web 2 version and modules (System - About): 2.4.2
* Version used (`icinga2 --version`): r2.7.2-1
* Operating System and version: CentOS 7.4

**Comment by lippserd** [comment]
Hi Markus,

Do you have any restrictions in place?

Cheers,
Eric

**Comment by mwaldmueller** [comment]
The only restriction in the additional roles is "_host_owner=XXX" at "monitoring/filter/objects".

**Comment by lippserd** [comment]
This might be related to #3088. Do you only have service contacts configured?

**Comment by mwaldmueller** [comment]
My example contact isn't assigned to any host or service.

Thanks for your investigation!

**Comment by nilmerg** [comment]
Is this then an issue at all? A restriction which causes a link to hosts being made/required does of course not include contacts which have no relation to hosts **and** services.

#3088 would only be related if these contacts are at least linked to services.

**Comment by nilmerg** [comment]
Hi Markus,

as commented above, this is working as intended. In order to see such a contact one must not be restricted to only see objects related to hosts/services.

Best,
Johannes

**Comment by mwaldmueller** [comment]
I have to reopen the issue. The problem still persists with Icinga Web 2.5.3.
