### ISSUE TITLE
Add theme with hostname displayed on top

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2#3093]
This is an enhancement and especially helpful when you have Icinga Web 2 installed on two cluster nodes. Until now I expand the themes like this with "/usr/share/icingaweb2/public/css/themes/hostname.less":

```
#header:after {
        content: 'i2-master01';
        color: white;
        padding-left: 33px;
}
```

Example screenshot:
![bildschirmfoto 2017-11-16 um 10 04 19](https://user-images.githubusercontent.com/3973350/32882838-e653c10e-cab5-11e7-8113-0b0de9ac4140.png)

## Environment

* Icinga Web 2 version and modules (System - About): 2.4.2
* Version used (`icinga2 --version`): 2.7.2
* Operating System and version: CentOS 7.4

**Comment by Thomas-Gelf** [comment]
Problem with this is that it wastes space on the right side, as there is now superfluous free space on top. But lucky you, our next layout is in the work these days and we'll separate the logo itself from header row constraints. So, this will allow to do what you're currently practicing with even more possibilities and less spacing constraints.

And it could then allow us to provide an optional/configurable "header-logo-info" section. I could imagine a configuration section like this:

```ini
[themes]
logo-info = "${fqdn}: ${ipaddress}\n${operatingsystem}\nPowered by @mwaldmueller" 
```

Probably with less details, the example should just show what could be accomplished.

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: eventually talk to @flourish86, he's currently working on the new theme. So, now is the perfect time to influence him with your ideas.

**Comment by mwaldmueller** [comment]
Already done! Thanks for your feedback

**Comment by dnsmichi** [comment]
I would do that in the browsers tab title, if not already there. Classic UI had such a patch.

**Comment by nilmerg** [comment]
If such a thing is desired one can still (as shown in the OP) accomplish this with a custom theme. Plenty of users do this already. (even in a more extensive manner)

**Comment by dnsmichi** [comment]
I've moved this into https://github.com/Icinga/icingaweb2-theme-company/issues/7 since I really like the idea :)
