### ISSUE TITLE
If a controller does not provide a suitable action, log a programming error

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2#3103]
## Expected Behavior

A developer should see that the used controller does not provide any suitable action when called.

## Current Behavior

The controller does not provide any action, since `IndexAction` is a programming error.

```
class EventsController extends Controller
{
    public function IndexAction()
    //public function indexAction()
```

`Page not found.` is hard to debug why the controller does not work.

Debug log doesn't show anything either.

## Possible Solution

- Throw an exception (and let show_stacktraces handle the rest)
- Log the error to the defined logger

## Steps to Reproduce (for bugs)

1. Create HostsAction.php and point to MODULE/events
2. Create application/views/scripts/events/index.phtml
3. Create application/controllers/EventsController.php

## Context

Creating my own HostsAction hooks for OSMC demo cases.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2dbf9d8fec994c9a9f76a5a25d6f6f301470b3c1

**Comment by nilmerg** [comment]
Sorry, but it's not worth the effort making this more obvious. Knowing that a controller needs actions is considered general knowledge.

**Comment by dnsmichi** [comment]
Bäh :-P Ok, I have this issue which tells me that I am stupid next time :)
