### ISSUE TITLE
new sidebar: disturbing scrollbars

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2#3132]
## Current Behavior
the new sidebar looks really great but at a sidebar with many items there will appear disturbing scrollbars. 

because of this scrollbar it's hard to reach the flyout-menu. there is a little gap which will close the flyout-menu before i can reach it.

![collapsible-sidebar-01](https://user-images.githubusercontent.com/25298055/33124650-06576f38-cf7e-11e7-9caa-7f44e7b22043.png)

i've discovered the same behavior when the sidebar is in a collapsed state.

![collapsible-sidebar-04](https://user-images.githubusercontent.com/25298055/33124659-09260eb8-cf7e-11e7-8acf-f2fff8e6e4ed.png)

any chance to hide these scrollbars permanently or is it possible to reduce the size for a better appearance?

## Context
in this case i've used 15 inch notebook which has a QHD display (2560x1440px). for a better readability i've rise the dpi scaling to 175%. 

## Your Environment

* Icinga Web 2 version and modules (System - About): 2a4fdd12d7a951108c59fa858933055c26f43bff
* Version used (`icinga2 --version`): `r2.8.0-1`
* Operating System and version: Windows 10 64bit
* Browser: Chromium 62.0.3202.94

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Do you have the scrollbars permanently or do they disappear shortly after you've scrolled? Are you using our snapshot packages or is this a git installation?

Best regards,
Eric

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Do you have the scrollbars permanently or do they disappear shortly after you've scrolled? Are you using our snapshot packages or is this a git installation?

Best regards,
Eric

**Comment by vita2** [comment]
hello erik,

thank you for your response. i am using the latest git master for testing purpose.

the scrollbar only appears if there are too many menu items at the navigation or when i reduce the window size of my web browser. if they are visible then they will permanently stay visible. 

### expected behavior if there is enough space for all menu items
![1-2](https://user-images.githubusercontent.com/25298055/33130729-916e44c8-cf94-11e7-8e06-c97ed58eac23.png)

### current behavior if there isn't enough space for all menu items
![3-4](https://user-images.githubusercontent.com/25298055/33130731-9207e344-cf94-11e7-8f5f-edc8c1f3d1a3.png)

**Comment by lippserd** [comment]
Thanks for response. Any chance to test the PR?

**Comment by vita2** [comment]
sure. i have just tested it :)

the scrollbar is gone now but there is still a little area between menu item and flyout-menu where the mouseover focus gets lost. it seems it is the same behavior like before, just with a invisible scrollbar.

![sidebar](https://user-images.githubusercontent.com/25298055/33133807-3c488f6c-cf9e-11e7-8c5d-61b2604f1400.png)

![sidebar-collapsed](https://user-images.githubusercontent.com/25298055/33133808-3c7dbf70-cf9e-11e7-9740-7dd4427d2faf.png)

**Comment by vita2** [comment]
it's fixed 👍 

thank you @lippserd
