### ISSUE TITLE
Flexible downtimes doesn't set downtime in effect.

### ISSUE THREAD

**Issue by ratchetnclank** [Icinga/icingaweb2#3140]
## Expected Behavior
Adding a flexible downtime should result as downtime being shown as in effect.

## Current Behavior
Flexible downtimes do not set in effect so don't show under default downtime filter.
Removing the filter shows all but i feel the value should be set.

![](https://i.imgur.com/rANenBM.png)

![](https://i.imgur.com/IJztpfO.png)

## Context
Ideally all downtimes should be shown within the downtimes section. Both flexible and not.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.4.2
* Version used (`icinga2 --version`): r2.8.0-1

**Comment by dnsmichi** [comment]
Flexible downtimes will only be in effect if the host/service changes to a NOT-OK state (or it is at the scheduling time). This sounds more like a backend problem, enable icinga2's debug log and analyse why the downtime is not triggered. Query the icinga2 api to also double check how the core sees it.
