### ISSUE TITLE
Sorry! Failed to set up Icinga Web 2 successfully.

### ISSUE THREAD

**Issue by meilaniagnesia** [Icinga/icingaweb2#3141]
Hello, I am facing this same issue

User Group Backend configuration has been successfully written to: /etc/icingaweb2/groups.ini
Unable to create user group "Administrators". An error occured:
ERROR: Zend_Db_Adapter_Exception in /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php:139 with message: SQLSTATE[28000] [1045] Access denied for user 'apache'@'localhost' (using password: YES)

Anyone could help fix this issue will be highly appreciated. Thank you.

**Comment by meilaniagnesia** [comment]
![screenshot_2017-11-24_13-31-11](https://user-images.githubusercontent.com/33949683/33198071-86f94eb0-d11b-11e7-910c-f9487d701f9e.png)

**Comment by Al2Klimov** [comment]
Hello @meilaniagnesia,

It seems you have configured a database user group backend, but you forgot some configuration on the database server side.
Please could you tell how you configured Icinga Web 2 – step by step.

Best,
AK

**Comment by meilaniagnesia** [comment]
I follow this URL moslty https://linoxide.com/monitoring-2/setup-icinga-web-2-centos7-ubuntu-15/

**Comment by Al2Klimov** [comment]
I'm afraid this info isn't enough:

"moslty" – I've no idea which details you didn't follow.

**Comment by meilaniagnesia** [comment]
I mean mostly, sorry typo.
Do you have any idea why this error happened?

**Comment by Al2Klimov** [comment]
I didn't complain about your typo (I actually didn't even notice it) – I just said that if you say that you followed that guide "mostly", then you did something different – and I have no idea how your setup differs from that guide if you don't tell me.

**Comment by Al2Klimov** [comment]
> Upon providing the credentials you might get the below message, but there is nothing to worry if your are unable to validate your database just choose the skip validation option and click on the next button.

– https://linoxide.com/monitoring-2/setup-icinga-web-2-centos7-ubuntu-15/

Hell no. If our setup wizard tells you that you specified invalid/non-accessible/whatever DB credentials, please fix them by actually creating the database and **not** by just skipping the validation.

**Comment by meilaniagnesia** [comment]
Oh, so what I have to fix now?

**Comment by Al2Klimov** [comment]
First of all please tell what you did not the way the guide described it.

**Comment by meilaniagnesia** [comment]
Yes, it works now. Thank you.

**Comment by Al2Klimov** [comment]
@meilaniagnesia

1. If this issue is not related to this ticket, please open another one.
2. If this is an Icinga 2 Core issue, please open the ticket in https://github.com/Icinga/icinga2.

**Comment by itspezialist** [comment]
As the Error message clearly says: Your Access denied to the file
/usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php

Which means you dont have permission to access the file.

Try to give the file full permission first
with: chmod 777 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php

Then reload the webpage in your browser.
After it tested ok you can adjust your permission 
chmod 777 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php
chmod 755 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php
