### ISSUE TITLE
ISSUE WHILE CONNECTING TO HOST ON ICINGAWEB2

### ISSUE THREAD

**Issue by meilaniagnesia** [Icinga/icingaweb2#3148]
Hello, I found another issue while connecting to Host on Icingaweb2
![screenshot_2017-11-27_11-34-29](https://user-images.githubusercontent.com/33949683/33251216-1adfed8e-d368-11e7-98d7-70417f36a854.png)

meilani@meilani-ops:~$ sudo icinga2 node wizard
Welcome to the Icinga 2 Setup Wizard!

We'll guide you through all required configuration details.

Please specify if this is a satellite setup ('n' installs a master setup) [Y/n]: y
Starting the Node setup routine...
Please specify the common name (CN) [meilani-ops]: meilani-ops
Please specify the master endpoint(s) this node should connect to:
Master Common Name (CN from your master setup): localhost.localdomain
Do you want to establish a connection to the master from this node? [Y/n]: y
Please fill out the master connection information:
Master endpoint host (Your master's IP address or FQDN): 192.168.56.10
Master endpoint port [5665]: 5665
Add more master endpoints? [y/N]: n
Please specify the master connection for CSR auto-signing (defaults to master endpoint host):
Host [192.168.56.10]: 
Port [5665]: 
warning/cli: Backup file '/etc/icinga2/pki/meilani-ops.key.orig' already exists. Skipping backup.
warning/cli: Backup file '/etc/icinga2/pki/meilani-ops.crt.orig' already exists. Skipping backup.
information/base: Writing private key to '/etc/icinga2/pki/meilani-ops.key'.
information/base: Writing X509 certificate to '/etc/icinga2/pki/meilani-ops.crt'.
information/cli: Fetching public certificate from master (192.168.56.10, 5665):

critical/TcpSocket: Invalid socket: No route to host
critical/pki: Cannot connect to host '192.168.56.10' on port '5665'
critical/cli: Peer did not present a valid certificate.

**Comment by lazyfrosch** [comment]
Hey @meilaniagnesia, sorry but this is the issue tracker for icingaweb2, and I only can see an issue with the Icinga 2 core, so https://github.com/icinga/icinga2 is the correct repository

Other than that, it looks like the node you want to setup, can't connect to the Icinga 2 master via network:

    critical/TcpSocket: Invalid socket: No route to host
    critical/pki: Cannot connect to host '192.168.56.10' on port '5665'

Check if Icinga 2 is running on the remote side, and configured with API enabled.

**Comment by meilaniagnesia** [comment]
@lazyfrosch yes, so I have to fix now? Please advise.

**Comment by lazyfrosch** [comment]
I suggest you checkout the community support channels: https://www.icinga.com/support/ (at the bottom)

Other than that start to read here: https://www.icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/

Icinga Web 2 is not part of the Icinga 2 cluster, it uses the IDO DB to display data, and the API of Icinga 2 to interact based on user request.

**Comment by dnsmichi** [comment]
Next time you're opening an issue please use normal letters. The topic reads like shouting.
