### ISSUE TITLE
Donuts in Tactical Overview not visible

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#3151]
![to-invisible-donuts](https://user-images.githubusercontent.com/16668527/33263769-49ae439c-d36b-11e7-93b9-01d0bf0e632e.jpg)

This is with 5aa83ea0d9f881badbb13b3770ba66ad97040c47

**Comment by nilmerg** [comment]
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/62.0.3202.94 Chrome/62.0.3202.94 Safari/537.36

**Comment by Thomas-Gelf** [comment]
@nilmerg: this is because of localized `%f` VS `%F` in `sprintf()`, @lippserd should already have fixed this, it just didn't make it into master yet.
