### ISSUE TITLE
Wrong default filter error/coloring

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2#3168]
## Expected Behavior
Should not happen

## Current Behavior
Default Filter shows error, color purple, should be red. Bubble tip reports error

![web2filter](https://user-images.githubusercontent.com/4162281/33324297-87cc5f30-d44f-11e7-918c-a5f03fe49d82.PNG)

![web2filter2](https://user-images.githubusercontent.com/4162281/33324609-6254ea96-d450-11e7-9bb8-e0b116811ea6.PNG)

## Possible Solution
fix color, remove bubble tip

## Steps to Reproduce (for bugs)
see screenshots

## Context
sidebar

## Your Environment
* Version used (`icinga2 --version`): 2.5.0

**Comment by lippserd** [comment]
Hi Simon,

This looks like the high-contrast theme. Purple here refers to UNKNOWN. Please show your restrictions since there seems to be something wrong w/ your filter.

Best regards,
Eric

**Comment by SimonHoenscheid** [comment]
Fixed. Thanks
