### ISSUE TITLE
The parameter showFullscreen opens a new window with sidebar

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2#3169]
hello,

while using the shiny new icingaweb2 i've discovered a small issue with the paramter `showFullscreen`.

some of my shared navigation elements should open in a new window with fullscreen mode. 

example: `monitoring/list/services?service_problem=1&service_state!=3&sort=service_severity&showFullscreen&showCompact`

## Expected Behavior
the parameter showFullscreen should open a new window without all the things like tabs, big logo, sidebar and so on.

## Current Behavior
the page will opened in a new window. the sidebar and tabs are invisible but few seconds later the sidebar and the icinga2 logo appears again.

## Your Environment

* Icinga Web 2 version and modules (System - About): ebe1917b152b786cc708abe5215fd0c4be7c4237
* Version used (`icinga2 --version`): `r2.7.2-1`
* Operating System and version: Windows 10 64bit
* Browser: Chromium 62.0.3202.75

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I can confirm this bug. We'll fix this one asap.

Cheers,
Eric
