### ISSUE TITLE
Basic auth with PHP-FPM not working

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2#3173]
## Expected Behavior
Basic Auth to the Web2 API should work.

## Current Behavior
Returns a 401 Error

## Possible Solution
Because Basic auth is not done to the webserver, but to the PHP backend itself, it will fail in Apache httpd if 

```
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
```

 is not set 

More Info:

https://devhacksandgoodies.wordpress.com/2014/06/27/apache-pass-authorization-header-to-phps-_serverhttp_authorization/

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.0
* Version used (`icinga2 --version`): 2.8.0
* Operating System and version: Centos 7 Latest

FYI: @lazyfrosch

**Comment by lippserd** [comment]
Hi Simon,

Thanks for the report. Could you please also open an issue at https://github.com/Icinga/icinga-packaging.

Cheers,
Eric

**Comment by dheule** [comment]
A simpler solution is to add the following to the apache config:

CGIPassAuth on

see https://httpd.apache.org/docs/2.4/en/mod/core.html#cgipassauth

**Comment by lazyfrosch** [comment]
@dheule Thanks for the pointer, but this will cause problems with older Apache 2.4 releases, like shipped in CentOS/RHEL 7:

```
[root@26caa4131c40 ~]# cat /etc/httpd/conf.d/test.conf
<Directory /var/www/html>
  CGIPassAuth on
</Directory>
[root@26caa4131c40 ~]# apachectl -t
AH00526: Syntax error on line 2 of /etc/httpd/conf.d/test.conf:
Invalid command 'CGIPassAuth', perhaps misspelled or defined by a module not included in the server configuration
```

Current solution will ensure the broadest support with FPM.

**Comment by mmahfoudi** [comment]
Hello,
I still have this error :(

**Comment by lippserd** [comment]
@mmahfoudi Please open a new issue and provide all the necessary details about your setup and how to reproduce the error.
