### ISSUE TITLE
Doc: Schema upgrade instructions for 2.5.0 missing

### ISSUE THREAD

**Issue by ggzengel** [Icinga/icingaweb2#3175]
There is nothing written about #2153 and c195790 :
/usr/share/icingaweb2/etc/schema/mysql-upgrades/2.5.0.sql

After upgrade my database looks like:

```
show columns from icingaweb_group_membership;
+----------+------------------+------+-----+---------+-----------------------------+
| Field    | Type             | Null | Key | Default | Extra                       |
+----------+------------------+------+-----+---------+-----------------------------+
| group_id | int(10) unsigned | NO   | PRI | NULL    |                             |
| username | varchar(64)      | NO   | PRI | NULL    |                             |
| ctime    | timestamp        | YES  |     | NULL    |                             |
| mtime    | timestamp        | YES  |     | NULL    | on update CURRENT_TIMESTAMP |
+----------+------------------+------+-----+---------+-----------------------------+
```

$ uname -a
> Linux lx-icinga.hq1.local 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

$ cat /etc/apt/sources.list.d/icinga.list 
> deb http://packages.icinga.org/debian icinga-stretch main

**Comment by dnsmichi** [comment]
What exactly do you mean? Did you apply the schema upgrade file as usual, or is this issue about something different?

**Comment by ggzengel** [comment]
In icingaweb2 it's not usual. It's the first schema update since beta and in release notes there is no note about this.
Icingaweb2 does not notice that there is a upgrade missing like icinga2.
