### ISSUE TITLE
Apache2 SSO -> Basic-auth fallback -> icingaweb2 very slow

### ISSUE THREAD

**Issue by schirrmie** [Icinga/icingaweb2#3182]
We use Apache2 Single Sign On with Kerberos Auth. This works fine from the intranet. For external (Internet) access we use Basic-Auth fallback. If we access icingaweb2 from the Internet, we get the standard browser basic auth dialog. We can successfully login but icingaweb2 is very slow. Pages needs over 10 seconds to load.

Here is the console output from internet access with firefox

```
GET https://icinga.domain.de/icingaweb2/dashboard [HTTP/1.1 200 OK 12496ms]
GET https://icinga.domain.de/icingaweb2/css/icinga.min.css [HTTP/1.1 200 OK 395ms]
GET https://icinga.domain.de/icingaweb2/js/icinga.min.js [HTTP/1.1 304 Not Modified 12444ms]
Icinga Web 2: setting initial layout to default-layout dashboard:304:11
GET https://icinga.domain.de/icingaweb2/img/icinga-logo.svg [HTTP/1.1 304 Not Modified 132ms]
GET https://icinga.domain.de/icingaweb2/img/icons/search_white.png [HTTP/1.1 304 Not Modified 271ms]
unreachable code after return statement [Weitere Informationen] icinga.min.js:118:186
11:45:25.986 Icinga is ready, running on jQuery 2.1.0 icinga.min.js:24:522
GET XHR https://icinga.domain.de/icingaweb2/monitoring/list/services [HTTP/1.1 200 OK 231ms]
GET XHR https://icinga.domain.de/icingaweb2/monitoring/list/hosts [HTTP/1.1 200 OK 12472ms]
GET XHR https://icinga.domain.de/icingaweb2/monitoring/tactical [HTTP/1.1 200 OK 12534ms]
unreachable code after return statement [Weitere Informationen] icinga.min.js:118:186
Source-Map-Fehler: request failed with status 401
Ressourcen-Adresse: https://icinga.domain.de/icingaweb2/js/icinga.min.js
Source-Map-Adresse: jquery.tipsy.min.map [Weitere Informationen]
11:45:26.692 No lastUpdate, setting one application-state icinga.min.js:24:522
GET XHR https://icinga.domain.de/icingaweb2/layout/menu [HTTP/1.1 200 OK 12215ms]
GET XHR https://icinga.domain.de/icingaweb2/application-state [HTTP/1.1 200 OK 12283ms]
12:57:27.443 Reloading CSS icinga.min.js:24:522
GET https://icinga.domain.de/icingaweb2/css/icinga.min.css [HTTP/1.1 200 OK 12250ms]
```

You see a lot of over 12000ms but with status 200 ok.
Only one 401 `Source-Map-Fehler: request failed with status 401` but I don't know if this is important?

## Expected Behavior
normal speed

## Your Environment
Debian - 8
Apache2 - 2.4.10-10
icingaweb2 - 2.5.0-1.jessie

/etc/apache2/conf-enabled/icingaweb2.conf
    AuthName "Icinga Access"
    AuthType Kerberos
    KrbMethodK5Passwd on
    KrbMethodNegotiate on
    KrbAuthoritative on
    #KrbServiceName Any
    KrbServiceName https/host.domain.de
    KrbAuthRealms DOMAIN.DE
    Krb5KeyTab /etc/apache2/auth_kerb.keytab
    KrbLocalUserMapping on
    KrbSaveCredentials on
    Require valid-user

/etc/icingaweb2/authentication.ini
[Icinga Access]
backend = "external"

[icingaweb2]
user_class = "user"
filter = "!(objectClass=computer)"
user_name_attribute = "sAMAccountName"
backend = "msldap"
base_dn = "DC=domain,DC=de"
resource = "icingaweb_ldap"

In authenticiation.ini we have the external backend and for the groups the msldap backend.

**Comment by Seb35** [comment]
I cannot answer regarding the core issue you experience (speed), but the issue with the 401 Source-Map-Fehler is probably not relevant.

You can check [this help page about source map errors](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors), which is a developer tool probably automatically opened by Firefox when you opened the console (hence not used in normal operations). I got myself a 404, but you 401 probably comes from your server config with authentication: [Firefox does not send the authentication when retrieving the *.map files](https://bugzilla.mozilla.org/show_bug.cgi?id=1426097). I guess my 404 is a minor Icinga web issue, although it seems to be fixed in #2505 (I have version 2.5.0).

**Comment by Seb35** [comment]
1. About the core issue, are you sure it is an issue with Icinga? => It could be related to your internet gateway/server (apache, nginx, etc).
2. Do you have have similar websites on the same server with a similar authentication? Is it speeder?
3. Do you still experience the issue some weeks later? => to assert it is not a temporary issue

I ask questions to document this issue, but I’m not myself an Icinga developer, only a user.

**Comment by lazyfrosch** [comment]
This sounds really like a problem with Apache with Kerberos Auth.

Probably the client tries to authenticate and couldn't. Icinga Web does nothing in terms of special or additional authentication handling.

* User is logged in as `REMOTE_USER` (defined by the webserver)
* Groups and Roles are resolved
* Within that session of icingaweb2 (until timeout or you click logout) this is not refreshed automatically...

I suggested testing without Kerberos, maybe another VHost for external access, the problem lays there for sure.

**Comment by schirrmie** [comment]
Hi,
Thank You for your answer and sorry for my delayed answer.
Between the holidays we had some time and analyse a little bit. We found out that we only open udp and not tcp port for kerberos. Now its seems normal so it was a firewall issue and nothing with icingaweb2.

I close the issue.

Regards
