### ISSUE TITLE
Custom menu item throws log message every load of the menu

### ISSUE THREAD

**Issue by 10bias** [Icinga/icingaweb2#3189]
## Expected Behavior
No log message is created for configured menu items.

## Current Behavior
A log message is created for every load of the menu:
```
2017-12-05T13:43:13+01:00 - DEBUG - Failed to find custom navigation item class MenuItem for item Kibana. Using base class NavigationItem now
```
Configuration looks like:
```
[Kibana]
users = "*"
type = "menu-item"
target = "_blank"
url = "http://kibana:5601/"
owner = "someuser"
icon = "chart-pie"
```

## Steps to Reproduce (for bugs)
1. Create a custom menu item
2. Enable logging at level DEBUG
3. Watch the log

## Context
Filesystem was full because of excessive logging.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.5.0 (test environment), 2.4.1 (production environment)
* Version used (`icinga2 --version`): 2.8.0 (test environment), 2.6.1 (production environment)
* Operating System and version: RHEL 7

**Comment by dnsmichi** [comment]
It is just a debug entry. If filesystem is running full, adjust the log level to errors only.
