### ISSUE TITLE
migrate module for domain-aware authentication missing in packages

### ISSUE THREAD

**Issue by mcktr** [Icinga/icingaweb2#3190]
## Expected Behavior

Coming from the documenation [Domain-aware Authentication](https://www.icinga.com/docs/icingaweb2/latest/doc/05-Authentication/#default-domain).

>**Caution!**
>
>Enabling domain-awareness or changing domains in existing setups requires migration of the usernames in the Icinga Web 2 configuration. Consult icingacli --help migrate config users for details.

The command `icingacli --help migrate config users` should work. 

## Current Behavior

```
root@<HOSTNAME>:~# icingacli --help migrate config users
ERROR: There is no such module or command: 'config'

USAGE: icingacli [module] <command> [action] [options]

Available commands:

  help            Help for modules, commands and actions
  module          List and handle modules
  web

Available modules:

  cube
  director
  fileshipper
  grafana
  map
  monitoring

Global options:

  --log [t]       Log to <t>, either stderr, file or syslog (default: stderr)
  --log-path <f>  Which file to log into in case of --log file
  --verbose       Be verbose
  --debug         Show debug output
  --help          Show help
  --benchmark     Show benchmark summary
  --watch [s]     Refresh output every <s> seconds (default: 5)

Show help on a specific command : icingacli help <command>
Show help on a specific module  : icingacli help <module>
```
The command seems to be non existent.

## Possible Solution

Correct the command in the documentation. I don't know if such a command even exist, I couldn't find a possible matching candidate.

## Steps to Reproduce (for bugs)

1. Try to run `# icingacli --help migrate config users `

## Context

I read through the documentation for Domain-aware Authentication and came across the command. Wanted to get details about the mentioned required usernames migration.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.0
* Version used (`icinga2 --version`): r2.8.0-1
* Operating System and version: Debian GNU/Linux 8.9

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We forgot to include the `migrate` module in our packages. Shame on us! You may copy it into your installation from https://github.com/Icinga/icingaweb2/tree/master/modules/migrate.

Best regards,
Eric

**Comment by mcktr** [comment]
Thanks for the workaround, worked.

**Comment by lippserd** [comment]
Moved to icinga/icinga-packaging#87
