### ISSUE TITLE
Custom Variables field not shown after upgrade

### ISSUE THREAD

**Issue by unix0r** [Icinga/icingaweb2#3193]
Hey guys, i have a setup with a lot of hosts and they all use custom variables.
In the previous version 2.4.2 there was a field in the host view for all custom variables.

After the upgrade to 2.5 the field is gone. The variables are still part of the host object.

Is there a way to get the view back?

Thats the new look:
![bildschirmfoto von 2017-12-06 09-15-17](https://user-images.githubusercontent.com/4679329/33651419-10de56cc-da66-11e7-9d06-0732891647be.png)

And this is the view with custom variables:
![bildschirmfoto von 2017-12-06 09-15-28](https://user-images.githubusercontent.com/4679329/33651461-2cebcad4-da66-11e7-8a2f-b6016909e70b.png)

**Comment by lippserd** [comment]
Hi,

You're showing two different hosts in your screenshots. I think you either did not define any custom variable on the host where you think the variables are missing or the IDO isn't/wasn't able to keep up. If this is still a problem for you, please open a new issue with the following information:

- Configuration of the Host
- Icinga 2 API query result of the Host
- Icinga 2 Logs
- Icinga Web 2 Screenshot of the Host

Best regards,
Eric

**Comment by mjambach** [comment]
I have the same - in services I still can see the custom variables but in host-view they are gone (for every host - and every host has custom variables)

**Comment by unix0r** [comment]
We have only hosts, created via the API. So i deleted all hosts and let our software create them again.
That was the solution for my problem. Maybe it helps you.

**Comment by mjambach** [comment]
It started to show up again after adding another custom variable...guess its something like an upgrade bug... thanks for the hint

**Comment by fedepires** [comment]
Same for us. We noticed custom vars were missing when we tried some filters, and also the  Host Map module would only show a few hosts (since some of them did show custom vars). Like @mjambach , we added a new custom var to all hosts, and restarted icinga2 master service and that fixed it. We then removed it, and restarted, and now all custom vars are still showing up fine.
