### ISSUE TITLE
php7.0 lamp?

### ISSUE THREAD

**Issue by sdxy36** [Icinga/icingaweb2#3195]
## Possible Solution

A few days ago I use php5.6 can make icingaweb2 work, try again today need to rely on php7.0, resulting icingaweb2 not work, I do not know much about php. I used yum (CentOS6 x64) throughout the process. (Forgive my English ^_^||| )

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Icinga Web 2 version and modules (System - About):
* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by lippserd** [comment]
Hi,

Sorry but nobody can help you with this poor issue description. Next time, please fill in the details of the issue template, provide how you've installed Icinga Web 2 and its dependencies and tell us the exact problem you're facing instead of just "it does not work".

Best regards,
Eric
