### ISSUE TITLE
Custom Variables field not shown after upgrade

### ISSUE THREAD

**Issue by unix0r** [Icinga/icingaweb2#3196]
Hey guys, the field for custom variables of a host is missing since the upgrade to icingaweb 2.5.

See:
![bildschirmfoto von 2017-12-06 09-15-17](https://user-images.githubusercontent.com/4679329/33667434-1f8da8c6-da9d-11e7-8527-d31376c58b48.png)

The host is configured via an API call and the API query results are:

>  curl -k -s -u api:pass 'https://localhost:5665/v1/objects/hosts/pls-freiburg_disp1-py'  | python -m json.tool
{
    "results": [
        {
            "attrs": {
                "__name": "pls-freiburg_disp1-py",
                "acknowledgement": 0.0,
                "acknowledgement_expiry": 0.0,
                "action_url": "",
                "active": true,
                "address": "192.168.5.131",
                "address6": "",
                "check_attempt": 1.0,
                "check_command": "hostalive",
                "check_interval": 60.0,
                "check_period": "",
                "check_timeout": null,
                "command_endpoint": "",
                "display_name": "disp1-py",
                "downtime_depth": 0.0,
                "enable_active_checks": true,
                "enable_event_handler": true,
                "enable_flapping": false,
                "enable_notifications": true,
                "enable_passive_checks": true,
                "enable_perfdata": true,
                "event_command": "",
                "flapping": false,
                "flapping_current": 0.0,
                "flapping_last_change": 0.0,
                "flapping_threshold": 0.0,
                "flapping_threshold_high": 30.0,
                "flapping_threshold_low": 25.0,
                "force_next_check": true,
                "force_next_notification": false,
                "groups": [
                    "Dispenser",
                    "linux-servers",
                    "pls-freiburg"
                ],
                "ha_mode": 0.0,
                "icon_image": "",
                "icon_image_alt": "",
                "last_check": -1.0,
                "last_check_result": null,
                "last_hard_state": 1.0,
                "last_hard_state_change": 1512485462.450984,
                "last_reachable": true,
                "last_state": 1.0,
                "last_state_change": 1512485462.450984,
                "last_state_down": 0.0,
                "last_state_type": 0.0,
                "last_state_unreachable": 0.0,
                "last_state_up": 0.0,
                "max_check_attempts": 3.0,
                "name": "pls-freiburg_disp1-py",
                "next_check": 1512571680.92293,
                "notes": "",
                "notes_url": "",
                "original_attributes": null,
                "package": "_api",
                "paused": false,
                "retry_interval": 30.0,
                "severity": 24.0,
                "source_location": {
                    "first_column": 0.0,
                    "first_line": 1.0,
                    "last_column": 34.0,
                    "last_line": 1.0,
                    "path": "/var/lib/icinga2/api/packages/_api/monitoring-1508225094-1/conf.d/hosts/pls-freiburg_disp1-py.conf"
                },
                "state": 1.0,
                "state_type": 0.0,
                "templates": [
                    "pls-freiburg_disp1-py",
                    "dispenser",
                    "generic-host"
                ],
                "type": "Host",
                "vars": {
                    "_capacityLinks": 0.0,
                    "_capacityRechts": 0.0,
                    "_count": "10",
                    "_key": "192.168.5.131/disp1-py",
                    "_kiosk": "Kiosk 1000",
                    "_lastSeen": "2017-08-24T17:11:56.211333+02:00",
                    "_name": "disp1-py",
                    "_type": "Disp",
                    "_zone": "pls-freiburg",
                    "os": "Linux"
                },
                "version": 1512485503.452792,
                "volatile": false,
                "zone": "pls-freiburg"
            },
            "joins": {},
            "meta": {},
            "name": "pls-freiburg_disp1-py",
            "type": "Host"
        }
    ]
}

The template for these hosts is:

> template Host "dispenser" {
    import "generic-host"
    vars._type = "Disp"
    vars._name = ""
    vars._capacityLinks = 0
    vars._capacityRechts = 0
    vars._count = 0
    vars._kiosk = ""
    vars.os = "Linux"
    address = ""
}

Thank you for your help.

**Comment by dnsmichi** [comment]
Tested it with a freshly added host. I'm not able to reproduce this.

```
object Host NodeName + "2" {
  import NodeName
}
```

![screen shot 2017-12-06 at 16 02 02](https://user-images.githubusercontent.com/382049/33668059-ea09315a-da9e-11e7-9cd1-5e69fb4df444.png)

**Comment by lippserd** [comment]
@dnsmichi Any chance that Icinga 2 is not inserting the custom variables when the Host is added via API? Maybe the missing bits are inserted once after the first check happened?

**Comment by dnsmichi** [comment]
```
$ curl -k -s -u root:icinga -H 'Accept: application/json' -X PUT 'https://localhost:5665/v1/objects/hosts/runtime01' -d '{ "attrs": { "check_command": "dummy", "vars.os": "macOS" } }'
{"results":[{"code":200.0,"status":"Object was created"}]}
```

![screen shot 2017-12-06 at 16 14 14](https://user-images.githubusercontent.com/382049/33668598-89a2789c-daa0-11e7-829d-9dc68ddc5fbe.png)

**Comment by lippserd** [comment]
Ok. Thanks for the quick update and thanks to @dnsmichi for the support.
