### ISSUE TITLE
icingaweb2.5 update requires strict dependencies for PHP extensions

### ISSUE THREAD

**Issue by basg** [Icinga/icingaweb2#3201]
Updating to `icingaweb2-2.5.0-1.el7.icinga.noarch` fails on resolving dependencies for PHP 7.1 extensions when these were already present, but installed from another repository. In our case the extensions were installed from the Remi repository.
 
Icingaweb2.5 package requires PHP extensions to be installed from SCL repository on Centos7 systems. We would like to be able to use PHP extensions provided by remi repository, which is more complete and up to date; SCL provides 7.1.8, where Remi provides 7.1.12. 

example yum output for a few of the required extensions: 
```
# yum update icingaweb2
[....]
--> Finished Dependency Resolution
Error: Package: icingaweb2-2.5.0-1.el7.icinga.noarch (icinga-stable-release)
           Requires: rh-php71-php-mysqlnd
Error: Package: php-Icinga-2.5.0-1.el7.icinga.noarch (icinga-stable-release)
           Requires: rh-php71-php-gd
```
`rpm -qa` to verify that PHP extensions are present:
```
# rpm -qa
php-mysqlnd-7.1.12-4.el7.remi.x86_64`
php-gd-7.1.12-4.el7.remi.x86_64
```

## Expected Behavior
Icingaweb2.5 resolves dependencies for already installed PHP extensions

## Current Behavior
Icingaweb2.5 fails because it expects PHP extensions from SCL repo

## Steps to Reproduce (for bugs)
1. Install PHP7.1 + extensions from remi repository
2.`yum update icingaweb2.5`

## Your Environment

* Icinga Web 2 version and modules (System - About): icingaweb2.4.2, updating to 2.5
* Operating System and version: Centos7

**Comment by dnsmichi** [comment]
Duplicates icinga/icinga-packaging#69
