### ISSUE TITLE
500 Internal Server Error after installing latest Grafana

### ISSUE THREAD

**Issue by ant0nwax** [Icinga/icingaweb2#3203]
Grafana was installed on the Icinga Server for Performance Monitoring last Friday
suddenly icinga was updated, just by the fact that i installed grafana in yum
Watching the installation, ive seen some php stuff got installed on the Icinga Server
I thought - Oh no - not again, it might cause trouble.

On Friday the trouble was not visible yet, and I was kind of happy.
there was just the INIParser error with the # is not used for comments anymore and it should be ;
One INI File was corrected and then the GUI was clean and working

Today There is 500 Internal Server Error instead of Login Page on /icingaweb2/index.php

root@monitoringsrv ~ # php --version
PHP 5.6.32 (cli) (built: Oct 29 2017 19:00:01)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

root@monitoringsrv ~ # tail -1 /var/log/httpd/monitoringsrv.access.log
172.17.3.12 - - [11/Dec/2017:11:58:29 +0100] "GET /icingaweb2/index.php HTTP/1.1" 500 662 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"

root@monitoringsrv ~ # tail -1 /var/log/httpd/monitoringsrv.error.log
[Mon Dec 11 11:45:08 2017] [warn] proxy: No protocol handler was valid for the URL /icingaweb2/inwdex.php. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.

All Proxy Modules are loaded

I already tried the last time when I had problems with PHP to switch on debug without success, I am not a PHP guru, not even a novice :) though I am very good with Linux/Unix

Could anyone help here? is it a bug? is it about PHP 7? stuff went on the server?

I also did a yum update -y and that froze at cleaning up some postgres package

If you need more information, please tell me which files you would like to see.

Thanks in advance, kind regards

**Comment by lippserd** [comment]
Hi,

Please have a look at the PHP-FPM error logs. You find them in the directory `/var/opt/rh/rh-php71/log/php-fpm/`.

Best regards,
Eric

**Comment by ant0nwax** [comment]
First of all thanks for the feedback:

1) icingaweb2 is running again, a colleague helped me, who understands php and httpd

we are using httpd 2.2, though we commented out the following lines in /etc/httpd/conf.d/icingaweb2.conf

# <IfVersion < 2.4>
#    # Forward PHP requests to FPM
#    <LocationMatch "^/icingaweb2/(.*\.php)$">
#        ProxyPassMatch "fcgi://127.0.0.1:9000/usr/share/icingaweb2/public/$1"
#    </LocationMatch>
# </IfVersion>

2) I started to go into your direction myself by starting the rh-php70-php-fpm service, it did not help anything, i did this before my colleague solved the issue by the solution in 1) 

everything inside the /var/opt/rh/rh-php70/log/php-fpm/error.log is here:

[11-Dec-2017 13:21:30] NOTICE: fpm is running, pid 18593
[11-Dec-2017 13:21:30] NOTICE: ready to handle connections
[11-Dec-2017 13:22:45] NOTICE: Terminating ...
[11-Dec-2017 13:22:45] NOTICE: exiting, bye-bye!
[11-Dec-2017 14:09:40] NOTICE: fpm is running, pid 25379
[11-Dec-2017 14:09:40] NOTICE: ready to handle connections
[11-Dec-2017 14:18:33] NOTICE: Terminating ...
[11-Dec-2017 14:18:33] NOTICE: exiting, bye-bye!
[11-Dec-2017 15:15:50] NOTICE: fpm is running, pid 13174
[11-Dec-2017 15:15:50] NOTICE: ready to handle connections
[11-Dec-2017 15:15:52] NOTICE: Terminating ...
[11-Dec-2017 15:15:52] NOTICE: exiting, bye-bye!
[11-Dec-2017 15:15:52] NOTICE: fpm is running, pid 13197
[11-Dec-2017 15:15:52] NOTICE: ready to handle connections
[11-Dec-2017 15:35:25] NOTICE: Terminating ...
[11-Dec-2017 15:35:25] NOTICE: exiting, bye-bye!



You may close the issue or comment as solved, if you would not like to investigate further. Thanks

PS: I will open another issue about LDAP bind does not work after 24 hours, maybe tomorrow, but most likely only next week. have a nice day

BR Adam

**Comment by lippserd** [comment]
Ok. Thanks for your response.
