### ISSUE TITLE
Navigation URLs doesnt open external urls inside single column.

### ISSUE THREAD

**Issue by jelayeb** [Icinga/icingaweb2#3205]
i used to have many external urls that open inside icingaweb2 and this doesnt work anymore after upgrading to latest version 2.5.0
if i change them to open a new window then they open fine, 

## Expected Behavior
External URLs should be open normally inside icingaweb2 columns same as before, when they are used as a Navigation URL

## Current Behavior
When click on shared navigation urls with external link inside, and configured to open in a single column then i get **Page not found.**  the same with if i change them to a **new column** or **current column** anything that open inside icingaweb2 provides page not found

## Steps to Reproduce (for bugs)
1. create a new external link that open in a single column
2. click on the link

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.0   Graphite 0.0.0.4 Businessprocess 2.0.0-beta1
* Version used (`icinga2 --version`): r2.8.0-1
* Operating System and version: Centos 7.4
* Enabled features (`icinga2 feature list`): api checker command graphite ido-mysql influxdb livestatus mainlog notification

**Comment by Al2Klimov** [comment]
Hello @jelayeb and thank you for your report!

Unfortunately I wasn't able to reproduce it: https://youtu.be/x7tsn8izplI

Have I done anything wrong?

Best,
AK

**Comment by jelayeb** [comment]
thanks for your fast response, yes i watched the video, but i dont know what is wrong with mine here. 
i have downgraded my icingaweb2 to the older version to be able to use my navigation urls and installed  the new one on a new master server for testing.  on this server icingaweb2 was completely removed and the new one installed, and works fine
but with the affected one it was updated from old to new by yum update. 

does this feature have any package dependencies??

**Comment by lippserd** [comment]
@jelayeb Could please share a URL which is not working?

**Comment by jelayeb** [comment]
they are all network internal links like dashborads in grafana
http://xgrafana.domian:3000/dashboard/db/icinga2-default?orgId=1&from=1513150878684&to=1513172478685&var-hostname=sfk2070

**Comment by lippserd** [comment]
Is it possible for you to recreate a non-working setup and check with your browser's developer tools whether Web 2 requests the correct URLs?

**Comment by jelayeb** [comment]
i found the cause of this problem, 
i checked the enabled modules of icingaweb2 and i found this module was enabled. 
iframe -> /usr/share/icingaweb2/modules/iframe
which is not on the fresh installation, so i removed the link and it worked. 

Thanks
