### ISSUE TITLE
Ldap authentication not working without default_domain in config.ini

### ISSUE THREAD

**Issue by Zanop** [Icinga/icingaweb2#3210]
Ldap authentication is not working without **_default_domain_** in config.ini. Icingaweb will not even try to contact the ldap server, tcpdump does not show any communication. Logs with 'debug' do not show anything too.
## Expected Behavior
Ldap authentication should work without this option.
According to the documentation at https://github.com/Icinga/icingaweb2/blob/master/doc/05-Authentication.md default_domain opton is:
```
For the sake of simplicity a default domain can be configured (in config.ini).
```
which implies its not needed and is only optional, unless you have multiple domains.

## Current Behavior
Ldap auth not working at all without default_domain option
## Possible Solution
always put 
```
[authentication]
default_domain = "icinga.com"
```
in config.ini
## Steps to Reproduce (for bugs)

1. Install icinga2 + icingaweb2 in ubuntu 16.04.1
2. configure ldap authentication in authentication.ini, groups.ini, roles.ini
3. try to login with ldap posixUser 

## Context
Cannot authenticate users with ldap at all.
## Your Environment

* Icinga Web 2 version and modules (System - About): icingaweb2                           2.5.0-1.xenial
* Version used (`icinga2 --version`): r2.8.0-1
* Operating System and version: 16.04.1 LTS (Xenial Xerus)
* Enabled features (`icinga2 feature list`): 
```
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql mainlog notification 
```
* Config validation (`icinga2 daemon -C`): 
```
information/cli: Icinga application loader (version: r2.8.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: xxxxxxxxxxxxx.local.lan
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 13 Notifications.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 209 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1 Host.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 12 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by lippserd** [comment]
Hi,

Did you configure a domain in the user or group backends? Please show the INI configuration files `config.ini`, `authentication.ini` and `groups.ini`.

Best regards,
Eric

**Comment by Zanop** [comment]
Yes, there is domain configured in authentication.ini

**Comment by lippserd** [comment]
Do you want to use domain aware authentication? If not, you have to remove the domain setting from the config.

**Comment by Zanop** [comment]
authentication.ini
```
[icingaweb2]
backend = "db"
resource = "icingaweb_db"
[ldap_auth]
backend = "ldap"
user_class = inetOrgPerson
user_name_attribute = "uid"
base_dn = "dc=domain,dc=info"
domain = "domain.info"
resource = "icingaweb_ldap"
;filter = "memberOf=cn=sysadmin,ou=group,dc=domain,dc=info"
filter = "(objectClass=posixAccount)"
```

groups.ini
```
[icingaweb2]
backend = "db"
resource = "icingaweb_db"

[ldap-groups]
backend = "ldap"
resource = "icingaweb_ldap"
base_dn = "ou=group,dc=domain,dc=info"
group_class = "posixGroup"
group_name_attribute = "cn"
user_backend = "ldap_auth"
group_member_attribute = "memberUid"
```

config.ini
```
[global]
show_stacktraces = "1"
config_backend = "db"
config_resource = "icingaweb_db"

[logging]
log = "file"
level = "debug"
file = "/var/log/icingaweb2.log"

[authentication]
default_domain = "domain.info"
```

**Comment by Zanop** [comment]
I don't need the domain but it got in the config either by the initial wizard install or when I was editing the web interface.

**Comment by lippserd** [comment]
Just remove the settings from config.ini, authentication.ini and groups.ini and everything should work as expected.

**Comment by Farfaday** [comment]
I confirm that by migrating from 2.4.2 to 2.5.0, LDAP auth was not working anymore.

I had to add **domain = "stuff.com"** to authentication.ini and a new section:
**[authentication]
default_domain = "stuff.com"**
to config.ini, in order to be able to log-on again.

**Comment by lippserd** [comment]
@Farfaday If you do not want to use domain-aware authentication, just remove all domain related settings.

**Comment by Farfaday** [comment]
Yes, I am not needing that feature, and had nothing about domain settings before.
But I had to add these settings to make the LDAP auth work again... so in my eyes, this is a bug.

**Comment by lippserd** [comment]
Ok. It would be nice if you could help here then. Please remove the settings and retry your LDAP auth. If it does not work, please post the related logs.

**Comment by Zanop** [comment]
Just tested it, and it works with domains settings removed from config.ini and authentication.ini.
I think the real bug is that the domain setting gets added automatically somewhere in the setup process even if its not needed.

**Comment by Farfaday** [comment]
Took back the two previous entries. And now it works.
Rollbacked config and icingaweb_db Database. Still works.
I have no idea how it could now work and was not working before... Anyway, thanks for your help! Don't hesitate to ask me it I can test more stuffs
