### ISSUE TITLE
Documentation module: Large image generates memory error

### ISSUE THREAD

**Issue by Hipska** [Icinga/icingaweb2#3223]
When a module documentation is viewed with the doc module, and this documentation points to a large image, then php throws this memory allocation error:
> **Fatal error**: Allowed memory size of xxx bytes exhausted (tried to allocate xxx bytes) in **/usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php** on line **582**

I noticed that a image was not loading, so i tried to access it directly using `{baseURL}/doc/module/{moduleName}/image/{image}`, which gave the previous error.

## Expected Behavior
Do not load image contents in memory .

## Current Behavior
Somewhere, the image seems to be loaded in memory before being sent to the browser.

## Context
I know I could raise the PHP memory limit, but the image should not be put into PHP's memory in the first place, and secondly, I assume that current limit has a good value.

## Your Environment
PHP memory limit is 128MiB and image size is 40MiB+.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Please provide the full stacktrace of the exception.

Best regards,
Eric

**Comment by Hipska** [comment]
Sadly, the already provided text is all that came out of PHP.

**Comment by lippserd** [comment]
@nilmerg Please have a look at this one. I think it's sufficient to add `ob_end_clean()` before the `readfile()` call in `\Icinga\Module\Doc\Controllers\ModuleController::imageAction()`.

**Comment by Hipska** [comment]
Great, thanks!
