### ISSUE TITLE
Tactical Overview inner donut labels missing in Firefox

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2#3226]
## Expected Behavior
The tactical overview should display the critical services inside the circle.

## Current Behavior
In Firefox 54.0.1 and some other releases (newer/older) the "services critical" with the number is missing (the inside of the circle is just empty). Reloading using F5 key restores it.
In Chrome it is shown correctly.

![screenshot_20171219_165915](https://user-images.githubusercontent.com/124109/34166630-aa8c3f7c-e4df-11e7-83a7-1717c58ca13b.png)

Sidenote: the tactical overview is great but the page looks a bit empty/misplaced imho :)

## Steps to Reproduce (for bugs)
1. Click on Overview
2. Click on Tactical Overview
3. => services critical missing
4. Refresh (F5)
5. => services critical shown

## Context
Looks empty/misplaced

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.5.0
* Version used (`icinga2 --version`): r2.8.0-1
* Operating System and version: Red Hat 7.4
* Enabled features (`icinga2 feature list`): api checker command ido-mysql influxdb mainlog notification

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I can confirm this bug.

Best regards,
Eric

**Comment by lippserd** [comment]
@Al2Klimov Please have a look at this one. I think the problem is that the div of the label is inside the svg tag. It should be after it.

**Comment by lippserd** [comment]
And while you're at it. Could you please always show the labels even if there's no host down or service critical?

![zero](https://user-images.githubusercontent.com/1894563/34997391-b2fa2d96-fadc-11e7-9502-7aef17bbf583.jpg)
