### ISSUE TITLE
Fix installation doc on Ubuntu

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#3231]
## Current Behavior

> On RedHat / CentOS 6 you also need to install `mod_proxy_fcgi` for httpd

– https://github.com/Icinga/icingaweb2/blob/master/doc/02-Installation.md

## Expected Behavior

No, also on at least Ubuntu 16.04.

**Comment by Al2Klimov** [comment]
OK, you don't need (you can't) install it, but you have to enable it.

**Comment by lippserd** [comment]
@Al2Klimov Please document the missing bits.
