### ISSUE TITLE
Missing "Validate Configuration" button

### ISSUE THREAD

**Issue by kirjastojk** [Icinga/icingaweb2#3233]
## Expected Behavior

Configuration -> Application -> Authentication has "Validate Configuration" button for both the "User Backends" and "User Group Backends".

## Current Behavior

Only backends listed under "User Backends" have the "Validate Configuration" button. User Group Backends should have it too.

## Steps to Reproduce (for bugs)
1. Go to the page /config/userbackend

**Comment by lippserd** [comment]
Hi,

Thanks for the report.

@nilmerg Could you please have a look here?

Best regards,
Eric
