### ISSUE TITLE
Icinga user should be allowed to read /etc/icingaweb2

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2#3235]
Some checks in the ITL run `icingacli` which fails in default setups because Icinga 2 is not allowed to read `/etc/icingaweb2`.

What should be discussed is how to change permissions for that. We could simply add the `icinga` user (or its equivalent) to the `icingaweb2` group, but what about hosts only running Icinga Web 2 without Icinga 2 installation. While this is rather unlikely to happen we should cover odd setups as well.

**Comment by thammw** [comment]
Had this problem with the businessprocesses-check. SELinux was also a problem on this part.

**Comment by dnsmichi** [comment]
Adding the icinga user to a different application group is dangerous and shouldn't be done by default. SELinux will deny such too if the policy is not adjusted. @dgoetz your thoughts on the matter?

**Comment by dgoetz** [comment]
For SELinux: I would not enable this by default, but I can add another boolean to policy to allow this. This can be a little bit tricky to build because of dependency created in this way. Please assign me and I will look into it with the other SELinux issues

For DAC permissions: I would only add this to documentation as there is no dependency between Icinga 2 and Icinga Web 2 packages for now and because of this there is no reliable way to add group membership in post scripts except from trying in both packages if the other already is installed.

**Comment by lazyfrosch** [comment]
A user can easily add this on their own, we should not add it as default...

**Comment by dnsmichi** [comment]
I wanted to write docs for the `businessprocess` CLI command a while ago, still an open task in icinga/icingaweb2-module-businessprocess#120 - I've only implemented this inside the Vagrant boxes for now.

**Comment by dgoetz** [comment]
While thinking about I found another possible solution for SELinux. I have to create a new nagios-plugins context for the icingacli and let the icinga 2 domain transition to it when executing the plugin. I think this will be the easiest solution.

**Comment by dgoetz** [comment]
As my suggested solution is not wanted, please reassign the issue to someone else to find a proper solution.

**Comment by widhalmt** [comment]
Why shouldn't it be wanted, @dgoetz

**Comment by nilmerg** [comment]
Since this is [documented](https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#icingacli) now (and that's the final verdict in #3369) I'll close this.

**Comment by widhalmt** [comment]
@nilmerg did the documentation about SELinux get lost in an update? I only see a reference to `usermod` which is by far not enough by default setup RHEL/CenOS boxes.

**Comment by nilmerg** [comment]
SELinux wasn't covered that time. That's the "easy solution" which is documented there. If you now wish to see more detailed info about this please create a follow-up issue over at icinga2.
