### ISSUE TITLE
icingaweb2-selinux-2.5.0-1.el7.icinga does not set all proper selinux contexts

### ISSUE THREAD

**Issue by ethantq** [Icinga/icingaweb2#3236]
Issue:

After installing icinga2-selinux and icingaweb2-selinux the setup would not connect to LDAP for authentication. Was just getting a general error of "Can't contact LDAP server" After disabling SELinux and rebooting then it all worked fine. I added the rule below after re-enabling SELinux and I could then validate the LDAP settings.

setsebool -P httpd_can_connect_ldap 1

## Expected Behavior
LDAP validates and setup continues.

## Current Behavior
LDAP won't validate.

## Possible Solution
Check for failed SELinux using a command like ausearch -m avc -ts recent
implement required failures in the SELinux packages

This allowed LDAP to validate: setsebool -P httpd_can_connect_ldap 1

## Steps to Reproduce (for bugs)
1. Install Centos 7.4 with SELinux
2. Install the requisite packages for icinga2 and icingaweb2 from icinga centos repos
3. Try to walk through icingaweb2 setup
4. It will fail at LDAP authentication validation
5. Run "setsebool -P httpd_can_connect_ldap 1" and LDAP will validate

## Context
I am just trying to install and use this program. Nagios is a pain to set up, but this I can't even get installed and working properly. I now can't even log into the web interface with my ldap username and password. SELinux has even been disabled.

## Your Environment
* Icinga Web 2 version and modules (System - About):

Don't know except from package info in subject. I can't log in at all.

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.11.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Operating System and version:
CentOS Linux release 7.4.1708 (Core)

* Enabled features (`icinga2 feature list`):
Disabled features: api command compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: checker ido-mysql mainlog notification

* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.8.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 12 Notifications.
information/ConfigItem: Instantiated 209 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1 Host.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 11 Services.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by lippserd** [comment]
Hi,

Thanks for the report.

@dgoetz Could you please have a look at this one?

Cheers,
Eric

**Comment by dgoetz** [comment]
This is correct behavior from SELinux perspective by not allowing things not required by default. What we could do is enhance documentation telling people about the boolean to toogle or the setup module looking for selinux being enabled and if it is toggle the boolean.

**Comment by lippserd** [comment]
@dgoetz Thanks for the quick feedback. Adding this to our docs sounds like a good solution.

@nilmerg Please add this to our selinux doc.
