### ISSUE TITLE
Vagrantfile references non-existing box

### ISSUE THREAD

**Issue by mhutter** [Icinga/icingaweb2#3240]
## Expected Behavior
`vagrant up` successfully starts the vagrant box

## Current Behavior
```
The box 'boxcutter/centos7' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/boxcutter/centos7"]
Error: The requested URL returned error: 404 Not Found
```

## Possible Solution
- make sure the boxcutter boxes are available
- use different box (ie `centos/7`)

## Steps to Reproduce (for bugs)
1. `vagrant up`

## Context
I try to test a fix i wrote :)

## Your Environment
- Icingaweb2 current HEAD
- Vagrant 1.9.5 with VirtualBox 5.1.30 r118389

**Comment by dnsmichi** [comment]
Oh, thought I had fixed this already. That's true, boxcutter removed their boxes from atlas for some reason. We'll have to stick with bento for the time being I guess.
