### ISSUE TITLE
showFullscreen is no longer working

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2#3243]
## Expected Behavior
Icinga Web should only display content when adding `?showFullscreen` to the URL.

## Current Behavior
This seems to be completely ignored with the new 2.5 menu layout.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.5.0

**Comment by lazyfrosch** [comment]
![bildschirmfoto von 2018-01-04 09-01-15](https://user-images.githubusercontent.com/121874/34554671-5d3845c6-f12e-11e7-92f2-8deced02bdca.png)
![bildschirmfoto von 2018-01-04 09-00-02](https://user-images.githubusercontent.com/121874/34554672-5d516ace-f12e-11e7-92bf-48874a8692a8.png)

**Comment by nbuchwitz** [comment]
Looks like it was fixed in #3174

**Comment by lazyfrosch** [comment]
@nbuchwitz thanks, didn't see it looking for an issue

duplicates #3174
