### ISSUE TITLE
icingaweb2 on RHEL depends on PHP from Software Collections

### ISSUE THREAD

**Issue by bcogel** [Icinga/icingaweb2#3246]
Update of icingaweb2 from 2.4.2 to 2.5.0 has fixed dependencies to PHP from Red Hat Software Collections for RHEL 6. Update with PHP 7.x from IUS breaks because of this. 

To be independent from Red Hat support policies for web applications we're using several packages from IUS Community Repo on our systems. This includes various versions of PHP. Since director required some time ago a recent version of PHP, we already have PHP 7.1 from IUS repo installed.

## Expected Behavior

Because  we already have PHP 7.1 from IUS repo installed, an update of icingaweb2 should be possible without an error. And the admin responsible for the system should be able to decide which repo he would like to use.

## Current Behavior

Update of icingaweb2 causes errors because of fixed dependencies to PHP 7.0 from Red Hat Software Collections.

LANG=C yum update
Loaded plugins: enabled_repos_upload, package_upload, product-id, refresh-packagekit, replace, search-disabled-repos, security, subscription-manager
Setting up Update Process

...

Resolving Dependencies
--> Running transaction check
---> Package icingacli.noarch 0:2.4.2-1.el6.icinga will be updated
---> Package icingacli.noarch 0:2.5.0-2.el6.icinga will be an update
--> Processing Dependency: rh-php70-php-cli >= 5.6.0 for package: icingacli-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: /opt/rh/rh-php70/root/usr/bin/php for package: icingacli-2.5.0-2.el6.icinga.noarch
---> Package icingaweb2.noarch 0:2.4.2-1.el6.icinga will be updated
---> Package icingaweb2.noarch 0:2.5.0-2.el6.icinga will be an update
--> Processing Dependency: rh-php70-php-common >= 5.6.0 for package: icingaweb2-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: rh-php70-php-fpm >= 5.6.0 for package: icingaweb2-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: rh-php70-php-pgsql for package: icingaweb2-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: rh-php70-php-mysqlnd for package: icingaweb2-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: rh-php70-php-ldap for package: icingaweb2-2.5.0-2.el6.icinga.noarch
---> Package icingaweb2-common.noarch 0:2.4.2-1.el6.icinga will be updated
---> Package icingaweb2-common.noarch 0:2.5.0-2.el6.icinga will be an update
---> Package icingaweb2-vendor-HTMLPurifier.noarch 1:2.4.2-1.el6.icinga will be updated
---> Package icingaweb2-vendor-HTMLPurifier.noarch 1:2.5.0-2.el6.icinga will be an update
--> Processing Dependency: rh-php70-php-common >= 5.6.0 for package: 1:icingaweb2-vendor-HTMLPurifier-2.5.0-2.el6.icinga.noarch
---> Package icingaweb2-vendor-JShrink.noarch 0:2.4.2-1.el6.icinga will be updated
---> Package icingaweb2-vendor-JShrink.noarch 0:2.5.0-2.el6.icinga will be an update
--> Processing Dependency: rh-php70-php-common >= 5.6.0 for package: icingaweb2-vendor-JShrink-2.5.0-2.el6.icinga.noarch
---> Package icingaweb2-vendor-Parsedown.noarch 0:2.4.2-1.el6.icinga will be updated
---> Package icingaweb2-vendor-Parsedown.noarch 0:2.5.0-2.el6.icinga will be an update
--> Processing Dependency: rh-php70-php-common >= 5.6.0 for package: icingaweb2-vendor-Parsedown-2.5.0-2.el6.icinga.noarch
---> Package icingaweb2-vendor-dompdf.noarch 0:2.4.2-1.el6.icinga will be updated
---> Package icingaweb2-vendor-dompdf.noarch 0:2.5.0-2.el6.icinga will be an update
--> Processing Dependency: rh-php70-php-common >= 5.6.0 for package: icingaweb2-vendor-dompdf-2.5.0-2.el6.icinga.noarch
---> Package icingaweb2-vendor-lessphp.noarch 0:2.4.2-1.el6.icinga will be updated
---> Package icingaweb2-vendor-lessphp.noarch 0:2.5.0-2.el6.icinga will be an update
--> Processing Dependency: rh-php70-php-common >= 5.6.0 for package: icingaweb2-vendor-lessphp-2.5.0-2.el6.icinga.noarch
---> Package icingaweb2-vendor-zf1.noarch 0:2.4.2-1.el6.icinga will be updated
---> Package icingaweb2-vendor-zf1.noarch 0:2.5.0-2.el6.icinga will be an update
--> Processing Dependency: rh-php70-php-common >= 5.6.0 for package: icingaweb2-vendor-zf1-2.5.0-2.el6.icinga.noarch
---> Package php-Icinga.noarch 0:2.4.2-1.el6.icinga will be updated
---> Package php-Icinga.noarch 0:2.5.0-2.el6.icinga will be an update
--> Processing Dependency: rh-php70-php-common >= 5.6.0 for package: php-Icinga-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: rh-php70-php-xml for package: php-Icinga-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: rh-php70-php-pdo for package: php-Icinga-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: rh-php70-php-mbstring for package: php-Icinga-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: rh-php70-php-gd for package: php-Icinga-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: rh-php70-php-intl for package: php-Icinga-2.5.0-2.el6.icinga.noarch
--> Processing Dependency: /opt/rh/rh-php70/root/usr/bin/php for package: icingacli-2.5.0-2.el6.icinga.noarch
--> Finished Dependency Resolution
Error: Package: php-Icinga-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-common >= 5.6.0
Error: Package: icingaweb2-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-mysqlnd
Error: Package: icingaweb2-vendor-Parsedown-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-common >= 5.6.0
Error: Package: icingaweb2-vendor-zf1-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-common >= 5.6.0
Error: Package: icingaweb2-vendor-dompdf-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-common >= 5.6.0
Error: Package: php-Icinga-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-xml
Error: Package: icingacli-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: /opt/rh/rh-php70/root/usr/bin/php
Error: Package: icingaweb2-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-common >= 5.6.0
Error: Package: icingaweb2-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-ldap
Error: Package: icingaweb2-vendor-JShrink-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-common >= 5.6.0
Error: Package: icingacli-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-cli >= 5.6.0
Error: Package: icingaweb2-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-fpm >= 5.6.0
Error: Package: php-Icinga-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-gd
Error: Package: php-Icinga-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-pdo
Error: Package: php-Icinga-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-intl
Error: Package: php-Icinga-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-mbstring
Error: Package: icingaweb2-vendor-lessphp-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-common >= 5.6.0
Error: Package: 1:icingaweb2-vendor-HTMLPurifier-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-common >= 5.6.0
Error: Package: icingaweb2-2.5.0-2.el6.icinga.noarch (RRZK_ICINGA-6_ICINGA-6)
           Requires: rh-php70-php-pgsql

...

## Possible Solution

Define clean requirements like: Requires: php >= 5.6
This should work independent of the used repo or software channel.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Icinga Web 2 version and modules (System - About): 
icingaweb2 2.5.0
* Version used (`icinga2 --version`):
* Operating System and version:
RHEL 6.9
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by nbuchwitz** [comment]
Looks like related / duplicate to #3201 and https://github.com/Icinga/icinga-packaging/issues/69

**Comment by dnsmichi** [comment]
Right, all the details are discussed in Icinga/icinga-packaging#69

Cheers,
Michael

**Comment by bcogel** [comment]
This breaks our setup! I have to switch also to http24 from software collection to use this php modules. Great... This is bull.... Sorry... but this has far to much impact on existing systems for a simple software update!

**Comment by dnsmichi** [comment]
As said, please proceed in the linked issue. No need to change your tone, please watch your language.

Regards,
Michael
