### ISSUE TITLE
Wrong time in "Reschedule Host Check"

### ISSUE THREAD

**Issue by tmueller2017** [Icinga/icingaweb2#3248]
## Expected Behavior
*Check Time* in *Reschedule Host Check* should have the current local time as default value.

## Current Behavior
The value is the current time +1 hour.  
This behaviour is different when scheduling a service downtime. The standard value there is the current time.

## Steps to Reproduce (for bugs)

1. Set timezone on server to 'Europe/Berlin'
2. Set date.timezone in php.ini to 'Europe/Berlin'
3. Install icingaweb2
4. Reschedule Host Check via Browser

## Context
I want to reschedule a hostcheck and have it done immediately. Right now I have to set the vaule manually to my localtime.

## Your Environment

* Icinga Web 2 version and modules (System - About):

        Icinga Web 2 Version
            2.5.0
        Git commit
            ebe1917b152b786cc708abe5215fd0c4be7c4237
        Git commit date
            2017-11-27
        Copyright
            © 2013-2018 The Icinga Project 
        Loaded modules
          - grafana
          - monitoring

* Version used (`icinga2 --version`):

        icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)

* Operating System and version:

        System information:
          Platform: CentOS Linux
          Platform version: 7 (Core)
          Kernel: Linux
          Kernel version: 3.10.0-693.2.2.el7.x86_64
          Architecture: x86_64

* Enabled features (`icinga2 feature list`):

        Disabled features: compatlog debuglog elasticsearch gelf graphite livestatus opentsdb statusdata
        Enabled features: api checker command ido-mysql influxdb mainlog notification perfdata syslog

* php.ini

        [root@icinga2 ~]# grep date.timezone /etc/opt/rh/rh-php71/php.ini
        date.timezone = "Europe/Berlin"

* timedatectl

        [root@icinga2 ~]# timedatectl
              Local time: Fr 2018-01-05 13:09:24 CET
          Universal time: Fr 2018-01-05 12:09:24 UTC
                RTC time: Fr 2018-01-05 12:09:24
               Time zone: Europe/Berlin (CET, +0100)
             NTP enabled: yes
        NTP synchronized: yes
         RTC in local TZ: no
              DST active: no
         Last DST change: DST ended at
                          So 2017-10-29 02:59:59 CEST
                          So 2017-10-29 02:00:00 CET
         Next DST change: DST begins (the clock jumps one hour forward) at
                          So 2018-03-25 01:59:59 CET
                          So 2018-03-25 03:00:00 CEST

**Comment by lippserd** [comment]
Hi,

Thanks for the report. If you want to reschedule an immediate check, please us the Check Now action. The default for scheduling downtimes assumes that you want to schedule a downtime now. The default for rescheduling a check is that you want to schedule the check in the future. I see no reason why we should change this. But I'm open for feedback.

Best regards,
Eric
