### ISSUE TITLE
non domain ldap group backend includes user from domain in domain aware auth

### ISSUE THREAD

**Issue by spaolo** [Icinga/icingaweb2#3250]
In domain aware authentication groups without domain keyword restult including users in authentication backend with domain keyword specifide if backends have colliding users.

## Expected Behavior
An ldap group backend not belonging to a domain sould include only users not belonging to any domain.
## Current Behavior
An ldap group backend not belonging to a domain includes users belonging to domain.

## Possible Solution
Add a reverse check against $users->hasDomain existece at line https://github.com/spaolo/icingaweb2/blob/7e5f5405aadc17d48b77602a3f5686c1a5e5b65a/library/Icinga/Authentication/UserGroup/LdapUserGroupBackend.php#L692

Adding the domain aware feature to mysql backend could help to hide the problem 

## Steps to Reproduce (for bugs)

1. set up two different users and group backend 
```
in /etc/icingaweb2/authentication.ini
[nondomain_user]
backend = "ldap"
resource = "nondomain_ldap"
base_dn = "ou=users,dc=nondomain"

[domain_users]
backend = "ldap"
resource = "domain_ldap"
base_dn = "ou=people,dc=domain"
domain = "domain"

in /etc/icingaweb2/groups.ini

[nondomain_group]
backend = "ldap"
resource = "nonuser_ldap"
base_dn = "ou=groups,dc=nondomain"

[nonuser_group]
backend = "ldap"
base_dn = "ou=groups,dc=domain"
domain="domain"
```
2.
add the same user "ldapuser" to both ou=users,dc=nondomain and ou=users,dc=domain auth resource.

add the user ldapuser from ou=users,dc=nondomain to the "unwanted_group_for_domain" group
add the user ldapuser from ou=users,dc=domain to the "wanted_group_for_domain_domain" group

3.
 log as ldapuser@domain and see it's belonging to both  "unwanted_group_for_domain" and "wanted_group_for_domain_domain" groups even if unexpected

## Context

having an installed user base with:
  - one mysql user/group  backend without domain
  - one ldap user/group backend without domain
Adding an
  - one ldap user/group backend with domain 

Without forcing the existing users to add a @domain to their logins.

## Your Environment

icingaweb2 version 
*  Icinga Web 2 .5.0 with: director,monitoring,doc.
*  icinga2 version r2.7.1-1
* Operating System and version:  Debian jessie 8.9
* Enabled features  api checker mainlog
* Config validation:  result ok

**Comment by lippserd** [comment]
Hi,

Thanks for the report and the PR. We'll have a look at them.

@Al2Klimov Please take care of this.

Best regards,
Eric

**Comment by marcofl** [comment]
This actually broke ldap groups for me, see https://github.com/Icinga/icingaweb2/issues/3324

**Comment by Al2Klimov** [comment]
Hello again @spaolo,

as discussed w/ @lippserd (offline), we'll probably revert that "fix" because

1. it broke @marcofl's setup
2. it may be not neccessary because this issue is not a bug

Please could you help us in our research and tell how did you *add the user ldapuser from ou=users,dc=domain to the "wanted_group_for_domain_domain" group*?
How did you change which AD object attributes?

Best,
AK

**Comment by spaolo** [comment]
Hallo @Al2Klimov.
I'm really curious how do you you and @lippserd argued that that johndoe from ldap server A gets the same permission of johndoe@domain from ldap server B is not a bug  :wink:. 
I understand you have and installed user base that don't use domain as realms and is currently in the "I'm basing my setup on an feature unexpected by coders" mode, i've lost count of times happened to me.
IMO this situation is not a low level coding problem but it's more about what a "domain" is, which objects is containing (users/groups/roles) and the @marcofl question "are they really mandatory?".
I think there are only 3 ways to fix the bug and gets off this empasse.
-  enforce all users in @marcofl situation to conform the actual domain logic and explain them domains are mandatory in ldap, i see it's not your favourite option.
-  tell me i need to force my existing user base to add a @domain while login, mercy please, i'm neither shure this will fix my actual situation.
-  add "disable_domain" keyword to place all user source in a single domain containing all objects, or at leaset the simplest implementation i can think for the @marcofl solution proposal.

To answer your question in groups.ini we use 
group_class = "groupOfNames"
group_member_attribute = "member"
Adding an user to a group means in the end to add a member to the object resulting like this.
``` 
dn: cn=wanted_group_for_domain,ou=groups,dc=domain
cn: wanted_group_for_domain
member: uid=johndoe,ou=users,dc=domain
objectclass: groupOfNames
objectclass: top
```
I'ts ok for you and @lippserd if I start working on a disable_domain keyword?

**Comment by lippserd** [comment]
I'm not quite sure why this patch was applied in the first place.
If you log in with user@domain and have a user group backend configured which is not responsible for a domain, the LDAP lookup is made with the full username, i.e. user@domain. This should not result in additional groups unless you really have this account in your LDAP obviously.
We are talking about the very same LDAP server with different base DNs in your example right? Any chance you provide us with the related debug logs when you log in with ldapuser@domain? Please make sure to revert this change beforehand.

**Comment by spaolo** [comment]
Unfortunately asking existing user to log with "@domain" it's exactly what i don't want.
I don't remember test results for the case you are referring, if you plan to revert PR #3251 I will need to restart all tests for my use case and forcibly found another solution and it will likely end up asking users to log wiht "@domain"  :laughing:

If i rightly undestood the code domain objects segregation or inclusion (users, group and roles) is made by web interface code beyond the ldap query construction that  commonly look up uid, cn or dn, object don't likes "@domain" form that much.

My setup its' a quite tricky, i will explain entirely if you wish, to be short users have the very same server,uid and dn and backends are splitted by filters but it's trickyness has the only fault of rising the probability of a username/uid/cn/dn collision from two different ldap server.

As said if you will revert PR i need to recreate a test setup with a 2.5.1 without PR #3251 for my setup.
I suppose i can add some test case to reproduce the issue in in a generic setup more interesting to you such:
- one mysql user backend
- two separated slapd istances with different basedn
but it will take time.
Any other suggestion/request for your setup/test cases ?.

**Comment by Al2Klimov** [comment]
TODO(AK): Fix as discussed w/ @nilmerg (offline).

**Comment by nilmerg** [comment]
@lippserd Domain awareness is a new feature recently introduced. Regarding user backends it behaves distinctly different in the way users are authenticated. Previously any user could authenticate with any backend as long as the user is known to the backend.

Now, domain aware backends only authenticate users of a specific domain and users of a specific domain can only authenticate with a backend responsible for it.

Domain aware group backends already provide groups only for users of the correct domain. However, group backends without domain awareness also provide groups for users authenticated by a user backend of a specific domain.

Scenario:
`jdoe@icinga.com` logs in using a backend responsible for `icinga.com`.

Current behaviour:
`jdoe` gets possibly groups assigned by a group backend not responsible for any domain.

Expected behaviour:
`jdoe` gets only groups assigned by a group backend responsible for the domain `icinga.com`.

Though, that's how we think it should behave. We may also consider the current behaviour a feature. Nonetheless we need to document the behaviour of group backends in this manner.

**Comment by spaolo** [comment]
@lippserd, @nilmerg is describing my scenario, as i can see PR #3403 and PR #3251, are basically the same patch, unfortunately i got some problems wich tooks precedence on this issue but i think im resuming this task, i think that vagrant box, test case and debug log will be ready in a week.

**Comment by Al2Klimov** [comment]
@spaolo But we're trying not to break @marcofl's setup by explicitly checking for "real domain-users".

**Comment by spaolo** [comment]
I know and unfortunately that's the point, it's unlikely you have both (me,@nilmerg ) and (@marcofl,@cstegm,@kajla) happy without a this_istance_of_icingaweb_dont_wanna_domain_segregation = true|false or a option.
IMHO the only one real escape from this empasse is making a reasonable test environment with setup cases and settle what is supported and what is not, and that's what i'm try to do.

**Comment by Al2Klimov** [comment]
No, IMO it's not that unlikely. (#3403)
Think positive! 😄

**Comment by nilmerg** [comment]
@spaolo The new pull request does not interfere with the environment of @marcofl. There's no domain aware user backend involved but users still login with e.g. `jdoe@icinga.com`. That's just the standard behaviour of non-domain aware backends, which broke with #3251.

#3403 avoids this by checking the user backend a user authenticated with. If it's a domain aware user backend, non-domain aware group backends do not feel responsible at all.

**Comment by spaolo** [comment]
I just finish up with tests and i'm a quite astounded, I can't reproduce the problem in the form i got it in my running setup only 
In [this test playground](https://github.com/spaolo/icinga-playground) issue seems more related to a group collision issue instead of a wrong group assignment, below results.
[result-and-debug.zip](https://github.com/Icinga/icingaweb2/files/1904982/result-and-debug.zip)

Since @nilmerg PR #3403 fix both mine and @marcofl setup should be shurely preferred to my patch even if test3 still shows some problem with group collision.

Test results also shows my wierd setup does not behave like two really distinct ldap server as I tought in first, my apologize in being stubborn about that.

Feel free to push any other test to the playground and ask me for a run.

Thank you all for your patience.

**Comment by lippserd** [comment]
The patch which made it into version 2.5.1  has been reverted in version 2.5.2. For version 2.6.0 we think about whether it makes sense to disallow group backends to be responsible for users which authenticated via a user backend which is restricted to a domain.

**Comment by spaolo** [comment]
i guess it depend on wath one think a "domain" is:
- a tenant fence
- an extra way of tagging user
as long as I'm for the first option i hope PR #3403 will be merged sooner or later.
