### ISSUE TITLE
Replace custom patterns in plugin output

### ISSUE THREAD

**Issue by Programie** [Icinga/icingaweb2#3257]
It would be nice to allow custom formatting of the plugin output.

In my case I'm using Check_MK which uses `(!)` and `(!!)` for displaying a warning and error inline box. I want to replace those Check_MK specific tags with custom HTML like the following examples.

Example replacement for `(!)`:
```html
<i class="icon-attention-circled" style="color: orange; font-size: larger;"></i>
```

Example replacement for `(!!)`:
```html
<i class="icon-attention-circled" style="color: red; font-size: larger;"></i>
```

So a plugin output like
```
WARN - Data is outdated(!)
```
would be rendered as
```html
WARN - Data is outdated <i class="icon-attention-circled" style="color: orange; font-size: larger;"></i>
```

**Comment by lazyfrosch** [comment]
Icingaweb2 replaces something like: `[WARNING]`

But in theory we could add custom replacements based on hooks...

**Comment by lippserd** [comment]
Yep, we should make that hookable.

@Programie Thanks for the report.
