### ISSUE TITLE
Ini comments with hash (#) break IniParser

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2#3267]
```
<b>Fatal error</b>:  Uncaught ErrorException: syntax error, unexpected END_OF_LINE, expecting '=' in Unknown on line 5
 in /usr/share/php/Icinga/File/Ini/IniParser.php:263
Stack trace:
#0 [internal function]: Icinga\Application\ApplicationBootstrap-&gt;Icinga\Application\{closure}(2, 'syntax error, u...', '/usr/share/php/...', 263, Array)
#1 /usr/share/php/Icinga/File/Ini/IniParser.php(263): parse_ini_string('[global]\ndefaul...', true)
#2 /usr/share/php/Icinga/Application/Config.php(326): Icinga\File\Ini\IniParser::parseIniFile('/etc/icingaweb2...')
#3 /usr/share/php/Icinga/Application/Config.php(421): Icinga\Application\Config::fromIni('/etc/icingaweb2...')
#4 /usr/share/icingaweb2/modules/nagvis/configuration.php(12): Icinga\Application\Config::module('nagvis')
#5 /usr/share/php/Icinga/Application/Modules/Module.php(1221): include('/usr/share/icin...')
#6 /usr/share/php/Icinga/Application/Modules/Module.php(1239): Icinga\Application\Modules\Module-&gt;includeScript('/usr/share/icin...')
#7 /usr/share/php/Icinga/Application/Modules/M in <b>/usr/share/php/Icinga/File/Ini/IniParser.php</b> on line <b>263</b><br />
```
Example:
```ini
[global]
default-map = "locations"

#[menu]
#TestMap = CustomerTest
```

This worked with Icinga Web 2.4. Should we fix this error?

Also the error in the Nagvis module breaks whole UI, including login.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.5.0 (previously 2.4.2)
* Operating System and version: CentOS 7

**Comment by lazyfrosch** [comment]
Oh and btw. the previous version logged a deprecation warning:

```
PHP Deprecated:  Comments starting with '#' are deprecated in Unknown on line 5 in /usr/share/php/Icinga/File/Ini/IniParser.php on line 263, referer: http://localhost/icingaweb2/dashboard
```

Question is: Do we care for this? :smile:

**Comment by dnsmichi** [comment]
That's been reported in #3252 already :)

**Comment by lazyfrosch** [comment]
Hm I looked for the EOL error...

**Comment by lazyfrosch** [comment]
But technically that another error than #3252...

**Comment by dnsmichi** [comment]
#3252 involves fixing and catching exceptions thrown by the new ini parser. `#` as comments has been deprecated for 10 years, and afaik 7.x marks that as a real error these days.

**Comment by Al2Klimov** [comment]
We could switch back to our own INI Parser, but @Thomas-Gelf would hit the roof for performance reasons. (He already did – that's why we're using PHP's parser.)

**Comment by lippserd** [comment]
We should just add this change to our upgrade docs but still don't support `#` as comment prefix.

**Comment by lippserd** [comment]
@Al2Klimov Please add this to our docs.
