### ISSUE TITLE
Navigation item urls with partial port macros are not saved

### ISSUE THREAD

**Issue by ralphbr** [Icinga/icingaweb2#3301]
I tried to create a service action with this target:

**http://$host.name$:5$_service_sysnr$00/**

The target of the service will not be saved, means if you call the navgation elements properties afterwards, the target field stays empty.

With **http://$host.name$:50000/**  it works fine.

The variable exists, I tested it with standard filter rules.

Icinga Web Version 2.5.0
Icinga2 Version: r2.8.1-1

**Comment by Al2Klimov** [comment]
Hello @ralphbr and thank you for reporting!

please could you
1. test `http://192.0.2.42:5$_service_sysnr$00/` and tell the result
2. share either your action as-is or (if there's sth. confidential) a minimal, censored version which definitively doesn't work

Best,
AK
