### ISSUE TITLE
Dashlets stopped using the whole space in dashboard

### ISSUE THREAD

**Issue by twagener** [Icinga/icingaweb2#3302]
In version 2.5.1 I just recognised that my dashlet doesn't use 100% of its space. If there is only one dashlet in the dashboard it's size is only 33% or 50%... I think before 2.5.1 the dashlet could grow to 100% if there is only one dashlet in the dashboard and not got cut off at 33%.

![icinga2](https://user-images.githubusercontent.com/5496512/35276654-5204cb00-0044-11e8-8354-b95e2bb4bfe0.jpg)

Would be nice to have this behaviour back...

**Comment by Tontonitch** [comment]
Hello,
Might be due to the fix solving the issue https://github.com/Icinga/icingaweb2/issues/2756
Play with the limit argument as explained there may solve your issue.
BR,

**Comment by twagener** [comment]
Actually that is not my problem, if i do so i just get the cursors to navigate. Scrolling works fine but i prefer to see the whole dashlet and not just a part if it if there is enough space..

**Comment by wolf-in-sheeps-clothing** [comment]
Same here, you were faster than me ;-) - I can confirm, that this "issue" is new in Version 2.5.1.
I updated my System yesterday from 2.5.0 to 2.5.1. Bevor the update my Grid Dashlet (in a Dashboard with only one Dashlet) uses 100% of the space. Now in Version 2.5.1 it uses only about 33% or 50% of the space and shows scrollbars.

![image](https://user-images.githubusercontent.com/31659047/35295663-f82c11ac-0079-11e8-8eb7-f0bcb9df3587.png)

Please edit this, so that we can use the previous view again.

**Comment by Al2Klimov** [comment]
Hello everyone and thank you for reporting!

please could all of you test the above changes?

Best,
AK

**Comment by Al2Klimov** [comment]
Sorry @wolf-in-sheeps-clothing, it seems I can't assign you.

**Comment by wolf-in-sheeps-clothing** [comment]
@Al2Klimov 
Oh yeah! Nice work! That's why I love you Icinga-Team.
I can confirm that the "Bug" is gone. Thanks a lot.

**Comment by wolf-in-sheeps-clothing** [comment]
Oh by the way, when you use the statistic as dashlet, it will be squashed. This is as long as I use Icingaweb2. And it is regardless of whether if you use it as single dashlet or not. Look here:

![image](https://user-images.githubusercontent.com/31659047/35401466-d6f3e0ce-01f9-11e8-8fa6-196e97f0a0fc.png)

**Comment by Al2Klimov** [comment]
@wolf-in-sheeps-clothing Please could you share the dashlet URL?

**Comment by wolf-in-sheeps-clothing** [comment]
You mean this one?

![image](https://user-images.githubusercontent.com/31659047/35402524-272c0f64-01fd-11e8-8fe2-8484dd3f8f8f.png)

**Comment by wolf-in-sheeps-clothing** [comment]
The monitoring/health/info has the same "problem"
![image](https://user-images.githubusercontent.com/31659047/35402740-c9129532-01fd-11e8-89f4-18bd12056aaa.png)

**Comment by Al2Klimov** [comment]
If you discover any other URLs, please write them down here, too, but I don't need any more screenshots.

**Comment by wolf-in-sheeps-clothing** [comment]
OK! I conclude that the discussion here is ok for you and I don't have to open a new issue for this "problem".

**Comment by Al2Klimov** [comment]
Hello @wolf-in-sheeps-clothing,

I've updated my PR. Please could you test it again w/ your URLs?

Best,
AK

**Comment by wolf-in-sheeps-clothing** [comment]
Hey,
so I went back to the original widget.less (without :not(:only-child) at line 77) and edit the responsive.less
The Grid still uses the full space (like bevor).
If in a dashboard is only one dashlet with an url "monitoring/health/..." everything is also fine. So far so good.
But if you use two urls in a dashboard like "monitoring/health/stats" and "monitoring/health/info" they look still like my screenshot from above. also when you use the url "monitoring/tactical" and "monitoring/health/stats" for example (It doesn't matter if "monitoring/health/stats" is the first or the second dashlet).
So the solution is near but not complete.
Nevertheless thanks for your work. Such a fast reaction is not a matter of course in open source.
