### ISSUE TITLE
LDAP Group Membership broken in 2.5.1

### ISSUE THREAD

**Issue by marcofl** [Icinga/icingaweb2#3324]
LDAP users do not belong to LDAP groups after upgrading to 2.5.1 anymore and therefore will have no permissions in icingaweb2 at all. 

## Expected Behavior
Users are assigned to the LDAP groups as it was in 2.5.0

## Current Behavior
LDAP groups are not assigned to users anymore.

## Steps to Reproduce (for bugs)
1. have similar LDAP config to this:

### roles.ini 
```
[Administrators]
groups = "group-Admin"
permissions = "*"
```
### groups.ini
```
[ldap]
backend = "ldap"
base_dn = "DC=corp,DC=ADS,DC=test,DC=ch"
group_class = "group"
group_filter = "&(sAMAccountName=group-*)"
group_member_attribute = "member"
group_name_attribute = "sAMAccountName"
resource = "ldap"
user_backend = "ldap"
user_base_dn = "DC=corp,DC=ADS,DC=test,DC=ch"
user_class = "user"
user_name_attribute = "userPrincipalName"
```
### authentication.ini
```
[ldap]
backend = "ldap"
base_dn = "DC=corp,DC=ADS,DC=test,DC=ch"
filter = "(&(objectClass=person)(objectClass=user)(|(memberOf=CN=group-Viewer,OU=Distribution,OU=Groups,OU=myunit,DC=corp,DC=ADS,DC=test,DC=ch)(memberOf=CN=group-Benutzer,OU=Distribution,OU=Groups,OU=myunit,DC=corp,DC=ADS,DC=test,DC=ch)(memberOf=CN=group-Admin,OU=Distribution,OU=Groups,OU=myunit,DC=corp,DC=ADS,DC=test,DC=ch)))"
resource = "ldap"
user_class = "user"
user_name_attribute = "userPrincipalName"
```
2. login with an admin account (non ldap user for example)
3. check the group memberships of a LDAP user, it will be empty
4. downgrade to 2.5.0 icingaweb2
5. login again
6. check the group memberships of a LDAP user, it will display correct ldap groups again

Also adding my ldap user name to the role works around the issue:
```
[Administrators]
groups = "group-Admin"
users = "myuser@name.example"
permissions = "*"
```

## Context
Users are still able to login but will have no permissions due to the missing group membership and permissions which are based on those groups 

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: Ubuntu Xenial 16.04
* Enabled features (`icinga2 feature list`): not relevant
* Config validation (`icinga2 daemon -C`): not relevant

**Comment by marcofl** [comment]
I found out, that this https://github.com/Icinga/icingaweb2/pull/3258/files actually is the cause for ldap groups no longer working (at least for my use case). When I remove those 3 lines code, everything works as it was in 2.5.0

Unfortunately I was not able to find this whole "domain aware" ldap group backend thing anywhere in the docs. Maybe I'm just missing something in the ldap config.

**Comment by marcofl** [comment]
In our case we use `user_name_attribute = "userPrincipalName"` where `userPrincipalName` is something like `<sirname>.<lastname>@<randomdomain>.<tld>` so I'm not able to set a domain for a backend or group. I could not find out how to tell the group backend not to care about the domain in the username at all.

**Comment by spaolo** [comment]
If you have a single ldap backend and you wish to mix mysql user with ldap user simply remove domain = 'ch' from ldap backend definition in authentication.ini
all users and group will be placed in the 'no domain' context

**Comment by spaolo** [comment]
Removing domain keword i'ts not enoug as i thougth.
For your situation i agree the optimal behavior would be having a global parameter to disable the "domain aware auth" feature and remove any special meaning for '@'.

**Comment by marcofl** [comment]
actually this `domain="ch"?` was just me testing around. I don't set that at all (sorry for the confusion here). The user backend works as it should, when no domain is set anywhere but the https://github.com/Icinga/icingaweb2/pull/3258/ broke the groupbackend / group memberships.

**Comment by spaolo** [comment]
I got a look to the code, default_domain gets always added if backend is ldap or msldap, i suppose that's why you hit the problem, "ldap user should belong to a domain but email logins don't belong to default domain because the @"
Placing an enable/disable flag for domain aware auth does not seem extremely complex i will try a patch in the next days.
Another way could be adding a 'domain_separator' parameter and set it to some other than @ this will let you place all 'email' domain users in a single 'ldap' default_domain regardless the '@', it should be much simple from the patching point of view but i'm scared the program logic will suffer.

**Comment by marcofl** [comment]
> Another way could be adding a 'domain_separator' parameter and set it to some other than @ this will let you place all 'email' domain users in a single 'ldap' default_domain regardless the '@', it should be much simple from the patching point of view but i'm scared the program logic will suffer.

should work too, In my use-case I just need the full login email address (not split by separator) in `user_name_attribute` in ldap and then the group backend should not try to do some checks for domain awareness when assigning group memberships.

**Comment by cstegm** [comment]
I have the same requirements as @marcofl - i just need the full login provided by kerberos via apache.

**Comment by Al2Klimov** [comment]
Hello @marcofl and thank you for reporting!

> we use email addresses for login

That's exactly the problem. The auth algos always split the username by `@` into (localpart, domain). At the moment you shouldn't configure any domain-aware auth as that will (most likely) break your setup completely.

Best,
AK

**Comment by spaolo** [comment]
@Al2Klimov 
The problem seems to be ldap always triggers on domain aware auth.
I pushed my first steps into the "disable domain aware flag" solution [here](https://github.com/spaolo/icingaweb2/commit/6d8664dcccdb383d9d881e62f5728b00ce2e5e10) with the hope of being helpful.
The patch seems to solve in the described environment but is of course not much forward-thinking.

**Comment by Al2Klimov** [comment]
Hello @marcofl,

Please could you
1. Set your user backend's domain to `*`
2. Revert [your changes](https://github.com/Icinga/icingaweb2/issues/3324#issuecomment-360808251)
3. Apply [mine](#3331)
4. Test and tell the result

Best,
AK

**Comment by spaolo** [comment]
Please be patient to me @Al2Klimov,
I made a small test on #3331. domain=* solution seems working in an email-login environment and i hope @marcofl and @cstegm will confirm it.
Unfortunately 0a002f breaks non email users logging with full "user@authdomain" syntax (non default_domain users are forced to) on the [ldap lookup](https://github.com/Icinga/icingaweb2/blob/0a002ffef886174fed1dcee8e5f3e9d4b9f981e1/library/Icinga/Authentication/User/LdapUserBackend.php#L398).
I think adding a special case for '*' domain is needed [while setting $username](https://github.com/Icinga/icingaweb2/blob/142950b822d66cbb3625b3ea98be64a96979d1b0/library/Icinga/Authentication/User/LdapUserBackend.php#L393) to complete the fix.
`$username = $this->domain === '*' ? $user->getUsername() : $username = $user->getLocalUsername();`  seems working fine for both mail and non mail cases.

**Comment by Al2Klimov** [comment]
Hello @spaolo and thank you for testing!

Unfortunately your suggestion wouldn't change anything in your case as `getUsername()` yields the same as `getLocalUsername()` for non-domain users.
Please could you test adding another user backend w/ the same config, but no domain at all, and a group backend w/ the same config, but referencing the new user backend?

Best,
AK

**Comment by marcofl** [comment]
@Al2Klimov using changes from #3331 and setting `domain="*"` in `authentication.ini` for my user backend works.

**Comment by marcofl** [comment]
@spaolo that's my use-case yes, besides that I don't see the point of setting `domain=*` in groups.ini / for the group backend

**Comment by spaolo** [comment]
@marcofl, the point is which domain belongs the group ?

**Comment by marcofl** [comment]
@spaolo I don't understand sorry. We don't use domains, there is no such thing as domains for us. email address = username (= user_name_attribute = userPrincipalName), it's one string in our use-case. if icingaweb splits that internally okay, but as long as there a not multiple backends responsible for different sets of users / groups, I don't see the point of checking against domains which I need to configure on the backend definition. 

I see that there are more complex use-cases where you have users logging in with and without a domain as part of the username.  And I really don't get the big picture here though, I'm find with any solution as long as it's documented and works :-)

**Comment by Al2Klimov** [comment]
Hello @marcofl,

We apologize for that breaking change, we Icinga Web devs indeed didn't think about setups using eMail addresses as usernames (shame on us). We saw that feature just from the LDAP POV.
But especially your users actually *have* domains - as part of their eMail addresses. IMO counting them as domains or not depending on... whatever would be more overkill than my change.
Anyway thank you for testing.

Best,
AK

**Comment by marcofl** [comment]
@Al2Klimov yes, I see that now, no problem. Can you then reassign this ticket to a Icingaweb Dev or to you and maybe add a milestone so we have an idea what's the target release for a fix?

**Comment by Al2Klimov** [comment]
I'm afraid I shall not make decisions about that, but feel free to subscribe to #3331 so you'll get any updates immediately.

**Comment by marcofl** [comment]
sure, thank you @Al2Klimov and @spaolo for your help.

**Comment by dnsmichi** [comment]
@lippserd 

Likely the same reports.

https://monitoring-portal.org/t/ldap-settings-for-userprincipalname-based-login-groups-management/930
https://monitoring-portal.org/t/ldap-authentication-role-assignement-does-work-for-users-but-not-for-ldap-groups/1241

**Comment by kajla** [comment]
+1
Any news?
Thanks!

**Comment by spaolo** [comment]
No, current solutions are rolling back to 2.5.0 or apply PR  #3331  and set domain=* in both authentication.ini and groups.ini

**Comment by kajla** [comment]
Oh, it's bad news.
Okay, I will try it.

**Comment by kajla** [comment]
I downgraded to 2.5.0, but it's very-very slow and it isn't work too. :(
Look forward to the next stable release.

**Comment by kajla** [comment]
I applied PR #3331, but I can't login with it. We don't use domain to login. Group membership is still missing. :(

**Comment by cstegm** [comment]
PR #3331 works for me

**Comment by spaolo** [comment]
@kajla, remember "domain=*" in authentication.ini and groups.ini is required to have email logins to work.

**Comment by kajla** [comment]
@spaolo, I added `domain=*` string to these files, and I couldn't login anymore.
We don't use the email address to login, we login with simple username like this: `john`
Thank you!

**Comment by kajla** [comment]
I made a Python script for temporary fix. It will be automatically sync group members to groups.
[sync_group_users.py.txt](https://github.com/Icinga/icingaweb2/files/1811049/sync_group_users.py.txt)
