### ISSUE TITLE
Icingaweb2 is not correctly adding commas to users= which caused admin status problems

### ISSUE THREAD

**Issue by paladox** [Icinga/icingaweb2#3327]
Hi, icingaweb2 is not correctly adding commas to users= in roles.ini.

I can confirm this is a bug as when looking in the file it looks like

```
[Administrators]
users = "paladox
zppix
samtar
mirahezestaff
arthur
adotchar"
permissions = "*"
groups = "Administrators"
```

## Expected Behavior

The roles.ini file should look like:

```
[Administrators]
users = "paladox,
zppix,
samtar,
mirahezestaff,
arthur,
adotchar"
permissions = "*"
groups = "Administrators"
```

## Current Behavior
It is not adding commas.

## Possible Solution
Add commas after to each user added to users=
## Steps to Reproduce (for bugs)
1. create a user
2. create another user
3. add them both to the same group
4. look at the roles.ini file

## Context
This broke all users with admin status, so i had to debug and find where the problem was.

Adding the missing commas fixed being an admin, thus the dashboard showed our hosts again.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): r2.8.1-1
* Operating System and version: ubuntu artful (17.10)
* Enabled features (`icinga2 feature list`): api checker command ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`): passes
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
```
Object 'world-wiki-main.c.world-wiki.internal' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 6:1-6:24
  * __name = "world-wiki-main.c.world-wiki.internal"
  * host = ""
  * log_duration = 86400
  * name = "world-wiki-main.c.world-wiki.internal"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 6
    * last_column = 24
    * last_line = 6
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "world-wiki-main.c.world-wiki.internal" ]
    % = modified in '/etc/icinga2/zones.conf', lines 6:1-6:24
  * type = "Endpoint"
  * zone = ""
```

**Comment by Al2Klimov** [comment]
Hello @paladox and thank you for reporting!

Did this ever work for you? If yes, please tell any Icinga Web 2 version it worked with. (later is better)

Best,
AK

**Comment by lippserd** [comment]
Hi,

newlines in the textarea in the roles configuration are not automatically replaced with commas nor are commas automatically inserted anywhere. You have to place them manually.

Best regards,
Eric

**Comment by paladox** [comment]
Hmm, that breaks it thoguh. It dosent add commas it’s self when inserting new data.
