### ISSUE TITLE
empty hostgroups shown in icingaweb2

### ISSUE THREAD

**Issue by tomabg** [Icinga/icingaweb2#3328]
in icingaweb2 v2.5.1 empty hostgroups are shown under hostgroups

in former versions(2.4) empty hostgroups were not shown

**Comment by lazyfrosch** [comment]
see #2796 and #3221

**Comment by tomabg** [comment]
OK thanks accepted as wanted behaviour/feature-->close issue

use case in our scenario only for info.
having several satelites in the locations were only the local equpment/hostgroup was seen for local admins....now all hostgroups are seen on satelites..however this can be managed with monitoring groups and filter on hostgroups
