### ISSUE TITLE
Custom Tactical-Overview Graphs

### ISSUE THREAD

**Issue by mikeb93** [Icinga/icingaweb2#3334]
Create a new menu for customized Tactical graphs which can visualize filtered results.

## Expected Behavior

A new submenu inside "Overview" where we can add our own custom Tactical Overview graphs by filtering results (like we can do in the Host or Services submenu) and visualizing the status of the filtered objects.
Those tactical graphs could be arranged in a grid maybe with auto adapting sizes (like grafana's dashboards).

## Current Behavior

Right now, we just have a static overview of every host and every service of our monitoring environment. In my opinion it would greatly increase visability of overall health of different locations/branches/services. 

I've created a super professional mockup, so you can at least imagine what I'm thinking of:

![2018-02-13 13_40_17](https://user-images.githubusercontent.com/1926571/36156584-c85cce6c-10d7-11e8-9fda-f4890c5766e9.png)

To clarify further: With custom graphs I mean just that donut graph filled with my custom filtered events. This feature request is only meant for that graph you see in the picture above.

Thanks in advance :)

**Comment by dnsmichi** [comment]
As per discussion on the forums: A "graph" isn't what Grafana or Graphite provides, but a single widget (donut, chart, cake, whatever) which can be added as dashlet. It should provide a config form where to choose the filters, and then being added onto a dashboard.

**Comment by chrnie** [comment]
I think the question for a customizable "Tactical Overview" is the point in this. 
Do you think it could be done as I noticed sevaral users asking for this?
