### ISSUE TITLE
icingaweb2 - PDF - Uncaught ErrorException...

### ISSUE THREAD

**Issue by akqopensystems** [Icinga/icingaweb2#3338]
## Current Behavior
Under the overviewpoint in icingaweb2, there are the following buttons: Tactical Overview, Hosts, Services and so on.

Now, if we want to genarete a PDF, we get the following error message.

**-- snip --**
Warning: Uncaught ErrorException: require_once(/usr/share/php/Icinga/File/../../vendor/dompdf/lib/html5lib/Parser.php): failed to open stream: No such file or directory in /usr/share/php/Icinga/File/Pdf.php:25 Stack trace: #0 /usr/share/php/Icinga/File/Pdf.php(25): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'require_once(/u...', '/usr/share/php/...', 25, Array) #1 /usr/share/php/Icinga/File/Pdf.php(25): require_once() #2 [internal function]: Icinga\Application\ClassLoader->Icinga\File\{closure}() #3 /usr/share/php/Icinga/File/Pdf.php(31): call_user_func(Object(Closure)) #4 /usr/share/php/Icinga/Application/ClassLoader.php(303): require('/usr/share/php/...') #5 [internal function]: Icinga\Application\ClassLoader->loadClass('Icinga\\File\\Pdf') #6 /usr/share/php/Icinga/Web/Controller/ActionController.php(532): spl_autoload_call('Icinga\\File\\Pdf') #7 /usr/share/php/Icinga/Web/Controller/ActionController.php(482): Icinga\Web\Controller\ActionController->sendAsPdf() #8 /usr/share/icingaweb2/ in /usr/share/php/Icinga/File/Pdf.php on line 25

Fatal error: Icinga\Application\ClassLoader::Icinga\File\{closure}(): Failed opening required '/usr/share/php/Icinga/File/../../vendor/dompdf/lib/html5lib/Parser.php' (include_path='/usr/share/icingaweb2/library/vendor:.:/opt/rh/rh-php71/root/usr/share/pear:/opt/rh/rh-php71/root/usr/share/php') in /usr/share/php/Icinga/File/Pdf.php on line 25
**-- snip --**

## Your Environment

icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.4 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.11.6.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

[root@host ~]# rpm -qa|grep -i icingaweb2
icingaweb2-vendor-JShrink-2.5.1-1.el7.icinga.noarch
icingaweb2-vendor-HTMLPurifier-2.5.1-1.el7.icinga.noarch
icingaweb2-vendor-lessphp-2.5.1-1.el7.icinga.noarch
icingaweb2-2.5.1-1.el7.icinga.noarch
icingaweb2-vendor-Parsedown-2.5.1-1.el7.icinga.noarch
icingaweb2-vendor-zf1-2.5.1-1.el7.icinga.noarch
**icingaweb2-vendor-dompdf-2.5.1-1.el7.icinga.noarch**
icingaweb2-common-2.5.1-1.el7.icinga.noarch
icingaweb2-selinux-2.5.1-1.el7.icinga.noarch

**Comment by fp306** [comment]
+1 after upgrading from 2.4.2 to 2.5.1

**Comment by Tontonitch** [comment]
same for me, also on 2.5.1. Don't know how it was before.

**Comment by Tontonitch** [comment]
Fixed by changing in /usr/share/php/Icinga/File/Pdf.php
line 23 to 
`$baseDir = __DIR__ . '/../../../icingaweb2/library/vendor/dompdf';`

By the way, pdf generation is quite slow and sometimes fails with timeout

**Comment by akqopensystems** [comment]
@Tontonitch: Thank you! Yes, it is very slow, but it seems to be running.
We also noticed the timeout problem.

Unfortunately, there are also rendering problems.

**In icingaweb2:**
![grafik](https://user-images.githubusercontent.com/23358770/35816750-d68e2194-0a9b-11e8-8b79-c7026139e8fa.png)


**In PDF**
![grafik](https://user-images.githubusercontent.com/23358770/35816830-fecfc388-0a9b-11e8-9c81-0277468ed68d.png)

**Comment by Al2Klimov** [comment]
Hello @akqopensystems and thank you for reporting!

Please could all of you (@akqopensystems @fp306 @Tontonitch) test the above changes?

Best,
AK

**Comment by Tontonitch** [comment]
@akqopensystems for rendering issues I opened another issue #3341 with some other exemples

**Comment by Tontonitch** [comment]
@Al2Klimov indeed your change fix the failed to open issue, thanks

**Comment by fp306** [comment]
@Al2Klimov the above change worked for me too
