### ISSUE TITLE
Package "icingaweb2-module-monitoring" is only recommended on Ubuntu Xenial

### ISSUE THREAD

**Issue by N-o-X** [Icinga/icingaweb2#3339]
The package "icingaweb2-module-monitoring" has to be installed manually and does not come with the base "icingaweb2" package anymore. It's just a recommended package now. This seems to be a bit misleading.

**Comment by Al2Klimov** [comment]
1. Icinga Web 2 is (by design) just a framework around possibly the monitoring module and/or any other one
2. There is at least one of our customers who doesn't use the monitoring module at all

**Comment by lazyfrosch** [comment]
It was recommended from early on on Debian/Ubuntu, so that one can use just the web framework.

So agreed with @Al2Klimov
