### ISSUE TITLE
pdf generation issues with icons, logos, number rendering

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2#3341]
Hello,

I'm facing multiple issues with the pdf generation (issues with icons, logos, number).
Bellow some details about the issues on common icingaweb2 pages.

## Expected Behavior

- Overview>Hosts

should see something similar to
![image](https://user-images.githubusercontent.com/600025/35816192-5fd054d8-0a9a-11e8-9ede-ac272387ac81.png)

- Overview>Services

should see something similar to
![image](https://user-images.githubusercontent.com/600025/35816223-785c94b2-0a9a-11e8-94b9-a9cef5597d23.png)

- Overview>Hostgroups and Overview>Servicegroups

should see something similar to
![image](https://user-images.githubusercontent.com/600025/35816099-3fac41f8-0a9a-11e8-8a89-459af525e5df.png)

- Overview>Comments

![image](https://user-images.githubusercontent.com/600025/35816461-123f35bc-0a9b-11e8-93f4-0a2760029e72.png)

- Generalities with links:

I don't expect any links to remain.

## Current Behavior

- Overview>Hosts:

logo and exclamation mark icon generation fails:
![image](https://user-images.githubusercontent.com/600025/35815839-bf349a48-0a99-11e8-8a61-ac50376d97a3.png)

- Overview>Services

exclamation mark icon and pie charts generation fails:
![image](https://user-images.githubusercontent.com/600025/35815989-093cc854-0a9a-11e8-9724-805ee2223236.png)

- Overview>Hostgroups and Overview>Servicegroups

Numbers are not shown in the status details parts
![image](https://user-images.githubusercontent.com/600025/35816031-280e0bee-0a9a-11e8-8531-bf2ba15cf427.png)

- Overview>Comments

Wheel, tick and cross replaced by interrogation mark
![image](https://user-images.githubusercontent.com/600025/35816520-36dda0c0-0a9b-11e8-9a60-f4244380948f.png)

- Generalities with links:

There are links to files:/// resources, which are broken.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`):
* Operating System and version: RedHat 7.4
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by akqopensystems** [comment]
We have the same behavior.

**Comment by Al2Klimov** [comment]
Hello @Tontonitch and thank you for reporting,

we'll [rebuild](https://github.com/Icinga/icingaweb2-module-pdfexport) that anyway – one nice day...

Best,
AK

**Comment by Tontonitch** [comment]
@Al2Klimov Yep I saw that new repo yesterday, but didn't know if it was still in the roadmap. Apparently yes, nice ;-)
