### ISSUE TITLE
Business Process Downtime Set

### ISSUE THREAD

**Issue by tomek0001** [Icinga/icingaweb2#3343]
Hello,
I guess this is more of a feature request, but it would be nice to setup a downtime for applications configured under business process. It's rather tedious to go to each monitored components and set the downtime manually when an application is composed of many monitors. Is that something anyone has thought about implementing?

Thank you,

Tom

**Comment by Al2Klimov** [comment]
Hello @tomek0001,

do you mean downtimes for *business processes*? If yes, feel free to open your issue at [the respective tracker](https://github.com/Icinga/icingaweb2-module-businessprocess/issues).

Best,
AK
