### ISSUE TITLE
Sparkline charts are flickering on refresh since v2.5.1

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#3344]
## Expected Behavior
On auto-refresh I do not want to see flickering elements
 
## Current Behavior
Sparkline elements are flickering since v2.5.1, v2.5.0 is fine. Might be related to #3288.

**Comment by lippserd** [comment]
@Al2Klimov Could you please have a look at this one.

**Comment by Al2Klimov** [comment]
It *is* related to #3288 – it's a direct result of that fix of mine.
