### ISSUE TITLE
QUESTIONS your datepicker is awesome

### ISSUE THREAD

**Issue by stoivo** [Icinga/icingaweb2#3345]
Your date picker is awesome.

I did not find the source at once. I'm not used to browsing php apps. Is it a open extension which I could look at or is it something you developed here?

**Comment by lazyfrosch** [comment]
It is essentially HTML 5: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

**Comment by stoivo** [comment]
Thanks, I did not see that. The HTML5 date picker is good then.
