### ISSUE TITLE
Display check_timeout if set

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2#3346]
## Expected Behavior

check_timeout should be displayed if set in the detail view of a host or service

## Current Behavior

check_timeout is not displayed in the detail view of a host or service

## Possible Solution

display check_timeout in the detail view in the check_execution section

**Comment by dnsmichi** [comment]
`check_timeout` isn't available in the IDO database resource.

**Comment by cstegm** [comment]
check_timeout ist available when i click in inspect.

**Comment by dnsmichi** [comment]
`inspect` is provided by the Director module, not the monitoring module.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We may add this to our schema or keep it in mind for the Icinga DB. Option 2 seems like the logical choice to me.

Cheers,
Eric

**Comment by lippserd** [comment]
Icinga DB will have this information available. Until then we have to use director's inspect functionality.
