### ISSUE TITLE
Please add doc module searching

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2#3353]
Enchancement request, search box when parsing docs inside icingaweb2:

![image](https://user-images.githubusercontent.com/27829577/36038414-a516f5ec-0d8d-11e8-8887-8a0a553cedeb.png)

**Comment by dnsmichi** [comment]
Please open these feature requests in the dedicated module project [here](https://github.com/Icinga/icingaweb2-module-doc).
