### ISSUE TITLE
Create issue from host and services page

### ISSUE THREAD

**Issue by KAMI911** [Icinga/icingaweb2#3362]
Call a predefined, prepared link with parameters to "Create issue" from an actually viewed host page or service page.

## Expected Behavior
Add a new link next to Comment / Notification / Downtime bar as "Create issue" from a currently selected services and hosts those in error state (W or C). From preferences side.

Like generictss it would be nice to have option to create a new ticket from an issue.

**Comment by lazyfrosch** [comment]
Well this is a pretty broad feature request.

1. Just "creating a ticket" is not that easy, but could be implemented as a module
2. Any module can provide Actions for monitored objects, there is an [example in Director](https://github.com/Icinga/icingaweb2-module-director/blob/master/library/Director/ProvidedHook/Monitoring/ServiceActions.php)
3. You can add those "ServiceActions" also via custom navigation (User -> My Account -> Navigation)

Currently it is not possible to add those actions to the top navigation bar in DetailView.

You should use one of those options.

**Comment by Thomas-Gelf** [comment]
@KAMI911: the [JIRA](https://github.com/Thomas-Gelf/icingaweb2-module-jira) module implements something similar for a specific issue tracker - JIRA. Eventually this can help you to get an inspiration of how to solve this for your specific software.
