### ISSUE TITLE
LDAP Discover function breaks auth if discover it not allowed

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icingaweb2#3365]
If ldap doesnt allow discovering icingaweb2 will not be able to get users from the ldap. 
```
Validation Log

Connect without encryption
LDAP bind (uid=xx,cn=Users,ou=xxx,dc=xxx / ***) to ldap.domain with default port 389 successful
Schema discovery not possible: Capability query failed (ldap.domain; Default port: 389): Can't contact LDAP server. Check if hostname and port of the ldap resource are correct and if anonymous access is permitted.
```
Stacktrace:
```
LDAP bind (uid=xxx,cn=Users,ou=xxx,dc=xxx / ***) to ldap.domain with default port 389 failed: Can't contact LDAP server

#0 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(432): Icinga\Protocol\Ldap\LdapConnection->bind()
#1 /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php(457): Icinga\Protocol\Ldap\LdapConnection->fetchAll(Object(Icinga\Protocol\Ldap\LdapQuery), NULL)
#2 /usr/share/php/Icinga/Data/SimpleQuery.php(579): Icinga\Protocol\Ldap\LdapConnection->fetchRow(Object(Icinga\Protocol\Ldap\LdapQuery))
#3 /usr/share/php/Icinga/Data/SimpleQuery.php(455): Icinga\Data\SimpleQuery->fetchRow()
#4 /usr/share/php/Icinga/Repository/RepositoryQuery.php(450): Icinga\Data\SimpleQuery->hasResult()
#5 zend.view:///usr/share/icingaweb2/application/views/scripts/user/list.phtml(43): Icinga\Repository\RepositoryQuery->hasResult()
#6 /usr/share/php/Icinga/Web/View.php(270): include(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#13 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#15 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#17 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#18 {main}
```

When I disable the discover function I'll get a result of all users without problems. 
```
/usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php
 249     /**
 250      * Return the capabilities of the current connection
 251      *
 252      * @return  LdapCapabilities
 253      */
 254     public function getCapabilities()
 255     {
 256     /*
 257         if ($this->capabilities === null) {
 258             try {
 259                 $this->capabilities = LdapCapabilities::discoverCapabilities($this);
 260                 $this->discoverySuccess = true;
 261                 $this->discoveryError = null;
 262             } catch (LdapException $e) {
 263                 Logger::debug($e);
 264                 Logger::warning('LADP discovery failed, assuming default LDAP capabilities.');
 265                 $this->capabilities = new LdapCapabilities(); // create empty default capabilities
 266                 $this->discoverySuccess = false;
 267                 $this->discoveryError = $e;
 268             }
 269         }
 270     */
 271         $this->capabilities = new LdapCapabilities (); // create empty default capabilities
 272         $this->discoverySuccess = false;
 273         return $this->capabilities;
 274
 275     }
```

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.5.1 
* Version used (`icinga2 --version`): 2.8.1
* Operating System and version: Centos 6

**Comment by lippserd** [comment]
Hi,

Thanks for the report. @nilmerg any chance we make the capabilities discovery optional?

Best regards,
Eric

**Comment by nilmerg** [comment]
@lippserd The discovery is optional. It has never been mandatory. If it's really an issue with the discovery, we'll need to fix this.

 @mkayontour The stacktrace you have posted does not mention anything about the discovery. It's simply from a connection buildup during user retrieval. Please show us the correct stacktrace, without any changes to the source code.

**Comment by lippserd** [comment]
@mkayontour Any news?

**Comment by mkayontour** [comment]
As I stated in my inital post, there's written: 

> Schema discovery not possible: Capability query failed

![grafik](https://user-images.githubusercontent.com/7584938/37330102-4755f670-26a0-11e8-9833-6519f45b6c1a.png)

In addition I don't get any more output than that on this topic. Debug won't log any error so this is the only information I have. In fact I only get the stacktrace when I try quering all users ...

**Comment by nilmerg** [comment]
Okay. I think you'll need to start from scratch whatever you're trying to accomplish.

The message about the schema discovery is only for informational purposes. The validation still passes without problems. It's even able to perform a successful bind.

The stacktrace you've posted is, als already said, from a connection buildup. It simply says it cannot perform a bind with the LDAP server. However, the validation succeeded.

Please check whether the correct LDAP resource is configured for the authentication backend you're trying to list users from.

**Comment by mkayontour** [comment]
### First case: 
No encryption used and a valid BIND_DN which is allowed to read data from ldap.
Without disabling the discovery, I'm not able to login. And can't get the list of users. 

Result in the Log
```
Mar 13 09:58:21 lxf90p29 icingaweb2[38429]: Icinga\Exception\AuthenticationException in /usr/share/php/Icinga/Authentication/User/LdapUserBackend.php:417 with message: Failed to authenticate user "uxxx" against backend "User_P_LDAP". An exception was thrown: <- Icinga\Protocol\Ldap\LdapException in /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php:340 with message: LDAP bind (uid=DWxxx,cn=Users,ou=K-xxx,dc=xxx / ***) to tamxx.xxx with default port 389 failed: Can't contact LDAP server
```
### Second case: 
Using LDAPS as encryption and the valid BIND_DN which is allowed to read data from ldap
Without disabling the discovery, I'm able to login but still don't get a list of users. 

![grafik](https://user-images.githubusercontent.com/7584938/37332412-ef7c2cba-26a6-11e8-9646-6594e7d57a90.png)

![grafik](https://user-images.githubusercontent.com/7584938/37332456-0d9889b4-26a7-11e8-96b4-0e20525f16ab.png)


I have only one LDAP resource configured and therefore only one to check on. 

Thanks for your help.

**Comment by nilmerg** [comment]
Just out of curiosity, is there some kind of load balancing in effect? Or is it only possible for the hostname of the ldap server to resolve to a single ip address?

I'm asking because I wonder why enabling/disabling encryption makes such a difference.

**Comment by edward-of-clt** [comment]
I have begun to see a similar issue. Icinga is the only server that is having issues connecting to our LDAP server yet they are all built out of the same ansible scripts.

```shell
2018-05-09T11:03:32-04:00 - DEBUG - Connect using LDAPS
2018-05-09T11:03:32-04:00 - DEBUG - Icinga\Protocol\Ldap\LdapException in /usr/share/php/Icinga/Protocol/Ldap/LdapCapabilities.php:329 with message: Capability query failed (den-a-kvm-ipa04 den-a-kvm-ipa05; Default port: 636): Can't contact LDAP server. Check if hostname and port of the ldap resource are correct and if anonymous access is permitted.
2018-05-09T11:03:32-04:00 - WARNING - LADP discovery failed, assuming default LDAP capabilities.
2018-05-09T11:03:32-04:00 - ERROR - Icinga\Exception\AuthenticationException in /usr/share/php/Icinga/Authentication/User/LdapUserBackend.php:417 with message: Failed to authenticate user "eherbert" against backend "icingaweb2". An exception was thrown: <- Icinga\Protocol\Ldap\LdapException in /usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php:338 with message: LDAP bind (uid=ldaplookup,cn=users,cn=accounts,dc=theark,dc=cloud / ***) to den-a-kvm-ipa04 den-a-kvm-ipa05 with default port 636 failed: Can't contact LDAP server

```

**Comment by nilmerg** [comment]
@edward-of-clt This sounds like it confirms my assumption in #3639. You're not using full URIs in your host definition. Try putting `ldap://` (or `ldaps://`) in front of all hostnames.

@mkayontour I'll close this issue now. I really think there's a DNS failover/loadbalancer in effect which resolves to differently configured ldaps. If you can proof that's wrong (with the real reason) please re-open.
