### ISSUE TITLE
Basic auth doesn't work for the API when using the RPM packages

### ISSUE THREAD

**Issue by gunnarbeutner** [Icinga/icingaweb2#3366]
The Apache config that's installed by the RPM packages doesn't enable forwarding the 'Authorization' header to PHP which is required in order to use the Icinga Web 2 API.

I had to manually add the following setting in `/etc/httpd/conf.d/icingaweb2.conf` to make this work:

`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

**Comment by lazyfrosch** [comment]
This should have been fixed in #3173, which OS and Package version?

**Comment by gunnarbeutner** [comment]
I'm using Michael's Vagrant VMs.

**Comment by dnsmichi** [comment]
I'm not using the Apache config provided by the RPMs, but an own template. This is due to the fact that I want to switch to Nginx at some point.
