### ISSUE TITLE
No ability to edit default contact group "icingaadmins"

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2#3373]
## Expected Behavior

This default group should be editable somewhere in icignaweb, if not in Director:

/etc/icinga2/conf.d/users.conf
```
/**
 * The example user 'icingaadmin' and the example
 * group 'icingaadmins'.
 */

object User "icingaadmin" {
  import "generic-user"

  display_name = "Icinga 2 Admin"
  groups = [ "icingaadmins" ]

  email = "icingaadmin@localhost"
}

object UserGroup "icingaadmins" {
  display_name = "Icinga 2 Admin Group"
}
```

## Current Behavior
In order to get all notifications about the icinga host icingaweb2 is running on, you must edit the file directly. I do not see a way to edit this via icingaweb2.  Even if I add a hostname = icinga.domain.com to a host group "Assign where" clause, the main host is not picked up.

There must be a better way to configure the alerts for the default host other than changing users.conf or hosts.conf to direct the notifications to the proper on-call group we have.

## Possible Solution

Allow configuration of this object in Configuration or expose the user/group to Director.

## Context

We had disk alerts for the icinga master host that were not reaching our team.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.1

Name | Version
-- | --
director | master
doc | 2.5.1
graphite | 0.9.0
monitoring | 2.5.1
setup | 2.5.1

* Version used (`icinga2 --version`): 
```
Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.4 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.17.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```
* Operating System and version: RHEL 7.4 64-bit
* Enabled features (`icinga2 feature list`): 
```
Disabled features: compatlog elasticsearch gelf influxdb opentsdb statusdata syslog
Enabled features: api checker command debuglog graphite ido-pgsql livestatus mainlog notification perfdata
```
* Config validation (`icinga2 daemon -C`):
```
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 4 Zones.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 2 FileLoggers.
information/ConfigItem: Instantiated 5 UserGroups.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 271 Notifications.
information/ConfigItem: Instantiated 219 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 82 Hosts.
information/ConfigItem: Instantiated 10 HostGroups.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 5 Users.
information/ConfigItem: Instantiated 12 ServiceGroups.
information/ConfigItem: Instantiated 180 Services.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 PerfdataWriter.
information/ConfigItem: Instantiated 1 IdoPgsqlConnection.
information/ConfigItem: Instantiated 1 LivestatusListener.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

**Comment by dnsmichi** [comment]
Icinga Web 2 just reads the objects from the IDO database backend where Icinga 2 stores such details. You really need to re-configure Icinga 2 for that, or, as you've said already, use the Director to fully manage your configuration.

**Comment by lippserd** [comment]
Just my two cents: He asks for managing the default configuration in /etc/icinga2. The director does not import nor does the Director have a chance to override the configuration in /etc/icinga2. So, when managing configuration with the Director one should disable the /etc/icinga2/conf.d include. Of course there are advanced setups where it makes sense to combine manual and managed configuration. But this does not apply here. @Thomas-Gelf might second this. Just to be sure.

**Comment by mtdeguzis** [comment]
Yes, sorry I couldn't explain it better. @lippserd summarized what I mean. Director never really is allowed to ignore that setup from the IDO db so that you can use Director as intended, to manage all your configs.
