### ISSUE TITLE
Mixed de_DE/en_US translation in the Tactical Overview

### ISSUE THREAD

**Issue by akqopensystems** [Icinga/icingaweb2#3375]
The browser (Firefox, Chrome no matter what) is configured to use de_DE (German) language.
Unfortunately, a mix of the two languages is displayed. I noticed an incorrect translation in the "Tactical Overview".

![grafik](https://user-images.githubusercontent.com/23358770/36835903-06ae06a6-1d38-11e8-990a-938c0489cd2b.png)

icinga2 -  (version: r2.8.1-1)
OS: RHEL 7.4
Icingaweb2 (2.5.1)

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll fix this with our next release.

Best regards,
Eric
