### ISSUE TITLE
Support SQLite resources

### ISSUE THREAD

**Issue by kobmaki** [Icinga/icingaweb2#3381]
Defining a sqlite as resource backend.

## Expected Behavior
When the PDO-driver pdo_sqlite is installed, it should be available as database resource.

## Current Behavior
Not  possible to us a Sqlite database as an resource. 

Other icingaweb2 modules like [icingaweb2-module-toplevelview](https://github.com/Icinga/icingaweb2-module-toplevelview) brings a commandline [ConvertCommand](https://github.com/Icinga/icingaweb2-module-toplevelview/blob/master/application/clicommands/ConvertCommand.php) that requires pdo_sqlite to convert toplevelviews.

## Possible Solution
I created a patch for icingaweb2 that enables sqlite as database resource.  Required a pull request and review. Pre discussion at Icinga Camp Berlin 2018 would be nice.

## Steps to Reproduce (for bugs)
Feature, not a bug.

## Context
Enhancing the database feature in icingaweb2 for sqlite. 

This will close the issue https://github.com/Icinga/icingaweb2/issues/2649 for "db2 and sqlite" as db2 is already implement in https://github.com/Icinga/icingaweb2/issues/2932

## Your Environment
OS is a Debian Strech with installed icingaweb2 from source http://packages.icinga.org/debian

**Comment by dnsmichi** [comment]
Did you discuss this with someone at Icinga Camp Berlin?

**Comment by Thomas-Gelf** [comment]
He did :)

**Comment by kobmaki** [comment]
I only want that my patch from 

https://github.com/kobmaki/kobmon-build/blob/master/patches/icingaweb2/0001-icingaweb2-patch-Db-sqlite.patch

would be integrated. I try with the documentation from 

https://github.com/Icinga/icingaweb2/blob/master/CONTRIBUTING.md

but it looks wrong and ugly :-(
@Thomas-Gelf or @lippserd  some advice or help?

**Comment by lippserd** [comment]
Hi,

Sure, we'll have a look at your patch.

Cheers,
Eric

**Comment by Al2Klimov** [comment]
Hello @kobmaki and thank you for contributing!

However it seems your commit is quite over-engineered:

> Showing 481 changed files with 56,092 additions and 46,148 deletions.

– https://github.com/kobmaki/icingaweb2/commit/f8e4895b6fca929fa16c8b94cf025c883c120f6d

Please create a commit from the mentioned patch (and only this one) and create a pull request.

Best,
AK

**Comment by Al2Klimov** [comment]
PS: Your patch works as expected, but what is you variable [$offerSqlite](https://github.com/kobmaki/kobmon-build/blob/master/patches/icingaweb2/0001-icingaweb2-patch-Db-sqlite.patch#L17) for?

**Comment by kobmaki** [comment]
The offerSqlite is not used, my mistake so I remove it from my patch that I recreated.
