### ISSUE TITLE
Add headlines to columns in (list-)views and sort functionality

### ISSUE THREAD

**Issue by doctore74** [Icinga/icingaweb2#3384]
Hi,

with reference to our conversation (DNSMichi and Eric) at Icinga Camp 2018 in Berlin...

Please implement column headings for list views like in CSV and JSON Output.
Sorting by the selected column should also be possible if you click on the heading.

Thomas Gelf presented this in his talk within the VMware vCenter Module.

If you add additional columns (as @dnsmichi mentioned) you can not differenciate between them.

For the additional functionalities i will create other issues.

Regards,
Christian

* Director version (System - About): master v1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache httpd-2.4.6-67

**Comment by nilmerg** [comment]
Won't happen in the foreseeable future.
