### ISSUE TITLE
Add control to select which columns to display in list views

### ISSUE THREAD

**Issue by doctore74** [Icinga/icingaweb2#3385]
Hi,

with reference to our conversation (DNSMichi and Eric) at Icinga Camp 2018 in Berlin...

Issue reference to #3384

Add dropdown field to select which columns to display in (list-)views

Please implement a dropdown field with checkboxes to select which columns should be displayed in list views.

Thomas Gelf presented this in his talk within the VMware vCenter Module.

The resulting view should be saved permanently. 
Bonus: ...saved for every user seperately

Regards,
Christian

* Director version (System - About): master v1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache httpd-2.4.6-67

**Comment by lippserd** [comment]
Hi,

It was a pleasure to meet you in Berlin. Thanks for the report. We'll see when and how this is going to be implemented.

Best regards,
Eric

**Comment by nilmerg** [comment]
Is planned for Icinga DB Web, though won't happen here.
