### ISSUE TITLE
Add the possibility to resize column widths of col1 and col2

### ISSUE THREAD

**Issue by doctore74** [Icinga/icingaweb2#3386]
Hi,

Issue reference to #3384, #3385

Add the possibility to resize column widths in (list-)views.

After adding additional columns the resulting column widths doesn't fit every time.

1. ...the possibility to de-/activate col2 permanently via button would be great in some cases (like in the Classic GUI)
2. The resulting view/settings should be saved permanently. 
3. ...saved for every user seperately

Regards,
Christian

* Director version (System - About): master v1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache httpd-2.4.6-67

**Comment by lippserd** [comment]
Moved to #3416.

**Comment by doctore74** [comment]
there is a type here:
the possibility to de-/activate col2 permanently
=>
the possibility to de-/activate second line permanently
