### ISSUE TITLE
Possibility to deactivate replacing hostname with host description and display description in brackets

### ISSUE THREAD

**Issue by doctore74** [Icinga/icingaweb2#3387]
Hi,

add the possibility to deactivate the replacing of the hostname with host description in host list view and display the description in brackets like in the detailled information.

Or is it possibly a bug?

Regards,
Christian

* Director version (System - About): master v1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache httpd-2.4.6-67

**Comment by dnsmichi** [comment]
That's a wanted behaviour, to have everything displayed by the display_name attribute if set. That allows for "obscure" object names while the real list views provide the beautiful names. This follows the idea of the 1.x Classic UI where this also implemented as default many years ago.

I don't think that this should be changed, or added something in brackets. From my point of view, this is too much information, and particularly I am not interested in reading too much when looking at a problem listing. If I am, I open the detail view instead.

Is there a specific use case or known workflow you are describing?

Cheers,
Michael

**Comment by chrnie** [comment]
From my point of view it would be nice to have the possibility to choose if you want to show the display_name OR the hostname.

**Comment by doctore74** [comment]
That is exactly the point. I would like to have the choice. 
If you are documentating something like "DNS server" in the Display Name / Description field you would run into problems if f.e. a DNS Server hostgroup is shown.

The bracket thing is a solution hint and absolutly optional.

**Comment by dnsmichi** [comment]
I'm not a friend of providing configuration for different looks and behaviors, and just focus on one view. Still I'll wait what @lippserd says to this request.
