### ISSUE TITLE
Possibility to deactivate plugin output in line below host- or servicename in first column of list views

### ISSUE THREAD

**Issue by doctore74** [Icinga/icingaweb2#3388]
Hi,

Issue reference to #3385

add the possibility to deactivate the display of plugin output in list views. If #3385 is implemented one can display it in the next column right beside.

- In list views it is sometimes difficult to distinguish between the rows. 
- #3385 gives the possibility to customize the layout to different needs

Regards,
Christian

* Director version (System - About): master v1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache httpd-2.4.6-67

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I'll close this in favor of #3385.

Best,
Eric
