### ISSUE TITLE
Marking in list views not possible

### ISSUE THREAD

**Issue by doctore74** [Icinga/icingaweb2#3389]
Hi,

if you try to mark text in list views you end up in clicking of the item. That is not always wanted.

# expected behavior
...

Regards,
Christian

* Director version (System - About): master v1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache httpd-2.4.6-67

**Comment by lippserd** [comment]
Hi,

Thanks for the report. To be honest, I don't want to support this because it requires some efforts to get this up and running. Plus, you are just one click away from the detail area where everything should be selectable. What's your use case here?

Best regards,
Eric

**Comment by doctore74** [comment]
Hi Erik,

 thank you for the reply. Sometimes you need one of both sides of the screen. If you want to just want to use some of the displayed info - whatever - you make an unwanted selection and the describes behavior is done. That is sometimes really annoying. On the other hand it is not really understandable and hard to explain to our customers that displayed text in a browser is not markable/copyable.
