### ISSUE TITLE
Allow more navigation levels

### ISSUE THREAD

**Issue by doctore74** [Icinga/icingaweb2#3390]
Hi,

the bookmarks could be more usable.

Suggestions:
- add more possible levels to bring structure in bookmarks
- implement possibility to un-/fold different levels (current state should be saved)
- implement possibility to jump to edit page (icon?) without the long ways over My Account -> Navigation
- Possibility to add icons for bookmarks

Regards,
Christian

    Director version (System - About): master v1.4.3
    Icinga Web 2 version and modules (System - About): 2.5.1
    Icinga 2 version (icinga2 --version): r2.8.1-1
    Operating System and version: CentOS 7
    Webserver, PHP versions: Apache httpd-2.4.6-67

**Comment by lippserd** [comment]
Hi,

Thanks for the report. It's intentional that we do not support more navigation levels in order to keep the UI and configuration forms simple. I don't think that we'll change this in the near future but I'll leave this issue open for discussion.

Best,
Eric

**Comment by lippserd** [comment]
Hi,

I close this issue now because we have nothing planned in this regard and there seems to be nothing much of interest.

Best,
Eric
