### ISSUE TITLE
Missing sort options for services_severity and hosts_severity in the group summary views

### ISSUE THREAD

**Issue by LHIND-LP** [Icinga/icingaweb2#3395]
## Expected Behavior
In version 2.4.1 of Icingaweb2 it was possible to sort a servicegroup view by the services severity. This was a nice feature we used in a custom dashboard (with additional filters). This sorting was accessible through Overview->Servicegroups in the top right corner aswell as with the addition of  "&sort=services_severity" to the servicegroup action in the list command of the monitoring module.

## Current Behavior
In the current version 2.5.1 this feature is missing. After some digging, I think it was removed in this commit https://github.com/Icinga/icingaweb2/commit/e42d86a4e185fc4f8d7e38e64f23705177ee1852#diff-c4d628b2c3c5658b78286e72b266c99f.

## Possible Solution
Bring back the sorting for severity to the service group summary view.

## Steps to Reproduce (for bugs)
Go to Overview->Servicegroups and try to sort for Severity in the sort box. It's missing.

## Context
We use a custom view for our service desk, where we have a prioritized view of the service groups to handle first. Currently we are using version 2.4.1 but want to upgrade to 2.5.1.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I removed this options because I thought they were not helpful. Lesson learned 😆 We'll bring them back in our next release.

Best regards,
Eric

**Comment by nilmerg** [comment]
@Al2Klimov Please re-add sorting functionality for `service_severity` and `host_severity`
