### ISSUE TITLE
Pie Charts in Tactical Overview not shown

### ISSUE THREAD

**Issue by KKeXX** [Icinga/icingaweb2#3397]
## Expected Behavior
Show Pie Charts in the Tactical Overview

## Current Behavior
Printing php Error:  `Fatal error: Using $this when not in object context in /usr/share/php/Icinga/Chart/Donut.php on line 284`

## Steps to Reproduce (for bugs)

1. Enable RHSCL Repo: subscription-manager repos --enable rhel-server-rhscl-6-rpms
2. Update icingaweb2 from 2.4.2-1 to 2.5.1 and installing rh-php70-php as dependency: yum update icingaweb2

## Context
Tactical Overview of Hosts and Services is not shown.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.1
* Version used (`icinga2 --version`): r2.8.1-1
* Web Server version: Apache 2.2.15-60
* PHP Version: 5.3.3
* Operating System and version: RHEL 6.9
* Enabled features (`icinga2 feature list`): api checker graphite ido-pgsql mainlog notification

**Comment by lippserd** [comment]
Hi,

Thanks for the report. You've installed php70 from the SCL repository but did not upgrade your apache config to serve requests with PHP-FPM. Please have a close look at our upgrading docs. You're still running PHP 5.3 which does not have `$this` support for Closures.

Cheers,
Eric
