### ISSUE TITLE
Sortable announcements page

### ISSUE THREAD

**Issue by fedepires** [Icinga/icingaweb2#3414]
This is more of a feature request maybe.

It would be nice if the announcements page had all the announcements history sorted by Start time, or even better, if the user could select the column to sort by.

## Your Environment

* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version
    2.5.1
Git commit
    6f5d0a16f9cac2795d015323ad04024371449934
Git commit date
    2018-01-22
* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.2-1)
* Operating System and version:
CentOS 7.4
* Enabled features (`icinga2 feature list`):
Enabled features: api checker ido-mysql mainlog notification opentsdb
* Config validation (`icinga2 daeminformation/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 198 Zones.
information/ConfigItem: Instantiated 198 Endpoints.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 5 ApiUsers.
information/ConfigItem: Instantiated 9 UserGroups.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 6379 Notifications.
information/ConfigItem: Instantiated 659 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 203 Hosts.
information/ConfigItem: Instantiated 221 HostGroups.
information/ConfigItem: Instantiated 249 Dependencies.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 10 Users.
information/ConfigItem: Instantiated 61 ServiceGroups.
information/ConfigItem: Instantiated 5254 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 OpenTsdbWriter.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).on -C`):

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This is indeed a bug. We'll fix it for one of our next releases.

Cheers,
Eric
