### ISSUE TITLE
check_command http follows redirects but web still outputs "permanently moved"

### ISSUE THREAD

**Issue by maniac0s** [Icinga/icingaweb2#3415]
I created my CheckCommand

    object CheckCommand "http_redirect" {
            import "http"
    
            arguments += {
                    "-f" = {
                            description = "handle 301 follow"
                            value = "$http_onredirect$"
                    }
                   "-v" = {
                           description = "verbose output"
                           value = "$http_verbose$"
                   }
            }
    }

And called it with

    object Host "www.myhost.de" {
		import "generic-host"
		address = "www.myhost.de"

		check_command = "hostalive"

		vars.vhosts["web"] = {
		        http_uri = "/"
		        vars.http_ssl = true
		}
	}

	apply Service "https" for (http_vhost => config in host.vars.vhosts) {
		import "generic-service"
		check_command = "http_redirect"

		vars.sla = "24x7"
		vars.http_verbose = "true"
		vars.http_onredirect = "follow"
		vars.http_verbose = "true"
		vars.http_vhost = http_vhost

		vars += config
	}

This is what I see in the webgui

        Plugin Output
	GET / HTTP/1.1
	Moved Permanently

	The document has moved here.

I activated debug log level on icinga2

Command called by icinga2

    /usr/lib/nagios/plugins/check_http -H web -I www.myhost.de -f follow -u / -v

When I call that on command line, I get 200 OK instead of redirect. Why is icingaweb2 still reporting 301?

Also, how can I activate verbose output in the webfrontend to see exactly what's been send and whats returned? vars.http_verbose doesn't show anything despite check_http getting the -v option...

**Comment by dnsmichi** [comment]
Icinga Web 2 only displays the output of the check result returned from execution by Icinga 2. This isn't really a bug but sounds more like a configuration problem. Please hop onto the community channels and discuss there, e.g. https://www.monitoring-portal.org/
