### ISSUE TITLE
Longoutput Request Button for Historical Issues

### ISSUE THREAD

**Issue by lenrico** [Icinga/icingaweb2#3422]
Hi,

it would be nice to see if someone can add a button or something like that, so we are able to see the longoutput for a historical issue which lies in the near/far past.

Everything for that is available in the Icinga2 database, a ajax call or something like that should do the thing.

I think this should be easy to implement, what do you think about it!?

**Comment by lippserd** [comment]
Hi Enrico,

Icinga Web 2 version 2.5.1 introduced detail areas for events where it is possible to view the long output: #3191.

Cheers,
Eric
