### ISSUE TITLE
host selection not working after upgrade from 2.5.1 -> 2.5.2

### ISSUE THREAD

**Issue by teclogi** [Icinga/icingaweb2#3439]
After upgrading Icinga Web from version 2.5.1 to 2.5.2, the host information can not be displayed in Icingaweb 2. 
Only a blank or a grayed out part of the Website will be displayed.
The services of the hosts are displayed as usually.

After clicking on the host link, the mysql service on the Icinga2 host increasing to about 100% CPU load and will not recover until restarting the mysql service.

A restor of the server and upgrading again did not solve the problem.

## Expected Behavior

The host should be displayed on the website and the mysql service should not increase to 100% CPU load.

## Current Behavior

The host information can not be displayed in Icingaweb 2. 
Only a blank or a grayed out part of the Website will be displayed.
The services of the hosts are displayed as usually.

![icinga2-bug](https://user-images.githubusercontent.com/27726999/39347841-ef772924-49f4-11e8-98a2-2a243d87b644.png)

After clicking on the host link, the mysql service on the Icinga2 host increasing to about 100% CPU load and will not recover until restarting the mysql service.

![icinga2-bug-mysql](https://user-images.githubusercontent.com/27726999/39347842-f5554452-49f4-11e8-917d-040214c6a1a4.png)

If I restart the mysql service, an only click on services, the mysql service CPL load is not increasing at all.
 

## Steps to Reproduce (for bugs)

1. Open a host in icingaweb2

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.2
* Version used (`icinga2 --version`): r2.8.4-1
* Operating System and version: Debian 9 (stretch)
* Enabled features (`icinga2 feature list`): api checker command graphite ido-mysql livestatus mainlog notification
* Config validation (`icinga2 daemon -C`): OK
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by nilmerg** [comment]
Hi,

known issue (#3436) and a fix is rolling out soon as part of a v2.5.3.

Thanks for reporting though!

Best regards,
Johannes
