### ISSUE TITLE
Transform any URL in a Comment to a clickable Link

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2#3441]
Hi,

I think it would be good if any url in a comment is transformed to a clickable Link within icingaweb2, like in my module: https://github.com/cstegm/icingaweb2-module-commenturls

**Comment by dajones70** [comment]
Would the generictts module do what you need?
https://github.com/Icinga/icingaweb2-module-generictts/blob/master/README.md

**Comment by cstegm** [comment]
My Module does exactly what i want, but i think this functionality should be standard in icingaweb2.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll consider this feature for one of our next feature releases.

Best,
Eric

**Comment by lippserd** [comment]
Related to #3684
