### ISSUE TITLE
Expire Option for Comments

### ISSUE THREAD

**Issue by sysadminsha** [Icinga/icingaweb2#3447]
## Expected Behavior

Comments should disappear when they become irrelevant and stay visible just in the event history. 

## Current Behavior

Comments stay visible at the commented Event forever if you don't delete them manually. 

## Possible Solution

Implement an "expire date" option for comments like the expire option for acknowledgements. 

## Context

We are trying to avoid having old and confusing information at some Icinga events. 
Additionally we are trying to avoid having to delete all those old comments manually. 

## Your Environment
Icinga Web2 Version 2.5.0

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Unfortunately Icinga 2 does not provide such an option. If we want to support this feature in the future, we'll have to implement this in Icinga 2 in Web 2.

Best,
Eric
