### ISSUE TITLE
Icinga Web2 search function and filters are very unhandy to use

### ISSUE THREAD

**Issue by sysadminsha** [Icinga/icingaweb2#3450]
## Expected Behavior
Easier combination of different search criterias/filters (&& / or ...) and explanations/help fields for the available parameters.  

## Current Behavior
The problems / events / hosts search functions and filter options in the Icinga Web2 portal are very unpractical to use. 
More Complex searches are hard to build. 
Many available filters are hard to understand, because it seems like any existing field of the database is presented as possible search filter. 

## Steps to Reproduce (for bugs)
1. just use the filter / search options  
2.
3.
4.

## Context
We tried building some complex searches with some ANDs and ORs on different levels. 

## Your Environment
Icinga Web2 portal 2.5.0

**Comment by nilmerg** [comment]
Hi!

We're aware of this, unfortunately long-standing, issue. It's going to improve as part of #1748. One of the improvements should be that the dropdown is narrowed down or replaced with an auto-completion input.

Best regards,
Johannes
