### ISSUE TITLE
CentOS 7: Kickstart Installation: Missing DB Schema Files

### ISSUE THREAD

**Issue by poing** [Icinga/icingaweb2#3462]
When installing icingaweb2 using kickstart (automated OS install with icingaweb2 packages) does not install the DB schema files.

```
%packages
# core packages
# icinga2 packages

# IncingaWeb2
centos-release-scl
httpd
icingacli
icingaweb2
icingaweb2-selinux
rh-php71-php-mysqlnd
sclo-php71-php-pecl-imagick

%end
```

To get the DB schema files installed, I followed the recommendation in bug: #1295

I can install the schema files by reinstalling the package, I was also able to do this in the kickstart post installation.

```
%post

yum reinstall -q -y --setopt=tsflags='' /mnt/Packages/icingaweb2-2.5.3-1.el7.icinga.noarch.rpm

%end
```

## Steps to Reproduce (for bugs)

1. Create kickstart installation using CentOS-7-x86_64-Minimal-1804.iso
2. Include icinga2/icingaweb2 in the kickstart
3. After installation, check `/usr/share/doc/icingaweb2/schema`
4. Find the directory is empty

## Context
Trying to create an automated OS and icinga2/icingaweb2 installation.

This is **not a high priority** bug, but it's an unexpected behavior when installing a software package.  Posted to help others trying to create a kickstart and let the developers know about the issue.

## Your Environment

* CentOS-7-x86_64-Minimal-1804.iso
* icingaweb2-2.5.3-1.el7.icinga.noarch.rpm
* icingaweb2-common-2.5.3-1.el7.icinga.noarch.rpm
* icingaweb2-selinux-2.5.3-1.el7.icinga.noarch.rpm

**Comment by dnsmichi** [comment]
Sounds like a similar issue as with Docker, where packages do not install any documentation by default. I don't know what `kickstart` is or how it works but I could imagine that it needs the same configuration bits.
https://superuser.com/a/817649

Package related problems should be reported to icinga/icinga-packaging in the future too.

**Comment by poing** [comment]
I noticed that it may be a documentation issue.  I was using the following in my `kickstart`:
```
%packages --excludedocs
icingaweb2
%end
```
I plan to test and see if that's the cause.  Will close this issue, once I confirm.

Since the schema files are **important** for installing icingaweb2, I don't think they should be classified as documentation.  Excluding documentation during an OS install (or Docker instance) typically implies "don't install man pages".

The schema used to be kept in: `/usr/share/icinga-web/etc/schema`

**Comment by dnsmichi** [comment]
Change is hard here, everyone knows where such are located and Google does so too. I don't think that this will happen, still you've found your problem now anyways.

**Comment by dnsmichi** [comment]
I personally never use excludedocs, as I expect the same as you do with a package installation. This is the overall problem, the Docker image for centos:7 does the same and people fall into it. Anyhow, I consider this resolved. Next time, please chime into the community channels at first glance, this has been discussed before.
