### ISSUE TITLE
config/module links broken

### ISSUE THREAD

**Issue by Farfaday** [Icinga/icingaweb2#3464]
Hi,

on icingaweb2 2.5.3, when navigating to config/module, i get the list of all modules, but clicking on the links
( links build like https://icingatest.xxx.xx/config/module/?name=monitoring ) I get only 
> The connection to the Icinga web server was lost at 2018-05-28 14:15.
in a red bar on the bottom of my screen.

I can then notice that the URL is now `https://icingatest.xxx.xx.xxx.com/config/modules#!/config/module/?name=monitoring`

If I open the same link but by pressing right-click -> "open in a new tab", the page loads, URL being `https://icingatest.xxx.xx.xxx.com/config/module?name=monitoring`

I tried to login/logout, without success.

How can I help debugging more ? What log do you need ?

From the nginx logs:
not working:
`10.112.50.72 - - [28/May/2018:12:19:52 +0000] "GET /config/module/?name=monitoring HTTP/1.1" 301 178 "https://icingatest.xxx.xx.xx.xx.com/config/modules" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" "10.96.130.93"
`
working:
`
10.112.50.72 - - [28/May/2018:12:23:11 +0000] "GET /config/module?name=monitoring HTTP/1.1" 200 14184 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" "10.96.130.93"
`

Many Thanks for your help,
François

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Which browser are you using?

Best,
Eric

**Comment by lippserd** [comment]
Hi,

There's an extra slash before the query string part in the URLs which are not working. Strange thing is that we don't render or add this slash somewhere in our code. Do you any browser extensions active? Are you still seeing this issue with Web 2 2.6.x?

Best,
Eric

**Comment by Farfaday** [comment]
Hi,
I tested on Firefox and chromium on linux, and on chrome and safari on macOS same behaviour. So I guess it is not extension related.
Still seeing the issue with icingaweb2 2.6.1
Many thanks,
François

**Comment by lippserd** [comment]
Could please share your Web 2 nginx config?

**Comment by Farfaday** [comment]
It has not changed since I provided it here : https://github.com/Icinga/icingaweb2/issues/3464#issuecomment-399134786

**Comment by lippserd** [comment]
This is your main nginx.conf if I'm not mistaken. The Web 2 nginx conf should look like this

```
location ~ ^/icingaweb2/index\.php(.*)$ {
  fastcgi_pass 127.0.0.1:9000;
  fastcgi_index index.php;
  include fastcgi_params;
  fastcgi_param SCRIPT_FILENAME /vagrant/public/index.php;
  fastcgi_param ICINGAWEB_CONFIGDIR /etc/icingaweb2;
  fastcgi_param REMOTE_USER $remote_user;
}

location ~ ^/icingaweb2(.+)? {
  alias /vagrant/public;
  index index.php;
  try_files $1 $uri $uri/ /icingaweb2/index.php$is_args$args;
}
```

**Comment by Farfaday** [comment]
hups, sorry:

```

bash-4.4# cat nginx/conf.d/default.conf 
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  root /usr/share/webapps/icingaweb2/public/;
  index index.php;

  # direct access to token file
  location /token { alias /etc/icingaweb2/setup.token; }

  if (!-d $request_filename) {
    rewrite ^/(.+)/$ /$1 permanent;
  }

  location / {
    try_files $1 $uri $uri/ /index.php$is_args$args;
  }

  location ~ ^/index\.php(.*)$ {
    fastcgi_pass 127.0.0.1:9000;
    #fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /usr/share/webapps/icingaweb2/public/index.php;
    fastcgi_param ICINGAWEB_CONFIGDIR /etc/icingaweb2;
    fastcgi_param REMOTE_USER $remote_user;
  }
}
bash-4.4# 
```

**Comment by Farfaday** [comment]
Hey,
I upgraded to 2.6.2 and i cannot reproduce the issue anymore !
Thanks!

**Comment by lippserd** [comment]
Okay, thanks for the feedback!
