### ISSUE TITLE
Passwords in clear

### ISSUE THREAD

**Issue by gonzalo-** [Icinga/icingaweb2#3466]
Hello, 

I am a new user on Icinga, and I have my setup running with Icingaweb2, I am using also modSecurity in front of it and I just figured that on modSecurity logs I can see the users and passwords on clear text, like:

`username=TEST&password=TESTt3sT&redirect=&formUID=form_login&CSRFToken=536984395%7Cce7086d76dd8ed92ec644d1b0a3d45a8baddf4641d845be4a83e8c8b248b2137&btn_submit=Login`

Is this normal? I am doing something wrong?

## Your Environment
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.17.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

**Comment by lazyfrosch** [comment]
Forms should always be submitted as POST, so data shouldn't be written to logs.

And yes passwords for login and other forms are submitted in plaintext.

**Comment by lazyfrosch** [comment]
As long as there is no suggestion to change this, im going to close the issue
