### ISSUE TITLE
Persistent acknowledgment comments do not "persist" when using the Api command transport

### ISSUE THREAD

**Issue by mdetrano** [Icinga/icingaweb2#3467]
When set to use the Icinga API as a backend command transport, an acknowledgment submitted with the "persistent" option doesn't actually have the comment "persist" after the ack. is removed.

## Expected Behavior

The comment sent with an acknowledgment should still be visible in the "comments" section of the web interface, after the object recovers or the acknowledgment is removed.  This is what happens when using the external pipe as a command transport.  

## Current Behavior

The comment submitted with the acknowledgment disappears when the ack is removed.

## Possible Solution

I think the fix is very simple:
In ..modules/monitoring/library/Monitoring/Command/Renderer/IcingaApiCommandRenderer.php

add

            'persistent'        => $command->getPersistent()

in this function 

public function renderAcknowledgeProblem(AcknowledgeProblemCommand $command)

## Steps to Reproduce (for bugs)

1. Setup Icinga Web 2 to use the Icinga Rest API as a command transport
2. Acknowledge a problem, checking the Persistent Comment box
3. Remove the Acknowledgment
4. Verify that the comment is no longer visible in the "Comments" section of the acknowledged object

## Context

Consulting clients would like to have the comments available to review who fixed a problem and what was noted at the time.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.3 (also, current code in git)
* Version used (`icinga2 --version`): 2.8.4
* Operating System and version: Centos 7

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll fix this asap.

Best,
Eric
