### ISSUE TITLE
Icingaweb2 fails when graphite host is down.

### ISSUE THREAD

**Issue by Stefar77** [Icinga/icingaweb2#3474]
When using Graphite for graphs and the Graphite webserver stops responding the Icingaweb2 becomes totally useless.

## Expected Behavior
It should at least just not show graphs or show a warning.

## Current Behavior
Getting stack-traces on everything that contains a graph.

## Possible Solution
Didn't look into it any further, may need a change in the exception handling to ignore the errors.

## Steps to Reproduce (for bugs)
1. Install carbon/graphite and configure it in Icingaweb
2. Down the Graphite server/jail
3. Try using Icingaweb2

## Context

I was doing some maintenance and while upgrading the base of the graphite jail I noticed IcingaWeb2 being totally useless until I was finished and started the Graphite jail again.

## Your Environment

* Versions used: 2.7 / web: 2.4
* Operating System and version: FreeBSD 11.1
* Enabled features: Graphite

**Comment by dnsmichi** [comment]
Should be reported to icinga/icingaweb2-module-graphite in case you are using this module.

**Comment by lippserd** [comment]
Our module should not fail in this case. If it's still the case please open an issue over here: https://github.com/icinga/icingaweb2-module-graphite
