### ISSUE TITLE
Confusing UI for downtime events 

### ISSUE THREAD

**Issue by ghost** [Icinga/icingaweb2#3478]
The host downtime status thing is very confusing for me:

![downtimes](https://user-images.githubusercontent.com/31341707/41643311-7e340c74-7473-11e8-86cd-e3c87a811106.png)

If I mouseover on the word "Fixed" it will highlight the whole line "Fixed downtime by icingaadmin created on Jun 19 16:23 ǀ scheduled on Jun 25 expires on Jun 26". That's good so far. However the mouseover on the word "Fixed" doesn't give any hover but it gives only on the text  "Jun 19 16:23", "Jun 25" and "Jun 26". The UI doesn't give any indication that these dates would be somehow separate elements that can be hovered on and it took me a long time to figure out how to find out the exact time for "Jun 25" downtime.

## Possible Solution

Let's get rid of the text " created on Jun 19 16:23 ǀ " or maybe put in in the hover text and then display "Jun 25" and "Jun 26" in the full format, so the text would be like this:
`Fixed downtime by icingaadmin | scheduled on Jun 25 12:20 expires on Jun 26 19:00 `

The hover text could be:
`Downtime created on Jun 19 16:23`

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.5.3

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll fix this in our next feature release.

Best,
Eric

**Comment by lippserd** [comment]
@nilmerg I accidentally pushed the fixes for this issue to master branch. Please have look 😆

**Comment by nilmerg** [comment]
In a host's detail view not all cases use the full date: ![Bildschirmfoto von 2019-07-11 13-55-47](https://user-images.githubusercontent.com/16668527/61049069-d7817500-a3e3-11e9-8f37-f26741635334.png)

The same area shows *flexible* twice for not started yet flexible downtimes: ![Bildschirmfoto von 2019-07-11 13-52-12](https://user-images.githubusercontent.com/16668527/61049068-d7817500-a3e3-11e9-8897-8c64606389da.png)

**Comment by lippserd** [comment]
Well and it shows expires w/o a timestamp.
