### ISSUE TITLE
Display the Director Caption of a Custom Variable

### ISSUE THREAD

**Issue by phil-or** [Icinga/icingaweb2#3479]
## Expected Behavior

Display the "Caption" of a custom variable in IcingaWeb2.

## Current Behavior

We define our "Data Fields" with the Icinga Director and want to display the "Caption" in IcingaWeb2
![datafield](https://user-images.githubusercontent.com/36534023/41643953-41feea6a-745c-11e8-8463-d2561a786c9f.JPG)

IcingaWeb2 currently display the "Field Name" of custom variable.
![customvariable](https://user-images.githubusercontent.com/36534023/41643957-451d0038-745c-11e8-9f33-3823116e5d1b.JPG)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.3
* Version used (`icinga2 --version`):  r2.8.4-1

**Comment by stevie-sy** [comment]
+1

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This requires a hook in Web 2 which allows to override the name of a custom variable. We'll think about whether and when we'll implement this.

Best,
Eric

**Comment by nilmerg** [comment]
ref/NC/734495

**Comment by phil-or** [comment]
Any news on this issue?
