### ISSUE TITLE
Missing Paramters for ressources.ini in Documentation

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icingaweb2#3482]
When you install or configure Icingaweb2 via GUI, there will be set this paramters in the file /etc/icingaweb2/ressources.ini:
![unbenannt](https://user-images.githubusercontent.com/38723488/41840642-c98d53c0-7855-11e8-9a53-1c372531d607.PNG)

![unbenannt1](https://user-images.githubusercontent.com/38723488/41840690-e4878e98-7855-11e8-9f24-3f69943bf6e0.PNG)

You also get an mouseover-Information:
![zwischenablage01](https://user-images.githubusercontent.com/38723488/41840736-06c71f28-7856-11e8-8b89-7bbd937198e6.jpg)

but in the online documentation (git and icinga.com) you can't find a description about this parameters:
![unbenannt3](https://user-images.githubusercontent.com/38723488/41840788-296d92aa-7856-11e8-9fbd-d558fad35f38.PNG)

**Comment by dnsmichi** [comment]
Can you send in a PR please? :)

**Comment by stevie-sy** [comment]
Do you mean this? 

Your Environment
•Icinga Web 2 version and modules (System - About): 2.5.3
•Version used (icinga2 --version): r2.8.4-1

**Comment by lippserd** [comment]
Hi,

Thanks for your report. Please don't use the persistent option because it's prone to errors. We'll remove this option with version 2.6.0. See #3480.

Best,
Eric
