### ISSUE TITLE
Request::getPost() parses JSON without respecting Content-Type

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#3484]
With a444b8adf5491d45f7ee7aff9259c4618308f140 `Request::getPost()` parses the POST body as JSON if header `Accept:application/json` is set.

However, `Accept` does not mean what is being sent so any other content type in the POST body is rejected with a syntax error.

Putting such a fundamental presumption in a base class is bad and we should only parse JSON unconditionally in concrete implementations. If this should be kept in the base class, it should only run if the POST body is actually JSON.

**Comment by lippserd** [comment]
Hi Johannes,

Yep, that's true. Thanks for the fast report. Will you open a PR?

Cheers,
Eric

**Comment by nilmerg** [comment]
Sure why not.
