### ISSUE TITLE
Anchor navigation not working

### ISSUE THREAD

**Issue by akqopensystems** [Icinga/icingaweb2#3492]
Wenn we want to look in a history an older service or host status we have to click multiple times on 'load more' button and it jumps every time to the beginning of the page.

## Expected Behavior
It should stay on the bottom of the page.

## Current Behavior
It jumps every time to the beginning of the page and we have to scroll increasingly to the bottom of the page.

## Possible Solution
It would be even better a date selection with from-to choises.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.3 Git commit date 2018-04-27
* Version used (`icinga2 --version`): r2.8.4-1
* Operating System and version: RHEL 7.5 3.10.0-862.el7.x86_64

**Comment by nilmerg** [comment]
Hi!

thanks for reporting this!

Just tracked this down. It's the result of https://github.com/Icinga/icingaweb2/pull/3295.
