### ISSUE TITLE
icingacli businessprocess don't work

### ISSUE THREAD

**Issue by xam-stephan** [Icinga/icingaweb2#3499]
Command: "/usr/bin/icingacli businessprocess process check test --config test"
don't work since 4ec783b75eeca7bfb53c202236ea04b6a07cbecb

Output:
PHP Fatal error:  Call to undefined method Icinga\Data\Db\DbConnection::getConfig() in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php on line 704

Fatal error: Call to undefined method Icinga\Data\Db\DbConnection::getConfig() in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php on line 704

## Expected Behavior

Icinga2 can't check ab BP

## Current Behavior

no "PHP Fatal error" ;-)
/usr/bin/icingacli businessprocess process check test --config test
Business Process OK: TEST

## Steps to Reproduce (for bugs)

1. icingaweb2 (master - testet with f905a978d8b3b968010fdee99521bda887b2d8c0)
2. icingaweb2-module-businessprocess (master - testet with 887bbd97f3d40ee5b35b156c661ea2bb7a914828)
3. any BP-Config (example test)
4. /usr/bin/icingacli businessprocess process check test --config test
5. Faild
6. git checkout c3b19996f8cae39839b111a86070c633d9061366 (icingaweb2)
7. /usr/bin/icingacli businessprocess process check test --config test
8. successful

## Your Environment

* Icinga Web 2 version and modules (System - About): 
* Version used (`icinga2 --version`): r2.8.1-1 / r2.8.2-1
* Operating System and version: SUSE Linux Enterprise Server 12 SP1 / SUSE Linux Enterprise Server 12 SP3
* Enabled features (`icinga2 feature list`): 
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql mainlog notification

* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: <host>
warning/ApplyRule: Apply rule 'TCP 3200' (in /var/lib/icinga2/api/zones/director-global/director/service_apply.conf: 1:0-1:23) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Ping' (in /var/lib/icinga2/api/zones/director-global/director/service_apply.conf: 9:1-9:20) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule '' (in /var/lib/icinga2/api/zones/director-global/director/service_apply.conf: 27:1-27:52) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'HTTP' (in /var/lib/icinga2/api/zones/director-global/director/servicesets.conf: 7:1-7:20) for type 'Service' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 2 Zones.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 4 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 5 UserGroups.
information/ConfigItem: Instantiated 8 NotificationCommands.
information/ConfigItem: Instantiated 1 Notification.
information/ConfigItem: Instantiated 222 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 795 Hosts.
information/ConfigItem: Instantiated 4 HostGroups.
information/ConfigItem: Instantiated 1 TimePeriod.
information/ConfigItem: Instantiated 5 Users.
information/ConfigItem: Instantiated 3 Comments.
information/ConfigItem: Instantiated 61 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by vita2** [comment]
get the same error with current icingaweb2 master (424f687f5deb5e8b2794f9391456dcbf3b275f01) & businessprocess master (icinga/icingaweb2-module-businessprocess@024d537272ddfe59bf2379ede1455929dd223ee6) 

my check command:
`/usr/bin/icingacli businessprocess process check mail --config all --details`

output:
```
PHP Fatal error:  Call to undefined method Icinga\Data\Db\DbConnection::getConfig() in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php on line 704

Fatal error: Call to undefined method Icinga\Data\Db\DbConnection::getConfig() in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php on line 704

```

**Comment by vita2** [comment]
i do not know why, but the issue does not exist anymore. few days ago, i did a system upgrade that seemingly fixed the problem :satisfied:

**Comment by lippserd** [comment]
Thanks for the feedback.
