### ISSUE TITLE
Can not delete downtime from Icingaweb2 interface

### ISSUE THREAD

**Issue by terraweb** [Icinga/icingaweb2#3506]
Hi
When in clustered environment, I can not delete downtime by hitting (X) in icingaweb2 web interface. 
Delete using console api call is working as expected.
It is the same behaviour on two completely different clusters/systems.

When on standalone icinga/icingaweb2, delete downtime in icingaweb2 web interface works fine.

icingaweb2 are two HTTP servers behind haproxy. I disabled one of the HTTP hosts from haproxy and left only one operational. The result is the same. Can not delete downtime.

Icinga Web 2 Version 2.5.3 Git commit

## Expected Behavior

Downtime to be deleted

## Current Behavior

Nothing happen. The downtime counter continues.
## Steps to Reproduce (for bugs)

1. Put host on downtime from icingaweb2 interface
2. try to remove the downtime by hitting (x) 
3.
4.

## Your Environment

* Icinga Web 2 version and modules (System - About):
* Version used (`icinga2 --version`): version: r2.8.4-1
* Operating System and version: RHEL7
* Enabled features (`icinga2 feature list`): api checker command ido-mysql influxdb mainlog notification perfdata
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.8.4-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: master.server
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 4 Zones.
information/ConfigItem: Instantiated 5 Endpoints.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 2 UserGroups.
information/ConfigItem: Instantiated 6 NotificationCommands.
information/ConfigItem: Instantiated 26017 Notifications.
information/ConfigItem: Instantiated 268 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 3147 Hosts.
information/ConfigItem: Instantiated 49 HostGroups.
information/ConfigItem: Instantiated 12 Downtimes.
information/ConfigItem: Instantiated 4 TimePeriods.
information/ConfigItem: Instantiated 2 Users.
information/ConfigItem: Instantiated 12 ServiceGroups.
information/ConfigItem: Instantiated 11435 Services.
information/ConfigItem: Instantiated 22 ScheduledDowntimes.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 PerfdataWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

Object 'global-templates' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 45:1-45:30
  * __name = "global-templates"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 46:3-46:15
  * name = "global-templates"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 45
    * last_column = 30
    * last_line = 45
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "global-templates" ]
    % = modified in '/etc/icinga2/zones.conf', lines 45:1-45:30
  * type = "Zone"
  * zone = ""

Object 'internal' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 33:1-33:22
  * __name = "internal"
  * endpoints = [ "internal1.worker", "internal2.worker" ]
    % = modified in '/etc/icinga2/zones.conf', lines 34:3-34:71
  * global = false
  * name = "internal"
  * package = "_etc"
  * parent = "master"
    % = modified in '/etc/icinga2/zones.conf', lines 35:3-35:19
  * source_location
    * first_column = 1
    * first_line = 33
    * last_column = 22
    * last_line = 33
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "internal" ]
    % = modified in '/etc/icinga2/zones.conf', lines 33:1-33:22
  * type = "Zone"
  * zone = ""

Object 'external' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 38:1-38:22
  * __name = "external"
  * endpoints = [ "external1.worker" ]
    % = modified in '/etc/icinga2/zones.conf', lines 39:3-39:44
  * global = false
  * name = "external"
  * package = "_etc"
  * parent = "master"
    % = modified in '/etc/icinga2/zones.conf', lines 40:3-40:19
  * source_location
    * first_column = 1
    * first_line = 38
    * last_column = 22
    * last_line = 38
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "external" ]
    % = modified in '/etc/icinga2/zones.conf', lines 38:1-38:22
  * type = "Zone"
  * zone = ""

Object 'master' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 29:1-29:20
  * __name = "master"
  * endpoints = [ "master1.server", "master2.server" ]
    % = modified in '/etc/icinga2/zones.conf', lines 30:3-30:71
  * global = false
  * name = "master"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 29
    * last_column = 20
    * last_line = 29
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "master" ]
    % = modified in '/etc/icinga2/zones.conf', lines 29:1-29:20
  * type = "Zone"
  * zone = ""

**Comment by terraweb** [comment]
PHP version: rh-php71

**Comment by lippserd** [comment]
Hi,

Are you using the API as command transport or the external command pipe?

Cheers,
Eric

**Comment by terraweb** [comment]
Hi Eric
Thank you for the quick response that pointed me to the right direction!
The transport has been set to Local. I changed it to api, and now it works as expected. 

Thank you again!

**Comment by lippserd** [comment]
You're welcome.
