### ISSUE TITLE
icingacli: "Got invalid column: service_problem" from list hosts --problems 

### ISSUE THREAD

**Issue by wopfel** [Icinga/icingaweb2#3512]
```
[root@icinga2 ~]# icingacli monitoring list hosts --problems
ERROR: Icinga\Exception\ProgrammingError in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php:806 with message: Icinga\Module\Monitoring\Backend\Ido\Query\HoststatusQuery : Got invalid column: service_problem
```

## Expected Behavior
Show only hosts with status <> UP.

## Current Behavior
Results in an error, program aborts.

## Steps to Reproduce (for bugs)
1. Fresh clone of https://github.com/Icinga/icinga-vagrant
2. cd icinga-vagrant/standalone
3. vagrant up
4. (wait) :-)
5. vagrant ssh
6. sudo -i
7. icingacli monitoring list hosts --problems

## Context
The following commands work just fine (no error):
* icingacli monitoring list hosts
* icingacli monitoring list services
* icingacli monitoring list services --problems

I've encountered the above error message on an Arch Linux system running the latest build and checked the behavior with a Vagrant box now.

## Your Environment
* Vagrant "Standalone" Box
* Icinga Web 2 version and modules (System - About): Icinga Web 2 Version 2.5.3, Git Commit 04913f36995b96a82327e95c95bbe0a3fef71227
* Version used (`icinga2 --version`): v2.8.4-814-gebd9d45
* Operating System and version: CentOS Linux 7 (Core), Kernel 3.10 (x64_64) (<-- VM), Arch Linux (<-- Host)
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`): _only warning and information messages_

Please let me know if I can add any other valuable information.

Kind regards,
Bernd

**Comment by lippserd** [comment]
Hi,

Thanks for the detailed report. Will be fixed asap.

Cheers,
Eric
