### ISSUE TITLE
Add a healthcheck endpoint

### ISSUE THREAD

**Issue by jakubgs** [Icinga/icingaweb2#3513]
As far as I can tell the Web UI does not have any path I could use as a healthcheck for this service.
There should be something like `/api/health` or `/icingaweb2/status` or something like that so I can verify the service is up.

**Comment by dnsmichi** [comment]
If you just want to see that the web frontend is running, use /icingaweb2 and grep for a specific text. If you want to simulate a login, try and see if you're redirected to the dashboard.

Specific system health pages can be queried too, e.g. http://localhost/icingaweb2/monitoring/health/info?format=json

In terms of a health check and more metrics, it would be interesting to know what exactly you'd expect with some more examples and design drafts.

**Comment by jakubgs** [comment]
For example Icinga2 uses a database. Proper healtcheck would verify that it is available and working.
But I guess in my case just checking `/icingaweb2` might be enough. Although it's not usable in my case because [Consul](https://www.consul.io/) checks do not allow for searching for any specific text, and the page HTML would make the Consul UI for that host a wall of useless html.

**Comment by lippserd** [comment]
This sounds like a good feature to me. Modules could provide health information via hooks. If anybody is interested in contributing this, give me a ping.
