### ISSUE TITLE
Host name with 'xxxx' ignores display_name

### ISSUE THREAD

**Issue by PeteNJ** [Icinga/icingaweb2#3522]
## Expected Behavior
i would expect display_name to be shown regardless of host name

## Current Behavior
object Host "Serverxxxx-name" {
     import generic_host
     display_name = "my server"
}

icingaweb2 dashboard shows host as "Serverxxxx-name" and not using the display_name;  services will show the host.display_name as expected but not the host tab

"ServerXXXX-name" and "Serverxxx-name" will honor the display_name value

it appears that "xxxx" is the issue.

## Steps to Reproduce (for bugs)

1. create host object with "xxxx" in the name and set a display_name; restart icinga2
2. look in icingaweb2 dashboard at host vs service tabs
3. change host object name to not have "xxxx"; restart icinga2
4. look in icingaweb2 dashboard to see display_name showing in host tab

## Your Environment

* Icinga Web 2 version and modules (System - About):  icingaweb2 2.5.1
* Version used (`icinga2 --version`): icinga2 r2.8.2-1
* Operating System and version:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.4.0-128-generic
  Architecture: x86_64

**Comment by nilmerg** [comment]
Works for me:

![my_server](https://user-images.githubusercontent.com/16668527/42616294-02d0191e-85ae-11e8-998d-5490ec673531.png)

using:

```
object Host "Serverxxxx-name" {
import "generic-host"
display_name = "my server"
}
```
as your example didn't work out of the box.

This looks like a configuration issue to me. Please head over to https://monitoring-portal.org for further questions.

**Comment by PeteNJ** [comment]
running through a couple more scenarios i was able to reproduce it using Host name "SERVER1xxxx-NAME" - a number of other case/number naming don't seem to show the same behavior.  apologies for not doing additional testing before posting
