### ISSUE TITLE
Documentation about default theme configuration is wrong

### ISSUE THREAD

**Issue by paul-stempel-cancom** [Icinga/icingaweb2#3539]
## Expected Behavior

In the following documentation is a topic for themes. 

https://github.com/Icinga/icingaweb2/blob/master/doc/03-Configuration.md
https://www.icinga.com/docs/icingaweb2/latest/doc/03-Configuration/

The documentation says, that the default configuration is set with the the theme attribute.

[themes]
disabled = "1"
theme = "Icinga"

This does not change the theme.

## Current Behavior

We found out, that **default** is accepted and changes the default theme.

[themes]
disabled = "1"
default = "Icinga"

## Possible Solution

Please update the documentation.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. That's right, our documentation is wrong here.

Best,
Eric
