### ISSUE TITLE
Changes in dashboard.ini needed due to updated german localization 

### ISSUE THREAD

**Issue by log1-c** [Icinga/icingaweb2#3542]
As there is a updated german localization fpr IcingaWeb2 2.6.0 existing dashboard.ini files for users need to be updated to use the new words.
The default dashboard "Aktuelle Incidents" was renamed to "Aktuelle Vorfälle".

I have fixed this for my using "vi" and ```:%s/Incidents/Vorfälle/g``` 

Maybe add a shot mention to the update docs?

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I think that this is a bug because identifiers in INI files shouldn't get translated.

Best,
Eric
