### ISSUE TITLE
FileCache directory clash between multiple virutal hosts

### ISSUE THREAD

**Issue by wferi** [Icinga/icingaweb2#3543]
We're hosting several Icinga2 instances (not in the "zones" sense) and their corresponding IcingaWeb2 interfaces on a single server. They use separate IDO databases and are meant to operate in total independence. All this works pretty well. However, I noticed that there is a `/tmp/FileCache_icingaweb` directory on the server, owned by one IcingaWeb2 instance (they run as separate UNIX users under PHP-FPM). Looking at the code, this denies the caching functionality from the other instances. What's the recommended way around this? Is setting `TMPDIR` in the FPM environment a good move? In my opinion the best solution would be making the name (currently hardwired to `icingaweb`) configurable in `config.ini`. Do I overlook something?

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I think it's best to chance the `TMPDIR` configuration. We try to keep the Web 2 configuration files as simple as possible. Could you please report back whether this works out for you?

Best,
Eric

**Comment by wferi** [comment]
Well, it works. But it introduces an extra directory level and requires extra maintenance, because the custom `TMPDIR` must exist. So I'd welcome an internal solution nevertheless.
