### ISSUE TITLE
Deprecated: __autoload() is deprecated, use spl_autoload_register()

### ISSUE THREAD

**Issue by paladox** [Icinga/icingaweb2#3547]
I am getting a deprecated notice when scheduling a host for downtime (and all child services).

```
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /usr/share/php/HTMLPurifier.autoload.php on line 17
test
```

## Expected Behavior

I expect no deprecated notice
## Current Behavior

I am getting a deprecated notice.

## Steps to Reproduce (for bugs)

1. schedule a host as downtime (tick all services and also select all child services too)

## Context

Just spam i guess though it could break in the future?

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.1
* Version used (`icinga2 --version`): 2.9.1
* Operating System and version: debian stretch
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

I am running php7.2

**Comment by lippserd** [comment]
Hi,

Thanks for the report. On jessie we depend on php-htmlpurifier which may not get an update for php7. How did you install php7 on jessie? I think it's best to depend on our shipped vendor version of htmlpurifier.

Best,
Eric

**Comment by paladox** [comment]
Hi, I am using stretch.

I installed php 7.2 using 
https://deb.sury.org/

**Comment by paladox** [comment]
I guess this 
https://github.com/ezyang/htmlpurifier/commit/bb7ad665265a29303ec59918f0c1832528bdc509 is the fix.

**Comment by paladox** [comment]
Closing this as it seems to be a upstream issue.

Sorry for not realising this was not in icingaweb2.
