### ISSUE TITLE
Authentication problem while using python 

### ISSUE THREAD

**Issue by lall3** [Icinga/icingaweb2#3551]
So I have been trying to pull json data from the icinga web app. Using the url /icingaweb2/monitoring/list/services?service_problem=1&service_handled=0&sort=service_severity&format=json
I had to use a cookie from the chrome developers tool but that cookie expires and I can autonomously generate a new cookie. 
Base authentication doesn't work.

Does anyone know a fix?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Icinga Web 2 version and modules (System - About):
* Version used (`icinga2 --version`):
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by lippserd** [comment]
Hi,

Maybe you're just missing to send the `Accept: application/json` header. But without posting code, used versions and just a simple "doesn't work", nobody is able to help you. Further, this is does not seem to be an issue with Web 2 in the first place, so please move on to the community channels.

Cheers,
Eric

**Comment by lall3** [comment]
Sorry for the lack of description.

So I do accept json . I was wondering if maybe there was a way to get authentication through python, to pull this data. I get to the url by clicking on services and choosing the json format.
`
cookies = {
    'Icingaweb2': 's2k1n20l54vlng8a45pus5otehh16euo',
}
params = (
    ('format', 'json'),
    ('renderLayout', ''),
)

response = requests.get('http://..../icingaweb2/monitoring/list/services?format=json', cookies=cookies) 
`
This works when I pull the most recent cookie from chromes dev tool tab. I couldnt use the standard authentication provided by the requests library. I even tried changing the ssl context.
