### ISSUE TITLE
Validate user input prior to querying the database.

### ISSUE THREAD

**Issue by mphilipps** [Icinga/icingaweb2#3556]
hi
I just tried to filter the service view for services that are not ok.
So I configured it to:

![icingaweb2_filter](https://user-images.githubusercontent.com/17722151/44031524-8f542a78-9f04-11e8-8111-e30c21ebfbd6.jpg)

## Expected Behavior
A list of services that are not ok.

## Current Behavior

> SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "Ok"
> LINE 5: ...cked IS NULL THEN 99 ELSE ss.current_state END != 'Ok' OR CA...
> ^, query was: SELECT so.name1 AS host_name, h.display_name AS host_display_name, CASE WHEN hs.has_been_checked = 0 OR hs.has_been_checked IS NULL THEN 99 ELSE hs.current_state END AS host_state, so.name2 AS service_description, s.display_name AS service_display_name, CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 99 ELSE ss.current_state END AS service_state, CASE WHEN (ss.scheduled_downtime_depth = 0 OR ss.scheduled_downtime_depth IS NULL) THEN 0 ELSE 1 END AS service_in_downtime, ss.problem_has_been_acknowledged AS service_acknowledged, CASE WHEN (ss.problem_has_been_acknowledged + ss.scheduled_downtime_depth + COALESCE(hs.current_state, 0)) > 0 THEN 1 ELSE 0 END AS service_handled, ss.output AS service_output, ss.perfdata AS service_perfdata, ss.current_check_attempt || '/' || ss.max_check_attempts AS service_attempt, UNIX_TIMESTAMP(ss.last_state_change) AS service_last_state_change, s.icon_image AS service_icon_image, s.icon_image_alt AS service_icon_image_alt, ss.is_flapping AS service_is_flapping, ss.state_type AS service_state_type, CASE WHEN ss.current_state = 0 THEN CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 16 ELSE 0 END + CASE WHEN ss.problem_has_been_acknowledged = 1 THEN 2 ELSE CASE WHEN ss.scheduled_downtime_depth > 0 THEN 1 ELSE 4 END END ELSE CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 16 WHEN ss.current_state = 1 THEN 32 WHEN ss.current_state = 2 THEN 128 WHEN ss.current_state = 3 THEN 64 ELSE 256 END + CASE WHEN hs.current_state > 0 THEN 1024 ELSE CASE WHEN ss.problem_has_been_acknowledged = 1 THEN 512 ELSE CASE WHEN ss.scheduled_downtime_depth > 0 THEN 256 ELSE 2048 END END END END AS service_severity, ss.notifications_enabled AS service_notifications_enabled, ss.active_checks_enabled AS service_active_checks_enabled, ss.passive_checks_enabled AS service_passive_checks_enabled, ss.check_command AS service_check_command FROM icinga_objects AS so
> INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id AND so.is_active = 1 AND so.objecttype_id = 2
> INNER JOIN icinga_hosts AS h ON h.host_object_id = s.host_object_id
> INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = s.host_object_id
> INNER JOIN icinga_servicestatus AS ss ON ss.service_object_id = so.object_id WHERE ((CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 99 ELSE ss.current_state END != 'Ok' OR CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 99 ELSE ss.current_state END IS NULL)) ORDER BY LOWER(s.display_name) ASC LIMIT 25
> 
> SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "Ok"
> LINE 5: ...cked IS NULL THEN 99 ELSE ss.current_state END != 'Ok' OR CA...
> ^

## Possible Solution
If the textinput field is only supposed to accept numbers I shouldn't be able to input other characters. In addition to that the input should be validated on server prior to running it against the database. Also please give us a better error message.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.6.1
* Operating System and version: Debian stretch

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This issue will be fixed as part of #3631.

Best,
Eric
