### ISSUE TITLE
Announcements should be more visible

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2#3560]
The announcements look like just another bookmark bar in the Browser. Since Announcements are more less important information for the user they should be more visible. 

## Possible Solution
- Colorize
- Maybe something like that: https://css-tricks.com/examples/PopFromTopMessage/

## Steps to Reproduce (for bugs)

1. Create an announcement
2. Ask your colleagues if they have noticed new the annoucment ;)

**Comment by theFeu** [comment]
Sort of related to the issue here: the <ul id="announcements"> is wrapped by a <div id="announcements"> which doesn't seem right.

**Comment by theFeu** [comment]
We should probably evaluate how much importance we want to give to the announcements.

As in:
- how are they used?
- should they be the first thing you notice?
- do you need to react to them immediately?

Despite that, if we want to keep them sort of the way they are, just slightly more noticable I would suggest painting them in a more "notification-specific" colour with a drop-shadow, like so:

![image](https://user-images.githubusercontent.com/22217062/58424464-b95fef80-8097-11e9-8ee9-06ce77c2d13b.png)

**Comment by flourish86** [comment]
Let's consider increasing the font-size. Maybe this should already do it, so we don't need the yellow background.

![Screenshot 2019-06-05 at 16 16 44](https://user-images.githubusercontent.com/6977434/58963519-9b883e00-87ad-11e9-9482-b72954057946.png)

**Comment by flourish86** [comment]
By the way: Notifications at the bottom, also have the bigger font-size.

![Screenshot 2019-06-05 at 17 10 14](https://user-images.githubusercontent.com/6977434/58967675-e9547480-87b4-11e9-90b6-19a1ab1c9c45.png)

**Comment by nilmerg** [comment]
> By the way: Notifications at the bottom also have the bigger font-size.

And got a colored background. That's what this is all about isn't it? I mean, what's the better way to draw attention to important things if not with a color? (Without a *ring-ring-ringelin* sound or a *right-in-your-face* popup)

The fact that announcements didn't have a color like our other notifications has already left me wondering why ever since. So I support applying a colored background to them.

**Comment by dnsmichi** [comment]
Yellow always reminds me of a warning state, I don't really like that at the bottom itself - scheduling a check isn't something which really needs my attention. A more sensible, maybe even transparent overlay with green or blue looks better imho. In contrast to that, a problem with webserver connection loss or anything else should still be red, that's good.

The same goes for an announcement - it should be visible and standalone at the top, but not ring the alarm bells. Maybe an announcement could get different states and as such, different colors. Like `info` - blue, `warn` - yellow, `crit` - red.

When you look at Discourse for instance, an announcement banner is in transparent blue, draws attention, but not too offensive. Ignore the height of the example, that's too big imho.

![Screen Shot 2019-06-06 at 09 20 38](https://user-images.githubusercontent.com/382049/59014224-67a82980-883c-11e9-8040-afb25539fcb2.png)

**Comment by theFeu** [comment]
![image](https://user-images.githubusercontent.com/22217062/59033623-65a88f80-8869-11e9-9fd6-cf06c6f75e34.png)

no padding to the right, the closing x is overlapped

**Comment by lippserd** [comment]
I also opt for just increasing the font-size. The yellow background makes it kind of a warning as @dnsmichi said. If we follow this, our other notifications should not have the yellow background too.
