### ISSUE TITLE
showFullscreen/showCompact on Dashboard having a BusinessProcess on it doesn't work

### ISSUE THREAD

**Issue by snoopyf** [Icinga/icingaweb2#3563]
## Expected Behavior
FullScreen / Compact Mode should work with BusinessProzesses as Dashlets on a Dashboard pane

## Current Behavior
When showing a Dashboard Pane which holds a Business Process (no matter if togehter with other Dashlets or not) with URL Parameters "showFullscreen&showCompact" shows the left menu and the titlebar (but this without pane buttons)

## Steps to Reproduce (for bugs)
1. Create a Business Process
2. Add it to a Dashboard
3. Open the Dashboard and add "showFullscreen&showCompact" to the URL

## Context
We want to build a Dashboard with some BusinessProcesses on it and show this in FullScreen on a bigger Monitor

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.4.2 / businessprocess 2.1.0, doc 2.4.2, monitoring | 2.4.2
* Version used (`icinga2 --version`): r2.7.1-1
* Operating System and version: SLES 12 SP3
* Enabled features (`icinga2 feature list`): api checker command ido-mysql mainlog notification

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This has to be fixed in the businessprocess module. I close this one.

Best,
Eric
