### ISSUE TITLE
Allow to export Alert Summary and Timeline

### ISSUE THREAD

**Issue by WhiteKnight735** [Icinga/icingaweb2#3579]
Feature request: it would be very useful to be able to export notifications and timeline history.  This would comme in handy when making outage reports.  As it is we can not even select text when looking at history.

Alternatively, if we could have a reports section where we can generate reports on alerts history of specific service etc.

Thank you.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. The alert summary and timeline reports are deprecated features in Web 2 because we're in the process of developing a dedicated reporting module. We'll release a first version at the end of this year or at the beginning of the next year.

Best,
Eric
