### ISSUE TITLE
Make array filter method "contains" available for all searches like in director apply rules/assign where

### ISSUE THREAD

**Issue by Gammenon** [Icinga/icingaweb2#3581]
## Description
We work with an array in which "host tags" are stored for that the number of individual host variables get too much out of hand.
In the director this can be used wonderfully with "apply rules" in the "assign where" with "var contains tag". (e.g. for service or host groups)
Unfortunately this filter method cannot be used in the rest of icingaweb2 to dynamically filter a selection based on a certain tag (array element).
This would be an important feature for us.

## Expected Behavior
It should be generally possible to filter/search for array elements in a custom var.

## Current Behavior
custom variables of type Array are not selectable in the Filter dropdown field and there is no option for "contains" in the comparison operators.

## Possible Solution
Perhabs have a look at the method used in the director apply rules and check if it adaptable for the normal search filter

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We can't implement this feature for the current monitoring module because custom var hashes and arrays are written to the database as JSON blob. But we'll provide this feature with Icinga DB (our new data backend) and our new monitoring module. I think that we're ready with this in February or March next year. 

Best,
Eric

refs #2773

**Comment by Gammenon** [comment]
Hi,
thanks for your answer. I see the difficulty in this.

I found out, that it is aleady possible to search/filter for array "parts" by adding * to the search in the URL e.g.:
MyCustomArray=("foo","bar","searchstring","something else")
https://<SERVER>/icingaweb2/monitoring/list/hosts?_host_MyCustomArray=*searchstring*

I know, this is a little bit fuzzy, but that would be enough for us at the moment.
One problem stays the same, the array vars aren't selectable in the dropdown field.

Would it at least be possible to make them accessible in the dropdown?
