### ISSUE TITLE
No hover effect on detail history entries in Safari

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2#3582]
It's not obvious that history list items are interactive (clickable) in Safari.

## Expected Behavior
See current implementation in Chrome (69.0.3497.100)
When hovering a history list item, its background should change to transparent icinga-blue and the cursor should be a pointer.

## Current Behavior
When hovering a history list item, it's background stays unchanged and the cursor is the regular arrow.

## Possible Solution
Change CSS or JS

## Steps to Reproduce (for bugs)
1. Use Icinga Web 2 on Safari, then log in
2. Select a service or host list item
3. Switch to the "History" Tab in Detail View
4. Hover above a list item

## Your Environment
* Icinga Web 2.5.3
* Safari Version 12.0 (14606.1.36.1.9)
* macOS 10.14 (18A391)

**Comment by nilmerg** [comment]
@theFeu There's actually nothing special going on here. An attribute selector `tr[href]:hover` is used for this. As I don't have Safari available please investigate what the issue might be.

**Comment by theFeu** [comment]
I can confirm the bug.
I'll have a look what might cause this

**Comment by theFeu** [comment]
What I found out:

When you turn the :hover (on a specific tr) on and off again in the Safari inspector it works perfectly fine.
Even just hovering the tr in the document afterwards, all of the 'untouched' trs still have the buggy behaviour and need to be 'activated' one by one.

**Comment by nilmerg** [comment]
@flourish86 Please investigate this. I've tried to fix this with the referenced PR but @theFeu meant it does not resolve the issue. Since I've got no Safari here I've no idea where to look further.

**Comment by flourish86** [comment]
It seems like in some constellations, Safari has a problem with invoking the native hover effect due to layering inconsistencies. This can be fixed by adding ´-webkit-transform: translate3d(0,0,0)`.
