### ISSUE TITLE
Icinga Web2 is not showing in the dashboard. It was working before

### ISSUE THREAD

**Issue by vivuu1989** [Icinga/icingaweb2#3590]

**Comment by vivuu1989** [comment]
Version 2.6.1.

The dashboard and overiew panels are not showing any details and before we could monitor the master servers services. After adding one cent os host now nothing is displaying

**Comment by lippserd** [comment]
Hi,

I'm sorry but we can't help you with such a little issue description. If you face this problem again, please open a new issue and provide more information.

Best,
Eric
