### ISSUE TITLE
How to use 24 hours time format?

### ISSUE THREAD

**Issue by kepi** [Icinga/icingaweb2#3595]
I tried to browse through documentation and code but I didn't find any way how to set time format in icingaweb2 to 24 hours.

According to documentation there is no setting in config.ini. There are also no time related settings in "My Account" directly in webapp.

Thanks for any hint.

Btw. there is old issue #268 and related commit 99871e73 which added this to config.ini but it was probably removed later...

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I'm not quite sure which times you're referring to. In most places we're using relative times. Are you talking about them? If you hover those times you should get a tooltip with the time in 24 hour format.

Best,
Eric

**Comment by kepi** [comment]
Sorry, I didn't realize it is unclear. Problem is in forms for downtime, schedule, acknowledgement and possibly others.

![downtimes](https://user-images.githubusercontent.com/105303/48480975-47ffd400-e80c-11e8-9718-e1914ce64dc5.png)

BTW it would be amazing to set time relatively too in this forms (downtime for 15 minutes, 2 hours etc). Its only unpleasant experience in icingaweb2 for us, but its for separate issue.

**Comment by lippserd** [comment]
For date and time inputs we rely on browser features at the moment. So I think this is related to some settings in your browser. We're not in control here. The relative time feature for downtimes will be implemented sooner or later. @ekeih started with that during the OSMC hackathon.

**Comment by kepi** [comment]
Oh, that possibility didn't cross my mind, closing the issue now. Thanks for information.

Happy to hear about relative downtimes!

**Comment by ypid-work** [comment]
> So I think this is related to some settings in your browser.

How can I change this in my browser? Not sure if this is common thing to configure in the browser. It is probably more practical to configure in Icinga. At least that is how other web apps do it. Can you reopen?

**Comment by nilmerg** [comment]
It may also depend on your system settings. That depends on the browser and system.

**Comment by lippserd** [comment]
Chrome doesn't respect the system settings afaik and sets the date format from its configured language.
