### ISSUE TITLE
localization issue

### ISSUE THREAD

**Issue by bedenko** [Icinga/icingaweb2#3596]
## Expected Behavior
Manual check should work

## Current Behavior
When defining _http_vhosts_ (for example) with name "črv", the manual test run with _Check now_ fails with above error.
## Possible Solution
No idea...

## Steps to Reproduce (for bugs)
Following code should be applied and manual check should be executed through Icinga Web
```
vars.http_vhosts["črv"] = {
    http_ssl = true
    http_vhost = "test.com"
    http_address = "test.com"
  }
```

## Context
When defining _http_vhosts_ with some non-english characters, manual check fails with error: 
```
icinga2: Can't send external Icinga command: 404 No objects found.
```

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.1
* Version used (`icinga2 --version`): r2.9.1-1
* Operating System and version: CentOS 7.5
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`): no errors

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Does check now fail for objects that are created form your vhosts variable? Could you please share your apply rule which creates those objects?

Best,
Eric

**Comment by bedenko** [comment]
Apply rule is pretty much generic:
```
apply Service for (http_vhost => config in host.vars.http_vhosts) {
  import "generic-service"
  check_command = "http"
  max_check_attempts = 3
  vars += config
  display_name = "HTTP: " + http_vhost
}
```
and yes, they failed for those checks only.

**Comment by lippserd** [comment]
@bedenko What's the character set of your Icinga 2 database and which charset is configured in Icinga Web 2 for the database resource?

**Comment by bedenko** [comment]
Both icinga_ido and icingaweb_db are configured to use utf8 Character set.
As for database itself:
```
MariaDB [(none)]> SHOW VARIABLES LIKE  'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```
So it appears, that i've messed up right from the beginning, since i would need latin2 or utf8.

Is it possible to convert database charset now (without loosing any data)?

**Comment by lippserd** [comment]
Could you please try latin1 as charset for the ido resource?

**Comment by lippserd** [comment]
@dnsmichi Do we have a charset configuration for the IDO features?

**Comment by dnsmichi** [comment]
@lippserd No, since there's `name1/2` hardcoded in the schema with latin1 as specific requirement, as otherwise case-sensitive object names compares won't work. MySQL already stores garbage when inserting the object name once.

```
MariaDB [icinga]> select * from icinga_objects order by object_id desc limit 1;
+-----------+-------------+---------------+-------+-------+-----------+
| object_id | instance_id | objecttype_id | name1 | name2 | is_active |
+-----------+-------------+---------------+-------+-------+-----------+
|     51721 |           1 |             2 | utf8  | ?rv   |         1 |
+-----------+-------------+---------------+-------+-------+-----------+
1 row in set (0.002 sec)
```

This goes on for many column which store string values (output, notes, etc.). This is something which cannot be fixed in the IDO schema imho.

**Comment by bedenko** [comment]
I have changed charset for ido resource to latin1 and problem is resolved.
I should probably change charset for icingaweb_db also, since it resides on same database.

**Comment by lippserd** [comment]
Please keep the icingaweb resource at utf8. We explicitly define utf8 as charset in the schema here.

I'll close this issue.
