### ISSUE TITLE
Sorry! Failed to set up Icinga Web 2 successfully (again)

### ISSUE THREAD

**Issue by crsprsp** [Icinga/icingaweb2#3600]
I tried to set up a new Icingaweb2 and got the following error: 

![screenshot from 2018-10-24 11-01-25](https://user-images.githubusercontent.com/16636402/47419311-3599f980-d77c-11e8-8ab7-f5785c082140.png)

Database is a MariaDB Version: 5.5.60-MariaDB on REL7.

bye, Rico

**Comment by dnsmichi** [comment]
Which database root user did you provide to create the database? This lacks the permission to create the icingaweb2 db user.

**Comment by crsprsp** [comment]
Used a user who has GRAND ALL privs on the icingaweb2 DB. Should be quite enough...please correct me if i'm wrong. :)

**Comment by KevinHonka** [comment]
if you have a standalone DB with no other DBs on it, just try the root user, which should always work.

**Comment by crsprsp** [comment]
i forgot to mention that it's not a local DB on the Icingabox, it's a remote DB but with a user with enough privs...i thought...

**Comment by crsprsp** [comment]
got it. closed.
