### ISSUE TITLE
Apache reverse proxy URL appended

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [Icinga/icingaweb2#3601]
I'm running an Icinga2 master/webhost on a server that is connected to my edge server by an Apache reverse proxy.

I've added this to my virtualhost:

```
        SSLProxyEngine On
	ProxyPreserveHost On
        ProxyPass /admin/icinga http://192.168.0.28/icingaweb2/
        ProxyPassReverse /admin/icinga http://192.168.0.28/icingaweb2/
        ProxyPassReverseCookieDomain /admin/icinga http://192.168.0.28/icingaweb2/
        ProxyPassReverseCookiePath /admin/icinga http://192.168.0.28/icingaweb2/
```

This is a working proxy but Icinga redirects _example.com/admin/icinga_ to _example.com/icingaweb2/authentication/login_.

If I put it in a subdomain it has the same problem. If I make the ProxyPass path _/icingaweb2_ it has a redirect loop.

How do I fix this?

**Comment by dnsmichi** [comment]
Please don't do cross-posts. I'm closing here in favour of https://monitoring-portal.org/t/apache-reverse-proxy-url-appended/4750

**Comment by Dzordzu** [comment]
Yep. The link is dead
