### ISSUE TITLE
BG Color of acknowledged Hosts in Hostgroups not working

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2#3603]
I all,
in my company theme, I have re-defined the color for down Hosts from red to black as it was written by @lippserd once at https://github.com/Icinga/icingaweb2/issues/2259 .
```
.state-down {
  background-color: black !important;

  &.handled {
    border-color: black !important;
    background-color: @body-bg-color !important;
  }
}
```
This works in /list/hosts?host_problem=1&host_acknowledged=0&host_in_downtime=0 and /list/hosts?host_acknowledged=1, also in /list/hostgroups for "not acknowledged hosts" but the acknowledged hosts have white text on white background, Shouldn't this be grey or sth. like this like all the other acknowledged services?
![image](https://user-images.githubusercontent.com/7324088/47547507-fd1e2b00-d8f5-11e8-847d-71a7279eb2bf.png)

If you want black font on white BG, you need to add color to the handled part.

```
.state-down {
  background-color: black !important;

  &.handled {
    border-color: black !important;
    background-color: @body-bg-color !important;
    color: black
  }
}
```

I don't know if this breaks anything or if there is a better solution. Just wanted to post this here, if someone else will get in this situation. Any advices are welcomed :)

**Comment by lippserd** [comment]
Hi,

I'm not quite sure how to help. Again, our community channels are the right place for such stuff.

Best,
Eric
