### ISSUE TITLE
Icingaweb 2 shows also inactive Services in Service count

### ISSUE THREAD

**Issue by afeefghannam89** [Icinga/icingaweb2#3608]
## Expected Behavior
Icinga Web 2 show only active services in Service count.

## Expected Behavior
Icinga Web2 shows services although they are inactive in Icinga Databases. 

![screenshot from 2018-10-30 09-01-06](https://user-images.githubusercontent.com/39904920/47705739-b7c86900-dc27-11e8-8498-8ef1231b0d80.png)
![screenshot from 2018-10-30 09-21-58](https://user-images.githubusercontent.com/39904920/47705745-bdbe4a00-dc27-11e8-91aa-c4ad6742033b.png)

![screenshot from 2018-10-30 09-42-23](https://user-images.githubusercontent.com/39904920/47706022-7dab9700-dc28-11e8-9d66-9c9ca24c2ca3.png)

## Steps to Reproduce (for bugs)
1. Create service in a configuration directory
2. Remove the include of the directory from configuration
3. Services are gone from Service views but still in the Service count at the Host.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.6.1
* Version used (`icinga2 --version`): 2.9.1
* Operating System and version: CentOS 7

**Comment by lippserd** [comment]
Hi,

You've managed to create a new Icinga instance. Please have a look at instance_id in your database. There are some views/queries in Web 2 which are able to distinguish between instances but that's not guaranteed. I doubt that this is going to be fixed anytime soon. I'm closing here.

Best,
Eric
