### ISSUE TITLE
Reload filter only after applying it

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icingaweb2#3613]
## Expected Behavior

When creating a (complex) filter the page is only reloaded after I pressed the "Apply" button.

## Current Behavior

The page is reloaded every time when an element changes.

## Steps to Reproduce (for bugs)

1. Click on "Modify this filter"
2. Add an element
3. See the page reload

## Context

A reload with (really) many services is slow. Thus creating a complex filter takes too much time.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.1
* Version used (`icinga2 --version`): 2.9.2
* Operating System and version: Debian stretch

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This is indeed a good feature for big environments or complex filters.

Best,
Eric

**Comment by lippserd** [comment]
Part of #3631
