### ISSUE TITLE
icingaweb2 install

### ISSUE THREAD

**Issue by MrLiNk** [Icinga/icingaweb2#3618]
Hey,

`FEHLER: Zend_Db_Statement_Exception in /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php:225 with message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'icinga.icingaweb_group' doesn't exist, query was: SELECT COUNT(*) AS cnt FROM icingaweb_group AS g WHERE (g.name = 'Administratoren')`

i get this error, anybody can help?

**Comment by dnsmichi** [comment]
Please move such questions with wrong database name configuration onto the community channels.
