### ISSUE TITLE
Main layout is broken without JS

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#3629]
## Expected Behavior
Basic functionality should be available without JS, page should look good.

## Current Behavior
It looks ugly, we broke this with v2.5

## Steps to Reproduce (for bugs)
Disable JavaScript, load the page

**Comment by lippserd** [comment]
Fix broke announcements.

**Comment by theFeu** [comment]
I noticed, that in the detail views there is very little space between the tabs and the content in the controls div. With JS enabled there is a div with the class 'tabs-spacer'.

**Comment by theFeu** [comment]
Without JS the dropdown is also without functionality:

![uselessbutton](https://user-images.githubusercontent.com/22217062/58172167-19b9f000-7c98-11e9-9737-f00a6a91d2a2.jpg)

**Comment by theFeu** [comment]
Todo here:
- announcements break the tab bar
- when trying to close an announcement things break as well
- print to pdf doesn't exactly work either
- 'monitoring-statusbar' in the footer is too wide
- clicking on an event in the event history doesn't work

**Comment by theFeu** [comment]
Layout problems will be fixed with #3810

still consisting issues:
* generated pdfs look off
* multi-select but this should be tackled in #3742

**Comment by nilmerg** [comment]
> * clicking on an event in the event history doesn't work

Is covered by #3804.
