### ISSUE TITLE
Menu header is repainted on page load

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#3630]
## Expected Behavior
No flickering on page load

## Current Behavior
Menu is repainted in an ugly way. This is related to #3629

## Steps to Reproduce (for bugs)
Reload the page, watch.

## Your Environment
It behaves like this since Icinga Web 2.5

**Comment by lippserd** [comment]
Fix broke announcements.

**Comment by theFeu** [comment]
Will be fixed with #3810

**Comment by nilmerg** [comment]
Gets possibly better with #3810. Postponed for v2.8 therefore.

**Comment by nilmerg** [comment]
Duplicate of #3683
