### ISSUE TITLE
need to implement health check in icinga2

### ISSUE THREAD

**Issue by automation777** [Icinga/icingaweb2#3642]
Hi , 

can anyone help me in implementing health check for website ---https endpoints in icinga2

**Comment by lippserd** [comment]
Hi,

Please visit https://icinga.com/community/ for channels where to ask such questions. But be advised that nobody might help you if you do not share what you've already tried and what exactly you want to achieve.

Cheers,
Eric

**Comment by automation777** [comment]
Hi I already implemented health check for my website but while accessing this site I am getting 503 error page after getting logged in sometimes but I didn't any change in Icinga2, beacuse of that I need help
