### ISSUE TITLE
Announcements API with custom author field

### ISSUE THREAD

**Issue by fedepires** [Icinga/icingaweb2#3644]
We are using announcements to mark deployments currently in progress in the UI. Before the new API (in https://github.com/Icinga/icingaweb2/pull/2754) we were just creating the files with a script, which allowed us to use an author field with any name, that doesn't necessarily need to be a valid user in icingaweb. It would be nice if you could support that in the API, so we can have announcements of deployments from people without a valid user in icingaweb.

Thanks!

**Comment by lippserd** [comment]
Hi,

Sounds good. We'll consider this for our next feature release.

Best,
Eric
