### ISSUE TITLE
Disable zone 

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2#3646]
Hi,

Is there any way to disable a zone from checks? 

Our situation is that we temporary shut down a location because of relocation and we don't want to see that zone at all in icinga2 but we don't want to delete anything since soon will be up again.

At least can we exclude the zone for the Cluster HA and Cluster Zone services?

Thanks

**Comment by lippserd** [comment]
Hi,

Please head over to our community support channel: https://community.icinga.com.

Best,
Eric
