### ISSUE TITLE
Filter not preserved when navigating away from the host-/servicegrid

### ISSUE THREAD

**Issue by gasmick** [Icinga/icingaweb2#3664]
Same as #3586, but now in Grid View mode. In the Hostgroups dashlet, Grid View, the link at the name of a hostgroup in the list doesn't respect filters. The buttons for hosts and services do it correctly, so the button of the hostgroup name shoud do it, too.

## Expected Behavior

In the Hostgroups dashlet, Grid View, if you set the filter on some custom variable, and then click on the name of a hostgroup in the resulting list, you should get the list of all hosts with the filter applied.
## Current Behavior

In the Hostgroups dashlet, Grid View, if you set the filter on some custom variable, you get the list filtered correctly.
But when you click on the name of a hostgroup in this resulting list, the output list will not be filtered.
## Steps to Reproduce (for bugs)

1. Go to Hostgroups dashlet. 
2. Toggle (by the way, not _Toogle_) Grid View
3. Set a filter on a custom variable
4. Click on the name of a hostgroup in the filtered list
5. Look on the button with the number of hosts, see the difference

## Context

The users create elaborate filters for the hostgroups dashlet, Grid View, and want to see the members of the hostgroup filtered. 

## Your Environment

Icinga Web 2 version and modules (System - About): 2.6.2
Version used (icinga2 --version): r2.10.2-1
Operating System and version: Ubuntu 18.04.1 LTS

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll fix this one asap.

Best,
Eric
