### ISSUE TITLE
Dashboard empty after initial install

### ISSUE THREAD

**Issue by sitilge** [Icinga/icingaweb2#3669]
After initially installing the icinga2 + icingaweb2 + nginx on arch linux, there is no output on the main dashboard. It is empty, only "No services found matching the filter." displayed.

Is there something else that should be configured?

````
version: v2.10.2-164-g21a592acd
Kernel version: 4.20.3-a  Config directory: /etc/icinga2
Data directory: /var/lib/icinga2
Log directory: /var/log/icinga2
Cache directory: /var/cache/icinga2
Spool directory: /var/spool/icinga2
Run directory: /run/icinga2
````

**Comment by lippserd** [comment]
Seems like Icinga is not writing to the database. If you have further questions please head over to our community support channels.

**Comment by lippserd** [comment]
community.icinga.com
