### ISSUE TITLE
Document dashboard.ini

### ISSUE THREAD

**Issue by fireba11** [Icinga/icingaweb2#3674]
There is zero documentation on possible config values in a dashboard.ini
I currently was inrerested if i can set a dashlet to a height of two rows to arrance my dashlets nicely, but apparently apart from looking at an existing dashboards ini-file there is no way to find out what options there are without reading half the codebase for it ...

**Comment by lippserd** [comment]
The GUI shows all available configuration options. There is really not much one can do here. But we're about to change dashboard management and sharing so there will be more options and documentation in the future.
