### ISSUE TITLE
icingaweb2 test cases failures

### ISSUE THREAD

**Issue by srajmane** [Icinga/icingaweb2#3675]
## Current Behavior

I am installing icingaweb2 v2.6.2 , referring https://github.com/Icinga/icingaweb2/blob/v2.6.2/doc/20-Advanced-Topics.md#installing-icinga-web-2-from-source-

Also I am running test cases using 

> ./bin/icingacli  test php unit

But I am facing 6 test case failures,

> There  were 6 failures:

>1)Tests\Icinga\Application\ConfigTest::testWhetherFromIniThrowsAnExceptionOnInsufficientPermission
Failed asserting that exception of type "Icinga\Exception\ConfigurationError" matches expected exception "Icinga\Exception\NotReadableError". Message was: "Couldn't parse the INI file `/etc/shadow'" 

> 2) Tests\Icinga\File\Storage\LocalFileStorageTest::testCreateThrowsNotWritableError
Failed asserting that exception of type "Icinga\Exception\AlreadyExistsException" matches expected exception "\Icinga\Exception\NotWritableError". Message was: "Couldn't create the file "foobar": ErrorException: fopen(/notwritabledirectory/foobar): failed to open stream: File exists in /icinga/icingaweb2/library/Icinga/File/Storage/LocalFileStorage.php:59

> 3)Tests\Icinga\File\Storage\LocalFileStorageTest::testReadThrowsNotReadableError
Failed asserting that exception of type "\Icinga\Exception\NotReadableError" is thrown.

> 4)Tests\Icinga\File\Storage\LocalFileStorageTest::testUpdateThrowsNotWritableError
Failed asserting that exception of type "\Icinga\Exception\NotWritableError" is thrown.

> 5)Tests\Icinga\File\Storage\LocalFileStorageTest::testDeleteThrowsNotWritableError
Failed asserting that exception of type "\Icinga\Exception\NotWritableError" is thrown.

> 6)Tests\Icinga\Web\Form\Validator\WritablePathValidatorTest::testValidateInputWithNonWritablePath
Failed asserting that true is false.

FAILURES!
Tests: 348, Assertions: 2219, Failures: 6, Skipped: 21, Incomplete: 7.

## Your Environment

* Version used (`icinga2 --version`): v2.10.2
* Operating System and version:Ubuntu 16.04 amd64

**Comment by dnsmichi** [comment]
Same as with icinga/icinga2#6923 - why not use the official Ubuntu packages?

**Comment by srajmane** [comment]
That's all good but i am interested in building from source and executing the tests manually.
and I am facing issues at the test part and needs info on what is being missed .

**Comment by lazyfrosch** [comment]
This sounds like you are running the tests as root...

Those errors are expected to occur on non-root users, and catched in tests.

Please try `./bin/icingacli test php unit` as any other user that is part of the `icingaweb2` group of `/etc/icingaweb2`

This should probably be an error, that tests should not be run as root...
