### ISSUE TITLE
History Event Grid should offer better input

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2#3681]
## Expected Behavior

Event Grid should offer:
* Open selection for timeperiod start and end
* Filtering by host and service properties

## Current Behavior

You can only select certain inputs by dropdown:
![bildschirmfoto von 2019-02-07 11-44-42](https://user-images.githubusercontent.com/121874/52406397-e5963700-2acd-11e9-81f0-897cc5e904a5.png)

ref/NC/590161

**Comment by lippserd** [comment]
We will tackle this view with our new monitoring module for the Icinga DB. The current view won't be touched unfortunately. I close this one.
