### ISSUE TITLE
MySQL query fails in History section because of collation issue

### ISSUE THREAD

**Issue by northbear** [Icinga/icingaweb2#3682]
Hi, guys 

Icingaweb2 provides MySQL backtrace error messages in sections "History"->"Event Overview" and "History"->"Timeline". In all other sections it looks all works fine. 
Error message is about illegal mix of collations (*latin1_general_ci* and *utf8mb4_0900_ai_ci*). It looks strange because default character set and collation used in icingaweb2 mysql database are defined as **utf8mb4** and **utf8mb4_unicode_ci** respectively. Default charset of PHP is also UTF8. 

So I have no idea collation latin1_general_ci managed to be hardcoded in SQL queries. Another question is where it takes *utf8mb4_0900_ai_ci* collation if it doesn't match defaults used?

```
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_general_ci,EXPLICIT) and (utf8mb4_0900_ai_ci,COERCIBLE) for operation 'UNION', query was: SELECT eh.id, eh.host_name, eh.host_display_name, eh.service_description, eh.service_display_name, eh.object_type, eh.timestamp, eh.state, eh.output, eh.type FROM (SELECT sth.id, sth.timestamp, sth.output, sth.type, sth.state, sth.object_type, sth.host_name, sth.service_description, sth.host_display_name, sth.service_display_name FROM (SELECT hh.statehistory_id AS id, ('host') AS object_type, h.display_name COLLATE latin1_general_ci AS host_display_name, ho.name1 AS host_name, NULL AS service_description, NULL AS service_display_name, NULL AS service_host_name, (CASE WHEN hh.state_type = 1 THEN 'hard_state' ELSE 'soft_state' END) AS type, UNIX_TIMESTAMP(hh.state_time) AS timestamp, hh.object_id, hh.state, (CASE WHEN hh.state_type = 1 THEN hh.output ELSE '[ ' || hh.current_check_attempt || '/' || hh.max_check_attempts || ' ] ' || hh.output END) AS output FROM icinga_statehistory AS hh
INNER JOIN icinga_objects AS ho ON ho.object_id = hh.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id WHERE (hh.state_time >= '2019-01-31 15:36:32') UNION ALL SELECT sh.statehistory_id AS id, ('service') AS object_type, h.display_name COLLATE latin1_general_ci AS host_display_name, so.name1 AS host_name, so.name2 AS service_description, s.display_name COLLATE latin1_general_ci AS service_display_name, so.name1 AS service_host_name, (CASE WHEN sh.state_type = 1 THEN 'hard_state' ELSE 'soft_state' END) AS type, UNIX_TIMESTAMP(sh.state_time) AS timestamp, sh.object_id, sh.state, (CASE WHEN sh.state_type = 1 THEN sh.output ELSE '[ ' || sh.current_check_attempt || '/' || sh.max_check_attempts || ' ] ' || sh.output END) AS output FROM icinga_statehistory AS sh
INNER JOIN icinga_objects AS so ON so.object_id = sh.object_id AND so.is_active = 1 AND so.objecttype_id = 2
INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id
INNER JOIN icinga_hosts AS h ON h.host_object_id = s.host_object_id WHERE (sh.state_time >= '2019-01-31 15:36:32')) AS sth UNION ALL SELECT dsh.id, dsh.timestamp, dsh.output, dsh.type, dsh.state, dsh.object_type, dsh.host_name, dsh.service_description, dsh.host_display_name, dsh.service_display_name FROM (SELECT hdh.downtimehistory_id AS id, ('host') AS object_type, h.display_name COLLATE latin1_general_ci AS host_display_name, ho.name1 AS host_name, NULL AS service_description, NULL AS service_display_name, NULL AS service_host_name, ('dt_start') AS type, UNIX_TIMESTAMP(hdh.actual_start_time) AS timestamp, hdh.object_id, (-1) AS state, ('[' || hdh.author_name || '] ' || hdh.comment_data) AS output FROM icinga_downtimehistory AS hdh
INNER JOIN icinga_objects AS ho ON ho.object_id = hdh.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id WHERE (hdh.actual_start_time > '1970-01-02 00:00:00') AND (hdh.actual_start_time >= '2019-01-31 15:36:32') UNION ALL SELECT sdh.downtimehistory_id AS id, ('service') AS object_type, h.display_name COLLATE latin1_general_ci AS host_display_name, so.name1 AS host_name, so.name2 AS service_description, s.display_name COLLATE latin1_general_ci AS service_display_name, so.name1 AS service_host_name, ('dt_start') AS type, UNIX_TIMESTAMP(sdh.actual_start_time) AS timestamp, sdh.object_id, (-1) AS state, ('[' || sdh.author_name || '] ' || sdh.comment_data) AS output FROM icinga_downtimehistory AS sdh
INNER JOIN icinga_objects AS so ON so.object_id = sdh.object_id AND so.is_active = 1 AND so.objecttype_id = 2
```

## Our Environment
The application is running on OS: CentOS 7.5 
Icinga Web 2 Version 2.6.2 
Git commit: 63cb9d728338225833884fda2c312a5a9f431fd6
Git commit date: 2018-11-21
Icinga2 --version: 
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-957.1.3.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
icinga2 feature list
```
Disabled features: compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql mainlog notification
```

Screenshouts attached below:

![icingaweb2-history-event-overview](https://user-images.githubusercontent.com/65731/52416133-9235e000-2af1-11e9-9634-83d63adf1389.PNG)
![icingaweb2-history-timeline](https://user-images.githubusercontent.com/65731/52416141-95c96700-2af1-11e9-896b-35ed607ece0f.PNG)

**Comment by ABaumgaertner** [comment]
+1 - same here
Ver 8.0.15 for Linux on x86_64 (MySQL Community Server - GPL)
Oracle Linux 7.6 
Linux 4.1.12-124.24.1.el7uek.x86_64 #2 SMP Wed Jan 2 14:29:32 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
icinga2  r2.10.2-1
Icinga Web 2 Version 2.6.2

grep -l -i -R "collate latin1_general_ci"
modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatusQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HoststatehistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/GroupsummaryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatehistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommenthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimeQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ContactgroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServiceflappingstarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicenotificationQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicestatusQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostnotificationQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcommenthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimestarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicegroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcommentQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicedowntimeQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/CustomvarQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostcontactQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostdowntimestarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostflappingstarthistoryQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecontactQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php
modules/monitoring/library/Monitoring/Backend/Ido/Query/ServicecommentQuery.php

**Comment by nilmerg** [comment]
Hi,

first we need to clear some things up:

* The queries mentioned access the IDO, not Icinga Web 2's database
* In case of the IDO, only `latin1` is supported as charset

You seem to have mixed up some of the tables with a different encoding. Also note that the database's *default* encoding may be overridden on table level.

For more information please read the discussion [here](https://github.com/Icinga/icinga2/issues/5412).

**Comment by erpo41** [comment]
I found a workaround for this issue, and because this was one of three hits while googling the error message, I'm going to post it here.

In my case, this is what happened:
* Icinga2 and icingaweb2 worked without issues immediately after installing them on Ubuntu 18.04 according to the official instructions.
* Upgrading to Ubuntu 19.10 for unrelated reasons left icinga2 and icingaweb2 mostly functional.
* As part of the upgrade, mysql 5.x was replaced with mysql 8.0.
* After the upgrade, clicking a service in icingaweb2 and then clicking the History tab resulted in a very long error message starting with "General error: 1267 Illegal mix of collations (latin1_general_ci,EXPLICIT) and (utf8mb4_0900_ai_ci,COERCIBLE) for operation" instead of the history I was expecting.

The solution was:
* Make a backup of /etc/mysql/mysql.conf.d/mysqld.cnf.
* Open mysqld.cnf in an editor.
* In the [mysqld] section, add the line character-set-server=latin1
* Save the file and close the editor.
* Run sudo systemctl restart mysql

After performing those steps, clicking the History tab on a service showed the history I was expecting. However, I recommend exercising caution before using this workaround for the following reasons:

* It was the result of a lucky guess, and I don't claim to have a full understanding of the effect it will have on mysql or icinga2. It may have resolved that error while causing other problems that are not as evident. Because I'm just running icinga2 for fun, this was not a problem for me, but it may be a problem for people who depend on icinga2 for something serious.

* Setting this variable affects all clients connecting to mysql. In my case, there were no other applications using the same database server to worry about, but people running multiple applications may want to think about how this configuration would affect them.

* There may be better workarounds that I did not try, such as downgrading mysql or doing a fresh install on Ubuntu 19.10.

* Unicode is great, so this is kind of throwing the baby out with the bath water.

**Comment by nilmerg** [comment]
@erpo41 The proper solution is to configure `latin1` as the charset for the IDO connection. Do this in the resource configuration of Icinga Web 2.
