### ISSUE TITLE
Make notes markdown-aware

### ISSUE THREAD

**Issue by sjulez** [Icinga/icingaweb2#3684]
## Expected Behavior
Every Service we monitor gets a very detailed description of what has to be done if the service enters warning oder critical states. These descriptions can contain links to other resources.

## Current Behavior
Currently there is no way to provide links in notes to services or even highlight important things about the description to the service.

## Possible Solution
The Director should be able to render markdown (for example).

**Comment by Thomas-Gelf** [comment]
I transferred this issue to the Icinga Web 2 project

**Comment by ekeih** [comment]
This would be awesome for notes and acknowledgment comments!

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This sounds like a good addition 👍 

Best,
Eric

**Comment by dnsmichi** [comment]
Sounds very good, and we can probably use the code available in Icinga Exchange :)
