### ISSUE TITLE
Make unit conversion configurable

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2#3685]
Icinga Web 2 shows the performance data of checks and converts the output which is a nice thing. e.g. you see the filling level of harddisks shown in gibibytes.

It would be nice to have an option for configuring how this conversion is done. Especially a global default *and* per user.

Some options that seem to be useful:
* raw data
* automatic (GiB,MiB,...)
* automatic (GB,MB,...)
* fixed (with a field to chose one of several supported units)

This needs to be choosable for every unit support as UOM by monitoring plugins.

**Comment by widhalmt** [comment]
ref/NC/600397

**Comment by lippserd** [comment]
Hi,

I close this in favor of #3690 because we should automatically use the appropriate binary prefix.

Best,
Eric
