### ISSUE TITLE
File Upload fails on PHP 7.2 because of count(null)

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#3689]

**Comment by gjongenelen** [comment]
Why is this commit not released yet? Facing this error on  Icingaweb 2.6.3 at php7.3

**Comment by nilmerg** [comment]
@gjongenelen It's been overlooked while backporting 7.x related fixes for v2.6.3. :roll_eyes: 

@Thomas-Gelf Please create a PR or set at least a milestone next time.
