### ISSUE TITLE
Use auto-detected binary prefix (SI/IEC) for perf data display

### ISSUE THREAD

**Issue by lippserd** [Icinga/icingaweb2#3690]
We always use the IEC prefixes for perf data display. This is wrong for disk checks for example. But we could automatically detect whether to use SI or IEC prefixes from the perf data units.

**Comment by lippserd** [comment]
Stalled until Icinga 2 supports writing UOMs with the IEC prefix.

**Comment by nilmerg** [comment]
Superseded by https://github.com/Icinga/icingadb-web/issues/71
