### ISSUE TITLE
Checks that are only checked at specific timeslots are marked as late results

### ISSUE THREAD

**Issue by rafiwui** [Icinga/icingaweb2#3696]
## Expected Behavior
A service that is only checked eg. between 16:00 and 18:00 should set its *Next check* variable to 16:00 and should not appear in the "late service check results"-dashlet.

## Current Behavior
The *Next check* is showing (in our case) one minute after the last check even though it is out of the checking period. (The example below was changed from 06:00-08:00 to 16:00-18:00, thats why the last check was at 07:59)
![image](https://user-images.githubusercontent.com/9059431/53175404-2886fd00-35ec-11e9-9bfa-ebf1fba91b58.png)

Also the check is listed in the "late service check results"-dashlet.
![image](https://user-images.githubusercontent.com/9059431/53175585-916e7500-35ec-11e9-80fa-49605f5cc9c7.png)

## Steps to Reproduce
1. Create a timeperiod
2. Assign it to a service check
3. Wait until the checking period is over

## Context
It is not that annoying because we barely never use the Overdue dashboard but it is a bit confusing when you check one of your services and it tells you that it should have been checked hours ago (even though it shouldn't).

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.6.2, using Director -> current master
* Version used (`icinga2 --version`): r2.10.2-1
* Operating System and version: CentOS 7

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We consider this for our next feature release.

Best,
Eric
