### ISSUE TITLE
Removing leading and trailing whitespaces in search input field

### ISSUE THREAD

**Issue by dbu1986** [Icinga/icingaweb2#3697]
## Expected Behavior

Pasting a host name or service name into the search input field should return the result, regardless of leading or trailing whitespaces.

## Current Behavior

The search result does not contain the searched object. It only shows results for the director config object at "Host configs:". Removing leading and trailing whitespaces manually will make the search return the desired results.

## Possible Solution

Trimming the search input value before executing the lookup. It looks like the search mechanism for director config objects already does so. Maybe this can easily be adapted for monitoring objects.

## Steps to Reproduce (for bugs)

1. Assume you have an existing host like HostA.
2. Type "HostA " into the search input field
3. Check the results: HostA will not be listed at "Hosts:", but at "Host configs:".
4. Manually remove leading and trailing whitespaces in the search input, and HostA will also be listed at "Hosts:".

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.1
* Version used (`icinga2 --version`): r2.9.1-1
* Operating System and version: * RHEL 7.5
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by nilmerg** [comment]
Hi, thanks for the report.

We'll handle this as part of #3631.

Closed as duplicate.
