### ISSUE TITLE
Custom Plugins

### ISSUE THREAD

**Issue by kishorek353** [Icinga/icingaweb2#3698]
As per the process i have been added the service and commands as per the below format;

Service.conf
apply Service "load" {
import "generic-service"
check_command = "check_load"
/*command_endpoint = host.vars.remote_client*/

assign where host.name  == "Windows_1"

}

Commands.conf

object CheckCommand "check_load" {
import "plugin-check-command"
command = [ PluginDir + "/check_load.exe" ]
arguments = {
"-w" = "40%"
"-c" = "50%"
}
}

At last the services has been added too Icingaweb2 

![image](https://user-images.githubusercontent.com/47882867/53228475-58dfa180-36a7-11e9-9040-60d565901304.png)

Kindly tell me whether the arguments are correct or not .

And give me the solution to resolve it .

**Comment by pcasis** [comment]
Hello,

For this kind of questions, please open a topic on https://monitoring-portal.org/

Regards

**Comment by nilmerg** [comment]
Or the official https://community.icinga.com one.
