### ISSUE TITLE
Multiline values in ini files broken

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#3705]
Since 86ae8c12d multiline values in ini files cause the UI to badly crash.

There's at least one native way (announcements) with which to get newlines into ini files using the UI.

**Comment by widhalmt** [comment]
ref/NC/602603

**Comment by widhalmt** [comment]
ref/NC/603991

**Comment by ekeih** [comment]
@nilmerg Thanks for fixing several of the ini-file issues! Currently this blocks our update to 2.6.2.
Do you have any idea when you will release 2.7.0? Or would it be possible to release a bugfix release 2.6.3 to fix the ini-file issues from 2.6.2?
Either way: Thank you for fixing it! :)

**Comment by nilmerg** [comment]
@ekeih 2.7 is still way off. A 2.6.3 is more likely, though not planned yet. But that's currently on schedule and an appropriate milestone may be created soon.

**Comment by ekeih** [comment]
@nilmerg Thanks for the feedback! :)
