### ISSUE TITLE
Resetting admin password on icingaweb2

### ISSUE THREAD

**Issue by lloydwilke** [Icinga/icingaweb2#3709]
## Expected Behavior
reset password from within the database or icingacli setup command

## Current Behavior
Icingacli setup token create doesnt work and the openssl passwd -1 "yoursecurepassword" command doesnt generate a working password

## Steps to Reproduce (for bugs)

1. openssl passwd -1 "yoursecurepassword"
2. create a new account in icingaweb_user
3. Login to mysql
4.

## Your Environment
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.3-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later http://gnu.org/licenses/gpl2.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
Platform: CentOS Linux
Platform version: 7 (Core)
Kernel: Linux
Kernel version: 3.10.0-957.5.1.el7.x86_64
Architecture: x86_64

Build information:
Compiler: GNU 4.8.5
Build host: unknown

Application information:

General paths:
Config directory: /etc/icinga2
Data directory: /var/lib/icinga2
Log directory: /var/log/icinga2
Cache directory: /var/cache/icinga2
Spool directory: /var/spool/icinga2
Run directory: /run/icinga2

Old paths (deprecated):
Installation root: /usr
Sysconf directory: /etc
Run directory (base): /run
Local state directory: /var

Internal paths:
Package data directory: /usr/share/icinga2
State path: /var/lib/icinga2/icinga2.state
Modified attributes path: /var/lib/icinga2/modified-attributes.conf
Objects path: /var/cache/icinga2/icinga2.debug
Vars path: /var/cache/icinga2/icinga2.vars
PID path: /run/icinga2/icinga2.pid

**Comment by nilmerg** [comment]
Hi,

`Icingacli setup token create` does not create a password to log into Icinga Web 2. It's solely being used to access the web-wizard.

`openssl` cannot be used anymore to generate passwords. Take a look into the documentation for details: https://github.com/Icinga/icingaweb2/blob/master/doc/20-Advanced-Topics.md#advanced-topics-authentication-tips-manual-user-database-auth

Though, if you still can access Icinga Web 2 using the current password it may be easier to just login and change the password within the preferences.

**Comment by lloydwilke** [comment]
The problem is that the password set is either incorrect or not working and we cannot login to change it.
That is why an attempt was made to reset the setup to create a new account or to reset the password from within the database

--

Regards

Lloyd Wilke
Linux Specialist

Bayport International Group Support
Cell: +27 (0)72 392 3887<tel:+270723923887> | Tel: +27 (0)11 236 7300<tel:+270112367300>
Fax: +27 (0)11 234 9285<tel:+270112349285> | lloydw@bayportfinance.com<mailto:lloydw@bayportfinance.com>
<http://www.bayportfinance.com/><http://www.bayportfinance.com/><http://www.bayportfinance.com/>www.bayportfinance.com<http://www.bayportfinance.com>

-----Original Message-----
