### ISSUE TITLE
Quicker entry for array fields

### ISSUE THREAD

**Issue by oakwhiz** [Icinga/icingaweb2#3710]
## Expected Behavior
* It should be possible to populate arrays easily in bulk, for example by pasting a list containing newline characters to add multiple items simultaneously.
* It should be possible to use a Data List to provide both autocomplete and point-and-click suggestions for arrays, while also allowing arbitrary strings to be entered.

## Current Behavior
* Currently the user must enter array items one at a time, pressing Enter resets the text box so that it must be clicked on again, and as the list becomes longer they have to scroll further down to reach the end each time. This results in a poor user experience when using arrays.
* Data Lists offer a remedy, however with Data Lists you cannot enter arbitrary strings that are not present in the Data List. You also don't get type-to-autocomplete functionality with Data Lists, you are forced to choose using a dropdown menu.

## Context
* A common example of a difficult task for users is entering arrays of network interface names for hosts that cause individual services to be applied automatically to those specific interfaces on those specific hosts.

## Your Environment
* Icinga Web 2 version 2.6.2
* `icinga2 --version` r2.6.0-1
* Debian 9

**Comment by nilmerg** [comment]
Hi, you may want to head over to the [director's](https://github.com/icinga/icingaweb2-module-director/issues) issue tracker instead and re-open it there.
