### ISSUE TITLE
LDAPS authentication ignores custom port setting

### ISSUE THREAD

**Issue by ignasr** [Icinga/icingaweb2#3713]
## Expected Behavior
LDAP resource with LDAPS encryption uses the port that is configured in the 'Port' field.

## Current Behavior
Because of how ldap_connect() works, the port used is always 636 (and the configured port is ignored). See "elsint at yahoo dot com" comment on http://php.net/manual/en/function.ldap-bind.php

## Possible Solution
When LDAPS is used, the $hostname must be concatenated with $port. The line
https://github.com/Icinga/icingaweb2/blob/d00fdf4d19839c916d811bc5caeee63f1299f2ec/library/Icinga/Protocol/Ldap/LdapConnection.php#L1195
should be changed to 
`$hostname = 'ldaps://' . $hostname . ':' . $this->port;`

## Steps to Reproduce (for bugs)
1. in the icingaweb2 GUI, create a new LDAP resource, choose LDAPS and random server (9.9.9.9) and radom port (8888) and random pw as connection parameters
2. on the icingaweb2 instance start tcpdump with `tcpdump -i any host 9.9.9.9 -nn`
3. click "Validate configuration" and watch how tcpdump logs this (notice the wrong port)
```
16:52.100727 IP 10.xx..xx.xx.38266 > 9.9.9.9.636: Flags [S], seq 2868288110, win 26883, options [mss 8961,sackOK,TS val 1034756882 ecr 0,nop,wscale 7], length 0
```
although this is (wrongly) logged by icingaweb2:
```
Mar 08 18:16:57 host icingaweb2[28849]: LDAP bind (uid=xxx / ***) to 9.9.9.9 with default port 8888 failed: Can't contact LDAP server
```

After the code change the connection looks and works like expected:
```
18:29:48.853087 IP 10.xx.xx.xx.60032 > 9.9.9.9.8888: Flags [S], seq 4193613384, win 26883, options [mss 8961,sackOK,TS val 1035533634 ecr 0,nop,wscale 7], length 0
```

## Context
This ticket is similar but it seems it did not fix the problem: https://github.com/Icinga/icingaweb2/issues/2812

## Your Environment
* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version     2.6.2
Git commit     63cb9d728338225833884fda2c312a5a9f431fd6
Git commit date    2018-11-21
* Operating System and version: Centos 7
* PHP:
[root@host ~]# /opt/rh/rh-php71/root/usr/bin/php --version
PHP 7.1.8 (cli) (built: Aug  9 2017 13:20:06) ( NTS )

**Comment by nilmerg** [comment]
Hi, thanks for reporting this!

That's even documented: `The port to connect to. Not used when using LDAP URIs.` Which is forced since 1b440a4f1b18c5d340ab48404e2e4ee933a0a5ac :man_facepalming:
