### ISSUE TITLE
Blacklist objects for specific roles

### ISSUE THREAD

**Issue by rafiwui** [Icinga/icingaweb2#3717]
Currently it is only possible to set specific objects to be visible to a role.
But it would be much easier to specify objects that souldn't be visible for specific roles in some environments.

## Expected Behavior
Be able to set a object blacklist for a role.

## Current Behavior
You can only set a filter for what is viewable.

## Possible Solution
Seeing a blacklist for properties in my opinion it cannot be that hard to replace properties with hosts or services.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.2
* Version used (`icinga2 --version`): r2.10.3-1
* Operating System and version: CentOS 7

**Comment by nilmerg** [comment]
You can use the entire filter syntax for the `monitoring/filter/objects` restriction. For example: `!host_name=foo` or `host_name!=foo`

**Comment by rafiwui** [comment]
Ah ok. Then this issue is closed hereby. Thanks.
