### ISSUE TITLE
Dashboard Not found

### ISSUE THREAD

**Issue by gintisaurabh** [Icinga/icingaweb2#3720]
![image](https://user-images.githubusercontent.com/44056238/54486966-a66db980-48b5-11e9-9780-7a3ec1efd309.png)

configured Icinga2 with Grafna and Influx.

Dashboards are not coming to Icinga2 also perf data not visible for plugin check commands

**Comment by nilmerg** [comment]
Hi,

this seems rather a configuration or environmental issue. For such please head over to our forums: https://community.icinga.com
