### ISSUE TITLE
"Got invalid column: host" in Event Overview

### ISSUE THREAD

**Issue by wopfel** [Icinga/icingaweb2#3721]
## Expected Behavior
Filter event messages by the host name

## Current Behavior
Error is shown: `Icinga\Module\Monitoring\Backend\Ido\Query\HostnotificationQuery : Got invalid column: host`

## Steps to Reproduce (for bugs)
1. Start a fresh _standalone_ Icinga vagrant box
2. Wait for the end message (mine was `icinga2: Navigate to http://192.168.33.5`)
3. Log in to the Icingaweb2 page (I was using Chrome)
4. Navigate to History / Event Overview
5. Expand the pre-defined filter
6. Click on the + sign (add another filter)
7. Enter a host name (esfapp01, or esf*) and click Apply

## Context
I'd like to see only messages for a specific host 

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.6.2, Git commit a487f83f99e440bc71e268725a31943d9e29ea75
* Version used (`icinga2 --version`): v2.10.2-257-g856d3a1
* Operating System and version: CentOS Linux release 7.5.1804
* Enabled features (`icinga2 feature list`): api checker graphite ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`): many informations, some warnings, no errors
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

Example:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/362645/54621316-dbba0900-4a67-11e9-8041-4ed4fffd066d.png">

**Comment by nilmerg** [comment]
Hi,

thanks for the report. You may circumvent this by selecting `host_name` instead. (`host` is case insensitive and `host_name` case sensitive)

**Comment by wopfel** [comment]
Hi, you're welcome.

The same error happens when I select the _Service_ filter:
`Icinga\Module\Monitoring\Backend\Ido\Query\HostnotificationQuery : Got invalid column: service`
By the way, there's no `Service name` selection for the filter like you mentioned for `Host name`.

I've found another issue. When I select Type=Notification I get an empty result. When selecting Type!=Notification, I get everything (I expected I get only Notifications, or everything but Notifications):

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/362645/54715892-c66ed880-4b54-11e9-8ad5-213e00eb5bc1.png">

Should I file separate Github issues for those or can we handle all in this issue?

**Comment by nilmerg** [comment]
> By the way, there's no Service name selection for the filter like you mentioned for Host name.

It's because it's called `service_description` :grin: 

> When I select Type=Notification I get an empty result. When selecting Type!=Notification, I get everything.

That's because the type is not `Notification` but rather `notify`. Try to filter for that.

**Comment by wopfel** [comment]
> It's because it's called `service_description` 😁

Ah 😃

> That's because the type is not `Notification` but rather `notify`. Try to filter for that.

All right, that's the trick. Thanks 😃 I was stuck to `Notification` as that text is displayed in the `Event Details` on the right pane. I can create a PR with kind of doc/xx-search-examples.md if you'd like...

**Comment by nilmerg** [comment]
> I can create a PR with kind of doc/xx-search-examples.md if you'd like...

Nah, such a thing shouldn't require extensive documentation. It should exactly work as you expected it. There is #3631 for that.
