### ISSUE TITLE
[Suggestion] Rename 'Check Source' to 'Command Endpoint'

### ISSUE THREAD

**Issue by junglistikal** [Icinga/icingaweb2#3730]
To be more consistent with the Icinga2 API, can 'Check Source' be renamed to 'Command Endpoint'. It would add a little less confusion to newcomers of Icingaweb2 who are creating their checks via API.

**Comment by dnsmichi** [comment]
`check_source` is not necessarily the command endpoint. It may also originate from the local scheduler on this instance.

Also, `check_source` is the key provided by Icinga 2's API when querying for check results.

**Comment by nilmerg** [comment]
The term *endpoint* has a specific meaning while *check source* is more of a general term. And since https://github.com/icinga/icinga2/issues/2985 `check_source` gets the endpoint's name by default. (Implying that it may *not* be the command endpoint)

So I'd say we keep things as they are.
