### ISSUE TITLE
[Feature-Request] Keep comments a little longer than the downtime/acknowledgement

### ISSUE THREAD

**Issue by sklaes** [Icinga/icingaweb2#3736]
## Current Behavior
Currently, the comment for a acknowledgment or downtime is deleted the moment the acknowledgment or downtime ends. As a result, this information will no longer be available if a new notification is sent. The only way to prevent this is to use persistent comments. The problem with this is that they have to be removed manually and we all know that it doesn't work (reliably).

## Expected Behavior
Therefore my suggestion would be to keep the comments a few minutes longer to be able to integrate them into the next notification. 

## Possible Solution
Implement an offset between acknowledgment/downtime duration  an the duration of the comment.

## Steps to Reproduce (for bugs)
it not a bug

## Context
I experience it more often that an existing fault is given to another colleague because the information from the comments is lost. The new colleague then starts again from zero. I tried to mitigate the problem by including the duration of the malfunction in the notification. However, the duration refers to the current status. If the service is from Warning to Critical, the duration is reset.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.6.2
I will add more details about my Environment if needed.

Thanks!

**Comment by nilmerg** [comment]
Hi,

persistent comments are exactly meant for this. That these imply additional required maintenance is also expected at this moment. Though, there's a feature planned to let comments expire: https://github.com/Icinga/icinga2/issues/4663
