### ISSUE TITLE
Icinga ignores autologin settings

### ISSUE THREAD

**Issue by jakubgs** [Icinga/icingaweb2#3737]
I'm trying to configure Icinga2 to auto-login as admin because I'm putting it behind and oauth proxy.
I've set this in `/etc/icingaweb2/authentication.ini`:
```ini
[autologin]
backend  = external
```
And I have set the `REMOTE_USER` var in Apache config:
```Apache
SetEnv REMOTE_USER admin
```
But I'm still getting this:
```
It appears that you did not configure Icinga Web 2 yet so it's not possible to log in without any defined authentication method. Please define a authentication method by following the instructions in the documentation or by using our web-based setup-wizard.
```
So I tried following the settings from the [Authentication docs section](https://icinga.com/docs/icingaweb2/latest/doc/05-Authentication/#apache-configuration):
```Apache
AuthType Basic
AuthName "Icinga Web 2"
AuthUserFile /etc/icingaweb2/.http-users
Require valid-user
```
But despite that I keep getting the same error about authentication method not being defined.
I see no errors or warnings related to this in `/var/log/icinga2/startup.log`.

How can I debug this further?

**Comment by nilmerg** [comment]
Hi,

check your permissions of `/etc/icingaweb2/authentication.ini`. The webserver seems not be able to read the file so it spits out this warning.

**Comment by jakubgs** [comment]
Oh! You were right, both my `/etc/icinga2` and `/etc/icingaweb2` folders were not owned by group `nagios`. Fixing that fixed the error. Thanks for your help!

Truth be told the an error/warning in the logs or docs should mention that requirement.

**Comment by nilmerg** [comment]
Glad to hear that and thanks for reporting back.

The docs can't cover everything and if you follow the proposed installation procedures (by package, from source) this issue won't occur.
