### ISSUE TITLE
Exceptions with MySQL 8

### ISSUE THREAD

**Issue by lippserd** [Icinga/icingaweb2#3740]
The default character set and collation in MySQL 8 is `utf8mb4` with `utf8mb4_0900_ai_ci`.
This leads to exceptions in some views because we always select columns with their explicit collation `latin1_general_ci`:

> SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_general_ci,EXPLICIT) and (utf8mb4_0900_ai_ci,COERCIBLE) for operation 'UNION', query was: SELECT eh.id, eh.object_type, eh.host_name, eh.host_display_name, eh.service_description, eh.service_display_name, eh.timestamp, eh.state, eh.output, eh.type FROM (SELECT sth.id, sth.timestamp, sth.output, sth.type, sth.state, sth.object_type, sth.host_name, sth.service_description, sth.host_display_name, sth.service_display_name FROM (SELECT hh.statehistory_id AS id, ('host') AS object_type, h.display_name COLLATE latin1_general_ci AS host_display_name, ho.name1 AS host_name, NULL AS service_description, NULL AS service_display_name, NULL AS service_host_name, (CASE WHEN hh.state_type = 1 THEN 'hard_state' ELSE 'soft_state' END) AS type, UNIX_TIMESTAMP(hh.state_time) AS timestamp, hh.object_id, hh.state, (CASE WHEN hh.state_type = 1 THEN hh.output ELSE '[ ' || hh.current_check_attempt || '/' || hh.max_check_attempts || ' ] ' || hh.output END) AS output FROM icinga_statehistory AS hh
INNER JOIN icinga_objects AS ho ON ho.object_id = hh.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id WHERE (('host') = 'host' AND ho.name1 = 'frs98a10wg100.us.fit') UNION ALL ...

The example above is from our history views. Other views may be affected as well. Adopting the character set in the resources configuration has no effect here because the issue is about the collation.

We also have to check our custom variable join template because we hardcode the collation there as well.

**Comment by nilmerg** [comment]
The join template is not hardcoded anymore since #3443 :thinking: 

And isn't this only a thing for new installations? Does a schema fix suffice then?

**Comment by lippserd** [comment]
The collation is hardcoded in our join template. I don't know whether MySQL 8 likes mixing `utf8mb4_0900_ai_ci` with `utf8mb4_general_ci` (in UNIONs). The obvious fix is to select columns w/o their collation. We need the ci collation only for filters and sorting.

**Comment by jhuebner79** [comment]
Is this still being worked on? Is there a known fix for MySQL 8 deployments?

**Comment by nilmerg** [comment]
@jhuebner79 Yes, a fix is now in the master. Will be part of v2.8. Though, requires an explicit `latin1` charset configuration for the IDO resource to have an effect.

**Comment by jhuebner79** [comment]
What if the server's charset is "utf8mb4" (that's what you get when you use Amazon RDS with MySQL 8)?

**Comment by nilmerg** [comment]
The resource configuration overrides this for each connection. `latin1` is anyways what is for the IDO recommended.
