### ISSUE TITLE
Remove dependency in Redhat/Centos 7 for rh-php-71.

### ISSUE THREAD

**Issue by BigPuppyDev** [Icinga/icingaweb2#3744]
## Is your feature request related to a problem? Please describe.
We have PHP-7.2 on our servers from the Remi repo. Currently when trying to install icingaweb2 on Centos, we are forced to install rh-php71 alongside.

## Describe the solution you'd like
Remove the dependency in the Centos repo for php. 

## Additional context
rh-php71 is flagging false positives for the pentesting, which is causing issues as well.

**Comment by nilmerg** [comment]
Hi, please open this issue over at https://github.com/Icinga/icinga-packaging/issues. Thank you.

**Comment by dnsmichi** [comment]
Please don't. That scenario is not supported, PHP packages from SCL are a hard requirement for the packages. The discussion can be read over here: https://github.com/Icinga/icinga-packaging/issues/69
