### ISSUE TITLE
Tactical Overview display incorrect value

### ISSUE THREAD

**Issue by sysres-dev** [Icinga/icingaweb2#3746]
## Describe the bug
The value is incorrect.

## To Reproduce
Since it was in a production environment, i dont have a clean way to reproduce it, however, generating thousands of hosts by api and set their dummy state to down should give the same result.

## Expected behavior
I would expect ~27k to show up, or maybe ~30k if you choose to round up the value at display.
I dont mind if you reduce text size to fit in the donut.

## Screenshots
![image](https://user-images.githubusercontent.com/45565495/56130883-5f431900-5f86-11e9-8573-e6c4ef458f58.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.6.1
* Web browser used: Chrome Version 49.0.2623.110 m
* Screen resolution : 1920x1200
* Icinga 2 version used (`icinga2 --version`):  r2.9.1-1
* PHP version used (`php --version`): PHP 7.1.8 
* Server operating system and version: Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by nilmerg** [comment]
Hi,

thanks for the report. I'd even go as far to just floor the value and drop the `~`.
