### ISSUE TITLE
No hosts visible during some seconds after deployment

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2#3755]
## Describe the bug
After each deployment there is a moment when the no host is is visible for some seconds (around 10s). In this time I can see them in host config section. 

Here I have 2 screenshot with the same view before it happens and when it happens:
![image](https://user-images.githubusercontent.com/31234197/56361111-38d3e680-61ef-11e9-8dea-f34ce3d15807.png)

![image](https://user-images.githubusercontent.com/31234197/56360932-c400ac80-61ee-11e9-95c0-7b8daebed1d4.png)

In this screenshot a monitored host was selected when it happened:

![image](https://user-images.githubusercontent.com/31234197/56361365-d62f1a80-61ef-11e9-9608-938c2cf706e5.png)

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Deploy any change
2. Open a view where some monitored hosts are shown or select one 
3. Wait for some time and see how the filtered hosts disappear and they come back after some seconds

## Expected behavior

Hosts shouldn't disappear.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
**director master of September 2018**
![image](https://user-images.githubusercontent.com/31234197/56361431-01196e80-61f0-11e9-8e4b-ebcaa54ddf7e.png)

* Web browser used:
Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)

* Icinga 2 version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.4-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-8-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: 602f071dcede

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* PHP version used (`php --version`):
```
PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies
```

* Server operating system and version:
`Debian Linux 9.8 x64
`

**Comment by nilmerg** [comment]
Hi,

please have a look at https://github.com/Icinga/icinga2/issues/7125. That's possibly the same?

**Comment by bunghi** [comment]
Seems to be the same but only hosts disappear, like other user reported. 
I'm happy that I'm not the only one with this issue :)

**Comment by nilmerg** [comment]
Thanks for the feedback. I'll close this then.
