### ISSUE TITLE
Incorporate module reporting to default Web installation 

### ISSUE THREAD

**Issue by aflatto** [Icinga/icingaweb2#3756]
## Is your feature request related to a problem? Please describe.
The reporting and IDO reports modules are the main thing users constantly complain about missing in Icinga. 
Some companies have dropped the potential of using Icinga due to this missing functionality.

## Describe the solution you'd like
Incorporate the reporting modules in to the binary installation of the IcingaWeb2 core, and not as an add on module.

**Comment by nilmerg** [comment]
Hi Assaf,

the reporting module currently requires a lot of dependencies which are not in a state yet to be part of any packages.

But, rest assured we'll definitely consider this module being a part of a packaged solution in the future. :wink: 

Best,
Johannes
