### ISSUE TITLE
Include details about the object for which a macro could not be resolved

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icingaweb2#3759]
## Is your feature request related to a problem? Please describe.
We checked our icingaweb2 log and saw this messages many times
![image](https://user-images.githubusercontent.com/38723488/56637573-4284a080-666c-11e9-9eb6-77a64347d614.png)
The Problem is, it cames not like an interval and we do not recognize a pattern. We checked our config in the director and every template. But it's really hard to find the host or service, who/which produce the message. 

## Describe the solution you'd like
A solution could be to write also the hostname or servicename into the message. 

## Describe alternatives you've considered
A alternative could be - but it's not nice - supress the message. Because in our case we use the variable "icmp_message" for the check "check_icmp". And if there is an error or something wrong with the config, the check result would be "critical" or "unknown". 

## Additional context
Our versions: 
icingaweb2: 2.6.1 (production environment), 2.6.2 (test Environment). 
icinga2: 2.10.2 (production environment), 2.10.4 (test Environment). 
CentOS 7.6.1810

**Comment by nilmerg** [comment]
Hi,

this error may have the following origins:

* A host's `notes_url`, `action_url` or `icon_image` property *(Icinga 2 Config)*
* A service's `notes_url` or `icon_image` property *(Icinga 2 Config)*
* A navigation item of type host- or service-action *(Icinga Web 2 Config)*

There you should look for `$icmp_address$`.

The message itself or rather the fact that the property is not found shouldn't be much of a problem. It's logged as part of level `DEBUG` after all. If you don't want this message in your log, lower the log level.

Though, including the name of the host or service in the message may indeed possible.

**Comment by stevie-sy** [comment]
thanks for the Information. We changed the log Level for us. if we have time, we'll take a look what the director is rendering. Maybe there one rule needs a little update. For us it is also low priority. 

I opened this feature-request as a little improvement with the log files for the future. Nothing important.

**Comment by tbauriedel** [comment]
ref/NC/761567
