### ISSUE TITLE
Add --version parameter to icingacli

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2#3763]
## Describe the solution you'd like

I'd like to gather the version on the CLI, similar to other tools. Even if I may use package repo tools, the runtime CLI command may use a different source with paths and what not.

```
icingacli --version
2.6.3 ...
```

The PHP version would be a bonus.

## Additional context

Thinking about simple release tests and further troubleshooting.

**Comment by nilmerg** [comment]
So, essentially what the *About* page displays but on the CLI. I'd even include the installed modules with their respective version.

And the PHP version on the *About* page would also benefit if there's the PHP version visible. (Especially since the entire php-fpm vs cli topic)

**Comment by dnsmichi** [comment]
Basically, yes - I didn't think about modules at this very moment. I was just updating the Release docs, and thought about the best way to identify the correct version being installed :-)
