### ISSUE TITLE
not all hosts are listed in icinga service grid

### ISSUE THREAD

**Issue by azamukhamedov** [Icinga/icingaweb2#3788]
## Describe the bug
Not all hosts are displayed in Icinga Service grid.
## To Reproduce
1. Problems > Service Grid
2. Press navigation buttons (up, down)

## Expected behavior
should display same number of hosts as configured in icinga2 director

## Screenshots
![icinga](https://user-images.githubusercontent.com/28984892/58095937-473d6580-7bd4-11e9-9128-48c51af679d6.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.3
* Web browser used: Chrome Version 74.0.3729.157 (Official Build) (64-bit)
* Icinga 2 version used (`icinga2 --version`): (version: r2.10.4-1)
* Server operating system and version:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-957.5.1.el7.x86_64
  Architecture: x86_64

**Comment by nilmerg** [comment]
Hi,

in order for us to reproduce this you need to be more elaborate.

* Got the missing hosts services at all?
* If you have hosts without services, do any of those show up or are all missing?
* Are these hosts services visible for other hosts?
* Are the hosts also missing if you increase the grid by clicking *Load More*?

And please show a full screenshot with the gaps visible as well as a screenshot of a missing host's detail view.

**Comment by azamukhamedov** [comment]
Hi, I'll try to be more precise,

there are around 45 hosts which are configured in Icinga Director (all of them with services), however in the service grid only 19 of them are listed by some reason.
As you can see in the screenshot, it is not possible to load more hosts in the service grid by clicking the navigation buttons (load more).

the screenshot of service grid with listed hosts:
![service grid](https://user-images.githubusercontent.com/28984892/58119145-9d290200-7c02-11e9-8138-d5c7364c5f7e.png)

**Comment by nilmerg** [comment]
The url is which? By default the grid only shows problems, so if none of your hosts and none of their services have a problem they won't show up.

**Comment by azamukhamedov** [comment]
thanks for the information
