### ISSUE TITLE
Service grid problem toggle

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#3793]
## Is your feature request related to a problem? Please describe.
The service grid shows only problems by default. By removing the `problems` parameter the grid shows everything though this is not obvious enough. (#3788)

## Describe the solution you'd like
A toggle to switch between *only problems* and *everything*. Similar to what we have for group overviews.

**Comment by theFeu** [comment]
In all of the other views in the 'Problems' tab there is a filter, that you can just remove:
![image](https://user-images.githubusercontent.com/22217062/58249244-9d3e1480-7d5e-11e9-806a-14071ffa0ed0.png)

Why don't we have this in the service grid?

**Comment by nilmerg** [comment]
Because it's a rather special filter. Any other filter is utilized with a comparison. (e.g. `something=else`) and applied on the result directly. `problems` however is not applied directly, it's processed differently and so putting it in the filter editor does not work. That's because I think we should provide a toggle switch as well here. (Just like the service grid already has one for `?flipped`)
