### ISSUE TITLE
LDAP user group in group does not work

### ISSUE THREAD

**Issue by pknutti** [Icinga/icingaweb2#3796]
## Describe the bug
When I use a active directory group in a role definition which includes only groups, then icingaweb2 is not able to resolve these groups to get the members. 

As soon as I try to get the information who are the members of the group then I am not able to see them. In the overview tab you can see only the subgroup as user. 

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1.Import Groups and user from active directory
2.Create a role with an assigned AD-group and grant needed permissions and filter
3.Login with a member of this Group

## Expected behavior
resolve members of capsulated groups 

## Screenshots
Role with assigned group
![grafik](https://user-images.githubusercontent.com/36183993/58315489-f1560100-7e11-11e9-8107-ffdfbc5abadc.png)

Group in group bahavior
![grafik](https://user-images.githubusercontent.com/36183993/58315179-4d6c5580-7e11-11e9-9971-a0aa7641b808.png)

The imported group in this picture was resolved correctly

## Your Environment
![grafik](https://user-images.githubusercontent.com/36183993/58314735-6b858600-7e10-11e9-86af-6d4b87ab65c5.png)

* Icinga Web 2 version and modules (System - About):
* Web browser used: Firefox68.0b3, Internet Explorer 11, Firefox66
* Icinga 2 version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.4-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.5 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-862.11.6.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* PHP version used (`php --version`):
PHP 5.4.16 (cli) (built: Jun 19 2018 13:09:01)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
* Server operating system and version:
Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by nilmerg** [comment]
Hi,

I can't say for sure what the exact problem is here.

* Are these roles not correctly applied?
* Are just the membership overviews in the UI incomplete/bugged?

Nested groups are supported by Icinga Web 2 (for Active Directory) by enabling this for the authentication backend. There's a checkbox you can tick to enable nested group resolution.

**Comment by pknutti** [comment]
That solves it. Thanks a lot.
