### ISSUE TITLE
Same ID on two elements in the announcements

### ISSUE THREAD

**Issue by theFeu** [Icinga/icingaweb2#3798]
The `<ul id="announcements">` is wrapped by a `<div id="announcements">` which doesn't seem right.

![image](https://user-images.githubusercontent.com/22217062/58329893-f0cf6180-7e35-11e9-9440-d45afd59fc5b.png)

**Comment by nilmerg** [comment]
There's already #3762 for that. Though, thanks for pointing out another example.
