### ISSUE TITLE
Event Handlers do not disable recursively through satellite zones from Monitoring Health

### ISSUE THREAD

**Issue by blakehartshorn** [Icinga/icingaweb2#3799]
## Describe the bug
Under /icinga2/monitoring/health/info, disabling Event Handlers does not appear to recurse past Master zone. It works fine with Notifications, but we have noticed during software deploys that event handlers are running in satellite zones (fortunately we don't have any that would break this at this time).

## To Reproduce
1. Add an event command for a child in a satellite zone.
2. Disable Event Handlers globally via Monitoring Health.
3. Observe for the event handler to execute.

## Expected behavior
Event Handlers disable globally.

## Your Environment
* One-direction top-down environment.
* Icingaweb2 2.6.3
* Icinga2 2.10.4 on masters and satellites (at least 2.10.2 everywhere else).

We'll try to seek out that API call when we have some time.

**Comment by dnsmichi** [comment]
Those calls are not replicated to all cluster instances, this only affects the instance where Icinga Web 2 is running on. This is a known problem with other commands in this area.

**Comment by nilmerg** [comment]
As Michael said, replicating this to all connected instances in the cluster is Icinga 2's task. Icinga Web 2 can only send API requests to a single instance.

Since we have to wait here for Icinga 2, I'll close this now.
