### ISSUE TITLE
Redesign Comment/Downtime lists

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2#3803]
## Current Design of the *Comment*/*Downtime* List
The current designs of the comment and downtime lists don't make much sense. The wrong information is highlighted and the details are not easy to grasp.

## Solution
We should restructure the layout of the list items both individually for comments and downtimes to make the respective list views more useful.

**Comment by theFeu** [comment]
Is this roughly what you had in mind?
![image](https://user-images.githubusercontent.com/22217062/58428269-3d1ed980-80a2-11e9-8896-0c4cfd19813f.png)

**Comment by flourish86** [comment]
Yes, looks much clearer.

**Comment by flourish86** [comment]
refs #3478

**Comment by theFeu** [comment]
refs #3615
