### ISSUE TITLE
Dashboard Settings too hidden

### ISSUE THREAD

**Issue by theFeu** [Icinga/icingaweb2#3807]
It feels to me, like the dashboard settings are too hidden away

In the sense of that I am used to it from other views, that the arrow down icon ![image](https://user-images.githubusercontent.com/22217062/58536399-b4fb1a00-81f0-11e9-8e9a-00daaa159d7e.png) is for using the view for something (like print it or export it) - but not edit it.
Intuitively I wouldn't search for settings under it.

**Comment by nilmerg** [comment]
Valid point, though please add your comment to #3809. I don't want another separate issue for the same topic.
