### ISSUE TITLE
Shared Navigation: line breaks in Users/Groups TextBoxes result in a FatalError

### ISSUE THREAD

**Issue by dbu1986** [Icinga/icingaweb2#3808]
## Describe the bug
Using line breaks in the users or groups text input field of a Shared Navigation causes Icingaweb2 to crash with a Fatal error:
```
Fatal error:  Uncaught ErrorException: Uncaught ErrorException: syntax error, unexpected '&quot;' in Unknown on line 7
 in /usr/share/php/Icinga/File/Ini/IniParser.php:265
Stack trace:
#0 [internal function]: Icinga\Application\ApplicationBootstrap-&gt;Icinga\Application\{closure}(2, 'syntax error, u...', '/usr/share/php/...', 265, Array)
#1 /usr/share/php/Icinga/File/Ini/IniParser.php(265): parse_ini_string('[Test NaviItem]...', true, 1)
#2 /usr/share/php/Icinga/Application/Config.php(326): Icinga\File\Ini\IniParser::parseIniFile('/etc/icingaweb2...')
#3 /usr/share/php/Icinga/Application/Config.php(445): Icinga\Application\Config::fromIni('/etc/icingaweb2...')
#4 /usr/share/php/Icinga/Application/Web.php(239): Icinga\Application\Config::navigation('menu-item')
#5 /usr/share/php/Icinga/Web/Navigation/Navigation.php(437): Icinga\Application\Web-&gt;getSharedNavigation('menu-item')
#6 /usr/share/php/Icinga/Web/Menu.php(21): Icinga\Web\Navigation\Navigation-&gt;load('menu-item')
#7 zend.view:///usr/share/icingaweb2/application/layouts/scri in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 259
```

The Shared Navigation is stored at /etc/icingaweb2/navigation/menu.ini:
```
[Test NaviItem]
type = "menu-item"
target = "_main"
url = "monitoring/list/services?modifyFilter=1"
owner = "icingaadmin"
users = "User1
User2"
```

## To Reproduce
1. Create a Shared Navigation (activate "Shared" CheckBox)
2. Type in Users/Groups the Navigation shall be shared with, seperated by line breaks.
3. Save Changes.
4. Icingaweb2 immediately crashes with the FatalError.

## Expected behavior
Although the ToolTips of the TextBoxes advise the user to provide a comma separated list of users/groups, the TextBoxes' multi-line layout suggests to be capable of handling line breaks. A solution could be to provide a single-line InputField instead of a TextBox. Another idea to avoid the crash might be converting line breaks into commas and (in a second step) to regex-replace multiple commas without literals in between, before the content gets saved in the menu.ini file.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.6.2
* Web browser used: Google Chrome, Firefox
* Icinga 2 version used (`icinga2 --version`): r2.10.2-1
* PHP version used (`php --version`): 5.4.16
* Server operating system and version: RHEL 7.5

**Comment by nilmerg** [comment]
Hi,

please upgrade to v2.6.3 where this issue is fixed. Though, the corrupted ini-file needs to be fixed manually. Replace every line break with a literal `\n` and the error is gone.
