### ISSUE TITLE
Checks execution delay

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2#3820]
## Describe the bug
Not sure is the right place to open this issue. The thing is that sometimes we have a lot of delay executing checks. Like this example:

![image](https://user-images.githubusercontent.com/31234197/59245202-4d958f00-8c20-11e9-9c17-b15430e387ac.png)

Even if I run Check now it doesn't change. Anyone else with this issue?

Anyway, in most of the times it takes about 20s since I click on "Check Now"  button and I see the script being executed, and about 30s more to be refreshed on Icingaweb2.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
![image](https://user-images.githubusercontent.com/31234197/59245255-8df50d00-8c20-11e9-82fb-702a7e55339c.png)

* Web browser used:
Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)

* Icinga 2 version used (`icinga2 --version`):
```
root@mqde01icinga2wk01:/var/tmp$ icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.5-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-8-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: cb654124b660

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* PHP version used (`php --version`):
```
PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies
```

* Server operating system and version:
Debian 9.9

**Comment by nilmerg** [comment]
Hi, this seems to be a problem on the icinga 2 side. The logs may shed some light onto this. Though, please head over to our forums (https://community.icinga.com) if you have further questions. You'll get certainly more help there.
