### ISSUE TITLE
Non-combined / Non-stacked Permission

### ISSUE THREAD

**Issue by pdorschner** [Icinga/icingaweb2#3821]
## Is your feature request related to a problem? Please describe.
Yes. Stacking-Filters (https://github.com/Icinga/icingaweb2/blob/master/doc/06-Security.md#stacking-filters-) doesn't provides the appropriate permissions.   Only combined permissions which may not provide the desired access rights.

## Describe the solution you'd like
The desired solution would be, to provide separated permissions which granularly provide better access rights. For example, it should be possible to have one user in two different groups with separated permissions, instead of combined rights, which allow him access with elevated permission to both groups. 

## Additional context
Code example for expanded permissions to Group1
```
[Group OnlyView]
groups = "Group1"
permissions = "module/monitoring"
monitoring/filter/objects = "(_service_view_group=*|_host_view_group=*)"

[Group MoreRights]
groups = "Group2"
monitoring/filter/objects = "(_service_view_group=SERVICEGROUP)"
permissions = "module/monitoring, monitoring/command/schedule-check, monitoring/command/downtime/*, monitoring/command/remove-acknowledgement"
```

**Comment by pdorschner** [comment]
ref/NC/618607

**Comment by nilmerg** [comment]
Hi, this is already handled with #2455. Closed as duplicate.
