### ISSUE TITLE
Own Icingaweb2 Module only shown with "Allow Anything *" Role

### ISSUE THREAD

**Issue by Tux12Fun** [Icinga/icingaweb2#3824]
Hi,

I know that is not directly a Icingaweb2 bug, but I don't now who can help me with that problem.

Currently I write a Module for Icingaweb2 and this Module looks like this:

`
namespace Icinga\Module\CeGraph;

use Icinga\Module\Monitoring\Object\MonitoredObject;
use Icinga\Module\Monitoring\Object\Host;
use Icinga\Module\Monitoring\Object\Service;
use Icinga\Application\Hook\GrapherHook;
use Icinga\Web\Url;

class Grapher extends GrapherHook{
....

public function getPreviewHtml(MonitoredObject $object){
    return "myHTMLCodeForGraph";
}

`

The Problem: This Module is only shown with Rolle Allow Anything *" Role. 

With this role everything is working fine and the IFrame with the Graph is shown.

Have I missed something with a rights Mangement? and is there any Guide where i can fetch this knowlege?

Icingaweb2 is the latest version from Repo on a Ubuntu 18.04.2 with PHP7.2

**Comment by dnsmichi** [comment]
Please move this discussion to https://community.icinga.com inside the modules category.
