### ISSUE TITLE
Dashboard size of columns should be changeable and stored

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2#3825]
## Is your feature request related to a problem? Please describe.
Icinga Web 2 has fixed column sizes based on screen resolution, in some cases it would be better to have different column sizes matching the use case like a operator view which should always have all three (smaller) columns independently from the screen resolution. In some cases having even more columns than the maximum 3 would be nice.

## Describe the solution you'd like
I would like to adjust the column size per drag and drop and perhaps even store them to the dashboard config.

## Describe alternatives you've considered
Having an additional border for the screen resolution where you get 4 columns would solve some but not all use cases.

## Additional context
ref/NC/609335

**Comment by nilmerg** [comment]
That's covered by #3809. Closed as duplicate.
