### ISSUE TITLE
Object actions don't handle external paths properly

### ISSUE THREAD

**Issue by mhirschb** [Icinga/icingaweb2#3829]
## Describe the bug
The externall hostname in the "New Navigation Item"-URL is always replaced by the own hostname

## To Reproduce
1. vars.directory="/some/directory/1234/"
2. in the "create Navigation Item"-GUI:
3. URI-Field: http://some.host.com/$directory$

(Hostname of the monitoring server is "http://monitoring.host.com")

## Expected behavior
Navigation-item URI: "http://some.host.com//some/directory/1234/"
Current behaviour URI: "http://monitoring.host.com//some/directory/1234/"

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.6.3

**Comment by nilmerg** [comment]
Hi, I did the exact steps you've defined to reproduce this. However, it works for me very well. The url is identified as external and handled as such. Did you forget to mention something?

**Comment by mhirschb** [comment]
Hi. I was afraid of this :/

Here is the configuration-file-entry:
![image](https://user-images.githubusercontent.com/9540999/60031666-751b3b80-96a5-11e9-8120-d23925999836.png)
here the configuration:
![image](https://user-images.githubusercontent.com/9540999/60031733-8e23ec80-96a5-11e9-8af0-46d48c68c473.png)
here the host-attributes in the icingaweb2:
![image](https://user-images.githubusercontent.com/9540999/60031791-a85dca80-96a5-11e9-8123-2d0597226e84.png)
and here the resulting link:
![image](https://user-images.githubusercontent.com/9540999/60032168-4f426680-96a6-11e9-837b-c4b5b9e6dcd2.png)

As you can see, the hostname is replaced by the hostname of the monitoring server.

**If there is a '?' or a '#' in the URL, the concatenation works as expected:**
![image](https://user-images.githubusercontent.com/9540999/60032303-90d31180-96a6-11e9-83d0-e824680bf5db.png)
results (correctly) in 
![image](https://user-images.githubusercontent.com/9540999/60032352-a6483b80-96a6-11e9-9a1c-5b44b3010dc1.png)

**Comment by nilmerg** [comment]
Well, I did not include the trailing slash after the hostname. That's what causes the host to disappear. To fix this on your end you'll need to either remove the trailing slash in the nav item's url field or the leading slash in the custom variable.

Though, it's still a bug (fix incoming), thanks for the report.
