### ISSUE TITLE
Unable to reschedule service check via icingaweb2

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2#3841]
## Describe the bug
Service check reschedule is not working. It does nothing.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Select a service
2. Click on "Reschedule" button and set next execution
3. Check if "Next check" time changed

## Expected behavior
Expectation is to be executed when scheduled but nothing changes.

## Screenshots
Check next check time:
![image](https://user-images.githubusercontent.com/31234197/60516346-3b21e900-9ce6-11e9-9755-67b74da8bd3a.png)

Reschedule, in this example 2 hours later:
![image](https://user-images.githubusercontent.com/31234197/60516378-4d9c2280-9ce6-11e9-8c39-68189eee7c58.png)

Check next check time:
![image](https://user-images.githubusercontent.com/31234197/60516401-5a207b00-9ce6-11e9-9717-a9523edf9520.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
![image](https://user-images.githubusercontent.com/31234197/60516516-9a7ff900-9ce6-11e9-9652-3d2b01100365.png)

* Web browser used:
Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

* Icinga 2 version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.5-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-9-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: cb654124b660

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* PHP version used (`php --version`):
```
PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies
```

* Server operating system and version:
Debian 9.9

**Comment by dnsmichi** [comment]
As asked in #3820 already, move this into the community forums please.
