### ISSUE TITLE
Allow filtering Output by partial match

### ISSUE THREAD

**Issue by Tjololo12** [Icinga/icingaweb2#3842]
## Is your feature request related to a problem? Please describe.
I have a service check that outputs different failures with specific strings (Commercial, Private, etc). Currently there is no way to filter the event overview/history page to only show me specific queries (IE all service events since <startdate> which have been critical and contain the word "Commercial" in the output)

## Describe the solution you'd like
An additional filter state "Contains" which would make the MySQL query something like "output LIKE %search terms%"

## Describe alternatives you've considered
Maybe instead of a "contains" filter, you could keep the standard = but recognize if the filter value is surrounded by %, it would change the query from = to LIKE. Alternatively, all searches on "Output" specifically (and maybe other fields) would default to "LIKE %value%" or "NOT LIKE %value%" to avoid having to add another use case.

## Additional context
Screenshot:

![image](https://user-images.githubusercontent.com/3385791/60538195-11fa5c00-9cd8-11e9-9271-f18506c0aa19.png)

**Comment by Tjololo12** [comment]
I should note: This is after manually making the changes in PR #3781

**Comment by nilmerg** [comment]
Hi, as I've already written in our forums this is possible by using the `*` wildcard.
