### ISSUE TITLE
UX issue with ghosted values in fields

### ISSUE THREAD

**Issue by ccallawa** [Icinga/icingaweb2#3847]
## Describe the bug
Grayed out (ghosted) text in fields can be interpreted either as defaults or examples. 

## To Reproduce
1.  Go to *Configuration > Modules > monitoring > Security*
2.  For "Protected Custom Variables", the "pw,pass,community" string is shown in gray if it has not been configured

## Expected behavior
It should be more clear whether it is an example or a default.  My suggestion in this case is that you should see "Ex: *pw*,*pass*,community" so the user knows it is an example.  Without the "Ex:" it might be a default value.

## Your Environment
* Icinga Web 2 2.6.2

**Comment by ccallawa** [comment]
Updates:
* The [official documentation](https://icinga.com/docs/icingaweb2/latest/modules/monitoring/doc/03-Configuration/#security-configuration) does not mention that the regex is case insensitive
* The phrase "string patterns" sounds like it's a regular expression, but it seems that * is the only operator available
* The standard definition of "Comma separated list" allows for optional spaces after the comma. If you use them here, they are included as part of the string pattern.

I think the above are important because if you are unaware of these limitations, the result is failure to hide a password, which is a security problem.

For the UX issue, I think you should use a tooltip like this attached screenshot to explain the details.
![example-gui-director](https://user-images.githubusercontent.com/2863948/60888621-847ab700-a257-11e9-80be-074600d3f2ae.png)

**Comment by lippserd** [comment]
Adding something like "Example: " to the placeholder absolutely makes sense.
But should we also change the styles of our placeholders @flourish86?

[1] Placeholder

![Screenshot 2019-08-05 at 13 19 22](https://user-images.githubusercontent.com/1894563/62461006-e7426e00-b783-11e9-9f96-5d9fe43c91df.png)

[2] Real value

![Screenshot 2019-08-05 at 13 19 35](https://user-images.githubusercontent.com/1894563/62461011-ec9fb880-b783-11e9-8b2f-2104d97ab45a.png)

**Comment by flourish86** [comment]
Maybe setting placeholder in _italics_ would help to distinguish it better from real values.
