### ISSUE TITLE
icingaweb2-module development

### ISSUE THREAD

**Issue by zaynkorai** [Icinga/icingaweb2#3854]
I am trying to develop a module in icinga and following this guide
https://github.com/Icinga/icingaweb2-module-training/blob/master/doc/icinga-web-2-erweitern.md

I am facing a issue where I Can't access the particular url of module except index.
like I can access localhost/icingaweb2/training/
But I can not access  localhost/icingaweb2/training/hello/world

* Icinga Web 2 version and modules (write a module):
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 latest`):
* PHP version used (`php 7.3`):
* Server operating system and version: local Setup Ubuntu

**Comment by nilmerg** [comment]
Hi, please head over to our community forum (https://community.icinga.com) for such topics. This is an issue tracker for bugs and features. Thank you.
