### ISSUE TITLE
Evaluate infinite scrolling for object lists preserving pagination functionality

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2#3873]
## Pagination is not intuitive
Navigating through long object lists isn't as effortless as it could be. Even if items per page is set to a large number it's unintuitive, if the user has to navigate back to the pagination control, which is located in the top of the viewport.

## Investigate infinite scroll
We should investigate if some kind infinite scrolling solution would make sense. There are already solutions that enhance the pagination navigation.

For example Search Results in _Duck Duck Go_
![Screen Recording 2019-07-23 at 13 33 47 2019-07-23 13_36_15](https://user-images.githubusercontent.com/6977434/61709187-e99dd480-ad4e-11e9-890e-2193c69b4a93.gif)

Some things to notice here:
* The next page doesn't auto load, which can be helpful since scroll detection is pretty hard to implement well (performance vs. accuracy)
* Page markers are preserved, so it will be clear, which page you're on for later rediscoverability. We could use the page markers as anchors to scroll to, when clicking the pagination control. This has to be technically investigated, though. I'm not sure, how much this will collide with auto-refresh and all of Icinga Web's pecularity.

## Enhance current pagination
A first step to this could be to make the pagination control more intuitive. A next/previous control at the end of the list would help already.

**Comment by nilmerg** [comment]
That's exactly what we currently have in the dashboard and event overview.

True infinite scrolling as well, albeit only in the timeline and may require some attention to detail. (Though, it works fine generally)

**Comment by nilmerg** [comment]
Is available in Icinga DB Web's history lists.
