### ISSUE TITLE
'File exists' error for temporary files

### ISSUE THREAD

**Issue by bsdlme** [Icinga/icingaweb2#3874]
## Describe the bug
I am often seeing this error message in the web interface:

`25.07. 07:26ERROR | ErrorException in /usr/local/www/icingaweb2/library/Icinga/File/Storage/TemporaryLocalFileStorage.php:21 with message: mkdir(): File exists#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)#1 /usr/local/www/icingaweb2/library/Icinga/File/Storage/TemporaryLocalFileStorage.php(21): mkdir(String, Integer)#2 /usr/local/www/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(21): Icinga\File\Storage\TemporaryLocalFileStorage->__construct()#3 /usr/local/www/icingaweb2/modules/pdfexport/library/Pdfexport/ProvidedHook/Pdfexport.php(20): Icinga\Module\Pdfexport\HeadlessChrome->__construct()#4 /usr/local/www/icingaweb2/library/Icinga/Web/Widget/Tabextension/OutputFormat.php(88): Icinga\Module\Pdfexport\ProvidedHook\Pdfexport->isSupported()#5 /usr/local/www/icingaweb2/library/Icinga/Web/Widget/Tabextension/OutputFormat.php(49): Icinga\Web\Widget\Tabextension\OutputFormat->getSupportedTypes()#6 /usr/local/www/icingaweb2/modules/monitoring/application/controllers/ListController.php(759): Icinga\Web\Widget\Tabextension\OutputFormat->__construct()#7 /usr/local/www/icingaweb2/modules/monitoring/application/controllers/ListController.php(28): Icinga\Module\Monitoring\Controllers\ListController->createTabs()#8 /usr/local/www/icingaweb2/library/Icinga/Web/Controller/ActionController.php(152): Icinga\Module\Monitoring\Controllers\ListController->init()#9 /usr/local/www/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)#10 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))#11 /usr/local/www/icingaweb2/library/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))#12 /usr/local/www/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()#13 /usr/local/www/icingaweb2/public/index.php(4): require_once(String)#14 {main}
-- | --`

After reloading the page the error is gone but can re-appear any time.

See the screenshot for a sample error.

* Icinga Web 2 version and modules (System - About): 2.6.3
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): r2.10.5-1
* PHP version used (`php --version`): 7.2.20
* Server operating system and version: FreeBSD 12.0-RELEASE

**Comment by bsdlme** [comment]
![icingaweb](https://user-images.githubusercontent.com/1733402/61848843-b2930480-aeaf-11e9-9730-e1178a45bbfc.png)

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I think that's related to the pdfexport module: https://github.com/Icinga/icingaweb2-module-pdfexport/issues/8

Cheers,
Eric
