### ISSUE TITLE
Uncaught ErrorException on Service Downtime

### ISSUE THREAD

**Issue by cfcnigel** [Icinga/icingaweb2#3883]
## Describe the bug
Icingaweb2 throws an exception when I open a services that have downtimes.

There's error info:

`Warning: Uncaught ErrorException: require_once(HTMLPurifier/Bootstrap.php): failed to open stream: Datei oder Verzeichnis nicht gefunden in /usr/share/icingaweb2/modules/monitoring/application/views/helpers/EscapeComment.php:26 Stack trace: #0 `

`/usr/share/icingaweb2/modules/monitoring/application/views/helpers/EscapeComment.php(26): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'require_once(HT...', '/usr/share/icin...', 26, Array) #1 `

`/usr/share/icingaweb2/modules/monitoring/application/views/helpers/EscapeComment.php(26): require_once() #2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(345): Zend_View_Helper_EscapeComment->escapeComment('test') #3 `

`/usr/share/php/Icinga/Web/View.php(278): Zend_View_Abstract->__call('escapeComment', Array) #4 zend.view:///usr/share/icingaweb2/modules/monitoring/application/views/scripts/show/components/downtime.phtml(111): Icinga\Web\View->__call('escapeComment', Array) #5 `

`/usr/share/php/Icinga/Web/View.php(259): include('zend.view:///us...') #6 / in /usr/share/icingaweb2/modules/monitoring/application/views/helpers/EscapeComment.php on line 26`

`Fatal error: Zend_View_Helper_EscapeComment::escapeComment(): Failed opening required 'HTMLPurifier/Bootstrap.php' (include_path='/usr/share/icingaweb2/library/vendor::/usr/share/kopano/php') in /usr/share/icingaweb2/modules/monitoring/application/views/helpers/EscapeComment.php on line 26
`

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Add a Downtime to Service
2. 
3.
4.

## Screenshots
![image](https://user-images.githubusercontent.com/49064657/62129981-47469980-b2d8-11e9-84f3-fc32361bf5c2.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.6.3
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): r2.10.5-1
* PHP version used (`php --version`): PHP 7.2.19-0ubuntu0.18.04.1
* Server operating system and version: Ubuntu Server 18.04.2 LTS

**Comment by nilmerg** [comment]
@lazyfrosch Please have a look here. @lippserd meant this may be an issue with our packages.

**Comment by lazyfrosch** [comment]
We are currently using php-htmlpurifier on Debian and Ubuntu from a system package.

This should probably be updated to use our internal vendor lib. (This came from the official Debian packaging standard)

But the real problem with @cfcnigel error is an incorrect include path!

The include_path should include /usr/share/php, is this a custom PHP installation or has the include_path been changed?

**Comment by cfcnigel** [comment]
the php installation is default, no changes from me. How can i check the include_path?

**Comment by lazyfrosch** [comment]
@cfcnigel You see it in your screenshot, include_path is currently:

* `/usr/share/icingaweb2/library/vendor` (which we add)
* `/usr/share/kopano/php` which must be set system wide or via Apache

You can check your include_path settings like below, be aware that CLI, Apache and FPM have different config files on Debian/Ubuntu.

    grep -r include_path /etc/php

The compiled-in path should be `.:/usr/share/php`.

**Comment by cfcnigel** [comment]
```
/etc/php/7.2/mods-available/mapi.ini:include_path="${include_path}:/usr/share/kopano/php"
/etc/php/7.2/cli/php.ini:;include_path = ".:/usr/share/php"
/etc/php/7.2/cli/php.ini:;include_path = ".;c:\php\includes"
/etc/php/7.2/cli/php.ini:; PHP's default setting for include_path is ".;/path/to/php/pear"
/etc/php/7.2/cli/php.ini:; Enables or disables file search in include_path optimization
/etc/php/7.2/apache2/php.ini:;include_path = ".:/usr/share/php"
/etc/php/7.2/apache2/php.ini:;include_path = ".;c:\php\includes"
/etc/php/7.2/apache2/php.ini:; PHP's default setting for include_path is ".;/path/to/php/pear"
/etc/php/7.2/apache2/php.ini:; Enables or disables file search in include_path optimization
/etc/php/7.2/apache2/php.ini.ucf-dist:;include_path = ".:/usr/share/php"
/etc/php/7.2/apache2/php.ini.ucf-dist:;include_path = ".;c:\php\includes"
/etc/php/7.2/apache2/php.ini.ucf-dist:; PHP's default setting for include_path is ".;/path/to/php/pear"
/etc/php/7.2/apache2/php.ini.ucf-dist:; Enables or disables file search in include_path optimization
```


The solution is: I activate the commented out include_path in the php ini

however, I had not played around in the php ini. this has been installed exactly with the commented out path. ;-)

Thank for your help

**Comment by lazyfrosch** [comment]
The setting including "kopano" is coming from somewhere...

**Comment by dnsmichi** [comment]
Seems that Kopano is a web app which loads a custom mapi php extension, which overrides the include path. https://forum.kopano.io/topic/1199/php-fatal-error/4 

```
/etc/php/7.2/mods-available/mapi.ini:include_path="${include_path}:/usr/share/kopano/php"
```

indicates that, but for some reason `${include_path}` is empty. If you don't need that app/extension, disable that for testing and see whether this fixes the issue.

**Comment by nilmerg** [comment]
I'm closing this now, since the reason is identified. Thanks @lazyfrosch for the investigation.

**Comment by lazyfrosch** [comment]
The packaging will use the vendored version of HTMLPurifier in the future:
https://git.icinga.com/packaging/deb-icingaweb2/commit/c9c0bc7cff2d5a098381d7c4adc8d53338f4df2a
