### ISSUE TITLE
Wildcard filters in chains broken

### ISSUE THREAD

**Issue by aledr** [Icinga/icingaweb2#3886]
Hi.

Updating 2.6 to 2.7 broke _monitoring/filter/objects_ using * (wildcard).

Example: I would like to match Host Group Names _"foo-set1"_ and _"foo-set2"_ so the filter is set as **"hostgroup_name=foo-*"**.

Thanks.

**Comment by nilmerg** [comment]
Hi, thanks for reporting this. I've reproduced this successfully, identified the cause (#3868) and I'm now investigating a fix..
