### ISSUE TITLE
Highlight links in the notes of an object

### ISSUE THREAD

**Issue by winem** [Icinga/icingaweb2#3888]
## Is your feature request related to a problem? Please describe.
Links are not visible as such if they are part of the notes. `Just a link to netways :)` in the screenshot is a link.

## Describe the solution you'd like
Highlight the links to match the improved look and usability of icingaweb2 2.7.

## Describe alternatives you've considered
I would suggest to underline them or colour the font.

## Additional context
![Selection_397](https://user-images.githubusercontent.com/1457899/62271700-8f310200-b439-11e9-8b7e-05a663c2f6fa.png)

**Comment by nilmerg** [comment]
Hi, thanks for the suggestion!

I'm sure we'll get this into the upcoming hotfix. :thinking:
