### ISSUE TITLE
Dashlets order changed in 2.7

### ISSUE THREAD

**Issue by PitWenkin** [Icinga/icingaweb2#3889]
## Describe the bug
After update to 2.7 the order of our customised dashlets was partially changed
## To Reproduce
It seems that the 3 'default' dashlets `Host Problems`, `Service Problems`, and `Recently Recovered Services"` will now always be added in that order, even if their Url's are customised.

The only way to get a customise order of those dashlets, is to remove the default dashlets, an add new ones with **slightly different names**.

My current dashboard.ini now looks like this:

>  [Current Incidents.Host Problems]
> url = "monitoring/list/hosts?host_problem=1&sort=host_severity"
> title = "Host Problems"
> disabled = "1"
> 
> [Current Incidents.Recently Recovered Services]
> url = "monitoring/list/services?service_state=0&limit=10&sort=service_last_state_change&dir=desc"
> title = "Recently Recovered Services"
> disabled = "1"
> 
> [Current Incidents.Service Problems]
> url = "monitoring/list/services?service_problem=1&limit=10&sort=service_severity"
> title = "Service Problems"
> disabled = "1"
> 
> [Current Incidents.Services Problems]
> url = "monitoring/list/services?service_problem=1&host_in_downtime!=1&service_in_downtime!=1&host_problem!=1&sort=service_severity&service!=apt&service!=apt-slow"
> title = "Services Problems"
> 
> [Current Incidents.Recently Recovered]
> url = "monitoring/list/services?service_state=0&limit=10&sort=service_last_state_change&dir=desc"
> title = "Recently Recovered"
> 
> [Current Incidents.Hosts Problems]
> url = "monitoring/list/hosts?host_problem=1&sort=host_severity&host_in_downtime!=1"
> title = "Hosts Problems"
> 
> [Current Incidents.Apt]
> url = "monitoring/list/services?(service=apt|service=apt-slow)&service_problem=1&host_in_downtime!=1&service_in_downtime!=1"
> title = "Apt"

## Expected behavior
Update should not have f***ed up my (and my colleagues) dashboard

## Screenshots
This is what I had before the update (and after changing the dashboard.ini)

![Dashboard](https://user-images.githubusercontent.com/45786226/62271457-f9957280-b438-11e9-9ce8-836d52d470c6.png)

This is how the dashboard settings screen looks like now:

![Screen Shot 2019-08-01 at 08 42 29](https://user-images.githubusercontent.com/45786226/62271291-87bd2900-b438-11e9-9b37-3d15f9932679.png)

## Your Environment
Icinga Web 2 Version
2.7.0
Git commit
861c5601b6e01402a932687d7b59a037c72a6804
PHP Version
7.0.33-0ubuntu0.16.04.5
Git commit date
2019-07-30

**Comment by Goldie2009** [comment]
The order can be repaired this way. However, I think this must be done quite laboriously for each user.
During the last update to 2.7.0-1 also the link 'Show more' seems to have been 'rationalized' away.

**Comment by nilmerg** [comment]
Hi, sorry for the inconvenience.

A customized order of dashlets was never supported though. It has ever been only possible by re-ordering them in the INI file manually or simply by updating them one after another in the order they should appear.

That this is now gone is a side-effect of the fix in #3837 because section names are now nothing more than identifiers and the processing of user dashboards can't influence the order of default dashlets anymore due to that.

Custom dashboard panes however show still the same behavior. So for full control over the order of dashlets you'll need to create your own panes.

Full dashboard customization is still a thing in #3809. May be part of the next major release.

**Comment by nilmerg** [comment]
The missing *Show More* is a bug and caused by #3891.

**Comment by PitWenkin** [comment]
> During the last update to 2.7.0-1 also the link 'Show more' seems to have been 'rationalized' away.

Same for me … did not yet see that one

> A customized order of dashlets was never supported though. It has ever been only possible by re-ordering them in the INI file manually or simply by updating them one after another in the order they should appear.

I definetly did not do it via the INI file, therefore probably did it via updating them via the interface

> That this is now gone is a side-effect of the fix in #3837 because section names are now nothing more than identifiers and the processing of user dashboards can't influence the order of default dashlets anymore due to that.

ok.

> Full dashboard customization is still a thing in #3809. May be part of the next major release.

👍
