### ISSUE TITLE
Menu item state badges glitch

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2#3890]
The state badge for problems is rendered in a new line instead of to the side.

![Bildschirmfoto von 2019-08-01 09-19-04](https://user-images.githubusercontent.com/121874/62273559-2009dc80-b43e-11e9-8155-b9fe8d66ea17.png)

The error is likely to be caused due to float behavior, the badge should be added **before** the icon in my opinion.

![Bildschirmfoto von 2019-08-01 09-24-54](https://user-images.githubusercontent.com/121874/62273642-4d568a80-b43e-11e9-977e-d83d2ca31e3c.png)

~~But I never seen this problem apart from one customer site. If you like to have a look, visit me at my desk :wink:~~

I can also reproduce this in other environments with Firefox 60.x

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.6.3 and 2.7.0
* Web browser used: Firefox 60.3.0esr on Windows Server

**Comment by nilmerg** [comment]
That's a bug in Firefox. Has already been reported. (#3791)
