### ISSUE TITLE
Default sort rules no longer work in 2.7.0

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2#3891]
## Describe the bug

Something is wrong with the statehistory:

* sorting is not correct
* ~~certain statechanges are not shown~~
* ~~or only notifications are visible in its place~~
* ~~the latest event is not shown, but olders are~~

## Screenshots

2.7.0

![Bildschirmfoto von 2019-08-01 09-41-58](https://user-images.githubusercontent.com/121874/62274732-bccd7980-b440-11e9-8811-4518319fbb6f.png)

2.6.3

![Bildschirmfoto von 2019-08-01 09-40-13](https://user-images.githubusercontent.com/121874/62274727-b939f280-b440-11e9-81d1-9fed128d4648.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.7.0
* Web browser used: Chrome and Firefox
* Icinga 2 version used (`icinga2 --version`): 2.10.5

**Comment by nilmerg** [comment]
@lippserd Is that what #3836 caused? Please don't tell me we forgot to fix this :neutral_face:

**Comment by lazyfrosch** [comment]
I just noticed: There is no sorting at all

**Comment by lazyfrosch** [comment]
Longer screenshots

2.7.0

![Bildschirmfoto von 2019-08-01 10-03-40](https://user-images.githubusercontent.com/121874/62276151-b55b9f80-b443-11e9-9d96-b43ba12610be.png)

2.6.3

![Bildschirmfoto von 2019-08-01 10-02-51](https://user-images.githubusercontent.com/121874/62276154-b55b9f80-b443-11e9-9ec0-beab9d282885.png)

**Comment by nilmerg** [comment]
This seems to also affect the *Show More* link in list overviews. The dashboard and search don't show them anymore. (Reported by @Goldie2009 in #3889)

**Comment by NetworkNub** [comment]
Reverting #3836 restores proper sorting and the load more link for me

**Comment by mafri27** [comment]
I had the same problem. Servicehistory only shown the OK-events. Reverting #3836 fixed it.

**Comment by bunghi** [comment]
+1

**Comment by danielgohlke** [comment]
+1

**Comment by cfcnigel** [comment]
do you already have an idea when this will be fixed?  this is a big problem for us. Thankyou

**Comment by hardoverflow** [comment]
We have the same behavior with 2.7.0.

**Comment by lippserd** [comment]
Hi,

Thanks to all for the report and sorry for the bug. 2.7.1 will be released next week.
Feel free to apply the linked PR as patch.

Best,
Eric

**Comment by dnsmichi** [comment]
Here's some feedback from Twitter: https://twitter.com/icinga/status/1159119367197679616
