### ISSUE TITLE
Theme solarized-dark on 2.7.0 has contrast issues / ambiguous controls

### ISSUE THREAD

**Issue by Diftraku** [Icinga/icingaweb2#3892]
## Describe the bug
After updating Icinga Web 2 to 2.7.0 via CentOS repos, I noticed couple issues with the choice of colours causing some issues with either text being invisible or control elements having ambiguous states due to their colours.

## To Reproduce
1. Update Icinga Web 2 to version 2.7.0
2. Browse to the login page (first issue)
3. Login and open any service with at least warning state, click acknowledge (first issue, textareas)
4. On the same page, further down on the form (second issue).
5. Navigate to Configuration -> Application (first issue, dropdowns)
6. On the same page, after the options (nitpick on the button colours)

## Expected behavior
Text should be clearly visible on the appropriate elements and the controls should not be ambiguous if they are toggled or not.

## Screenshots
First one is visible on the login page (the username field has `helloworld` written in it):
![image](https://user-images.githubusercontent.com/171226/62276983-e50fa500-b44d-11e9-814d-e1791e27be2e.png)
This is also present on textareas (the textarea has `Hello world!` written in it):
![image](https://user-images.githubusercontent.com/171226/62277147-3455d580-b44e-11e9-9cc4-197f6bc17058.png)
And on dropdowns:
![image](https://user-images.githubusercontent.com/171226/62277351-ab8b6980-b44e-11e9-96b9-51ee09d041b5.png)

The second issue relates to the toggles: which ones are enabled and which are disabled?
![image](https://user-images.githubusercontent.com/171226/62277190-4f284a00-b44e-11e9-8aad-c65755a4d94e.png)

As a last nitpick, the primary/secondary colours for the buttons could use some love:
![image](https://user-images.githubusercontent.com/171226/62277325-9a425d00-b44e-11e9-86bd-911ca00b0b8b.png)

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.7.0
* Web browser used: Google Chrome v75.0.3770.142 (64-bit)
* Icinga 2 version used (`icinga2 --version`): r2.10.5-1
* PHP version used (`php --version`): 7.0.27
* Server operating system and version: CentOS Linux release 7.6.1810 (Core)

## Additional context
SELinux is not enabled on the server.

**Comment by nilmerg** [comment]
Hi, thanks for the report!

We seem to have overlooked our own themes. :roll_eyes: 

@theFeu Please have a look at all the built-in themes and fix them if they show the same issue.

**Comment by flourish86** [comment]
@theFeu Can you please adjust the colours of the form like the following? This way it's more consistent with the dark color style.

![Artboard](https://user-images.githubusercontent.com/6977434/62295321-0b910880-b46d-11e9-8562-a0733dd530b0.jpg)

**Comment by theFeu** [comment]
@flourish86 I used the same background colour as in the sidebar now, because I felt like the blue-ish colour you chose doesn't work too well with the dropdown-triangles for the selects.
The contrast is less crisp, but I think it still fits the theme :)


![image](https://user-images.githubusercontent.com/22217062/62358104-5e71cb00-b514-11e9-8b47-89a96e8aef2a.png)

**Comment by Diftraku** [comment]
Both of these are a big improvement over the current one. Could the toggle colouring be inverted so the state is not ambiguous (dim when off, bright when on)?

**Comment by theFeu** [comment]
@Diftraku  It's still a work in progress, I will update it over the course of the day :)

**Comment by theFeu** [comment]
Added love to toggles, input backgrounds and buttons!

![image](https://user-images.githubusercontent.com/22217062/62365592-c3cdb800-b524-11e9-8983-8781811f042e.png)

**Comment by theFeu** [comment]
Also adapted the sidebar colours in the last commit - if there is anything I overlooked, please do tell!
@Diftraku: There is no such thing as being too nitpicky, appreciate the help in spotting inconsistencies! :)

![image](https://user-images.githubusercontent.com/22217062/62374843-2468ef00-b53d-11e9-8885-3bb8bbd476ee.png)

**Comment by flourish86** [comment]
The editor controls also need to be adjusted. Could you take care of it as well, @theFeu?

![Screenshot 2019-08-05 at 11 25 42](https://user-images.githubusercontent.com/6977434/62454039-d984ec80-b773-11e9-893f-7b56724cda3c.png)

**Comment by nilmerg** [comment]
While I see this, please remember that our form styles are now encapsulated in two main classes: `icinga-form` (layout), `icinga-controls` (style)

Because the editor shouldn't require any special styles, instead it should apply to the general form style. (Since it has class `icinga-controls` applied to it)

**Comment by theFeu** [comment]
@nilmerg 
Made it apply to `icinga-form` and `controls` now, that ok?

**Comment by nilmerg** [comment]
Maybe, though without a PR I don't look at the code :wink:
