### ISSUE TITLE
LoginForm errors look bad

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#3894]
![Bildschirmfoto von 2019-08-01 14-45-36](https://user-images.githubusercontent.com/16668527/62294383-121e8080-b46b-11e9-8598-20862ee66eb6.png)

**Comment by lippserd** [comment]
@Thomas-Gelf Also reported something like. Please see the screenshot.

![abigkgoncbgbiooh](https://user-images.githubusercontent.com/1894563/62460799-45bb1c80-b783-11e9-8ac0-5ff1b0767a93.png)

**Comment by lippserd** [comment]
@flourish86 Could you please have a look here.

**Comment by flourish86** [comment]
Should be fixed by fab25f87. Could you please check, @lippserd?
