### ISSUE TITLE
Old History Data on Services

### ISSUE THREAD

**Issue by cfcnigel** [Icinga/icingaweb2#3896]
## Describe the bug
The History tab of a service displays old data. New events are missing

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

Click on a service in the dashboard.
then on the tab History
Here all events concerning the service are displayed.

My data is not up to date here

Funny is that the sorting is totally confused .. However, all events are old, although the service was critical yesterday.

However, if I go to the event overview via the menu on the left and search for the service concerned, I can see the correct and up-to-date data.

The same problem have of all my services.

The data is sent via a satellite to the master. but also on the satellite the data are displayed incorrectly.

As a test, I have created a downtime, even this is not displayed in the tab History.

## Screenshots
![image](https://user-images.githubusercontent.com/49064657/62367646-9126be00-b52a-11e9-80d7-0c19367f6066.png)

![image](https://user-images.githubusercontent.com/49064657/62366908-72272c80-b528-11e9-8618-a4c50a41e67b.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.7.0
* Web browser used: r2.10.5-1
* Icinga 2 version used (`icinga2 --version`): Chrome 
* PHP version used (`php --version`): PHP 7.0.33-0ubuntu0.16.04.5
* Server operating system and version: Ubuntu 16.04.6 LTS

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This is a dup of #3891. Will be fixed asap!

Best,
Eric
