### ISSUE TITLE
Sidebar not found

### ISSUE THREAD

**Issue by zilchms** [Icinga/icingaweb2#3909]
## Describe the bug
On a new installation of Debian, Icinga2 and Icingaweb2, following the official documentation, the
sidebar only is shown for a short time and then is replaced by a "Not Found" error.
The error description provided is:
"The requested URL /icingaweb2icingaweb2....icingaweb2/layout/menu was not found on this server"
Debugging with the browserconsole, shows several exceptions being thrown, such as "SyntaxError: ':hidden' is not a valid selector", however those seem be getting caught.

## To Reproduce
1. Install Icingaweb2 on a fresh Debian 9 installation
2. Configure the icinagweb2 configs for backend as seen fit, i personally use puppet for configuration with ldap backend
3. Open Icingaweb2 with a browser of your choice, I have only tested this for Firefox

## Screenshots
![Icinga](https://user-images.githubusercontent.com/30926421/62820420-547b4800-bb64-11e9-8ac2-007e28d81f35.png)

## Your Environment

* Icinga Web 2 version and modules: Current Debian Stretch Release: Icingaweb2 2.4.1-1, with corresponding modules doc and monitoring
* Web browser used: Firefox
* Icinga 2 version used (`icinga2 --version`): Icinga2 version r2.6.0-1
* PHP version used (`php --version`): PHP 7.0.33
* Server operating system and version: Debian Stretch Release: 9.9

## Additional context
No additional configurations have been done to the Apache2 Config, aside from the configuration done by the puppet module for icingaweb2, it should be as it comes with a clean debian installation.
I am not sure if the error is located in Icingaweb2 or in the puppet module.
Any help would be welcome.

**Comment by dnsmichi** [comment]
Sounds like a problem in the Vhost config. Since you're using an old version, I'd suggest using our official package repos from https://packages.icinga.com which brings you 2.7 ... icinga2 2.6 also is out of support already.

**Comment by zilchms** [comment]
ok thanks, I will have a look into that.

**Comment by zilchms** [comment]
Ok, I have setup a fresh VM in case my apache2 config has had errors. I have brought the packages up to version 2.7.0.1. However the problem still remains the same.

**Comment by dnsmichi** [comment]
Can you share your apache configuration? There's some rewrite in place which renders the URL like `icingaweb2icingaweb2icingaweb2...`. Maybe the RewriteBase has been modified and is now foobar.

**Comment by nilmerg** [comment]
This is most surely a configuration issue. Maybe also related to redirection.

I'll close the issue now. Though, discussion is still open.

**Comment by zilchms** [comment]
I have the configuration files for my apache2 attached below. If you need more/ other files let me know.


[configurations.zip](https://github.com/Icinga/icingaweb2/files/3496292/configurations.zip)

**Comment by dnsmichi** [comment]
```
<Directory /usr/share>
    AllowOverride None
    Require all granted
</Directory>
```

Not an apache expert here, but AllowOverride=None might be culprit here. Chances for help are higher at https://community.icinga.com btw.

**Comment by zilchms** [comment]
Ok, thanks. I am new to webadministration myself. I will move the discussion to the community forum.
