### ISSUE TITLE
Filter editor parser fails with complex filters

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icingaweb2#3910]
## Summary
While the filter editor can be used to create simple filters by entering the filter expression in the text entry field, it fails to parse slightly more complex filter expressions

## Steps to Reproduce
Enter the filter expression `hostgroup_name!=test-hosts&servicegroup_name!=test_services` in the text entry field of the filter editor, then click on the filter icon.

## Expected Result
The filter expression parsed looks like this:
```
AND
|- Hostgroup Name != test-hosts
|- Servicegroup Name != test-services
```

## Actual Result
```
|- Hostgroup Name != test-hosts & servicegroup_name!
```

It is possible to produce the expected (and working) result by clicking it together in the GUI. If this is done, the resulting textual representation is exactly the one shown above. 

## Environment
Icinga Web 2 versions 2.6.3 and 2.7.0, CentOS 7, Icinga 2.10.5/2.11, PHP 7.1 from the CentOS SCL packages.

**Comment by nilmerg** [comment]
Hi,

I'm afraid but I thought you were talking about the restriction field in a role's configuration. The search box of the filter editor is not meant to accept chained conditions, the most complex thing you can enter there is a single comparison. (e.g. `foo!=bar`) If you want to apply more complex filters by copy&paste you need to adjust the url in your address bar.

Though, we are aware that some of you want to enter more complex filters there. That's already covered by #3631 and #1748.

**Comment by peteeckel** [comment]
So if the text field is not supposed to accept complex queries, why does it accept and mis-interpret them? Good to now there's something in the works, the current state is at least confusing.
