### ISSUE TITLE
Host or Service History ordering weird

### ISSUE THREAD

**Issue by patlicht** [Icinga/icingaweb2#3912]
# Problem
Sorting of the host or service history is weird, see screenshot.

PHP Timezone: Europe/Zurich
Tested with version: 2.7.0-1.bionic 

# Expected Result
History Items should be ordered by date.

# Screenshot
![history-sorting](https://user-images.githubusercontent.com/47595675/62864061-02c0f200-bd0b-11e9-9320-e6bc50419021.png)

**Comment by nilmerg** [comment]
Hi, this has already been reported in #3901. Closed as duplicate.
