### ISSUE TITLE
Hostgroups "AND" filter stopped working with 2.7.0

### ISSUE THREAD

**Issue by nE0sIghT** [Icinga/icingaweb2#3916]
## Describe the bug
After upgrading to Icinga Web 2 version 2.7.0 ```OR``` filter with ```hostgroup``` fields stopped to work

## To Reproduce
1. Create hostgroup contains word "foo" in name (not in Display name)
2. Create hostgroup contains word "bar" in name (not in Display name)
3. Create hostgroup filter ```Hostgroup = *foo* OR Hostgroup = *bar*``` (in the URL it would be ```hostgroup=*foo*|hostgroup=*bar*```).

## Expected behavior
Both hostgroups contains "foo" and "bar" should appear in search list

## Your Environment
* Icinga Web 2 Version 2.7.0
*  PHP Version 7.1.8
* director	1.6.0
* doc	2.7.0
* grafana	1.3.4
* incubator	v0.1.1
* ipl	v0.1.1
* monitoring	2.7.0
* reactbundle	v0.4.1
* translation	2.7.0
* vspheredb	1.0.3
* x509	1.0.0
* Web browser used: Google Chrome latest
* Icinga 2 version used (`icinga2 --version`): r2.10.5-1
* PHP version used (`php --version`): 7.1.8
* Server operating system and version: RHEL 7

**Comment by nilmerg** [comment]
Hi, thanks for reporting this. But it's a known (#3886) and fixed (#3903) issue.

**Comment by nE0sIghT** [comment]
@nilmerg 
The fix doesn't works for me with filter  ```Hostgroup != *foo* AND Hostgroup != *bar* AND Hostgroup != *qwe*```

**Comment by nilmerg** [comment]
Yes, you're right. Thanks for the feedback. We're working on it. :+1:

**Comment by lippserd** [comment]
Hi @nE0sIghT,

Thanks for reporting the issue. Do you have any chance to test the related PR?

Best,
Eric

**Comment by nE0sIghT** [comment]
Sure. I can test it tomorrow.

вт, 13 авг. 2019 г., 19:21 Eric Lippmann <notifications@github.com>:

**Comment by nE0sIghT** [comment]
@lippserd 
Just tested PR - it works for me for both ```OR/AND``` with/without negations.
