### ISSUE TITLE
Selection of multiple downtimes fails

### ISSUE THREAD

**Issue by GeoMight** [Icinga/icingaweb2#3920]
## Describe the bug

When I select one downtime and want to select another one:

a) to have selected more than one with ctrl/command
b) select another one to select all from-to(shift)

Selected are ALL downtimes.

No matter if I have a tab with only 25 downtimes selected.
No matter if I use filters.

**This works in service and was working before 2.7, and 2.7.1**

## To Reproduce

Steps:
1. Have at least 2 downtimes
2. Left-click one
3. Holding command/ctrl/shift select another one

What you can observe is that the url changes:

/monitoring/list/downtimes?page=1#!/monitoring/downtimes/show?(()|())
The last part **(()|())** is reposible for selected elements each `()` is 1 element so for
command/ctrl we always have 2 - (()|())

For Selection with a shift of 3 elements, we have  (`()`|`()`|`()`)

Selected items are not highted

## Expected behavior

Working as services, ~ before 2.7

## Screenshots

I selected 2 items:

![Screenshot 2019-08-15 at 12 16 14](https://user-images.githubusercontent.com/26327820/63089268-8cfd9600-bf57-11e9-8272-a32731c81ed4.png)

## Your Environment
```bash
icinga-rpm-release.noarch        7-2.el7.centos                  installed
icinga2.x86_64                   2.10.5-1.el7.icinga             @icinga-stable-release
icinga2-bin.x86_64               2.10.5-1.el7.icinga             @icinga-stable-release
icinga2-common.x86_64            2.10.5-1.el7.icinga             @icinga-stable-release
icinga2-ido-mysql.x86_64         2.10.5-1.el7.icinga             @icinga-stable-release
icinga2-selinux.x86_64           2.10.5-1.el7.icinga             @icinga-stable-release
icingacli.noarch                 2.7.1-1.el7.icinga              @icinga-stable-release
icingaweb2.noarch                2.7.1-1.el7.icinga              @icinga-stable-release
icingaweb2-common.noarch         2.7.1-1.el7.icinga              @icinga-stable-release
icingaweb2-selinux.noarch        2.7.1-1.el7.icinga              @icinga-stable-release
icingaweb2-vendor-HTMLPurifier.noarch
                                 1:2.7.1-1.el7.icinga            @icinga-stable-release
icingaweb2-vendor-JShrink.noarch 2.7.1-1.el7.icinga              @icinga-stable-release
icingaweb2-vendor-Parsedown.noarch
                                 2.7.1-1.el7.icinga              @icinga-stable-release
icingaweb2-vendor-dompdf.noarch  2.7.1-1.el7.icinga              @icinga-stable-release
icingaweb2-vendor-lessphp.noarch 2.7.1-1.el7.icinga              @icinga-stable-release
icingaweb2-vendor-zf1.noarch     2.7.1-1.el7.icinga              @icinga-stable-release
php-Icinga.noarch                2.7.1-1.el7.icinga              @icinga-stable-release
```

```bash
The Icinga 2 network monitoring daemon (version: r2.10.5-1)
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-957.27.2.el7.x86_64
  Architecture: x86_64
```

Chrome Version 76.0.3809.100 (Official Build) (64-bit)
The Icinga 2 network monitoring daemon (version: r2.10.5-1)
PHP 7.1.8 (cli) (built: Aug  9 2017 13:20:06) ( NTS )
Mac 10.14.5 (18F132)

**Comment by PitWenkin** [comment]
I can confirm this, i had it in 2.7 and was hoping 2.7.1 would fix it, which id did not.

On the overview for all services of a host e.g. `/monitoring/host/services?host=…` (even if host and services are in downtime) multiselect still works.

**Comment by nilmerg** [comment]
@GeoMight Thanks for reporting this. Though it does not only affect multi-selection nor just downtimes. A downtime's detail view is also not reachable and the comment overview is also affected. I've identified the cause and prepared a fix already. PR incoming.

@PitWenkin If you noticed it already with 2.7.0 why not reporting it? Hoping that someone else does it now went exactly the way it was to be expected. :neutral_face:

**Comment by PitWenkin** [comment]
@nilmerg I saw it once and could at that time not really describe it…

**Comment by cfcnigel** [comment]
Hi, the problem still exists in 2.7.1. it occurs only on downtimes. selecting multiple host or services everything is working fine.
