### ISSUE TITLE
Removing Downtime Muted tab

### ISSUE THREAD

**Issue by webairjon** [Icinga/icingaweb2#3929]
Appears since the last couple updates, I am unable to ctrl+select multiple hosts to remove downtime in the muted tab. 
Any attempts to remove multiple downtimes on hosts from the 'Muted' tab the selection is not functioning properly.

 I can remove the downtime for 1 host, but if I select multiple, ie. 2 or 10 or 15 it only asks me to remove ALL hosts (161 hosts in this case) downtime. There is nothing in between.

How to replicate, select muted tab, and attempt to highlight 2+ hosts and remove the downtime. You will see it only allows 1 host or all. 

Icinga Web 2 Version
2.7.1
Git commit
b0bf9c4b0637f6113adb788e78c2bcf619225dd8
PHP Version
7.1.8
Git commit date
2019-08-14
Copyright
© 2013-2019 The Icinga Project

**Comment by webairjon** [comment]
Appears since the last couple updates, I am unable to ctrl+select multiple hosts to remove downtime in the muted tab.
Any attempts to remove multiple downtimes on hosts from the 'Muted' tab the selection is not functioning properly.

I can remove the downtime for 1 host, but if I select multiple, ie. 2 or 10 or 15 it only asks me to remove ALL hosts (161 hosts in this case) downtime. There is nothing in between.

How to replicate, select muted tab, and attempt to highlight 2+ hosts and remove the downtime. You will see it only allows 1 host or all.

Icinga Web 2 Version
2.7.1
Git commit
b0bf9c4
PHP Version
7.1.8
Git commit date
2019-08-14
Copyright
© 2013-2019 The Icinga Project

**Comment by dnsmichi** [comment]
Hi,

please don't double post nor bump issues. Also, please use the issue search before creating a new one. Yours is covered in #3920 which links a PR to test already. Closing here.

Cheers,
Michael
