### ISSUE TITLE
Problem during upgrade

### ISSUE THREAD

**Issue by r4a5a88** [Icinga/icingaweb2#3930]
## Describe the bug
When I upgrade icingaweb2 to its newest version, this happens.
The website appears, but I can't login and the design is gone.
apache does not see a relevant error.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1.  install icinga2 on debian container with icingaweb2 
2.  upgrade in stretch or dist-upgrade to buster

## Expected behavior
I expected the upgrade to smooth and with out any problems 

## Screenshots
![icinga](https://user-images.githubusercontent.com/22817846/63676891-33655900-c7ec-11e9-9437-3e504782993b.PNG)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.6.3
* Web browser used: Firefox / Opera
* Icinga 2 version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.5-1)
* PHP version used (`php --version`): 7.0 and yes, I had the error with php 7.3
* Server operating system and version: Debian 9 
* Icinga2 feature enabled : api checker command graphite ido-mysql mainlog notification perfdata

**Comment by dnsmichi** [comment]
That looks as if Javascript and CSS is not loaded, maybe for a caching or config problem reason. Try investigating on the development console from the browser whether some resources cannot be loaded. Also, look into you webserver's log for possible errors.

**Comment by r4a5a88** [comment]
apache error log 
```
[Tue Aug 27 13:07:08.671061 2019] [core:info] [pid 7845] [client 127.0.0.1:59114] AH00128: File does not exist: /var/www/html/tags/tagMultiSeries
[Tue Aug 27 13:07:12.691143 2019] [authz_core:debug] [pid 7845] mod_authz_core.c(809): [client 127.0.0.1:59114] AH01626: authorization result of Require all granted: granted
[Tue Aug 27 13:07:12.691165 2019] [authz_core:debug] [pid 7845] mod_authz_core.c(809): [client 127.0.0.1:59114] AH01626: authorization result of <RequireAny>: granted
[Tue Aug 27 13:07:12.691206 2019] [core:info] [pid 7845] [client 127.0.0.1:59114] AH00128: File does not exist: /var/www/html/tags/tagMultiSeries
```
I got the same error before the upgrade 
Firefox gave me 
`
13:02:37.807 Someone messed up our responsiveness hacks, html font-family is serif icinga.min.js:18:537`
and if you fold out the error message you get
`writeToConsole error layoutHasBeenChanged onWindowResize triggerWindowResize initialize initialize Icinga  lc`
I searched the icingaweb2 folders and could not find the icinga.min.js file 
do you know where it is or how its generated

**Comment by r4a5a88** [comment]
I found the problem. Ther is something wrong with the theme I created. When I switched the themes it works fine.

**Comment by dnsmichi** [comment]
AFAIK the minified version from JS is created on-demand. You can disable this behaviour with enabling the development mode by adding `_dev=1` to the URL params. https://icinga.com/docs/icingaweb2/latest/doc/20-Advanced-Topics/#global-url-parameters

**Comment by r4a5a88** [comment]
i went back to the original theme of icinga2web. Is there a theme template ?

**Comment by nilmerg** [comment]
Hi, we've upgraded the library which is responsible to parse LESS with 2.7.0. Since then it complains about every undefined variable or mixin and the CSS will not load.

Make sure to only utilize variables/macros/mixins in your theme which exist and the problem should be gone. The exact error message should appear by visiting: /icingaweb2/css/icinga.css
