### ISSUE TITLE
Recently Recovered Services in dashboard "Current Incidents" seems out of order

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2#3931]
## Describe the bug
Clicking on a service in the main built-in "Current Incidents" dashboard orders "Recovered Services" above. This makes parsing difficult when things get busy, as it pushes the actual service issues further down. I don't believe this was the behavior prior to Icingaweb2 2.7.0

![Screen Shot 2019-08-26 at 10 58 50 AM](https://user-images.githubusercontent.com/27829577/63700623-462e5c80-c7f1-11e9-8602-273310a94770.png)

![Screen Shot 2019-08-26 at 11 03 03 AM](https://user-images.githubusercontent.com/27829577/63700607-3adb3100-c7f1-11e9-8e86-2362532d3c30.png)

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Install Icinagweb 2.7.0+

## Expected behavior
The host/service problems should be presented first for the "Current Incidents" dashboard.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version
2.7.1
Git commit
b0bf9c4b0637f6113adb788e78c2bcf619225dd8
PHP Version
7.1.30
Git commit date
2019-08-14
```
* Web browser used: Chrome/Firefox
* Icinga 2 version used (`icinga2 --version`): r2.10.5-1
* PHP version used (`php --version`):
```
/opt/rh/rh-php71/root/usr/sbin/php-fpm --version | head -n 1 | awk '{print $2}'
7.1.30
```

* Server operating system and version:
```
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```

**Comment by log1-c** [comment]
Can confirm, that when having _English_ selected as language, the Recently Recovered Services list will be placed above the Service Problems list, after clicking on on of the recently recovered checks.
![image](https://user-images.githubusercontent.com/24474580/63762515-30896780-c8c3-11e9-84f8-94393b79f5c0.png)

With a dashboard set to _German_ language this does not happen.
![image](https://user-images.githubusercontent.com/24474580/63762577-5c0c5200-c8c3-11e9-90c2-2579ddfc9635.png)

**Comment by mtdeguzis** [comment]
The default order appears to be

1. service problems
2. Recently recovered services
3. Host problems

Should this order always be:

1. service problems
2. host problems
3. Recently recovered 1 or 2

?

![image](https://user-images.githubusercontent.com/27829577/67013881-d8e8ca80-f0c1-11e9-8681-00c0232ce09d.png)

```
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.0-1)
```

Am I incorrect here, or should I open a new issue?

**Comment by nilmerg** [comment]
Nope. The order with v2.6.3 is:

1. service problems
2. Recently recovered services
3. Host problems

And that's what it is for me with v2.7.2.

**Comment by mtdeguzis** [comment]
Got it @nilmerg , thanks for confirming.
