### ISSUE TITLE
Icon handling

### ISSUE THREAD

**Issue by bitboy85** [Icinga/icingaweb2#3933]
1. Currently icingaweb uses 32x32 (or maybe 48x48) icons in most cases, except the user defined ones for hosts and services in the overview section which only uses 16x16.
I think it would look better having larger icons there, for example:
![example](https://user-images.githubusercontent.com/6197580/63851010-a52cd680-c995-11e9-951d-5e2ee8f7d4ce.png)

2. Not sure if its related to icingaweb2 or director, but i think it would be useful if subdirectories of /usr/share/icingaweb2/public/img/icons/ would be possible as most icon packs uses subdirectories.

**Comment by nilmerg** [comment]
Hi,

1. Icinga Web 2 doesn't use any images as icons. Though, you're correct that user-defined icons are limited in width. That's 24px for me. (Depending on the resolution, but shouldn't differ much for you)
2. You can put as many directories (with sub-directiories) as you want in `public/`. Then just define their relative path as icon. (e.g. `public/fo/ob/ar.png` needs to be `fo/ob/ar.png`)

I don't think allowing bigger icons there is a good idea here. It's a list after all with many entries, just think of a full list where every single entry got such a big icon.

@flourish86 What do you think?

**Comment by bitboy85** [comment]
Hi,

so the relative path to start is /usr/share/icingaweb2/public ? i used the full path given in my first post. i'll give it a try and report back.

i had in mind if someone is scrolling through the list and knows he searches for a windows machine, an icon is faster to identifiy than reading trough all the text or host names.
Like scrolling through a large list of files, instead of searching for the name you just look for the icon thats associated with.

**Comment by nilmerg** [comment]
Hi.

I've told you how to use sub directories and hope this worked for you.

Since bigger icons would really be more disturbing if there are many of them (especially if they're still shown at their current placement), I'll close this issue now. Also, we're currently working on a redesign of these views to this may change anyway.
