### ISSUE TITLE
Passive checks history details

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2#3937]
## Is your feature request related to a problem? Please describe.

Currently in the History tab of a service you only can see events when service state changes. For the passive checks it would be very useful to see all the messages sent to the service even if the state didn't change.

Example in our environment:
A backup script is sending passive messages to Icinga2 during the script in different moments (when it starts, when it stops database, when it finished backup of db, when it starts db and when it finished execution).  Having all these details in the History tab would help us to see how it went.. 

## Describe the solution you'd like
See all passive messages sent to Icinga2 in the history tab, not only when state changed.

**Comment by nilmerg** [comment]
Hi, we're just reading what's in the database regarding an object's history. If there's something missing, we can't do anything to show it. It's probably the core which is not writing all events to the database. Besides that, there's probably a better way than utilizing passive checks as progress report.
