### ISSUE TITLE
Group overviews provide invalid filter columns

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2#3940]
## Describe the bug
When filtering the host groups list view, errors occur when filtering for the following parameters:

* `services_total`
* `hosts_total`
* others: `host`, `host_alias`, `host_display_name`, `hosts_down_handled`, `hosts_pending`, `hosts_severity`, `hosts_unreachable_handled`, `hosts_unreachable_unhandled`, `hosts_up`, `service`, `service_display_name`, `servicegroup`, `servicegroup_alias`, `services_critical_handled`, `services_critical_unhandled`, `services_ok`, `services_pending`, `services_unknown_handled`, `services_unknown_unhandled`, `services_warning_handled`, `services_warning_unhandled`

## To Reproduce
1. Navigate to _Overview_ > _Hostgroups_
2. Open filter editor by clicking ![Screenshot 2019-09-03 at 13 45 47](https://user-images.githubusercontent.com/6977434/64170738-2500e800-ce51-11e9-9b95-fe9473f2959a.png)
3. Select one of the above mentioned parameters, e.g. _Hosts Total_
4. Type a value, e.g. _0_
5. Hit _Apply_

This will result in an error page, saying for example 
```
_Icinga\Module\Monitoring\Backend\Ido\Query\HostgroupQuery : Got invalid column: host_
```
when filtering for _Host_

## Expected behavior
The list should update and show the corresponding results

## Screenshots
![Screen Recording 2019-09-03 at 13 51 27](https://user-images.githubusercontent.com/6977434/64171246-7bbaf180-ce52-11e9-80df-4efac79d666c.gif)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 Vagrant Box, version 2.7
* Safari: Version 12.1.2 (14607.3.9)

**Comment by nilmerg** [comment]
It's a bug, yes. Though it's the fact that these columns are even suggested. We can't filter for such (aggregated) columns with the current query implementation.
