### ISSUE TITLE
Use disk status icon in custom scripts.

### ISSUE THREAD

**Issue by cristorrian** [Icinga/icingaweb2#3945]
Hi all, I have searched for all sites but i haven't found how to use the icon disk status in my custom scripts to show it in a particular service.
Any idea?

Sorry for my bad english.

I show an image.

![imagen](https://user-images.githubusercontent.com/51986864/64526437-9504e780-d303-11e9-87a7-b9469628dff8.png)

**Comment by nilmerg** [comment]
These little pie-charts are a result of the check's performance data. Any check which provides performance data that can be presented with a pie chart gets these. (e.g. percent values, or values with a minimum and maximum value)

For further questions please head over to https://community.icinga.com.

**Comment by cristorrian** [comment]
> These little pie-charts are a result of the check's performance data. Any check which provides performance data that can be presented with a pie chart gets these. (e.g. percent values, or values with a minimum and maximum value)
> 
> For further questions please head over to https://community.icinga.com.

Oh i see, i only had the maximum value set.
Thank you so much :)
