### ISSUE TITLE
Only the first 2 item could be marked in Downtime list

### ISSUE THREAD

**Issue by fscaptain** [Icinga/icingaweb2#3952]
## Describe the bug
It is not possible to mark more downtimes, could be only the first 2 item in the downtime list.

## To Reproduce
Could no mark multiple downtimes by selecting with ctrl-key or shift-key. Only the first 2 items are possible

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.7.1
* Web browser used: Chrome, FF 
* Icinga 2 version used (`icinga2 --version`): r2.10.5-1
* PHP version used (`php --version`): 7.0.33
* Server operating system and version: Debian 9

**Comment by nilmerg** [comment]
Hi, thanks for the report. Though this is a known issue (#3920) and as such I'll close this as duplicate.
