### ISSUE TITLE
Radio buttons have no style

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#3957]
![Bildschirmfoto von 2019-09-23 08-06-24](https://user-images.githubusercontent.com/16668527/65404519-1fa41700-ddd9-11e9-8062-ad67df4fee62.png)

* Disable/Enable flap detection for a single host/service (or any other feature)
* Select this host/service and multiple others where this feature is not disabled/enabled

**Comment by flourish86** [comment]
Here is a draft of how _multiple values_ should look in the multiselect detail.

![Screen Recording 2019-10-07 at 13 25 11](https://user-images.githubusercontent.com/6977434/66308059-62500e00-e906-11e9-88cd-a72e88958f8d.gif)
