### ISSUE TITLE
Filter Editor: Wrong results when filtering by check attempt

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2#3960]
## Describe the bug
Filtering by Service Attempt delivers wrong results.

## To Reproduce

1. Navigate to a service list, e.g _Overview_ > _Service_
2. Add a filter row with Service Attempt > 1
3. It will show Results, including ones that have attempts = 1

## Expected behavior

Filter results should only show services with attempts > 1, not >= 1

## Screenshots

![Screenshot 2019-09-23 at 14 15 25](https://user-images.githubusercontent.com/6977434/65425202-bc80a780-de0d-11e9-8117-18e73ec81206.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

![Screenshot 2019-09-23 at 14 26 08](https://user-images.githubusercontent.com/6977434/65425376-1bdeb780-de0e-11e9-8292-f7cb0140ed10.png)

Safari 13.0, macOS

**Comment by nilmerg** [comment]
I'm afraid but this is due to the fact that the database only knows about `"1/5"` and treats this as string during comparison. Hence only equal and unequal comparisons work as expected.

I'll close this since we have #3631 to enhance such cases.
