### ISSUE TITLE
 [BUG] Servicegroup filter for roles also hides host

### ISSUE THREAD

**Issue by sklaes** [Icinga/icingaweb2#3962]
## Describe the bug
Defining a servicegroup based filter for an authentication role will also[!] hide the host.

## To Reproduce
Create a ServiceGroup:
`object ServiceGroup "customer_services" 
{
    assign where match("*.customer.foo", host.name) && match("customer_*", service.name)
}`

And set the following filter for a role
`monitoring/filter/objects: "servicegroup_name!=customer_services"`

## Expected behavior
The filter should only filter the services that matches not the host object
(the filtering of servies is done corretly - reffer to the screenshot below)

## Screenshots
Searching for the Hostname

With Filter:
![image](https://user-images.githubusercontent.com/13706940/65594894-e663d680-df93-11e9-864f-122ba7af2e9f.png)

same search without filter in the role:
![image](https://user-images.githubusercontent.com/13706940/65595028-21fea080-df94-11e9-8cfd-0f44563c6436.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.7.1 (b0bf9c4b0637f6113adb788e78c2bcf619225dd8)
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.10
* PHP version used (`php --version`): 7.1
* Server operating system and version: Centos 7

**Comment by nilmerg** [comment]
Hi, we're already handling this in a different issue: #3550
