### ISSUE TITLE
Missing end date for scheduled downtimes on history tab

### ISSUE THREAD

**Issue by jschanz** [Icinga/icingaweb2#3968]
## Describe the bug
Date is missing for entries on history tab. Only time of entry time, trigger time, etc. is shown. So it's hard to do an investigation why a downtime was set and how long it lasts.

## To Reproduce
Schedule a downtime for a host or service for more than one day (e.g. 2019-10-02 11:01:44 to 2019-10-04 12:01:44)

## Expected behavior
Entries for entry time, trigger time, etc. also should show the date.

## Screenshots
![Auswahl_267](https://user-images.githubusercontent.com/5750462/66033078-da819280-e506-11e9-9bc2-aa8d4a6136ff.png)
![Auswahl_268](https://user-images.githubusercontent.com/5750462/66033083-dd7c8300-e506-11e9-80c2-5149d5a3fb1a.png)

## Your Environment
Icinga Web 2 - 2.7.1

**Comment by nilmerg** [comment]
Hi, you're right, thanks for the report! (Caused by #3660)
