### ISSUE TITLE
Unable to filter host that are members of more than one group

### ISSUE THREAD

**Issue by wp-perc** [Icinga/icingaweb2#3972]
## Describe the bug
You have a host object that is member of group A and B.

- If you search for hosts that are members of group A or B, the host object is displayed
- If you search for hosts that are members of BOTH groups A and B, no host will be displayed.

## Expected behavior
The host object should be displayed

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.6.2
* Web browser used: Any
* PHP version used (`php --version`): 7.1.8
* Server operating system and version: CentOS 7

**Comment by nilmerg** [comment]
Hi, this is a known and fixed issue. With 2.6.x versions it is unfortunately not fully fixed. Prior v2.7.0 this is only possible by writing the filter this way: `hostgroup_name=(groupA|groupB)`
