### ISSUE TITLE
Filter: more/less than doesn't seem to working

### ISSUE THREAD

**Issue by Foxeronie** [Icinga/icingaweb2#3974]
Hey!

I have a custom host variable "importance_level" that goes from 0 to 100.
When I try to filter hosts where this variable is more or less than a number I don't get the expected hosts.

## To Reproduce
- Create a custom host variable on multiple hosts with numbers between 0 and 100.
- Go to Overview -> Hosts
- Modify the filter
- add the filter importance_level>50

## Expected behavior
In my setup a lot of hosts should be shown, but the result is "No hosts found matching the filter."

## Screenshots
Host Inspection with var:
![filter_by_level_host-inspection](https://user-images.githubusercontent.com/10115997/66192086-07ad7c80-e690-11e9-8777-eb0669481fa6.png)

Host view with var:
![filter_by_level_host-tab](https://user-images.githubusercontent.com/10115997/66192087-07ad7c80-e690-11e9-93f4-1357d6f05000.png)

Filter search with no result:
![icinga_bug_servicegroup_filter](https://user-images.githubusercontent.com/10115997/66192088-07ad7c80-e690-11e9-940e-deaec4e7ee51.png)

## Your Environment
```
Icinga Web 2 Version
2.7.1
Git commit
c3603c991df2ae2e0e5d03968f54216f4086f198
PHP Version
7.0.33-0ubuntu0.16.04.5

Modules:
businessprocess
director
generictts
ipl
monitoring
reactbundle
x509
```

```
Chromium 76
```

```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.6 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-146-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: 9c880c2f42f5
```

```
Ubuntu 16.04.6
```

Best regards,
Patrick

**Comment by R-Sommer** [comment]
+1
