### ISSUE TITLE
No line breaks in notes field

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2#3976]
## Describe the bug
Notes field as of Icingaweb 2.7.1 no longer contains line breaks when viewed from overview services.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Create a service template
2. Create a service/service apply rule with multi-line text in the notes field
3. Apply

## Expected behavior
```
The note should look like this.
Link to docs: linkz
Hi!
```

## Screenshots
Instead, anything without an extra line in-between will not be line broken. This was not behavior prior to this version that I can recall.
![image](https://user-images.githubusercontent.com/27829577/66419954-fc7d8800-e9d2-11e9-90b9-8ad2fe8dbafc.png)
![image](https://user-images.githubusercontent.com/27829577/66419326-efac6480-e9d1-11e9-9d92-ef4fd13c2d0c.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 
  * Icinga Web 2 Version 2.7.1
  * Git commit b0bf9c4b0637f6113adb788e78c2bcf619225dd8
  * PHP Version 7.1.30
* Web browser used: Chrome v75
* Icinga 2 version used (`icinga2 --version`): 2.11.0-1
* PHP version used (`php --version`):
```
[root@udaicinga icingaweb2]# /opt/rh/rh-php71/root/usr/sbin/php-fpm -v
PHP 7.1.30 (fpm-fcgi) (built: Jul 10 2019 09:46:42)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

* Server operating system and version:
```
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
```

**Comment by nilmerg** [comment]
Hi, you're right. Though that's a side effect since we support Markdown in notes. I don't know if we can do anything here nor do I think it's sensible to prevent this automatically. It's a Markdown feature after all.

In case you don't know how to write new paragraphs:
* Put an empty line in-between (as you already noticed)
* Put two spaces before any new-line (the least intuitive solution, I know)

**Comment by mtdeguzis** [comment]
oh! If you support markdown, I can write in markdown-compliant text. Did this change in the last release or two? I suppose then this is a non-issue and I'll use MD.

**Comment by mtdeguzis** [comment]
For those that see this post, `<br>` works and is much more visible.

```
Impact: high <br>
Urgency: high <br>
```

Result:
![image](https://user-images.githubusercontent.com/27829577/66486127-03aaa180-ea78-11e9-9252-c0031f996ee2.png)

While hello\ works with a few Markdown parsers, it is not part of the specification and therefore some parsers ignore it. 

The double-space thing is a bad idea in general because many text editors automatically trim white-space at the end of each line upon saving. Its best to use a form that'll work for the most amount of people.

As (typical?) normal, you'll see the notes field update when a new check instance runs.
