### ISSUE TITLE
Option to select custom vars to be displayed after the hostname

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icingaweb2#3977]
## Describe the solution you'd like
I would like to have an option where i can select some important custom vars to be displayed after the hostname like:

![image](https://user-images.githubusercontent.com/7545210/66470886-bdab0900-ea8a-11e9-9bd4-22e6e1407aff.png)

## Additional context
A simple global option would be enough, where empty or non exists vars are silently skipped for host which don't have this var.

**Comment by nilmerg** [comment]
Hi,

there's already a parameter with which you can achieve this:

`/icingaweb2/monitoring/list/services?addColumns=_host_env,_host_department,_host_services`

Produces the following for me:
![Bildschirmfoto von 2020-05-13 14-46-44](https://user-images.githubusercontent.com/16668527/81814234-cedc5c80-9528-11ea-98d8-ed528451bd8d.png)

For Icinga DB Web we'll provide a nice widget and more so this is not just as hidden and *ugly*. :smile:
