### ISSUE TITLE
Disable Notification when getting into a better state (Crit to Warn)

### ISSUE THREAD

**Issue by Elfearo** [Icinga/icingaweb2#3980]
Hi there,

i´ve got some checks like load that are using stats over time to choose the state of a check. When using load for example i might have the following case:

Limits for Load: Warn: 5,3,1.5   Crit: 7,4,2 

1. Message: Crit: - load average: 10.00, 5.04, 1.08

Now having the Server in this state and then decreasing the load quite often gives me a second message:

2. Message: Warn - load average: 0.02, 3.92, 2.04

So basically the statements are all right, its just that the 15 minute average is still too high and just decreasing slowly, thus giving another warn even though the problem is basically solved for the moment. 

## Describe the solution you'd like
It would be nice if i could set a flag for a service, stating that a better state than the last should never release a new message.

## Describe alternatives you've considered
Thought about changing the tresholds for the check, but on the one hand it wouldnt be that specific anymore and on the other hand the problem can still occour then.

**Comment by nilmerg** [comment]
Hi,

first and foremost, this is rather a feature for icinga core. So better suited in the [respective issue tracker](https://github.com/Icinga/icinga2/issues).

Though, before you head over there. What you want won't be handled by icinga core itself. Neither by Icinga Web 2. It's more a functionality of our next installment of NoMa. (Notification Manager) However, there is no exact time-frame yet for its release.
