### ISSUE TITLE
Can't send external Icinga command: 401 Unauthorized. Please check your user credentials.

### ISSUE THREAD

**Issue by JanaFischinger** [Icinga/icingaweb2#3982]
```
icinga_api: Can't send external Icinga command: 401 Unauthorized. Please check your user credentials.

#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php(70): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleServiceCheckCommand))
#1 /usr/share/php/Icinga/Web/Form.php(1158): Icinga\Module\Monitoring\Forms\Command\Object\CheckNowCommandForm->onSuccess()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(275): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(60): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->setupQuickActionForms()
#4 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(66): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ServiceController->showAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}
```

This only happens when click on "Check now" and then i refresh then it worked. So seems every 2nd try work.
How to fix?

**Comment by nilmerg** [comment]
Hi, please head over to our community forums at https://community.icinga.com for such questions. We'd like to handle only bug reports and feature requests here at Github.

Though, when you create a new topic there please already include what you already tried to verify your API configuration: https://icinga.com/docs/icinga2/latest/doc/12-icinga2-api/#authentication (Especially the *Authentication Test* is a good start :wink: )

**Comment by JanaFischinger** [comment]
## Describe the bug

Host(s) are missing which are assigned to satellite.
Same issue like in this video:
https://www.youtube.com/watch?v=V5o-LHGQEB4

## To Reproduce
i used this following as base:
https://www.youtube.com/watch?v=XsmdsNXgCxE

1. Edited zones.conf via ssh and added the new endpoint as zone on master and endpoint.
2. Same on Endpoint edited zones.conf and added the master.
3. In director used kickstart to import endpoint and zone.
4. created a new host with same name as satellite, custer-zone is endpoint zone and icinga2 agent is enabled.
5. deployed but new host is not visible in icingaweb2
6. same with additional hosts, when i change cluster zone to master then host(s) are visible. but then checks running on master and not on satellite.

## Expected behavior

Show host in icingaweb2

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga2 r2.11.0-1
* Debian 10
* Enabled features: api checker ido-mysql mainlog notification
* Icinga Web 2 2.6.2 with director and monitoring module
* Config validation (information/cli: Finished validating the configuration file(s).)
