### ISSUE TITLE
Custom Variable view should be case sensitive

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2#3987]
The first letter of Custom Variables is currently always a capital letter, regardless of the real spelling. This is very confusing, especially if users work with apply rules where custom variables should be case sensitive.

Example:

```
object Host "srv01.localdomain" {
  import "generic-host"

  address = "10.37.129.3"
  vars.checker = "srv02.localdomain"
  vars.role = "master"
}
```

Custom Variable view of Icinga Web 2:

![Bildschirmfoto 2019-10-25 um 13 42 46](https://user-images.githubusercontent.com/3973350/67569040-0bcc3780-f72e-11e9-9ad5-1a7ce2ae19cb.png)

Current version: Icinga Web 2.7.3

**Comment by theFeu** [comment]
There's some more to that; if you have a var called "example" and one called "Example" you cannot distinguish between the two.

If I am not completely mistaken right now, the UI also turns underscores into spaces, which causes very similar problems.

**Comment by dnsmichi** [comment]
AFAIK the problem originates from supporting Icinga 1.x where CVs have a slightly different format, and no case sensitivity at all.
