### ISSUE TITLE
Minimize / shorten current incidents output on dashboard, same as plugin output

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2#3989]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
A while back, the plugin output, if an error was shown, would truncate itself:
![image](https://user-images.githubusercontent.com/27829577/67639259-1ae4ee00-f8c4-11e9-9c4d-54a7868c9a60.png)
... adding a dropdown arrow.

Now, with the items in the current incidents column, this is not the case. The full output robs the vertical space of Icingaweb2:
![image](https://user-images.githubusercontent.com/27829577/67639313-acecf680-f8c4-11e9-8fb9-4f225645ffff.png)

## Describe alternatives you've considered
Use the same truncation methods as the plugin output area for checks. At most this should be a few lines ideally. This should not be treated as "hey don't output too much". Some plugins or output can unexpectedly spill out nonsense on a whim if an exception is thrown.

**Comment by nilmerg** [comment]
Hi,

we decided explicitly against making output collapsible in lists as well. It clutters up the UI way too much. Of course, nonsense and exceptions do the same, but they should not show up in lists at all.

We show only the first line of output in lists. The long output is not shown. The case you're showing can only occur if a check mal-functions badly. (At least that's what I'd call a check spitting out that much nonsense in the first line.)
