### ISSUE TITLE
Translation for Overdue don't work

### ISSUE THREAD

**Issue by ClemensBW** [Icinga/icingaweb2#3994]
## Describe the bug
Translation for "Overdue" don't work

## To Reproduce
Search for a check that is over time and mouseover the clock icon

## Expected behavior
See "Überfällig"

## Screenshots
![grafik](https://user-images.githubusercontent.com/13568169/68412911-6ed9b780-018d-11ea-85a5-6189e3bd0bcf.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):  2.7.3

## Additional context
Think problem was the missing "%s" here: https://github.com/Icinga/icingaweb2/blob/861c5601b6e01402a932687d7b59a037c72a6804/modules/monitoring/application/locale/de_DE/LC_MESSAGES/monitoring.po#L3460

**Comment by nilmerg** [comment]
Will be fixed with the release.
