### ISSUE TITLE
Role permissions for the module monitoring are not displayed correctly

### ISSUE THREAD

**Issue by luciov66** [Icinga/icingaweb2#3996]
## Describe the bug
Role permissions for the module monitoring are not displayed correctly, i.e. the permission definitions are overwritten by the selection gauge and the information button.

## How to reproduce
Use a browser other than Firefox (i.e. Chrome, Edge). From the GUI, select Configuration -> Authentication;
select the tab Roles; click on "Create a new role";
in the New role tab, insert Role name "test"; then as Users insert "root" (anything will do); then inhibit the Administrative Access selector, so it gets greyed out;
then scroll down to the "monitoring" module;
click on "monitoring": the Permissions list will drop down;
scroll down to the monitoring/command/feature/object permissions:
you see the permission definitions overwritten by the selector and the information button, as displayed in the picture above.
The problem does not occur with Firefox Quantum 69.0.3 (64-bit).

## Expected behavior
The permission definitions should all be displayed clearly.

## Screenshots
![image](https://user-images.githubusercontent.com/40464048/68782046-01200680-0639-11ea-801b-c215c7fc5fc4.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules ( monitoring version 2.6.1):
* Web browser used: Microsoft Edge 44.17763.771.0, Microsoft EdgeHTML 18.17763;
and also Google Chrome Version 78.0.3904.97 (Official Build) (64-bit).
* Icinga 2 version used (r2.10.5-1):
* PHP version used (`php --version`):
* Server operating system and version: CentOS Linux release 7.6.1810 (Core)

**Comment by nilmerg** [comment]
Looks fine to me, almost:

![Bildschirmfoto von 2019-11-14 10-04-36](https://user-images.githubusercontent.com/16668527/68842174-3e7ea580-06c6-11ea-908e-0a00852f6d4d.png)

You don't seem to use the default Icinga theme. Which one is this?

**Comment by Wintermute2k6** [comment]
ref/IP/19585

**Comment by luciov66** [comment]
yes, I included the screenshot from Neteye4, which is an integration of Icinga and other tools. However, with the icingaweb2 on IE11 we get this:
![immagine](https://user-images.githubusercontent.com/40464048/69318206-f4a13c80-0c3c-11ea-84c6-aef440b30f17.png)
