### ISSUE TITLE
possibility to hide logout button in dashboard

### ISSUE THREAD

**Issue by rtubiera** [Icinga/icingaweb2#3998]
Hi,

Is there any possibility to hide the logout button in the dashboard or menu bar in icingaweb2?

![image](https://user-images.githubusercontent.com/33832830/68854695-90035080-0717-11ea-9efa-3b3a30132797.png)

Thanks for the answer.

**Comment by nilmerg** [comment]
Hi,

no that's not possible.

Please ask such a question on [community.icinga.com](https://community.icinga.com). Github is for issues and feature requests.
