### ISSUE TITLE
$service.name$ in notes_url does not get resolved whereas $host.name$ does get resolved

### ISSUE THREAD

**Issue by derJD** [Icinga/icingaweb2#4000]
## Describe the bug
When using macros in notes_url "$host.name$" gets resolved whereas "$service.name$" does not.
Using "$service.display_name$" instead makes no difference.

## To Reproduce
* set notes_url in a service_object to "https://example.de/wiki/$host.name$#$service.name$"

## Expected behavior
Service Macros should get resolved in icingaweb2 as well

## Your Environment

* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version 2.7.3
Git Commit 06cabfe8ba28cf545a42c92f25484383191a4e51
* Web browser used:
FF 70.0.1(64-Bit)
* Icinga 2 version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.2-1)

* PHP version used (`php --version`):
PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18) ( NTS )
* Server operating system and version:
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
Linux mon01vp 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

## Additional context
Using "$SERVICEDESC$" works fine.

**Comment by nilmerg** [comment]
Hi,

that's because `$service.name$` is wrong. It's actually `$service.description$`.

**Comment by derJD** [comment]
wow. Thanks a lot @nilmerg ! It works! =)
But this is kind of counterintuitive. I didn't find service.description here:
https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#service-runtime-macros
and since host.name/host.display_name works and notification commands are able to parse service.name correctly I thought icingaweb2 should parse it the same way =/

**Comment by nilmerg** [comment]
Well, that's because you were looking at Icinga 2's runtime macros. These are only available in Icinga 2's DSL. Icinga Web 2 only supports a specific subset of legacy (1.x) runtime macros. That's also the reason why `$SERVICEDESC$` works.

But you're right that it's counter intuitive nonetheless. We're currently working on the successor of the monitoring module ["Icinga DB"](https://github.com/Icinga/icingaweb2-module-icingadb) which should solve this since filter and column definitions are much more streamlined with Icinga 2 then. Then it's e.g. `service.name` in filters and also `$service.name$` in macros.

**Comment by derJD** [comment]
Thanks for the clarification! Now I'm looking forward for your successor monitoring module =)

**Comment by derJD** [comment]
Sorry @nilmerg  for reopening this issue.

TL:DR: Is there currently a Macro that icinga2-dsl as well as icingaweb2 understands?

When switching to `$service.description$` my notificationcommand isn't able to interpret it.  So I switched back to service.name since for my case the link is more important in actual notifications.

**Comment by nilmerg** [comment]
Nope, if at all there's `$SERVICEDESC$`. (Though I don't know if Icinga 2 understands the legacy macros)

**Comment by dnsmichi** [comment]
Icinga 2 doesn't understand these macros, we made the decision to only support the new format. That's explained in the [migration docs](https://icinga.com/docs/icinga2/latest/doc/23-migrating-from-icinga-1x/#macros). Icinga Web 2's support for those old macros originates from the request to run it with Core 1.x AFAIK.

**Comment by nilmerg** [comment]
Then, I'm afraid, there's no way to use the same macro for Icinga Web 2 and Icinga 2 to resolve a service's name.

**Comment by derJD** [comment]
Thats quiet a triangle I've got here :D.
By using icinga-director I'm bound to strings which may contain macros. `"<string>" + vars` isn't supported afaik.
Icingaweb2 only supports/translates old macros  from icinga1/nagios.
Icinga2-DSL does not understand those old macros but icingaweb2 is *the* main webfrontend.
This *could* change with the new icinga db module.

I still think this would be a nice feature for icingaweb2. So... this is rather an enhancement request, I guess.

**Comment by nilmerg** [comment]
We'll include `service.name` as macro with v2.8.0 :smiley:
