### ISSUE TITLE
Search object followed by a space finds no results

### ISSUE THREAD

**Issue by mzac** [Icinga/icingaweb2#4002]
## Describe the bug
When typing in something to search in the search box, if the text is followed by a space (which could happen with a copy and paste) then the search results show 'No results found matching the filter'

## To Reproduce
Type in something you know should have results and add a space after in the search box

## Expected behavior
The search box should ignore and trailing spaces

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.7.3
* Web browser used: Chrome 78
* Icinga 2 version used (`icinga2 --version`): r2.11.2-1
* PHP version used (`php --version`): 7.2.24-0ubuntu0.18.04.1
* Server operating system and version: Ubuntu 18.04.3 LTS

**Comment by nilmerg** [comment]
Hi, yes you're right, give me a minute. :sweat_smile:
