### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#4009]
Didn't have a detailed look what's needed for this. Just had accidentally an issue with it since the zend framework we ship utilizes some deprecated functions/interfaces.

**Comment by reubenfarrelly** [comment]
Yes.  Here's the first problem seen with php-7.4:

Sat Nov 30 12:16:32.317104 2019] [php7:error] [pid 3920:tid 140598682044160] [client 2403:5800:7100:950::23:46504] PHP Fatal error:  Uncaught ErrorException: Uncaught ErrorException: include(): \\Icinga\\Web\\ViewStream::stream_set_option is not implemented! in /usr/share/icingaweb2/library/Icinga/Web/View.php:262\nStack trace:\n#0 /usr/share/icingaweb2/library/Icinga/Web/View.php(262): Icinga\\Application\\ApplicationBootstrap->Icinga\\Application\\{closure}()\n#1 /usr/share/icingaweb2/library/Icinga/Web/View.php(262): include()\n#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\\Web\\View->_run()\n#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render()\n#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript()\n#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()\n#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_Vi in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 259

**Comment by marxin** [comment]
May I please ask when do you plan a new release that include the new PHP support?

**Comment by nilmerg** [comment]
v2.8-rc1 is already due. We just wait for https://github.com/Icinga/icinga2/issues/7532 as it blocks anything else.

**Comment by marxin** [comment]
> v2.8-rc1 is already due. We just wait for [Icinga/icinga2#7532](https://github.com/Icinga/icinga2/issues/7532) as it blocks anything else.

The icinga2 was released. When can one expect a release of `icingaweb2` please?

**Comment by Selimduman** [comment]
How do you download the newest 2.8.1 version of Icinga using Ubuntu terminal commands?
