### ISSUE TITLE
Login failing with 500 Internal Server Error in Chrome (Not FireFox)

### ISSUE THREAD

**Issue by robertheessels** [Icinga/icingaweb2#4011]
## Describe the bug

Login failing with as error in the console:
`icinga.min.js:3 POST http://mydomain.com/icingaweb2/authentication/login 500 (Internal Server Error)`
and in the browser:
```
#0 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2280): Icinga\Web\Form\Element\CsrfCounterMeasure->isValid(String, Array)
#1 /usr/share/php/Icinga/Web/Form.php(1292): Zend_Form->isValid(Array)
#2 /usr/share/php/Icinga/Web/Form.php(1169): Icinga\Web\Form->isValid(Array)
#3 /usr/share/icingaweb2/application/controllers/AuthenticationController.php(54): Icinga\Web\Form->handleRequest()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AuthenticationController->loginAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#10 {main}
```

This was working fine before, but fails now in Google Chrome.
Is still working fine in FireFox.

## To Reproduce

When I direct Chrome to my Icinga web url, I do get a correct login screen, but right after I submit the form, I get the above error.

## Your Environment

* Icinga Web 2 version and modules (System - About):

2.7.3 (Git commit 06cabfe8ba28cf545a42c92f25484383191a4e51)
Modules:
grafana 	1.3.4
monitoring 	2.7.3 

* Web browser used:

Lastest Chrome fails. Latest Vivalfdi fails. It works fine on FireFox.

* Icinga 2 version used (`icinga2 --version`):

r2.11.2-1 (installed with apt on Ubuntu 18.04)

* PHP version used (`php --version`):

7.2.24-0ubuntu0.18.04.1

* Server operating system and version:

Ubuntu 18.04

**Comment by nilmerg** [comment]
Hi,

this is usually caused either by a browser not accepting cookies or by a server not accepting them. Since it's working with other browsers, it's a browser issue.

Did you try to clear your cache in these browsers? Are they allowed to store cookies? Or have they a custom configuration how long cookies are preserved?
