### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by MacFan4000** [Icinga/icingaweb2#4031]
I’m running the latest versions of icingaweb2 and icinga2 with PHP 7.4 on Debian 10. When I try to use icingaweb2 I get the following:

Fatal error: Uncaught ErrorException: Uncaught ErrorException: include(): \Icinga\Web\ViewStream::stream_set_option is not implemented! in /usr/share/php/Icinga/Web/View.php:262 Stack trace: #0 /usr/share/php/Icinga/Web/View.php(262): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'include(): \\Ici...', '/usr/share/php/...', 262, Array) #1 /usr/share/php/Icinga/Web/View.php(262): include() #2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...') #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL) #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('error/error.pht...', NULL) #5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render() #6 /usr/share/icingaweb2/library/vendor/Zend/Controller in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 259

Help is appreciated, thanks.

**Comment by nilmerg** [comment]
Hi,

the latest release is not yet compatible with PHP 7.4. Support for it is currently only on master (#4009) but will be part of v2.8.

**Comment by amarnath-jena** [comment]
Switch back to lower version of php. It resolved my issue.

sudo a2enmod php7.2
sudo systemctl restart apache2

**Comment by onkobu** [comment]
The same currently happens on Gentoo-Linux. Luckily it can run multiple PHP-versions in parallel. Need to set apache2-variant with eselect:

1. ``eselect php list apache2`` – lists installed versions, hopefully one with 7.2, otherwise ``emerge`` accordingly
1. ``eselect php set apache2 <num>`` – pick <num> from previous output, e.g. 1
