### ISSUE TITLE
Add domain logic to user database backend

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2#4033]
Currently the user backend database does not support the introduced domain logic.

## Environment

Lets say we have the following environment:

Admin: icingaadmin
LDAP Domain: NETWAYS
User Account: mfrosch@NETWAYS

## Working case

Without setting a "Default Login Domain".

* Admin can log in via `icingaadmin`
* User can log in via `mfrosch@netways`

## Non working case

Once we set the default login domain to ease handling for our users.

* Admin can no longer login via `icingaadmin` or any other combination
* User can login as `mfrosch` or `mfrosch@netways`

Only solution is to store the users in database in a full domain format: `icingaadmin@local`. While the domain does not need to be configured in this case, a local user can log in again.

## Suggestion

Add a domain config field for database backends, so the admin can pick a domain like `local` and instruct admins to use it.

**Comment by nilmerg** [comment]
I'm not quite sure what exactly you're suggesting?

The current state intentionally expects a database user backend's entries to include a domain if a default one is configured. This is also documented: https://github.com/Icinga/icingaweb2/blob/master/doc/05-Authentication.md#sql-database-
So the fact that `icingaadmin` can't login with a default domain set (without an appropriate `icingaadmin@domain` entry in the db) is working as designed.

What effect would have the config option you're suggesting?

**Comment by nilmerg** [comment]
> Only solution is to store the users in database in a full domain format: icingaadmin@local. While the domain does not need to be configured in this case, a local user can log in again.

This is the intended solution if a default domain is active and the database authentication is still required.
