### ISSUE TITLE
special characters disply incorrectly

### ISSUE THREAD

**Issue by fireba11** [Icinga/icingaweb2#4035]
## Describe the bug
Display names with (at least) äöüß get mangled.
I'm using director, but i checked the icinga config files, those are still correct.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.7.3
* Web browser used: FF 71
* Icinga 2 version used (`icinga2 --version`):
* PHP version used (`php --version`): 7.3.11-1~deb10u1
* Server operating system and version: debian 10

**Comment by dnsmichi** [comment]
Please share the database resource configuration for the IDO database (remove credentials).

**Comment by tobor** [comment]
‘Hostname’ and ‘Display name’  Add UTF-8 charaters display:  äº‘åˆ°å¾®è½¯

**Comment by fireba11** [comment]
[icinga_ido]
type = "db"
db = "mysql"
host = "localhost"
port = ""
dbname = "icinga2"
username = "icingaweb"
password = "password"
charset = ""
persistent = "0"
use_ssl = "0"

so i guess it's a configuration error. curious how charset can just be empty :-D
note: just setting it as "utf8" doesn't change anything

**Comment by nilmerg** [comment]
The IDO's resource option `charset` must be set to `latin1` for umlauts to work correctly.

**Comment by log1-c** [comment]
Though this is quite old I stumble upon this again and again some time.
I just set up a new system on Ubuntu 20.04, where this happens as well.
As it seems mariadb on Ubuntu uses `utf8mb4` as a default charset when creating the databses.

@nilmerg 
I think it is worth mentioning in the [docs ](https://icinga.com/docs/icinga-2/latest/doc/02-installation/#setting-up-the-mysql-database) to set the charset/collation to `latin1 `when setting up the database

**Comment by fireba11** [comment]
How did it end up with utf-8 **not** working and latin1 being the correct one? That just feels wrong ...
