### ISSUE TITLE
Shared storage for dynamic data entered from web interface

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [Icinga/icingaweb2#4037]
## Is your feature request related to a problem? Please describe.
Although icingweb2 can be used in an HA configuration (with a load balancer, for instance) the configuration data that can be changed dynamically within icingaweb2 is not automatically propagated to other icingaweb2 systems.

## Describe the solution you'd like
Any data that can be changed from the web interface (roles.ini, for example) should be stored in a shared location so that changes are automatically reflected in every icingaweb2 interface.

This is especially important for roles.ini, since the roles are typically configured in the web interface. The administrator must currently either execute the same web interface actions on each icingaweb2 server, or must have a means to copy the roles.ini file between servers.

Ideally this dynamic data would be stored in a database. I say this realizing that not every icingaweb2 deployment necessarily uses an icingaweb2 database.

## Describe alternatives you've considered
* An rsync cron job would solve the problem, but there certainly would be a time lag. Requires setting up SSH keys, logs, monitoring, etc.
* The changes can be made manually in multiple locations. Error prone and laborious.

## Additional context
This is based on a support customer request.

**Comment by carraroj** [comment]
ref/IP/20433

**Comment by dnsmichi** [comment]
AFAIK that feature request already exists with #3770

**Comment by nilmerg** [comment]
Correct.
