### ISSUE TITLE
Add link to style guide to .md

### ISSUE THREAD

**Issue by Fonata** [Icinga/icingaweb2#4038]
As a new contributor, I want to keep my source code lines as readable as possible.

In https://github.com/Icinga/icingaweb2/blob/master/CONTRIBUTING.md#-pull-request-review, a style guide is mentioned, but I could not find one.

I suggest to hyperlink to the guide, if it exists.

**Comment by nilmerg** [comment]
That'd be a quick web search for *php style guide* which leads to: https://www.php-fig.org/psr/psr-12/
