### ISSUE TITLE
How can I add bandwidth usage alert

### ISSUE THREAD

**Issue by webkida** [Icinga/icingaweb2#4041]
Hi,

I want to  allot bandwidth usage for each server for e.g. server 1 - 1TB data transfer per month, server 2 - 2 TB and so on.
Also want to set alert notification so that get alert on 80% & 95% consumption.

**Comment by lippserd** [comment]
Hi,

Please ask such questions in our [community forum](https://community.icinga.com/).

Best,
Eric
