### ISSUE TITLE
Create Downtime - option "All Services" should automatic switched on

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icingaweb2#4059]
## Is your feature request related to a problem? Please describe.
If somebody create a downtime for a host which has a lot of services, it happens very often that we forget to switch on the option "all services".

![icingaweb2](https://user-images.githubusercontent.com/38723488/72536411-7f3b9c00-387a-11ea-9225-5146679d0fa3.png).

The result is if the the colleague maintain the server during the specified time you see in a view with "unhandled hosts" not the server, but you see the critical services in an unhandled services view. 

## Describe the solution you'd like
We have two ideas:
a) You switch on the option "all Services" in this form generally. 
b) If you don't like Option a) because every icinga customer handle this in diffrent ways, it should be possible that everybody should be able to declare a standard option for this. Either per installation or each user individually, which is easier to release or you prefer.

**Comment by dnsmichi** [comment]
Hi,

that's already possible: https://icinga.com/docs/icingaweb2/latest/modules/monitoring/doc/03-Configuration/#default-settings

Cheers,
Michael

**Comment by stevie-sy** [comment]
@dnsmichi  thank you, we didn't know that. Works as expected. 

Then we have a "merge" request for the icinga book and training documents for the icinga Trainings :-)  Because there we didn't found and heard about it ;-)

**Comment by dnsmichi** [comment]
Typically, books and training resources cannot cover everything. Imho the documentation is the source of everything which is supported or evolves over time :)
