### ISSUE TITLE
Icingaweb2 doesn't display check_procs perfdata correctly

### ISSUE THREAD

**Issue by Crited** [Icinga/icingaweb2#4062]
Icingaweb2 doesn't display check_procs perfdata correctly. 

**# Example**
For example:
```
object Host "icinga2-node1.localdomain" {
...
vars.services["sshd"] = {
procs_warning = "1:"
procs_critical = "2:"
}
vars.services["httpd"] = {
procs_critical = ":18"
}
}
```

In perfdata for "Service sshd" both warning and critical are _0_ instead of the expected set values, and for "Service httpd" warning is set to the default as it should be, but critical is _0_

**## Expected behavior**
Perfdata should display the set value for warning and critical.

**## Your Environment**
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version used (`icinga2 --version`): 2.8.4
* PHP version used (`php --version`): 7.1.8
* Server operating system and version: CentOS 7

I suspect this is also happening in the current stable version. (Probably, caused by the ":")

**Comment by dnsmichi** [comment]
Threshold ranges for plugins are [not supported](https://github.com/Icinga/icinga2/issues/909#issuecomment-358678617) by Icinga 2, especially in the perfdatavalue parser.
