### ISSUE TITLE
Sort services based on performance metrics

### ISSUE THREAD

**Issue by ak2766** [Icinga/icingaweb2#4067]
## Is your feature request related to a problem? Please describe.

I've created a custom dashboard where I've collected the metrics I'm most interested in viewing.  One of the metrics is the amount of RAM a LXD container is consuming.

## Describe the solution you'd like

I'd like to be able to sort based on Container Memory Usage (see screenshot).

![Selection_00172](https://user-images.githubusercontent.com/6629646/73787066-9d981600-47ee-11ea-9a11-4749ae3d7e15.png)

**Comment by nilmerg** [comment]
Hi, that's currently not possible. The performance data is not stored in a way that allows us to implement sorting based on this. Changing this would require quite a few adjustments in how Icinga 2 processes performance data and stores it in the database.

But regardless of any changes required, I'm not sure if this is really something that should be possible in a monitoring tool. Icinga monitors the RAM usage and, if the thresholds are reached, reports a problem. In the UI it is then possible to sort based on a service's severity and any problem is easily found.

I'd suggest you consider using a graphing solution to solve your requirement. Some are described in the documentation: https://icinga.com/docs/icinga2/latest/doc/13-addons/#graphs-and-metrics
You can then integrate the graphs in Icinga Web 2 by an appropriate module and show them on the dashboard. They're even prettier than our list views.

If you need help or don't know which graphing solution to pick, please head over to our forums: https://community.icinga.com

**Comment by ak2766** [comment]
> I'd suggest you consider using a graphing solution to solve your requirement. Some are described in the documentation: https://icinga.com/docs/icinga2/latest/doc/13-addons/#graphs-and-metrics

I've already integrated Grafana into my Icinga server; I was simply hoping that it was possible to sort based on these metric so that I could expand on the culprit containers:
![Selection_00174](https://user-images.githubusercontent.com/6629646/73820815-ad434900-4846-11ea-8ab3-655e6f575470.png)

If it's not worth your time, then junk it.

Thanks for replying.

**Comment by nilmerg** [comment]
If I came across being elitist, I apologize. That wasn't my intent, I just told you my view regarding what Icinga is responsible for. But, granted, closing the issue right away probably wasn't the best idea.

Still, I don't see a reason why sorting based on performance metrics should be possible in Icinga Web 2. With that I don't mean I can't see a reason why anyone would want that and especially not that this is a dumb idea..
Icinga does what it can best but that unfortunately doesn't include metrics. Though, there are plenty of other options out there (graphing being the most prominent thing that comes to my mind) that handle metrics fine. You may also try using [Elasticsearch](https://icinga.com/docs/icinga2/latest/doc/09-object-types/#elasticsearchwriter) or a similar tool.
