### ISSUE TITLE
It should be possible to set restrictions for users with administrative access in the UI

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#4068]
## Describe the bug

While it is perfectly possible (and desirable) to define restrictions for users having `permissions = *`, in the UI this is currently requires the following steps:

* switch admin access off
* specify your restriction
* switch admin access on
* store your role

**Comment by nilmerg** [comment]
That was made because `permissions = *` includes config access and so the possibility to change the restrictions. What is the point in restricting someone which is then able to lighten/remove the restriction?

**Comment by Thomas-Gelf** [comment]
Icinga Admins who do not want to be bothered with Host/Service problems from other teams in larger setups. Same goes for other artificial restrictions in other modules. `permissions = *` does and should not overrule restrictions, that's intentional. IMHO our UI should reflect this.

**Comment by Thomas-Gelf** [comment]
@nilmerg: related, but eventually a different issue -> I often see people granting temporary admin access for various reasons. When doing so in the UI, this now means that they'll lose all the granular hand-cured permissions they granted that role beforehand.

Any objections against keeping them as they are (like it happens with the restrictions) when granting full access?

**Comment by nilmerg** [comment]
No, I guess not. The preservation of restrictions in this case is already specifically handled.
