### ISSUE TITLE
 User custom vars should be displayed

### ISSUE THREAD

**Issue by theFeu** [Icinga/icingaweb2#4070]
If there are any custom vars assigned to a user (like shown below, the favourite animal) are not displayed in the front end.
Host and Service custom vars are displayed in their detail views.
I feel like we should add that.

I would recommend to just add that to the user details under: `/icingaweb2/user/show`

```
object User "icingaadmin" {
  display_name = "Icinga 2 Admin"
  groups += [ "icingaadmins" ]

  vars.favourite_animal = "chicken"

  email = "training@localhost"
}

```

There could be useful stuff there too, like "Internal ID" or similar.

If we have the information on the user object, I feel like we should display it too.

**Comment by dnsmichi** [comment]
Is this for IcingaDB as backend, or with using the old IDO schema?

For the IDO parts, the schema does not allow for that which is why, User#vars is not dumped by the IDO feature in Icinga 2.

**Comment by theFeu** [comment]
I didn't check if it was possible yet (hence the _if_ we have the info), but I think it would be pretty useful!

**Comment by dnsmichi** [comment]
For IcingaDB, I don't know the schema but could imagine that @N-o-X has taken this into account. In terms of the IDO backend, I doubt we will make this data available and extend the schema.

**Comment by N-o-X** [comment]
The Icinga DB schema already takes this into account and provides custom vars for most config objects. That data isn't shown by our Icinga DB Web Module yet. Might be worth an issue there: https://github.com/Icinga/icingaweb2-module-icingadb

**Comment by theFeu** [comment]
Nice!
I'll open one right away! :)

**Comment by theFeu** [comment]
Moved to the Icinga DB module :)

https://github.com/Icinga/icingaweb2-module-icingadb/issues/19
