### ISSUE TITLE
Change the order in a dashlet group that contains a renamed dashboard generates an error

### ISSUE THREAD

**Issue by andickts** [Icinga/icingaweb2#4073]
## Describe the bug
Resorting a dashboard in a dashlet group that contains a renamed dashboard generates an error

## To Reproduce
1. Create two new dashboard in the same dashlet group
2. Rename one of the dashboards created
3. Try to change the order in configuration 

## Expected behavior
No error on sorting change

## Screenshots
Try to change the order:
![image](https://user-images.githubusercontent.com/60885471/74343724-c6e71200-4dab-11ea-8387-b03517b5fedb.png)
Generates the error:
![image](https://user-images.githubusercontent.com/60885471/74343537-84bdd080-4dab-11ea-8347-76a54e71269f.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): -2.7.3
* Web browser used: Mozilla Firefox
* Icinga 2 version used (`icinga2 --version`): 2.10.5
* PHP version used (`php --version`):  7.1.8
* Server operating system and version: CenOS 7

## Additional context

Original content of dashboard.ini:

[Current Incidents.Test1]
url = "monitoring/host/show?host=virtual-win81.WORKGROUP"
title = "Test1"

[Current Incidents.Test2]
url = "monitoring/service/show?host=virtual-win81.WORKGROUP&service=DiskQueueLength"
title = "Test2"

After dashboard rename, only the title will be changed, but the sorting button don't find the dashboard with the new name:

[Current Incidents.Test1]
url = "monitoring/host/show?host=virtual-win81.WORKGROUP"
title = "Test1-mod"

[Current Incidents.Test2]
url = "monitoring/service/show?host=virtual-win81.WORKGROUP&service=DiskQueueLength"
title = "Test2"

**Comment by Yonas-net** [comment]
Sorry, but I have no way of getting to the error like you do because the dashboards of the latest version of Icinga Web 2 do not have a drag and drop functionality built in. Do you have any modules built in that allow you to do this and could lead to this bug?

**Comment by andickts** [comment]
Hi @Yonas-net , we don't use any drag&drop functionality.
Dashlets are ordered using arrows in dashboard setting as shown in first image.

**Comment by nilmerg** [comment]
Then you're running a customized/patched version of Icinga Web 2. We have never supported re-ordering dashlets in the UI. There's also no method `moveDashletAction()` in our [DashboardController.php](https://github.com/Icinga/icingaweb2/blob/master/application/controllers/DashboardController.php).

**Comment by andickts** [comment]
Thanks for the support. I found the cause of the problem. It is not your feature!
