### ISSUE TITLE
translate ansi terminal colours to into html/css for the plugin output

### ISSUE THREAD

**Issue by mphilipps** [Icinga/icingaweb2#4074]
hi,
It would be nice if the coloured output of a check command could be preserved when displaying it in Icinga2.  

Tried doing it my self from within the check, but couldn't get the CSS part to work.

**Comment by nilmerg** [comment]
Hi,

is this now about terminal colors or embedded HTML/CSS?

HTML/CSS should work fine. You can also use `(OK)`, `(CRITICAL)` or `[OK]`, `[CRITICAL]` (and so on) which get styled automatically.

ANSI escape codes (i.e. terminal colors) however are hardly an option. Check plugins are usually ran by Icinga, not a by a human being. So under normal circumstances there's no terminal (emulator) in between which could interpret these.

If colored or structured output is desired, HTML/CSS can be used.
