### ISSUE TITLE
Toggle Feature Commands does not display change

### ISSUE THREAD

**Issue by riban-bw** [Icinga/icingaweb2#4076]
## Describe the bug
Toggling "Feature Commands" within web interface does not show the new state until page is manually refreshed.

## To Reproduce

1. Navigate to a service
2. Click on "Active Check"

## Expected behaviour
Active Check is disabled. Active Check indication (checkbox) within web interface is unchecked.

## Actual behaviour
Active Check is disabled. Active Check indication (checkbox) within web interface is unchanged.

* Icinga Web 2 version and modules (System - About):

Icinga Web 2 Version
2.6.3
Git commit
0d119242ba1728f4b617000a1bd14a230f96f2ee
Git commit date
2019-04-25

setup | 2.6.3
businessprocess | 2.2.0
cube | 1.1.0
ipl | v0.4.0
monitoring | 2.6.3

* Web browser used:
Chome 80.0.3987.106 (Official Build) (64-bit)

* Icinga 2 version used (`icinga2 --version`):
r2.10.5-1

* PHP version used (`php --version`):
5.4.16

* Server operating system and version:
System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-957.21.3.el7.x86_64
  Architecture: x86_64

## Additional context
Manually refreshing web page shows correct status.

**Comment by nilmerg** [comment]
Hi,

this should not require a manual refresh. Did you disable automatic refreshes?

**Comment by riban-bw** [comment]
The web interface generally updates dynamically with new alerts being indicated. It is only this tickbox that does not refresh after clicking.

**Comment by nilmerg** [comment]
Then I suspect this is just due to the time which Icinga needs to process the request. We already refresh the host/service details (while auto-refresh is enabled) shortly after a feature is changed. Though, if Icinga didn't process the request yet or didn't update the database we have no other way of showing the change.

**Comment by nilmerg** [comment]
Closing this. We're currently not able to "fix" this, since it's dependent on how fast Icinga is processing the request and writing the update into the database.

**Comment by riban-bw** [comment]
Disappointing to close a known issue. This is particularly frustrating as the user must make the change, then manually refresh page which is not intuitive. The user sees the setting start to change but then the visual representation changes back to its previous state. If this is a timing issue related to speed of database, could a solution be to offer a configuration for auto-update / refresh speed? Maybe a page avoids updates for a period after user interaction. This kind of bug undermines confidence in the validity of the UI which is highly undesirable in an alarm monitoring tool.
