### ISSUE TITLE
Add service_flapping/host_flapping to icingacli JSON output

### ISSUE THREAD

**Issue by fdellwing** [Icinga/icingaweb2#4077]
## Is your feature request related to a problem? Please describe.

We are using `icingacli monitoring list services --format json` to generate a custom Dashboard that is shown on some monitors in the building. We can already filter out things that are acknowledged or in downtime, but not if they are flapping.

## Describe the solution you'd like

Add `host_flapping` and `service_flapping` to the output of `icingacli monitoring list services --format json`

## Describe alternatives you've considered

I can't think of any.

## Additional context

```
$ icingacli --version
Icinga Web 2  2.7.3     
Git Commit    06cabfe8ba28cf545a42c92f25484383191a4e51 
PHP Version   7.0.33-0+deb9u7 
MODULE      VERSION   
doc         2.7.3     
mbcl        1.0.0     
monitoring  2.7.3     
pnp         1.1.0
```

**Comment by nilmerg** [comment]
Hi,

you can pass the columns you want to the command with `--columns <comma-separated-column-names>`.

e.g. `icingacli monitoring list services --format json --columns host_name,host_state,host_output,host_handled,host_acknowledged,host_in_downtime,ser_downtime,service_handled,service_output,service_perfdata,service_last_state_change,host_is_flapping,service_is_flapping`

**Comment by fdellwing** [comment]
Thanks, maybe add the available columns to the `--help` output?

**Comment by nilmerg** [comment]
That's the case. `icingacli help monitoring list services` produces this:

```
List and filter services
========================

This command allows you to search and visualize your services in
different ways.

USAGE

icingacli monitoring list services [options]

OPTIONS

  --verbose  Show detailled output
  --showsql  Dump generated SQL query (DB backend only)

  --format=<csv|json|<custom>>
    Dump columns in the given format. <custom> format allows $column$
    placeholders, e.g. --format='$host$: $service$'. This requires
    that the columns are specified within the --columns parameter.

  --<column>[=filter]
    Filter given column by optional filter. Boolean (1/0) columns are
    true if no filter value is given.

  --problems
    Only show unhandled problems (HARD state and not acknowledged/in
downtime).

  --columns='<comma separated list of host/service columns>'
    Add a limited set of columns to the output. The following service
    attributes can be fetched: state, handled, output, acknowledged,
in_downtime, perfdata last_state_change

EXAMPLES

  icingacli monitoring list services --problems
  icingacli monitoring list services --problems --service_state_type 0
  icingacli monitoring list services --host=local* --service=*disk*
  icingacli monitoring list services --columns
'host,service,service_output' \
    --format='$host$: $service$ ($service_output$)'
```

**Comment by fdellwing** [comment]
I meant **all** available columns.

I saw the few that are mentioned in the help and thought it supported only them.

**Comment by nilmerg** [comment]
Oh, I see. Thing is, there are way too many columns to list them all since any column which can be used as a filter is allowed. May I suggest you take a look at what you can choose in the UI's filter editor? The same columns should be usable for this command option.
