### ISSUE TITLE
Wizards stucks when changing settings or move to last/next page

### ISSUE THREAD

**Issue by Foxeronie** [Icinga/icingaweb2#4078]
Hi!

After passing the token and clicking next on the next page the loading icon next to the button appear, the background is fading grey, but nothing happens. If you press F5 the next page appears.
You can find the error "uncaught exception: Requires a node" via web developer console.

Problem starts for me between these commits:

working: nilmerg committed on Jan 15 1 parent 3db65d7 commit fdd14c96b144fd00eac923987b26a4f66fd3da60 

not working: nilmerg committed on Jan 16 2 parents 3464455 + e9b27b3 commit b555c4bd8b4f88982194ddf18cd696bc77c027b6 

On git master:
1. Insert setup token
2. Press next
3. nothing happens
4. Press F5
5. Next Page appears
6. repeat

## Screenshots
![Screenshot from 2020-02-22 01-20-50](https://user-images.githubusercontent.com/10115997/75082068-37133780-5512-11ea-95e0-b53ae54f5c76.png)

## Your Environment
Ubuntu 18.04
apache2 and php7.2
firefox 73
icingaweb2 git master

Best regards,
Patrick

**Comment by darkpixel** [comment]
Same on FreeBSD 12.

**Comment by nilmerg** [comment]
You're right, reproduced it successfully.

Thanks for the report!
