### ISSUE TITLE
dashboard tab rotation

### ISSUE THREAD

**Issue by pknutti** [Icinga/icingaweb2#4079]
## Is your feature request related to a problem? Please describe.
I am searching for a feature to rotate dashboard tabs.

## Describe the solution you'd like
would be nice to have a possibility to rotate dashboard tabs and activate/ deactivate it in user settings.

## Additional context
I am pretty sure that this kind of feature was already there in a previous version of icingaweb2 but I cannot find this function anymore.

**Comment by nilmerg** [comment]
Hi,

please add your request in #3809.

Thanks.
