### ISSUE TITLE
Filterexpression doesn't work correctly

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2#4090]
## Describe the bug
While looking for Services i encountered reproducable the following error

```
[internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Data/Filter/FilterExpression.php(209): preg_match(String, String)
```

## To Reproduce

```
apply Service "nrpe-v3-cpu" {
    import "nrpe-v3"

    assign where (! match("*redacted*certs", host.name) && ! match("app/*", host.name) && ! match("net/*", host.name) && match("redacted*", host.name)) || (match("epastatistik*", host.name) && ! match("*redacted*rds*", host.name)) || match("something-redacted-somthing*", host.name) || match("something-prod-redacted*", host.name)
    vars.netcool_sys_app_type = "something:redacted"
    vars.nrpe_arguments = [ "-uw 70 -iw 95 -sw 85 -uc 80 -ic 98 -sc 95 -n 5" ]
    vars.nrpe_command = "check_perf_cpu_monpers"
    vars.verfahrensumgebung = "$host.vars.verfahrensumgebung$"

    import DirectorOverrideTemplate
}
```

## Expected behavior
No Filter Error Shown in Web 2

## Screenshots
![error](https://user-images.githubusercontent.com/7203835/75565275-f6557a00-5a4d-11ea-9e9c-1d59fb6e9f9d.png)

## Your Environment
-

## Solution Suggestion

Replace in /usr/share/php/Icinga/Data/Filter/FilterExpression.php line 195:

-  $parts[] = preg_quote($part);
+ $parts[] = preg_quote($part, '/');

**Comment by nilmerg** [comment]
Hi,

you've missed to include the filter you're using, please add that as well.

**Comment by Thomas-Gelf** [comment]
@nilmerg: @carraroj should have a related NC ticket. However, the expression doesn't matter. `preg_quote` got no delimiter, and therefore every character matching the delimiter (`/`in this case) will break the expression.

Cheers,
Thomas

**Comment by carraroj** [comment]
ref/NC/663687
