### ISSUE TITLE
Ability to hide/show groups in Icingaweb2

### ISSUE THREAD

**Issue by phinnay** [Icinga/icingaweb2#4091]
## Is your feature request related to a problem? Please describe.
We utilize groups for some behind-the-scenes activities like cluster identification and schedules. Currently, those groups show up in Icingaweb2 even though there is no benefit to their visibility or they contain duplicate items. 

## Describe the solution you'd like
I'd like to be able to specify something in my group definition config that would turn off it's appearance in Icingaweb2

example:
vars.groups.hidden = true

## Describe alternatives you've considered
We hide some elements based on user login. This is tedious.

**Comment by nilmerg** [comment]
Hi, you basically want the same as #3349 and #3550, though as hostgroup only filter.

While both issues above can be worked-around by using custom variables in restrictions, you want to limit access to specific hostgroups only (not their hosts/services) which is not possible this way.

This differentiation is not possible yet, but we're aware of it. There's need for a rewrite of our current authorization mechanics already and we'll make sure this differentiation will be part of it.

**Comment by phinnay** [comment]
thank you!
