### ISSUE TITLE
Icingaweb2 -> System -> About (Undefined offset: 1)

### ISSUE THREAD

**Issue by 42bios** [Icinga/icingaweb2#4092]
## Describe the bug
Since I hardly need this menu item, I recently noticed the following problem:
In menu "System -> About" there seems to be a problem with my Icinga, but I haven't found a solution to fix it. I suspect a problem with the installed PHP version?

`Undefined offset: 1`

`#0 /usr/share/php/Icinga/Application/Modules/Module.php(686): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Application/Modules/Module.php(619): Icinga\Application\Modules\Module->metadata()
#2 zend.view:///usr/share/icingaweb2/application/views/scripts/about/index.phtml(120): Icinga\Application\Modules\Module->getVersion()
#3 /usr/share/php/Icinga/Web/View.php(262): include(String)
#4 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}`

## Screenshots
<a href="https://abload.de/image.php?img=system__icingawebo6k2i.png"><img src="https://abload.de/img/system__icingawebo6k2i.png" /></a>

* Icinga Web 2 version and modules (System - About):
`Icingaweb2 version 2.7.3`

* Web browser used: 
`MS Edge 80, Firefox 73, MS IE 11, Chrome 80`

* Icinga 2 version used (`icinga2 --version`):  
`icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.2-1)`

* PHP version used (`php --version`):
`PHP 7.2.24-0ubuntu0.18.04.3 `

* Server operating system and version:
`Ubuntu 18.04.4 LTS`

**Comment by nilmerg** [comment]
Hi,

this is a problem with one of the installed modules you have. Please list them with their version you've got.

**Comment by 42bios** [comment]
Ha, thank you for the hint (y) 
-> the problem was the "Snow Theme" from mikesch-mp.
I removed the module and now works without errors.

**Comment by lippserd** [comment]
Hi,

Thanks for the quick feedback. I've reopened the issue because we should not crash here even if a module has a flawed `module.info`.

Best,
Eric

**Comment by shadabkhan-sk** [comment]
You have to learn base MySQL database tables rows delete information. 
You have to delete the last entry from you MySQL database which you created. 
In my case, i enter the wrong entry host from the Icinga director which was created this issue so i login to mysql server and deleted the stuck entry.
dev_vpn_server is my wrong host entry who created issues. Please replace it with you last wrong entry.
Please find the command below in my case. 

use director_icinga; (It is your icinga director database name)
SELECT * FROM icinga_host WHERE object_name = "dev_vpn_server"; (filter all your wrong entery rows and delete one by one) 
DELETE FROM icinga_host WHERE object_name = "dev_vpn_server";
DELETE FROM director_activity_log WHERE id = "dev_vpn_server";
