### ISSUE TITLE
Schedule Downtime with Edge: Wrong Date format

### ISSUE THREAD

**Issue by ErwinE** [Icinga/icingaweb2#4093]
## Describe the bug

If we try to plan a downtime of a host or service with the Edge browser and using the calendar function, a error message appears. Same with Edge based on chromium. 
"Start Time not in the expected format: Y-m-d\TH:i:s"

With the Chrome Browser it works as usual.
If you put the date manually without the calender function, it works with the Edge Browser too.

## To Reproduce

1. Use the Downtime function in Icinga Web 2 with Microsoft Edge Browser
2. Click on Calender Button next to Start or End Time, to put the date in it
3. Press "Schedule Downtime"

## Screenshots
![image](https://user-images.githubusercontent.com/54027101/75781641-dda2d800-5d5d-11ea-9b52-24c33d819d46.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.7.3
* Web browser used: Tested with Microsoft Edge and Microsoft Edge chromium
* Icinga 2 version used (`icinga2 --version`): 2.11.3
* PHP version used (`php --version`): 7.3.15
* Server operating system and version: Red Hat Enterprise Linux Server release 7.7

**Comment by nilmerg** [comment]
Hi,

which version of Edge is this exactly? (Or Windows version, if that matters)

**Comment by ErwinE** [comment]
Hi,
I am using the following versions:
- Edge based on Chromium version 80.0.361.62 (64-Bit)
- Windows 10 Version 1903 (Build 18362.657)

**Comment by ErwinE** [comment]
> Hi,
> 
> which version of Edge is this exactly? (Or Windows version, if that matters)

Hi,
I am using the following versions:

Edge based on Chromium version 80.0.361.62 (64-Bit)
Windows 10 Version 1903 (Build 18362.657)

**Comment by FreezFree** [comment]
Same here:

- Icinga Web 2 version: 2.7.3
- Icinga 2 version: r2.11.3-1
- PHP version: 7.2.24
- Server operating system: Ubuntu 18.04.4 LTS (4.15.0-88-generic)

Edge Chromium 80.0.361.66 - Wrong Format - doesn't work
![image](https://user-images.githubusercontent.com/21083552/76537731-80560780-647e-11ea-90fc-ff5375682016.png)

Mozilla Firefox 74.0 - Right Format - works
![image](https://user-images.githubusercontent.com/21083552/76537908-bb583b00-647e-11ea-9c9e-9ee1094c5bee.png)

Google Chrome 80.0.3987.132 - Visually wrong, but works
![image](https://user-images.githubusercontent.com/21083552/76538096-0c682f00-647f-11ea-877f-665bffa8d8e7.png)

**Comment by derJD** [comment]
Same here:
* Icinga2 version 2.11.3
* Icingaweb2 version 2.7.3
* PHP version 7.3.14
 * Server OS version Debian GNI/Linux 10 (buster)

* Chromium Edge Version 80.0.361.69 (Official build) (64-bit)
![grafik](https://user-images.githubusercontent.com/5338396/77754832-63980300-702c-11ea-9102-b9f764b19dd8.png)

**Comment by 408573** [comment]
We've had the same issues here but with the latest Version of Edge (Chromium) Version 81.0.416.58 (Official Build) it seems to work fine.

**Comment by ErwinE** [comment]
> We've had the same issues here but with the latest Version of Edge (Chromium) Version 81.0.416.58 (Official Build) it seems to work fine.

Tested it also with the newest version of Edge (Chromium) and it seems to work fine now.
