### ISSUE TITLE
Column layout broken by wide content

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#4097]
To reproduce this it should suffice to fill the right column (`#col2`) with a wide table. It is expected to scroll horizontally.

## Icinga Web 2.7.3

![importsource_preview_2 7 3](https://user-images.githubusercontent.com/553008/75955785-d9d69900-5eb6-11ea-8277-49d29727fabf.png)

## Current master

![importsource_preview_master](https://user-images.githubusercontent.com/553008/75955954-25894280-5eb7-11ea-883e-e9eb423ca021.png)

**Comment by Thomas-Gelf** [comment]
NB: It behaves unpredictable and very creative. Often the full menu vanishes, sometimes only part of it:

![importsource_variant](https://user-images.githubusercontent.com/553008/75958473-97b05600-5ebc-11ea-95ef-681a4e34dbe8.png)

**Comment by nilmerg** [comment]
That's the same as with https://github.com/Icinga/icingaweb2-module-director/issues/2065. You really should get rid of your `width: 50%` instructions (Replace with `flex-grow: 1`), these are incompatible with the flex box layout.

**Comment by Thomas-Gelf** [comment]
@nilmerg: how would you implement this to keep compatibility with different Icinga Web 2 versions?

**Comment by nilmerg** [comment]
The new layout uses an additional container (`.content-wrapper`) with which you can define different rules.

e.g.
```css
#layout.twocols > .content-wrapper #col1 {
  // flexbox rules
}

#layout.twocols > #main #col1 {
  // legacy rules
}
```

**Comment by Thomas-Gelf** [comment]
Thanks, I'll give it a try
