### ISSUE TITLE
convert service grid into list and back

### ISSUE THREAD

**Issue by OG2K** [Icinga/icingaweb2#4104]
## Purpose
increase usability
1) to perform actions, using multiselect
2) to visualize similar services and similar hosts

## Expected Behavior
convert services, which are presented in service grid into list.
convert services, which are presented in list into service grid

## Current Behavior
feature is absent

## Possible Solution
create link/button [convert to service grid] and [convert to list]

## Your Environment
Icinga Web 2 Version 2.7.3
Git commit 06cabfe8ba28cf545a42c92f25484383191a4e51
PHP Version 7.1.30
Git commit date 2019-10-18
Copyright © 2013-2020 The Icinga Project

icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.2-1)

System information:
Platform: Red Hat Enterprise Linux Server
Platform version: 7.7 (Maipo)
Kernel: Linux
Kernel version: 3.10.0-1062.12.1.el7.x86_64
Architecture: x86_64

Build information:
Compiler: GNU 4.8.5
Build host: runner-LTrJQZ9N-project-322-concurrent-0

Webserver, PHP versions:
httpd -v
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built: Jun 9 2019 13:01:04

![Annotation 2020-03-02 143112 - convert to list](https://user-images.githubusercontent.com/9702688/75675467-46c01800-5c98-11ea-9217-4abd0a9b8d85.png)

**Comment by nilmerg** [comment]
Hi,

each host- and service-name is a link you can click, which then leads you to the services presented in the respective row/column.

Doesn't this already allow you to do everything you want?

**Comment by OG2K** [comment]
Dear Johannes,

No, it does not, Clicking on host column or service row will open only to host or service related issues. But NOT to both.
For example: "all checks on *host* named hosts ".  In my example pattern "*host*" found two hosts which have 9 issues. To acknowledge all of them, I need to make  a list first, multiselect them and hit [acknowledge].
Another situation, when I would look for all "*IMAP*" service checks, let's assume, 10 servers will be found and I want to run [check now] action on them. That also need, first lest to be created and then multiselect, [check now].

Thank you for pointing that out, that my description was not clear enough.

BR /A

**Comment by nilmerg** [comment]
So it's only the actions you miss. Not the list itself. Then I suppose it's sufficient to allow you to perform actions right on the servicegrid?

i.e. you set the filter as shown in your second screenshot and from there you directly open the multi-selection view (what's usually shown upon selecting multiple list entries manually) without the list in-between.

**Comment by nilmerg** [comment]
We'll make sure the service grid in Icinga DB Web allows to perform actions on the shown services when filtering.

**Comment by OG2K** [comment]
Dear nilmerg,
Thanks for keeping updated.
Indeed, final action is needed, not list itself. Usually, "check now", "acknowledge" or perform multitask operation.
BR /A
