### ISSUE TITLE
Grafana Graph Displaying wrong time 

### ISSUE THREAD

**Issue by leonmarquez** [Icinga/icingaweb2#4119]
## Describe the bug
The grafana graph is not displaying the correct time. The values in the graph are matching as if the time was right. If i click on the graph and open it in Grafana it displays the correct values.
Icingaweb2 detects the right browser timer: Europe/Paris

## Expected behavior
The graph should display the correct time matching the values above.

## Screenshots

![image](https://user-images.githubusercontent.com/16097307/78258058-f9370500-74fa-11ea-9362-1a0080df8d7f.png)
Current time in the Image: 15:58 / 3:58pm

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.6.2 and module 1.3.5
* Web browser used: Chrome, Firefox, Edge
* Icinga 2 version used (`icinga2 --version`): r2.10.2-1
* PHP version used (`php --version`): PHP 7.0.33-0+deb9u6
* Server operating system and version: Debian GNU/Linux 9

**Comment by nilmerg** [comment]
Hi,

is this from the [grafana module](https://github.com/Mikesch-mp/icingaweb2-module-grafana)? Shouldn't the issue be opened over there then? Icinga Web 2 only shows the graph but doesn't have any control over its contents.

**Comment by leonmarquez** [comment]
Hi,
thats what i am not sure about.
I dont know if it is a problem with the module or if icingaweb2 is getting the right time.

**Comment by nilmerg** [comment]
Just look at the various places where Icinga Web 2 shows a date. History entries for example do that. Or add a comment and check what's displayed as entry time.

**Comment by leonmarquez** [comment]
Okay seems to be a issue related to the module
