### ISSUE TITLE
Update dependent PHP requirement on CentOS7

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2#4128]
## Describe the bug
The dependent PHP requirement on CentOS7 should be updated from php71 to php72 or php73. Especially the "icingadb"-module (https://github.com/Icinga/icingadb-web) requires PhpRedis, which is not available as a package for php71 (only sclo-php72-php-pecl-redis5 and sclo-php73-php-pecl-redis5).

## To Reproduce
see above

## Expected behavior
see above

## Screenshots
not necessary

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.8.0 RC
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.12.0 RC
* PHP version used (`php --version`): 7.1
* Server operating system and version: CentOS 7.7

## Additional context
not necessary

**Comment by nilmerg** [comment]
Hi,

this is rather a package issue. I've created a new issue in our package repository. Closing here.
