### ISSUE TITLE
LDAPS validation fails 

### ISSUE THREAD

**Issue by BTT-Nick** [Icinga/icingaweb2#4142]
## Describe the bug
The validation for LDAPS connection in icingaweb2 returns 2/3 of the time an error.
When then saved with valid configuration the login attempt also is not working 2/3 of the times. 

## To Reproduce
Icingaweb2 -> Application - Ressources
![image](https://user-images.githubusercontent.com/64477716/80490875-47a4bb80-8962-11ea-9048-b1b5c10d7c1c.png)

1. Click Validate Configuration

Mentioned before if i just re-click the button "Validate Configuration" it works 2/3.

![image](https://user-images.githubusercontent.com/64477716/80491058-8175c200-8962-11ea-8192-c2ac8eef239f.png)

## Expected behavior
The connection to LDAPS should work all the time. 

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.7.3
* Web browser used: Chrome, Firefox, MS Edge
* Icinga 2 version used (`icinga2 --version`): 2.11.3-1
* PHP version used (`php --version`): 7.1.30
* Server operating system and version: RHEL 7.8

## Additional context
LDAPS connection through CLI work fine without failed connections. 
Tested with: `ldapsearch`

**Comment by lippserd** [comment]
Hi @BTT-Nick,

Thanks for the report. Could you please double check all server nodes belonging to the DN.
It may be the case that not every node is configured properly.

All the best,
Eric

**Comment by BTT-Nick** [comment]
Hi @lippserd,

just to be sure, you mean the AD servers right? 
Indeed we have two resources configured, one with only a single node were the connection is established to and there also is the same behavior. 

BR
Nicolas

**Comment by nilmerg** [comment]
Eric didn't meant resources you've configured in Icinga Web 2. He was referring to what you've configured as host for a single resource.

There were already cases in other occasions where this was a load-balanced endpoint and only a part of the nodes behind it were able to properly serve connections with Icinga Web 2. Either because they didn't respond to TLS or due to other configuration issues.

**Comment by BTT-Nick** [comment]
@nilmerg ok then i understand it correctly. 

The following configuration only uses one endpoint and that is not load-balanced. 
![image](https://user-images.githubusercontent.com/64477716/81795889-f6bdc700-950c-11ea-8da3-c338761b7f0f.png)

and there is the same behavior. 

BR 
Nicolas

**Comment by BTT-Nick** [comment]
*Fixed*
I changed the Host from IP to FQDN and it is now working fine.

/solved
