### ISSUE TITLE
Please don't swear in release notes

### ISSUE THREAD

**Issue by bootc** [Icinga/icingaweb2#4172]
## Describe the bug
"Our latest hot shit is now available" makes you look immature and stupid

## To Reproduce
https://github.com/Icinga/icingaweb2/releases/tag/v2.8.0

The word "shit" doesn't bother me, but in this setting it makes you look really silly. I can imagine this putting lots of people and potentially organisations off Icinga. You can get the same message across without silly language.

## Expected behavior
Just use plain English please.

**Comment by nilmerg** [comment]
Hi,

we just try to put some *life* into our release notes. Everyone can write boring release notes. The phrase *hot shit* is meant with a little wink that we're proud of our work and those of others while emphasizing that this is a highly subjective opinion.

Though, I can imagine that this might be too offensive or vulgar to others. Updated the release notes..
