### ISSUE TITLE
Tactical overview showing "-1 pending" hosts

### ISSUE THREAD

**Issue by Stefomat** [Icinga/icingaweb2#4174]
## Describe the bug
After updating to icingaweb2 2.8.0 the tactical overview shows the following behavior.

- There are 0 pending hosts: tactical overview shows "-1 pending" hosts,

- There is 1 pending host: tactical overview shows no number,

- There are 2 pending hosts: tactical overview shows "1 pending" host,

- So on and so forth...

## To Reproduce
1. have icingaweb2 in version 2.7.3 installed
2. update icingaweb2 to version 2.8.0 via apt
3. go to tactical overview, without having a pending host in your monitoring

## Expected behavior
I expect the tactical overview to correctly count the number of hosts in the pending state.

## Screenshots
No host pending
![no host pending](https://user-images.githubusercontent.com/41241946/84129019-aa00d980-aa41-11ea-9f4f-b2e581c33ac3.png)
One host pending
![one host pending](https://user-images.githubusercontent.com/41241946/84129022-ab320680-aa41-11ea-9089-d60cdf7ac172.png)
Two hosts pending
![two hosts pending](https://user-images.githubusercontent.com/41241946/84129023-abca9d00-aa41-11ea-8b27-9bf30c7e18c9.png)

## Your Environment
* Icinga Web 2 version and modules (System - About):
![2020-06-09 10_46_21-About __ Icinga Web](https://user-images.githubusercontent.com/41241946/84126684-85efc900-aa3e-11ea-84a7-4900d0c86f16.png)

* Web browser used:
Firefox 68.9.0esr

* Icinga 2 version used (`icinga2 --version`):
```icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.3-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 4.19.0-9-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-LTrJQZ9N-project-298-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* PHP version used (`php --version`):
```PHP 7.3.14-1~deb10u1 (cli) (built: Feb 16 2020 15:07:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```

* Server operating system and version:
Debian GNU/Linux 10.4 (buster)

## Additional context
As the tactical overview always shows one less host being in pending state than there realy is,
I suspect [this commit](https://github.com/Icinga/icingaweb2/pull/4126/commits/289a6991cbd1521b60a709706c4f6e3de326826b) to have something to do with this problem.
Keep in mind though, I am by no means a developer.

greetings
Stefomat

**Comment by nilmerg** [comment]
Hi,

that's due to #3280. Not checked objects (which were never checked at all) are not pending anymore in the tactical overview now. Though, that there's `-1` shown in one of your cases is not intended of course.

**Comment by dolefi** [comment]
Hi guys, 
I am experiencing simmilar issue. Altho my issue is with services and not hosts. My Pending shows -6.

![image](https://user-images.githubusercontent.com/17765008/84262663-46001300-ab1e-11ea-88ea-9dfb4ca9c431.png)

Is this the same problem as for hosts ?

**Comment by nilmerg** [comment]
@dolefi Yes.

To both of you, could you please click on `Not Checked` and include a screenshot of the resulting list?
