### ISSUE TITLE
Filter: Hostgroup(case insensitive)

### ISSUE THREAD

**Issue by martindemharter** [Icinga/icingaweb2#4178]
## Bug:
Case insensitiveness is gone in the service-grid filter for Hostgroup (**case insensitive**)

## Example:
Different results for filter hostgroup (case insensitive):
Hostgroup: Customer:Client1 != Hostgroup: Customer:CLIENT1 != Hostgroup: CUSTOMER:Client1 != Hostgroup: CUSTOMER:CLIENT1

## Expected behavior
Case sensitiveness does not matter. It should always show the same results.

## Environment
* Icinga2: 2.11.3-1
* Icingaweb2: 2.8.0.1
* Modules:
director | 1.7.2
doc | 2.8.0
grafana | 1.3.5
incubator | 0.5.0
ipl | v0.4.0
monitoring | 2.8.0
reactbundle | 0.7.0
* OS: Ubuntu 18.04.4 - Kernel version: 4.15.0-106-generic
* Web browser used: Firefox 68.9.0/32Bit & Microsoft Edge 44.17763.831.0
* PHP version: 7.4.7

Thanks in advance!

**Comment by nilmerg** [comment]
Hi,

works for me very well.

Please include a proper formatted filter (our column names do not contain any colons) and the database vendor + version your using.

**Comment by martindemharter** [comment]
Sorry, due to GDPR i have to censor some parts: 
The relevant part of the URL is: **&hostgroup=STAGE%3ALIVE** vs. **&hostgroup=STAGE%3ALive**

I added also two screenshots. The whole difference in those two icingaweb2 screenshots is, that in one case i wrote **STAGE:Live** and in the other case i wrote **STAGE:LIVE**
![github_icingaweb2_filterissue_caseinsensitive](https://user-images.githubusercontent.com/66956665/84673512-17bd7180-af2a-11ea-8ed0-9b58ed6bd56f.PNG)
![github_icingaweb2_filterissue_casesensitive](https://user-images.githubusercontent.com/66956665/84673521-18560800-af2a-11ea-9638-e90643ef3cfc.PNG)

**Comment by nilmerg** [comment]
Reproduced it successfully. It's Postgres specific and only applies to case-insensitive columns testing for combined memberships. (Since #3457)
