### ISSUE TITLE
Setup Wizard: Module selection broken with too many modules (overflow)

### ISSUE THREAD

**Issue by N-o-X** [Icinga/icingaweb2#4193]
## Describe the bug
The setup wizards module selection can break if you have many modules (needs overflow) and activate one in the lower rows. This then looks a bit like `margin-top: -80%` on the body.

## To Reproduce
1. Install many modules (15+, depends on your resolutions)
2. Go to the setup wizards module selection screen
3. Make sure to have some overflow (enough modules)
4. Scroll down and enable one of the modules in the last row
5. The UI should be broken as seen in the screenshots

## Screenshots
Before
<img width="1680" alt="Screenshot 2020-06-23 at 16 42 30" src="https://user-images.githubusercontent.com/9316896/85419144-fedc3e00-b571-11ea-80eb-80e89d0c0df8.png">

After
<img width="1680" alt="Screenshot 2020-06-23 at 16 43 08" src="https://user-images.githubusercontent.com/9316896/85419187-0b609680-b572-11ea-8099-65da0de3ef61.png">

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): Current master (361fc27)
* Web browser used: Google Chrome, Firefox

**Comment by flourish86** [comment]
It seems like this is weird behaviour related to the browser trying to scroll to focussed elements. To be honest, I ran out of ideas on how to solve this. 😬

**Comment by flourish86** [comment]
Should be fixed with 7ce3997, which was related to #4310.

**Comment by lippserd** [comment]
> Should be fixed with [7ce3997](https://github.com/Icinga/icingaweb2/commit/7ce3997db89e6c7a1b0c26e6bf4ddb4f641b5b79), which was related to #4310.

@flourish86 Could you please verify that?

**Comment by flourish86** [comment]
> > Should be fixed with [7ce3997](https://github.com/Icinga/icingaweb2/commit/7ce3997db89e6c7a1b0c26e6bf4ddb4f641b5b79), which was related to #4310.
> 
> @flourish86 Could you please verify that?

Yes, it’s fixed. But with [this commit](https://github.com/WuerthPhoenix/icingaweb2/commit/24c1bb1f8cc63e811fc60d0157a895de9ab3569f).
