### ISSUE TITLE
GraphDash Module broken since Icinga Web V.2.8.0

### ISSUE THREAD

**Issue by geotekberlin** [Icinga/icingaweb2#4194]
## Describe the bug
A clear and concise description of what the issue is.

The GraphDash Module is broken after upgrading Icinga Web from V.2.7.3 to V.2.8.0.  Error Message is:

#0 /usr/share/icingaweb2/modules/graphdash/application/views/scripts/month/index.phtml(11): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Web/View.php(248): include(String)
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run(String)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL)
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript(String, NULL)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#13 {main}

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Install GraphDash Module from Icinga Exchange and enable it
2. Define one or more Graphs
3. Click on the "GraphDash" link on any associated host or service
4.

## Expected behavior
Either defined Graphs should appear or a message saying that no graphs were defined yet

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version  2.8.0
cube 	1.1.0
director 	master
doc 	2.8.0
graphdash 	1.0
incubator 	0.5.0
ipl 	v0.4.0
monitoring 	2.8.0
pnp 	1.1.0
reactbundle 	0.7.0
vspheredb 	1.1.0 

* Web browser used: Firefox 77.0.1

* Icinga 2 version used 2.11.4-1 from Debian repo

* PHP version used 7.3.14-1~deb10u1

* Server operating system and version:  Debian 10, 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

## Additional context
Problem occurs also with Icinga Admin Role, so it does not seem to be a privilege issue. GrapDash worked perfectly with all previous versions of Icinga Web 2

**Comment by lippserd** [comment]
Hi,

You are using PHP short open tags, i.e. `<?` instead of `<?php` in your view scripts. That is discouraged because it requires `short_open_tags` to be enabled and actually deprecated since PHP version 7.4. With Web version 2.8.0 we've removed our short open tag compatibility layer and that's why you're getting the error. You could enable `short_open_tags` if you're not running PHP version 7.4+ but you really should fix your scripts and use `<?php` instead of `<?`.

All the best,
Eric
