### ISSUE TITLE
Single negated membership filter fails with PostgreSQL

### ISSUE THREAD

**Issue by mphilipps** [Icinga/icingaweb2#4196]
Hi,
Since updating from 2.8.0 to 2.8.1 filtering for Servicegroup (case insensitive) fails when used negated.

`/monitoring/list/servicegrid?servicegroup!=Support status`

**array_map(): Argument #2 should be an array**

Also the snapshot builds are still at 2.8.0 undermining the whole point of having them.

**Comment by nilmerg** [comment]
Hi,

thanks for the report :neutral_face: 

I know that's only a workaround, but if you use multiple conditions or wrap a single condition in parentheses (i.e. `(servicegroup!=Support Status)`), this error doesn't occur.

That the snapshots are not up to date, is unfortunately a recurring problem, we're on it.
