### ISSUE TITLE
Filter editor limited to page height

### ISSUE THREAD

**Issue by lucafwp** [Icinga/icingaweb2#4199]
## Describe the bug
Using a lot of filter conditions in filter editor blocks user from saving the filter.
The right browser scroll does not affect the page. Only decreasing zoom level allows user to continue editing the filter.

## To Reproduce

1. Navigato to Overview >> Services
2. Add at least 10 filter conditions with different depth levels
3. Try to save

## Expected behavior
Users should be able to use as many filter conditions as they need.

## Screenshots
![image](https://user-images.githubusercontent.com/36190810/86470202-39489680-bd3b-11ea-949c-8575ddb008f3.png)

## Your Environment

* Icinga Web 2 version: 2.7.3
* Icinga Web 2 modules:
director | 1.7.2
incubator | 0.5.0
ipl | v0.5.0
monitoring | 2.7.3
reactbundle | 0.7.0
* Web browser used: Chrome Version 83.0.4103.116 
* Icinga 2 version used (`icinga2 --version`): 2.11.4-1
* PHP version used (`php --version`): 5.6.40 (+rh-php71-1-1)
* Server operating system and version: CentOS Linux release 7.8.2003 (Core)

**Comment by nilmerg** [comment]
Hi,

please upgrade to version 2.8+, the latest version is not affected by this.

**Comment by lucafwp** [comment]
Confirmed, with version 2.8.2 works correctly.
Thanks
