### ISSUE TITLE
Enlarge Service Grid

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2#4205]
## Is your feature request related to a problem? Please describe.
The Service Grid shows "only" 20 lines per default, this should be enlarged to a defineable or selected number of rows. Maybe depending on the screen resolution.

**Comment by carraroj** [comment]
ref/NC/685537

**Comment by carraroj** [comment]
The Event-Grid with more the 20 events is not able to expand with the button "more" if you save the url  from the event-grid as dashlet in Icinga Web 2, because the button "more" isn't visible.

**Comment by nilmerg** [comment]
Hi Markus,

please be more specific what you exactly want. Because it is possible to enlarge the service grid by clicking on *Load More* in the respective direction. This is also persisted in the resulting URL, so the enlarged grid can be added to the menu or dashboard.

What more do you want?

**Comment by mwaldmueller** [comment]
In the meanwhile I found the solution. The curious thing is that the limit of 20 for "dasbhoard1" doesn't work in my case and the lines in "dashboard2" are unlimited. Can you explain why?

```
[test]
title = "test"

[test.dashboard1]
url = "monitoring/list/servicegrid?host_name=webservices%2A&modifyFilter=1&limit=20"
title = "dashboard1"

[test.dashboard2]
url = "monitoring/list/servicegrid?host_name=webservices%2A&modifyFilter=1&limit=20%2C100"
title = "dashboard2"
```

**Comment by nilmerg** [comment]
No, works for me. What version of Icinga Web 2 are you using?
![Screenshot from 2020-09-04 09-30-09](https://user-images.githubusercontent.com/16668527/92211906-76431d80-ee91-11ea-9c5d-3c6266f4db01.png)

**Comment by mwaldmueller** [comment]
Icinga Web 2.8.2

I can show it to you next week directly on the customer environment.

**Comment by mwaldmueller** [comment]
The explanation is that the limit-parameter requires values for x- and y-axis separated with a comma, otherwise the default is 20.
