### ISSUE TITLE
Tab is too small with Object Inspection

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2#4207]
## Describe the bug
If the Director module is enabled and you click on the "Inspect"-action link at a Host or Service, the middle tab is too small.

## Screenshots
![inspect](https://user-images.githubusercontent.com/3973350/87418770-901f5d00-c5d2-11ea-95ef-1eac06d1c5e6.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.8.1
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.11.4
* PHP version used (`php --version`): 7.3
* Server operating system and version: CentOS 7.8

**Comment by nilmerg** [comment]
Hi,

this is a bug in the director: https://github.com/Icinga/icingaweb2-module-director/issues/2065
