### ISSUE TITLE
Add show more links in the service grid

### ISSUE THREAD

**Issue by carraroj** [Icinga/icingaweb2#4208]
## Describe the bug
expand view in servicegrid is not working if you create a dashlet of the servicegrid

## To Reproduce
1. open servicegrid in icingaweb2
2. klick on "load more" to expand the view
3. create a dashlet with this view in a dashboard
4. the is no botton "load more" to extend the view its just cut off in this dashlet

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.8.1-1
* Web browser used:
* Icinga 2 version used (`icinga2 --version`):2.11.4-1
* PHP version used (`php --version`): rh-php7.3-fpm
[Web2-Dashboard-Fehler-3.docx](https://github.com/Icinga/icingaweb2/files/4919281/Web2-Dashboard-Fehler-3.docx)

* Server operating system and version: CentOS 7

**Comment by carraroj** [comment]
ref/NC/685537

**Comment by nilmerg** [comment]
Hi,

the load more functionality is not supposed to be used in a dashlet. There's limited space available in dashlets, so any view displayed there is rather static and needs to be defined when the dashlet is added. Later adjustments are only possible by changing the dashlet's configuration.

However, you can click on the dashlet's title to open the view in the next column and use `Load More` there.

Additionally, there are currently enhanced dashboards (#3809) in the works, which will allow to resize dashlets on demand. Content of a resized dashlet is then supposed to fill the new available height/width automatically and we don't need `Load More` any longer. So I close this in favor of this.
