### ISSUE TITLE
Can't save in /etc/icingaweb2 !!

### ISSUE THREAD

**Issue by DocMAX** [Icinga/icingaweb2#4212]
## Describe the bug
When saving i get an error:

Saving Configuration Failed
The file /etc/icingaweb2/config.ini couldn't be stored. (Error: "file_put_contents(/etc/icingaweb2/config.ini): failed to open stream: Read-only file system") 

I checked permissions and they are fine. Even chmod 777 did not fix the issue.

## Expected behavior
Save config without errors

## Your Environment

Icinga Web 2 Version
    2.8.1
Git commit
    233bd29e4104125b4e5ef631e8c16dde33dadd9a
PHP Version
    7.4.8

director | 1.7.2
incubator | 0.5.0
ipl | v0.5.0
monitoring | 2.8.1
reactbundle | 0.7.0

**Comment by DocMAX** [comment]
looks like an arch linux package problem

**Comment by der-martin85** [comment]
I have the same problem under openSuse 15.2

Icinga Web 2 Version 2.8.2-1
PHP 7.4.6 (FPM)

SELinux is disabled, which is the only thing I found on the internet regarding this issue...
