### ISSUE TITLE
LDAP handling of mulitple UID

### ISSUE THREAD

**Issue by HipDragon** [Icinga/icingaweb2#4213]
LDAP authentication should be expanded to handle data that could be entered into a LDAP server by default. This includes the ability to handle when an user has multiple UID set. UID by default allows for multiple values in LDAP servers [LDAP UID IETF](https://tools.ietf.org/html/rfc4519#page-18). 

Icinga LDAP implementation currently expects one to change their LDAP configuration to only allow a single value. If multiple values are found it will cause an error. The error message is "strtolower() expects parameter 1 to be string, array". This also applies to groups as well with their identifier, which most commonly is set to CN.

One should not have to change their LDAP configuration to match the software using it. But the software should conform to the LDAP standards as defined.

**Comment by nilmerg** [comment]
This is coming from https://community.icinga.com/t/ldap-user-validation-error/4592

**Comment by nilmerg** [comment]
Hi,

I've attempted to fix this today and I think I succeeded. Though, I only have a *development* LDAP environment here, not a production one, so I'd welcome any tests in your environment. You can find the changes in the linked pull request (branch). If you need help applying the changes to your installation, don't hesitate to ask for help. :smiley:

**Comment by HipDragon** [comment]
I'll pass it along to the people who now manage it. I switched jobs, so no longer have access to that environment to test for you. I'm hoping you solved it, sorry I could not be of more help this time.

**Comment by vijayasaradhi-danda** [comment]
@nilmerg  after applying the changes, I don't see the exception anymore.

**Comment by nilmerg** [comment]
Thanks for the feedback @vijayasaradhi-danda !
