### ISSUE TITLE
Collapsible on Detail Plugin Output doesn't work reliably

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2#4216]
## Describe the bug
In some cases having the plugin output container transformed to a collapsible container won't work reliably.

## To Reproduce
1) Go to a Icinga DB Services or Hosts list
2) Click through list items
3) In detail view some plugin output containers aren't collapsed properly, when applicable (> 100 px, as `data-visible-height="100"` implies)

## Expected behavior
Plugin output that is taller than 100px should be collapsibe.

## Screenshots
![Screenshot 2020-08-03 at 10 26 32](https://user-images.githubusercontent.com/6977434/89162823-e732a500-d574-11ea-9eb9-5a510441680b.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 2.8.1
* Safari, Chrome, Firefox

**Comment by nilmerg** [comment]
This is working as intended. The rows or height of the content need to be double than what `data-visible-rows` or `data-visible-height` are set to. This avoids seemingly unnecessary collapsed states. In your example, for example, only 38 pixels would be collapsed which would be totally unnecessary and annoying.

**Comment by flourish86** [comment]
Sounds reasonable. 😉
