### ISSUE TITLE
make splitscreen border movable/fixed 50:50

### ISSUE THREAD

**Issue by martindemharter** [Icinga/icingaweb2#4225]
## Is your feature request related to a problem? Please describe.
I use the splitscreen functionality a lot. So for example opening a detail view of a certain check, using the director and so on.
I have the issue, that it seems to be random, how the widthness is portioned between the left and the right window.
So most of the times it is almost in the middle, and i have no issue with that. 

But sometimes, it divides seemingly 30 - 70 ratio, and then its not comfortable to read in the smaller part.
Currently i am working on Firefox 78.1 (beforehand it was 68.1 for a long time, sry i have no influence on that matter). 

Currently, if it does not open the splitscreen properly, i am closing the splitscreen, and open again. Then it is usually in the right place. If necessary, rinse and repeat.

## Describe the solution you'd like
My best guess would be switching it to either 50:50 or make it movable.

## Additional context
All size and portion mentions are excluding the sidebar/menu. The sidebar is fine as it is.

Greetings

Martin

Screenshot for reference (this one is a good one, sry not to have one with actual panel-width 'issues'):
![image](https://user-images.githubusercontent.com/66956665/90225112-0ea92d80-de11-11ea-9646-d50b34635e21.png)

**Comment by nilmerg** [comment]
Hi,

is the panel-width issue you're experiencing [this one](https://github.com/Icinga/icingaweb2-module-director/issues/2065)?

**Comment by nilmerg** [comment]
I guess it's the issue you experienced. Should be solved in the next director release.
