### ISSUE TITLE
Duplicate Service Entrys in Monitoring with multiple Notification-Contacts

### ISSUE THREAD

**Issue by Tqnsls** [Icinga/icingaweb2#4238]
## Describe the bug
When having a host or a service with more than one notification-contacts, the module monitoring shows multiple entries of the same host or service as soon as one of the following conditions is met

- add a "&addColumns=host_contact" to the URL

- add a "&addColumns=service_contact" to the URL

- the modifyFilter filters for different host- or service-contacts

Also the CLI shows multiple entries when executing 
"icingacli monitoring list hosts --format csv --columns 'host,host_contact' --host=<hostname>" 
or 
"icingacli monitoring list services --format csv --columns 'host,host_address,service,host_contact' --host=<hostname> --service=<servicename>".

## To Reproduce
1. Install and configure icinga2 and icingaweb2.

2. Add a host or a service that matches more than one Notification Apply Rule, so more than one contact will be applied to the host / service.

## Expected behavior
Show only one entry of the host / service.

## Screenshots
in the screenshots you can see that as soon as the filter or the column is removed the number of entries is reduced to one.

![icingacli_host](https://user-images.githubusercontent.com/67681686/95186724-96386a80-07ca-11eb-8106-a14169473e07.png)
![icingacli_service](https://user-images.githubusercontent.com/67681686/95186729-96d10100-07ca-11eb-8093-41c8350e0c28.png)

![monitoring1_host](https://user-images.githubusercontent.com/67681686/95186760-a05a6900-07ca-11eb-888c-25b34ddc1a37.png)
![monitoring1_service](https://user-images.githubusercontent.com/67681686/95186764-a0f2ff80-07ca-11eb-969b-6353667885a8.png)
![monitoring2_host](https://user-images.githubusercontent.com/67681686/95186766-a0f2ff80-07ca-11eb-8903-963cbe6e9acb.png)
![monitoring2_service](https://user-images.githubusercontent.com/67681686/95186767-a18b9600-07ca-11eb-8cbc-eba86a42a756.png)

and here's a screenshot that shows that both, the host and the service have more than one contact.
![monitoring](https://user-images.githubusercontent.com/67681686/95187419-6d64a500-07cb-11eb-9086-90f466d229c9.png)

*some information had to be censored due to privacy reasons*

## Your Environment
icingacli --version
Icinga Web 2  2.8.2
Git Commit    8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version   7.3.11

MODULE              VERSION
businessprocess     2.2.0
director            1.7.2
doc                 2.8.2
fileshipper         1.1.0
graphite            1.1.0
incubator           0.5.0
ipl                 v0.4.0
map                 1.1.0
monitoring          2.8.2
reactbundle         0.7.0
vspheredb           1.1.0
x509                1.0.0

icinga2 --version
icinga2 version: 2.12.0-1
System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.8 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1127.19.1.el7.x86_64
  Architecture: x86_64

**Comment by mwaldmueller** [comment]
ref/NC/681373

**Comment by nilmerg** [comment]
Hi,

this is the expected behavior. You're querying additional columns that are not part of the table the module selects from the IDO but from a related table. Since the IDO is a relational database, it is to be expected that the results contain duplicate entries if a table is joined without a group by.

The monitoring module does not add the group by automatically nor does it provide a way to control this also by URL. So anyone querying such columns needs to be aware of any duplicates and handle them accordingly. Which shouldn't be a problem, since the results of such queries are usually processed by another piece of code.

Filtering by the way works without a problem. You still had the columns queried, that's the only reason why there are duplicates.

**Comment by Tqnsls** [comment]
Hi Johannes,

thanks for answering that quick. Unfortunately this is not the answer i hoped to get. But thats ok than.
Will this "visual bug" be solved when IDO will be replaced in the future? 

> Filtering by the way works without a problem. You still had the columns queried, that's the only reason why there are duplicates.
I'm not quite sure if I understand what you mean, but for example as soon as I filter for something like 
(service_contact=mail.*|service_contact=voice.*) it shows the duplicated entries.
So in this case I would expect that the module would show me only one entry because I did not specificly query it in the frontend. Or you mean that it gets queried in the backend when I add such a filter?

**Comment by Thomas-Gelf** [comment]
> [..] Though the thing is, `addColumns` was never actually meant to show additional information in the UI, but it's rather a thing for exports (e.g. json) [..]

Please allow me to correct you here. It absolutely was, it has been built to show additional information in your dashboards. This is an essential feature for some environments I'm working with. It allows to show important context right next to your hosts and services in your dashboard.

There is one customer where they are monitoring thousands of routers from lots of locations. Their main problem dashboards have been modelled to group problem by various filters, but all filtered lists show the "location" custom variable. Whenever a bunch of new unhandled problems pops up, they can immediately spot similarities, like "most of them are in the same region".

Cheers,
Thomas

**Comment by Tqnsls** [comment]
Hi Johannes @nilmerg,
i just tested it, after implementing your commit to https://github.com/Icinga/icingaweb2/issues/4464 and I noticed that there still are duplicate entries when showing services with more than one contact. Also still happens with hosts with more than one hostgroup.
![image](https://user-images.githubusercontent.com/67681686/126643220-42f89e31-719a-4fbf-aa22-c8a94a2369df.png)
The URL I used is like
/icingaweb2/monitoring/list/services?host=foobar&(service=foobar1|service=foobar2)&modifyFilter=&sort=host_display_name&addColumns=service_contact%2Chostgroup

Do you need more system information?

**Comment by nilmerg** [comment]
Sorry, but I've already explained why this is the case and why we cannot "fix" this. It's not under our control, it's you who adds the columns using `?addColumns`. As long as you don't have a way to also define by what to group the results (say, a `?groupBy` parameter), the duplicates are to be expected.

#4273 only fixed the duplicates that occurred when *filtering* after e.g. `service_contact`.

**Comment by Tqnsls** [comment]
Ok, than I misunderstood, but (as long as one uses ?addColumns) https://github.com/Icinga/icingaweb2/pull/4273 than does _not_ fix this issue because as the title says the duplicate entries are still visible.
I just tested in 2.9.0 and 2.8.2 and in both versions you still see duplicate services when filtering after "service_contact=XYZ" and using ?addColumns.
Sure, when one does not use addColumns with service_contact or hostgroup (etc.) there are no duplicates, but just because there were _no duplicates ever_ in the GUI when one did not use addColumns.

And regarding your post from 6 Oct 2020 even when you export that view via json or csv there will be duplicate entries when using addColumns which could be very misunderstanding for "not-so-deep-icinga-users", what you could call many of our users :)
As @Thomas-Gelf stated it seemingly was intended for such dashboards we use very frequently.

Nvm, but could you imagine implementing a ?groupBy? As far I know this does not exist by now.

**Comment by nilmerg** [comment]
> as soon as I filter for something like (service_contact=mail.|service_contact=voice.) it shows the duplicated entries.

>  #4273 than does not fix this issue

The title is correct and the fix for the issue matches it. Although yeah, it only fixes half of the issue.

> there will be duplicate entries when using addColumns which could be very misunderstanding for "not-so-deep-icinga-users"

It's difficult for people that never worked with relational databases, yes.

> could you imagine implementing a ?groupBy? As far I know this does not exist by now.

Since it's only a url parameter (that still is not documented anywhere), which also only applies to the host and service list.. I wouldn't count on it.

However, I can imagine how this may be solved: A specific widget such as the sort control, that allows to apply functions on columns. One of those could be a function to group values and concatenate them by a user defined separator. Something like that could be easily implemented for [Icinga DB Web](https://github.com/Icinga/icingadb-web/issues/82). :grin:
