### ISSUE TITLE
Cannot open roles for viewing/editing

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2#4240]
## Describe the bug
Since I installed icingadb module I can't open any role in **Authentication - Roles** 

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

Not sure but it seems to look for icingadb module (which is disabled).

## Expected behavior

Open the role

## Screenshots

![image](https://user-images.githubusercontent.com/31234197/95747932-e9fef400-0ca1-11eb-8ab8-8c01acc71656.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
![image](https://user-images.githubusercontent.com/31234197/95748028-1286ee00-0ca2-11eb-851b-7d37f8e7d879.png)

* Web browser used:
Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

* Icinga 2 version used (`icinga2 --version`):
```
$ icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.0-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-13-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* PHP version used (`php --version`):
`$ php --version
PHP 7.0.33-0+deb9u9 (cli) (built: Aug 24 2020 11:14:22) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u9, Copyright (c) 1999-2017, by Zend Technologies
`
* Server operating system and version:
`$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`
* IcingaWeb2 modules:
```
$ icingacli module list
MODULE         VERSION   STATE     DESCRIPTION
amothemes      0.0.0     enabled   amothemes
businessprocess 2.1.0     enabled   A Business Process viewer and modeler
dashing-icinga2 0.0.0     enabled   dashing-icinga2
director       1.7.1     enabled   Director - Config tool for Icinga 2
globe          1.0.4     enabled   Globe 3D module
grafana        1.3.6     enabled   Grafana - A perfdata visualisation module
incubator      0.5.0     enabled   Incubator provides bleeding-edge libraries
ipl            v0.5.0    enabled   The Icinga PHP library
map            1.0.3     enabled   Map visualization
monitoring     2.7.3     enabled   Icinga monitoring module
reactbundle    0.7.0     enabled   ReactPHP-based 3rd party libraries
unicorn        1.0.2     enabled   Unicorn Theme
vspheredb      1.1.0     enabled   VMware vSphere DB
```

**Comment by nilmerg** [comment]
Hi,

this is due to the version of Icinga Web 2. Icinga DB Web requires 2.8+ to run.

The reason why you run into this error despite Icinga DB Web being disabled, is that the role configuration tries to load permissions/restrictions from all modules no matter their active state.

So strictly speaking, this is actually a dependency issue you have here. To solve this, either upgrade Icinga Web 2 or remove Icinga DB Web entirely.

**Comment by bunghi** [comment]
I upgraded Icinga Web 2 and now it works. Thanks for the hint! ;)
