### ISSUE TITLE
Coloring bug in the state badges

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingaweb2#4244]
## Describe the bug
Hello,

the bug only occurs when there are pending hosts or services. An aditional placeholder (?) apears an when you click either on the badge with host- or service state 0 / 99, the color of the badge with state 0 shifts.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. have pending hosts and services
2. go to the host or service badge and click on either state 0 or 99 to make the placeholder appear
3. click on the state 99 badge
![27-10-_2020_15-56-25](https://user-images.githubusercontent.com/34264690/97322487-2456bc80-1870-11eb-8267-128d3bb0344d.png)
4. when you click on the state 0 badge after this, its color shifts
![27-10-_2020_16-04-32](https://user-images.githubusercontent.com/34264690/97322506-291b7080-1870-11eb-9551-54fc1bc49fdd.png)
5. the same goes for services
![27-10-_2020_16-02-45](https://user-images.githubusercontent.com/34264690/97322456-1bfe8180-1870-11eb-9b01-6a890467a647.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):

```
Icinga Web 2 Version
    2.7.4
Git Commit
    3ebfb5c38330d22966d24d2ace57d7eb3fb2a6db
PHP Version
    7.1.8
Git Commit Datum
    2020-08-17
Copyright
    © 2013-2020 Das Icinga Projekt 
```

* Web browser used:
`firefox, chrome and ie`

* Icinga 2 version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.6-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1160.2.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-wytxxqbb-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

```
* PHP version used (`php --version`):
```
PHP 5.4.16 (cli) (built: Oct 29 2019 09:56:22)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```

* Server operating system and version:
`RHEL 7.9`

**Comment by nilmerg** [comment]
Hi,

I can reproduce the shifting color, but which *placeholder* do you mean? Do you have picture of that as well? What view did you experience this in? Which language are you using?

**Comment by K0nne** [comment]
By placeholder I meant that square in the bottom right corner of the images. It only appears in this situation.

**Comment by nilmerg** [comment]
Ouch, now I see it. :rofl:
