### ISSUE TITLE
Scheduled Downtime can't be removed

### ISSUE THREAD

**Issue by luiscontrerasdo** [Icinga/icingaweb2#4247]
## Describe the bug
Clicking on the blue x for removing a scheduled downltime, the web assumes that is deleting it, but it doesn't return me a message if it was deleted or not.

## To Reproduce
Create a scheduled downtime, and try to remove it using web interface.

## Expected behavior
After clicking on the blue x for removing the scheduled downtime, it could be interesting to have a message about the status of the command, if it was deleted or not.

## Screenshots
Here you can see from where I clicked for removing the scheduled downtime.

![image](https://user-images.githubusercontent.com/6249657/97357271-dfcb2100-186f-11eb-9153-77a8c5b59167.png)

Here you can appreciate a message after clicking on the blue x for removing the scheduled downtime.

![image](https://user-images.githubusercontent.com/6249657/97357208-ca55f700-186f-11eb-8a83-44c872c6e9e9.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.0-rc1
* Icinga Web 2 version (System - About): 2.8.2
* Web browser: Google Chrome
* Icinga 2 version (`icinga2 --version`):  2.12.1-1
* Icinga DB version (`icingadb --version`): v1.0.0-rc1
* PHP version used (`php --version`): PHP 5.4.16
* Server operating system and version: CentOS 7

**Comment by nilmerg** [comment]
Hi Luis,

we can't do anything here unfortunately. Icinga 2 does not tell us that the removal failed (despite the log message) and Icinga Web 2 has no way to know whether the removal would be possible as it doesn't know how to differentiate downtimes created by config and downtimes created on demand.

Though, we'll make sure not to have this issue in Icinga DB Web again.
