### ISSUE TITLE
Linebreak with \n causes Problems because "\n" is a part of the Service

### ISSUE THREAD

**Issue by Nathaniel-Donahue** [Icinga/icingaweb2#4249]
## Describe the bug
We have a Problem with the linebreak of \n because we have one Service which has \n as a Part of the service output - its a part of the URL.
The Service used is [Disk SMB](https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#disk_smb) and the URL is \\servername\n$. 

## To Reproduce
The Service is Used to Monitor the Drive \n.

## Expected behavior
I would expect that it can handle the "\n" as part of a link. It should output correctly.

* Icinga Web 2 version and modules (System - About): Its an Icinga Web 2 version 2.8.2 with the Director Module
* Web browser used: any
* Icinga 2 version used (`icinga2 --version`): 2.12.1
* PHP version used (`PHP --version`): 2.7.3
* Server operating system and version: Debian 10

**Comment by nilmerg** [comment]
Hi,

please include an example link.

**Comment by Nathaniel-Donahue** [comment]
![Variabeln](https://user-images.githubusercontent.com/56820910/97692716-68300880-1aa0-11eb-871a-41a1fd94ab92.png)
![Icinga_output](https://user-images.githubusercontent.com/56820910/97692725-69f9cc00-1aa0-11eb-8444-3d29c3edc3e6.png)

**Comment by nilmerg** [comment]
Ah, thought at first you're trying to filter for output which includes a `"\n"`. Anyway, this works as intended. Any control character in its textual representation is replaced with the actual character in plugin output. This is (I believe) because Icinga already transforms newlines to `\n` so Icinga Web 2 has no way to differentiate between `\n` and `"\n"`.

**Comment by Nathaniel-Donahue** [comment]
Hi, here is proof that the problem is not Icinga 2. The Database output is correct.
```
select output  from icinga_servicestatus ss, icinga_objects o where ss.service_object_id=o.object_id and o.name1="HOSTNAME" and o.name2="SERVICENAME";
+----------------------------------------------------------------+
| output                                                         |
+----------------------------------------------------------------+
| Disk ok - 3.73G (1%) free on \\HOSTNAME\n$  |
+----------------------------------------------------------------+
´´´

**Comment by nilmerg** [comment]
Of course it is in your case. It's just a `"\n"` and not a real line break after all. I've meant that Icinga may be transforming real line breaks to `"\n"`. But even if that's not the case, it doesn't matter much. This is a behavior that has historical reasons by now, is done on purpose and as such is not a bug. There are check plugins which output a literal newline and expect that to be displayed as real newline.

I'm afraid, but there's not a correct way to handle such a case but to choose one way. And this has been the way now for several years.
