### ISSUE TITLE
View custom vars on Groups and Users

### ISSUE THREAD

**Issue by f-froehlich** [Icinga/icingaweb2#4264]
## Is your feature request related to a problem? Please describe.
I want to add multiple email addresses to an user. Therefore I have to add a new custom variable 'email_addresses' in the User object. The same I have done on a UserGroup. Everything works fine but I can't view the value of this custom variable in the icingaweb2 dashboard. The same information get lost on HostGroups and ServiceGroups. 

## Describe the solution you'd like
Create a tab to display those (and all other) information on the detail page of the User and create an detail page for Groups

## Additional context
```
object UserGroup "group" {

  vars.email_addresses = [
    "Group mail 1",
    "Group mail 2",
    "Group mail 3",
  ]

}

object User "user" {
  vars.email_addresses = [
    "User mail 1",
    "User mail 2",
    "User mail 3",
  ]
}

```

**Comment by nilmerg** [comment]
Hi,

this is not possible I'm afraid. (https://github.com/Icinga/icingaweb2/issues/4070)
