### ISSUE TITLE
Date / Time picker not visible on browser firefox

### ISSUE THREAD

**Issue by carraroj** [Icinga/icingaweb2#4279]
## Describe the bug
if your creates a downtime in icingaweb2 you are able to select the time range (start and endtime)  of the downtime, but the is the date/time picker missing. In browser chromium or chrome it is visible and available. 

## To Reproduce
Create a downtime in Chrome or in Firefox and you will see the missing picker in Firefox.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.8.2
* Web browser used: Firefox 80
* Icinga 2 version used (`icinga2 --version`):2.12
* PHP version used (`php --version`):
* Server operating system and version: CentOS 7

![Screenshot_20201120_145237](https://user-images.githubusercontent.com/25805027/99807922-7245a400-2b40-11eb-9bbd-080ca82d7430.png)
![Screenshot_20201120_145343](https://user-images.githubusercontent.com/25805027/99807937-75d92b00-2b40-11eb-9d9d-8f11140e3637.png)

**Comment by carraroj** [comment]
ref/NC/696290

**Comment by nilmerg** [comment]
I'm afraid, but this is still not supported by Firefox and hence the input is a simple text box. (#2836, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#Browser_compatibility)

Though, we intend to implement our own picker (#4107) which will hopefully be part of the next major version.
