### ISSUE TITLE
Event overview shows future events by default

### ISSUE THREAD

**Issue by lucafwp** [Icinga/icingaweb2#4280]
## Describe the bug
Event overview shows future events, like scheduled downtimes, by default.
All these future events will show up before actual or just passed events.

## To Reproduce

1. Schedule a downtime for every day in a specific timeperiod
2. Assign it to ha host with rules
3. Click on History > Event Overview

## Expected behavior
Filter should show "timestamp>=-7 days & timestamp <= now"

## Screenshots
![history_overview](https://user-images.githubusercontent.com/36190810/99970042-95b85b00-2d9b-11eb-9406-cd68b2478f44.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.8.2
director: 1.7.2
incubator: 0.5.0
ipl: v0.5.0
monitoring: 2.8.2
reactbundle: 0.7.0

* Web browser used: Chrome Version 86.0.4240.198
* Icinga 2 version used (`icinga2 --version`): 2.12.1-1
* PHP version used (`php --version`): 7.3.11
* Server operating system and version: CentOS Linux release 7.9.2009

**Comment by nilmerg** [comment]
Hi,

we won't change that in the monitoring module as showing downtimes scheduled in the future was always the default. If users are annoyed by them, they should filter them out and add this view as custom menu entry.

Though, it's already not the case in [Icinga DB Web](https://github.com/Icinga/icingadb-web) anymore. There it's an actual *history* of events, which already excludes any future events..

So this is really only a case of *it has ever been so*. In Icinga DB Web as the successor such changes have way more chances.
