### ISSUE TITLE
Weird curl behavior when quering monitoring/service/show

### ISSUE THREAD

**Issue by fl0wx** [Icinga/icingaweb2#4281]
## Describe the bug
A clear and concise description of what the issue is.

If i go to the following Icinga Page (Service Status page with added &format=json) https://ICINGAHOST/monitoring/service/show?host=HOST&service=SERVICE&format=json
i will see the complete Result in JSON format.

If i query the same url via curl, i got "{"status":"success","data":{"message":"Scheduling check.."}}" and the Check is being rescheduled.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

curl to a monitoring service:

curl -k -u USER -v -H 'Accept: application/json' "https://ICINGAHOST/monitoring/service/show?host=HOST&service=SERVICE&format=json"

## Expected behavior
I want to get the same JSON Result if i query the url via curl.

## Screenshots
-

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):  Icinga Web 2 Version 2.7.3
Modules 
director | 1.7.2
doc | 2.7.3
enforceddashboard | 0.0.0
grafana | 1.3.6
incubator | 0.5.0
ipl | v0.3.0
monitoring | 2.7.3
reactbundle | 0.7.0

* Web browser used: Chrome 84 
* Icinga 2 version used (`icinga2 --version`): r2.11.3-1
* PHP version used (`php --version`):  PHP 7.3.19-1
* Server operating system and version: Debian GNU/Linux 10 (buster)

**Comment by Al2Klimov** [comment]
The master is affected, too:

```
➜  icingaweb2 git:(master) curl -Lvu icingaadmin:icinga -H 'Accept: application/json' http://localhost:8080/icingaweb2/monitoring/service/show\?host\=test-random-2\&service\=ping4\&format\=json
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'icingaadmin'
> GET /icingaweb2/monitoring/service/show?host=test-random-2&service=ping4&format=json HTTP/1.1
> Host: localhost:8080
> Authorization: Basic aWNpbmdhYWRtaW46aWNpbmdh
> User-Agent: curl/7.64.1
> Accept: application/json
>
< HTTP/1.1 200 OK
< Date: Thu, 26 Nov 2020 17:09:28 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
< X-Powered-By: PHP/7.3.11
< Transfer-Encoding: chunked
< Content-Type: application/json
<
* Connection #0 to host localhost left intact
{"status":"success","data":{"message":"Scheduling check.."}}* Closing connection 0
➜  icingaweb2 git:(master)
```
