### ISSUE TITLE
Do not enforce dependencies on module activation

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#4284]
Dependencies are now being checked in Icinga Web, that's great. It enforces dependencies on module activation, which turns out to be problematic:

* I guess many automation tools (and custom automation) are not prepared to deal with this - we'll break their setups
* it makes it impossible to deploy specific git branches or hashes, as the dependency check will fail for modules following best practices

Dependencies for quite some modules in my setup are considered being broken, for various reasons. Here two distinct examples:

* [aws](https://github.com/Icinga/icingaweb2-module-aws/blob/master/module.info) (~fails as it depends on **any** version of the monitoring module~ -> i pulled again, this has been fixed :+1:)
* [bem](https://github.com/Thomas-Gelf/icingaweb2-module-bem) fails when running the GIT master and not a release version of the Icinga Director
* [pve](https://github.com/nbuchwitz/icingaweb2-module-pve/blob/master/module.info) fails because of a syntax error. I wouldn't blame the developer, as we had the very same error in some of our modules too

Even if the dependency syntax in the Proxmoxx VE module is going to be being fixed, it would still fail in case you're running the current master of the Icinga Director. You'll read "master" as it's version when running anything but an exact release tag.

I would suggest to only show dependency issues while not enforcing them right now. Then we can move on to find solutions for above problems:

* special treatment for the most common syntax errors (ignore the dependency, show an error)
* a solution for modules following best practices when support-branches are involved. e.b.:
  * is "master" always recent enough?
  * do we need an additional field saying "I promise, I'm newer than x.y.0" (minor releases are usually tagged in the master branch, while patch releases are tagged in the support branch)
* how to deal with automation tools? I guess many users do something like `icingaweb2::module { ['businessprocess', 'director', 'ipl' ]: ensure => installed }` or similar in their tool of choice (or custom automation script). The installation might fail because of dependency errors. At lease when they depend on `icingacli`, it works when they deal with symlinks on their own.

Enforcing restrictions is of course great for essential modules which are available as releases only, there are exactly three of them: incubator, ipl, reactbundle. For the rest, I see enforcement problematic right now.

**Comment by nilmerg** [comment]
> special treatment for the most common syntax errors (ignore the dependency, show an error)

The example you've shown is technically not a syntax error. Even if it would be, I don't see a reason why we should handle such gracefully. It's a developer that's responsible for it and and not an end-user after all.

> a solution for modules following best practices when support-branches are involved

Then we would need to define such best practices first. I was never aware of `master` being a supported *version* for our modules. We have used semantic versioning everywhere in the past, so I consider this being the established (best) practice. No need to support to such outliers IMHO.

> do we need an additional field saying "I promise, I'm newer than x.y.0" (minor releases are usually tagged in the master branch, while patch releases are tagged in the support branch)

We have no *patch* releases. These are our *minor* releases, since the true *major* version never changes. Also, Git tags are not of concern here, it's the contents of `module.info` which dictates the version of a module. The master, as being the most recent (official) state of the code, should always have the latest version in its `module.info`. Including our *special* patch (minor) releases.

> how to deal with automation tools?

That's really the only concern of you I'm with you here. Since tools use the icingacli, I'd suggest to just disable dependency checks for the `module enable` command and leave the UI checks as they are.

**Comment by Thomas-Gelf** [comment]
> The example you've shown is technically not a syntax error. Even if it would be, I don't see a reason why we should handle such gracefully. It's a developer that's responsible for it and and not an end-user after all.

I'd still prefer to be friendly to them and to make their life as easy as possible ;-)

> > a solution for modules following best practices when support-branches are involved
> 
> Then we would need to define such best practices first. I was never aware of `master` being a supported _version_ for our modules. We have used semantic versioning everywhere in the past, so I consider this being the established (best) practice. No need to support to such outliers IMHO.

This happens BECAUSE of those best practices. The Director always shows "master" and not a version after each .0 release in the master, and patch releases are tagged solely in support branches. The enforced restrictions make it impossible to activate modules for a) developers working with GIT and b) customers sponsoring features and fixes who wants to benefit from what they payed for.

> We have no _patch_ releases. These are our _minor_ releases, since the true _major_ version never changes. Also, Git tags are not of concern here, it's the contents of `module.info` which dictates the version of a module. The master, as being the most recent (official) state of the code, should always have the latest version in its `module.info`. Including our _special_ patch (minor) releases.

SemVer still applies. Don't know about other modules, but I try to follow it in all larger modules. Trying very hard to not break compatibility and to always provide a smooth upgrade path. Not concerned about _major_ versions, as that's more a marketing thing. You cannot tag patch versions in the master branch, support branches diverge after a _minor_ release. How would you tag a security fix 2.7.4 in the master with 2.8.1 already being released?

> That's really the only concern of you I'm with you here. Since tools use the icingacli, I'd suggest to just disable dependency checks for the `module enable` command and leave the UI checks as they are.

Agree on the CLI part.

**Comment by Thomas-Gelf** [comment]
> > The example you've shown is technically not a syntax error. Even if it would be, I don't see a reason why we should handle such gracefully. It's a developer that's responsible for it and and not an end-user after all.
> 
> I'd still prefer to be friendly to them and to make their life as easy as possible ;-)

NB: As mentioned in the initial comment, I wouldn't blame them for errors they committed by copying from us. We used this different syntax in various modules ([Business Process](https://github.com/Icinga/icingaweb2-module-businessprocess/commit/72f1a88f), [Jira](https://github.com/Icinga/icingaweb2-module-jira/commit/2deb5dc), I'm sure there are others) long time ago, and they never matched the code that reads our dependencies.

**Comment by nilmerg** [comment]
>  How would you tag a security fix 2.7.4 in the master with 2.8.1 already being released?

That's not the point. It's the following:

> The Director always shows "master" and not a version after each .0 release in the master

What is tagged and what not is **not** of interest if it comes to what the dependency check uses to source a module's version. It's the `module.info`.

Versions defined in this file follow semantic versioning. Not Git references. What exactly is it what the Director prevents from showing `1.7.2` there on the master? If you're so keen on keeping compatibility with older versions and other modules, isn't it possible to run the Director's master with a module requiring 1.7.2 although the master is 192 commits ahead of it?

**Comment by nilmerg** [comment]
I've now disabled dependency checks for the module enable command by default. Regarding your other objections, I'd highly recommend to use a compatible version identifier in your `module.info` such as `1.8.0-dev` or something similar.
