### ISSUE TITLE
Icingaweb2 isn’t compatible with php8.0

### ISSUE THREAD

**Issue by MacFan4000** [Icinga/icingaweb2#4287]
When trying to install icingaweb2 on php8.0 I get the below error
Uncaught ValueError: max(): Argument #1 ($value) must contain at least one element in /usr/share/icingaweb2/modules/setup/application/views/scripts/index/index.phtml:14
Stack trace:
#0 /usr/share/icingaweb2/modules/setup/application/views/scripts/index/index.phtml(14): max()
#1 /usr/share/php/Icinga/Web/View.php(248): include('...')
#2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#10 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch()
#11 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#13 {main}
thrown

**Comment by rtyler** [comment]
I can confirm, I just spotted this on 2.8.2 using the icingaweb2-php80 package on FreeBSD.

**Comment by imp1sh** [comment]
I can confirm this errors happens in FreeBSD 12.2 with php80 while it does not with php74

**Comment by sebastic** [comment]
icingaweb2 works with PHP 8 when you add the patches from #4289 & #4298, we did that for the Debian package:

 https://salsa.debian.org/nagios-team/pkg-icingaweb2/-/tree/master/debian/patches
