### ISSUE TITLE
Sometimes dashboard.ini is saved with wrong access rights, user and group

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingaweb2#4292]
## Describe the bug
Hello,

yesterday we got an issue from one of our users:
He tried to save a new dashboard. Upon saving he got the following error message:

![04-12-_2020_11-14-46](https://user-images.githubusercontent.com/34264690/101153845-3a049200-3625-11eb-9462-293d8be53359.png)
(The blurred content is a-zA-Z0-9)

After this message all of his dashboard / menu entries were gone and he was unable to save any new items.

His dashboard.ini was in the following state:

![04-12-_2020_11-36-25](https://user-images.githubusercontent.com/34264690/101154145-a089b000-3625-11eb-917f-02b7cafcf2e8.png)

The content of the dadshboard.ini was the text mentioned in the error message.
We had to change the access rights, user and group to fix this.

This is the 2nd time a user mentioned this issue.

## To Reproduce
Unknown so far. I was unable to reproduce it.

## Expected behavior
Users can save their dashboards an menu items.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version
    2.7.4
Git Commit
    3ebfb5c38330d22966d24d2ace57d7eb3fb2a6db
PHP Version
    7.1.8
Git Commit Datum
    2020-08-17
Copyright
    © 2013-2020 Das Icinga Projekt 
```

* Web browser used: 
`chrome`
* Icinga 2 version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.6-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1160.2.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-wytxxqbb-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* PHP version used (`php --version`):
```
PHP 5.4.16 (cli) (built: Oct 29 2019 09:56:22)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```

* Server operating system and version: 
`RHEL 7.9`

**Comment by nilmerg** [comment]
Hi K0nne,

please show the access rights of `/etc/icingaweb2`

**Comment by K0nne** [comment]
Hi nilmerg,

the access rights are as following:

![07-12-_2020_09-19-54](https://user-images.githubusercontent.com/34264690/101326605-cb664500-386d-11eb-87f5-fa3c0d153a84.png)

**Comment by nilmerg** [comment]
Looks fine, thanks. Though, I just noticed you're running PHP 5.4, is this (really) intentional? :laughing: Is an update to at least PHP 5.6 feasible? Just to eliminate it as possible cause, 5.4 is not supported anyway.

And, is php-fpm / apache running as root by any chance? If so, please try running it with the apache user and see if this helps.

**Comment by K0nne** [comment]
Thanks for the heads up. This is not intentional :sweat_smile: I will look into this. 
Unfortunately this will take some time.

![image](https://user-images.githubusercontent.com/34264690/101343899-f7d98b80-3884-11eb-9a2a-522a4b6bbef0.png)

All child processes are running as apache.

**Comment by K0nne** [comment]
I will close this until the error comes back with a newer php version.

**Comment by K0nne** [comment]
Offtopic:
Icingaweb2 shows in "system / about" a different used php version than mentioned in the issue tamplate.

```
Icinga Web 2 Version
    2.7.4
Git Commit
    3ebfb5c38330d22966d24d2ace57d7eb3fb2a6db
PHP Version
    7.1.8
Git Commit Datum
    2020-08-17
```
