### ISSUE TITLE
Dashlet of PNP view not refreshing

### ISSUE THREAD

**Issue by onkobu** [Icinga/icingaweb2#4296]
## Describe the bug
I added a dashlet on the dashboard with a PNP-URL. It is displayed but not refreshing. URL looks like this:

```
pnp/zoom?host=the-host.net&srv=lmsensors&view=0&source=0&start=-2 hours&graph_width=500&graph_height=100
```

I added a simple iframe-view to icingaweb2-module-pnp to wrap for forwarding to pnp4nagios:

```
<iframe src="<?= $this->url ?>" style="height: 400px; width:100%" frameborder="no"></iframe>
```

And added ZoomController.php is a copy of the existing [GraphController](https://github.com/Icinga/icingaweb2-module-pnp/blob/master/application/controllers/GraphController.php). It only wraps the query parameters with the base URL to the final URL forwarded to pnp4nagios.

The latter already supports relative time points and also omitting end implies now() as timestamp. This all works. But I need to hit dashboard's reload button to refresh the iframe/ its content.

## To Reproduce

0. fix broken parameter handling of zoom-controller in pnp4nagios locally (https://github.com/lingej/pnp4nagios/issues/177)
1. Enable module [icingaweb2-module-pnpi](https://github.com/Icinga/icingaweb2-module-pnp) icingawe2 with 
2. Setup a metric that displays a PNP graph in service/ or host details, e.g. http_check and its timing data
3. Click on magnifying glass of the graph/ zoom in/ find the pnp4nagios-URL containing /zoom
4. delete parameter end from the URL, change start to -2 hours (incl. space)
5. add URL has dashlet to the dashboard
6. wait >2mins, no updates (graph title contains timestamp)
7. Click reload-button of dashboard -> refreshes

## Expected behavior
I assume the iframe is reloaded by the page it is embedded into – easy.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): Icinga Web 2 Version
    2.8.2
Git Commit
    8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version
    7.2.34
* Web browser used: Firefox/ Any
* Icinga 2 version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.12.1-1)
* Server operating system and version: Gentoo Linux

## Additional context
I also had a variant with dynamic calculation of the iframe's src attribute. This had the same behavior: displayed the graph with no further updates. Another try involved JavaScript to reload the iframe itself. This worked but caused flickering and required a <script>-block in the view – something I expect to be triggered by the dashboard itself.

Maybe outline this in the documentation or simply answer with a link to the relevant API-docs and I'll dig in.

**Comment by nilmerg** [comment]
There's no automatic refresh active by default for dashlets. The route that serves a dashlet's content has to enable this explicitly.

In a controller's action, use this to set a refresh interval of 30 seconds: `$this->setAutorefreshInterval(30);`

The current documentation is only for general usage, not for development. Though, there's #4109 to which you should subscribe if interested.
