### ISSUE TITLE
IcingaWeb2 shows 0.00 as perfdata, even if its an error in the check and the perf value in question is empty

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingaweb2#4302]
## Describe the bug

Hello,

in a different issue I am tracking a icinga2.log warning indicating invalid perfdata ("cluster_service_status" is affected):

```
[2021-01-08 14:06:59 +0100] warning/GraphiteWriter: Ignoring invalid perfdata for checkable 'HOSTNAME!Cluster Health' and command 'by_pwsh' with value: cluster_service_status=;;4
Context:
        (0) Processing check result for 'HOSTNAME!Cluster Health'
```

When I looked in Icingaweb2 it shows me "0.00" as value, so I thought everything was fine:

![08-01-_2021_14-10-12](https://user-images.githubusercontent.com/34264690/104019235-7b0b3b80-51bb-11eb-88d3-11d7eae666f3.png)

The plugin output however shows that the value for "cluster_service_status" is missing:

` '9_status_information'=0;;2 '9_state'=0;-1;2 '12_status_information'=0;;2 '12_state'=0;-1;2 '10_state'=0;-1;2 '10_status_information'=0;;2 '11_status_information'=0;;2 '11_state'=0;-1;2 'cluster_service_status'=;;4`

## Expected behavior

I expected IcingaWeb2 to show missing Perfdata as "-" instead of  "0.00". Is this expected behaviour?

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version
    2.7.4
Git Commit
    3ebfb5c38330d22966d24d2ace57d7eb3fb2a6db
PHP Version
    7.1.8
Git Commit Datum
    2020-08-17
Copyright
    © 2013-2020 Das Icinga Projekt 
```

* Web browser used: 
`chrome`
* Icinga 2 version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.7-1)

Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1160.11.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* PHP version used (`php --version`):

I'm aware of the old PHP ^^
```
PHP 5.4.16 (cli) (built: Oct 29 2019 09:56:22)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```

* Server operating system and version: 
`RHEL 7.9`

**Comment by nilmerg** [comment]
I wouldn't call that *expected*, but it's certainly coded like this. If that's intentional or just a **very old** oversight, I can't tell, yet.
