### ISSUE TITLE
The upgrade doc should mention starttls

### ISSUE THREAD

**Issue by jwpit** [Icinga/icingaweb2#4314]
## Describe the bug

doc/80-Upgrading.md should mention that it might be necessary to change the encryption parameter from ldaps to starttls. when upgrading to 2.6.0.

**Comment by nilmerg** [comment]
Can you please elaborate on why it is necessary?

**Comment by nilmerg** [comment]
I don't want to appear impatient, but the reason it **might** be necessary really requires a reason which I'd like to hear. Thanks.

**Comment by nilmerg** [comment]
Closing because I received no response.
