### ISSUE TITLE
Introduce permissions for format=sql/json/pdf

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2#4315]
## Describe the bug

The standard module functionality can/might be used to expose more info about the underlying host/services

## To Reproduce

change https://localhost/monitoring/list/services?service_problem=1&sort=service_severity&format=pdf
to  https://localhost/monitoring/list/services?service_problem=1&sort=service_severity&format=sql or https://localhost/monitoring/list/services?service_problem=1&sort=service_severity&format=json 

In permission restrictive environments to expose more info than the previously generated pdf file itself.
The sql and json export is an underlying function which should be also be restrictable via the permission Settings.

## Expected behavior

Export Options should only expose those features they are meant to provide .. eg. pdf, csv etc.
Other unwanted export options should be selectable to minimize unwanted information gathering. 

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.8.2 Icinga Web 2 
* Web browser and version: Firefox 85 & Chrome 88
* Icinga 2 version used (`icinga2 --version`): 2.12.3

* Server operating system and version: centos 7 

ref/NC700678

**Comment by nilmerg** [comment]
Hi,

is this about a bug that access to data using any of these export methods is possible although restrictions are set up?

If yes, please contact security@icinga.com and tell us the details about it there.

If not, I absolutely don't see any reason why these export methods could expose too much information. Especially the SQL export, which shows only the query used, not any results. (And the query itself has absolutely no sensitive information, the schema is open source and so is the code generating the queries.)

If permissions are desired just to limit this functionality, well, okay. But the allegation that *more info could be exposed* without any more details on it is bad.

**Comment by Wintermute2k6** [comment]
I think the security risk lies inside the exposed query itself, more than in the already known schemata .. hypothetical you can use the so aquired information to expose other hosts which follow the same name schema which the company already uses .. but that's a hypothetical usage of information by pentesters.. maybe it will help if the developers would get in contact with the customer and listen to their concerns .. about the viewable information .. also i see this more as a feature request as a bug .. but i just raised the issue for the customer

**Comment by nilmerg** [comment]
If restriction filters are exposed by `?format=sql` this is indeed ... questionable. I thought this was already the case, but checked this just now and it's not. Not since #1943 at least. We should change that :thinking:
