### ISSUE TITLE
Make Icinga Web 2 username available for URLs

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2#4319]
## Is your feature request related to a problem? Please describe.

Not really. It could help with creating more useful urls, though.

## Describe the solution you'd like

Have the username of the current user available as variable. The first (and maybe only) use could be in the `notes_url` or `action_url`. That way users could generate user-specific links for objects.

Like

    url?viewedbyuser=$me$

## Describe alternatives you've considered

None so far, because this simply came up as a "nice to have" not to solve an actual issue.

## Additional context
Fun fact:

It is related but just in so far as it came out of a misinterpreted issue. While talking about a solution the customer ultimately didn't ask for, @Wintermute2k6 , @lippserd and me came to the discovery that what we *thought* they wanted might be handy as well.

**Comment by lippserd** [comment]
ref/NC/724890
