### ISSUE TITLE
Searching for users on ldap backend error

### ISSUE THREAD

**Issue by lucafwp** [Icinga/icingaweb2#4321]
## Describe the bug
Searching for a user on an ldap authentication backend in "Configuration >> Authentication >> Users" shows up the following error:

> vsprintf(): Too few arguments
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Exception/IcingaException.php(28): vsprintf(String, Array)
#2 [internal function]: Icinga\Exception\IcingaException->__construct(String)
#3 /usr/share/php/Icinga/Exception/IcingaException.php(41): ReflectionClass->newInstanceArgs(Array)
#4 /usr/share/php/Icinga/Web/Controller.php(87): Icinga\Exception\IcingaException::create(Array)
#5 /usr/share/php/Icinga/Web/Controller/AuthBackendController.php(62): Icinga\Web\Controller->httpNotFound(String)
#6 /usr/share/icingaweb2/application/controllers/UserController.php(64): Icinga\Web\Controller\AuthBackendController->getUserBackend(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\UserController->listAction()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#13 {main}

## To Reproduce

1. Configure a working LDAP resource
2. Go to "Configuration >> Authentication >> Users"
3. Select the LDAP user backend
4. Search for a user

## Expected behavior
The searched user should be found without the error to show up.
Also if you search first for the user and then switch on the LDAP user backend the user is found without issues.

## Screenshots
![image](https://user-images.githubusercontent.com/36190810/108846122-80430f00-75de-11eb-853c-546f4b791cf6.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.8.2
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.11.6
* PHP version used (`php --version`): 7.3
* Server operating system and version: CentOS 7.9.2009

**Comment by nilmerg** [comment]
Hi,

I can't reproduce that. Are you using a different language than `en_US`? If so, please try it with `en_US` and if it works (or it's a different error) tell me the language you've used previously.

**Comment by lucafwp** [comment]
Hi @nilmerg , no I am using en_US as language.
Do you need other debugging details?

**Comment by nilmerg** [comment]
Hm, does the name of the backend contain a percent sign?

**Comment by nilmerg** [comment]
Or a space?

**Comment by lucafwp** [comment]
Hi @nilmerg , you got it right! 
The user backend had some spaces in his name. Removing them solved the problem.

**Comment by nilmerg** [comment]
Aye, our FilterEditor probably double encodes query params :thinking:
