### ISSUE TITLE
Can't avoid an Icinga Web database

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#4334]
## Describe the bug

I don't need any database for Icinga Web itself, but nowadays it seems to require one.

## To Reproduce

![Bildschirmfoto 2021-03-15 um 19 12 34](https://user-images.githubusercontent.com/6053266/111201943-992e5700-85c3-11eb-96cb-d94e7346209b.png)
![Bildschirmfoto 2021-03-15 um 19 13 23](https://user-images.githubusercontent.com/6053266/111201948-9a5f8400-85c3-11eb-9b1c-e40ecbfb52e4.png)
![Bildschirmfoto 2021-03-15 um 19 13 36](https://user-images.githubusercontent.com/6053266/111201950-9af81a80-85c3-11eb-8251-51bf98a26ae1.png)
![Bildschirmfoto 2021-03-15 um 19 13 48](https://user-images.githubusercontent.com/6053266/111201953-9b90b100-85c3-11eb-823a-e3eebf2fe507.png)
![Bildschirmfoto 2021-03-15 um 19 13 57](https://user-images.githubusercontent.com/6053266/111201956-9b90b100-85c3-11eb-8b6d-95200ef8a10c.png)
![Bildschirmfoto 2021-03-15 um 19 14 01](https://user-images.githubusercontent.com/6053266/111201957-9c294780-85c3-11eb-8696-d0d65189c2a7.png)
![Bildschirmfoto 2021-03-15 um 19 14 18](https://user-images.githubusercontent.com/6053266/111201959-9c294780-85c3-11eb-9328-e5b84b98c073.png)
![Bildschirmfoto 2021-03-15 um 19 14 23](https://user-images.githubusercontent.com/6053266/111201962-9c294780-85c3-11eb-9dab-6a4e5d3b6acb.png)

## Expected behavior

![Bildschirmfoto 2021-03-15 um 19 16 40](https://user-images.githubusercontent.com/6053266/111202098-ca0e8c00-85c3-11eb-80ba-32127498c396.png)
![Bildschirmfoto 2021-03-15 um 19 17 06](https://user-images.githubusercontent.com/6053266/111202099-cb3fb900-85c3-11eb-93f0-0fc35ddeba09.png)
![Bildschirmfoto 2021-03-15 um 19 17 13](https://user-images.githubusercontent.com/6053266/111202101-cb3fb900-85c3-11eb-8dc9-0acea6c2844c.png)
![Bildschirmfoto 2021-03-15 um 19 17 19](https://user-images.githubusercontent.com/6053266/111202103-cbd84f80-85c3-11eb-8a52-1cb37ac2a7a0.png)
![Bildschirmfoto 2021-03-15 um 19 17 23](https://user-images.githubusercontent.com/6053266/111202106-cc70e600-85c3-11eb-867c-4be12133c8a1.png)
![Bildschirmfoto 2021-03-15 um 19 17 26](https://user-images.githubusercontent.com/6053266/111202109-cc70e600-85c3-11eb-87e9-bc9acfb6c508.png)
![Bildschirmfoto 2021-03-15 um 19 17 38](https://user-images.githubusercontent.com/6053266/111202110-cd097c80-85c3-11eb-8673-105e5d85962c.png)
![Bildschirmfoto 2021-03-15 um 19 17 46](https://user-images.githubusercontent.com/6053266/111202113-cd097c80-85c3-11eb-83a4-9cf3b728a288.png)
![Bildschirmfoto 2021-03-15 um 19 17 53](https://user-images.githubusercontent.com/6053266/111202115-cda21300-85c3-11eb-9fb6-70c6884ce0e0.png)

## Your Environment

master vs. v2.8.2 in Docker

## Additional context

https://github.com/Icinga/icingaweb2/pull/4333#pullrequestreview-612500027

**Comment by nilmerg** [comment]
Good to see that it works, as intended. (#4135)

**Comment by Al2Klimov** [comment]
![](https://i.kym-cdn.com/entries/icons/original/000/006/306/FlipTable.jpg)
