### ISSUE TITLE
Add FPM set up for SUSE to documentation

### ISSUE THREAD

**Issue by knbrende** [Icinga/icingaweb2#4335]
With version 7.4 FPM implemented the sandboxing feature of systemd to protect the /etc directory (amongst others) against write access.
This means when you run the icingaweb2 setup the check result of the config directory shows "The directory /etc/icingaweb2 is not writable".
https://github.com/php/php-src/blob/master/sapi/fpm/php-fpm.service.in
https://man7.org/linux/man-pages/man5/systemd.exec.5.html

There are 2 ways to solve the problem:
- move the config to a directory outside of /etc
- modify the service definition of php-fpm (for SLES 15: /usr/lib/systemd/system/php-fpm.service) and add the following Option:

> ReadWritePaths=/etc/icingaweb2 /usr/share/icingaweb2/public

I experienced this problem on SLES 15 SP2. I'm not sure if other distributions have the same default settings.
Please add this to the documentation. Maybe it saves someone else a few hours in the future.

**Comment by nilmerg** [comment]
Hi,

thanks for pointing this out! We'll make sure it's included in the next release.
