### ISSUE TITLE
iFrames disappear during auto refresh if the Plugin Output is collapsible

### ISSUE THREAD

**Issue by Linuxfabrik** [Icinga/icingaweb2#4339]
## Describe the bug
As soon as the Plugin Output of a Service is more than 9 lines and therefore collapsible by the "Collapse"-button on the bottom right of the output, embedded iFrames disappear during the auto refresh. The then missing HTML-element leads to unwanted CSS-formatting.
In this case, the iFrames are Grafana-Panels.

## To Reproduce

1. Make sure Icingaweb2 auto refresh is enabled (User > My Account > Enable auto refresh: True)
2. Make sure the [Grafana Module](https://github.com/Mikesch-mp/icingaweb2-module-grafana) is installed and uses iFrames (`/etc/icingaweb2/modules/grafana/config.ini`):
```
[grafana]
version = "1"
host = "example.com/grafana"
protocol = "https"
timerangeAll = "1w/w"
defaultdashboard = "Default"
defaultdashboarduid = "default"
defaultdashboardpanelid = "1"
defaultorgid = "1"
shadows = "0"
theme = "light"
datasource = "influxdb"
accessmode = "iframe"
debug = "0"
ssl_verifypeer = "0"
ssl_verifyhost = "0"
```
3. Add a command that runs the following script:
```bash
#!/usr/bin/env bash

echo '1'
echo '2'
echo '3'
echo '4'
echo '5'
echo '6'
echo '7'
echo '8'
echo '9'
echo '10'
```
4. Add a service with `Process performance data: yes` for said command.
5. Open the service in Icingaweb2 and wait for about 10s.

## Expected behavior
The iFrames should not disappear during the auto refresh.

## Screenshots
Expected:
![2021-03-24_11-04](https://user-images.githubusercontent.com/24634880/112293005-ef6d5b00-8c91-11eb-9860-5d345b2878d8.png)

Problem:
![2021-03-24_11-04_1](https://user-images.githubusercontent.com/24634880/112293022-f3997880-8c91-11eb-85e8-090926f85db8.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version 2.8.2
company     1.0.0
director    1.7.2.2020111901
grafana     1.3.6
idoreports  0.9.1
incubator   0.5.0
ipl     v0.3.0
monitoring  2.8.2
pdfexport   0.9.0
reactbundle     0.7.0
reporting   0.9.2 
```
* Web browser used: Firefox 86.0.1 (64-bit)
* Icinga 2 version used (`icinga2 --version`): 2.12.3
* PHP version used (`php --version`): 7.3.20
* Server operating system and version: CentOS 7

**Comment by nilmerg** [comment]
Hi,

something seems to mix-up the HTML there. The grafana module already has reports [about a similar issue](https://github.com/Mikesch-mp/icingaweb2-module-grafana/pull/209#issuecomment-491854871). I'll take a look at this though, to ensure it's the same.

**Comment by Linuxfabrik** [comment]
I'm not sure whether the grafana module is responsible or icingaweb itself.

**Comment by Linuxfabrik** [comment]
It **is** the "Collapse" button.

To reproduce: just let a plugin produce enough output - it does not need to be multi-lined. If the output fits into the window without the need of "Collapse", the HTML stays clean. If you make your browser window smaller so that Icingaweb switches the "Collapse" button on, the HTML is messed up.

**Output fits into browser window:**

![plugin-output-fits-into-window](https://user-images.githubusercontent.com/24634880/112319885-c909e880-8cae-11eb-8011-fd7301c81059.png)

**Browser window is too small:**

![the-same-plugin-output-does-NOT-fit-into-window](https://user-images.githubusercontent.com/24634880/112319900-cd360600-8cae-11eb-8e32-376f428b04f9.png)

**Comment by nilmerg** [comment]
Reproduced it successfully. Though, it's indeed the grafana module itself which is causing this. I've provided a fix there instead: https://github.com/Mikesch-mp/icingaweb2-module-grafana/pull/263

**Comment by Linuxfabrik** [comment]
perfect, thank you!
