### ISSUE TITLE
Default Settings config.ini hostdowntime_end

### ISSUE THREAD

**Issue by Gninieb** [Icinga/icingaweb2#4364]
## Is your feature request related to a problem? Please describe.
I would be very helpfull if it may be possible to configure the default hostdowntime in the config.ini
I have to reboot several server and the default downtime is always 1h. But I only want to have default 10 minutes. Thats enough for a reboot. 

## Describe the solution you'd like
config.ini => 
[settings]
**hostdowntime_end = PT10M**
hostdowntime_all_services = 1

## Describe alternatives you've considered
Change default setting in the webfrontend.

**Comment by cadirol** [comment]
Same here! such a default setting would be really nice!
IMHO all the input fields, should be fixed with a default setting.
99% of all downtimes, is  "reboot" the Comment. A default text would be great in this case!

**Comment by nilmerg** [comment]
We'll add the possibility to configure the downtime duration and default comment. :smiley:
