### ISSUE TITLE
Tumbleweed and icingaweb2 problem

### ISSUE THREAD

**Issue by majed17** [Icinga/icingaweb2#4375]
## Describe the bug
when visiting:
https://icinga.quesqilia.by/icingaweb2/setup
and putting the token, i get:
Cannot validate token: /etc/icingaweb2/setup.token (FileObject::__construct(/etc/icingaweb2/setup.token): failed to open stream: Permission denied)
 i am on opensuse tumbleweed
# VERSION="20210515"

sudo ls -l icingaweb2/
total 4
drwxrwx--- 1 root icingaweb2 32 May 18 13:04 modules
-rw-rw---- 1 root root       16 May 18 16:32 setup.token

i was following the procedure from:
[(https://icinga.com/docs/icinga-2/latest/doc/02-installation/#icinga2-user-interface-webserver)]
i enabled https using:
[(https://support.nagios.com/kb/article/nagios-core-configuring-ssl-tls-595.html#SUSE)]
then from here:
[(https://community.icinga.com/t/icinga-web-2-on-https/1359/4)]
icingweb2.conf looks like this:
```

Alias /icingaweb2 "/usr/share/icingaweb2/public"

# Remove comments if you want to use PHP FPM and your Apache version is older than 2.4
#<IfVersion < 2.4>
#    # Forward PHP requests to FPM
#    SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
#    <LocationMatch "^{urlPath}/(.*\.php)$">
#        ProxyPassMatch "fcgi://127.0.0.1:9000/{documentRoot}/$1"
#    </LocationMatch>
#</IfVersion>

<Directory "/usr/share/icingaweb2/public">
    Options SymLinksIfOwnerMatch
    AllowOverride None

    DirectoryIndex index.php

    <IfModule mod_authz_core.c>
        # Apache 2.4
        <RequireAll>
            Require all granted
        </RequireAll>
    </IfModule>

    <IfModule !mod_authz_core.c>
        # Apache 2.2
        Order allow,deny
        Allow from all
    </IfModule>

    SetEnv ICINGAWEB_CONFIGDIR "/etc/icingaweb2"

    EnableSendfile Off

    <IfModule mod_rewrite.c>
        RewriteEngine on
		RewriteCond %{HTTPS} off
		RewriteRule ^.*$ https://%{HTTP_HOST}%{REQUEST_URI}/$1 [R,L]
        RewriteBase /icingaweb2/
        RewriteCond %{REQUEST_FILENAME} -s [OR]
        RewriteCond %{REQUEST_FILENAME} -l [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [NC,L]
        RewriteRule ^.*$ index.php [NC,L]
    </IfModule>

    <IfModule !mod_rewrite.c>
        DirectoryIndex error_norewrite.html
        ErrorDocument 404 /icingaweb2/error_norewrite.html
    </IfModule>

# Remove comments if you want to use PHP FPM and your Apache version
# is greater than or equal to 2.4
#    <IfVersion >= 2.4>
#        # Forward PHP requests to FPM
#        SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
#        <FilesMatch "\.php$">
#            SetHandler "proxy:fcgi://127.0.0.1:9000"
#            ErrorDocument 503 {urlPath}/error_unavailable.html
#        </FilesMatch>
#    </IfVersion>
</Directory>
```

```
sudo icingacli --version
Icinga Web 2  2.8.2     
Git Commit    8a89839af94a247ee2149b2336c73b8251b477c0 
PHP Version   7.4.19    
MODULE  VERSION   
setup  2.8.2 
```

**Comment by nilmerg** [comment]
Hi,

you're not using PHP FPM, but could this still be due to systemd? Another SUSE user had a similar issue: #4335

**Comment by majed17** [comment]
hmm thanks for guiding in  the right direction. i commented the above section of fpm, enabled and started fpm, but now the setup page asks to  download a php file, and i am unable to find a right guide to properly setup fpm in tumbleweed, any ideas?

**Comment by nilmerg** [comment]
I didn't mean that you have to enable FPM, you don't. But systemd may still interfere here, check apache's systemd unit file for the mentioned attributes. Your problem may also be caused by selinux, try to disable this temporarily or set it to `permissive`.

**Comment by majed17** [comment]
well i modified apache2.service to be:

```
[Unit]
Description=The Apache Webserver
After=network.target nss-lookup.target time-sync.target remote-fs.target
Before=getty@tty1.service plymouth-quit.service xdm.service
PartOf=apache2.target

[Service]
Type=notify
PrivateTmp=true
ExecStart=/usr/sbin/start_apache2 -DSYSTEMD -DFOREGROUND -k start
ExecReload=/usr/sbin/start_apache2 -DSYSTEMD -DFOREGROUND -k graceful
ExecStop=/usr/sbin/start_apache2 -DSYSTEMD -DFOREGROUND -k graceful-stop
KillMode=mixed
TasksMax=infinity
NotifyAccess=all
ReadWritePaths=/etc/icingaweb2 /usr/share/icingaweb2/public

[Install]
WantedBy=multi-user.target
Alias=httpd.service apache.service
```
did a systemctl damon-reload
disabled fpm in apache
and sudo systemctl restart icinga2 apache2 mariadb
and generated a new token
and now the page opens agian but with the permission denied problem persisting...

**Comment by majed17** [comment]
just tried to disable and stop apparmor even though there is no entry for icinga in /etc/apparmor
and it didn't help

**Comment by nilmerg** [comment]
ooof, just noticed only root has read access to the token: `-rw-rw---- 1 root root 16 May 18 16:32 setup.token`

Your webserver user (`apache`, `httpd` or `www-data`) is simply not allowed to read this.

**Comment by majed17** [comment]
yeah i knew that and thought it was only for copying and not for checking...but i had given up, i'm trying a new linux distribution for a new attempt at icinga, but i still would be glad to know that something is fixed with it

**Comment by nilmerg** [comment]
Just install Icinga Web 2 by package ([if there is one](http://packages.icinga.com/SUSE/)) or make sure you [set `/etc/icingaweb2` correctly up.](https://icinga.com/docs/icinga-web-2/latest/doc/20-Advanced-Topics/#preparing-icinga-web-2-setup)

For future questions regarding the installation please head over to https://community.icinga.com/ first. Thank you.
