### ISSUE TITLE
Documentation - clarify supported php versions

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [Icinga/icingaweb2#4383]
## Is your feature request related to a problem? Please describe.

The documentation (https://icinga.com/docs/icinga-web-2/latest/doc/02-Installation/) currently indicates that php >= 5.6 is required. But I would like clarification whether it supports specific version of php, especially since some 7.x versions have deprecations and 8.x has even more.

consider the major changes between php versions it seems unlikely that >= 5.6 is sufficient to indicate which versions of php are actually supported

## Describe the solution you'd like
A list of major php versions supported
eg: 7.0,7.1,7.2.7.3,7.4,8.0

## Additional context
linux ubuntu 20.04

**Comment by nilmerg** [comment]
The greater or equal comparison operator is rather standard in versioning systems. It should be clear that by defining `>= 5.6` any version up to the latest is supported.

And that's the case. We may not always support the latest major out-of-the-box, but we'll always make sure we provide support for it. That's the case with the next major release 2.9 where we'll officially add support for PHP8. While still keeping support for PHP 5.6.

I don't think it's required to specifically mention every single PHP release in our documentation. The `>=` operator makes our intention perfectly clear.

**Comment by jgrammen-agilitypr** [comment]
Thank you for your reply, you have made it clear the icingaweb2 explicitly supported php versions up to 7.4. 
My issue stems from a lot of projects that claim support for >= php5.6 but were written when 5.6 or 7.0 were release and hence don't actually have support for the later versions (and really should have php >= 5.6 and php  <= 7.1).
This is actually partially true in this case, since php8.0 wont be officially supported until 2.9, but the project lists php >= 5.6

I guess there is some OS still supporting 5.6 because php official stance was it was eol january 2019. Both Ubuntu and Debian, no longer support it.
