### ISSUE TITLE
Firefox 88.0.1 issues

### ISSUE THREAD

**Issue by yibfozzy** [Icinga/icingaweb2#4385]
## Describe the bug
The list of problematic services is not updated in Firefox 88.0.1 on macOS (it's only loaded once upon login and it does not update after) and the time on the services resets every 10 seconds - e.g. for this service:

https://paste.pics/9834c0d4ad09767f2fa822ba9c9179d6

the time reaches 0m 51s and then resets to 0m 41s. The Firefox console shows the following error:

Uncaught TypeError: icinga.history is null
Uncaught Requires a node

Also, when we try to re-login using private browsing, the index page looks like this:

https://paste.pics/46e83476d8e370a2d2bac2588bf7f61d

## To Reproduce

1. Have Firefox 88.0.1 on macOS.
2. Login to Icinga Web, navigate to Problems - Service problems
3. Check if the time resets every 10 seconds and the list of services is being updates.

## Your Environment
* Icinga Web 2 version and modules (System - About):

Icinga Web 2 Version
2.8.2
Git commit
8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version
7.2.33

* Web browser used: Firefox 88.0.1
* Icinga 2 version used (`icinga2 --version`): 2.12.4-1
* PHP version used (`php --version`): 7.2.33
* Server operating system and version: CentOS Linux release 7.9.2009 (Core)

## Additional context

We have observed this bug in earlier versions of Firefox, seems like it appeared after Firefox 68.

**Comment by nilmerg** [comment]
I also have the same version of Firefox on Ubuntu 20 here and I don't have this issue. A colleague of mine is on macOS and also has the same version but doesn't have any issues either.

Please dig a bit deeper if possible to show us the actual issue if you're able to identify it. Also, please tell us which modules **plus their version** you have installed and enabled.

**Comment by yibfozzy** [comment]
The only module we have is 'monitoring':

https://paste.pics/a828bb355de59f202fe746a24fe3a9de

which is of 2.8.2 version.

Trying to dig something in logs/browser console, will post here as soon as I get more info.

**Comment by nilmerg** [comment]
Pictures are not available anymore and no further feedback followed. Closing.
