### ISSUE TITLE
Solarized dark theme: reconsider text-background contrast

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#4394]
## Describe the bug

At least unhandled critical list items and menu badges (black on red) and success notifications (didn’t-figure-out on yellow) are hard to read.

## To Reproduce

1. Switch to the solarized dark theme
2. List unhandled criticals
3. Have a look at "CRITICAL since ..." and the menu badges
4. Ack one
5. Have a look at the notification at the bottom

## Expected behavior

White on red and (let's say) black on yellow.

## Screenshots

![Bildschirmfoto 2021-06-19 um 01 33 31](https://user-images.githubusercontent.com/6053266/122624045-ca289700-d09e-11eb-844e-06415bc2f200.png)

## Your Environment

Latest stable in Docker container.

## Additional context

Wanted to take care of my eyes (dev after all), switched my IW2 theme and... was disappointed.

**Comment by Al2Klimov** [comment]
I'm afraid unhandled criticals are still black on red which is still hard to read.

Btw. consider changing font color of login page's "icinga.com" to something... better.

**Comment by nilmerg** [comment]
Oh you were talking not only about the notifications, my mistake.

Anyway, the new dark theme doesn't show critical list items any differently, so your request would match there as well. But I personally don't have any problems with the contrast of the text/background there. And if the critical box text is also white, I'd see that as too prominent, at least if it's the same *white* that is used for links.

I'll let @flourish86 decide here.

**Comment by Al2Klimov** [comment]
But the following point _was_ introduced in the new theme.

> Btw. consider changing font color of login page's "icinga.com" to something... better.

**Comment by flourish86** [comment]
> Btw. consider changing font color of login page's "icinga.com" to something... better.

See #4430

**Comment by flourish86** [comment]
> Oh you were talking not only about the notifications, my mistake.

The notifications will have a new design anyway.

### Solarized
![Screen Shot 2021-07-07 at 14 20 40](https://user-images.githubusercontent.com/6977434/124758239-aa162600-df2e-11eb-82e2-6f4d517b7a64.png)

### Default
![Screen Shot 2021-07-07 at 14 19 55](https://user-images.githubusercontent.com/6977434/124758257-ada9ad00-df2e-11eb-9d8c-d596b9133efa.png)


> Anyway, the new dark theme doesn't show critical list items any differently, so your request would match there as well. But I personally don't have any problems with the contrast of the text/background there. And if the critical box text is also white, I'd see that as too prominent, at least if it's the same _white_ that is used for links.

I completely agree with @nilmerg. It's also been this way for like forever in solarized-dark.
