### ISSUE TITLE
Dashboard setting doesn't look nice with Dark & System theme

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingaweb2#4403]
## Describe the bug
Tried the new theme dark and system mode and the dashboard names in the dashboard settings are pretty hard to see due to the background color being similar to the text color. See screenshot.

<img width="1267" alt="Bildschirmfoto 2021-06-28 um 18 20 40" src="https://user-images.githubusercontent.com/57616252/123670485-8de2fc80-d83d-11eb-8817-be00a19d20b1.png">

**Comment by flourish86** [comment]
We can close that then, right?
