### ISSUE TITLE
Group overviews don't show all hosts/services anymore if group filters are mixed

### ISSUE THREAD

**Issue by Napsty** [Icinga/icingaweb2#4404]
## Describe the bug
We have two Icingaweb2 instances for balancing and failover. Both run icingaweb 2.8.2. 
They have been running monitoring module 2.7.1 until today, because of this bug. 

As soon as the monitoring module is upgraded (e.g. the newest 2.8.2 version), hosts and their services are missing in the hostgroup view.

The role is using the following filter in the background:

```
[LAN]
users = "user1,user2,user3"
permissions  = "monitoring/command/*,module/*"
monitoring/filter/objects = "(hostgroup_name=TEAM-LAN|servicegroup_name=TEAM-LAN)"
```

## To Reproduce
1. Login with a user that uses a role with a filter
2. Go to /icingaweb2/monitoring/list/hostgroups
3. Test with monitoring module 2.7.1 and 2.8.2 and spot differences

## Expected behavior
The number of hosts and services are exactly the same.

## Screenshots

Monitoring module 2.7.1:

![image](https://user-images.githubusercontent.com/3702203/123749866-2f0d9980-d8b6-11eb-9aa6-e52e713056fd.png)

Monitoring module 2.8.2:

![image](https://user-images.githubusercontent.com/3702203/123749920-3e8ce280-d8b6-11eb-897a-7da894fce96f.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.8.2, monitoring module 2.8.2
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.12.3-1
* PHP version used (`php --version`): 7.4.3
* Server operating system and version: Ubuntu 20.04

**Comment by nilmerg** [comment]
Hi Napsty,

just tried this on my end and I can't spot a difference.

My restriction: `(hostgroup_name=backend-hosts-dev-docker|servicegroup_name=backend-services-dev-docker)`

All services which may match this are also tied to the hosts that would match. I assume this is the same in your case since you're using the same name twice?

If not, please provide a (**minimal**) example how your hosts/services are structured inside the groups that should match your restriction.

For example:

AWS Frankfurt: Only independent hosts/services (no connection to any other group than `TEAM-LAN`)
AWS Ireland: Hosts are also part of `TEAM-FOO`, services are independent
Sysmgmt LAN: Hosts are independent, services are also in groups `TEAM-BAR` and `TEAM-BLUB`

Or even better, what's the difference to Sysmgmt LAN and Sysmgmt WIS? How does they differ to the other groups? (Since they are the only groups whose counts are wrong)

**Comment by Napsty** [comment]
Thanks for your reply @nilmerg !

The host groups are built by apply rules which use custom variables:

```
# HOSTGROUPS BASED ON TEAMS
object HostGroup "TEAM-WIS" {
  display_name = "Sysmgmt WIS"
  assign where "WIS" in host.vars.team 
}

object HostGroup "TEAM-LAN" {
  display_name = "Sysmgmt LAN"
  assign where "LAN" in host.vars.team
}
```

The Host objects then contain this custom variable (array). Example for a switch:

```
object Host "aar-g1-sw-01" {
  import "host-network-prod"
  address = "10.137.250.101"
  vars.team = [ "LAN" ]
  vars.group = "Switches"
}
```

If I remove my user from that role `[LAN]` and use a role without any filter, I can see the full host group:

![image](https://user-images.githubusercontent.com/3702203/123764105-c37ef880-d8c4-11eb-820e-f2d345a97288.png)

So it must have something to do with how the filter is applied in the background.

**Comment by nilmerg** [comment]
Hey Napsty,

please also check the v2.7.2 and v2.7.3 if it shows the same problem.

**Comment by Napsty** [comment]
2.7.3 does show the same problem. 2.7.2 haven't tested yet.

**Comment by Napsty** [comment]
Tested with 2.7.2 (from https://github.com/Icinga/icingaweb2/archive/refs/tags/v2.7.2.tar.gz), same problem. 
Interesting is that the hosts actually show up - but the count in the host group overview is wrong.

![image](https://user-images.githubusercontent.com/3702203/124273049-d3564100-db3f-11eb-8bea-c661316b9994.png)

Reverted back to 2.7.1 and the count is correct again:

![image](https://user-images.githubusercontent.com/3702203/124273304-203a1780-db40-11eb-80fd-a0004d849afb.png)

**Comment by Napsty** [comment]
It's called by this commit: https://github.com/Icinga/icingaweb2/commit/1e4e878582e97bab539a6c649b6806bc15c0c8ea
I reverted the changes in modules/monitoring/library/Monitoring/Backend/Ido/Query/HostgroupQuery.php and tadaaaa:

![image](https://user-images.githubusercontent.com/3702203/124278693-de609f80-db46-11eb-92fc-e37428a1018c.png)

**Comment by nilmerg** [comment]
I think I've reproduced it successfully. The hostgroup query since v2.7.2 doesn't find hosts (and thus services) that have services which are not in any group, as long as a filter on `servicegroup_name` is present.

Gonna attempt to fix this now...

**Comment by nilmerg** [comment]
@Napsty Please try the linked PR :smiley:

**Comment by Napsty** [comment]
Re-Enabled 2.8.2 again. Hostgroups overview:

![image](https://user-images.githubusercontent.com/3702203/124478399-6e038980-dda5-11eb-99f2-8ac27d94791e.png)

With applied PR #4424 :

![image](https://user-images.githubusercontent.com/3702203/124478729-c76bb880-dda5-11eb-9199-daf21efb6407.png)

Well done! Thanks!
