### ISSUE TITLE
Login page: The input and the focus element are difficult to identify

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingaweb2#4414]
## Describe the bug
The input text is difficult to read and the focused area is difficult to identify because of the same background and border color.

![Screenshot 2021-07-01 at 11 05 08](https://user-images.githubusercontent.com/54990055/124111329-74be9380-da69-11eb-9413-d5c09cf32000.png)

**Comment by Yonas-net** [comment]
<img width="723" alt="Bildschirmfoto 2021-07-01 um 16 34 49" src="https://user-images.githubusercontent.com/57616252/124142681-b875c500-da8a-11eb-8829-242c6b66189a.png">

**Comment by Yonas-net** [comment]
**Note**:
This issues only appears in the `disable-dark-theme` branch. https://github.com/Icinga/icingaweb2/pull/4406
