### ISSUE TITLE
Make theme loading visible after theme has been changed

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingaweb2#4417]
## Describe the bug
After selecting a theme and pressing the button "Save for current session" or "Save to preferences", CSS is reloaded in the background but, depending on the browser, is not visible to the user.
* Safari has no delay and does it well.
* Chrome displays the small loading icon near the "Save for current session" button for a few milliseconds and nothing changes. After a few seconds, the theme loads automatically.
* Firefox also shows the same behaviour, but the theme does not load automatically. You have to reload/update the page to load the theme.

## Suggestion
we can show the icinga loading icon animation while loading the theme.

**Comment by nilmerg** [comment]
> Safari has no delay and does it well.

I'm impressed, for once.

> Chrome displays the small loading icon near the "Save for current session" button for a few milliseconds and nothing changes. After a few seconds, the theme loads automatically.

That's probably due to your host's performance. I have it sometimes as well, but then my fans are at 100% as well. Web runs on servers with more resources usually, so I don't think that's a real issue.

> Firefox also shows the same behaviour, but the theme does not load automatically. You have to reload/update the page to load the theme.

I. hate. Firefox. At what is this god damn browser actually good at? So that's really a bug. I need to revert 1c7e5b31b to fix this.... :sob:

**Comment by sukhwinder33445** [comment]
I have rebased the `disable-dark-theme` branch with master. 

Now changing the theme works fine. But when I switch back to a theme that is saved in the preferences, I have to manually reload/update the page to load the theme. (tested on Safari, Firefox and Chrome)

**Comment by nilmerg** [comment]
I've pushed a fix. Please test again.

**Comment by sukhwinder33445** [comment]
Working fine now 😄  👍🏽 .
