### ISSUE TITLE
Restrictions: Restricting to specific objects doesn't work correctly

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingaweb2#4422]
## Describe the bug
Have just tried several times to restrict to certain objects using and without wildcards, though couldn't get what I was expecting to see.

So my host list, without restriction looks like this and now want to restrict the view only to the ``docker-master`` host.

<img width="1264" alt="Bildschirmfoto 2021-07-05 um 12 21 16" src="https://user-images.githubusercontent.com/57616252/124456873-823a8d00-dd8b-11eb-937b-088f472fc8c7.png">

Add restrictions:

<img width="844" alt="Bildschirmfoto 2021-07-05 um 12 23 11" src="https://user-images.githubusercontent.com/57616252/124457136-c62d9200-dd8b-11eb-943a-7ec9fb079303.png">

After this restricts, all my dummy hosts should be gone, right? But nothing is filtered at all and the view is completely empty now.

<img width="1267" alt="Bildschirmfoto 2021-07-05 um 12 28 28" src="https://user-images.githubusercontent.com/57616252/124457796-831fee80-dd8c-11eb-8314-27a867acd8ee.png">

**Comment by nilmerg** [comment]
Remove the quotes and it should work. You don't need any quotes in the filter syntax unless they're actually part of what you're filtering for.

**Comment by Yonas-net** [comment]
Thanks! is working now.
