### ISSUE TITLE
Event Overview: Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingaweb2#4423]
## Describe the bug
In the Event Overview, an exception is raised when you increase the limit control from 25 to 500 and sometimes also when you press "Load more" afterwards (after you have increased the limit control to 500). See screenshot!

<img width="1440" alt="Bildschirmfoto 2021-07-05 um 13 39 24" src="https://user-images.githubusercontent.com/57616252/124466700-28d85b00-dd97-11eb-9828-228d175e3e16.png">

**Comment by nilmerg** [comment]
Well, that's nothing we can control. It's you who chooses such a high limit with a small macbook and a database running in parallel with another database, multiple web servers and icinga 2 + icingadb. Real installations requiring such a high limit to work run on waaaay beefier platforms.

If it happens with a limit of 25 or 100, we'd have a problem. But not with a limit of 500. (Especially not in the event overview)

**Comment by Yonas-net** [comment]
I actually was going to test it as some kind of benchmark but if you say that the problem is only on my end, then so be it!
