### ISSUE TITLE
Consider to jump to settings of just enabled module

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#4427]
## Is your feature request related to a problem? Please describe.

After clicking _enable_ for a module I have to click the module itself again and then one of its config tabs.

## Describe the solution you'd like

After clicking _enable_ for a module I jump immediately to its first config tab (if any).

## Describe alternatives you've considered

After clicking _enable_ for a module I stay on the same view.

**Comment by Al2Klimov** [comment]
Which of my suggestions did you implement in #4428 ?

**Comment by nilmerg** [comment]
The previous state, the alternative.

**Comment by Al2Klimov** [comment]
Isn’t the suggested solution an option, at least for the future?

**Comment by nilmerg** [comment]
No, changing the view without clear intention of the user isn't good UX. If at all, it's running the module's wizard (if it has one) upon activation.
