### ISSUE TITLE
Add option to disable login page animation. Causes high CPU load.

### ISSUE THREAD

**Issue by virtualdreams** [Icinga/icingaweb2#4437]
## Describe the bug
Add option to disable animation of the login page. Causes high CPU load, especially in rdp sessions. Input extremely slow and delayed.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.0
* Web browser used: Firefox 78.11esr
* Icinga 2 version used (`icinga2 --version`): r2.12.4-1
* PHP version used (`php --version`): 7.3.29-1~deb10u1
* Server operating system and version: Debian 10

**Comment by log1-c** [comment]
Can confirm.

Also it overlays our own company theme:
![image](https://user-images.githubusercontent.com/24474580/125453029-ad671eb6-56ba-4bd3-8795-6fd15152225f.png)

**Comment by nilmerg** [comment]
Regarding the company theme you have to hide the animated items yourself, I'm afraid.

**Comment by Thomas-Gelf** [comment]
I feel with you, v2.9 broke every company theme I ever did :see_no_evil: . The good news: first quick fixes are easy. You can for example get rid of those pulsating orbs by adding the following to your theme:

```
.orb { display: none; }
```

CPU load probably depends on your GPU, but for remote sessions animated backgrounds are of course not helpful at all. We faced this issue long time ago with the Winter theme, but that's an optional theme. For some of my simpler themes above fix was sufficient.

Others will still need some love, this depends on your level of customization. Color variable names have been changed quite a bit, so if you adjusted more than just `@icinga-blue` you might face color inconsistencies here and there - especially in the menu. Apart from this, most "content-related" styling should continue to work. The login page is definitively the part that changed the most.

Cheers,
Thomas

**Comment by virtualdreams** [comment]
The high CPU usage does not only occur in RDP sessions. I also have the same problem in Firefox under Linux. One core is completely utilized.
