### ISSUE TITLE
"Stay logged in" does not work after upgrading to 2.9.0

### ISSUE THREAD

**Issue by m-erhardt** [Icinga/icingaweb2#4438]
## Describe the bug
the follwing error is displayed when either enabling the "Stay logged in" switch on the logon screen or going to "System" -> "User Sessions" after logon

```
SQLSTATE[HY000] [2002]

#0 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(146): PDO->__construct()
#1 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(161): ipl\Sql\Connection->createPdoAdapter()
#2 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(399): ipl\Sql\Connection->connect()
#3 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(418): ipl\Sql\Connection->prepexec()
#4 /usr/share/php/Icinga/Web/RememberMe.php(301): ipl\Sql\Connection->select()
#5 /usr/share/icingaweb2/application/controllers/ManageUserDevicesController.php(42): Icinga\Web\RememberMe::getAllUser()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\ManageUserDevicesController->indexAction()
#7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#9 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#10 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#11 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#12 {main}
```
```
PDO::__construct(): Cannot connect to MySQL by using SSL

#0 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(146): PDO->__construct()
#1 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(161): ipl\Sql\Connection->createPdoAdapter()
#2 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(399): ipl\Sql\Connection->connect()
#3 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(418): ipl\Sql\Connection->prepexec()
#4 /usr/share/php/Icinga/Web/RememberMe.php(301): ipl\Sql\Connection->select()
#5 /usr/share/icingaweb2/application/controllers/ManageUserDevicesController.php(42): Icinga\Web\RememberMe::getAllUser()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\ManageUserDevicesController->indexAction()
#7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#9 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#10 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#11 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#12 {main}
```

## To Reproduce
* Upgrade from 2.8.2 to 2.9.0
* Run schema upgrade `/usr/share/doc/icingaweb2/schema/mysql-upgrades/2.9.0.sql`
* the DB connection works find and the schema upgrade worked

## Screenshots
**Test of DB connection**
![image](https://user-images.githubusercontent.com/43481037/125447069-0a51200c-0542-431d-aace-24460838d378.png)

**DB schema**
![image](https://user-images.githubusercontent.com/43481037/125447227-01d6907a-a4ab-4be6-be8b-d7e6a60f5a6b.png)

## Your Environment
* PHP version used: 7.4.6
* Server operating system and version: Rocky Linux 7.4
* MariaDB Server 10.5.11

![image](https://user-images.githubusercontent.com/43481037/125446855-1cb15131-4f87-4490-afbd-cfd88cef985e.png)
![image](https://user-images.githubusercontent.com/43481037/125446887-8c31f8d1-950f-48ea-935f-78d98412f6e4.png)

**Comment by log1-c** [comment]
Same here.

SQL error is
`SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: ''`
A refresh of the page brings you to the correct page after the login

![image](https://user-images.githubusercontent.com/24474580/125452014-50f115ec-0b6b-4cc1-9f2b-d8346998f0d6.png)

**Comment by 69teen** [comment]
Have the same issue. Using Centos 7 with Postgres
![image](https://user-images.githubusercontent.com/76161836/125461220-3718f047-ac63-4b6f-9b6e-a43c4b4aa6a6.png)

**Comment by log1-c** [comment]
Thx for the quick reply. Never would have thought of that. Works now

**Comment by nilmerg** [comment]
@m-erhardt Please add the message of the first error in the OP. It's missing.

@69teen Have you the same problem as the OP or as @log1-c?

**Comment by m-erhardt** [comment]
@nilmerg  I'm not quite sure what message you mean, both errors are in the initial report.
`SQLSTATE[HY000] [2002]`
`PDO::__construct(): Cannot connect to MySQL by using SSL`
![image](https://user-images.githubusercontent.com/43481037/125582095-6daf223b-ea0e-4788-a430-83fe025f3659.png)

**Comment by nilmerg** [comment]
Huh, I expected a message after `SQLSTATE[HY000] [2002]`, but that seems to be swallowed or so.

**Comment by 69teen** [comment]
@nilmerg With Postgres Database problem looks like (when i've opened https://icingaweb2/manage-user-devices)
![image](https://user-images.githubusercontent.com/76161836/125588923-0269750e-d3eb-4822-b9e7-4dcf19617962.png)

I've solved it by commenting charset option in the resources.ini file (/etc/icingaweb2/resources.ini), it was empty.

**Comment by nilmerg** [comment]
@m-erhardt Have you configured to disable certificate verification for the resource in question? If so, please adjust the `/etc/icingaweb2/resources.ini` by hand and change `ssl_do_not_verify_server_cert` to `"0"`. And then test again, though make sure you're already on the user device list, as this will **enable** certificate verification for all other views. After the test you should change that back to `"1"` :wink:

**Comment by m-erhardt** [comment]
@nilmerg No, I do not have disabled the verification of the server certificate, the resource for the Icingaweb2 DB currently looks like this:
```
[icingaweb2_db]
type = "db"
db = "mysql"
host = "aaa.bbb.ccc.com"
port = "3306"
dbname = "icingaweb2"
username = "icingaweb2"
password = "***"
charset = ""
use_ssl = "1"
ssl_do_not_verify_server_cert = "0"
ssl_key = ""
ssl_cert = ""
ssl_ca = "/etc/pki/tls/certs/chain.pem"
ssl_capath = ""
ssl_cipher = ""
```

**Comment by nilmerg** [comment]
Hm, please still test what happens if you remove `ssl_do_not_verify_server_cert = "0"` (it defaults anyway to `false`) from the config or if set to `"1"`. I still have the suspicion that this the issue.

And remember to also remove `charset = ""`, otherwise you'll get the same error as the other two as well. :)

**Comment by m-erhardt** [comment]
@nilmerg 
I've comepletely removed the `charset` and `ssl_do_not_verify_server_cert` parameters from the icingaweb2 DB resource now.
Unfortunately I still get the exact same error message.

As the rest of Icingaweb2 still works normal (everything besides "Stay logged in"-switch and "System"->"User sessions") I've had a closer look at the DB.
The only obvious difference between the tables that I see is that all tables within the DB are using charset/collation `utf8` whilst `icingaweb_rememberme` is using `utf8mb4`.

**Comment by nilmerg** [comment]
Yeah, but why should the charset lead to an error related to SSL? :thinking: 

The "Stay logged in" content is also accessed by [a different database library](https://github.com/Icinga/ipl-sql) than all the other views in Icinga Web 2. So the issue might indeed be there, I just don't know where I should look elsewhere now. Will have to dig deeper I guess..

**Comment by lippserd** [comment]
In IPL we use `isset` instead of a simple` if` for the configuration options. In this way we set the empty string for the MySQL options, which obviously fails. @m-erhardt Until we fix this, you can remove all configuration statements with an empty string as a value.

**Comment by lippserd** [comment]
Please see Icinga/ipl-sql#42.

**Comment by m-erhardt** [comment]
@lippserd 

Thanks, great job! I can confirm that removing the empty parameter strings in the DB ressource configuration fixed the Issue!
