### ISSUE TITLE
Nested custom variables are flattened

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2#4439]
## Describe the bug
customvars array is not processed correctly in icingaweb2

## To Reproduce
create an data field array in icinga director.
add it to a service
fill it with values
deploy it.

In this case "user"
after deploy you get:
object Host "thishost" {
    import "node"

    address = "xxx.xxx.xxx.xxx"
    vars["_override_servicevars"] += {
        apt = {
            user = [ "nico", "lisi" ]
        }
    }
}

icingaweb2 shows:
Custom Variables
0	nico
1	lisi
user

printing the array customvars shows that the user part is empty but the values there
Array ( [0] => nico [1] => lisi [user] => )

## Expected behavior
Custom Variables
user: nico, lisi

Array ([user] =>["nico","lisi"] )

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9
* Icinga Director version 1.8.1
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.12.4-1
* PHP version used (`php --version`): 7.4
* Server operating system and version: Ubuntu 20.4

## Additional context

was working back in 2.8.2
![customvars2](https://user-images.githubusercontent.com/29682206/125477574-980bb2cf-c60f-4bcb-a9cc-4e5db0c17a28.PNG)

broken in 2.8.3, 2.9
![customvars](https://user-images.githubusercontent.com/29682206/125474772-d1575b14-f163-4f9f-b60e-976406ceccbd.PNG)

**Comment by nilmerg** [comment]
Thanks for the report! I already made a fix. Needs further testing though because it's been introduced as part of the fix for [GHSA-2xv9-886q-p7xx](https://github.com/Icinga/icingaweb2/security/advisories/GHSA-2xv9-886q-p7xx). As such it also needs to be backported to v2.7 and v2.8 again. :roll_eyes:

**Comment by moreamazingnick** [comment]
thanks for the quick fix, i updated the Monitoring object according to your patch. the service view is fine now, but the host view looks strange
![hostcustomvars](https://user-images.githubusercontent.com/29682206/125485663-bc79f3e9-6579-4701-b655-b6275b5c8f6a.PNG)

**Comment by abaumgaertner** [comment]
Comparison host / service icingweb2

v2.8.2

![icingaweb2-2 8 2](https://user-images.githubusercontent.com/11097052/125505762-a512ae8f-287a-4215-80ba-d739cdb5ac5c.jpg)

v2.9.0 with patch #4440

![icingaweb2-2 9 0-with-patch](https://user-images.githubusercontent.com/11097052/125505862-4df3e49a-4a08-4d80-a07b-760af879e1af.jpg)

Custom Vars on Host Level look fine with patch. Service Level is still flat.

**Comment by nilmerg** [comment]
Looks fine on my end in both cases: (left is a host, right is a service)

![Screenshot from 2021-07-14 09-54-21](https://user-images.githubusercontent.com/16668527/125584991-68710ec5-b000-45a0-852b-2ed780b6340d.png)

@abaumgaertner The `config` property of your service seems to be JSON, not a map.

**Comment by abaumgaertner** [comment]
yes - JSON both on Host and Service. Should I open a seperate ticket then?
Custom Vars in JSON are based on dictionaries feature in Director.

**Comment by nilmerg** [comment]
Yep. v2.8.2 doesn't detect this as JSON either, so this is a different topic.

**Comment by nilmerg** [comment]
Finished my tests. Custom variable protection rules were not affected by this and still function correctly without the patch. So it's only a rendering issue, which the patch solves as shown in my screenshot above.

If any of you, with the patch applied, still have problems then please show screenshots and the respective cv configuration.

**Comment by abaumgaertner** [comment]
> Yep. v2.8.2 doesn't detect this as JSON either, so this is a different topic.

2.8.2 was working fine. 2.8.3 is broken.

**Comment by nilmerg** [comment]
Then please show an before and after screenshot, showing the exact same host/service. Your first two shots show entirely different objects.

**Comment by abaumgaertner** [comment]
> 
> 
> Then please show an before and after screenshot, showing the exact same host/service. Your first two shots show entirely different objects.

opened a new issue and screenshots are there in #4447
