### ISSUE TITLE
Paragraphs in Acknowledge/Downtime not possible, but in "Comment" they are

### ISSUE THREAD

**Issue by DasWiesel23** [Icinga/icingaweb2#4443]
Hello Team

Since the latest changes to icingaweb2 it is not possible to write paragraphs in the comment field of "Acknowledge" and "Downtime", but in "Comment" itself it is possible. However, it is possible to copy & paste multiline content into the non-working comment fields.

Is there a quick fix available?

Not working Acknowledge comment:
![comment_ack](https://user-images.githubusercontent.com/27570502/125507903-04765c0e-0dee-4ad5-8816-c8d46320d60a.png)

Not working downtime comment:
![comment_downtime](https://user-images.githubusercontent.com/27570502/125507995-21bb5de9-7212-4d18-83a8-4b8ee21712c6.png)

Working "Comment" comment:
![comment_comment](https://user-images.githubusercontent.com/27570502/125507493-af692700-f978-4a50-8ce1-0c78da6a5620.png)

Best,
Dennis

**Comment by lippserd** [comment]
Hi,

Do you mean that the enter key ist not working?

**Comment by DasWiesel23** [comment]
Yes, enter isn't working. 
Shift + Enter is not working as well

**Comment by lippserd** [comment]
That’s a feature so that you keep comments short 😆 Does your browser report anything suspicious in the console?

**Comment by DasWiesel23** [comment]
I am getting two errors every time I switch between Acknowledge and Downtime.
I am not getting these errors on the "Comment" function.

![chromium_console](https://user-images.githubusercontent.com/27570502/125511648-06589879-ff82-4a63-b11d-014218515179.png)

**Comment by mafri27** [comment]
I only see one error at the console. But if I load the Ack/Downtime tab with activated debugger, multiline comments are working. 

```
icinga.min.js:750 Uncaught TypeError: Cannot read property 'classList' of undefined
    at HTMLInputElement.<anonymous> (icinga.min.js:750)
    at Function.each (icinga.min.js:14)
    at HTMLBodyElement.DatetimePicker.onRendered (icinga.min.js:747)
    at HTMLDocument.dispatch (icinga.min.js:15)
    at HTMLDocument.v.handle (icinga.min.js:15)
    at Object.trigger (icinga.min.js:16)
    at HTMLDivElement.<anonymous> (icinga.min.js:16)
    at Function.each (icinga.min.js:14)
    at w.fn.init.each (icinga.min.js:14)
    at w.fn.init.trigger (icinga.min.js:16)

```

**Comment by lippserd** [comment]
Can confirm that this is a problem with the new date/time picker. For acks it doesn't work if expire time is enabled and for downtimes it does not work at all. Thanks for the report!

**Comment by nilmerg** [comment]
> Can confirm that this is a problem with the new date/time picker.

Woah, I'm baffled. Speechless... :no_mouth:
