### ISSUE TITLE
Database setup should include setting UTF8

### ISSUE THREAD

**Issue by theFeu** [Icinga/icingaweb2#4446]
As far as I know the default charset for Red Hat and CentOS is still latin1 and we should add the information how to set it to UTF8 in our installation docs.

**Comment by nilmerg** [comment]
Which database are we talking about?

**Comment by Mikesch-mp** [comment]
Icingaweb2 it looks like if it is not utf8 you get now an error if you try to change settings. Some distribution or MariaDB still have latin1 as default for new databases. For myself i did it now for years with latin1, with 2.9 it has to be utf8 and also the connection collation must set to utf8, like the director database.

I also see not only the docs are missing the information how to create the database for icingaweb2 with utf8, also the setup module just executes "create database $name", maybe there should also added the collation/characte set just to make sure it is really utf8.

**Comment by nilmerg** [comment]
The default charset/collation for each table is part of the schema. And that's UTF-8. Does this not suffice or does it not work?

**Comment by Mikesch-mp** [comment]
Did not work for me, i got an connection error, first one wass that utf8 is not a .. of latin1 and when i migrated database and tables to utf i got the error that in the connect the charset is '' (empty).

**Comment by nilmerg** [comment]
Hm, that should indeed not happen. Which MariaDB version exactly is this with?

**Comment by Mikesch-mp** [comment]
It is 10.5, but i bet it hits all versions of mariadb on CentOS

**Comment by naiz0** [comment]
Hi. I have the same problem as Mikesch-mp.
I use centOS 7.9.2009 with MySQL 5.7.23, Icinga Web 2 Version 2.9.0 and PHP 7.4.20
Problem occurs only if i activate the "stay logged in" slider.
If i hit F5 im logged in.

all database are in latin1_swedish_ci
