### ISSUE TITLE
display Custom Variables containing dictionary is flattened / broken

### ISSUE THREAD

**Issue by abaumgaertner** [Icinga/icingaweb2#4447]
## Describe the bug
with 2.8.3 and 2.9.0 custom vars with dictionary content are not displayed correctly

## To Reproduce
add service to host, create custom var with dictionary content at service level

```
object Service "dummy" {
    host_name = "abcd"
    import "service_template"

    vars.filesystem = {
        "/" = {
            thr_cr = "98"
            thr_ma = "95"
        }
        "/appl" = {}
        "/appl/home" = {}
        "/boot" = {}
        "/home" = {}
        "/opt" = {}
        "/opt/it" = {}
        "/usr" = {}
        "/var" = {
            thr_cr = "98"
            thr_ma = "95"
        }
    }
}
```

## Expected behavior
screenshot from 2.8.2 - ok

![json custom var in 2 8 2](https://user-images.githubusercontent.com/11097052/125742999-9b408f77-7b2d-4e35-8f74-8b061642827c.jpg)

## Screenshots
screenshot from 2.8.3 - broken

![json custom var in 2 8 3](https://user-images.githubusercontent.com/11097052/125743015-de1acc5a-5d85-4113-b59f-202583a0777f.jpg)

screenshot from 2.9.0 - broken
![json custom var in 2 9 0](https://user-images.githubusercontent.com/11097052/125746828-81b0a1b3-8d90-4b2f-803b-178dbdd274ba.jpg)

## Your Environment
see screenshots

## Additional context
was working in 2.8.2

**Comment by nilmerg** [comment]
Hah, didn't saw the issue before my last comment in #4439.

Though, that's not JSON in the first two screenshots. It's native Icinga 2 configuration syntax and hence indeed related to #4439. It's the exact same issue.

JSON in Icinga 2 configuration would be this:

```
object Host "host_with_json_vars" {
    display_name = "Host With JSON Vars"
    check_command = "dummy"
    check_interval = 5m
    retry_interval = 1m

    vars.dummy_state = 0
    vars.issue_no = 4439
    vars.json = "{ \"arr\": [ { \"one\": 1, \"two\": 2 }, { \"three\": 3 } ], \"map\": { \"four\": 4, \"five\": 5 } }"
}
```

That's what your third screenshot shows (for which I still miss a before version) showing the `config` variable.

**Comment by abaumgaertner** [comment]
> 
> 
> Hah, didn't saw the issue before my last comment in #4439.
> 
> Though, that's not JSON in the first two screenshots. It's native Icinga 2 configuration syntax and hence indeed related to #4439. It's the exact same issue.
> 
> JSON in Icinga 2 configuration would be this:
> 
> ```
> object Host "host_with_json_vars" {
>     display_name = "Host With JSON Vars"
>     check_command = "dummy"
>     check_interval = 5m
>     retry_interval = 1m
> 
>     vars.dummy_state = 0
>     vars.issue_no = 4439
>     vars.json = "{ \"arr\": [ { \"one\": 1, \"two\": 2 }, { \"three\": 3 } ], \"map\": { \"four\": 4, \"five\": 5 } }"
> }
> ```
> 
> That's what your third screenshot shows (for which I still miss a before version) showing the `config` variable.


sorry for that mistake - updated the screenshot for 2.9.0 with JSON object - here is the definition:

`
object Service "BASE_Filesystems" {
    host_name = "avl4083t.it.internal"
    import "BASE_Filesystem_DSL_Magic_final"

    vars.debug = "1"
    vars.filesystem = {
        "/" = {
            thr_cr = "98"
            thr_ma = "95"
        }
        "/appl" = {}
        "/boot" = {}
        "/home" = {}
        "/opt" = {}
    }
}
`

**Comment by nilmerg** [comment]
Again, that's not JSON.

Have you tried applying #4440 to v2.8.3 and v2.9.0 to see if it helps?

**Comment by abaumgaertner** [comment]
JSON is rendered from dictionary at command level: return Json.encode(macro("$service.vars.filesystem$"))

**Comment by abaumgaertner** [comment]
applied [https://github.com/Icinga/icingaweb2/commit/9c740f0c19be6b61f21028c1abe509be70f05277.patch](url)

2.8.3

![json custom var in 2 8 3 with #4440](https://user-images.githubusercontent.com/11097052/125766963-5a68ffef-6309-4109-950e-6f6032d36135.jpg)

2.9.0

![json custom var in 2 9 0 with #4440](https://user-images.githubusercontent.com/11097052/125766998-00c4df81-9719-44ba-aecd-bd071bfa5426.jpg)

Thank you for the fix!
