### ISSUE TITLE
Module "ipl" is not enabled. This module is mandatory for Icinga DB Web

### ISSUE THREAD

**Issue by PrinzMonty** [Icinga/icingaweb2#4448]
I get the following message in the backend:

Module "ipl" is not enabled. This module is mandatory for Icinga DB Web

When i watch in my container, ipl is installed in version 0.6.0 under /usr/share/icinga-php/ipl

When i show with icingacli

```
icingacli module list

MODULE         VERSION   STATE     DESCRIPTION
icingadb       1.0.0-rc1 enabled   Icinga DB Web
monitoring     2.9.0     enabled   Icinga monitoring module
setup          2.9.0     enabled   Setup module
```

Backend error:

```
Uncaught TypeError: Argument 1 passed to ipl\Orm\Compat\FilterProcessor::apply() must be an instance of ipl\Stdlib\Filter\Rule, instance of Icinga\Data\Filter\FilterAnd given, called in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php on line 263 and defined in /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Compat/FilterProcessor.php:33
Stack trace:
#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(263): ipl\Orm\Compat\FilterProcessor::apply(Object(Icinga\Data\Filter\FilterAnd), Object(ipl\Orm\Query))
#1 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(245): Icinga\Module\Icingadb\Web\Controller->applyMonitoringRestriction(Object(ipl\Orm\Query))
#2 /usr/share/icingaweb2/modules/icingadb/application/controllers/ServicesController.php(67): Icinga\Module\Icingadb\Web\Controller->filter(Object(ipl\Orm\Query))
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(218): Icinga\Module\Icingadb\Controllers\ServicesCo

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```
What else I tried:

I also tried to install "ipl" manually in the container unfortunately no change.

System:
Based on Docker Compose file https://github.com/lippserd/docker-compose-icinga but i build docker-icingadb branch bugfix/cfg-segv manual.

**Comment by nilmerg** [comment]
I already wondered why you closed https://github.com/Icinga/docker-icingaweb2/issues/50 :sweat_smile: 

Though, this is indeed an issue with the docker container. Not with Icinga Web2 nor with Icinga DB Web. See https://github.com/Icinga/docker-icingaweb2/issues/46 for details.

**Comment by PrinzMonty** [comment]
Ok sorry. I just wasn't sure if it was really a problem with the docker container.

**Comment by nilmerg** [comment]
No harm done :wink:
