### ISSUE TITLE
Don't open links in comments in IFrames

### ISSUE THREAD

**Issue by milohb** [Icinga/icingaweb2#4449]
We are often put links to our ticket system into the comments of downtimes or acknoledgements. Since v2.9 these links loaded in an IFrame. This is a problem, because our ticket system (as do a lot of sites) does not allow loading in IFrames to prevent clickjacking.

Because our ticket system uses another sub domain (ticket.example.com) than our monitoring (monitoring.example.com) iciningaweb detects the link as external [(community thread](https://community.icinga.com/t/since-2-9-iframes-in-external-links/7763))

The links in comments should be loaded in new windows or tabs by default.

It would be an enhancement, if this could be configured: 

- This could be a switch (load in IFrames: Yes/No)
- An alternative could be a list of domains, which should be allowed or forbidden for IFrame linking.

**Comment by nilmerg** [comment]
We'll just change the default I guess.

**Comment by michaelimfeld** [comment]
This issue still seems to persist for us. We are using the "notes" field on each host to add documentation links to our docs server. 
Example:

monitoring.example.com
docs.example.com/hosts/a

I went through the code in the linked pull request an noticed that the `$useIframe` variable is always set to `true` in our case (as our linked page does not have an extension) and therefore the link is opened in an iframe regardless of `$url->isExternal()`.

**Comment by fujexo** [comment]
@nilmerg This would fix it for our instance, I can create a PR if wanted.
Probably needs some discussion as I am not fully aware of the code which uses that function.

```diff
--- LinkTransformer.php.bak     2021-12-22 08:17:46.182388043 +0000
+++ LinkTransformer.php 2021-12-22 08:23:47.203602412 +0000
@@ -61,9 +61,9 @@
         }

         if ((! isset($attr['target']) || ! in_array($attr['target'], ['_blank', '_self']))) {
-            if ($useIframe) {
+            if (($useIframe) && (! $url->isExternal())) {
                 $attr['href'] = Url::fromPath('iframe', ['url' => $url])->getAbsoluteUrl();
-            } elseif ($url->isExternal()) {
+            } else {
                 $attr['target'] = '_blank';
             }
         }
```

**Comment by michaelimfeld** [comment]
My bad, yes there is indeed: `docs.example.com/hosts/a.example.com/example`
So the `ext` would be parsed as `com/example`, right?

**Comment by nilmerg** [comment]
Nope :D, worse, it'd be `example.com/example`. We have to refine the extension detection I guess.

**Comment by michaelimfeld** [comment]
How about making it configurable globally? I suspect such a detection will always have its edge cases.

**Comment by michaelimfeld** [comment]
Alright. Well, I do not understand why the extension is a deciding factor whether a link should be opened in an iframe or not. What is/was the idea behind this?

**Comment by nilmerg** [comment]
Mainly, images. These can only be shown in an Iframe or in a new window. We've chosen the first because we deemed it more useful to have an image right next to the host/service detail for example. But now that you ask for it, I can't remember the reason why not just images are opened in Iframes. At least not with that in mind that this is not the default behavior anymore anyway. Best is probably to really only open images in Iframes, nothing else. :thinking:
