### ISSUE TITLE
Show Eventhandler in Icingaweb2

### ISSUE THREAD

**Issue by phil-or** [Icinga/icingaweb2#4453]
Would be nice to see the configured eventhandler_commands in the host/service overview and if executed in the history.

In 2017 there was already an issue for this: #2676

Any news about this feature or do we have to wait for icinga-db?

**Comment by nilmerg** [comment]
The IDO still doesn't provide enough information in this regard. So no plans here.

Icinga DB (Web) may probably show the configured event handler, but also there are no plans as of yet. (Please make a feature request over there)
Showing eventhandler events in the history is another matter, as this requires extensive changes to Icinga 2 for which there also no plans I'm afraid.

**Comment by nilmerg** [comment]
Question has been answered, closing.
