### ISSUE TITLE
Make filter method "contains" available for all searches 

### ISSUE THREAD

**Issue by phil-or** [Icinga/icingaweb2#4454]
Since we are now increasingly using "array"-custom vars, we had the problem, that in Icingaweb2 the filter method "contains" cannot be used and also "array"-custom vars are not selectable in the dropdown menu. 

In 2018 there was also an issue with my problem #3581

Any news about this or do we also have to wait for IcingaDB?

**Comment by nilmerg** [comment]
No news. Icinga DB (Web) is already capable of this. So you'll have to wait I'm afraid.

**Comment by nilmerg** [comment]
Question has been answered, closing.
