### ISSUE TITLE
icingaweb2 fails to load pages properly after update to version 2.9

### ISSUE THREAD

**Issue by dskachan** [Icinga/icingaweb2#4456]
## Describe the bug
today after updating of icingaweb2 using apt I've found out that pages are not loaded properly. 

## To Reproduce
It is difficult to say what went wrong. icingaweb2 worked as expected and after the update, I've got the pictures provided below. 
in the log of apache I've found the following error for e.g. login screen: 
```
[Fri Jul 16 07:56:18.868111 2021] [php7:error] [pid 900962] [client 192.168.88.110:49301] PHP Fatal error:  Uncaught Less_Exception_Chunk: ParseError: Unexpected input in anonymous-file-0.less on line 14424, column 1\n14422| .badge-missing { background: #ccc; }\n14423| /** END Badges **/\n14424| .badges\n14425| /** BEGIN Tiles **/\n14426| .tiles:after {\n14427|     content:''; in /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Parser.php:631\nStack trace:\n#0 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Parser.php(578): Less_Parser->GetRules(NULL)\n#1 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Parser.php(420): Less_Parser->_parse()\n#2 /usr/share/icingaweb2/library/vendor/lessphp/lessc.inc.php(129): Less_Parser->parse('\\n\\n@font-face {\\n...')\n#3 /usr/share/php/Icinga/Web/LessCompiler.php(272): lessc->compile('\\n\\n@font-face {\\n...')\n#4 /usr/share/php/Icinga/Web/StyleSheet.php(210): Icinga\\Web\\LessCompiler->render()\n#5 /usr/share/php/Icinga/Web/StyleSheet.php(248): Icinga\\Web\\StyleSheet->render(true)\n#6 /usr/share/php/Icinga/Application/webrouter.php(62): Icinga\\Web\\StyleSheet::send(true)\n#7 /usr/sha in /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Parser.php on line 631, referer: http://i2.test-network.de/authentication/login
```

## Screenshots
that is what is visible on the login screen at that moment: 
![image](https://user-images.githubusercontent.com/4593130/125900190-01a4abc1-b55c-4d75-a03c-6a2103a7bd76.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 
```
Icinga Web 2 Version
    2.9.0
Git commit
    3b0a0a78df9389c46d3a74611a8eaec2f2b3cc77
PHP Version
    7.4.3
Git commit date
    2021-07-12
Copyright
    © 2013-2021 Icinga GmbH 

Loaded Libraries
Name 	Version
icinga/icinga-php-thirdparty 	0.10.0
icinga/icinga-php-library 	0.6.0
Loaded Modules
Name 	Version
setup 	2.9.0
aws 	1.1.0
businessprocess 	2.3.0
cube 	1.1.0
director 	1.8.0
grafana 	1.3.6
incubator 	0.6.0
ipl 	v0.5.0
lazaroblanc 	1.0.0
map 	1.1.0
monitoring 	2.9.0
nagvis 	1.1.1
reactbundle 	0.8.0
toplevelview 	0.3.1 
```
* Web browser used: firefox 90.0, google chrome 91.x
* Icinga 2 version used (`icinga2 --version`): r2.12.5-1
* PHP version used (`php --version`):  7.4.3
* Server operating system and version: Ubuntu 20.04.2 LTS

## Additional context
Not the only login page is affected but all of them.

**Comment by nilmerg** [comment]
Hi,

please check the upgrading notes. They'll tell you to upgrade the businessprocess module to v2.3.1 and Icinga Web 2 is as beautiful as it always is :)

**Comment by dskachan** [comment]
Oh, cool. Thank you! 
just don't expect to have such issues if updating using `apt`
