### ISSUE TITLE
HTML Broken after update to v2.9

### ISSUE THREAD

**Issue by MagnusArias** [Icinga/icingaweb2#4458]
## Describe the bug
After updating icinga2 and icingaweb2 from verison 2.8 to newest, HTML brokes. In web console I found an error: 
`Someone messed up our responsiveness hacks, html font-family is Times New Roman`

## To Reproduce

1. yum update 
2. Refresh the Icingaweb2 webpage

## Expected behavior
Seamless upgrade to newer version

## Screenshots
![image](https://user-images.githubusercontent.com/19928923/125945846-fe6a670b-bc00-449c-ac8d-6cb6bd3ef1bb.png)

## Your Environment

* Icinga Web 2 version: 2.9
* Icinga Web 2 modules: director, bussinessprocess, x509, Grafana, vspheredb, incubator, ipl, reactbundle, fileshipper, monitoring, translation
* Web browser used: Chrome 91
* Icinga 2 version used (`icinga2 --version`): 2.12.5
* PHP version used (`php --version`): 7.3.29
* Server operating system and version: CentOS 7.9

**Comment by nilmerg** [comment]
> Seamless upgrade to newer version

No offense intended, but you're not the first with this issue... A minor version upgrade should not break. Upgrading to a major version of a software usually dictates checking any upgrading notes. No?

Please check them. Not just due to this issue. This is the case because you didn't upgrade the businessprocess module to v2.3.1.

**Comment by MagnusArias** [comment]
Upgraded businessprocess from v.2.3.0 to v.2.3.1. Problem solved... 
I thought this could be an apache/php related issue. Thank you.

**Comment by MagnusArias** [comment]
Unfortunately, it didn't helped a lot. I double-checked all the dependencies, everything seems to be correct and I still have the same problem.

#icingacli --version
Icinga Web 2  2.9.0
Git Commit    3b0a0a78df9389c46d3a74611a8eaec2f2b3cc77
PHP Version   7.3.20

MODULE     VERSION
businessprocess  2.3.1
company          1.0.0
director         1.8.1
doc              2.9.0
elasticsearch    1.0.0
fileshipper      1.1.0
grafana          1.3.2
incubator        0.6.0
monitoring       2.9.0
reactbundle      0.9.0
vspheredb        1.0.3
x509             1.0.0

I also checked if PHP Library and ThirdParty packages are installed. Yes, they are installed. Tested both on HTTP and HTTPS. No firewall is blocking, no SELinux running (temporarily). Disabling and removing some modules also doesn't improve anything.

**Comment by nilmerg** [comment]
Please disable one module at a time and re-test. There must be another faulty module.

**Comment by MagnusArias** [comment]
Disabling them one by one changes nothing. I will try to disable all modules at once and test it once again.

**Comment by lippserd** [comment]
Could you share the output of the URL `icingaweb2/css/icinga.min.css` please?

**Comment by MagnusArias** [comment]
Yes, sure.
`
Fatal error: Uncaught Less_Exception_Compiler: .code is undefined in anonymous-file-0.less in /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Mixin/Call.php:143 Stack trace: #0 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(143): Less_Tree_Mixin_Call->compile(Object(Less_Environment)) #1 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(86): Less_Tree_Ruleset->EvalMixinCalls(Object(Less_Tree_Ruleset), Object(Less_Environment), 2) #2 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(91): Less_Tree_Ruleset->compile(Object(Less_Environment)) #3 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(91): Less_Tree_Ruleset->compile(Object(Less_Environment)) #4 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Parser.php(185): Less_Tree_Ruleset->compile(Object(Less_Environment)) #5 /usr/share/icingaweb2/library/vendor/lessphp/lessc.inc.php(130): Less_Parser->getCss() #6 /usr/share/php/Icinga/Web/LessCompiler.php(272): lessc->compile in /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Mixin/Call.php on line 143`

**Comment by nilmerg** [comment]
Ah, you should upgrade the vspheredb module as well. At least to v1.0.4.

**Comment by MagnusArias** [comment]
Upgraded vsphere DB from v1.0.3 to v1.1.0. Worked like a charm. Thank you once again!
