### ISSUE TITLE
After updating to 2.9.0 the service_contact via addColumns creates an error

### ISSUE THREAD

**Issue by Tqnsls** [Icinga/icingaweb2#4464]
## Describe the bug
We use several custom dashboards as first page for our customers, many of them with addColumns like 
"addColumns=host_address,host_notes,service_contact".
Unfortunately the Column "service_contact" is not working anymore. It is not that it is spelled wrong (then the error were "Got invalid column: service_contacts"), we get an error that a column in the sql statement is unknown.
![image](https://user-images.githubusercontent.com/67681686/126288977-1cb998c7-66fe-40c3-bea6-2350bb59e60d.png)

host_contact is still working..

## To Reproduce
Just open `/icingaweb2/monitoring/list/services?sort=host_display_name&limit=10&addColumns=host_address%2Chost_notes,host_contact`, this will work.

Add ",service_contact"
`/icingaweb2/monitoring/list/services?sort=host_display_name&limit=10&addColumns=host_address%2Chost_notes,host_contact,service_contact`
--> Link broken

This also fails via CLI
`icingacli monitoring list services --host <HOSTNAME> --format csv --columns "host,service,service_contact"`

## Expected behavior
No errors :)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

Icinga Web 2 Version 2.9.0
Git commit 3b0a0a78df9389c46d3a74611a8eaec2f2b3cc77
PHP Version 7.3.20
Git commit date 2021-07-12
   
Loaded Libraries
Name	Version
icinga/icinga-php-thirdparty	0.10.0
icinga/icinga-php-library	0.6.0

Loaded Modules
Name	Version
audit	1.0.1
businessprocess	2.3.0
cube	1.1.0
director	1.8.0
fileshipper	1.1.0
globe	1.0.4
graphite	1.1.0
idoreports	0.9.1
incubator	0.6.0
ipl	v0.5.0
map	1.1.0
monitoring	2.9.0
pdfexport	0.9.1
reactbundle	0.9.0
reporting	0.9.2
trapdirector	1.0.7a
vspheredb	1.1.0
x509	1.0.0

* Icinga 2 version used (`icinga2 --version`): 2.12.5-1
* Server operating system and version: RHEL 7.9

**Comment by Tqnsls** [comment]
I also found https://github.com/Icinga/icingaweb2/issues/4384, service_contact is still noted as available, so that might be wrong, too ( icingaweb2 > v.2.9.0).

**Comment by nilmerg** [comment]
That's a result of the fix for #4238.
