### ISSUE TITLE
'The filter column "*" is not allowed here' error for host/service problems badges

### ISSUE THREAD

**Issue by pprkut** [Icinga/icingaweb2#4469]
## Describe the bug
In the sidebar, both host and service problems show a purple badge with count 1, which does not match the actual problem count. When hovering the badge the popup says `The filter column "*" is not allowed here`.

## To Reproduce

Sorry, I have no idea :(
It appeared one day and I have no idea how to track down where this is even coming from

## Expected behavior
Badge should show actual problem count

## Screenshots
![Screenshot_20210721_094717](https://user-images.githubusercontent.com/56635/126451473-31c7e34b-67e3-4af5-a7e7-468ec3434a2c.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):

Icinga Web 2 2.9.0

Modules:
- audit 1.0.1
- aws 1.1.0
- businessprocess 2.3.1
- cube 1.1.0
- director 1,8,1
- incubator 0.6.0

* Web browser used: Firefox 89
* Icinga 2 version used (`icinga2 --version`): 2.12.5-1
* PHP version used (`php --version`): 7.4.20
* Server operating system and version: CentOS 7.9.2009

**Comment by nilmerg** [comment]
You should check your `monitoring/filter/objects` restriction.

**Comment by pprkut** [comment]
Ah, indeed. That was it. Thanks! :)
