### ISSUE TITLE
Migration of preferences from INI to Database

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2#4471]
## Is your feature request related to a problem? Please describe.
Icinga Web 2 2.9.0 is deprecating the backend INI for preferences, but the data are not migrated to the Database. In a bigger environment this would mean many users losing their preferences when switch the backend or additional custom work to migrate the data.

## Describe the solution you'd like
Icinga Web 2 should provide a migration command to migrate the data. This should be run automatically or if manual execution is required included in upgrading docs. Also the command should be available at least in a version before the backend gets removed, so testing and in case of problems a fallback is possible.

## Describe alternatives you've considered
Scripting this would be rather complicated, as you need the user from the directory name and section, name and value from the ini file. Furthermore you would perhaps need to query the database and switch between insert and update.

## Additional context
Also modules like map can have their preferences in INI or the database, so it should be as generic as possible, as there could be other modules including custom ones we do not know which use preferences.

**Comment by nilmerg** [comment]
> Also modules like map can have their preferences in INI or the database, so it should be as generic as possible, as there could be other modules including custom ones we do not know which use preferences.

That's not our concern. The deprecation only affects the storage location of Icinga Web 2 preferences. Not the storage of config in INI files by modules.

**Comment by Al2Klimov** [comment]
@nilmerg Please let me know once there's a solution, so I can use it in Docker before you release v2.9.1.

**Comment by dgoetz** [comment]
It should be concerned as it is only another section in the preferences and not a different file. 

You can see what I mean at https://github.com/nbuchwitz/icingaweb2-module-map/blob/master/doc/03-Exploring-the-map.md#user-specific-overrides , so map is using the section map and can have all the general settings there as user specific override.

**Comment by nilmerg** [comment]
Ihäh, I just looked at the code, and that is only accessing the INI file. There's no form that saves prefs to the database and our preferenceform is not hookable. So the only way users are able to use the db in the map module for its preferences is to manually insert values in the database?

Thanks for showing me this...
