### ISSUE TITLE
After upgrade opensuse 15.2 -> 15.3 login page not displayed

### ISSUE THREAD

**Issue by plivnik** [Icinga/icingaweb2#4476]
## Describe the bug
After upgrade opensuse 15.2 -> 15.3 login page not displayed. Only error message

## To Reproduce
Open http://127.0.0.1/icingaweb2/authentication/login

## Expected behavior
Login dialog

## Screenshots
Fatal error: Uncaught ErrorException: Uncaught ErrorException: include(): \Icinga\Web\ViewStream::stream_set_option is not implemented! in /usr/share/php/Icinga/Web/View.php:262 Stack trace: #0 /usr/share/php/Icinga/Web/View.php(262): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'include(): \\Ici...', '/usr/share/php/...', 262, Array) #1 /usr/share/php/Icinga/Web/View.php(262): include() #2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...') #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render(NULL) #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('error/error.pht...', NULL) #5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render() #6 /usr/share/icingaweb2/library/vendor/Zend/Controller in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 259

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
Icingaweb2 2.7.4-bp153.11 from https://packages.icinga.com/SUSE/15.3/release/
* Web browser used: Firefox 78.12.0esr, Opera 77.0.4054.146
* Icinga 2 version used (`icinga2 --version`): r2.12.4-1
* PHP version used (`php --version`):
PHP 7.3.10 (cli) (built: Oct  4 2019 21:49:02) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
* Server operating system and version:
 Platform: openSUSE Leap
  Platform version: 15.3
  Kernel: Linux
  Kernel version: 5.3.18-59.16-default
  Architecture: x86_64

## Additional context
??? php upgraded to 7.4 ???

**Comment by nilmerg** [comment]
Hi,

If the dist-upgrade caused PHP to be upgraded to version 7.4, you also need to upgrade Icinga Web 2 to version 2.8.x. Version 2.7.x is not compatible with PHP 7.4.

Next time, please head over to our [forums](https://community.icinga.com) for these kind of questions. We'd like to focus on bugs/features on Github.
