### ISSUE TITLE
Icinga Web 2.9.1 fails completely after upgrade

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icingaweb2#4490]
## Describe the bug
Well ... it's dead, Jim.

![Screenshot 2021-07-27 at 21 13 05](https://user-images.githubusercontent.com/6815386/127214291-50a502c3-2cfe-40ad-a14f-40bc1ef23314.jpg)

## To Reproduce
Upgraded my working Icinga Web 2 2.9.0 installation to 2.9.1

## Expected behavior
The same user experience as with 2.9.0, minus issue #4439.

## Your Environment
* Web browser used:
Safari 14.1.2
Firefox 90.0.2

* Icinga 2 version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.5-2)
Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
System information:
  Platform: AlmaLinux
  Platform version: 8.4 (Electric Cheetah)
  Kernel: Linux
  Kernel version: 4.18.0-305.el8.x86_64
  Architecture: x86_64
Build information:
  Compiler: GNU 8.4.1
  Build host: runner-hh8q3bz2-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.1.1g FIPS  21 Apr 2020
Application information:
General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2
Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var
Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* PostgreSQL database backend: (PostgreSQL 12)

* PHP version used (`php --version`):
PHP 7.3.20 (cli) (built: Jul  7 2020 07:53:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.20, Copyright (c) 1998-2018 Zend Technologies

* Server operating system and version:
AlmaLinux release 8.4 (Electric Cheetah)

**Comment by peteeckel** [comment]
After running `yum -y downgrade icingaweb2`, all is well again, so it was probably the 2.9.1 upgrade that broke the installation.

**Comment by nilmerg** [comment]
Sorry, I even joked about us and PostgreSQL in the same god damn release notes. I'd like to set everything on fire now.

**Comment by peteeckel** [comment]
The problem might be that you need to tell MySQL/MariaDB about UTF-8 possibly having 4 bytes per character. PostgreSQL already knows the standard :-)
