### ISSUE TITLE
Stay Logged In - Unknown cipher algorithm

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingaweb2#4493]
Hello, 

when i open the icingaweb2 in chrome i get the error "open_ssl_decrypt(): Unknown ciper algoritm"
If I do this with Edge or Firefox I don't have this problem
I clear also the cache of chrome ! 

Firefox 87
Edge Version 92.0.902.55 
Google Chrome : Version 92.0.4515.107 (Official Build) (64-bit)

In the /var/log/message I got the error :
Jul 28 13:25:56 xxxx icingaweb2[10347]: ErrorException in /usr/share/php/Icinga/Crypt/AesCrypt.php:186 with message: openssl_decrypt(): Unknown cipher algorithm   

#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)   
#1 /usr/share/php/Icinga/Crypt/AesCrypt.php(186): openssl_decrypt(String, String, String, Integer, String, String)   
#2 /usr/share/php/Icinga/Crypt/AesCrypt.php(206): Icinga\Crypt\AesCrypt->decrypt(String)   
#3 /usr/share/php/Icinga/Web/RememberMe.php(211): Icinga\Crypt\AesCrypt->decryptFromBase64(String)   
#4 /usr/share/icingaweb2/application/controllers/AuthenticationController.php(52): Icinga\Web\RememberMe->authenticate()   
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AuthenticationController->loginAction()   
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)   
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))   
#8 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))   
#9 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()   
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)   
#11 {main}

See here extra info : 
# icinga2 --version

icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.5-1)
Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1160.31.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-505-concurrent-0
  OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
  
  
  Is this a bug or is there something i'm overlooking ?
  
  regards,
  Geert

**Comment by lippserd** [comment]
Hi,

Thanks for the report. It's a bug.

You also need to delete the Icinga Web 2 cookies in Chrome. This is related to the remember me cookie. Please do not use this feature until we have fixed the problem.

All the best,
Eric

**Comment by gbin2265** [comment]
Hello,

Ok, I'm not going to clean the cookie.
I have another browser to continue working with.

regards,
Geert

**Comment by retozeder** [comment]
Just curious, you are releasing a new feature which doesn't work at all? Doesn't really matter if you use Chrome, Firefox or whatever. That's a little bit unpleasant because all of our users now have that button but get a nasty error as soon as they try to log in with the "stay logged in" button switched.

**Comment by lippserd** [comment]
It’s only a problem on RHEL/CentOS 7 afaik and occurs since version 2.9.1. We‘ll release version 2.9.3 tomorrow though which fixes this issue. And no, that was of course not by intention.

**Comment by NoobyNoob1983** [comment]
This Line in `/usr/share/php/Icinga/Crypt/AesCrypt.php`
QuickFix is to change the Constructor and the `$random_bytes_len`
 
```
 public function __construct($random_bytes_len = 256 )
    {
        if (version_compare(PHP_VERSION, self::GCM_SUPPORT_VERSION, '<')) {
            //$this->method = 'AES-128-CBC';         //  Replace this with the Line Below
            $this->method = "AES-256 -CBC";
        }

        $this->key = random_bytes($random_bytes_len);
    }
```

**Comment by Thomas-Gelf** [comment]
@lippserd: in case you're not already planning to do so, I'd suggest to:

* stay away from single hard-coded cypher methods
* define a list of supported (lowercase, normalized) cypher methods, sorted by preference
* determine available methods, normalize them, pick the best one that fits
* [openssl-get-cipher-methods](https://www.php.net/manual/en/function.openssl-get-cipher-methods.php) provides some example code
* when verifying secrets, expect to get data encrypted/signed via varying methods
* test the scenario "we have get a secret  where we used X, now (after a dist-upgrade) we support only Y and Z" by tweaking supported methods. Expected outcome: deny access, clear the cookie, redirect to login

We should expect cypher method support changing in SSL libraries over time, again and again.

Cheers,
Thomas

**Comment by drapiti** [comment]
Hi guys, sorry we have opened a new issue which relates to this problem. please see "openssl_cipher_iv_length(): Unknown cipher algorithm" also. We have a fix for it also. 
Thanks.

**Comment by gbin2265** [comment]
Hello, 

i have the same problem like the case #4497 after adjusting your proposal above.

I made the adjustments as in #4497 , and everything is fine now.

I'm going to wait for the new rpm, test again, before I upgrade my production environment.

thank you for the support ! 

regards,
Geert
