### ISSUE TITLE
Tactical overview: include unknown services in counter

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#4494]
## Is your feature request related to a problem? Please describe.

In contrast to unreachable hosts unknown services aren’t just collateral damage which goes away once all down hosts are up again.

## Describe the solution you'd like

The right counter in /monitoring/tactical, its color and description includes unknown services.

## Describe alternatives you've considered

The mentioned counter falls back to unknown services if none are critical and unhandled.

**Comment by nilmerg** [comment]
Isn't it there already??

![Screenshot from 2021-08-02 10-22-21](https://user-images.githubusercontent.com/16668527/127828575-a5a9a826-945a-429b-b131-6934315800ed.png)

**Comment by Al2Klimov** [comment]
No. The counter I mentioned (and you showed) unconditionally displays the number of unhandled critical services:

https://github.com/Icinga/icingaweb2/blob/907f7826b2d49e9fc5018d288aaa671dc8c53368/modules/monitoring/application/controllers/TacticalController.php#L95

Now imagine there aren’t 15, but 0 ones, but the amount of unhandled unknown services didn’t change (967). In this case the eye-catching counter behaves like this:

![](https://cdn.vox-cdn.com/thumbor/2q97YCXcLOlkoR2jKKEMQ-wkG9k=/0x0:900x500/1200x800/filters:focal(378x178:522x322)/cdn.vox-cdn.com/uploads/chorus_image/image/49493993/this-is-fine.0.jpg)

**Comment by nilmerg** [comment]
> The right counter in /monitoring/tactical, its color and description includes unknown services.

Then please fix your wanted solution.

**Comment by Al2Klimov** [comment]
Fine.
