### ISSUE TITLE
Call to undefined function Icinga\Web\Controller\mime_content_type()

### ISSUE THREAD

**Issue by knbrende** [Icinga/icingaweb2#4503]
## Describe the bug
Fontawesome icons arent't displayed correctly

## To Reproduce
Open Configuration -> Access Control -> Select a random role

or

Press any safe button -> the alert to confirm the change will have the same problem

## Expected behavior
I guess a checkmark or a cross in the case of a failure should be visible

## Screenshots
![image](https://user-images.githubusercontent.com/80825106/128341331-71f4deec-c934-4c7d-b32f-0c5f9eef290c.png)

![image](https://user-images.githubusercontent.com/80825106/128341388-c46f0c17-f22d-422b-aac9-db01381e7198.png)

Developer Tools Chrome:
![image](https://user-images.githubusercontent.com/80825106/128341650-507ca787-c52f-46e3-8862-2ab3735bfd90.png)

Opening Link to fa-solid-900.woff2:
![image](https://user-images.githubusercontent.com/80825106/128341777-57777ce4-5886-45da-b2ea-1cb4bafff8c6.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.2
* Web browser used: Chrome 92, Firefox 90.0.2, Edge 92
* Icinga 2 version used (`icinga2 --version`): 2.13.0-1
* PHP version used (`php --version`): 7.4.6
* Server operating system and version: SLES 15 SP3

## Additional context
I already deleted the entire icingaweb2 directory and cloned the latest git version -> still not working.

**Comment by nilmerg** [comment]
Hi,

install the `fileinfo` extension for PHP and it should work.

**Comment by knbrende** [comment]
You were right: I installed the extension and the icons are shown properly now.

Did I miss this part in the docs?

**Comment by nilmerg** [comment]
Nope, it's missing.
