### ISSUE TITLE
Call to undefined method Icinga\Protocol\Ldap\LdapConnection::getDbAdapter() in /usr/share/php/Icinga/User/Preferences/Store/DbStore.php:89

### ISSUE THREAD

**Issue by paladox** [Icinga/icingaweb2#4505]
## Describe the bug
When running migrate command, the cli throws an exception

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Use ldap
2. run `icingacli migrate preferences --resource=auth_ldap`

## Expected behavior
No exception should happen and the migration should be successful.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.3
* Web browser used: Safari
* Icinga 2 version used (`icinga2 --version`): r2.12.5-1
* PHP version used (`php --version`): 7.3.29-1~deb10u1 
* Server operating system and version: Debian 10

## Additional context

```
root@mon2:/home/paladox# icingacli migrate preferences --resource=auth_ldap

Fatal error: Uncaught Error: Call to undefined method Icinga\Protocol\Ldap\LdapConnection::getDbAdapter() in /usr/share/php/Icinga/User/Preferences/Store/DbStore.php:89
Stack trace:
#0 /usr/share/icingaweb2/modules/migrate/application/clicommands/PreferencesCommand.php(68): Icinga\User\Preferences\Store\DbStore->load()
#1 /usr/share/php/Icinga/Cli/Loader.php(267): Icinga\Module\Migrate\Clicommands\PreferencesCommand->indexAction()
#2 /usr/share/php/Icinga/Application/Cli.php(164): Icinga\Cli\Loader->dispatch()
#3 /usr/share/php/Icinga/Application/Cli.php(154): Icinga\Application\Cli->dispatchOnce()
#4 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#5 {main}
  thrown in /usr/share/php/Icinga/User/Preferences/Store/DbStore.php on line 89
```

**Comment by paladox** [comment]
Oh I guess I misinterpreted this.

```
root@mon2:/home/paladox# icingacli migrate preferences --resource=icinga_ido
Cannot fetch preferences for user guest from database: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'icinga.icingaweb_user_preference' doesn't exist, query was: SELECT icingaweb_user_preference.section, icingaweb_user_preference.name, icingaweb_user_preference.value FROM icingaweb_user_preference WHERE (username = 'guest')
Failed to migrate some user preferences
```

**Comment by nilmerg** [comment]
Yeah, an ldap resource won't work there. The ido is also the wrong db, you should use a resource that points to the icingaweb2 database.
