### ISSUE TITLE
"My Account" broken after Upgrade from 2.8.2 to 2.9.3

### ISSUE THREAD

**Issue by Clasko** [Icinga/icingaweb2#4512]
## Describe the bug
"My Account" is completly broken for some users after upgrading from 2.8.2 to 2.9.3. 

Error message in Webinterface: `file_get_contents(): Filename cannot be empty`

Traceback:
`
2021-08-23T11:01:00+02:00 - ERROR - ErrorException in /usr/share/icingaweb2/application/forms/PreferenceForm.php:214 with message: file_get_contents(): Filename cannot be empty
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/application/forms/PreferenceForm.php(214): file_get_contents(String)
#2 /usr/share/php/Icinga/Web/Form.php(776): Icinga\Forms\PreferenceForm->createElements(Array)
#3 /usr/share/php/Icinga/Web/Form.php(1118): Icinga\Web\Form->create(Array)
#4 /usr/share/icingaweb2/application/forms/PreferenceForm.php(171): Icinga\Web\Form->populate(Array)
#5 /usr/share/php/Icinga/Web/Form.php(1209): Icinga\Forms\PreferenceForm->onRequest()
#6 /usr/share/icingaweb2/application/controllers/AccountController.php(78): Icinga\Web\Form->handleRequest()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AccountController->indexAction()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#13 {main}
`

## To Reproduce
Unclear to me right now. I don't see any differences between users who have this issue and those who don't.
Issues exists since Upgrade to 2.9.3.

## Expected behavior
Preferences should be available as normal.

## Screenshots
![grafik](https://user-images.githubusercontent.com/510177/130422066-f30eac76-6881-4a19-a70a-151f29e530f0.png)

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.9.3
* Web browser used: Firefox 91.0.1
* Icinga 2 version used (`icinga2 --version`): 2.9.3
* PHP version used (`php --version`): 7.3.20
* Server operating system and version: RHEL 7

**Comment by Clasko** [comment]
Ok, found the reason: This happens if you have an theme configured which does not exists anymore.
I disabled some incompatible themes with 2.9.3 in advanced and set "Users Can't Change Theme" before.

**Comment by nilmerg** [comment]
Exactly, a module's theme defined in the preferences of a user causes this issue, if the module is not enabled. The only work-around currently is to re-enable the modules in question or update the user preferences to not use their themes.
