### ISSUE TITLE
After updating Icinga2 from 2.12.3 to 2.13.1, I am unable to fetch ticket from Agent tab on icingaweb2

### ISSUE THREAD

**Issue by Prathameshhankare** [Icinga/icingaweb2#4514]
## Describe the bug
I recently updated icingaweb2 and Icinga2 to the latest version available after which I am unable to fetch tickets from Hosts - > Agent tab.

I get the following error:

`Requesting salt, but got none

#0 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/AgentWizard.php(109): Icinga\Module\Director\IcingaConfig\AgentWizard->getTicketSalt()
#1 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/AgentWizard.php(141): Icinga\Module\Director\IcingaConfig\AgentWizard->getTicket()
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/SelfService.php(256): Icinga\Module\Director\IcingaConfig\AgentWizard->renderWindowsInstaller()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/SelfService.php(52): Icinga\Module\Director\Web\SelfService->showLegacyAgentInstructions(Object(Icinga\Module\Director\Controllers\HostController))
#4 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(544): Icinga\Module\Director\Web\SelfService->renderTo(Object(Icinga\Module\Director\Controllers\HostController))
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\HostController->agentAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}`

## Screenshots
![image](https://user-images.githubusercontent.com/52577680/130597390-7e35e477-b01c-448e-969c-bf26f32f944d.png)

## My Environment
* Icinga Web 2 version and modules (System - About): 2.9.3
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.13.1
* PHP version used (`php --version`): PHP-73
* Server operating system and version: Centos 7

**Comment by mocdaniel** [comment]
Does the salt constant `TicketSalt` in `/etc/icinga2/constants.conf` exist on your master node? Sounds to me like it might be missing and this might be the problem.

**Comment by Prathameshhankare** [comment]
Yes, the const TicketSalt is present in the constants.conf file. Also, to add my director version is master. I accidentally installed the master version but it was working fine until I updated Icinga2 and Icingaweb2 to the latest version.

**Comment by Prathameshhankare** [comment]
The issue is resolved now. good to close the case.
