### ISSUE TITLE
Proposal for new Feature make comments collapsible

### ISSUE THREAD

**Issue by tomabg** [Icinga/icingaweb2#4515]
Hi,

i made an integration of icinga into a monitoring system which also includes regular status updates and so on.
The problem i have is hat comments after time may very long (1000 + lines or more).

It would be a usefull feature if comments can be collabsed to a configuratble number of lines.
Maybe 25 Lines are default and it should be overwriteable in Users Preferences.

This would be usefull in service View and comments view

Maybe a usefull feature for Icingaweb2?

**Comment by nilmerg** [comment]
Hi,

I have to differentiate here:

* Host/Service detail lists comments, if they'll contain images or large chunks of text they're still shown in their entirety
* The same applies to the comment overview (list)

Comments in these places don't need to be shown in their entirety. The full comment (comment detail) though should be a single click away.

The comment detail on the other hand already shows the full comment and I see no reason why it should be collapsed there as the place there is already reserved for the comment.

So no, making comments collapsible here isn't the right solution. We should instead limit the shown comment to e.g. two lines and only reveal the full comment by clicking on it.

This could look like this: (Image taken from Icinga DB Web)

![Screenshot from 2021-08-25 15-45-13](https://user-images.githubusercontent.com/16668527/130802130-f7894bbd-8a1d-4752-9461-5f0662f82e7c.png)

Hence I'll mark this as bug, will also help to get this resolved more quickly :wink:
