### ISSUE TITLE
JS assets loading order in libraries (#4272)

### ISSUE THREAD

**Issue by distahl** [Icinga/icingaweb2#4518]
This is reagrding libraries from #4272. 
But the same happens with assets from an additional "helper" module (#3961), which is deprecated now.

## Is your feature request related to a problem? Please describe.
I'm not sure if I do something wrong, but it feels like an ordering issue.
When adding additional javascript modules/files to `<lib>/asset/js`, which depend on jquery. They seem to get loaded before jquery gets loaded. This results in not working/exiting functions, which I want to use in my module's `module.js`

## Describe the solution you'd like
Make javascript assets get loaded after jquery (is it `icinga.js` ?) and before the module's `module.js`. And inside the `asset/js` directory load the files alphabetically, if not already. This way I can use `00-file.js`, `01-file.js`, ... to order them.

## Describe alternatives you've considered
-

## Additional context
-

**Comment by nilmerg** [comment]
Hi!

Nice to see that you're making use of the library integration!

We have our own module loader implementation that uses a similar interface as RequireJS. With this you can control when factories are evaluated. Just do this:

File: `asset/js/foo/bar.js`

```js
define(function () {
    // Just use `$`. At the time of reference it should be available
});
```

Somewhere in your `module.js`: `let bar = require('<library-name>/foo/bar');`

**Comment by distahl** [comment]
Hi,
Thank you. I'm not sure if I did it right, but I tried the `require()` approach. Like this in my `module.js` at the very top of the file:
```
require('my_libraries/third-party/jquery-ui.min.js');
require('my_libraries/third-party/FileSaver.js');
require('my_libraries/third-party/loadingoverlay.js');
require('my_libraries/third-party/fm.datetator.jquery.js');
require('my_libraries/third-party/fm.datetator-de.jquery.js');
require('my_libraries/third-party/jquery-customselect-1.9.1.min.js');
require('my_libraries/third-party/jquery.easy-autocomplete.js');
require('my_libraries/third-party/jquery.getStyleObject.js');
```

Unfortunately this doesn't change anything. I'm still getting `Uncaught TypeError: Cannot read property 'oPagination' of undefined` and after that `Uncaught ReferenceError: Icinga is not defined`. 

Even if I disable all of my custom modules. This error appears and breaks hole icingaweb. It looks like files inside `asset/js` are getting all autoloaded by icingaweb just because they are there.

**Comment by nilmerg** [comment]
> I'm not sure if I did it right, but I tried the require() approach.

The `.js` file extension is not necessary.

> It looks like files inside asset/js are getting all autoloaded by icingaweb just because they are there.

Yep.

> Unfortunately this doesn't change anything.

You should ensure that nothing besides the call to `define` runs in your files once loaded. Also the factory you're passing it must not run immediately.
If you have that much separate assets, also think about passing the implicit requirements in the call to `define`.

Maybe look at [what the icinga-php-library does](https://github.com/Icinga/icinga-php-library/tree/stable/0.6.1/asset/js).

If you use some vendor libs not written by you, they may only support the *official* RequireJS interface, not ours. For this you'd have to adjust the files accordingly. This usually looks like this:

```js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
        typeof define === 'function' && define.amd ? define(factory) :
            (global = global || self, global.Sortable = factory());
}(this, function () { 'use strict';
```

There you'll need to change `define.amd` to `define.icinga`.

**Comment by distahl** [comment]
I have to admit, I'm completely lost now. My knowledge in javascript is kindof basic. I never heard about RequireJS before and I'm afraid many jquery libraries or additions don't care about something like this. I also have many question marks in my head while looking at your example, which explains how to make them ready for the require approach. This becomes very complicated. Only thing I wanted to do is load some default javascript libraries in a special order :-(

**Comment by nilmerg** [comment]
Then I'd suggest to read up on [RequireJS's *asynchronous module definition* (amd)](https://requirejs.org/docs/whyamd.html). Though, remember we don't utilize RequireJS but a cut-down self-written implementation, so not everything mentioned there works here.

**Comment by nilmerg** [comment]
On my way out, but at first glance:

* Use `["jquery"]` instead of `['jquery']` when defining dependencies. You should also see some debug messages in the log regarding this.
* >  In the moment you specifiy an requirement, like define(['jquery'], function ($) {});, you will get an syntax error.
  
  Shouldn't happen. We make use of this exclusively in the icinga-php-library and it works.

**Comment by distahl** [comment]
> * Use `["jquery"]` instead of `['jquery']` when defining dependencies.

Unforunately doesn't changes anything regarding the errors or regarding `["my_libraries/third-party/jquery"]`.

> You should also see some debug messages in the log regarding this.

Which log do you speaking about? The console log of the browser? If yes, there are no debug messages displayed regarding this.

> Shouldn't happen. We make use of this exclusively in the icinga-php-library and it works.

Hmm...I just wanted to reproduce it, to show you the error message, but the error doesn't happen anymore. Maybe I did something wrong the last time. So never mind :-)

**Comment by nilmerg** [comment]
Looking now at your library list, I noticed you don't have a jquery named one. If you want to designated this way you'll want that jQuery Icinga Web 2 provides, this won't work. And that's the reason why you get those "is undefined" errors. The dependency cannot be fulfilled and that's the result.

The libraries are isolated from Icinga Web 2. If you want to use jQuery, just use it. Don't require it.

**Comment by distahl** [comment]
Thank you so much. It seems to work now.
I've removed the "jquery" dependency and as a workaround, I added a `var $ = $ || window.jQuery;` at the beginning of the code part. E.g. like this:

```js
(function( factory ) {
	"use strict";
	if ( typeof define === 'function' && define.icinga ) {
		define([], function () { return factory();});
	}
	else {
		factory(jQuery);
	}
}
(function($){
    var $ = $ || window.jQuery;
    
    $.fn.getStyleObject = function(){
    [...]
}));
```

**Comment by nilmerg** [comment]
I think we can close here.
