### ISSUE TITLE
Issue with non javascript files in asset/js directory

### ISSUE THREAD

**Issue by distahl** [Icinga/icingaweb2#4519]
## Describe the bug
If using the library (#4272) or module asset approach (#3961) and you put non javascript files in `asset/js`, the minifier will give you an error. I realized that, because I'm using webdav to access my files and unfortunately webdav sometimes creates `.DAV` directories with some status/info files inside.

Maybe this is also a thing for the `asset/css`. But I didn't checked that. Just as a sidenode.

## To Reproduce
Put a non javascript coded file into `asset/js`

## Expected behavior
Only read `*.js` files from `asset/js` directory

**Comment by nilmerg** [comment]
I've thought about that but neglected it because I only thought about files being placed manually there. But of course, some tools create hidden files/directories automatically. Be it vim, an IDE of sorts or now Webdav...

Will be fixed for sure!
