### ISSUE TITLE
Slower since 2.8.3 -> 2.9.1 upgrade

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2#4527]
## Describe the bug
On Friday September 3rd we upgraded icingaweb2 from v2.8.3 to v.2.9.1 and since then the user experience is bad, it is very slow browsing menus or showing search results, for instance (about 30s).

Besides that the VM IOPS increased a lot after the upgrade on Friday and even more today after rebooting the system:

![image](https://user-images.githubusercontent.com/31234197/132192352-76c2be4e-fba3-4284-89d9-775b312e13d8.png)

Disk:
![image](https://user-images.githubusercontent.com/31234197/132193109-64275fb1-755c-489e-880f-e5fec9da1750.png)

OS CPU:
![image](https://user-images.githubusercontent.com/31234197/132193296-3304e0f8-307b-4959-9cf1-6666c9305d16.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
![image](https://user-images.githubusercontent.com/31234197/132192762-6c2e451a-7328-4366-8139-13ec53c6f2c3.png)

* Web browser used:
Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)
Mozilla Firefox 78.13.0esr (64-bit)

* Icinga 2 version used (`icinga2 --version`):
```
$ icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.1-1)

Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-16-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: runner-hh8q3bz2-project-508-concurrent-0
  OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

```
* PHP version used (`php --version`):
```
PHP 7.0.33-0+deb9u11 (cli) (built: Jul 12 2021 18:15:58) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u11, Copyright (c) 1999-2017, by Zend Technologies

```
* Server operating system and version:
```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
```

**Comment by bunghi** [comment]
It looks like vsphere module was generating high load on the disks. We disabled the module and Icinga is fast again.

**Comment by nilmerg** [comment]
Oh ghosh, thanks for the update. I was just answering and asking for more details and whatnot. :laughing:
