### ISSUE TITLE
Service list slow when user is restricted to a service group

### ISSUE THREAD

**Issue by kayssun** [Icinga/icingaweb2#4529]
## Describe the bug
The page "service problems" has very long loading time (around 45 seconds) when there are a lot of objects in the database and the user is restricted to a service group. This seems to be the query for the object count (I guess for the paging links).

## To Reproduce
We have around 32000 objects in the icinga_objects table (around 30000 services). Most services are assigned to our monitoring team (SE) with the following role:

```
[SystemEngineering]
permissions = "*"
groups = "SE"
monitoring/filter/objects = "servicegroup_name=se"
```

When a user with this role clicks on "Problems/Services" or "Overview/Services" or several other lists which include numbers of services, the page loads very slow (about 45 seconds for most of them).

## Expected behavior
The page loading time should be less then a few seconds.

## Your Environment
Icinga version: 2.13.1-1
Icinga Web 2 Version: 2.9.3
Git commit: c757a17530c326c7d6daebd6171486cb8167a8a1
PHP Version: 7.4.6

## Additional context
The slow query is:

```
SELECT COUNT(*) AS cnt FROM icinga_objects AS so
 INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id AND so.is_active = 1 AND so.objecttype_id = 2
 INNER JOIN icinga_hosts AS h ON h.host_object_id = s.host_object_id
 INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = s.host_object_id
 INNER JOIN icinga_servicestatus AS ss ON ss.service_object_id = so.object_id WHERE (CASE WHEN COALESCE(ss.current_state, 0) = 0 THEN 0 ELSE 1 END = '1' AND  (EXISTS  (SELECT 1 FROM icinga_objects AS sub_sgo
 INNER JOIN icinga_servicegroups AS sub_sg ON sub_sg.servicegroup_object_id = sub_sgo.object_id AND sub_sgo.objecttype_id = 4 AND sub_sgo.is_active = 1
 INNER JOIN icinga_servicegroup_members AS sub_sgm ON sub_sgm.servicegroup_id = sub_sg.servicegroup_id
 INNER JOIN icinga_objects AS sub_so ON sub_so.object_id = sub_sgm.service_object_id AND sub_so.objecttype_id = 2 AND sub_so.is_active = 1 WHERE ((sub_sgo.name1 IN ('se')) AND sub_sgm.service_object_id = so.object_id))) )
```

This query takes about 45 seconds on our database so I guess this is the main problem. At this point I am not sure if the main data query is just faster because it is limited to 25 objects.

If I can help debugging by running test queries or changing code please let me know.

**Comment by nilmerg** [comment]
This is a very simple query and filter. The database shouldn't have any problem resolving this. If I run an explain on it here, It shows that the optimizer joins the table as best as it can. Though I only have about as many as 10% of the services than you. So I'm not sure if we can do anything on our side.

| id | select\_type | table | partitions | type | possible\_keys | key | key\_len | ref | rows | filtered | Extra |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | SIMPLE | sub\_sgo | NULL | ref | PRIMARY,objecttype\_id,objects\_name1\_idx,sla\_idx\_obj | objecttype\_id | 140 | const,const | 1 | 10 | Using where; Start temporary |
| 1 | SIMPLE | so | NULL | ref | PRIMARY,objecttype\_id,sla\_idx\_obj | objecttype\_id | 9 | const | 3177 | 10 | Using where |
| 1 | SIMPLE | sub\_so | NULL | eq\_ref | PRIMARY,objecttype\_id,sla\_idx\_obj | PRIMARY | 8 | icinga2.so.object\_id | 1 | 5 | Using where |
| 1 | SIMPLE | ss | NULL | eq\_ref | object\_id | object\_id | 9 | icinga2.so.object\_id | 1 | 100 | Using where |
| 1 | SIMPLE | s | NULL | ref | services\_host\_object\_id\_idx,services\_combined\_object\_idx | services\_combined\_object\_idx | 9 | icinga2.so.object\_id | 1 | 100 | Using where; Using index |
| 1 | SIMPLE | h | NULL | ref | hosts\_host\_object\_id\_idx | hosts\_host\_object\_id\_idx | 9 | icinga2.s.host\_object\_id | 1 | 100 | Using index |
| 1 | SIMPLE | hs | NULL | eq\_ref | object\_id | object\_id | 9 | icinga2.s.host\_object\_id | 1 | 100 | Using index |
| 1 | SIMPLE | sub\_sgm | NULL | ref | sgmbrs\_sgid\_soid,idx\_servicegroup\_members\_object\_id | idx\_servicegroup\_members\_object\_id | 9 | icinga2.so.object\_id | 2 | 100 | Using where |
| 1 | SIMPLE | sub\_sg | NULL | eq\_ref | PRIMARY | PRIMARY | 8 | icinga2.sub\_sgm.servicegroup\_id | 1 | 10 | Using where; End temporary |

**Comment by kayssun** [comment]
We have an old installation with 25000 services running Icinga Web 2.6.3 - and everything is fast (about 1 second loading time for the service problems list). So that problem is not exclusively the large amount of services, something got really slow in the newer versions. Maybe I can try to identify the version that first hat this problem.

**Comment by kayssun** [comment]
I switched to Postgres now and that solved my issue. Page loading times are below one second. Should I leave this issue open since it still affects MariaDB (10.4.14) users?

**Comment by nilmerg** [comment]
We have no similar reports and the MySQL user-base is way larger than PostgreSQL, so I think if it's a general issue we'd have similar reports :thinking:
