### ISSUE TITLE
Baseurl issues behind loadbalancer

### ISSUE THREAD

**Issue by fl0wx** [Icinga/icingaweb2#4534]
## Expected Behavior
The graphs schould be shown
## Current Behavior
if i access the icingaweb2 host directly the graph from icingaweb2-grafana is loaded as expected. If i try to access the icingaweb2 host not directly, but with a loadbalancer, then the graphs arent shown.

Reason could be the "getBaseUrl" function.

this codefragment generates always a baseurl with the icingaweb2 host, not the balancerhost:
https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/2cae443a51f964f01f83b59c5d206bba08bd944d/library/Grafana/ProvidedHook/Grapher.php#L219

I havent found any configuration property to change that behavior.

here is the function which is called by the grafana module: 
https://github.com/Icinga/icingaweb2/blob/b75cf362b8f3a64a028fd88c7cf8b40cfddb4c84/library/Icinga/Web/Url.php#L161-L239

And here the line i think could be the issue
https://github.com/Icinga/icingaweb2/blob/b75cf362b8f3a64a028fd88c7cf8b40cfddb4c84/library/Icinga/Web/Url.php#L196

## Your Environment

* Icinga Web 2 Grafana version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.7.3
* Version used (`icinga2 --version`): 2.11.3
* Operating System and version:
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):

**Comment by nilmerg** [comment]
Hi,

this is most likely be solvable by a configuration change of your load balancer or web server. The line you've mentioned already does it's best job [identifying the base url by means of various environment variables](https://github.com/Icinga/icingaweb2/blob/master/library/vendor/Zend/Controller/Request/Http.php#L474-L533).

If need further help, please ask on the [forums](https://community.icinga.com).
