### ISSUE TITLE
Tab nav skips "stay logged in"

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#4563]
## Describe the bug

![Bildschirmaufnahme 2021-10-19 um 16 23 00](https://user-images.githubusercontent.com/6053266/137931891-2bff50b2-440e-4e46-ae40-84ca61bb8545.gif)

## To Reproduce

1. Go to login page
2. Focus the password field
3. Tab

## Expected behavior

It's not skipped.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 18188f718
* Web browser used: Opera
* PHP version used (`php --version`): 7.3
* Server operating system and version: CentOS 7

**Comment by Al2Klimov** [comment]
Ah! It’s disabled! Any reason for that?

**Comment by lippserd** [comment]
> Ah! It’s disabled! Any reason for that?

`config_resource` (which has to be a Icinga Web DB resource) is not set under `global`, I suppose.
