### ISSUE TITLE
Update the dompdf library included in icingaweb2-vendor-dompdf

### ISSUE THREAD

**Issue by stupiddr** [Icinga/icingaweb2#4577]
## Describe the bug
dompdf (https://github.com/dompdf/dompdf) needs in library/vendor/dompdf/

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Setup Icingaweb2 Server running PHP8
2. Attempt to download a pdf via any of the following options under Overview (Hosts, Services, Hostgroups, Servicegroups, Contactgroups, Contacts, Comments, Downtimes)

## Expected behavior
End User is prompted to download the PDF

## Screenshots
![image](https://user-images.githubusercontent.com/33382280/139743177-78105dd5-d5b7-4780-bc46-b73ab0113bac.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
```
# icingacli module list
MODULE         VERSION   STATE     DESCRIPTION
director       1.8.1     enabled   Director - Config tool for Icinga 2
incubator      0.6.0     enabled   Incubator provides bleeding-edge libraries
ipl            v0.5.0    enabled   The Icinga PHP library
monitoring     2.9.3     enabled   Icinga monitoring module
reactbundle    0.9.0     enabled   ReactPHP-based 3rd party libraries
```

* Web browser used:
Firefox 93.0 (64-bit)

* Icinga 2 version used (`icinga2 --version`):
```
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.13.1-1)

Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1160.45.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-507-concurrent-0
  OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* PHP version used (`php --version`):
```
# /usr/bin/php80 --version
PHP 8.0.12 (cli) (built: Oct 19 2021 10:34:32) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
```

* Server operating system and version:
`CentOS Linux release 7.9.2009 (Core)`

## Additional context

I can resolve the error by updating the dompdf library manually by:
```
# cd /usr/share/icingaweb2/library/vendor
# git clone https://github.com/dompdf/dompdf.git dompdfnew
# cp -R dompdfnew/* dompdf/
```

**Comment by nilmerg** [comment]
Hi,

the latest version of dompdf is not compatible with PHP 7.0, which is still required. Any chance for you to use the [pdfexport](https://github.com/Icinga/icingaweb2-module-pdfexport) module? (Use the master, latest release isn't working fine)

**Comment by nilmerg** [comment]
Since v2.11 drops support for 7.0, we can use v1.2.0 ([which brings PHP 8.1 support](https://github.com/dompdf/dompdf/pull/2668)) once it's released.
