### ISSUE TITLE
Database names with underscores in it are not working in the setup wizard

### ISSUE THREAD

**Issue by andreasscherbaum** [Icinga/icingaweb2#4586]
## Describe the bug
Tried to setup a new Icinga Web 2 and the database name has an underscore in the name (`icingaweb2_db`). When starting the web installer, the wizard asks for the database credentials, verifies the credentials as "working", and upon "Next" the Wizard complains about the same credentials that they are not working. No additional information is provided as to why the credentials are suddenly no longer working.

## To Reproduce

In the database log I can see the following query:
```
2021-11-05T01:57:21.113978Z     56649 Query     SELECT COUNT(*) as matches FROM information_schema.schema_privileges WHERE grantee = '\'icingaweb2\'@\'%\'' AND table_schema = 'icingaweb2\\_db' AND privilege_type IN ('CREATE','ALTER','REFERENCES')
```

Running this query manually:
```
mysql> SELECT COUNT(*) as matches FROM information_schema.schema_privileges WHERE grantee = '\'icingaweb2\'@\'%\'' AND table_schema = 'icingaweb2\\_db' AND privilege_type IN ('CREATE','ALTER','REFERENCES');
+---------+
| matches |
+---------+
|       0 |
+---------+
1 row in set (0,00 sec)
```

If I try the same setup without underscore, I end up with the following query in the log:
```
SELECT COUNT(*) as matches FROM information_schema.schema_privileges WHERE grantee = '\'icingaweb2\'@\'%\'' AND table_schema = 'icingaweb2' AND privilege_type IN ('CREATE','ALTER','REFERENCES');
```

Which results in:
```
mysql> SELECT COUNT(*) as matches FROM information_schema.schema_privileges WHERE grantee = '\'icingaweb2\'@\'%\'' AND table_schema = 'icingaweb2' AND privilege_type IN ('CREATE','ALTER','REFERENCES');
+---------+
| matches |
+---------+
|       3 |
+---------+
1 row in set (0,00 sec)
```

Modifying the non-working query in a setup with "database with underscore in name", and removing the unnecessary quotes in the database name produces the expected result:
```
mysql> SELECT COUNT(*) as matches FROM information_schema.schema_privileges WHERE grantee = '\'icingaweb2\'@\'%\'' AND table_schema = 'icingaweb2_db' AND privilege_type IN ('CREATE','ALTER','REFERENCES');
+---------+
| matches |
+---------+
|       3 |
+---------+
1 row in set (0,00 sec)
```

## Expected behavior

Database names with underscores in it should "just work". If they are not working, for whatever reason, the wizard must complain when entering credentials.

Right now the Wizard happily accepts underscores, validates that the database connection is working, only then on the next page complains about something is not working without providing any detailed information.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.8.2-2 
* Icinga 2 version used (`icinga2 --version`): r2.12.3-1
* PHP version used (`php --version`): 8.0.8
* Server operating system and version: Ubuntu 21.10

## Additional context

The query above is querying the information_schema, using equal (=), not using LIKE. This query expects exact results, and is not affected by any MySQL magic for "%" and "\_" in GRANT statements. The database name should be properly escaped (or prepared statements should be used), but escaping the "\_" for the sake of escaping is producing wrong results.

**Comment by lippserd** [comment]
Hi,

Did you do the `GRANT`(s) manually? If so, please see #3476.

All the best,
Eric

**Comment by nilmerg** [comment]
No feedback on here. I guess Eric's comment solved it.
