### ISSUE TITLE
&showFullscreen supresses announcements

### ISSUE THREAD

**Issue by slalomsk8er** [Icinga/icingaweb2#4596]
## Describe the bug
If I set a announcements it gets ignored while in fullscreen.
## To Reproduce

1. Add &showFullscreen&showCompact to a dashboard URL
2. create announcements
3. reload dashboard URL
4. remove  &showFullscreen&showCompact from dashboard URL
5. reload dashboard URL

## Expected behavior
Announcements get displayed on wall mounted displays that use a dashboard URL with &showFullscreen&showCompact.

* Icinga Web 2 version and modules (System - About):cinga Web 2 Version
2.9.3
Git Commit
c757a17530c326c7d6daebd6171486cb8167a8a1
PHP-Version
7.3.29
Git Commit Datum
2021-08-10

**Comment by B3RN0UT** [comment]
Determined the same behavior at our site.
We have the same need to display announcements on Screens with &showFullscreen&showCompact.
