### ISSUE TITLE
icinga director broken by icingaweb2 2.9.4

### ISSUE THREAD

**Issue by araujorm** [Icinga/icingaweb2#4598]
## Describe the bug
After updating icingaweb2 to v2.9.4, icinga director module breaks

## To Reproduce
1. Install icingaweb2 v2.9.4
2. Install and fully setup icingaweb2-module-director
3. Access zones or external commands section and try to view an item, nothing is displayed
4. Confirm on browser console that there are lots of javascript errors

## Expected behavior
Items should be displayed without javascript errors

## Screenshots
N/A

## Your Environment
CentOS 8, fresh install, fully updated, using icinga2 stable repos

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version 2.9.4
director 1.8.1
incubator 0.8.0
monitoring 2.9.3
```
* Web browser used: firefox and chrome
* Icinga 2 version used (`icinga2 --version`): 2.13.1-1
* PHP version used (`php --version`): 7.4.25
* Server operating system and version: CentOS 8, fully updated

## Additional context
Problems do not occur if downgrading to icingaweb2 2.9.3 so I'd say this is a icingaweb2 issue and not director module problem, if I'm wrong please tell me so that I can open the issue in the correct place.

**Comment by Thomas-Gelf** [comment]
Could you please share those errors? Does anything change, if you SHIFT-reload your browser window?

**Comment by nilmerg** [comment]
Please apply #4600 and check if that solves the problem. (`/usr/share/icingaweb2/public/js/icinga/loader.js`) Make sure to perform a force-reload (SHIFT-reload, as Tom suggested) after you've made the change.

**Comment by araujorm** [comment]
> Could you please share those errors? Does anything change, if you SHIFT-reload your browser window?

@Thomas-Gelf Here's the output of the browser console (firefox):
```
Icinga Web 2: setting initial layout to wide-layout commands:376:26
Incubator module is still waiting for icinga icinga.min.js:812:1343
16:33:29.658 Icinga is ready, running on jQuery  3.4.1 icinga.min.js:440:537
16:33:29.773 Incubator is ready icinga.min.js:440:537
16:33:30.398 No lastUpdate, setting one col1 icinga.min.js:440:537
16:33:30.403 No lastUpdate, setting one application-state
Uncaught TypeError: $target.data(...) is undefined
    redirectToUrl http://my.ip.address/icingaweb2/js/icinga.min.js:586
    processRedirectHeader http://my.ip.address/icingaweb2/js/icinga.min.js:584
    onComplete http://my.ip.address/icingaweb2/js/icinga.min.js:622
    c http://my.ip.address/icingaweb2/js/icinga.min.js:15
    fireWith http://my.ip.address/icingaweb2/js/icinga.min.js:15
    l http://my.ip.address/icingaweb2/js/icinga.min.js:15
    o http://my.ip.address/icingaweb2/js/icinga.min.js:15
    send http://my.ip.address/icingaweb2/js/icinga.min.js:15
    ajax http://my.ip.address/icingaweb2/js/icinga.min.js:15
    loadUrl http://my.ip.address/icingaweb2/js/icinga.min.js:566
    onRowClicked http://my.ip.address/icingaweb2/js/icinga.min.js:753
    dispatch http://my.ip.address/icingaweb2/js/icinga.min.js:15
    handle http://my.ip.address/icingaweb2/js/icinga.min.js:15
    add http://my.ip.address/icingaweb2/js/icinga.min.js:15
    Ae http://my.ip.address/icingaweb2/js/icinga.min.js:15
    each http://my.ip.address/icingaweb2/js/icinga.min.js:15
    each http://my.ip.address/icingaweb2/js/icinga.min.js:15
    Ae http://my.ip.address/icingaweb2/js/icinga.min.js:15
    on http://my.ip.address/icingaweb2/js/icinga.min.js:15
    bind http://my.ip.address/icingaweb2/js/icinga.min.js:651
    each http://my.ip.address/icingaweb2/js/icinga.min.js:15
    bind http://my.ip.address/icingaweb2/js/icinga.min.js:651
    applyGlobalDefaults http://my.ip.address/icingaweb2/js/icinga.min.js:651
    each http://my.ip.address/icingaweb2/js/icinga.min.js:15
    applyGlobalDefaults http://my.ip.address/icingaweb2/js/icinga.min.js:651
    initialize http://my.ip.address/icingaweb2/js/icinga.min.js:651
    initialize http://my.ip.address/icingaweb2/js/icinga.min.js:436
    Icinga http://my.ip.address/icingaweb2/js/icinga.min.js:435
    e http://my.ip.address/icingaweb2/js/icinga.min.js:15
    t http://my.ip.address/icingaweb2/js/icinga.min.js:15
    setTimeout handler*l/< http://my.ip.address/icingaweb2/js/icinga.min.js:15
    c http://my.ip.address/icingaweb2/js/icinga.min.js:15
    fireWith http://my.ip.address/icingaweb2/js/icinga.min.js:15
    fire http://my.ip.address/icingaweb2/js/icinga.min.js:15
    c http://my.ip.address/icingaweb2/js/icinga.min.js:15
    fireWith http://my.ip.address/icingaweb2/js/icinga.min.js:15
    ready http://my.ip.address/icingaweb2/js/icinga.min.js:15
    B http://my.ip.address/icingaweb2/js/icinga.min.js:15
    EventListener.handleEvent* http://my.ip.address/icingaweb2/js/icinga.min.js:15
    <anonymous> http://my.ip.address/icingaweb2/js/icinga.min.js:15
    <anonymous> http://my.ip.address/icingaweb2/js/icinga.min.js:15
```

> Please apply #4600 and check if that solves the problem. (`/usr/share/icingaweb2/public/js/icinga/loader.js`) Make sure to perform a force-reload (SHIFT-reload, as Tom suggested) after you've made the change.
@nilmerg Confirmed, replaced that file with the one in that pull request and the problem no longer occurs. So I'd say that pull request should be included in a hotfix release maybe? :)

Thanks.

**Comment by araujorm** [comment]
> Does anything change, if you SHIFT-reload your browser window?

Sorry, forgot to reply to this part. Unfortunately just doing that doesn't solve and still throws the javascript errors. However doing a SHIFT-reload after replacing the loader.js file with the fixed one makes it work OK again.
