### ISSUE TITLE
ADFS (SSO) integration for icingaweb2 login

### ISSUE THREAD

**Issue by ClemensBW** [Icinga/icingaweb2#4608]
## Is your feature request related to a problem? Please describe.
No.

## Describe the solution you'd like
A user who exists in an AD could log in more quickly, with an ADFS login buttom this requires only one click.

## Describe alternatives you've considered
Login with username and password, as already available.

## Additional context
None.

**Comment by akqopensystems** [comment]
👍

**Comment by lippserd** [comment]
Duplicate of #3069.
