### ISSUE TITLE
Increase the usage of expressions with combined operators

### ISSUE THREAD

**Issue by elfring** [Icinga/icingaweb2#4611]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://www.php.net/manual/en/language.operators.assignment.php#language.operators.assignment.arithmetic "Description for assignment operators") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's#(?<target>\$\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+/%^.]|-(?!>)|&(?!&)|\|(?!\|)|\*\*?|<<|>>|\?\?)#$+{target} $+{operator}=#gm' $(find ~/Projekte/Icinga-Web/lokal -name '*.php')
```

**Comment by elfring** [comment]
I would appreciate a more constructive feedback for this change suggestion. :thinking:

**Comment by nilmerg** [comment]
Which change suggestion?? I honestly identified this as spam / nonsense.

**Comment by elfring** [comment]
The Perl command example can point source code places out where assignment expressions can be adjusted, can't it? :thinking:

**Comment by nilmerg** [comment]
Ah, now I see what you're up to. We don't accept changes that achieve no further additions in features or fixing of bugs. I don't know what the command checks for (didn't even attempt to decipher it), but we have plenty of static analysis tools already running.

**Comment by elfring** [comment]
:thought_balloon: It seems that the source code analysis tools (which you know so far) do not point transformation possibilities out in the way I dared it here.
