### ISSUE TITLE
Restrict users to access /monitoring/health/info

### ISSUE THREAD

**Issue by deuntje** [Icinga/icingaweb2#4615]
## Is your feature request related to a problem? Please describe.
Users which are restricted with access control rules can access /monitoring/health/info and toggle Feature Commands which apply server-wide.

## Describe the solution you'd like
Would like to have the option to deny access to the page via the access control mechanism

## Describe alternatives you've considered
Make the Feature Commands toggles only available for admin users.

## Additional context
View from a restricted user:
![image](https://user-images.githubusercontent.com/17932042/144640775-97a3b302-59f6-4fcd-8f4c-e679cd1082a0.png)

add application/monitoring-health to this list.
![image](https://user-images.githubusercontent.com/17932042/144640098-eb680dcc-2209-4bfe-9f4e-8d8032951f12.png)

**Comment by nilmerg** [comment]
Unfold the `monitoring` section, and you'll find the permission you're looking for.

**Comment by deuntje** [comment]
I suppose you mean the 'monitoring/​command/​feature/​instance' access control under monitoring? I already had that one denied, but still have this option as a restricted user.

![afbeelding](https://user-images.githubusercontent.com/17932042/144814496-209d7b0a-1dfe-476c-85be-b6e81dd58753.png)

![afbeelding](https://user-images.githubusercontent.com/17932042/144814639-26a4d72d-bf28-425c-aaad-33f202552f23.png)

![afbeelding](https://user-images.githubusercontent.com/17932042/144815187-9e2cdce3-1a6e-47a1-af2c-edc3e1fab065.png)

Do I miss something?

**Comment by nilmerg** [comment]
You'll still see the state of the features (the toggles) but you cannot interact with them.

**Comment by deuntje** [comment]
Damn, you're right! Assumptions is the mother... Need to look and test better in the future, thanks for your responses!
