### ISSUE TITLE
Changing user account settings results in "Call to a member function isChecked() on null"

### ISSUE THREAD

**Issue by distahl** [Icinga/icingaweb2#4618]
## Describe the bug
When changing something in user account settings, you will get the following error:
```
Uncaught Error: Call to a member function isChecked() on null in /usr/share/php/Icinga/Web/Form.php:1231
Stack trace:
#0 /usr/share/icingaweb2/application/forms/PreferenceForm.php(445): Icinga\Web\Form->isSubmitted()
#1 /usr/share/php/Icinga/Web/Form.php(1175): Icinga\Forms\PreferenceForm->isSubmitted()
#2 /usr/share/icingaweb2/application/controllers/AccountController.php(78): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AccountController->indexAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\A
```

## To Reproduce
Change some user settings.

## Expected behavior
no error

## Screenshots
-

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.5
* Web browser used: Chromium v94.0.4606.81
* Icinga 2 version used (`icinga2 --version`): 2.13.2
* PHP version used (`php --version`): 7.3.29
* Server operating system and version: RHEL7 / CentOS7 / OL8

## Additional context
-

**Comment by nilmerg** [comment]
Hi,

this occurs because you don't have a *User Preference Storage Type* configured. This is [deprecated](https://github.com/Icinga/icingaweb2/blob/master/doc/80-Upgrading.md#upgrading-to-icinga-web-2-29x) since v2.9.0. Please configure a database as *User Preference Storage Type* in the general configuration and this error is gone.

**Comment by distahl** [comment]
Oh! Thank you for clarification.
I read this information the past, but I missrembered it. I thought it was not possible to set INI Storage, but existing ones will work until v2.11. But I guess this was something different then.

**Comment by nilmerg** [comment]
The INI storage type still works, yes, until v2.11. But you seem to have none at all. While this is not supposed to not work, it's also not on high priority to be fixed to be honest. So switching to a storage type now is the better option for you.

**Comment by distahl** [comment]
OK. Thank you. I've migrated to db storage. Now everything is working again :-)
Issue can be closed.
