### ISSUE TITLE
"Configuration->Access Control" not showing correct permissions, when perm uses wildcard

### ISSUE THREAD

**Issue by distahl** [Icinga/icingaweb2#4622]
## Describe the bug
When having a role permission, which is using a wildcard (`*`) without a preceding slash (e.g.: `something/sub1*`), IcingaWeb is not showing the correct permissions at `Configuration->Access Control`. Instead it seems to think this role has admin rights and shows everything like it would be allowed. But this seems to be only a display error, because, luckily, in real this role still has its limited access, which is configured.

## To Reproduce
Modify/Create a role (in `roles.ini`) and add to permissions this string for example: `something/sub1*`.
Look into `Configuration->Access Control`. Click onto the role you created/modified.
You will see wrong displayed permissions.

## Expected behavior
Show correct permissions.

## Screenshots
-

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.5
* Web browser used: Chromium 94.0.4606.81
* Icinga 2 version used (`icinga2 --version`): 2.13.2
* PHP version used (`php --version`): 7.3.29
* Server operating system and version: RHEL7

## Additional context
-

**Comment by nilmerg** [comment]
Hi,

all parts of this rely on what can be configured in the UI. The wildcard may work this way, but that's more of an implementation detail than a feature. Since it's not possible to configure this in the UI, but only by editing the file manually, I'm not fancy *fixing* this to be honest. It's easy to fix that it doesn't pretend that full access is allowed, but with that fixed, nothing is allowed at all since the permission is *unknown*. And that's not easy to change.

You're better off using the supported permissions only: https://icinga.com/docs/icinga-web-2/latest/doc/06-Security/#general-permissions

**Comment by distahl** [comment]
I'm not aware that I ever added the syntax, explained above, by hand. This must have been added by IcingaWeb GUI in an earlier version. And now, with newest version, gets missunderstood.

**Comment by nilmerg** [comment]
> this must have been added by IcingaWeb GUI in an earlier version. But, we will never know for sure.

While I really doubt that, it would be easier for me by knowing the exact permission, not just `something/sub1*` :wink:

**Comment by distahl** [comment]
It's a permission for a custom module someone of us (not me) created. The permissions is `dtag_linkliste/list/view*` and it seems the only one which has the wrong syntax.

**Comment by distahl** [comment]
Oh. I guess I now see what's wrong.
I just tested to add this specific permission to some other role, using the GUI. And it gets added exactly the same way (with wrong syntax) to the ini file.

That's why, I now looked into the modules `configuration.php`. And there I can see this
```
$this->providePermission
(
        'dtag_linkliste/list/view*',
        'Berechtigung zum Anzeigen der Linkliste'
);
```

So it looks like, the initial definition of this perm is already wrong.

**Comment by nilmerg** [comment]
Well, no. That's fine. It will also work fine, if the role configuration doesn't pretend that everything is allowed. Because it is a real/known permission, even if weirdly defined, it can be identified correctly.

So, I guess we'll fix that small issue and everything is fine. :grinning:

**Comment by distahl** [comment]
Just to get you right:
So now this is an accepted bug and not a wrong configuration on my side? :-)

**Comment by nilmerg** [comment]
Yes!

**Comment by distahl** [comment]
Great. Thank you very much.
