### ISSUE TITLE
Customvariables do not work as expected in Roles to restrict Hosts

### ISSUE THREAD

**Issue by ali-avci** [Icinga/icingaweb2#4626]
## Describe the bug
We have a custom variable named Responsible Team "responsible_team". 

When this one is used via the Filters available in the UI it is shown as Host Responsible Team. It is a choosable variable from 2 possible values (IT Team "IT", PS Team "PS"). When applying the filter via the UI it is executing as expected and the results are limited via the given value of 25.

When using the same Filter via a role assigned to a user nothing is displayed. Used a bug feature to extract the executed query on the UI and have seen that there is a "LIMIT 25" injected in the MYSQL Query probably on the wrong place. The limit is placed in the Subquery that is responsible for the Customvariable filtering. When applying the same query without the limit clause directly to mysql it is generating the complete result set.
 

## To Reproduce
It is probably only observable if the number of hosts is much more than the initial limit.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

IcingaWeb2 - 2.9.5

## Own investigation
Query taken via the UI (collate clause and group/sum clauses are removed, icinga_customvariablestatus produces results when the where clauses are executed only against that table)

SELECT so.name1 AS host_name FROM icinga_objects AS so
INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id AND so.is_active = 1
INNER JOIN icinga_servicestatus AS ss ON ss.service_object_id = so.object_id AND ss.current_state > 0
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = s.host_object_id
INNER JOIN (**SELECT** ho.object_id FROM icinga_objects AS ho
INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
LEFT JOIN icinga_customvariablestatus AS hcv_responsible_team ON h.host_object_id = hcv_responsible_team.object_id AND hcv_responsible_team.varname = 'responsible_team'  WHERE ( (hcv_responsible_team.varvalue = 'PS') ) **LIMIT 25**) AS h ON h.object_id = s.host_object_id

**Comment by nilmerg** [comment]
Hi,

where do you face this problem? In a monitoring module view or one by some other module? Which view exactly?

**Comment by nilmerg** [comment]
But as you can see here: (from `monitoring/list/services`)

```
SELECT ... FROM icinga_objects AS so
 INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id AND
so.is_active = 1 AND so.objecttype_id = 2
 INNER JOIN icinga_hosts AS h ON h.host_object_id = s.host_object_id
 INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = s.host_object_id
 INNER JOIN icinga_servicestatus AS ss ON ss.service_object_id =
so.object_id
 LEFT JOIN icinga_customvariablestatus AS hcv_env ON s.host_object_id =
hcv_env.object_id AND hcv_env.varname = 'env' COLLATE latin1_general_ci
WHERE ( (hcv_env.varvalue = 'prod') ) ORDER BY s.display_name COLLATE
latin1_general_ci ASC
```

The custom variables are not queried in a sub-select, but are directly joined. So it must be another view you've got your query from.

**Comment by ali-avci** [comment]
Found the problem: 
When entering the filter rule in the role definition have used the following string
_host_responsible_team = PS 

Spaces are treated as hard spaces and it is converted to the following where clause 
hcv_responsible_team = ' PS' (with the space in front of PS)

The documentation might be adopted so that the community is informed.

Thanks for your efforts... 

Closing this ticket.
