### ISSUE TITLE
Big pie charts in service overview

### ISSUE THREAD

**Issue by r3dbU1L** [Icinga/icingaweb2#4629]
## Describe the bug
After a migration from one host to another there are some weird display issues in the pie charts everywhere in icingaweb2

## To Reproduce
I can't really describe how to reproduce it, since I just moved the Icinga databases from the old system to the new one and updated the OS and icingaweb2

## Expected behavior
Little pie charts as in the screenshot from the old system

## Screenshots
Old System:
![image](https://user-images.githubusercontent.com/26123436/148181624-3775fc40-b831-4092-be07-6dab3d217b70.png)

New System:
![image](https://user-images.githubusercontent.com/26123436/148181667-b540ba0e-a76c-4a19-8669-a30f1dd862d1.png)

## My Environment

* Icinga Web 2 version and modules (System - About): Old server: 2.7.6 | **New server**: 2.9.5
* Web browser used: Google Chrome Version 96.0.4664.110
* Icinga 2 version used (`icinga2 --version`): Old server: r2.12.3-1 | **New server**: r2.13.2-1
* PHP version used (`php --version`): Old server: 7.0.33 | **New server**: 7.4.3
* Server operating system and version: Old server: Ubuntu 16.04.7 LTS | **New server**: 20.04.3 LTS

**Comment by nilmerg** [comment]
This is most likely a caching issue. Try clearing the browsers cache or hard reload the tab (Ctrl+R,Ctrl+F5,Cmd+...)

**Comment by r3dbU1L** [comment]
> This is most likely a caching issue. Try clearing the browsers cache or hard reload the tab (Ctrl+R,Ctrl+F5,Cmd+...)

Thanks for the hint, but it didn't work. Same problem on mobile browsers.

**Comment by nilmerg** [comment]
You could also switch the theme for a moment, that enforces a cache invalidation as well.

**Comment by r3dbU1L** [comment]
> 

Nope, didn't work :(

**Comment by r3dbU1L** [comment]
> You could also switch the theme for a moment, that enforces a cache invalidation as well.

Nope, didn't work :(

**Comment by nilmerg** [comment]
Fine.. then access the server directly and clean up all files from `/tmp/FileCache_icingaweb/`. (May differ depending on systemd)

If that doesn't help, please check if `md5sum /usr/share/icingaweb2/modules/monitoring/public/css/module.less` gives `e155667ea021577a010c51767f58b429` as result.

**Comment by r3dbU1L** [comment]
> Fine.. then access the server directly and clean up all files from `/tmp/FileCache_icingaweb/`. (May differ depending on systemd)
> 
> If that doesn't help, please check if `md5sum /usr/share/icingaweb2/modules/monitoring/public/css/module.less` gives `e155667ea021577a010c51767f58b429` as result.

Cleaning `/tmp/FileCache_icingaweb/` didn't help, but `md5sum /usr/share/icingaweb2/modules/monitoring/public/css/module.less` gave me `138ea727b0df1acacb77fcb71d051df3` as result

**Comment by nilmerg** [comment]
Then I suggest to re-install Icinga Web 2. Maybe remove it first to really get a clean install.

**Comment by nilmerg** [comment]
Did a re-install solve the issue?

**Comment by r3dbU1L** [comment]
> Did a re-install solve the issue?

I haven't tried yet, I will check it tomorrow

**Comment by nilmerg** [comment]
No other reports. No feedback here. Closing.
