### ISSUE TITLE
TemporaryLocalFileStorage __destruct doesn't recursively delete temporary directory

### ISSUE THREAD

**Issue by willfurnell** [Icinga/icingaweb2#4630]
## Describe the bug
Icinga reporting/PDF export completely fails. I've traced it back to this module where the TemporaryLocalFileStorage __destruct function doesn't recursively delete the temporary directory it creates.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Run a scheduled task using the Icinga Reporting module

## Expected behavior
The directory is deleted (I assume)

## Stacktrace
```
PHP Fatal error:  Uncaught ErrorException: rmdir(/tmp/61d80d7c4fbc5/HOME/Default/Local Storage/leveldb): Directory not empty in /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php:45
Stack trace:
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'rmdir(/tmp/61d8...', '/usr/share/php/...', 45, Array)
#1 /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php(45): rmdir('/tmp/61d80d7c4f...')
#2 [internal function]: Icinga\File\Storage\TemporaryLocalFileStorage->__destruct()
#3 {main}
  thrown in /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php on line 45

Fatal error: Uncaught ErrorException: rmdir(/tmp/61d80d7c4fbc5/HOME/Default/Local Storage/leveldb): Directory not empty in /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php:45
Stack trace:
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'rmdir(/tmp/61d8...', '/usr/share/php/...', 45, Array)
#1 /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php(45): rmdir('/tmp/61d80d7c4f...')
#2 [internal function]: Icinga\File\Storage\TemporaryLocalFileStorage->__destruct()
#3 {main}
  thrown in /usr/share/php/Icinga/File/Storage/TemporaryLocalFileStorage.php on line 45
```

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 

* Web browser used: N/A
* Icinga 2 version used (`icinga2 --version`): 2.13.2-1
* PHP version used (`php --version`): 7.3.21
* Server operating system and version: CentOS 7

## Additional context
Related to https://github.com/Icinga/icingaweb2-module-reporting/issues/106

**Comment by nilmerg** [comment]
Directories are correctly cleaned up, even nested ones. This error is only a symptom of the referenced issue in the reporting module that is causing the browser not to be terminated correctly and hence it still writes to the directory and interferes with the cleanup.
