### ISSUE TITLE
Add primary key to tmp_user_preference

### ISSUE THREAD

**Issue by NicolasGoeddel** [Icinga/icingaweb2#4641]
## Describe the bug
On a mariadb galera cluster you need a primary key on every table. You can read about here: [Galera Cluster wsrep sst crash when trying to sync table without PK (Primary Key)](https://www.claudiokuenzler.com/blog/1083/galera-cluster-sst-crash-sync-table-without-primary-key)

## To Reproduce
This bug happens sporadically and can not be reproduced step by step. Just sometimes one or more galera nodes are killed by a SIG_ABORT. I guess it can only happen if users change their settings and the table `tmp_user_preference` was changed.

## Expected behavior
A primary key in every table.

## Possible solution
My solution would be something like this:
```sql
ALTER TABLE tmp_user_preference ADD PRIMARY KEY(username, section, name);
```

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.5
* Web browser used: Chrome
* PHP version used (`php --version`): 7.4.19
* Server operating system and version: RedHat 8.5

**Comment by nilmerg** [comment]
Hi,

our schema files for one use `icingaweb_user_preference` as name and also have exactly the primary key by default you're suggesting.

Has someone/you maybe cloned the actual preference table while upgrading to v2.9.x as a backup?

**Comment by NicolasGoeddel** [comment]
You are completely right. I just wanted to comment here because this bug report is nonsense and we made up the problem by ourselves. Now that's embarrassing...
