### ISSUE TITLE
Performance Data not rendered completely

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2#4645]
## Describe the bug
I have a check that checks multiple values.
it return this a performance data:

`| humidity=78, pressure=1027, temp=2.04;-100.0:4000;-100.0:4000, wind_speed=1.79`

since there are no critical values set on 3 out of 4 the values are/ can be ommitted

strangely the performance data is rendered incomplete:

<img width="174" alt="2022-01-26 22_58_15-CMD check_weather __ icinga-master __ Services __ Icinga Web" src="https://user-images.githubusercontent.com/29682206/151253932-50813731-aab9-4b22-9909-d8ef4cc333a7.png">

I also want to add that the performace data are written to the database correctly.

If I set critical values on all of them, which includes them into the performance values the rendering is just fine.

I also want to add that the icingadb-web module throws an exception instead of rendering the service:

<img width="558" alt="2022-01-26 23_00_18-Services __ Icinga Web" src="https://user-images.githubusercontent.com/29682206/151254326-193589d7-deff-4c2b-a9f6-64f67748e2cb.png">

My question:

Should all icinga perfdata have the same format? A mentioned before if i set the critical and warning thresholds for all, it works fine.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

Have a check return mixed performance values like above

## Expected behavior
rendering should work regardless of critical and warning thresholds in mixed perf data 

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.95
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.13.2
* PHP version used (`php --version`): 7.4
* Server operating system and version: Ubuntu 20.04

**Comment by moreamazingnick** [comment]
found the problem
icinga perfdata are seperated by space not by ", "

| humidity=78 pressure=1027 temp=2.04;-100.0:4000;-100.0:4000 wind_speed=1.79
with that it works just fine

**Comment by moreamazingnick** [comment]
https://github.com/Icinga/icingaweb2/blob/a4d495e17c53676734c75c45991fd797b33cfd5b/modules/monitoring/library/Monitoring/Plugin/Perfdata.php#L376

the problem was the "," which got included in the numeric value, but old nagios checks might still use that like check ping 
$value was "80,"
so isNumeric fails 
if we add 
`$value = $value.trim(",");`
we add a lot of compatibility to the icingaweb2

**Comment by nilmerg** [comment]
"old nagios checks"? The times we cared about compatibility with Nagios was around 2009 to 2014, maybe 2015. That time is over.

If you don't mean a legacy version of the **monitoring plugins** with which you have issues with, I'm afraid but we won't do anything here.

**Comment by moreamazingnick** [comment]
to sum it up icingaweb2 supports that:
| humidity=78 pressure=1027 temp=2.04;-100.0:4000;-100.0:4000 wind_speed=1.79
but not that as a performance data
| humidity=78, pressure=1027, temp=2.04;-100.0:4000;-100.0:4000, wind_speed=1.79

**Comment by nilmerg** [comment]
Icinga Web 2 and other components support this: https://www.monitoring-plugins.org/doc/guidelines.html#AEN201
