### ISSUE TITLE
typo in Plugin/Perfdata.php 

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2#4646]
https://github.com/Icinga/icingaweb2/blob/a4d495e17c53676734c75c45991fd797b33cfd5b/modules/monitoring/library/Monitoring/Plugin/Perfdata.php#L485

Shouldn't it be getValue()?

best regards Nicolas

**Comment by nilmerg** [comment]
PHP is case-insensitive there. So yes it's a typo, but not one *I* care about to be honest.
