### ISSUE TITLE
Icingaweb2 shows variable names only in lowercase

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icingaweb2#4648]
## Describe the bug
All custom variable name are shown in lowercase only.

## To Reproduce
Creayte an host/service object with a custom var like `vars.LoWeRcAsE =  "test1234"`

## Expected behavior
Icingaweb should show the custom variable in the same camel case as icinga uses/defined it. (Icingawbdb does that already)

## Screenshots
![grafik](https://user-images.githubusercontent.com/6574967/151980377-0037ba58-5774-41c6-8633-35e78000f653.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.5
* Web browser used: Firefox, Chrome, Safari
* Icinga 2 version used (`icinga2 --version`): 2.13.2
* PHP version used (`php --version`): 7.3
* Server operating system and version: Centos 7

**Comment by yhabteab** [comment]
duplicated of #4639
