### ISSUE TITLE
[dev.icinga.com #5519] Make CLI documentation available to the docs module

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#467]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/5519

**Created by tgelf on 2014-01-20 18:20:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-06-29 14:32:32 +00:00 (in Redmine)_

---

CLI is autogenerating it's documentation by reflection, this should be made available to the docs module too. Doing so will allow us to print and export documentation for all CLI commands.

---

**Parent Task:** [#7153](https://dev.icinga.com/issues/7153)

**Comment by lippserd** [comment]
Moved to Icinga/icingaweb2-module-doc#1.
