### ISSUE TITLE
History entries are repeated many times

### ISSUE THREAD

**Issue by dwt** [Icinga/icingaweb2#4681]
## Describe the bug
Service History entries are repeated many many times.

## To Reproduce
I am not entirely sure that I have reduce this. For me this happens on all services (though not on hosts).

1. Define a service on a host
2. Switch to the History Tab of that service
3. Enjoy

## Expected behavior
Each entry should only be shown once.

## Screenshots
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/57199/154482430-1adb335c-2371-44d1-a3d9-d348e97bbfdf.png">

## Your Environment

* Icinga Web 2 version and modules (System - About): 
```
Icinga Web 2 Version
2.9.5
Git commit
1d98c8cc3d14d11a502a9e2e57cd467c0c0087bb
PHP Version
7.4.25
Git commit date
2021-11-22
Copyright
© 2013-2022 [Icinga GmbH](https://icinga.com/)
```

as well as:
```Icinga Web 2 Version
2.9.5
Git commit
52d51f0ee532c33f2a1ab3136d5cfd5fd20d5f4c
PHP Version
7.4.25
Git commit date
2022-02-16
``` 

* Web browser used: Safari Version 15.3 (17612.4.9.1.8), Firefox 97.0 (64-Bit)
* Icinga 2 version used (`icinga2 --version`):
```dwt@nathan ~/Code/Projekte/sntl/opensource/icinga (git)-[master] % docker compose exec icinga2 icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: v2.13.0-197-g8016b013a)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.10.76-linuxkit
  Architecture: x86_64

Build information:
  Compiler: GNU 10.2.1
  Build host: e2e8a1183e4d
  OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* PHP version used (`php --version`): 
```php --version  
PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies
```
* Server operating system and version: 
``` % docker compose exec icingaweb uname -a     
Linux d1df8e54699e 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 GNU/Linux
% docker compose exec icinga2 uname -a
Linux ops 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 GNU/Linux
```

**Comment by nilmerg** [comment]
Hi,

thanks for the report. Though, it's the second time now that you open an issue regarding Icinga DB Web here. Please open it in the [respective tracker](https://github.com/Icinga/icingadb-web) instead.

**Comment by dwt** [comment]
Well, sorry. It is hard to keep track which project the UI actually belongs to. How do I make sure to get the right project? Is the URL the hint? If it contains `icingadb`, does that mean the icingadb-web project is to blame?

**Comment by nilmerg** [comment]
> If it contains icingadb, does that mean the icingadb-web project is to blame?

Essentially, yes :sweat_smile:
