### ISSUE TITLE
Wildcard characters in object names should not be processed in detail queries

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#4682]
## Describe the bug
Having an asterisk in an object name causes it to be processed as wildcard.

## To Reproduce
Have a service or host with an asterisk in the name. Click on a link for this object in the UI. The object is not found.

## Expected behavior
The asterisk is not processed as wildcard in this case.

## Additional context
ref/IP/38281

**Comment by yhabteab** [comment]
I wasn't able to reproduce this!

<img width="831" alt="Bildschirmfoto 2022-04-04 um 09 33 52" src="https://user-images.githubusercontent.com/57616252/161495441-d9c6d16a-f850-4137-8768-7ebfde124369.png">

**Comment by tectumopticum** [comment]
The description of @nilmerg is missing an important detail: the error-message appears if you place a backslash before the asterisk in the servicename:
e.g. "testservice\\*"

```
Service not found

#0 /usr/share/php/Icinga/Exception/IcingaException.php(41): ReflectionClass->newInstanceArgs(Array)
#1 /usr/share/php/Icinga/Web/Controller.php(87): Icinga\Exception\IcingaException::create(Array)
#2 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(38): Icinga\Web\Controller->httpNotFound(String)
#3 /usr/share/php/Icinga/Web/Controller/ActionController.php(155): Icinga\Module\Monitoring\Controllers\ServiceController->init()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}
```
The link/url to the service in icingaweb2 is shown as follows:
https://icinga-test.test.local/monitoring/service/show?host=dummy.test.local&service=testservice%5C%2A

**Comment by nilmerg** [comment]
At first I thought we need to escape the wildcard in the service name somehow. But then I noticed that Icinga DB Web doesn't suffer from the same problem, which means escaping isn't the solution as Icinga DB Web doesn't escape as well. But it applies the query filter in a way, which doesn't result in the `\*` part to be identified as wildcard. It's used as-is by the database instead.

The solution I think we need here is a way to do the same. Though, I don't want to to fiddle with `Zend_Select` too much to be honest. We have already the classes `FilterMatch` and `FilterEqual`. The first processes wildcards in its `matches()` method while the latter does not. When building the query to fetch a single service for the detail view, we should use `FilterEqual` specifically to disable wildcard processing. Though, our database filter rendering don't support the same differentiation and handles both classes the same, which it must not.

So please do this:

* Apply service detail filters by using `FilterEqual`
  * Don't forget to do the same for all other detail views. I expect it's not just the service detail view that has problems like this
* Adjust our database filter rendering so that instances of `FilterEqual` are processed differently than instances of `FilterMatch` (the default)
