### ISSUE TITLE
ipl module version 0.0.0

### ISSUE THREAD

**Issue by nalkema** [Icinga/icingaweb2#4694]
RHEL 7.9
PHP 7.3.29
Director 1.8.1

I just updated my packages to the latest web2 release of Icinga and I noticed that there is no version
number of ipl in the Loaded Modules.

```
Mar 09 13:03:17 Updated: icingaweb2-common-2.9.6-1.el7.icinga.noarch
Mar 09 13:03:17 Updated: icingaweb2-vendor-zf1-2.9.6-1.el7.icinga.noarch
Mar 09 13:03:17 Updated: php-Icinga-2.9.6-1.el7.icinga.noarch
Mar 09 13:03:17 Updated: icingacli-2.9.6-1.el7.icinga.noarch
Mar 09 13:03:17 Updated: icingaweb2-vendor-Parsedown-2.9.6-1.el7.icinga.noarch
Mar 09 13:03:18 Updated: 1:icingaweb2-vendor-HTMLPurifier-2.9.6-1.el7.icinga.noarch
Mar 09 13:03:18 Updated: icingaweb2-vendor-JShrink-2.9.6-1.el7.icinga.noarch
Mar 09 13:03:18 Updated: icingaweb2-vendor-dompdf-2.9.6-1.el7.icinga.noarch
Mar 09 13:03:18 Updated: icingaweb2-vendor-lessphp-2.9.6-1.el7.icinga.noarch
Mar 09 13:03:19 Updated: icingaweb2-2.9.6-1.el7.icinga.noarch
Mar 09 13:03:31 Updated: icingaweb2-selinux-2.9.6-1.el7.icinga.noarch


```
![image](https://user-images.githubusercontent.com/34765193/157439715-1912c3c5-58cd-4de1-ba44-cd2f64d7f757.png)
![image](https://user-images.githubusercontent.com/34765193/157439837-2d31e919-ef03-4753-a740-4083ab8c753b.png)

Update: At Loaded Libraries I see the correct version : 0.7.0 and I just read that this module is no longer needed (https://github.com/Icinga/icingaweb2-module-ipl) I renamed it now to /usr/share/icingaweb2/modules/ipl-old and perhaps it's normal that it will stay in the list.

**Comment by nilmerg** [comment]
Ah, saw your update just now. You have Director v1.8.1, so you don't need the module at all.
