### ISSUE TITLE
icingaweb2 translation graphs

### ISSUE THREAD

**Issue by akqopensystems** [Icinga/icingaweb2#4701]
## Describe the bug
The translation is partly only complete. Some headings are in German and some in English. But all sub-items are then in German.

## Screenshots
![i_graph](https://user-images.githubusercontent.com/23358770/157865930-88b3b308-e67c-4b70-aa96-e8f8bcb146b8.PNG)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.6
* Web browser used: Firefox 91.6.0esr, 98.0
* Icinga 2 version used (`icinga2 --version`): 2.12.6
* PHP version used (`php --version`): 7.3.29
* Server operating system and version: RHEL-7.9

**Comment by nilmerg** [comment]
Hi,

translations are managed on https://translate.icinga.com. If you want to help, log in there and add the missing translations. ;)
