### ISSUE TITLE
Check now in quick actions not working

### ISSUE THREAD

**Issue by DasWiesel23** [Icinga/icingaweb2#4711]
## Describe the bug
The upper "Check Now" button is not working anymore on a service check. If you scroll down to "Check execution" and click on the Check now button at "Last check" it works.

## To Reproduce
Select a service, which you would like to have been checked immediately.  Try to press "Check now" right below the service. It will do nothing.

## Expected behavior
Click on the upper "Check now" button to get a service checked immediately. A small pop-up on the lower section of your screen should appear with "Scheduling check..."

## Screenshots
Using the following URL you'll see what section I mean in exact => https://ibb.co/2ydZ2L1

## Your Environment
Icinga Web 2 Version: 2.10.0
Git commit: f1dc03fd8553fe58ef85ca6fb607fe2922c3e078
PHP Version: 7.4.28
Git commit date: 2022-03-23
icinga2: r2.13.2-1
O/S: Debian 11

**Comment by moreamazingnick** [comment]
https://github.com/Icinga/icingaweb2/blob/f1dc03fd8553fe58ef85ca6fb607fe2922c3e078/modules/monitoring/application/views/scripts/partials/object/quick-actions.phtml#L46

`  <?php ($checkNowForm = clone $checkNowForm)->setName('quickAction_' . $checkNowForm->getName()); // Avoids id duplication ?>`

the quickAction prefix breaks something...

QUICKFIX:
after removing it, the button works again, but someone wanted to avoid duplicate ids for a reason.
`  <?php ($checkNowForm = clone $checkNowForm)->setName(/**'quickAction_' . **/$checkNowForm->getName()); // Avoids id duplication ?>`

**Comment by DasWiesel23** [comment]
Same issue on the "Remote Acknowledgement" button. After removing the quickAction prefix like on the Check Now one it works again.

https://github.com/Icinga/icingaweb2/blob/f1dc03fd8553fe58ef85ca6fb607fe2922c3e078/modules/monitoring/application/views/scripts/partials/object/quick-actions.phtml#L7
Changed to: `$removeAckForm->setName($removeAckForm->getName());`

**Comment by nilmerg** [comment]
Hi,

confirmed, thanks!
