### ISSUE TITLE
Dark Theme is shown for a second after login even if light theme is selected

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2#4713]
## Describe the bug
If I select the light theme as my user default theme, the dark theme is shown for a second directly after login.

## Screenshots
too fast for a screenshot

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.10
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.13.2
* PHP version used (`php --version`): 7.4
* Server operating system and version: Ubuntu 20.04

**Comment by nilmerg** [comment]
Hi,

the default is the dark theme. The theme or mode you chosen can only apply after you've identified yourself by logging in. This may take a while to load up, depending on the load/performance of the webserver. The same can happen if you change the mode or theme the first time in your preferences. It will get better once the cache hits, this should happen as soon as you're logging in the second time. This may depend on the lifetime of the cache though, which is stored in temp files on the server. If these get lost (by a restart or so) the same delay happens again for each user. This is nothing Icinga Web could solve.
