### ISSUE TITLE
Incorrect link for the unknown services counter in tactical view

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingaweb2#4714]
## Describe the bug
if you have no critical errors the tactical view shows the number of unknown in the circle of services.
If you then click the number you will get an empty list because it shows the list of critical services and not the unkown.
I think the service should be service_state=3 (now 2).

## To Reproduce
create a tactical view with only unknown errors and no critical errors and click on the number in the circle.

## Expected behavior
If the number in the circle is the unknown, then this also lists the unknown and not the critical in the details.
It should give the same if you clicked the unkown's link directly.

## Your Environment
Icinga Web 2 Version	2.10.0
Git commit	f1dc03fd8553fe58ef85ca6fb607fe2922c3e078
PHP Version	7.1.30
Git commit date	2022-03-23
icinga/icinga-php-library	0.8.0
icinga/icinga-php-thirdparty	0.10.0
Platform: Red Hat Enterprise Linux Server
Platform version: 7.9 (Maipo)
Kernel: Linux
Kernel version: 3.10.0-1160.53.1.el7.x86_64
Architecture: x86_64

**Comment by nilmerg** [comment]
Hi,

confirmed, thanks!
