### ISSUE TITLE
undefined method ipl\Html\HtmlElement::addHtml() in host and service pane after Update to 2.10.0

### ISSUE THREAD

**Issue by pb201** [Icinga/icingaweb2#4716]
After Update to 2.10 host and service pane show error
Uncaught Error: Call to undefined method ipl\Html\HtmlElement::addHtml() in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Widget/CustomVarTable.php:82
Stack trace:
#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Widget/CustomVarTable.php(191): Icinga\Module\Monitoring\Web\Widget\CustomVarTable->addRow()
#1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Widget/CustomVarTable.php(122): Icinga\Module\Monitoring\Web\Widget\CustomVarTable->renderScalar()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Widget/CustomVarTable.php(254): Icinga\Module\Monitoring\Web\Widget\CustomVarTable->renderVar()
#3 /usr/share/icingaweb2/modules/incubator/vendor/ipl/html/src/HtmlDocument.php(256): Icinga\Module\Monitoring\Web\Widget\CustomVarTable->assemble()
#4 /usr/share/icingaweb2/modules/incubator/vendor/ipl/html/src/BaseHtmlElement.php(209): ipl\Html\HtmlDocument->ensureAssembled()
#5 /usr/share/icingaweb2/modules/incubator/vendor/ipl/html/src/HtmlDocumen

![screenshot](https://user-images.githubusercontent.com/102286843/159875756-b93286ba-3281-45eb-9878-7ad2da5103f9.png)

Reinstalling icinga web did not solve the problem

**Comment by nilmerg** [comment]
Hi,

please show a screenshot of the about page.

**Comment by pb201** [comment]
Hi,

I have already attached one to the post.
Attached the same to this mail



Von: Johannes Meyer ***@***.***>
Gesendet: Donnerstag, 24. März 2022 09:51
An: Icinga/icingaweb2 ***@***.***>
Cc: Bernd Probst ***@***.***>; Author ***@***.***>
Betreff: Re: [Icinga/icingaweb2] undefined method ipl\Html\HtmlElement::addHtml() in host and service pane after Update to 2.10.0 (Issue #4716)


Hi,

please show a screenshot of the about page.

**Comment by nilmerg** [comment]
I asked you for a screenshot of the about page, not the traceback:
![Screenshot from 2022-03-24 10-12-03](https://user-images.githubusercontent.com/16668527/159882351-f9a04193-6107-4a3e-89bf-75053d1b3edf.png)

**Comment by pb201** [comment]
Sorry.
Here’s the screenshot of the About page

**Comment by nilmerg** [comment]
Email attachments seem not to be visible on Github..

**Comment by pb201** [comment]
![screenshot](https://user-images.githubusercontent.com/102286843/159887576-e85b497c-5167-4788-8a60-13d84874453c.png)

**Comment by nilmerg** [comment]
I expected this already: You have still installed the old ipl module. You don't need that anymore. The reactbundle module as well. You should also upgrade the director and incubator modules, they are heavily outdated.

**Comment by pb201** [comment]
updating of module incubator to v0.13.0 solved the problem
