### ISSUE TITLE
Contrast issues in the sidebar if the light mode is active

### ISSUE THREAD

**Issue by geotekberlin** [Icinga/icingaweb2#4720]
## Describe the bug
In the new white standard theme of V.2.10.0 readbility and contrast are poor, especially in the menu section which has grey characters on light grey/blueish background. The High Contrast theme is no suitable alternative, it should help visually impaired people and must neccecarily compromise design attractiveness to some extent. 

A good web design tries to minimize the number of different font sizes and appearances on a page. There is no reason to make the menu text color lighter (= less readable) than the body text.

## To Reproduce
Select white default theme of Icinga Web 2.10.0 and compare readability with previous versions on a calibrated monitor.

## To Solve
Set the menu text and symbol color from #777D7F to at least dark grey

## Expected behavior
The standard themes should follow accepted GUI design rules that combine good useability with an attractive visual appearance. The standard theme should not violate barrier-free web design rules.

## Screenshots
![Screenshot_2](https://user-images.githubusercontent.com/15341250/159881263-48b835ee-f8ca-4b18-971a-e05b81586d91.jpg)

## Your Environment
- Firefox Browser on hardware-calibrated sRGB graphic monitor
- Icinga Web 2.10.0 on Debian 11 updated via Icinga repository

## Additional context
- Useability ot the white default theme from V.2.9 was much better, in my opinion it was "Just Right"

**Comment by nilmerg** [comment]
@flourish86 Please comment.

**Comment by maggu** [comment]
If you save `public/css/icinga/legacy-theme.less` from Icinga Web 2.9, put it in `public/css/themes` on Icinga Web 2.10, and then change this:

```
  #header-logo-container {
    .var(background, icinga-blue);
  }
```
to this:
```
  #header-logo-container {
    background-color: @icinga-blue;
  }
```

and switch theme to "legacy-theme" in "My Account", you will have the legacy theme back.

Maybe just include it in Icinga 2.10?

**Comment by flourish86** [comment]
We're very proud of our new theme and the corresponding mode, but as in all 1.0 versions there will always be things to improve. So thanks for your feedback.

Some people found the contrast in the sidebar navigation too low, so we decided to increase that.

**Comment by maggu** [comment]
I changed the light theme body-bg-color to @white (#fff, same as for legacy), the menu-color to @black, and the menu-2ndlvl-color @black but 10% darker. Improved it quite a bit I think.
