### ISSUE TITLE
V.2.10 Overwrite of icon in collapsed sidebar not working anymore

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2#4725]
Hi all,
we have this snip in our custom theme to change the icon in the collapsed sidebar (changing the icon in the uncollapsed sidebar is still working):

```
#layout:not(.minimal-layout).sidebar-collapsed #header-logo {
    background-image: url('../img/company2/icon2_white.svg');
}
```
Unfortunately, Icingaweb does not submit this, the collapsed view still shows the icinga icon. Investigating with dev tools in the browser show

```
#layout:not(.minimal-layout).sidebar-collapsed #header-logo {
    background-image: url('../img/icinga-logo-compact.svg');
}
```

Cheers,
Marcus

**Comment by nilmerg** [comment]
Works fine for me:
![Screenshot from 2022-03-28 09-52-12](https://user-images.githubusercontent.com/16668527/160351789-f0e2f1cd-ca86-4583-9d50-cec7d83140f6.png)

Please ask in the forum for further assistance.
