### ISSUE TITLE
Preference changes of Theme / Theme Mode not working

### ISSUE THREAD

**Issue by nalkema** [Icinga/icingaweb2#4726]
When I try to change My Account -> Preferences -> Theme -> Icinga (default) or Theme mode from Dark to Light I get the following error :

![image](https://user-images.githubusercontent.com/34765193/160114534-11fbe849-d3fa-417e-964c-2e2a3d984e35.png)

## Your Environment

* Director: 1.8.1
* Icinga Web 2 version and modules (System - About): 2.10
* Web browser used: Firefox 98.0.1 (64-Bit)
* Icinga 2 version used : version: 2.13.2-1
* PHP version used (`php --version`): PHP 7.3.29 (cli) (built: Jul  1 2021 09:50:42) ( NTS )
* Server operating system and version: RHEL 7.9

**Comment by anmith** [comment]
+1
Icinga Web 2 Version: 2.10.0
PHP-Version: 7.4.28
Browser: Firefox 91.7.1esr (64-Bit) Windows / Microsoft Edge  99.0.1150.52 (Offizielles Build) (64-Bit)
OS: Debian 11.2

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Please see #4718. You have to switch to the database preference backend.

Cheers,
Eric
