### ISSUE TITLE
Pie charts look weird when Warning/Critical thresholds of 0 are specified

### ISSUE THREAD

**Issue by dasJ** [Icinga/icingaweb2#4727]
## Describe the bug

The pie charts generated from perfdata are weirdly cropped and are sometimes barely visible at all.

## To Reproduce

1. Have more than 2 pie charts per service
2. Have the service recover so it's on the dashboard

## Expected behavior

The diagrams should be readable

## Screenshots

![image](https://user-images.githubusercontent.com/4971975/160146195-39e84ee3-5602-48f0-b398-9d10728bca8d.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): `2.10.0`
* Web browser used: `Firefox 89.0.1`
* Icinga 2 version used (`icinga2 --version`): `Icinga 2.13.2`
* PHP version used (`php --version`): `8.0.17`
* Server operating system and version: `NixOS 21.11`

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll have a look. Can you please also share a screenshot of the about page?

Cheers,
Eric

**Comment by Virsacer** [comment]
Might be a cache issue. I have experienced something like this in the past.
Try to disable cache in developer tools and reload.

**Comment by nilmerg** [comment]
I also expect a caching issue. Looks fine on my end:
![Screenshot from 2022-03-28 09-26-53](https://user-images.githubusercontent.com/16668527/160347701-c072787d-c387-428a-94e9-a9cf4d7d025b.png)

**Comment by nilmerg** [comment]
@dasJ Is it solved by clearing the browser's cache or force reloading the browser? (shift+r, shift+f5, cmd+shift+r)

**Comment by dasJ** [comment]
Oh no, it looks like the perfdata is missing a `;` :((

**Comment by dasJ** [comment]
Still - I don't think this should escalate like this for 0 values.

**Comment by nilmerg** [comment]
Hm, no the perfdata is fine, it also looks still fine on my end:

**Chromium**
![Screenshot from 2022-03-31 08-48-50](https://user-images.githubusercontent.com/16668527/160993778-0b4c3bee-fe9e-4e3a-aae8-a31e793f03c2.png)

**Firefox**
![Screenshot from 2022-03-31 08-48-36](https://user-images.githubusercontent.com/16668527/160993745-14937c4b-fde4-4a4c-af69-381420871840.png)

If you already know how to use the inspector, are you able to pin-point a reason for the clipping?

**Comment by nilmerg** [comment]
We still have no similar reports. Neither here nor in the forums. Please re-open if you've found the cause and it's indeed Icinga Web 2.
