### ISSUE TITLE
Solarized Theme gone in new release

### ISSUE THREAD

**Issue by slalomsk8er** [Icinga/icingaweb2#4729]
## Describe the bug
After the upgrade to 2.10.0 the Solarized theme is gone and replaced with the new dark variant.

I use Solarized on dashboards hanging in different team bureaus and will have to answer all of them for why it will change.
There will be users that will come to me and ask, why I removed there theme!

Also I prefer Solarized as I like the colours better and perceive it as smoother and less harsh - OK, I'm biased as I also use it as my browser's, terminal's, editor's theme.

## To Reproduce

1. Upgrade to 1.20.0

## Expected behaviour
The Solarized theme was adapted to the new theme mode as it has a perfectly balanced out dark and light variant - one of the main reasons to use it besides pleasing choice of colours.

I don't expect official themes to vanish, on the contrary, I would expect them to grow in numbers.

**Comment by Virsacer** [comment]
You can download the theme from the previous version:
https://github.com/Icinga/icingaweb2/blob/v2.9.6/public/css/themes/solarized-dark.less

**Comment by nilmerg** [comment]
It is too similar to our new dark theme. That's why we removed it.

**Comment by slalomsk8er** [comment]
> It is too similar to our new dark theme. That's why we removed it.

Anything against me ripping of the old one and update it for the light/dark theme mode?

**Comment by nilmerg** [comment]
Of course not. It's all open-source.

**Comment by slalomsk8er** [comment]
Project started and right now a good start to restore the old solarized-dark theme.
Light/dark mode support is next on the TODO list.

https://exchange.icinga.com/slalomsk8er/Solarized%20Theme
