### ISSUE TITLE
Multi-Select not possible since update to version 2.10.0

### ISSUE THREAD

**Issue by ulfkosack** [Icinga/icingaweb2#4730]
## Describe the bug
After update to icingaweb2 2.10.0 via apt package you can't select multiple lines  via ctrl-key. So you can't execute actions on multiple hosts/services anymore.

## To Reproduce
Try to select multiple hosts or services in the standard dashboard.

## Expected behavior
select multiple hosts or services in every view of icingaweb2.

## Your Environment

* Icinga Web 2 version and modules (System - About):

```
Icinga Web 2 Version 	2.10.0
Git Commit 	f1dc03fd8553fe58ef85ca6fb607fe2922c3e078
PHP-Version 	7.4.28
Git Commit Datum 	2022-03-23
Get Icinga Support
Icinga Community
Einen Fehler melden
Icinga Dokumentation
Geladene Bibliotheken
icinga/icinga-php-library 	0.8.0
icinga/icinga-php-thirdparty 	0.10.0
Geladene Module
director 		1.8.0 	
fileshipper 		1.2.0 	
incubator 		0.6.0 	
ipl 		v0.5.0 	
monitoring 		2.10.0 	
nordlicht 		1.0.0 	
reactbundle 		0.9.0 	
spring 		0.0.1 	
Copyright © 2013-2022 Icinga GmbH 
```

* Web browser used: Firefox ESR 91.7.1, Chrome Version 99.0.4844.82, both also in private mode

* Icinga 2 version used (`icinga2 --version`):

icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.2-1)
```

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.13.19-6-pve
  Architecture: x86_64

Build information:
  Compiler: GNU 10.2.1
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
```

* PHP version used (`php --version`):

```
PHP 7.4.28 (cli) (built: Feb 17 2022 16:17:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.28, Copyright (c), by Zend Technologies
```

* Server operating system and version:

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

```

## Additional context
Installation is configured against PGSQL.

**Comment by mpounsett** [comment]
I'm seeing this as well, on Icingaweb 2.10.0 on Debian Bullseye.
Browser is Chrome 99.0.4844.83 on MacOS 12.1

The problem seems to be limited to the dashboard.

**Comment by Florian491** [comment]
I have the same problem after update via apt to version 2.10.0.
Also, I can no longer get to the overview page when I click on the host or service in the dashboard.
Under "Overview -> Host/Service" I get the overview page.

Web browser used:
Firefox 98.0.2 (64-Bit) & private mode too
Chrome Version 99.0.4844.82 (Offizieller Build) (64-Bit) & private mode too

Server operating system and version:
Distributor ID: Debian
Description: Debian GNU/Linux 11 (bullseye)
Release: 11
Codename: bullseye

**Comment by Virsacer** [comment]
This has been fixed: https://github.com/Icinga/icingaweb2/issues/4710
