### ISSUE TITLE
Check now button doesn’t work since update to version 2.10

### ISSUE THREAD

**Issue by Florian491** [Icinga/icingaweb2#4731]
## Describe the bug
After updating via the repository (apt) to 2.10.0, the "Check now" button under host / service check no longer works.
The "Check now" button under "Check execution" works fine.

## To Reproduce
At the top of the host or service check, click "Check now"

## Expected behavior
Check-Status will be renewed 

## Screenshots
**Does not work:**
![check_now1](https://user-images.githubusercontent.com/102486317/160299505-629077da-1280-41da-825f-b4e53790b8db.JPG)
**Works fine:**
![check_now2](https://user-images.githubusercontent.com/102486317/160299522-6ac90ea6-c5d1-4d14-a0ec-1c8b27a40aae.JPG)

## Your Environment
* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version 	2.10.0
Git commit 	f1dc03fd8553fe58ef85ca6fb607fe2922c3e078
PHP Version 	7.4.28
Git commit date 	2022-03-23
Loaded Libraries
icinga/icinga-php-library 	0.8.0
icinga/icinga-php-thirdparty 	0.10.0
Loaded Modules
director 		master
incubator 		0.13.0
ipl 		v0.5.0
monitoring 		2.10.0
reactbundle 		0.9.0

* Web browser used:
Firefox 98.0.2 (64-Bit) & private mode too
Chrome Version 99.0.4844.82 (Offizieller Build) (64-Bit) & private mode too

* Icinga 2 version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.2-1)
System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.10.0-13-amd64
  Architecture: x86_64
Build information:
  Compiler: GNU 10.2.1
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022

* PHP version used (`php --version`):
PHP 7.4.28 (cli) (built: Feb 17 2022 16:17:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.28, Copyright (c), by Zend Technologies

* Server operating system and version:
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

## Additional context

**Comment by Virsacer** [comment]
This has been fixed: https://github.com/Icinga/icingaweb2/issues/4711
