### ISSUE TITLE
Translation / Language not worked since 2.10

### ISSUE THREAD

**Issue by Florian491** [Icinga/icingaweb2#4733]
## Describe the bug
The Language under User is set to German, but the Icingaweb2 website is displayed in English.
However, the Icinga-Director is displayed in German.

## To Reproduce
Change the Language under User -> My Account -> Your Current Language

## Expected behavior
The system interface should be displayed in the set language.

## Screenshots
![lang1](https://user-images.githubusercontent.com/102486317/160356556-1ddb5444-a1bf-4017-9bd5-5eb57ee0c63c.JPG)
![lang2](https://user-images.githubusercontent.com/102486317/160356560-1f61ac6d-6b1b-45dd-ac00-0c842ebe0b48.JPG)
![lang3](https://user-images.githubusercontent.com/102486317/160357594-c0229a9b-0c95-41b5-9b96-566db02e14c7.JPG)

## Your Environment
* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version 	2.10.0
Git commit 	f1dc03fd8553fe58ef85ca6fb607fe2922c3e078
PHP Version 	7.4.28
Git commit date 	2022-03-23
Loaded Libraries
icinga/icinga-php-library 	0.8.0
icinga/icinga-php-thirdparty 	0.10.0
Loaded Modules
director 		master
incubator 		0.13.0
ipl 		v0.5.0
monitoring 		2.10.0
reactbundle 		0.9.0

* Web browser used:
Firefox 98.0.2 (64-Bit) & private mode too
Chrome Version 99.0.4844.82 (Offizieller Build) (64-Bit) & private mode too

* Icinga 2 version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.2-1)
System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.10.0-13-amd64
  Architecture: x86_64
Build information:
  Compiler: GNU 10.2.1
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022

* PHP version used (`php --version`):
PHP 7.4.28 (cli) (built: Feb 17 2022 16:17:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.28, Copyright (c), by Zend Technologies

* Server operating system and version:
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

## Additional context
System Language: LANG=de_DE.UTF-8

**Comment by nilmerg** [comment]
Hi,

have you installed icinga-l10n?

**Comment by Florian491** [comment]
Hi, thank you, no, that was not installed.
I have installed it now and the translation works, it's very strange that it wasn't installed.

Can this be included under "Translation Module Installation"?
https://icinga.com/docs/icinga-web-2/latest/modules/translation/doc/02-Installation/

**Comment by nilmerg** [comment]
The translation module is not for end-users. icinga-l10n is an optional dependency of the icingaweb2 package. Just like the monitoring module. If you've got the latter, I don't know why you don't got icinga-l10n installed.
