### ISSUE TITLE
comments missing umlauts or cube module fails

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2#4738]
According to [https://github.com/Icinga/icingaweb2/issues/4035#issuecomment-573577438](comment) "The IDO's resource option charset must be set to latin1 for umlauts to work correctly."

## Describe the bug
Comments show no umlauts.

## To Reproduce

1. set charset in resource to utf8 
2. umlauts are there but cube module throws exception
3. set charset empty
4. umlauts in comments are gone, cube module works, umlauts in names are strange <?>, icingaweb2 crashes
5. set charset in resource to latin1
6. umlauts in comments are gone, cube module works, umlauts in names are strange <?>, icingaweb2 crashes

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.10-master
* ido-mysql
* cube 1.2.0
* Web browser used: chrome
* Icinga 2 version used (`icinga2 --version`): 2.13.2
* PHP version used (`php --version`): 7.4
* Server operating system and version: ubuntu 20.04

## Additional context

edit: tried out cube module 1.1.0 -> no error with utf8

cube module 1.2.0 exception, after picking a dimension:
```
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8', query was: SELECT rollup.`application`, rollup.`hosts_cnt`, rollup.`hosts_down`, rollup.`hosts_unhandled_down`, rollup.`hosts_unreachable`, rollup.`hosts_unhandled_unreachable` FROM (SELECT sub.`application`, SUM(hosts_cnt) AS hosts_cnt, SUM(hosts_down) AS hosts_down, SUM(hosts_unhandled_down) AS hosts_unhandled_down, SUM(hosts_unreachable) AS hosts_unreachable, SUM(hosts_unhandled_unreachable) AS hosts_unhandled_unreachable FROM (SELECT `c_application`.`varvalue` AS `application`, SUM(CASE WHEN hs.has_been_checked = 1 THEN 1 ELSE 0 END) AS `hosts_cnt`, SUM(CASE WHEN hs.has_been_checked = 1 AND hs.current_state = 1 THEN 1 ELSE 0 END) AS `hosts_down`, SUM(CASE WHEN hs.has_been_checked = 1 AND hs.current_state = 1 AND hs.problem_has_been_acknowledged = 0 AND hs.scheduled_downtime_depth = 0 THEN 1 ELSE 0 END) AS `hosts_unhandled_down`, SUM(CASE WHEN hs.current_state = 2 THEN 1 ELSE 0 END) AS `hosts_unreachable`, SUM(CASE WHEN hs.current_state = 2 AND hs.problem_has_been_acknowledged = 0 AND hs.scheduled_downtime_depth = 0 THEN 1 ELSE 0 END) AS `hosts_unhandled_unreachable` FROM icinga_objects AS ho
INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
LEFT JOIN icinga_customvariablestatus AS `c_application` ON `c_application`.varname = 'application' COLLATE latin1_general_ci AND `c_application`.object_id = ho.object_id GROUP BY `c_application`.varvalue) AS sub GROUP BY (`application`) WITH ROLLUP) AS rollup ORDER BY (rollup.`application` IS NOT NULL) ASC, rollup.`application` ASC, (rollup.`hosts_cnt` IS NOT NULL) ASC, rollup.`hosts_cnt` ASC, (rollup.`hosts_down` IS NOT NULL) ASC, rollup.`hosts_down` ASC, (rollup.`hosts_unhandled_down` IS NOT NULL) ASC, rollup.`hosts_unhandled_down` ASC, (rollup.`hosts_unreachable` IS NOT NULL) ASC, rollup.`hosts_unreachable` ASC, (rollup.`hosts_unhandled_unreachable` IS NOT NULL) ASC, rollup.`hosts_unhandled_unreachable` ASC

SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'latin1_general_ci' is not valid for CHARACTER SET 'utf8'
```

**Comment by nilmerg** [comment]
The charset and collation of the icinga2 schema is in various places hardcoded. And latin1. Did you change that manually to utf8?

**Comment by moreamazingnick** [comment]
I left it blank, but changes it to utf8 because to debug behavour on a different machine
I think umlauts have been working previously with blank charset entry

now it only works with utf8, blank hides the umlauts

I patched the cube module and removed the latin1 part
https://github.com/Icinga/icingaweb2-module-cube/blob/487e426f123db46dc6d9ddaf49a6055a2cd68fc9/library/Cube/Ido/CustomVarDimension.php#L147
 
now the cube module works as axpected

**Comment by nilmerg** [comment]
It's hardcoded to latin1 in the [schema](https://github.com/Icinga/icinga2/blob/master/lib/db_ido_mysql/schema/mysql.sql#L360), that's why it's hardcoded in the query. Only versions of Icinga Web earlier than 2.9 also require it in the resource. The cube module doesn't need to be patched either.

I think you've changed the schema's encoding somehow. This is not supported. Revert it back to latin1 and everything is fine.

**Comment by moreamazingnick** [comment]
"Revert it back to latin1 and everything is fine." -> I did but umlauts are still gone for old and new comments

**Comment by moreamazingnick** [comment]
now i made sure that the ido database is in latin1 too.
ALTER DATABASE icinga2 CHARACTER SET latin1 COLLATE latin1_swedish_ci;

same issue:
empty charset => umlauts there, cube broken
utf-8 => umlaute there, cube broken
latin1 => umlauts gone, cube ok broken

**Comment by moreamazingnick** [comment]
i recreated the hole icinga ido db left charset blank-> umlauts still gone, but cube module works

**Comment by nilmerg** [comment]
I've tried it myself now. I'm **really** sure it worked in the past. But it doesn't now. There seems something wrong with Icinga 2 and how it's handling the input. We'll look further into it and let you know how we proceed.

**Comment by moreamazingnick** [comment]
there is something new:
icingaweb2 behaves different if
1) charset = ""
    umlauts work, cube 1.2 broken, cube 1.1.1 works fine
2) charset missing in resource ini
    umlauts are <?> cube 1.2 broken, cube 1.1.1 works fine

if you safe charset empty the entry is missing in resource ini

**Comment by nilmerg** [comment]
I've opened https://github.com/Icinga/icinga2/issues/9308.
