### ISSUE TITLE
QuickAction "Check now" stopped working in 2.10.0

### ISSUE THREAD

**Issue by abaumgaertner** [Icinga/icingaweb2#4742]
## Describe the bug
Quick Action "Check now" (top of the page) stopped working after upgrading icingaweb2 to v2.10.0

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. open a host / service
2. click on Check now (top of the page)
3. no reschedule happens
4. click on Check now (in section check execution / last check)
5. reschedule happens

## Expected behavior
rescheduled check

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.10.0
* Web browser used: Firefox 98.0.2
* Icinga 2 version used (`icinga2 --version`): 2.10.7
* PHP version used (`php --version`): rh-php73 7.3.20-1.el7 
* Server operating system and version: Oracle Linux Server 7.9

## Additional context
Difference seems to be in submitted form data: formUID

Check now - top of the page
formUID: quickAction_IcingaModuleMonitoringFormsCommandObjectCheckNowCommandForm
btn_submit: Check+now

Check now in section check execution - last check
formUID: IcingaModuleMonitoringFormsCommandObjectCheckNowCommandForm
btn_submit: Check+now

**Comment by lippserd** [comment]
#4711

**Comment by Napsty** [comment]
Can confirm, since upgrade to 2.10.0.

Top "Check Now" link executes the following POST:

```
--data-raw 'formUID=quickAction_IcingaModuleMonitoringFormsCommandObjectCheckNowCommandForm&CSRFToken=228950612%7C87cb0d215695ba7ef2f0f62e8a398b86f4a24439a29027a3b5ff776a84310cbf&btn_submit=Check+now'
```

The lower and working "check now" link uses different data in the POST:

```
--data-raw 'formUID=IcingaModuleMonitoringFormsCommandObjectCheckNowCommandForm&CSRFToken=116553135%7Ce67ef409f49a5cd660346fe02ffdc3e7a354a47484e93f42285a2ccf8ddfa3bf&btn_submit=Check+now'
```
