### ISSUE TITLE
Theme Mode switch disabled on theme with dark/light

### ISSUE THREAD

**Issue by Virsacer** [Icinga/icingaweb2#4744]
## Describe the bug
Apparently the fix for https://github.com/Icinga/icingaweb2/issues/4723 went to far:
Now the Theme Mode switch is always disabled when the global theme does not have dark/light.

## To Reproduce
1. Set a theme globally that does not have dark/light
2. Set a theme in the user settings that does have dark/light

## Expected behavior
The Theme Mode switch should be enabled when the user-selected theme does have dark/light and it should be disabled when the user-selected theme does not have dark/light

## Screenshots
![image](https://user-images.githubusercontent.com/8797510/162047384-813af9ce-6989-4046-9c73-cf6f41cff1e7.png)

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.10.1
* Web browser used: Firefox 100.0b1
* Icinga 2 version used (`icinga2 --version`): 2.13.2-1
* PHP version used (`php --version`): 8.0.8
* Server operating system and version: Ubuntu 21.10

**Comment by nilmerg** [comment]
Aye... but only if the default theme is chosen. Other themes with mode support are not affected.
