### ISSUE TITLE
No unhandled display after the hostname

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingaweb2#4749]
## Describe the bug
In the list of hosts he no longer gives the unhandled services after the hostname

IcingaWeb 2.9.5 -> hostname.com (4 unhandled services)

IcingaWeb 2.10.1 -> hostname.com          -> There is no message of the unhandled services

## To Reproduce
find a host with service errors and look at the list of hosts.
Or take the overview->hosts and there is no host with an 'unhandled service'

## Expected behavior
That there is a display of 'unhandled services' after the hostname.

## Your Environment

Icinga Web 2 Version	2.10.1
Git commit	974729a6421c17fdb8bb1931623107cf6a90fc7e
PHP Version	7.1.30
Git commit date	2022-04-06
Get Icinga Support
Icinga Community
Report a bug
Icinga Documentation
Loaded Libraries
icinga/icinga-php-library	0.8.0
icinga/icinga-php-thirdparty	0.10.0
Loaded Modules
grafana		1.4.2	Configure
map		1.1.0	Configure
monitoring		2.10.1	Configure

**Comment by nilmerg** [comment]
Hi,

this has been dropped (#4660) due to various technical limitations and issues.
