### ISSUE TITLE
Link to filter for host/service state leads to "invalid filter"

### ISSUE THREAD

**Issue by episodeiv** [Icinga/icingaweb2#4751]
## Describe the bug
Selecting multiple hosts or services and clicking the "List [n] services/hosts which are currently in state [y]" badges (see screenshot below) leads to an error message complaining of an invalid filter.

For services, the links point to

`icingaweb2/monitoring/list/services?service_problem=1&sort=service_severity#!/icingaweb2/monitoring/list/services?service_state=2&service_handled=0&(&((service=servicename1&host=host1)|(service=servicename2&host=host2)))
`
Resulting in the error message
`unexpected & at pos 36: level 1`

For hosts, the links point to

`icingaweb2/dashboard#!/icingaweb2/monitoring/list/hosts?host_state=1&host_handled=0&(&((host=host1)|(host=host2)))`
Resulting in the error message
`unexpected & at pos 30: level 1`

## To Reproduce
Select multiple hosts or services and click 
![image](https://user-images.githubusercontent.com/1003620/163421825-5634962e-d744-4cb6-bf67-4178d9877c96.png)

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.10.1
* Web browser used: Firefox Nightly
* Icinga 2 version used (`icinga2 --version`): r2.13.3-1
* PHP version used (`php --version`): 7.4.28
* Server operating system and version: debian-11.3

**Comment by nilmerg** [comment]
Hi,

thanks for reporting!
