### ISSUE TITLE
Notifications on mobile don't use the available width

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#4756]
## Describe the bug
![Screenshot from 2022-04-25 13-33-09](https://user-images.githubusercontent.com/16668527/165081120-e45767f9-a548-4dab-b1d8-7366d837aae2.png)

This applies to all notifications.

**Comment by nilmerg** [comment]
Well, I thought I've had this while on master, but no. It's only the case while on #4697. I'll leave the issue open, saves Github another comment. :sweat_smile:

**Comment by flourish86** [comment]
Fixed by c17234b, so I’ll close
