### ISSUE TITLE
Uncaught TypeError: Return value of Icinga\\Module\\Setup\\RequirementSet::key() must be of the type int, null returned

### ISSUE THREAD

**Issue by jsielemann** [Icinga/icingaweb2#4767]
## Describe the bug
Setup fails at point of checking requirements with the error-message (please see attached screenshot)

## To Reproduce
1. set up php-fpm7.4, create a virtual host with apache
2. install icingaweb2 from git-repo
3. launch the site
4. create the setup token
5. enter it and choose only monitoring at step 2 "modules"
6. continue to step "requirements"

## Expected behavior
Installation will continue

## Screenshots
![2022-05-02_22-38](https://user-images.githubusercontent.com/4294994/166324648-8b771980-a822-4f9f-b537-f8060e08a727.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): **2.10.1**
* Web browser used: **Firefox 91.7.1esr**
* Icinga 2 version used (`icinga2 --version`): **r2.13.3-1**
* PHP version used (`php --version`): **7.4.28**
* Server operating system and version: **Gentoo**

## Additional context
I switched from the portage-version of icingaweb2 because my CSS broke completely. As I later found out, it may be caused by an old version of dev-libs/icinga-php-library-0.6. I removed it and installed 0.8 from the git-repo.
```
# VHost-File
<VirtualHost _default_:443>

        ServerName icinga.xxxxxxxx.net
        DocumentRoot "/usr/share/icingaweb2/public"

        SSLEngine on
        SSLHonorCipherOrder On
        SSLProtocol ALL -SSLv2 -SSLv3
        SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128:AES256:HIGH:!RC4:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK
        SSLCertificateFile /etc/letsencrypt/live/icinga.xxxxxxx/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/icinga.xxxxxxxx/privkey.pem

        ErrorLog /var/log/apache2/icingaweb2_error.log
        LogLevel info
        LogFormat "%h %l %u %t \"%r\" %>s %b" common
        CustomLog /var/log/apache2/icingaweb2_access.log        common

<Directory "/usr/share/icingaweb2/public">
    Options SymLinksIfOwnerMatch
    AllowOverride None

    DirectoryIndex index.php

    <IfModule mod_authz_core.c>
        # Apache 2.4
        <RequireAll>
            Require all granted
        </RequireAll>
    </IfModule>

    <IfModule !mod_authz_core.c>
        # Apache 2.2
        Order allow,deny
        Allow from all
    </IfModule>

    SetEnv ICINGAWEB_CONFIGDIR "/etc/icingaweb2"

    EnableSendfile Off

    <IfModule mod_rewrite.c>
        RewriteEngine on
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} -s [OR]
        RewriteCond %{REQUEST_FILENAME} -l [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^.*$ - [NC,L]
        RewriteRule ^.*$ index.php [NC,L]
    </IfModule>

    <IfModule !mod_rewrite.c>
        DirectoryIndex error_norewrite.html
        ErrorDocument 404 /icingaweb2/error_norewrite.html
    </IfModule>

        # Forward PHP requests to FPM
        SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
        <FilesMatch "\.(php|phtml)$">
            SetHandler "proxy:fcgi://127.0.0.1:9004"
            ErrorDocument 503 /icingaweb2/error_unavailable.html
        </FilesMatch>
</Directory>
</VirtualHost>
```

**Comment by jsielemann** [comment]
I workarounded my problem by installing an older version of icingaweb2 and update the php-library to 0.8

**Comment by nilmerg** [comment]
That's one solution for sure, but not one that resolves this issue ;)

**Comment by jsielemann** [comment]
Yes, you're right. I can try to reproduce the issue and solve it with your support! I would also love to have the newest version up and running. How can I support you?

**Comment by nilmerg** [comment]
I'd just need one thing: Which modules have you chosen?

**Comment by jsielemann** [comment]
At the time of the error, I only used monitoring
