### ISSUE TITLE
icinga web 2 for centos 8 is out of date

### ISSUE THREAD

**Issue by emiliencartesoft** [Icinga/icingaweb2#4771]
## Describe the bug
Icinga web 2 version 2.10 is not available for centos 8.

Is it possible to update the packages icinga web 2 for centos 8? Thank you.

## To Reproduce
As you can see, there is no package for the version 2.10 here: https://packages.icinga.com/centos/8/release/noarch/icingaweb2/

Same result with yum info:
```
$ yum info icingaweb2
Last metadata expiration check: 0:08:59 ago on Wed 04 May 2022 11:41:42 AM CEST.
Available Packages
Name         : icingaweb2
Version      : 2.9.5
Release      : 1.el8.icinga
Architecture : noarch
Size         : 6.0 M
Source       : icingaweb2-2.9.5-1.el8.icinga.src.rpm
Repository   : icinga-stable-release
Summary      : Icinga Web 2
URL          : https://icinga.com
License      : GPLv2+ and MIT and BSD
Description  : Icinga Web 2
```

## Expected behavior
To have the latest version of icinga web 2 for centos 8

## Screenshots
N/A

## Your Environment
N/A

## Additional context
N/A

**Comment by lippserd** [comment]
Hi,

CentOS 8 is EOL. Please also have a look [here](https://icinga.com/subscription/support-matrix).

All the best,
Eric
