### ISSUE TITLE
Role not including AD group members in audit view when more than one auth backend configured

### ISSUE THREAD

**Issue by mlindsay1977** [Icinga/icingaweb2#4788]
**Describe the bug**

When multiple backend providers are configured and roles contain AD groups the user is only checked against the first configured backend (icinga2_db in my case). Debug logs show then following when an AD username  (bob@FAKEDOMAIN) is inspected in the Configuration->Access Control-> Audit screen:

2022-05-18T11:52:55-04:00 - DEBUG - No groups found in backend "icingaweb2" which the user "bob@FAKEDOMAIN" is a member of.

No other attempts are made to look the user up.

If you delete the other backends (both user and group resources, again icingaweb2 in my case which is a DB backend) then the audit check succeeds and the role permissions that the AD group is assigned to appear correctly and the user can log in.

If you leave both configured, then the only way the role perms and user auth works is if you add the user to a DB group and add that group to a role. Then the audit does work as it can find the AD user in the DB configured resource.

**Not working:**

_authentication.ini_
[icingaweb2]
backend = "db"
resource = "icingaweb_db"

[ldap_backend_users]
resource = "icingaweb_ldap_fakedomain"
user_class = "user"
filter = "&(objectClass=user)(|((memberOf:1.2.840.113556.1.4.1941:=CN=Icinga Users,OU=Icinga,OU=User Groups,DC=fake,DC=domain))"
user_name_attribute = "sAMAccountName"
backend = "ldap"
base_dn = "DC=fake,DC=domain"
domain = "FAKEDOMAIN"

_group.ini_
[icingaweb2]
backend = "db"
resource = "icingaweb_db"

[ldap_backend_groups]
resource = "icingaweb_ldap_fakedomain"
user_backend = "ldap_backend_users"
group_class = "group"
group_name_attribute = "cn"
group_member_attribute = "member"
base_dn = "DC=fake,DC=domain"
backend = "ldap"
group_filter = "|(cn=Operators)(CN=Read Only Users)(CN=SysAdmins)"

**Working:**

_authentication.ini_
[ldap_backend_users]
resource = "icingaweb_ldap_fakedomain"
user_class = "user"
filter = "&(objectClass=user)(|((memberOf:1.2.840.113556.1.4.1941:=CN=Icinga Users,OU=Icinga,OU=User Groups,DC=fake,DC=domain))"
user_name_attribute = "sAMAccountName"
backend = "ldap"
base_dn = "DC=fake,DC=domain"
domain = "FAKEDOMAIN"

_group.ini_
[ldap_backend_groups]
resource = "icingaweb_ldap_fakedomain"
user_backend = "ldap_backend_users"
group_class = "group"
group_name_attribute = "cn"
group_member_attribute = "member"
base_dn = "DC=cfake,DC=domain"
backend = "ldap"
group_filter = "|(cn=Operators)(CN=Read Only Users)(CN=SysAdmins)"

_roles.ini (unchanged in testing)_
[Administrators]
users = "admin"
permissions = "*"
groups = "Administrators, SysAdmins@FAKEDOMAIN"

[Maintenance]
permissions = "application/announcements,application/log,module/doc,monitoring/*,module/monitoring,pnp/*,module/pnp"
groups = "Operators@FAKEDOMAIN"
unrestricted = "1"

[RO Users]
permissions = "application/announcements,module/monitoring,module/pnp"
groups = "Read Only Users@FAKEDOMAIN"

**Include as many relevant details about the environment you experienced the problem in**

  
	Icinga Web 2 Version 2.9.5
	Git commit 053971c99dc1a4510beb64a888ea695cc14032dc
	PHP Version 7.4.19
	AlamLinux 8
	
	Loaded Libraries
	icinga/icinga-php-library 	0.7.0
	icinga/icinga-php-thirdparty 	0.10.0

	Loaded Modules
	director 	1.9.0
	doc 	2.9.5
	fileshipper 	1.2.0
	incubator 	0.12.0
	monitoring 	2.9.5
	pnp 	1.1.0
	vsphere 	1.1.1

**Comment by nilmerg** [comment]
Hi,

I don't think this is a bug. You have linked the user backend `ldap_backend_users` and the group backend `ldap_backend_groups`. This has the effect that the group backend is only asked for memberships if the user has been authenticated by the user backend.

I guess you see this issue only in the Audit view. There you have to choose a suggestion in the dropdown in order to also choose the backend the user should be authenticated by. If you just push enter, the first user backend is assumed. In this case `icingaweb2` which isn't the user backend that's linked to `ldap_backend_groups`.

**Comment by mlindsay1977** [comment]
sorry been swamped and just got back to this

I actually see this behaviour on login as well, but it was easier to see and document in audit mode. When logging in the user is authenticated just fine but since the group is only checked against the first configured source the ad user isn't found and we are presented with a empty dashboard as expected with an unconfigured user. If I log in with a db user then things work as expected. If I delete the first group backend (db) then the AD user is checked against the AD group and the assigned permissions work.

Cheers,
Mike

**Comment by nilmerg** [comment]
During login this works fine for me. Unless `doma.in` is the default domain, note that to authenticate as a user from the backend that has a domain, you need to append the domain to the username manually. (`admin@doma.in`)

Though, the audit view does not offer suggestions from such a domain-aware backend correctly. This is the current effect that by choosing a user from such a backend, the groups are not correctly applied even if a suggestion is chosen.
