### ISSUE TITLE
Sort by name of roles does not work properly

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2#4789]
## Describe the bug
Sort by name of roles does not work properly, sorting by other columns works fine.

## To Reproduce
1. Create some roles
2. Look at the default list and it will not be in order by name as the view suggests.
3. Switch set sort to another columns and it will be properly sorted
4. Switch back to sort by name and it will be again not ordered but differ then the initial order

## Expected behavior
Sort by name works, so its easier to find roles without search.

## Screenshots
Not allowed to take a screenshot from this environment because of the LDAP groups.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.6 / 2.10.2
* Web browser used: Edge, Firefox, Chrome
* PHP version used (`php --version`): 7.4.19
* Server operating system and version: RHEL 8

**Comment by nilmerg** [comment]
This is due to roles being stored on disk. The current implementation for this is deprecated though. A near future update will change this to database storage and this issue disappears naturally. So I'm closing here.

**Comment by Nathaniel-Donahue** [comment]
Hi,
in which version will this fix be available? Or is it already implemented?

regards,
Nathaniel

**Comment by nilmerg** [comment]
There will be no *fix*. The storage type change is in-progress and should be finished with v2.12 or v2.13.

**Comment by nilmerg** [comment]
This broke with v2.9.0 (#4349), I'm sorry.
