### ISSUE TITLE
Restore solarized-dark theme

### ISSUE THREAD

**Issue by deric** [Icinga/icingaweb2#4816]
Could you please restore `solarized-dark` theme? It was removed here #4688 with not much explanation.

Solarized themes use carefully selected contrast colors, which is something you can't say about the "new dark" theme.

It might be a matter of taste, but is there an issue in having multiple flavors of dark theme?

**Comment by nilmerg** [comment]
Is has been removed because we have no intention to maintain a theme that has a similar flavor and is not ours.

If you wan't the solarized flavor back, install the [community fork](https://exchange.icinga.com/slalomsk8er/Solarized%20Theme).
