### ISSUE TITLE
Icingaweb2 - why does adding a user to a group reduce their access?

### ISSUE THREAD

**Issue by gettoknowmii** [Icinga/icingaweb2#4828]
We have configured icinga to use LDAP for authentication. We have an Admin LDAP group. 
If I add myself to that admin ldap group, i get admin access to icinga. However if i add myself to that admin ldap group and another ldap group (i;e dba) - i only get access for the DBA group

I did some tests
test1. added myself to the ldap group(admin_users) that grants admin access to icinga
results: everything works as expected.

test2: added my self to 3 ldap groups EXCEPT 'admin_user' which is the admin group.
results: icinga properly assigned all the inherited permissions from the groups to my user

test2: added my self to 3 ldap groups PLUS 'admin_user' which is the admin group.
results: icinga properly assigned all the inherited permissions from the 3 groups BUT fails to inherited and assign to my user the admin permissions from the 'admin_user' group

in essence, it seems like one can not be a member of admin_user group and a member of any other group. in other to get full admin access to icinga, you have to be a member of just the admin_user group. 

This seems entirely wrong.

**Comment by nilmerg** [comment]
> i only get access for the DBA group

What does *access* mean? Do you mean permissions (such as command permissions) or restrictions? (such as `monitoring/filter/objects`)

Permissions of the administrative role must not be ignored, unless denied. I'm not aware of any issues in this regard.

Restrictions reduce access to data. A role (even if administrative) having no restriction does not allow access to all data however. If this is desired, the unrestricted flag must be turned on in a role.
