### ISSUE TITLE
Reload animation does not stop in global search view

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingaweb2#4834]
## To Reproduce
1. Search for something using the field in the sidebar.
2. Click the reload button at the top of the page.
3. Observe that the page contents are updated but the reload animation never stops.

## Expected behavior
Reload animation should stop after updating the page.

## Screenshots
https://user-images.githubusercontent.com/18552/175885596-ff1bed15-99fe-4ab6-b580-46727b49753a.mp4

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): d5d714b1eeb7c3cfb5893afef673579f3ad078b4
* Web browser used: Firefox 101.0.1 on Linux
* Server operating system and version: latest `icinga/icingaweb2:master` Docker image (`c47f206c8493f360423de5acf2ee15298f45538ce18870dd03ea1cb2b050f2d4`)

**Comment by nilmerg** [comment]
I can't reproduce that, neither with Chromium nor with Firefox (same version)

**Comment by julianbrost** [comment]
Strange, I can also reproduce it with Chromium (103.0.5060.53). Developer tools shows no errors in the console and no pending requests. Is there anything else I can check?
