### ISSUE TITLE
Installation on Ubuntu 22.04 throwing deprecated warnings

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icingaweb2#4849]
## Describe the bug
during the web installer  it throws some deprecated warnings

## To Reproduce
Run the web installer on a freshly installed Ubuntu 22.04

## Expected behavior
No warnings are thrown by php

## Screenshots
![grafik](https://user-images.githubusercontent.com/6574967/176835884-bee5947b-e9b8-4597-b0be-ed788bb6112b.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.11.0-1.jammy
* Web browser used: FireFox
* Icinga 2 version used (`icinga2 --version`): r2.13.4-1
* PHP version used (`php --version`): PHP 8.1.2 (cli) (built: Jun 13 2022 13:52:54) (NTS)
* Server operating system and version: Ubuntu 22.04

**Comment by nilmerg** [comment]
Yeah, thanks for the report. Happens once a module is chosen that does not provide its own wizard. Though, the installation can be continued and finished successfully.

Some modules may not be successfully enabled though, but that's a [different](https://github.com/Icinga/icingaweb2/issues/4850) issue. :roll_eyes:

**Comment by sebastic** [comment]
This patch prevents the deprecation warning:
```diff
--- a/library/Icinga/Application/Modules/Module.php
+++ b/library/Icinga/Application/Modules/Module.php
@@ -1036,7 +1036,7 @@ class Module
     public function providesSetupWizard()
     {
         $this->launchConfigScript();
-        if (class_exists($this->setupWizard)) {
+        if (!is_null($this->setupWizard) && class_exists($this->setupWizard)) {
             $wizard = new $this->setupWizard;
             return $wizard instanceof SetupWizard;
         }
```
