### ISSUE TITLE
wrong time in history overview

### ISSUE THREAD

**Issue by SharkPie** [Icinga/icingaweb2#4853]
## Describe the bug
History of services is showing the same time in the overview. In the detailed view the displayed times are correct.

## To Reproduce
Choose host -> service -> history -> all times are the same.
Click on a single entry in history and the correct time is shown with the details.

## Expected behavior
Correct times in the overview

## Screenshots
![icingaweb2](https://user-images.githubusercontent.com/7884051/176909962-a88e4ff0-ab3c-49ea-a5ab-ed140148a396.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):  Icinga Web 2 Version | 2.11.0
* Web browser used: Firefox and Chrome current versions
* Icinga 2 version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.4-1)
* PHP version used (`php --version`): PHP 7.4.28 (cli) (built: Feb 17 2022 16:17:19) ( NTS )
* Server operating system and version: System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.10.0-8-amd64
  Architecture: x86_64

## Additional context
-

**Comment by nilmerg** [comment]
I'm sorry to hear that, and thanks for reporting. Will be fixed asap :)

**Comment by adriangalbincea** [comment]
I can confirm that I have the same issue.
![ice_screenshot_20220703-083332](https://user-images.githubusercontent.com/53899277/177030063-dd1c02ca-1708-47a1-bcb1-c373756da20a.jpeg)
![ice_screenshot_20220703-083600](https://user-images.githubusercontent.com/53899277/177030066-e6386893-7c49-4525-b777-de7f537ab9df.jpeg)
