### ISSUE TITLE
environment_id should be a resource got string instead

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingaweb2#4857]
## Describe the bug
when I open the page /icingaweb2/icingadb/hosts or /icingaweb2/icingadb/services I keep getting the error 'environment_id should be a resource got string instead'

The service rh-php73-php-fpm.service say
UnexpectedValueException in /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Behavior/Binary.php:37 with message: environment_id should be a resource got string instead

i recreate the icinga & icingadb database from scratch. No Change.

I upgrade from icingaweb2 2.10.3 with rh-php72-php-fpm.

Did i forget something ? 

## To Reproduce
Open the page /icingaweb2/icingadb/hosts or /icingaweb2/icingadb/services

## Expected behavior
To see the info of the hosts or services

## Screenshots
environment_id should be a resource got string instead

#0 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Contract/PropertyBehavior.php(63): ipl\Orm\Behavior\Binary->fromDb(String, String, Integer)
#1 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Behaviors.php(120): ipl\Orm\Contract\PropertyBehavior->retrieveProperty(String, String)
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Redis/VolatileStateResults.php(131): ipl\Orm\Behaviors->retrieveProperty(String, String)
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Redis/VolatileStateResults.php(79): Icinga\Module\Icingadb\Redis\VolatileStateResults->applyRedisUpdates()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/BaseItemList.php(87): Icinga\Module\Icingadb\Redis\VolatileStateResults->rewind()
#5 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/ItemList/StateList.php(23): Icinga\Module\Icingadb\Common\BaseItemList->assemble()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(295): Icinga\Module\Icingadb\Widget\ItemList\StateList->assemble()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(497): ipl\Html\HtmlDocument->ensureAssembled()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\HtmlDocument->renderUnwrapped()
#14 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#17 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(491): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#18 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch(String)
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#21 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#22 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#23 {main}

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version	2.11.0
Git commit	46998464ea9f9e3c2889d98f9fb6df639d972550
PHP Version	7.3.29
Git commit date	2022-06-30

Loaded Libraries
icinga/icinga-php-library	0.9.0
icinga/icinga-php-thirdparty	0.11.0
Loaded Modules
icingadb		1.0.0	Configure
monitoring		2.11.0	Configure

* Web browser used: chrome

* Icinga 2 version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.4-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1160.59.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 11.2.1
  Build host: runner-hh8q3bz2-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

* PHP version used (`php --version`):
PHP 7.3.29 (cli) (built: Jul  1 2021 09:50:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.29, Copyright (c) 1998-2018 Zend Technologies

* Server operating system and version:
Linux xxx 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 16 12:17:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

regards,
Geert

**Comment by lippserd** [comment]
Hi,

Thanks for the report.

Please see Icinga/ipl-orm#69.

Duplicates #4858.

All the best,
Eric
