### ISSUE TITLE
Error icingadb

### ISSUE THREAD

**Issue by edsonblwolf** [Icinga/icingaweb2#4869]
Icinga Web 2 Version | 2.11.1
eecf8d9934cbf30ec063cea4a525b26bfd2bf99a
7.4.28
2022-07-06
Icinga Web 2 Version 	2.11.1
Git commit 	eecf8d9934cbf30ec063cea4a525b26bfd2bf99a
PHP Version 	7.4.28
Git commit date 	2022-07-06
[Get Icinga Support](https://icinga.com/support/)
[Icinga Community](https://icinga.com/community/)
[Report a bug](https://github.com/icinga/icingaweb2/issues)
[Icinga Documentation](https://icinga.com/docs/icinga-web-2/2.11)
Loaded Libraries
icinga/icinga-php-library 	0.9.1
icinga/icinga-php-thirdparty 	0.11.0
Loaded Modules
doc 		2.11.1 	[Configure](http://10.66.66.1:8090/icingaweb2/config/module/?name=doc)
icingadb 		1.0.0 	[Configure](http://10.66.66.1:8090/icingaweb2/config/module/?name=icingadb)
migrate 		2.11.1 	[Configure](http://10.66.66.1:8090/icingaweb2/config/module/?name=migrate)
monitoring 		2.11.1 	[Configure](http://10.66.66.1:8090/icingaweb2/config/module/?name=monitoring)
translation 		2.11.1 	[Config](http://10.66.66.1:8090/icingaweb2/config/module/?name=translation)
debian bullseye (11)
postgresql                           14+241.pgdg110+1 

Install :
https://icinga.com/docs/icinga-2/latest/doc/02-installation/01-Debian/
https://icinga.com/docs/icinga-db/latest/doc/02-Installation/03-Debian/#installing-icinga-db-package
https://icinga.com/docs/icinga-db-web/latest/doc/02-Installation/03-Debian/#installing-icinga-db-web-package

Error icingadb:
error all menu icingadb.

`

SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "host" does not exist
LINE 1: ...ft_state = 0 THEN 1 ELSE 0 END)) AS hosts_up FROM host LEFT ...
^

#0 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(402): PDOStatement->execute()
#1 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(418): ipl\Sql\Connection->prepexec()
#2 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Query.php(642): ipl\Sql\Connection->select()
#3 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(142): ipl\Orm\Query->yieldResults()
#4 [internal function]: ipl\Orm\ResultSet->yieldTraversable()
#5 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(122): Generator->valid()
#6 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/ResultSet.php(69): ipl\Orm\ResultSet->advance()
#7 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Query.php(614): ipl\Orm\ResultSet->current()
#8 /usr/share/icingaweb2/modules/icingadb/application/controllers/TacticalController.php(52): ipl\Orm\Query->first()
#9 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(477): Icinga\Module\Icingadb\Controllers\TacticalController->indexAction()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#12 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#13 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}

`
[https://ibb.co/QmB2CGP](url)

**Comment by edsonblwolf** [comment]
I imported
`psql -U icingadb -d icingadb < /usr/share/icingadb/schema/pgsql/schema.sql`

**Comment by nilmerg** [comment]
Okay, then you might have chosen the wrong resource in the module configuration. Check if that's really the resource for this database.
