### ISSUE TITLE
Icinga Web 2 always in English, although it is set to German.

### ISSUE THREAD

**Issue by Stefomat** [Icinga/icingaweb2#4871]
## Describe the bug
After updating to Icinga Web 2.11.1, the language remains in English even though `Browser (de_DE)` is selected in the settings.

## To Reproduce
1. Install Icinga Web 2
2. Apply DB schema updates
3. Hit F5 a few times (sometimes it jumps between languages)
4. It settles down to just stay in english

## Expected behavior
It should stay in the correct language for the chosen settings.

## Screenshots
![grafik](https://user-images.githubusercontent.com/41241946/178240405-6d65fc10-7076-4cd1-a967-d13e1af59b64.png)

## Your Environment
* Icinga Web 2 version and modules (System - About): 
![grafik](https://user-images.githubusercontent.com/41241946/178240669-ff29b4d1-9ba1-44b8-9c5d-524beb63db18.png)
* Web browser used: Mozilla Firefox 101.0.1 (64-Bit)
* Icinga 2 version used (`icinga2 --version`): r2.13.4-1
* PHP version used (`php --version`): 7.4.30
* Server operating system and version: Debian GNU/Linux 11.4 (bullseye)

## Additional context
I know this is only a little information. I am happy to provide more here. Just tell me what you want me to do.

**Comment by nilmerg** [comment]
Hi, works fine for me. You should check the web-server configuration, I guess it unsets the `Accept-Language` HTTP header.

**Comment by Stefomat** [comment]
Hi, thanks for your feedback. Unfortunately, I don't think it's because of that. A setting in Apache that removes the header is not set. Also, I can switch from `browser (de_DE)` to only `de_DE` in the settings and it still doesn't make a difference. With this setting, shouldn't it not matter what the browser delivers via the header?

**Comment by nilmerg** [comment]
Aaah, wait, you might be missing the `icinga-l10n` package. We've removed the builtin locales with v2.11.0.

**Comment by Stefomat** [comment]
That really helped. Now the texts are correctly displayed in German again.  
The switching back and forth directly after the update to 2.11 was probably browser cache then? Who knows.  
Have I overlooked an upgrade notice here and therefore not installed the package? Thanks for the quick help nevertheless.

**Comment by nilmerg** [comment]
No, it's not mentioned in the upgrade notices. Though, it's a recommended dependency of the main `icingaweb2` package since v2.8.0.
