### ISSUE TITLE
Duplicate service history entries

### ISSUE THREAD

**Issue by tt1062** [Icinga/icingaweb2#4896]
## Describe the bug
Service History  has repeated many repeated entries.

## To Reproduce

1. Define a service on a host
2. Switch to the History Tab of that service
3. We can see multiple entries

## Expected behavior
Only a single entry

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
   Icinga Web 2 Version
2.9.5
Git commit
053971c99dc1a4510beb64a888ea695cc14032dc
PHP Version
7.1.30
Git commit date
2021-11-18
Copyright
* Web browser used: chrome

**Comment by tt1062** [comment]
@lippserd Please let us know the exact version in which the bug is fixed

**Comment by nilmerg** [comment]
Since you didn't include a screenshot and didn't include which modules you have installed, I assume you're talking about the monitoring module history views? Or is it Icinga DB Web?

**Comment by nilmerg** [comment]
Thanks. Honestly though, I can only vaguely remember a similar issue like this in Icinga Web 2 (monitoring module). There was one in Icinga DB Web however. But I can't find anything here. I cannot tell you the exact version. But we have no similar reports and usually these pop up very soon if it's about the history views.

Try upgrading at least to v2.9.7.

**Comment by tt1062** [comment]
We have upgraded to v2.11.1 but still having the same issue

**Comment by tt1062** [comment]
after upgrading to v2.11.1 we are facing the same issue could you please help us how to resolve this 
<img width="521" alt="image" src="https://user-images.githubusercontent.com/107386973/209537709-5e29b1a9-cc92-4c36-80f1-f11ab90e05a9.png">
