### ISSUE TITLE
Check attempts are not being updated in gui

### ISSUE THREAD

**Issue by davixd** [Icinga/icingaweb2#4899]
## Describe the bug
While a check reaches a critical state, the check attempts are not being visualized in the icingaweb2 gui. Even as the check reaches the hard state, the check number of attempts is not being correctly visualized. It is always stocked at 1/3 or 1/5 for example.  

## To Reproduce
I did a update from icingaWeb2-2.10.1 to icinga2-2.13.5-1.el7.icinga.x86_64.
After the update, I did a mysql schema update:
`mysql -u root -p icingaweb2 < /usr/share/doc/icingaweb2/schema/mysql-upgrades/2.11.0.sql`

To complete the mysql schema update without a error in mariadb-5.5.68, I had to configure the mariadb with the following settings:

/etc/my.cnf:
```
innodb_file_per_table=true
innodb_large_prefix=1
innodb_file_format=Barracuda
```

otherwise I always got the following error:
ERROR without  mariadb setting:
> ERROR 1071 (42000) at line 8: Specified key was too long; max key length is 767 bytes
> ALTER TABLE icingaweb_group_membership CONVERT TO CHARACTER SET utf8mb4;

## Expected behavior
The check attempts flag in the GUI should be updated accordingly to the tries of critical return state. As the check being checked two times with critical state the check attempts flag should be visualized  2/3 or when reaching the hard state 3/3 for example.

## Your Environment
- centos-release-7-9
- icinga2-2.13.5-1.el7.icinga.x86_64
- icingaweb2-2.11.1-1.el7.icinga.noarch
- mariadb-5.5.68-1.el7.x86_64
- mariadb-server-5.5.68-1.el7.x86_64

**Comment by nilmerg** [comment]
Hi,

we have no similar reports. I suspect an issue on your side. Though, I can't help you with that. Since you already have opened a topic on the forums (https://community.icinga.com/t/check-attempts-are-not-being-updated-with-icingaweb2-2-11-1-1/10464) I hope you get some hints there.
