### ISSUE TITLE
LDAP login doesn't work with PHP 8.1

### ISSUE THREAD

**Issue by dbuelow** [Icinga/icingaweb2#4902]
`Uncaught Error: Call to undefined function Icinga\Protocol\Ldap\ldap_connect() in /var/www/$domain/source/library/Icinga/Protocol/Ldap/LdapConnection.php:1184`

# Environment

Icinga Web 2 Version  2.11.1

icinga/icinga-php-thirdparty    0.11.0
icinga/icinga-php-library   0.9.1

director        1.9.1   
doc         2.11.1  
grafana         1.4.2   
incubator       0.18.0  
map         1.1.0   
monitoring      2.11.1

icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.5-1)

PHP 8.1.9 (cli) (built: Aug  2 2022 13:02:24) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies

**Comment by lippserd** [comment]
I think you have to install `php-ldap`.

**Comment by dbuelow** [comment]
@lippserd 
omg, your'e right, thx.
