### ISSUE TITLE
Filtering of objects based on currently logged in user does not work anymore

### ISSUE THREAD

**Issue by chas0rde** [Icinga/icingaweb2#4908]
We experienced that our current configuration regarding user-based filtering of what you see in monitoring does not work anymore.
We use monitoring/filter/objects to filter based on host/service custom vars:

`_host_responsible=$user:local_name$|_host_deputy=$user:local_name$|_host_informational_users=*$user:local_name$*|_service_responsible=$user:local_name$|_service_deputy=$user:local_name$|_service_informational_users=*$user:local_name$*` 

This is based on commit 6ad74ef 

As it stopped working after recent updates I investigated and realized that the code of above commit has been migrated in #4306

According to @lippserd in above pullrequest it should still work as the code was just moved
I did not investigate the code to closely (from the quick look he is right) but all I can say is that it stopped working
When I manually re-add the code to User.php in our environment it works again right away

We are running (only what I thing is relevant here)
- 2.11.1
- PHP 8.1.9
- ubuntu 22.04 LTS

**Comment by nilmerg** [comment]
Please have a look at the [upgrading](https://github.com/Icinga/icingaweb2/blob/master/doc/80-Upgrading.md) documentation regarding breaking changes in v2.11. The macro is now called `user.local_name`.

**Comment by lippserd** [comment]
Sry, @chas0rde I missed that as well :)

**Comment by chas0rde** [comment]
Suttle change Thanks for the remark

I changed my above filter and replaced all the `user:local_name` with `user.local_name`
Afterwards I removed my edit of the User.php.

Result: The filter still does not work
I see no hosts/services.

Even if I add the following to User.php it doesn't work. 
`   public function setRestrictions(array $restrictions)
    {
        foreach ($restrictions as $name => $restriction) {
            $restrictions[$name] = str_replace('$user.local_name$', $this->getLocalUsername(), $restriction);
        }
        $this->restrictions = $restrictions;
        return $this;
    }`

If I alter that back to `user:` as well as my previous filter  it works right away

So it seems something is not working as (I) expect it with the renamed macro

Best regards

**Comment by nilmerg** [comment]
Works fine on my end. No matter with which version, be it 2.9.7, v2.10.3 or v2.11.1. You should revert all code changes, then adjust your restrictions, then have your users log out and log in again. Then it should work.

**Comment by chas0rde** [comment]
Hello
I am on v2.11.1
Reverted my changes
![grafik](https://user-images.githubusercontent.com/5859679/189853257-eb64e8f8-975f-43a8-ad66-6be517dc35e5.png)

Configured the filter for the user group to
`_host_responsible=$user.local_name$|_host_deputy=$user.local_name$|_host_informational_users=*$user.local_name$*|_service_responsible=$user.local_name$|_service_deputy=$user.local_name$|_service_informational_users=*$user.local_name$*`

Started a private browser window and logged in a a restricted user that falls into that role.
![grafik](https://user-images.githubusercontent.com/5859679/189853563-56b0f6a2-c53d-47fa-8e7b-ba2f038ea792.png)

So something must be different between your config and mine

**Comment by nilmerg** [comment]
Please add the restriction to your admin user, or, give the restricted user configuration access. Then head to e.g. the host list and add `?format=sql` in the address bar. This should show you the queries used and they should include the applied restrictions as well. There check if a condition is added that includes the current username. If I do this, it's included. If yours is not, please show the query.

**Comment by chas0rde** [comment]
Hello
what do mean by "give the restricted user configuration access"?

I just removed my changes from User.php again and logged in with a restricted user. SQL gives me the following:
`QUERY
=====
SELECT h.icon_image AS host_icon_image, h.icon_image_alt AS
host_icon_image_alt, ho.name1 AS host_name, h.display_name COLLATE
latin1_general_ci AS host_display_name, CASE WHEN hs.has_been_checked = 0
OR hs.has_been_checked IS NULL THEN 99 ELSE hs.current_state END AS
host_state, hs.problem_has_been_acknowledged AS host_acknowledged,
hs.output AS host_output, hs.current_check_attempt || '/' ||
hs.max_check_attempts AS host_attempt, CASE WHEN
(hs.scheduled_downtime_depth = 0) THEN 0 ELSE 1 END AS host_in_downtime,
hs.is_flapping AS host_is_flapping, hs.state_type AS host_state_type, CASE
WHEN (hs.problem_has_been_acknowledged + hs.scheduled_downtime_depth) > 0
THEN 1 ELSE 0 END AS host_handled, UNIX_TIMESTAMP(hs.last_state_change) AS
host_last_state_change, hs.notifications_enabled AS
host_notifications_enabled, hs.active_checks_enabled AS
host_active_checks_enabled, hs.passive_checks_enabled AS
host_passive_checks_enabled, hs.check_command AS host_check_command, CASE
WHEN hs.has_been_checked = 0 OR hs.has_been_checked IS NULL THEN CASE
hs.should_be_scheduled WHEN 1 THEN UNIX_TIMESTAMP(hs.next_check) +
(hs.normal_check_interval * 60) ELSE NULL END ELSE
UNIX_TIMESTAMP(hs.next_check) + (CASE WHEN COALESCE(hs.current_state, 0) >
0 AND hs.state_type = 0 THEN hs.retry_check_interval ELSE
hs.normal_check_interval END * 60) + (CEIL(hs.execution_time + hs.latency)
* 2) END AS host_next_update FROM icinga_objects AS ho
 INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id AND
ho.is_active = 1 AND ho.objecttype_id = 1
 INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
ORDER BY h.display_name COLLATE latin1_general_ci ASC

COUNT
=====
SELECT COUNT(*) AS cnt FROM icinga_objects AS ho
 INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id AND
ho.is_active = 1 AND ho.objecttype_id = 1
 INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
`

Maybe I overlooked it but I see nothing about restrictions in here

**Comment by nilmerg** [comment]
A user without access to configure roles won't see the restrictions by using this url parameter. You won't see them if the user has no permission to configure roles.

**Comment by chas0rde** [comment]
It seems that I had an error in my brain :P
The user I used for testing fell into another restricted roll in which i didn't change the respective filter :doh:

Sorry for wasting your time but everything works as expected
