### ISSUE TITLE
CSV export does not escape double quotes

### ISSUE THREAD

**Issue by domme0711** [Icinga/icingaweb2#4910]
## Describe the bug
When exporting the eventhistory as CSV: double quotes which are contained in comments are not escaped. This results in a broken CSV file which cannot be parsed properly.

## To Reproduce
1. Add any comment which contains double quotes to a host or service.
2. Go to History => Event Overview 
3. Export the view as CSV (/icingaweb2/monitoring/list/eventhistory?timestamp%3E=-7%20days&format=csv)

## Expected behavior
Download of a properly formatted CSV file. Strings are encapsulated by double quotes. Double quotes within these strings has to be escaped.

## Screenshots
![grafik](https://user-images.githubusercontent.com/96781721/189135916-dfb2243c-a748-486d-8051-6d8d2b577601.png)

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.11.1
* Web browser used: FF
* Icinga 2 version used (`icinga2 --version`): 2.13.5
* PHP version used (`php --version`): 7.4.6
* Server operating system and version: SLES15

**Comment by nilmerg** [comment]
Hi,

you are right, thanks for reporting!
