### ISSUE TITLE
Add number of Services to the host

### ISSUE THREAD

**Issue by Nathaniel-Donahue** [Icinga/icingaweb2#4913]
Hi,

## Is your feature request related to a problem? Please describe.
Ich would love to see how many Serices are on a Host. I know thats possible when you click it but it would really help to have that one step before.

## Describe the solution you'd like
I would like to have the "2 Services: 2" part out of attached picture 2 at the highlighted setcion of picture 1.

## Additional context
It really would help while trying to fully complete the monitroing of all hosts because for that we have to go to Web2 many times and compare how many Services are on which Server.

![image001](https://user-images.githubusercontent.com/56820910/189337309-5c189dc7-3413-49b2-8174-d5597fd8f7a8.jpg)
![image002 (1)](https://user-images.githubusercontent.com/56820910/189337312-e8ab3475-d8b3-4096-b415-22905a719bf8.jpg)

**Comment by Nathaniel-Donahue** [comment]
ref/NC/761164

**Comment by nilmerg** [comment]
Hi,

> It really would help while trying to fully complete the monitroing of all hosts because for that we have to go to Web2 many times and compare how many Services are on which Server.

This sounds like a one-time thing. There's no reason to add this by default. Not here anyway. But this is a good candidate for the [column chooser in Icinga DB Web](https://github.com/Icinga/icingadb-web/issues/82).
