### ISSUE TITLE
New DBWeb-Installer is always returning valid on first DBWeb-DB-Check and then requires root-database-permissions

### ISSUE THREAD

**Issue by pdolinic** [Icinga/icingaweb2#4917]
## Describe the bug
- a) The problem could be directly addresed by adding to Docs of DB-Web a way to manually add the required DBWeb-Schemata to one owns Database (as it was the case with Icinga-IDO and previous Web in the Docs)
- b) Currently the first check-validation of the DBWeb-WebDB during DBWeb-Installer is always returning **valid** even on **faulty** input - so users feel they did everything correct (this is also  optically visible compared to the second DBDB-Check-Validation -> where one receives output / return Values)
- c) As the required DBWeb-DBWebSchemata are not here until b) and not present in a the documentation users might feel like they need to enter DBWeb-WebDB credentials to the step after the missing validation. This is correctly communicated in the long information message though, but could be highlighted clearer if possible.
- d) This will of course not work, as one needs database-root rights to import the new DBWeb Schemata. This is slightly problematic as a lot of default configurations might limit root to sockets, ips etc. 
## To Reproduce
Install IcingaDB default, check any input return true on first DBWebDB-validation, check that the step following this requires root and only root.

## Expected behavior
- First validation should return false on faulty input
- Directly import the required DBWeb Schemata onself, or communicate clearly about root-permissions on the Backend-Database

## Screenshots
![first-always-succeeds](https://user-images.githubusercontent.com/71389319/190598714-97e94f97-4330-4c59-9708-1357ba5aba90.png)
"to access the database" -> "to update the database/import the new DBWeb-Schema"
![not-required-schema](https://user-images.githubusercontent.com/71389319/190598784-9cbf3b2a-9da7-42cb-af13-43b4fce96d7d.png)
- Side info, out of desparation some might search for "dpkg -L icingadb-web | grep mysql" and not find anything, then do the same with "icingaweb2" and import the old web-schemata, in case this happens even root-validation at the screenshots will fail, and later, even though the installer will finish, one will not be able to log in anymore so one has to redo the setup.
- Additonal small idea for improvement: The top left is named "Database Setup", new users not familiar with Icinga2 might benefit from a label such as "Web Database Setup" (to not get confused). Similar could be done for the IcingaDB input follwing some clicks later "IcingaDB Database Setup".

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.1
* Icinga Web 2 version (System - About): 2.11.1
* Web browser: Firefox on Linux 104.0.1
* Icinga 2 version (`icinga2 --version`): r2.13.5-1
* Icinga DB version (`icingadb --version`):  v1.0.0
* PHP version used (`php --version`): PHP 7.4.30 , Zend Engine v3.4.0,
* Server operating system and version: Debian 11

**Comment by nilmerg** [comment]
Hi,

first, Icinga DB Web already makes it clear when the database details for Icinga DB are required. You didn't include a screenshot of that, so I guess you didn't progress that far. I moved this for this reason to the icingaweb2 repository.

then, yes, the page asking for a "Database Resource" could indicate better that the database for Icinga Web is being set up. But it doesn't complain about invalid credentials or a missing database schema without a reason. The next step should make it clear why, as it asks for credentials to create the database and/or a user to administrate it. (i.e. root) The error message you have shown even told you so.

Honestly, I found it hard to decipher from your description what the actual problem is. To me it comes down to this: **Ensure the user knows that on the screenshots shown the Icinga Web database is set up.**

Correct?

**Comment by pdolinic** [comment]
Hi,
- basically it appears that the first database check only checks for IP and Port and ignores faulty username and password and then returns valid (no matter what)
![icinga-1](https://user-images.githubusercontent.com/71389319/191001686-cb518ae5-c0f3-4d95-9200-4af61b21c606.png)
- the step after that seems to continue with the wrongly-provided credentials (even now this case I am providing the correct root-credentials now) <-> so the only way is to press "skip validation"
![icinga-root](https://user-images.githubusercontent.com/71389319/191002223-b16aa742-acff-4d3e-ba68-4448fcc3721b.png)

**Comment by nilmerg** [comment]
Should be tackled together with #2543
