### ISSUE TITLE
Web page freezed

### ISSUE THREAD

**Issue by gianlucapiccolo** [Icinga/icingaweb2#4929]
## Describe the bug
I need to select a host "host parent" in the director. For that purpose I created a select custom data field that contains the list of all the hosts. When I open the host edit form in the director now the page freezes for about 2 minutes.

## To Reproduce
1. Decompress and import the attached example database [db-bug-reproduce.zip](https://github.com/Icinga/icingaweb2/files/9772439/db-bug-reproduce.zip): `mysql ${DIRECTOR_DB} < db-bug-reproduce.sql`
2. Open a host detail in the director: open `https://icingaweb2-domain/director/host?uuid=0b02e96c-dda4-4851-83d3-ea58fa4f10e2`
3. The browser page should be freezed

## Expected behavior
I would like that the page doesn't freeze. With large databases of the director it is acceptable that the loading time of the page is of some seconds, but not minutes.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.10.1
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.11.9-1
* PHP version used (`php --version`): 7.4.19
* Server operating system and version: RHEL 8.6

## Additional context
There is no correlation between the bug and the director, in my case the combination of elements that trigger the problem happened there but it could happen everywhere else. The problem is caused by the following CSS directive when there are a lot of elements in the DOM: 
```
public/css/icinga/forms.less
&[disabled] ~ * {
    opacity: .25;
}
```

This makes the client CPU work at 100% of the usage for more than a minute.

**Comment by nilmerg** [comment]
Ack. And thanks for reporting. May I ask how you've identified that line?

**Comment by gianlucapiccolo** [comment]
Thanks for asking! I did a research for exclusion...long process...not funny 😅 p.s. I'm not an expert of CSS at all.

**Comment by nilmerg** [comment]
Oh well, I thought you were using some fancy tool to inspect the rendering process. I know how tedious this is without one :exploding_head:
