### ISSUE TITLE
While using dropdown filter menu it gets closed automatically due to autorefresh

### ISSUE THREAD

**Issue by NicolasGoeddel** [Icinga/icingaweb2#4942]
## Describe the bug
When using the filter functions for hosts, services, etc the dropdown to choose the right filter automatically closes while scrolling through it.
There seems to be an old issue (#1005) about the same bug which got solved but now it is here again.

## To Reproduce
Prerequisites: No fancy configurations here, just the bare minimum to connect to the IDODB.

1. Open Overview -> Services
2. Click on filter
3. Open dropdown
4. Wait

## Expected behavior
The dropdown should not close automatically while I am still trying to find the correct filter.

## Screenshots
n/a

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version (System - About): 2.11.1
* Icinga Web 2 modules:
  - doc 2.11.1
  - grafana 1.4.3
  - incubator 0.19.0
  - ipl 0.5.0
  - monitoring 2.11.1
  - reactbundle 0.9.0
  - translation 2.11.1
  - vspheredb 1.5.0
* Web browser used: Firefox 106.0.5
* Icinga 2 version used (`icinga2 --version`): 2.13.5-1
* PHP version used (`php --version`): 8.1.2-1ubuntu2.6
* Server operating system and version: Ubuntu 22.04.1 LTS

**Comment by nilmerg** [comment]
I'm sorry, but... works fine for me. With Firefox v106.0.2. And Chrome/Chromium. What's your client OS, macOS maybe?

**Comment by NicolasGoeddel** [comment]
It only seems to happen in certain constellations. I try to find a reliable step by step guide to reproduce the issue. Give me a few minutes.

**Comment by NicolasGoeddel** [comment]
Okay, I got it.

Step by step:
1. Go to Overview -> Services
2. Add new filter "Service Check Command = ping4" and apply it
3. Open the dropdown again and wait
4. The dropdown closes automatically after a while

Instead of "Service Check Command = ping4" it also works with "Hostgroup Name = xyz" and I assume other

The dropdown closes when this GET request happens: http://localhost/icingaweb2/monitoring/list/services?service_check_command=ping4&modifyFilter=1

**Comment by nilmerg** [comment]
Confirmed.
