### ISSUE TITLE
Search in icingaweb2 results in slow query (~30 minutes / search)

### ISSUE THREAD

**Issue by bukovszg** [Icinga/icingaweb2#4944]
## Describe the bug
Searching in icingaweb2 triggers a slow SQL query. The query is a result of searching the teactial overview during global search (Integrate the tactical overview into the "global" search #2529)

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. log in to icingaweb2 to a reasonably big environment ( we have 20k services and 2k hosts)
2. in the top left global search, try searching for anything
3. either: in the database: show processlist; -> look for queries running longer than 60 seconds
4. or:  enable slow query logging and look at the log result.

After 60 seconds the UI returns with the massage "You don't have permission to access this resource."

## Expected behavior
Queries should end in reasonable time frame (under 60 seconds)

## Screenshots
No, but slow query log attached.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 
Icinga Web 2 Version
2.9.5
Git Commit
053971c99dc1a4510beb64a888ea695cc14032dc
PHP-Version
7.2.24
Git Commit Datum
2021-11-18

Name | Version
businessprocess | 2.3.1
doc | 2.9.5
grafana | 1.3.6
idoreports | 0.9.1
ipl | v0.5.0
monitoring | 2.9.5
pdfexport | 0.9.1
reactbundle | 0.9.0
reporting | 0.10.0

* Web browser used: Edge
* Icinga 2 version used (`icinga2 --version`): 
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.13.2-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 8
  Kernel: Linux
  Kernel version: 4.18.0-348.7.1.el8_5.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.4.1
  Build host: runner-hh8q3bz2-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.1.1k  FIPS 25 Mar 2021

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* PHP version used (`php --version`):
# php -version
PHP 7.2.24 (cli) (built: Oct 22 2019 08:28:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

* Server operating system and version:
      Operating System: CentOS Linux 8
      CPE OS Name: cpe:/o:centos:centos:8
      Kernel: Linux 4.18.0-348.7.1.el8_5.x86_64
      Architecture: x86-64

## Additional context
Example slow query:

# User@Host: icinga[icinga] @ localhost []
# Thread_id: 3492  Schema: icinga  QC_hit: No
# Query_time: 2188.022819  Lock_time: 0.000543  Rows_sent: 0  Rows_examined: 722178911
# Rows_affected: 0  Bytes_sent: 902
SET timestamp=1667559892;
SELECT SUM(CASE WHEN object_type = 'host' AND state = 0 THEN 1 ELSE 0 END) AS hosts_up, SUM(CASE WHEN object_type = 'host' AND state = 1 AND handled > 0 THEN 1 ELSE 0 END) AS hosts_down_handled, SUM(CASE WHEN object_type = 'host' AND state = 1 AND handled = 0 THEN 1 ELSE 0 END) AS hosts_down_unhandled, SUM(CASE WHEN object_type = 'host' AND state = 2 AND handled > 0 THEN 1 ELSE 0 END) AS hosts_unreachable_handled, SUM(CASE WHEN object_type = 'host' AND state = 2 AND handled = 0 THEN 1 ELSE 0 END) AS hosts_unreachable_unhandled, SUM(CASE WHEN object_type = 'host' AND state = 99 THEN 1 ELSE 0 END) AS hosts_pending, SUM(CASE WHEN object_type = 'host' AND state = 99 AND is_active_checked = 0 AND is_passive_checked = 0 THEN 1 ELSE 0 END) AS hosts_pending_not_checked, SUM(CASE WHEN object_type = 'host' AND is_active_checked = 0 AND is_passive_checked = 0 THEN 1 ELSE 0 END) AS hosts_not_checked, SUM(CASE WHEN object_type = 'service' AND state = 0 THEN 1 ELSE 0 END) AS services_ok, SUM(CASE WHEN object_type = 'service' AND state = 1 AND handled + host_problem > 0 THEN 1 ELSE 0 END) AS services_warning_handled, SUM(CASE WHEN object_type = 'service' AND state = 1 AND handled + host_problem = 0 THEN 1 ELSE 0 END) AS services_warning_unhandled, SUM(CASE WHEN object_type = 'service' AND state = 2 AND handled + host_problem > 0 THEN 1 ELSE 0 END) AS services_critical_handled, SUM(CASE WHEN object_type = 'service' AND state = 2 AND handled + host_problem = 0 THEN 1 ELSE 0 END) AS services_critical_unhandled, SUM(CASE WHEN object_type = 'service' AND state = 3 AND handled + host_problem > 0 THEN 1 ELSE 0 END) AS services_unknown_handled, SUM(CASE WHEN object_type = 'service' AND state = 3 AND handled + host_problem = 0 THEN 1 ELSE 0 END) AS services_unknown_unhandled, SUM(CASE WHEN object_type = 'service' AND state = 99 THEN 1 ELSE 0 END) AS services_pending, SUM(CASE WHEN object_type = 'service' AND state = 99 AND is_active_checked = 0 AND is_passive_checked = 0 THEN 1 ELSE 0 END) AS services_pending_not_checked, SUM(CASE WHEN object_type = 'service' AND is_active_checked = 0 AND is_passive_checked = 0 THEN 1 ELSE 0 END) AS services_not_checked FROM (SELECT CASE WHEN (hs.problem_has_been_acknowledged + hs.scheduled_downtime_depth) > 0 THEN 1 ELSE 0 END AS handled, CASE WHEN COALESCE(hs.current_state, 0) = 0 THEN 0 ELSE 1 END AS host_problem, NULL AS host_state, hs.active_checks_enabled AS is_active_checked, hs.flap_detection_enabled AS is_allowed_to_flap, hs.is_flapping, CASE WHEN hs.active_checks_enabled = 0 AND hs.passive_checks_enabled = 1 THEN 1 ELSE 0 END AS is_passive_checked, hs.event_handler_enabled AS is_processing_events, hs.notifications_enabled AS is_triggering_notifications, ('host') AS object_type, CASE WHEN hs.has_been_checked = 0 OR hs.has_been_checked IS NULL THEN 16 ELSE CASE  WHEN hs.current_state = 0 THEN 1 ELSE CASE WHEN hs.current_state = 1 THEN 64 WHEN hs.current_state = 2 THEN 32 ELSE 256 END + CASE  WHEN hs.problem_has_been_acknowledged = 1 THEN 2 WHEN hs.scheduled_downtime_depth > 0 THEN 1 ELSE 256 END END END AS severity, UNIX_TIMESTAMP(hs.last_state_change) AS state_change, CASE WHEN hs.has_been_checked = 0 OR hs.has_been_checked IS NULL THEN 99 ELSE hs.current_state END AS state FROM icinga_objects AS ho
 INNER JOIN icinga_hosts AS h ON h.host_object_id = ho.object_id AND ho.is_active = 1 AND ho.objecttype_id = 1
 INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = ho.object_id
 LEFT JOIN icinga_services AS s ON s.host_object_id = h.host_object_id
 LEFT JOIN icinga_objects AS so ON so.object_id = s.service_object_id AND so.is_active = 1 AND so.objecttype_id = 2 WHERE ( (EXISTS  (SELECT 1 FROM icinga_objects AS sub_hgo
 INNER JOIN icinga_hostgroups AS sub_hg ON sub_hg.hostgroup_object_id = sub_hgo.object_id AND sub_hgo.is_active = 1 AND sub_hgo.objecttype_id = 3
 INNER JOIN icinga_hostgroup_members AS sub_hgm ON sub_hgm.hostgroup_id = sub_hg.hostgroup_id
 INNER JOIN icinga_objects AS sub_ho ON sub_hgm.host_object_id = sub_ho.object_id AND sub_ho.is_active = 1 AND sub_ho.objecttype_id = 1 WHERE ((sub_hgo.name1 IN (<redacted over 20 hostgroups>)) AND sub_hgm.host_object_id = ho.object_id)))  AND  (ho.name1 COLLATE latin1_general_ci LIKE '%searchstring%' OR so.name2 COLLATE latin1_general_ci LIKE '%searchstring%') ) GROUP BY ho.object_id,
        h.host_id UNION ALL SELECT CASE WHEN (ss.problem_has_been_acknowledged + ss.scheduled_downtime_depth + COALESCE(hs.current_state, 0)) > 0 THEN 1 ELSE 0 END AS handled, CASE WHEN COALESCE(hs.current_state, 0) = 0 THEN 0 ELSE 1 END AS host_problem, CASE WHEN hs.has_been_checked = 0 OR hs.has_been_checked IS NULL THEN 99 ELSE CASE WHEN hs.state_type = 1 THEN hs.current_state ELSE hs.last_hard_state END END AS host_state, ss.active_checks_enabled AS is_active_checked, ss.flap_detection_enabled AS is_allowed_to_flap, ss.is_flapping, CASE WHEN ss.active_checks_enabled = 0 AND ss.passive_checks_enabled = 1 THEN 1 ELSE 0 END AS is_passive_checked, ss.event_handler_enabled AS is_processing_events, ss.notifications_enabled AS is_triggering_notifications, ('service') AS object_type, CASE WHEN ss.current_state = 0 THEN CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 16 ELSE 0 END + CASE WHEN ss.problem_has_been_acknowledged = 1 THEN 2 ELSE CASE WHEN ss.scheduled_downtime_depth > 0 THEN 1 ELSE 4 END END ELSE CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 16 WHEN ss.current_state = 1 THEN 32 WHEN ss.current_state = 2 THEN 128 WHEN ss.current_state = 3 THEN 64 ELSE 256 END + CASE WHEN hs.current_state > 0 THEN 1024 ELSE CASE WHEN ss.problem_has_been_acknowledged = 1 THEN 512 ELSE CASE WHEN ss.scheduled_downtime_depth > 0 THEN 256 ELSE 2048 END END END END AS severity, UNIX_TIMESTAMP(ss.last_state_change) AS state_change, CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 99 ELSE ss.current_state END AS state FROM icinga_objects AS so
 INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id AND so.is_active = 1 AND so.objecttype_id = 2
 INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = s.host_object_id
 INNER JOIN icinga_servicestatus AS ss ON ss.service_object_id = so.object_id WHERE ( (EXISTS  (SELECT 1 FROM icinga_objects AS sub_hgo
 INNER JOIN icinga_hostgroups AS sub_hg ON sub_hg.hostgroup_object_id = sub_hgo.object_id AND sub_hgo.is_active = 1 AND sub_hgo.objecttype_id = 3
 INNER JOIN icinga_hostgroup_members AS sub_hgm ON sub_hgm.hostgroup_id = sub_hg.hostgroup_id
 INNER JOIN icinga_objects AS sub_ho ON sub_hgm.host_object_id = sub_ho.object_id AND sub_ho.is_active = 1 AND sub_ho.objecttype_id = 1 WHERE ((sub_hgo.name1 IN (<redacted over 20 hostgroups>)) AND sub_hgm.host_object_id = s.host_object_id)))  AND  (so.name1 COLLATE latin1_general_ci LIKE '%searchstring%' OR so.name2 COLLATE latin1_general_ci LIKE '%searchstring%') )) AS statussummary;

**Comment by nilmerg** [comment]
Hi,

please tell us where the database is running on. Machine specs, available resources, etc.

**Comment by bukovszg** [comment]
Hi,

this is a virtual server with 12CPUs, 16GB of RAM and 250GB of all flash storage. Network is 25Gbit max for a single VM.  Memory utilization is around 30%  CPU below 20% - when the queries are not running. No disk IO, higher latency, higher network traffic etc. to see. It is only the CPU which is occupied by the long running query.

**Comment by bukovszg** [comment]
Any feedback/questions? Did some tuning on the DB itself using "mysqltuner" but it did not helped. The queries still run over 20 minutes eating up CPU.

**Comment by bukovszg** [comment]
Any news?

**Comment by nilmerg** [comment]
Sorry for the late reply.

> 12CPUs, 16GB of RAM and 250GB of all flash storage.

This isn't exactly much. My previous development machine had more and frequently ran into high load with 5k services and 1k hosts.

The IDO backend always wasn't that efficient. If it's an option, switch to [Icinga DB](https://icinga.com/docs/icinga-db/latest/doc/01-About/). That's your best option to solve this.

Best,
Johannes
