### ISSUE TITLE
find nothing of hosts when do global searching based on display name or address

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingaweb2#4950]
Now I don't know where to ask my question which I described below.
Is this an icingaweb2 or an icingadb-web problem?
(https://github.com/Icinga/icingadb-web/issues/690)

That's why I ask the question also here.

## Describe the bug
Hello,

when doing a global search it will search in the old monitoring in the object, address and display_name for me.
In icingadb it will only search in the object name I think.

## To Reproduce
Disable the old monitoring that you only work in icingadb mode. 
Search for something that is in the display_name or address , but is not in the object name (name or name_ci)

## Expected behavior
Find the horsts that find the text in the display name or address.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 2.11.2
* Icinga Web 2 version (System - About): 1.0.2
* Web browser: chrome
* Icinga 2 version (`icinga2 --version`): r2.13.6-1
* Icinga DB version (`icingadb --version`): v1.1.0
* PHP version used (`php --version`): 7.1.30
* Server operating system and version: Red Hat Enterprise Linux Server 7.9

**Comment by nilmerg** [comment]
It's an Icinga DB Web problem, your first attempt was already correct.
