### ISSUE TITLE
Module CA's menu entry not visible any longer

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2#4951]
## Describe the bug
The module CA (https://github.com/nunofernandes/icingaweb2-module-ca) has had a menu entry below System, but this is no longer visible with current version of Icinga Web 2 (likely since 2.10 as it introduced the change to the menu entries).

## To Reproduce
1. Install the module 
2. Do not find the menu entry
3. Directly access the url /icingaweb2/ca to see the module is still working fine

## Expected behavior
See the module entry again allowing to navigate to the URL

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.11.2
* Web browser used: Edge
* Icinga 2 version used (`icinga2 --version`): 2.13.2
* PHP version used (`php --version`): 7.4
* Server operating system and version: RHEL 8

## Additional context
Issue at the module: https://github.com/nunofernandes/icingaweb2-module-ca/issues/10

**Comment by nilmerg** [comment]
This is to be expected and can't be fixed without breaking the mobile menu. (Blocked by #4750) Though, by the time the mobile menu is redone I don't think much modules remain which require this fix, so I close here.
