### ISSUE TITLE
Shared navigation items are not accessible

### ISSUE THREAD

**Issue by Donien** [Icinga/icingaweb2#4953]
# Describe the bug

Shared navigation administration is no longer accessible via menu entry (likely since version 2.10).

# Expected Behavior

A user creates `shared navigation` items and shares them with other users.  
Other users can now see those navigation items in their side bar.  

There should be a way to `unshare` those navigation items.  

# Current Behaviour

Under `$HOST/icingaweb2/navigation` there is no way to access shared navigation items (shared by others).
You **have to know** the URL (`icingaweb2/navigation/shared`) in order to access it.

**$HOST/icingaweb2/navigation**  

![navigation](https://user-images.githubusercontent.com/88634789/205064646-bf9ca6e1-a3bd-462f-a338-17bf12f46945.png)

**$HOST/icingaweb2/navigation/shared**  
![navigation_shared](https://user-images.githubusercontent.com/88634789/205064948-3b0eca5b-4b90-4248-b9fa-fa0b0d8aaa1a.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

- Icinga Web 2 version and modules (System - About): 2.11.2
- Web browser used: Edge/Firefox
- Icinga 2 version used (icinga2 --version): 2.13.2
- PHP version used (php --version): 7.4
- Server operating system and version: RHEL 8

**Comment by carraroj** [comment]
ref/NC/770521
