### ISSUE TITLE
Restrictions: Restricting to specific objects doesn't work correctly

### ISSUE THREAD

**Issue by Gian1110** [Icinga/icingaweb2#4975]
## Describe the bug
Hi, I'm trying to set a restriction on a role but when I set it,  "hostgroup_name = Windows Server" doesn’t show any host with that user role.
I attach pictures where shows groups, configuration role and the user view

![imagen1](https://user-images.githubusercontent.com/44478908/211568003-e0346d44-f248-46eb-903e-022dc0b0ca8e.jpeg)
![imagen2](https://user-images.githubusercontent.com/44478908/211568009-8f42ec2c-f9d7-4ae4-9dee-962923a57f4b.jpeg)
![imagen3](https://user-images.githubusercontent.com/44478908/211568011-207e97d5-a879-489b-b319-543d328191fa.jpeg)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.11.1
* Web browser used: google chrome

**Comment by nilmerg** [comment]
Hi,

try `hostgroup_name=Windows Servers` (without spaces around the operator)

**Comment by Gian1110** [comment]
it's correct. thanks very much
