### ISSUE TITLE
Membership in a user group is retained after the user is deleted

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/icingaweb2#4993]
## Describe the bug
When a user is deleted in Icinga Web 2, the user's group memberships should also be removed. This is currently not the case

## To Reproduce
* Create a user
* Add to a group
* Delete the user

## Expected behavior
When a user is deleted, he should be automatically removed from the groups.

* Icinga Web 2 version and modules (System - About): 2.11.4
* Icinga 2 version used (`icinga2 --version`): 2.13.6
* PHP version used (`php --version`): 8.1.2
* Server operating system and version: Ubuntu 22.04.1 LTS

**Comment by tbauriedel** [comment]
ref/NC/775781

**Comment by nilmerg** [comment]
Duplicate of #3978
