### ISSUE TITLE
Graphs disappear after form controls are used after icingaweb2 2.11.3

### ISSUE THREAD

**Issue by araujorm** [Icinga/icingaweb2#4996]
## Expected Behavior
Graphs should never disappear

## Current Behavior
Graphs disappear after form controls are used and an autosubmit is made

## Possible Solution
Happens since icingaweb 2.11.3 (and still happens in latest release 2.11.4), more specifically since the following change was made in icingaweb2:
https://github.com/Icinga/icingaweb2/commit/8cd892359d1770260e10486554764bcd8c0be797

Reverting that change in icingaweb2 fixes this issue in graphite module, even in icingaweb2 2.11.4. So I'm not sure if this is something to be tackled as an issue on this module or in icingaweb2, but before submitting there it seemed more appropriate to submit here first (could be something the module is not doing correctly and just worked by luck before the change was made in icingaweb2?)

## Steps to Reproduce (for bugs)
After the graphs load for the first time, select "2 Weeks" instead of the default "1 day" (any change triggers the bug, until one forces a refresh of the page manually) and wait about 10 seconds, watch the graph image(s) disappear

## Context
No particular context, just normal usage watching graph values history. If you want me to submit this as a icingaweb2 issue please tell me.

## Your Environment

* Module version (System - About): 1.2.2 (tested with previous versions, all affected since icingaweb2 2.11.3)
* Icinga Web 2 version and modules (System - About): 2.11.3 and 2.11.4
* Icinga 2 version (`icinga2 --version`): not relevant
* Graphite (carbon, web, whisper) version: not relevant
* Operating System and version: not relevant
* Webserver, PHP versions: not relevant

**Comment by spacefreak86** [comment]
Hello together
I ran into the same issue on my productive environment. Is there a roadmap when this bug will bi fixed?

**Comment by BT-Khaled** [comment]
@nilmerg Do I understand correctly that the issue will be resolved in the upcoming version of Icinga Web?

**Comment by nilmerg** [comment]
Maybe. It's not planned yet.

**Comment by HOSTED-POWER** [comment]
Having the same issues here, pretty annoying, a fix would be fantastic! :)

**Comment by hege-li** [comment]
> Just add in ../TimeRangePicker/CommonForm.php -> function createSelect() ->
> 
> element−>setAttrib(′onchange′,′(".timerangepicker-container").load(window.location.href + " .timerangepicker-container")');
> 
> This will only reload the div and the Graph will no longer disappear.

Thanks, dunno if it's correct but atleast it fixes it here, clean patch:

```
--- graphite/application/forms/TimeRangePicker/CommonForm.php      2023-09-21 14:41:07.000000000 +0300
+++ graphite/application/forms/TimeRangePicker/CommonForm.php   2024-02-05 09:22:30.733709599 +0200
@@ -134,6 +134,8 @@
             'Zend_Form_Decorator_ViewHelper'    => $decorators['Zend_Form_Decorator_ViewHelper']
         ]);

+        $element->setAttrib('onchange','$(".timerangepicker-container").load(window.location.href + " .timerangepicker-container")');
+
         return $element;
     }

```

Open for a year already, can paying customer plead for official fix?

**Comment by menanceci** [comment]
> or a year already, can paying customer

Actually the same as in my post  ;o)
