### ISSUE TITLE
Dashboard with links to open in full page.

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingaweb2#5070]
hello, 

## Description problem

we have a large number of links that we are now bookmarking in the browser of the user that is important for him or for the group.
So with every new user or link we have to install/update it in his personal browser.
So it would be handy if this would also be directly in the icingaweb.

## Currently available
currently there is the possibility to create/change dashboard settings.
If you select the link in the settings page, it will open a 2nd screen next to it and show the results.
It would be handy if he wouldn't open as a 2nd screen next to it , but as a full page.

![dashletfullpage](https://github.com/Icinga/icingaweb2/assets/29303758/7b61a21a-9430-42a1-839c-d0b37a640bc8)

## Proposal
wouldn't it be possible to provide a checkbox that would allow it to say that you want the link to open in a 2nd screen, or that you want to open as a full page.

And if we could then pass a viewonly parameter, icingaweb2/dashboard/settings?viewonly, which only gives the lines followed by the links to the different pages, that would be fantastic. (no add/delete/.. buttons)

Do you think this proposal could be something useful for the icingaweb2 ?

regards,
Geert

**Comment by nilmerg** [comment]
Have you tried `Ctrl` + `Click` on the links?

**Comment by gbin2265** [comment]
but this is opening a full new tab, and here I would like to continue surfing in the same page.

if only an option could be added to the viewonly such as extra parameter FULLPAGE, I would be very happy ;-)
(why not, just one extra parameter at the viewpage.)

icingaweb2/dashboard/settings?viewonly&fullpage

I was already learning how to copy your settings page and make it viewonly , but then I thought it might be useful for other users as well.  So the question is what do you think of it.

**Comment by nilmerg** [comment]
Well, if that doesn't suit you, I'm afraid there is no option left. What you're talking about is a settings view. Not a view a user should regularly visit or interact with. Let alone save as bookmark. As such, it's use is very specific and such an option you're talking about is not suitable. You should think about not using dashlets, but a custom menu entry. There you have the functionality you're looking for.

**Comment by gbin2265** [comment]
I have already tested the menu entry but due to the number (more than 200 for one option) it is not usable.

I'm going to look into making my own module (newbie) that can do the view of the dashboard for our organization.
Starting with my last proposal and using the current dashboard ini file , and than later when I have the chance with other ini files with additional options.

In any case, thanks for the answer.

**Comment by nilmerg** [comment]
Two hundred? Yeah, a custom solution sounds good for such a specific case. (At least I'm not aware that such a high number of dashlets is common.)

**Comment by gbin2265** [comment]
I'm posting this last comment so that maybe it can help others who are having the same problem.

sometimes it's too easy :-)

I just created an empty module (name module dashlinks) and edit the file
File : configuration.php

```
<?php
$section = $this->menuSection(N_('Dashlinks'), array('icon' => 'globe'));
$mapModule = $section->add(N_($this->translate('DASH Links')), array(
    'icon' => 'thumbs-up',
    'description' => $this->translate('Dash links'),
    'url' => 'doc/module/toc?moduleName=dashlinks',
    'priority' => 1
));
```

go to the folder doc en make the file 01-name.md

In the file I make the menustructure + the links 

I use this structure for the link so that it opens a completely new page :

```
* <a href="icingadb/services?service.vars.variablename=1" data-base-target="_main">list of services for variablename</a>
```

And the doc menu goes very fast ! 

Why didn't i see this before :-)
Can start building all my links from the browser to the doc file and reduce a lot of hostgroups and servicegroups.

**Comment by nilmerg** [comment]
Pure lifehack, I'd say :rofl:
