### ISSUE TITLE
floats in user defined variables displayed with asteriskes

### ISSUE THREAD

**Issue by philfry** [Icinga/icingaweb2#5072]
## Describe the bug
Looking at the host or service tab, the values of variables containing a float are asterisk'ed out.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. add a custom variable containing a floating point number to a service or a host
2. look at the service or host tab

## Expected behavior
The float is displayed correctly.

## Screenshots
![Screenshot from 2023-08-02 13-01-17](https://github.com/Icinga/icingaweb2/assets/1649785/ecf65296-06ef-47f8-ae50-39669848c5cd)
![Screenshot 2023-08-02 at 12-57-43 rtl433 thermo-   hygrometer Chillzimmer raspi01 intranet unixadm org Services Icinga Web](https://github.com/Icinga/icingaweb2/assets/1649785/b9b62d84-1663-4b86-8517-bf8edc72c7f6)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version 	2.11.3
Git Commit 	f917436a894c1f4148a9c3d6a27f9c20f204e44f
PHP-Version 	8.0.29
Git Commit Datum 	2022-12-14
icinga/icinga-php-library 	0.10.1
icinga/icinga-php-thirdparty 	0.11.0
Geladene Module
monitoring 		2.11.3 	[Configure](https://argos.unixadm.org/icingaweb2/config/module/?name=monitoring)
statusmap 		0.0.0 	[Configure](https://argos.unixadm.org/icingaweb2/config/module/?name=statusmap)
```
* Web browser used: firefox
* Icinga 2 version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.8-1)

Copyright (c) 2012-2023 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Oracle Linux Server
  Platform version: 8.8
  Kernel: Linux
  Kernel version: 5.15.0-101.103.2.1.el8uek.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 8.5.0
  Build host: unknown
  OpenSSL version: OpenSSL 1.1.1k  FIPS 25 Mar 2021

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* PHP version used (`php --version`):
```
PHP 8.0.29 (cli) (built: Jun  7 2023 17:25:45) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.29, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.29, Copyright (c), by Zend Technologies
```
* Server operating system and version: Oracle Linux 8.8

**Comment by slalomsk8er** [comment]
This isn't a bug but a feature of Icingaweb2.
In the settings there is a option to protect variables from being shown and a default matched.
tem**pw**arn matches `*pw*` so this has nothing to do with the value being a float.

**Comment by philfry** [comment]
Spooky. I meant: Nice.
Thanks for the info, I guess I'll either rename my variables or just leave it as it is :D
