### ISSUE TITLE
IcingaDB can't show current status if secondary redis is unavailable

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icingaweb2#5073]
I installed an HA Icinga 2 Setup, each instance got its local icingadb, icingadb-redis running. 

I defined two redis backends for the IcingaDB Web Module:

```
[root@vwm1 ~]# cat /etc/icingaweb2/modules/icingadb/redis.ini

[redis1]
host = vwm1.localdomain

[redis2]
host = vwm2.localdomain
```

Firstly: When the `redis1` is not reachable the Webinterface will warn me, if the second `redis2` is not reachable I won't get any warning. 

When redis runs on localhost instead of 0.0.0.0, the heartbeat is missing. 
```
   CGroup: /system.slice/icingadb-redis.service
           └─13798 /usr/bin/icingadb-redis-server 127.0.0.1:6380
```
The IcingaDB knows it's running locally. Only the Webinterface tries to reach it from another host. 

```
cat /etc/icingadb/config.yml: 
[...]
redis:
  host: 127.0.0.1
  port: 6380
```

Excerpt from the journal -u icingadb:

```
vwm2.localdomain icingadb[8841]: heartbeat: Waiting for Icinga heartbeat
vwm2.localdomain icingadb[8841]: heartbeat: Waiting for Icinga heartbeat
```

## Whats happening? 

When in this current state - the second redis is not connected to Icinga Web 2, I won't get any new results shown/not even executed (cannot verify) in the Webinterface. Which defeats the purpose of having a HA setup. 
As soon as I stop Icinga2 on `vwm2`, checks are scheduled without any problem. 
In addition if IcingaWeb2 can reach the second redis again the checks will run properly. 

## Screenshots

<img width="616" alt="late checkresult" src="https://github.com/Icinga/icingaweb2/assets/7584938/2f962753-4411-4102-9f51-69b1fb18189d">

* Icinga Web2: 2.11.4
* Icinga DB: 1.0.2
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.14
* PHP version used (`php --version`):
* Server operating system and version: Rhel8

**Comment by nilmerg** [comment]
I cannot really decipher if we're talking about an Icinga DB or Icinga DB Web problem :thinking:

**Comment by mkayontour** [comment]
I can't tell either, I don't know if the web doesn't show the status or if the database/redis has not the actual informations stored. Can you help me to check where the information is outdated?

**Comment by nilmerg** [comment]
The source tab of a host or service also shows raw data from Redis in the *Volatile State Details* section. If this shows data if at least one Redis is online and reachable for Web, Web isn't the problem.

**Comment by mkayontour** [comment]
I checked, the issue is not on IcingaWeb - I'll open a new one for icinga2/db
