### ISSUE TITLE
Hide _override_servicevars in Host Details page

### ISSUE THREAD

**Issue by wp-perc** [Icinga/icingaweb2#5076]
## Is your feature request related to a problem? Please describe.
Contents of custom var `_override_servicevars` are displayed in the Host page alongside with all other custom vars.
During time this can become a hindrance, because the number of overrides is bound to increase.
Can we find a way to remove this variable from the visualization?

![image](https://github.com/Icinga/icingaweb2/assets/47447882/03ce8563-e2b1-460d-89a2-9cca0cb1d42b)

## Describe the solution you'd like
The obvious solution is to hide all overrides.

## Describe alternatives you've considered
Use `Protected custom variables` to hide the values will result in a more compact view, but doesn't completely remove the variable itself.
![image](https://github.com/Icinga/icingaweb2/assets/47447882/03a0e08f-5189-444e-98b1-0cd2ce5700d6)
![image](https://github.com/Icinga/icingaweb2/assets/47447882/e913eb6b-4c26-416d-b166-9d84b8a31a69)

## Additional context
Icingaweb2 version 2.10.4

**Comment by nilmerg** [comment]
This is a director specific variable, right? Then it's the director's job to hide it. Possible once https://github.com/Icinga/icingaweb2-module-director/pull/2445 is merged/finished.
