### ISSUE TITLE
Full text search over check output

### ISSUE THREAD

**Issue by sgrrr** [Icinga/icingaweb2#5119]
Hi, we were wondering if it is possible to implement a search that uses the check output (the return string of the service checks) so that you can search for contents of the return strings.

Maybe this could be implemented as a kind of data field to filter for?

**Comment by nilmerg** [comment]
Hi,

this is already possible? It's called the `output` and `long_output`.

Or where are you expecting it and missed it?

**Comment by sgrrr** [comment]
Thx. We obviously did not find it.
