### ISSUE TITLE
Zend_Controller_Request_Http not found after migration to 2.12.0

### ISSUE THREAD

**Issue by darxmurf** [Icinga/icingaweb2#5122]
Hi all,

Server running Debian 12 with hand compiled php 8.1.23 and apache 2.4.57.

Icingaweb2 was running fine on version 2.11.4.
Just moved to 2.12.0 and got this message when loading the main page

`
Fatal error: Uncaught Error: Class "Zend_Controller_Request_Http" not found in /var/www/icingaweb2/library/Icinga/Web/Request.php:14 Stack trace: #0 /var/www/icingaweb2/library/Icinga/Application/ClassLoader.php(275): require() #1 /var/www/icingaweb2/library/Icinga/Application/EmbeddedWeb.php(89): Icinga\Application\ClassLoader->loadClass() #2 /var/www/icingaweb2/library/Icinga/Application/Web.php(92): Icinga\Application\EmbeddedWeb->setupRequest() #3 /var/www/icingaweb2/library/Icinga/Application/ApplicationBootstrap.php(388): Icinga\Application\Web->bootstrap() #4 /var/www/icingaweb2/library/Icinga/Application/webrouter.php(105): Icinga\Application\ApplicationBootstrap::start() #5 /var/www/icingaweb2/public/index.php(4): require_once('...') #6 {main} thrown in /var/www/icingaweb2/library/Icinga/Web/Request.php on line 14`

It looks like libraries changed as there is no "/library/vendor/" folder anymore. I tried to copy it back from 2.11.4 but it did not fix the issue. So, this Zend library is missing somewhere.

Thanks for you help.

**Comment by lippserd** [comment]
Hi,

What means "just moved"?

**Comment by darxmurf** [comment]
Sorry my first message was probably not clear enough.

Yes it's a source installation but everything was running fine under 2.11.4.
I simply replaced the content of my /var/www/icingaweb2/ with the files from version 2.12.0. (which is basically what I did to upgrade to version 2.11.4 last time)

The only module not installed on my server is PDFExport as I don't need that.

**Comment by yhabteab** [comment]
> Yes it's a source installation but everything was running fine under 2.11.4.

Then check the requirements for Icinga Web 2.12 to install it from source please. Don't just copy paste contents!

> I guess you've installed from source. Please check your deps: https://github.com/Icinga/icingaweb2/blob/main/doc/02-Installation.md#installing-requirements-from-source-

**Comment by darxmurf** [comment]
> > Yes it's a source installation but everything was running fine under 2.11.4.
> 
> Then check the requirements for Icinga Web 2.12 to install it from source please. Don't just copy paste the contents!
> 
> > I guess you've installed from source. Please check your deps: https://github.com/Icinga/icingaweb2/blob/main/doc/02-Installation.md#installing-requirements-from-source-
> 
> > The only module not installed on my server is PDFExport as I don't need that.
> 
> You need also to upgrade `icinga-php-library` & `icinga-php-thirdparty`

My bad, I was cloning the default branch for `icinga-php-library` & `icinga-php-thirdparty`. Everything is fine now. Sorry about that folks.
