### ISSUE TITLE
check in MigrationManager.php not compatible with postgresql

### ISSUE THREAD

**Issue by jlammrs** [Icinga/icingaweb2#5129]
## Describe the bug
In the web interface I get an error
SQLSTATE[22023]: Invalid parameter value: 7 ERROR: unrecognized privilege type: "CREATE", query was: SELECT has_table_privilege(:user, :table, :privilege) AS table_privilege_granted
PostgreSQL doesn't have the CREATE privilege.

In the postgres log I see: 
`2023-09-27 09:09:54.232 UTC [4154218] icinga2@icinga2 ERROR:  unrecognized privilege type: "CREATE"
2023-09-27 09:09:54.232 UTC [4154218] icinga2@icinga2 STATEMENT:  SELECT has_table_privilege($1, $2, $3) AS table_privilege_granted
`

I removed 'CREATE' in the  public function getRequiredDatabasePrivileges() in /usr/share/php/Icinga/Application/MigrationManager.php
return ['CREATE','SELECT','INSERT','UPDATE','DELETE','DROP','ALTER','CREATE VIEW','INDEX','EXECUTE'];
-> return ['SELECT','INSERT','UPDATE','DELETE','DROP','ALTER','CREATE VIEW','INDEX','EXECUTE'];
which fixed the problem for me. I leave it up to someone else to find a more generic solution.

## To Reproduce

1.In the web interface an error occurs when clicking on the settings icon -> system -> migrate

## Expected behavior
Status screen

## Screenshots
![image](https://github.com/Icinga/icingaweb2/assets/15324030/6654d608-7222-416d-bed3-8846c1020504)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.12.0
* Web browser used: Firefox
* Icinga 2 version used (`icinga2 --version`): r2.14.0-1
* PHP version used (`php --version`): 8.1.2-1ubuntu2.14
* Server operating system and version: Ubuntu 22.04.3 LTS
*  Database: Postgres 14

## Additional context
--

**Comment by bisontim** [comment]
It happens with (PostgreSQL) 15.3  as well

**Comment by mbanck** [comment]
Will there be a point release to fix this soon?
