### ISSUE TITLE
Icinga DB Web restrictions using wildcards not working anymore

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#5131]
With the upgrade to Icinga Web v2.12, you may notice that views in Icinga DB Web may not show the desired results anymore you or your users are accustomed to.

The problem is a change in our filter syntax, **which only affects Icinga DB Web**.

The equal/unequal (`=`/`!=`) operators don't support wildcard matching (`*name*`) anymore. Instead, the new like/unlike (`~`/`!~`) operators support wildcards.

If you have restrictions for `icingadb/filter/objects`, `icingadb/filter/hosts` or `icingadb/filter/services` which use these, you'll have to change them.

For example, `host.name=*name*` must be changed to `host.name~*name*`.

The next release of **Icinga DB Web in version 1.1.1** will include proper migration procedures which will adjust all your roles and navigation items at once.

**Comment by jan-kantert** [comment]
That should really be highlighted as breaking change. This breaks all kind of integrations for us. For instance our desktop clients or controllers relying on the (json) output of some requests.

**Comment by nilmerg** [comment]
That's another bug: https://github.com/Icinga/icingadb-web/issues/911

**Comment by nilmerg** [comment]
Icinga DB Web v1.1.1 has been released on Nov 16, 2023.
