### ISSUE TITLE
Icingaweb2 Zend Issue

### ISSUE THREAD

**Issue by whizps** [Icinga/icingaweb2#5132]
## Describe the bug
When trying to add a user to a membership in the icingaweb2 portal the following error below occurs, steps below.

```
Header: Zend_Form_Element::_filterValue(): Argument #2 ($key) must be passed by reference, value given

#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}()
#1 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Form/Element.php(615): array_walk_recursive()
#2 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Form/Element.php(1415): Zend_Form_Element->getValue()
#3 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Form/Element/Multi.php(268): Zend_Form_Element->isValid()
#4 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Form.php(2296): Zend_Form_Element_Multi->isValid()
#5 /usr/share/php/Icinga/Web/Form.php(1297): Zend_Form->isValid()
#6 /usr/share/php/Icinga/Web/Form.php(1173): Icinga\Web\Form->isValid()
#7 /usr/share/icingaweb2/application/controllers/GroupController.php(239): Icinga\Web\Form->handleRequest()
#8 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(516): Icinga\Controllers\GroupController->addmemberAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#10 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch()
#11 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch()
#12 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#14 {main}

```
## To Reproduce

1. click the cogwheel "settings at the bottom by my name.
2. Access control > user groups
3. select "Administrator" user group.
4. click "+add new member" and select the member, then click add > Error occurs.

## Expected behavior
That the user i selected should be added to the correct group without any errors.

## Screenshots
[If applicable, add screenshots to help explain your problem.](https://imgur.com/a/tbVm9iu)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

    Icinga Web 2 version
    2.12.0

    Used modules and their versions (System - About)
    director 1.10.2
    doc 2.12.0
    icingadb 1.1.0
    incubator 0.20.0
    migrate 2.12.0

    Web browser used
    Chrome

    Icinga 2 version used (icinga2 --version)
    icinga2 - The Icinga 2 network monitoring daemon (version: r2.14.0-1)

    PHP version used (php --version)
    PHP 8.1.2-1ubuntu2.14 (cli)
    With Zend OPcache v8.1.2-1ubuntu2.14

    Server operating system and version
    Ubuntu 22.04.3 LTS (Jammy Jellyfish)

**Comment by whizps** [comment]
Hi @raviks789 

The fix you posted, would this be as simple as to just replace my entire file with the contents here? https://github.com/Icinga/icinga-php-thirdparty/blob/b5de80432ea84fdfb3022598ccc2c65a6c0da9a8/patches/shardj-zf1-future.patch

**Comment by raviks789** [comment]
Hi @whizps 

Not exactly. You should replace the patch file `shardj-zf1-future.patch` in the directory `usr/share/icinga-php/vendor/patches` with the contents has you mentioned and apply the patch using the  following command:
`patch -p 1 -d /usr/share/icinga-php/vendor -f < patches/shardj-zf1-future.patch`

**Comment by whizps** [comment]
Hi @raviks789 

Im getting this.

`/usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Form# patch -p 1 -d /usr/share/icinga-php/vendor -f < /usr/share/icinga-php/vendor/patches/shardj-zf1-future.patch
patching file vendor/shardj/zf1-future/library/Zend/Form/Element.php
Hunk #1 FAILED at 595.
Hunk #2 FAILED at 612.
2 out of 2 hunks FAILED -- saving rejects to file vendor/shardj/zf1-future/library/Zend/Form/Element.php.rej`

**Comment by raviks789** [comment]
Hi @whizps ,

You could also try replacing the line 615 in vendor/shardj/zf1-future/library/Zend/Form/Element.php as below.

Current Code:
```
array_walk_recursive($valueFiltered, [$this, '_filterValue']);
```

Replaced Code:
```
array_walk_recursive($valueFiltered, function (&$val, $key) {
  $this->_filterValue($val, $key);
});
```

**Comment by whizps** [comment]
Hi @raviks789 

Same error after replacing the code. looks like below now in my file after the change.

```
 public function getValue()
    {
        $valueFiltered = $this->_value;

        if ($this->isArray() && is_array($valueFiltered)) {
            array_walk_recursive($valueFiltered, function (&$val, $key) {
              $this->_filterValue($val, $key);
            });
```

**Comment by raviks789** [comment]
Hi @whizps ,

I could not reproduce the issue. 

Could you paste the entire `vendor/shardj/zf1-future/library/Zend/Form/Element::getValue()` method here?

**Comment by whizps** [comment]
Hi @raviks789 ,

Do you mean the entire Element.php file? or anything specific from that? I dont have a file named as in your path.

**Comment by raviks789** [comment]
Just the `getValue()` method would be sufficient for now.

**Comment by whizps** [comment]
Hi @raviks789 ,

Well not exactly sure which one you want since if ind three getValues in the file and none with the Element::getValue()

here's the ones i have.

```
/**
     * Retrieve filtered element value
     *
     * @return mixed
     */
    public function getValue()
    {
        $valueFiltered = $this->_value;

        if ($this->isArray() && is_array($valueFiltered)) {
            array_walk_recursive($valueFiltered, function (&$val, $key) {
              $this->_filterValue($val, $key);
            });
        } else {
            $this->_filterValue($valueFiltered, $valueFiltered);
        }

        return $valueFiltered;
    }
```

```
public function isValid($value, $context = null)
    {
        $this->setValue($value);
        $value = $this->getValue();

        if ((('' === $value) || (null === $value))
            && !$this->isRequired()
            && $this->getAllowEmpty()
        ) {
            return true;
        }
```

```
/**
     * Retrieve error messages and perform translation and value substitution
     *
     * @return array
     */
    protected function _getErrorMessages()
    {
        $translator = $this->getTranslator();
        $messages   = $this->getErrorMessages();
        $value      = $this->getValue();
        foreach ($messages as $key => $message) {
            if (null !== $translator) {
                $message = $translator->translate($message);
            }
            if (is_string($value)) {
                $messages[$key] = str_replace('%value%', $value, $message);
            } elseif ($this->isArray() || is_array($value)) {
                $aggregateMessages = [];
                foreach ($value as $val) {
                    $aggregateMessages[] = str_replace('%value%', $val, $message);
                }
                $aggregateMessages = array_unique($aggregateMessages); //prevent repeating the identical error message for multichoice-items
                if (count($aggregateMessages)) {
                    if ($this->_concatJustValuesInErrorMessage) {
                        $values = implode($this->getErrorMessageSeparator(), $value);
                        $messages[$key] = str_replace('%value%', $values, $message);
                    } else {
                        $messages[$key] = implode($this->getErrorMessageSeparator(), $aggregateMessages);
                    }
                }
            } else {
                $messages[$key] = str_replace('%value%', (string) $value, $message);
            }
        }
        return $messages;
    }
```

**Comment by raviks789** [comment]
Hi @whizps ,

I was looking for 1st code snippet. It looks correct and I have the same code as well. Could you share the error stacktrace (like the one in the description of the issue) that you are encountering now.

**Comment by whizps** [comment]
Hi @raviks789 ,

Oh well, it seems like it works now, even though the patch was applied with errors? But i guess that's expected then? might just be me that did not understand the output correctly! But a bit weird it produces errors.

Thanks for the help.
