### ISSUE TITLE
FreeBSD: Unable to set default downtime parameters on Icingaweb

### ISSUE THREAD

**Issue by gettoknowmii** [Icinga/icingaweb2#5135]
## Describe the bug
The settings describe on  https://icinga.com/docs/icinga-web/latest/modules/monitoring/doc/03-Configuration/ does not work.
# vim /usr/local/etc/icingaweb2/modules/monitoring/config.ini

[settings]
hostdowntime_all_services = 1
hostdowntime_comment_text = "Host is going down for maintainance"

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. install configure icinga on Freebsd
2. try changing the defaults to always downtime all services on a host per https://icinga.com/docs/icinga-web/latest/modules/monitoring/doc/03-Configuration/

## Expected behavior
when someone try to set downtime in the web UI, all services should be check by default and the message should be populated by default

## Screenshots
<img width="650" alt="image" src="https://github.com/Icinga/icingaweb2/assets/84911898/69e2ab80-fa41-40c0-8e61-3694e467b9e3">

## Your Environment
FreeBSD 13.2
icingaweb2-php81-2.11.4_1      Next generation web interface for Icinga 1 and 2
icinga2-2.14.0                 Monitoring and management system for hosts, services and networks

**Comment by nilmerg** [comment]
Hi,

works for me with a standard install of v2.11.4 and v2.12.0. Since you're using a non-standard configuration directory, make sure it is used by Icinga Web. Other than that, I cannot be any more of assistance, since we don't provide FreeBSD ports on our own. Contact the actual provider please.
