### ISSUE TITLE
Error during opening a navigation root item

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icingaweb2#5177]
We did a big Upgrade from our environment: 
- Icinga (2.13.8 -> 2.14.2), 
- Icingaweb2 (2.11.4 -> 2.12.1) 
- moved to icingadb. 

After this, we recognized, that we got an error clicking on an navigation item, created in the "navigation"-tab in the user account menu. 

![image](https://github.com/Icinga/icingaweb2/assets/38723488/652f3c9a-3d43-4653-b6b5-8b79f64f033e)

The root menu item is created like this:
![image](https://github.com/Icinga/icingaweb2/assets/38723488/0968b5e7-4970-4822-8f54-e56ca3595022)

and under this we created some custom views like this (a view with critical update service checks):
![image](https://github.com/Icinga/icingaweb2/assets/38723488/edcad149-6685-4618-babe-320fe8f43392)

While the views works perfectly as usal, the root menu entry throws the error from above. A little workarround - so that colleagues are not shocked by the error message - is to write some nonsense into the url field. 
![image](https://github.com/Icinga/icingaweb2/assets/38723488/713167a9-313c-424e-82a6-c22ad7e2acc0)
So they only get a small message like "page not found". 
![image](https://github.com/Icinga/icingaweb2/assets/38723488/a93a790c-0b11-4bae-abe6-d6d579ad8ac7)

These are the items in navigation.ini
```
[IT Custom Views]
type = "menu-item"
target = "_main"
users = "*"
groups = "*"
owner = "xxx"

[Critical Server Updatestatus (Liste)]
type = "menu-item"
parent = "IT Custom Views"
target = "_main"
url = "icingadb/services?(service.state.soft_state=2&host.vars.Verwalter~ST%2A)&(service.name_ci~%2Aupdatestatus%2A|service.name_ci~%2Aserverupdate%2A)&sort=host.display_name&columns=service.state.soft_state%2Cservice.state.last_state_change%2Cservice.icon_image.icon_image%2Cservice.display_name%2Cservice.host.display_name%2Cservice.state.output%2Cservice.state.performance_data%2Cservice.state.is_problem%2Chost.vars.verwalter&limit=100"
owner = "xxx"
```

Funny thing besides:
Doing this with an own module, you get a list with the child navigation object - like it should and it worked also before.
![image](https://github.com/Icinga/icingaweb2/assets/38723488/9a35d106-19be-4282-8809-cc5a04e8384c)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.12.1
* Web browser used: Firefox, Edge
* Icinga 2 version used (`icinga2 --version`): 2.14.1
* PHP version used (`php --version`): 8.0.3
* Server operating system and version: RHEL9.3

**Comment by christoph2497** [comment]
ref/NC/806421
