### ISSUE TITLE
Wrong sorting in access control

### ISSUE THREAD

**Issue by Nathaniel-Donahue** [Icinga/icingaweb2#5187]
Hi there,

under Access Control > Roles, there's an option to sort by name, and when you press that button, it actually sorts something, but not correctly.

I expect it to sort something like this:
Apples
Bannans
Cherrys

This behavior seems to occur in Icinga Web 2 version 2.12.1

Regards,

**Comment by tbauriedel** [comment]
ref/NC/807683

**Comment by nilmerg** [comment]
Duplicate of #4789

**Comment by nilmerg** [comment]
Will be fixed with v2.12.2.
