### ISSUE TITLE
Underscores in DB backend names not working

### ISSUE THREAD

**Issue by akellar** [Icinga/icingaweb2#5204]
## Describe the bug
When using MariaDB database back end, underscores in DB names result in the Icingaweb2 application not properly accessing the DB, even though underscores are permitted in DB names by MySQL/MariaDB (provided they don't begin with an underscore).

## To Reproduce
I have a live example here in community forums, if you need more troubleshooting steps or more information please let me know.
https://community.icinga.com/t/setting-up-icinga-web-db-for-local-auth-cannot-access-db/13349

## Expected behavior
IcingaWeb2 be able to access a MariaDB database authentication back end with an underscore in the DB name.

## Screenshots
Screenshots and clear examples shown in link provided in "To Reproduce" section.

## Your Environment
Debian 12 Bookworm environment, single master all databases on localhost (had tried a remote MariaDB server as well - experienced same issue)

* Icinga Web 2 version and modules (System - About): 2.12.1
* Web browser used: Firefox and Brave
* Icinga 2 version used (`icinga2 --version`): r2.14.2-1
* PHP version used (`php --version`): 8.2.7
* Server operating system and version: Debian 12 Bookworm

## Additional context
Detailed context and examples provided in the link. Please let me know if you need anything else.

**Comment by nilmerg** [comment]
Hi,

please have a look [here](https://github.com/Icinga/icingaweb2/issues/5147#issuecomment-1808334890)
