### ISSUE TITLE
PHP deprecation errors

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingaweb2#5221]
## Describe the bug
The host didn't have any notes, but when I navigate to the detail view of the host, I got this warning.
<img width="626" alt="Bildschirmfoto 2024-05-22 um 10 03 39" src="https://github.com/Icinga/icingaweb2/assets/57616252/0e55b78e-74a7-412d-a17d-4d42d622360d">

**Comment by nilmerg** [comment]
How can this happen? I have plenty of hosts without notes (since ages) and never saw this.

**Comment by yhabteab** [comment]
I don't know! I also did have plenty of other hosts without notes and I don't/never face that error, but obviously, as you can see in the screenshot above, I got this warning for this single host.
