### ISSUE TITLE
Generate CSV/JSON for History in Icingaweb2 2.12.1 with Icingadb doesn't work

### ISSUE THREAD

**Issue by ocstaron** [Icinga/icingaweb2#5231]
## Describe the bug
When creating the CSV/JSON for History the generated file consists of a lot of error messages like this:

b>Fatal error</b>:  Uncaught ErrorException: session_name(): Session name cannot be changed after headers have already been sent in /usr/share/php/Icinga/Web/Session/Php72Session.php:20
Stack trace:
#0 [internal function]: Icinga\Application\ApplicationBootstrap-&gt;Icinga\Application\{closure}()
#1 /usr/share/php/Icinga/Web/Session/Php72Session.php(20): session_name()
#2 /usr/share/php/Icinga/Web/Session/PhpSession.php(167): Icinga\Web\Session\Php72Session-&gt;open()
#3 /usr/share/php/Icinga/Web/Controller/ActionController.php(579): Icinga\Web\Session\PhpSession-&gt;write()
#4 /usr/share/php/Icinga/Web/Controller/ActionController.php(525): Icinga\Web\Controller\ActionController-&gt;shutdownSession()
#5 /usr/share/icingaweb2/modules/icingadb/application/controllers/ErrorController.php(58): Icinga\Web\Controller\ActionController-&gt;postDispatch()
#6 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(521): Icinga\Module\Icingadb\Controllers\ErrorController-&gt;postDispatch()
#7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action-&gt;dispatch()
#8 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher-&gt;dispatch()
#9 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front-&gt;dispatch()
#10 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web-&gt;dispatch()
#11 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#12 {main}

On our old server with same Icingaweb2 version and monitoring module it seems to work.

Also generating the csv for hosts or services for example work on the new host, but not for history.

## To Reproduce

Generate a CSV in the History (event or notification) view.

## Expected behavior

CSV with list of events or notification is generated.

## Your Environment
Oracle Linux 9
Icinga Web 2 Version	2.12.1
PHP-Version	8.0.30
icinga/icinga-php-thirdparty	0.12.1
icinga/icinga-php-library	0.13.2
defaultdash		0.0.0
director		1.11.1
doc		2.12.1
grafana		2.0.3
icingadb		1.1.1
incubator		0.22.0
ipl		v0.5.0
jira		1.3.4	
pdfexport		0.11.0name=pdfexport)
reactbundle		0.9.0

**Comment by nilmerg** [comment]
Please upgrade Icinga DB Web to v1.1.2.

**Comment by ocstaron** [comment]
ok, thanks. It worked.
