### ISSUE TITLE
impossible to export an event in json with icingaweb2

### ISSUE THREAD

**Issue by fdumont35** [Icinga/icingaweb2#5261]
## Describe the bug
Hi, for an application, I want to automatically retrieve the entire content of the output field of an old event.
![image](https://github.com/user-attachments/assets/b6bfba41-2f23-4aa7-a807-bd0368f244a2)

I can't do that with icinga2 api.
With icingaweb2  / eventhistory I have only the first line of the Output field.
So I try with this path : XXX/icingaweb2/monitoring/event/show?type=hard_state&id=22790006&format=json
but json export does not work. It is ok with pdf, but not with json and csv format. 
Can you fix this ?

## To Reproduce
Try to get json response with postman of in a web browser

## Your Environment
Program Version | r2.14.2-1

Thank you for your help

**Comment by nilmerg** [comment]
Hi,

I'd rather suggest to use Icinga DB Web's export functionality as basis for your app.

The monitoring module will not receive such an addition anymore.

**Comment by fdumont35** [comment]
Hi Nilmerg,
 It is not possible de add a parameter to icingaweb2/monitoring/list/eventhistory to export in json not only the first line, but all the content of ouput field ?

**Comment by nilmerg** [comment]
Possible, probably. Worth the effort, not really. :wink:

**Comment by fdumont35** [comment]
Thank you for your response, one last question :
Do you know why the json export for path icingaweb2/monitoring/event/show is not working ? 
Is it a problem on our side or global to icinga r2.14.2-1 ? You will not plan to fix this ?

**Comment by nilmerg** [comment]
The reason is, it is not implemented. In Icinga **Web** 2. (Specifically, the *monitoring* module) Icinga DB Web is the successor of the monitoring module, hence why I'm suggesting you to switch.
