### ISSUE TITLE
PluginOutputRenderer gets called twice in monitoring module

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2#5271]
## Describe the bug
The render is called seperately for output and long_output wich causes the PluginOutputRenderHook to be called twice see here:

https://github.com/Icinga/icingaweb2/blob/main/modules/monitoring/application/views/scripts/show/components/output.phtml

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Create a PluginOutputHook implementation
2. implement function render($command, $output, $detail)

## Expected behavior
* Use some parameter to let the Pluginoutput hook decide if it is about the output or the long_output.

or change the output.html into something like this:
```php
<?= $this->pluginOutput($object->output."\n".$object->long_output, false, $object->check_command) ?>
```
this would also get rid of the space between output and long_output.

## Screenshots
![Screenshot 2024-10-04 155921](https://github.com/user-attachments/assets/e7695ccf-2cfe-4ca6-b188-cf21fff249f2)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.12.2

Im happy to provide a pull request.

Best Regards
Nicolas

**Comment by nilmerg** [comment]
> or change the output.html into something like this:

:+1: (But with spaces around the concatenation operator (`.`))

Feel free to open a PR, thanks :D
