### ISSUE TITLE
PHP 8.1.27 - Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /usr/share/php/Icinga/File/Csv.php on line 40

### ISSUE THREAD

**Issue by Tqnsls** [Icinga/icingaweb2#5279]
## Describe the bug
I want to print host-objects with some custom-vars.
Each line that contains a null value in the custom-var, raises a php error.

Example command:
`icingacli monitoring list hosts --format csv --columns "host,_host_costcenter_name"`

Example Output:
![image](https://github.com/user-attachments/assets/15be122e-32b9-431f-9d83-3b965c4c349b)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.12.1
* Icinga 2 version used (`icinga2 --version`): r2.14.2-1
* PHP version used (`php --version`): 8.1.27
* Server operating system and version: RHEL 9
* Icingaweb-Modules / Packages: ![image](https://github.com/user-attachments/assets/c554688d-cc22-400d-9dc3-62bf732a096c)

**Comment by Tqnsls** [comment]
This seems to create another bug:
If I pull the latest Csv.php this raises all `OK `-service_states as `null`, but it should be printed as `0`.

Example: `icingacli monitoring list services --format csv --columns "service_state" | dos2unix  | sort | uniq -c`

![Image](https://github.com/user-attachments/assets/a0dd0b3b-cdc6-4a2c-97ff-cf68f522e2e2)

@nilmerg  Can we reopen this one or should I create a new referencing issue?

**Comment by nilmerg** [comment]
A new one, please.
