### ISSUE TITLE
After clicking on Check now, the page does not refresh itself

### ISSUE THREAD

**Issue by thrashiii** [Icinga/icingaweb2#5293]
## Describe the bug
If the “Check now” link is clicked in a host or service check, the page does not refresh automatically. The page is only updated when you click on the link a second time.

## To Reproduce
1. click on any service check
2. Click on "Check now" on the right side
3. the "last check" timer continues to run

## Expected behavior
if you click on the "Check now" link, a few seconds later the “last check” display should jump to 0 seconds

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.12.2
* Web browser used: chrome
* Icinga 2 version used (`icinga2 --version`): r2.14.3-1
* PHP version used (`php --version`): PHP 7.4.33
* Server operating system and version: debian 12

**Comment by nilmerg** [comment]
Hi,

are automatic refreshes enabled?

You might also notice this because Web doesn't wait for Icinga to perform the check, it just refreshes 1s afterwards. If Icinga didn't perform the check fast enough, the refresh happens but has no effect.

**Comment by thrashiii** [comment]
Hi,
thank you for your response. Yes, the automatic refreshes are enabled.

I think the refresh after 1 second no longer works properly. 
Normally, when I click on "Check now", the last check status is reset to a few seconds after one second. 
Now it's the case that after clicking on "Check now", it is no longer refreshed at all

**Comment by adriangalbincea** [comment]
I have the same issue, running the latest icinga2 and icingaweb2 with php8.3. I noticed this recently. Auto-refresh is enabled, I tried to toggle that off/on and even to change the refresh to fast but no joy.

**Comment by nilmerg** [comment]
The thing is, it works for me.

Do you have any modules enabled?

And please include a portion of the browser's console when you've clicked *Check Now* again. (e.g. Hit F12, select the *Console* tab, click *Check Now*, right click on any message and choose *Save as…*)

**Comment by adriangalbincea** [comment]
Hi, the only warning I could see is this: 

**Cookie “Icingaweb2” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite,**

it is increasing regardless of the Check now.

See the attached screenshot with all the loaded modules and Icinga version details:
![ice_screenshot_20241125-093157](https://github.com/user-attachments/assets/fc1a9dbd-3925-479e-a872-96081c2b6cb7)

**Comment by adriangalbincea** [comment]
> Hi, the only warning I could see is this:
> 
> **Cookie “Icingaweb2” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite,**
> 
> it is increasing regardless of the Check now.
> 
> See the attached screenshot with all the loaded modules and Icinga version details: ![ice_screenshot_20241125-093157](https://private-user-images.githubusercontent.com/53899277/389462385-fc1a9dbd-3925-479e-a872-96081c2b6cb7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1Mjc5MzcsIm5iZiI6MTczMjUyNzYzNywicGF0aCI6Ii81Mzg5OTI3Ny8zODk0NjIzODUtZmMxYTlkYmQtMzkyNS00NzllLWE4NzItOTYwODFjMmI2Y2I3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwOTQwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTliYjU5ZmVhZTQ5NjA0Y2M4OTE2MmY3OTI1Y2ZiZjRkNGIyY2MwMTVhMmVlNWY0NjkyZDZjYzJjNTgxYTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GYzy2urH1hwdhBXZ_p7J5J89FUSudAR6d9xlf-SpZ8E)

I updated director module and disabled the reactbundle module but still the same

**Comment by nilmerg** [comment]
Hmm, I think im onto something. Just to clarify, if you push *Check Now*, the text gets an outline and keeps it, right?

**Comment by thrashiii** [comment]
Here is a screenshot with loaded modules:
![icinga](https://github.com/user-attachments/assets/2170851d-9e5f-4cfd-a58f-c8a0cbb28d0f)

I can confirm too, that after on push "Check Now" the text keeps an outline.

**Comment by BarbUk** [comment]
Hi,

I have the same issue.
I can confirm too, that after on push "Check Now" the text keeps an outline.

![image](https://github.com/user-attachments/assets/bc3ce646-a729-414d-ac96-789a6d1b72bc)

Auto refresh configuration:
![image](https://github.com/user-attachments/assets/3dae9681-0ee9-42f8-a091-5e067e0197f1)

> And please include a portion of the browser's console when you've clicked Check Now again. (e.g. Hit F12, select the Console tab, click Check Now, right click on any message and choose Save as…)

![image](https://github.com/user-attachments/assets/b6a23618-55c2-49dc-851d-fc85507e87e9)

The request after clicking 'Check now' is:
`/monitoring/service/show?host=XXX&service=XXX`

![image](https://github.com/user-attachments/assets/f9c714f7-4d78-46c9-8d16-6ecc3098714c)

Request copied as curl:
```
curl 'https://xxx.domain.com/monitoring/service/show?host=xxx.host.com&service=Load%20average' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,fr;q=0.8' \
  -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'cookie: Icingaweb2=XXX; icingaweb2-remember-me=XXX; icingaweb2-tzo=3600-0; icingaweb2-session=XXX' \
  -H 'origin: https://xxx.domain.com' \
  -H 'priority: u=1, i' \
  -H 'referer: https://xxx.domain.com/dashboard' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -H 'x-icinga-accept: text/html' \
  -H 'x-icinga-col1-state: /dashboard' \
  -H 'x-icinga-col2-state: /monitoring/service/show?host=xxx.host.com&service=Load%20average' \
  -H 'x-icinga-container: col2' \
  -H 'x-icinga-windowid: longscebfxrp_rofnas' \
  -H 'x-requested-with: XMLHttpRequest' \
  --data-raw 'formUID=IcingaModuleMonitoringFormsCommandObjectCheckNowCommandForm&CSRFToken=XXX&btn_submit=Check+now'
```

This result in a 200OK response with an empty body:

```
< HTTP/2 200 
< date: Wed, 27 Nov 2024 07:35:50 GMT
< server: Apache
< x-content-type-options: nosniff
< referrer-policy: strict-origin-when-cross-origin
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< set-cookie: Icingaweb2=XXX; path=/; secure; HttpOnly
< x-icinga-redirect: %2Fmonitoring%2Fservice%2Fshow%3Fhost%3Dxxx.host.com%26service%3DLoad%2520average
< x-icinga-refresh: 1
< x-icinga-notification: success%20Scheduling%20check..
< vary: Accept-Encoding
< content-length: 0
< content-type: text/html; charset=UTF-8
```

@nilmerg Do you need more information ?

**Comment by nilmerg** [comment]
Thanks. Nope, I think I've reproduced it successfully.

**Comment by thrashiii** [comment]
Thank you, it works...
