### ISSUE TITLE
LDAP memberships cant be fetched - "Failed to fetch membership from configured backend"

### ISSUE THREAD

**Issue by tnagel1** [Icinga/icingaweb2#5294]
## Describe the bug
Can't fetch ldap memberships from configured external Active Directory

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Configure AD/LDAP user and group backend
2. Go to access control -> users -> click on one user (Users are successfully retrieved / Groups are retrieved successfully as well)
3. Error message appears that memberships cant be fetched from backend
ErrorException in /usr/share/icingaweb2/application/controllers/UserController.php:276 with message: Invalid argument supplied for foreach()
5.

## Expected behavior
1. Memberships can be fetched from external AD/LDAP 

## Screenshots
![image](https://github.com/user-attachments/assets/09e099d9-4684-419e-b996-f627c065e7d7)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
![image](https://github.com/user-attachments/assets/b2902b2c-d6bd-43e7-9b34-ebe9040f8c02)

* Web browser used:
* Icinga 2 version used (`icinga2 --version`): 2.13.1-1
* PHP version used (`php --version`): PHP 7.4.30 (cli) (built: Jun  7 2022 08:38:19) ( NTS )
* Server operating system and version: Rocky Linux

## Additional context
Its a build in IcingaWeb from a Storage system. Update isn't possible

**Comment by slalomsk8er** [comment]
I think I tried to fix the problem once but PHP isn't my strength.
Maybe you can find the old discussions we had?

**Comment by tnagel1** [comment]
That would be nice and help maybe further

**Comment by nilmerg** [comment]
Community: [Nope](https://community.icinga.com/search?q=ldap%20%40rivad%20in%3Aposted)
Issues: [Nope](https://github.com/Icinga/icingaweb2/issues?q=is%3Aissue+commenter%3Aslalomsk8er+commenter%3Anilmerg+ldap+invalid+is%3Aclosed)

Feel free to investigate further ;)

**Comment by slalomsk8er** [comment]
@nilmerg I meant this one https://github.com/Icinga/icingaweb2/issues/3935 but now I'm not so sure, if it's related.

**Comment by nilmerg** [comment]
Considering the error message, they're not. The error here rather points to a PHP related issue.
