### ISSUE TITLE
active checks by unvisible Hosts

### ISSUE THREAD

**Issue by littleprivate** [Icinga/icingaweb2#5306]
Hi, 

I've seen in our firewall logs connection attemps from our icinga instance to hosts, that are no longer existing.
We're managing our environment with the director. These hosts, we can see in the firewall logs are not existing in the hosts configuration in Icinga2. I went to the database and checked the table icinga_hosts and there I've found these hosts with active check set to 1.
So my question is, why are there not all hosts visible in the Icingaweb2 Frontend (Director) and how can I prevent Icinga is checking not (more) existing hosts?

Cheers

**Comment by nilmerg** [comment]
Hi, this question is rather suited in our forums: https://community.icinga.com/

But to quickly answer it anyway: The director only affects its own scope. Make sure you don't have those hosts manually configured in `/etc/icinga2`.

**Comment by littleprivate** [comment]
Hi, I am pretty sure not to have any coonfigurations made in /etc/icinga2
If it would be so easy to find any relations in the forum to this issue, I guess you have any links instead of the main URL to the forum and closing it?

**Comment by nilmerg** [comment]
Woah, calm down! There's a search functionality there:

https://community.icinga.com/t/remove-icinga-web2-host-permanently/7891
https://community.icinga.com/t/phantom-notifications-from-deleted-host/8925
