### ISSUE TITLE
SSO / SAML and icingaweb2 authentication Backend at the same time

### ISSUE THREAD

**Issue by swild1981** [Icinga/icingaweb2#5308]
## Is your feature request related to a problem? Please describe.
I need an additional way to authenticate to the icingaweb2. I would like to use SAML or OAuth2 but also the local backend (mariaDB). 

## Describe the solution you'd like
I think the best solution would be to add a button under the "login button" with an customizable link to "EntraID/AzureAD" or "Google" or "Github" and so on, like you have on the icinga community website.

## Describe alternatives you've considered
We tested with the "external" backend, but there is no way to do the local authentication anymore when apache2 is doing the authentication

## Additional context

![Bildschirmfoto 2024-12-17 um 10 41 18](https://github.com/user-attachments/assets/ceb62438-c37a-46f9-8e37-9135925b1727)

**Comment by nilmerg** [comment]
> We tested with the "external" backend, but there is no way to do the local authentication anymore when apache2 is doing the authentication

It certainly is, the web server just needs to be smart enough to conditionally provide/require authentication. Head over to our [forum](https://community.icinga.com/) to get assistance for this if you need it.
