### ISSUE TITLE
[dev.icinga.com #5903] View Icinga 2 cluster information

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#557]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/5903

**Created by mhein on 2014-04-01 07:25:36 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2015-03-30 11:18:12 +00:00_)
Target Version: _Backlog_
Last Update: _2015-05-18 14:03:35 +00:00 (in Redmine)_

---

As a user I want to view Icinga 2 cluster status because I want to know which node is active and get performance information out of it.

A cluster check is a simple check which outputs following information:

    Status Information:  Icinga 2 Cluster Problem: 1 Endpoints (icinga2b) not connected.
    Performance Data:    checkercomponent_checker_idle=52 checkercomponent_checker_pending=1 clusterlistener_icinga2-cluster_num_conn_endpoints=0 clusterlistener_icinga2-cluster_num_endpoints=2 clusterlistener_icinga2-cluster_num_not_conn_endpoints=1 idomysqlconnection_ido-mysql_query_queue_items=0 idopgsqlconnection_ido-pgsql_query_queue_items=0

**Acceptance criteria:**

-   Widget for the landingpage or any other exposed position
-   Display over-all status of the cluster
-   Display detail information about connected endpoints and missing endpoints
-   Display status information about queues

---

**Relations**:

* duplicates [#5903](https://dev.icinga.com/issues/5903)
* duplicates [#5814](https://dev.icinga.com/issues/5814)
* blocks [#5903](https://dev.icinga.com/issues/5903)
* blocks [#5903](https://dev.icinga.com/issues/5903)

**Comment by lippserd** [comment]
I close this issue because the feature will be part of a module dedicated to display the Icinga 2 environment state.
