### ISSUE TITLE
[dev.icinga.com #5949] cli --format output broken

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#562]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/5949

**Created by mfriedrich on 2014-04-06 16:42:45 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2014-04-29 15:27:05 +00:00_)
Target Version: _(none)_
Last Update: _2014-04-29 15:27:05 +00:00 (in Redmine)_

---

    [root@icinga2a icinga2]# icingacli monitoring list --unhandled --format '$host$: $service$'
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$
    $host$: $service$

**Comment by dnsmichi** [comment]
Unfortunately this was never documented, so it bit me again during today's training. I'll prepare a PR which updates the CLI command help output, also for `--unhandled` -> `--problems`.
