### ISSUE TITLE
[dev.icinga.com #6080] Remove default settings from config.ini

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#594]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6080

**Created by elippmann on 2014-04-29 10:13:32 +00:00**

Assignee: _jmeyer_
Status: _Feedback_ 
Target Version: _Backlog_
Last Update: _2017-01-13 11:06:04 +00:00 (in Redmine)_

---

As a user I do not want to see default settings in the config.ini because I want to keep my configuration readable, simple and I only want to know what I've actually changed. The web interface however must know of every configuration directive available, but that is not part of this issue. If I ever change a configuration value back to its default via the web interface, the configuration is removed from the config.ini.

**Changesets**

_2017-01-13 10:59:15 +00:00_ by _nhilverling_ 1623722e4d44113ee766e262da8b057e74403e6e

    Form: Implement attribute defaultValues
    
    refs #6080

_2017-01-13 10:59:27 +00:00_ by _nhilverling_ 07372d6e9ec09464f01926dd664427bfb2cef726

    Form: Implement form element attribute ignoreDefault
    
    refs #6080

_2017-01-13 10:59:27 +00:00_ by _nhilverling_ cba4bad29ada9f6ad7f4279923a4ee4ea15d298c

    GeneralConfigForm: Use element attribute ignoreDefault in createElements
    
    refs #6080

**Comment by N-o-X** [comment]
@nilmerg please review

**Comment by lippserd** [comment]
I close this issue as we won't implement this anytime soon.
