### ISSUE TITLE
[dev.icinga.com #6084] Share dashboard panes to other users

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#596]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6084

**Created by jmeyer on 2014-04-29 11:09:41 +00:00**

Assignee: _(none)_
Status: _New_  (closed on _2014-04-29 13:26:10 +00:00_)
Target Version: _Backlog_
Last Update: _2016-08-30 09:44:31 +00:00 (in Redmine)_

---

As a user, I want to add new panes to the dashboard.

**Attachments**

* [dashboard_settings.png](https://dev.icinga.com/attachments/download/1775/dashboard_settings.png) tgelf - _2014-04-29 13:32:08 +00:00_

**Changesets**

_2015-09-30 10:55:21 +00:00_ by _jmeyer_ 1c7b398219f6fff6f25ea584687d7b7ac21a2feb

    Navigation: Do not provide "dashlet" as default item type
    
    Please revert this commit once we're about to finish the new
    implementation.
    
    refs #6084

---

**Relations**:

* relates [#5600](https://dev.icinga.com/issues/5600)
* relates [#8818](https://dev.icinga.com/issues/8818)
* duplicates [#6084](https://dev.icinga.com/issues/6084)
* duplicates [#6084](https://dev.icinga.com/issues/6084)
* duplicates [#6084](https://dev.icinga.com/issues/6084)

**Comment by blieberman** [comment]
bump on this, would be extremely useful.

**Comment by peteeckel** [comment]
Absolutely, especially in a HA environment where the dashboards not only need to be synced across all user directories, but also across all HA nodes.

So there's a strong +1 from my side.

**Comment by NeverUsedID** [comment]
Would like to see the option to create / share global dashboards  too.

**Comment by nilmerg** [comment]
Continues with #3809. Closed.
