### ISSUE TITLE
[dev.icinga.com #6154] Multi-select is non-intuitive

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#634]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6154

**Created by gbeutner on 2014-05-09 07:45:44 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2014-10-28 09:26:10 +00:00_)
Target Version: _(none)_
Last Update: _2014-10-28 09:26:10 +00:00 (in Redmine)_

---

Selecting multiple services (i.e. by holding down the ctrl or shift keys while selecting other services) is non-intuitive for web users.

It should be possible to select multiple services in a way that is easy to grasp for users.

---

**Relations**:

* relates [#6233](https://dev.icinga.com/issues/6233)

**Comment by fedepires** [comment]
I know this is old, but the multi-select is still very annoying when using mobile. So, I would rather have checkboxes and be able to use mobile, than SHIFT if there is no other option.

And I agree it's somewhat  uncommon, I had to look at the docs to find out how it was done.

**Comment by dnsmichi** [comment]
You are replying to a closed old issue, please start a new discussion/request.
