### ISSUE TITLE
[dev.icinga.com #6172] Move PDF support to a module

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#648]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6172

**Created by tgelf on 2014-05-09 09:38:43 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:44 +00:00 (in Redmine)_

---

Currently dompdf is the by far largest vendor library we ship. PDF support is a key feature, but the Icinga Web can eventually also perfectly run without offering such. As there are a lot of other optional dependencies involved with dompdf I'd strongly opt for moving "PDF Export" to a dedicated web module.

This makes things easier for packaging and results in less "core framework" dependencies once dompdf reaches Debian or other distros: https://packages.debian.org/wheezy-backports/php-dompdf

Regards,
Thomas

**Changesets**

_2014-10-29 15:25:25 +00:00_ by _jmeyer_ 504853961bdf2a90694aa9182f680a2440e44c22

    Add temporary requirement for the DOM php module
    
    Should be removed once dompdf isn't shipped with Icinga Web 2 anymore
    
    refs #7163
    refs #6172

---

**Relations**:

* relates [#6302](https://dev.icinga.com/issues/6302)
* relates [#6172](https://dev.icinga.com/issues/6172)
* relates [#6175](https://dev.icinga.com/issues/6175)
* relates [#6174](https://dev.icinga.com/issues/6174)
* relates [#8082](https://dev.icinga.com/issues/8082)

**Comment by lippserd** [comment]
I'm closing this since either we do it at some point or not.
