### ISSUE TITLE
[dev.icinga.com #6174] Improve default layout for PDF exports and make it customizable

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#650]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6174

**Created by tgelf on 2014-05-09 09:49:20 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:44 +00:00 (in Redmine)_

---

PDF export currently uses a dummy layout, we should:

-   provide a "good-looking" default
-   Failsafe internationalized page numbering and localized date (Created: ...) support
-   optionally provide a "even-better-looking" default with a nice front page (reporting!)
-   define a supported default way to create "custom logos" (keeping "powered by Icinga") and "custom layouts"

Regards,
Thomas

---

**Relations**:

* relates [#6174](https://dev.icinga.com/issues/6174)
* relates [#6174](https://dev.icinga.com/issues/6174)
* relates [#8082](https://dev.icinga.com/issues/8082)
* duplicates [#6174](https://dev.icinga.com/issues/6174)

**Comment by lippserd** [comment]
Moved to Icinga/icingaweb-module-pdfexport#2
