### ISSUE TITLE
[dev.icinga.com #6175] View pie charts in PDF exports too

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#651]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6175

**Created by tgelf on 2014-05-09 09:53:47 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-11-20 13:10:45 +00:00 (in Redmine)_

---

While Tcpdf claimed to support SVGs, it seems that dompdf doesn't. While we don't want to create a custom "PNG renderer", we could get this solved by adding an Imagick-based -&gt;toPng() function in our PieChart renderer.

Cheers,
Thomas

NB: dompdf doesn't handle floating elements well, aligning images might therefore get a little bit tricky.

---

**Relations**:

* relates [#6175](https://dev.icinga.com/issues/6175)
* relates [#6174](https://dev.icinga.com/issues/6174)
* relates [#8082](https://dev.icinga.com/issues/8082)

**Comment by lippserd** [comment]
Moved to Icinga/icingaweb2-module-pdfexport#3
