### ISSUE TITLE
[dev.icinga.com #6286] Status Map

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#690]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6286

**Created by ccesario on 2014-05-23 16:49:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-03-31 08:00:05 +00:00 (in Redmine)_

---

It would be interesting create a Hosts Maps feature like in icingaweb v1

---

**Relations**:

* duplicates [#6286](https://dev.icinga.com/issues/6286)

**Comment by lippserd** [comment]
Won't be implemented anytime soon. So I close this one.
