### ISSUE TITLE
Since Version 2.4 Time is off by 1 hour

### ISSUE THREAD

**Issue by svenauhagen** [Icinga/icingaweb2#75]
Hi,

I just updated to 2.4 and since then the times in icingaweb2 have 1 hour more than they should.
It worked correct on 2.3 and I checked the timzone in the database, server and php and they all give me the correct time.

Any advice or idea where the error in icingaweb2 is?

I am a programmer too, if you point me in the right direction I can try and debug the problem in the code and send a PR.

Best
Sven

**Comment by lippserd** [comment]
Hi,

Thanks for the report. This will be fixed w/ #2651.

Best regards,
Eric
