### ISSUE TITLE
[dev.icinga.com #6524] Icinga 2: visualize 'icinga' and 'cluster' health check performance data

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#768]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6524

**Created by mfriedrich on 2014-06-20 12:08:37 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-03-31 08:13:12 +00:00 (in Redmine)_

---

Similar to the disk pie charts, we should find a way to visualize the health checks without any additional addon required.

**Comment by lippserd** [comment]
The performance data for those checks should include min and max values which makes Web 2 able to render pie charts.
