### ISSUE TITLE
[dev.icinga.com #6562] Find a userfriendly way to store complicated filters

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#783]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6562

**Created by tgelf on 2014-06-24 08:46:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-03-31 09:45:08 +00:00 (in Redmine)_

---

Right now dashboards can be configured like this:

    [some.dashlet]
    url = "monitoring/list/services?service_problem&host=local*"

Or like this:

    [some.dashlet]
    url = monitoring/list/services
    service_problem = 1
    host = "local*"

You can also choose to use a combination of both methods. Things get more complicated with tricky filters. In a project I'm using dashlets filtered as follows like this fight now:

    url = "monitoring/list/services?service_state=2!host_problem&!host_name=DUMMY\
      &!_host_satellite=(one.sat|another.sat|some.more.sat)&!_host_customer=Special%20customer\
      &service_in_downtime=0&service_notifications_enabled&addcolumns=_host_location\
      &sort=service_severity&limit=1000

Well, it's even more complex than this one as we also use special experimental columns like host\_in\_slatime in the very same filter ;-)

Problem is, that it is not possible to store something like this in a friendly way. This means that people manually creating such dashboard definitions need to care about URL encoding (see \_host\_customer). I'd really like to find a solution for this.

It's not urgent, but would be really nice.

Cheers,
Thomas

**Comment by lippserd** [comment]
We only support having the URL configured now which is sufficient.
