### ISSUE TITLE
[dev.icinga.com #6578] Recursively resolve Icinga 2 runtime macros

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#791]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/6578

**Created by ccesario on 2014-06-25 13:03:28 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-03-31 08:15:58 +00:00 (in Redmine)_

---

It appear that icingaweb2 doesn't interpret/parse variables with variables as value.

See the image attached and the example host definition.

**Host definition**

    object Host "teconmega_firewall" { 
      display_name = "Tecnomega Cyberoam"

      check_command = "check_multi_ip"

      vars.multi_address = "$ip_address0$ $ip_address1$"

      vars.ip_address0 = "187.17.xx.xx"
      vars.ip_address0_description = "Link Ensite"

      vars.ip_address1 = "192.168.0.12"
      vars.ip_address1_description = "Link Net"

      notes = "Cyberoam Firewall"
      vars.os = "Router"
    }

    object CheckCommand "check_multi_ip" {
        import "plugin-check-command"

        command = [
            PluginDir + "/check_icmp"
        ]

        arguments = {
            "-H" = "$multi_address$"
            "-w" = "$icmp_wrta$,$icmp_wpl$%"
            "-c" = "$icmp_crta$,$icmp_cpl$%"
            "-n" = "$icmp_packets$"
            "-t" = "$icmp_timeout$"
        }

        vars.icmp_wrta = 3000
        vars.icmp_wpl = 80

        vars.icmp_crta = 5000
        vars.icmp_cpl = 100
    }

**Attachments**

* [host_detail.png](https://dev.icinga.com/attachments/download/1860/host_detail.png) ccesario - _2014-06-25 13:03:23 +00:00_

---

**Relations**:

* relates [#6392](https://dev.icinga.com/issues/6392)

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.  If you're interested in this topic, please open a new issue.
