### ISSUE TITLE
[dev.icinga.com #3759] Main Menu Configuration

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#81]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/3759

**Created by jmosshammer on 2013-03-05 12:03:00 +00:00**

Assignee: _cruell_
Status: _Resolved_  (closed on _2014-01-28 14:57:10 +00:00_)
Target Version: _2.0-1_
Last Update: _2014-01-28 14:57:10 +00:00 (in Redmine)_

---

As a user, I want to configure the main menu for all users via configuration files because I want to change the default locations, add filters and add new entries.

**Acceptance criteria**

-   Section name describes hierarchy
-   If the title property isn't defined, the section name defines the title
-   I set the order of menu items via a priority property per section
-   If the priority is unset, entries are ordered alphabetically
-   The default priority is 100
-   I define menu icons as CSS class or image source
-   Icons must be 16x16 px large
-   Active item in the main menu is the first matching URL
-   If the URL does not match, no menu item is hightlighted
-   The url property defines the section's target
-   If a section is missing the url property, it's not clickable

Example:

    [Hosts]
    ; New section
    ; Title property unset means title is "Hosts"
    url="/monitoring/list/hosts"
    iconClass="icon-hosts"
    priority=1

    [Hosts.Problems]
    ; New section beneath section hosts
    title="Problem Hosts"
    url="/monitoring/list/hosts?problem=1"
    priority=2

    [Hosts.A Link]
    title="Wiki"
    url="https://wiki.somewhere.com"
    priority=1
    icon="https://wiki.somewhere.com/icon.png"

**Changesets**

_2014-01-28 12:34:57 +00:00_ by _elippmann_ 48f5eebd53b287c0e0ccff818d78b24627465072

    Menu: Fix code compliance
    
    refs #3759

_2014-01-28 12:34:57 +00:00_ by _elippmann_ 59cb1d3cc779cc0d757da43afda6a1ead40c3e8a

    Menu: Fix HTML
    
    refs #3759

_2014-01-28 13:43:43 +00:00_ by _elippmann_ 77f7c9c1a6266467d9b481b6f64fb968e05c72b7

    Fix menu throwing an exception when a parent menu item does not exist
    
    refs #3759

_2014-01-28 13:46:43 +00:00_ by _elippmann_ 3ee56d38fb6ed20f8f9af0f7058915c2bcb8706b

    Merge branch 'feature/menu-configuration-3759'
    
    resolves #3759

**Comment by Harvie** [comment]
> Application wide menu.ini + one menu.ini per file

Did this ended up merged? I haven't found any documentation on how to setup system wide menu. I can only add menu items per user in `/etc/icingaweb2/preferences/YOUR_USERNAME/menu.ini` files...

**Comment by nilmerg** [comment]
A user's menu items can be shared. (Use `*` for anyone) That's the only way to make custom menu entries globally available.

**Comment by Harvie** [comment]
@nilmerg So i did that in UI and it did the trick. It have created file `/etc/icingaweb2/navigation/menu.ini `, that's what i've been asking to know. Thanks.

```
[Tactical Overview]
type = "menu-item"
url = "monitoring/tactical"
users = "*"
target = "_blank"
owner = "root"
```
