### ISSUE TITLE
[dev.icinga.com #7051] Url class should work also on CLI

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#952]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7051

**Created by tgelf on 2014-09-02 07:57:00 +00:00**

Assignee: _elippmann_
Status: _Feedback_  (closed on _2015-03-31 08:37:34 +00:00_)
Target Version: _Backlog_
Last Update: _2016-12-20 13:33:23 +00:00 (in Redmine)_

---

Fails because of depending on a Request. I'd suggest to solve this in two steps:

-   quickfix, provide a Cli\\FakeRequest and teach the Url class to get that one when running on CLI
-   in the long run, try to make Cli\\Params compatible to Url\\Params and create a "real" Request object for the CLI

Best,
Thomas

**Changesets**

_2016-10-28 09:47:45 +00:00_ by _jmeyer_ d207dcbd03bb70d885127c085f025e4e7bfef2fa

    Url: Throw ProgrammingError when trying to use Url::from* on the CLI
    
    refs #7051

_2016-12-20 13:32:10 +00:00_ by _(unknown)_ 66e4813c84a449e5da6e8dc76484cc4cdf84832e

    Make Url class working on CLI
    
    refs #7051

**Comment by lippserd** [comment]
@nilmerg Please open a new issue and clarify which parts of the Url class you want to use in the CLI. Since we have no real requirements specified here, I'll close this issue.
