### ISSUE TITLE
[dev.icinga.com #7052] Show translation statistics

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#953]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7052

**Created by tgelf on 2014-09-02 08:07:56 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-12-15 09:27:07 +00:00 (in Redmine)_

---

I'd like to see current translation progress on CLI.

---

**Comment by nilmerg** [comment]
@theFeu Please fix the following minor issues:

* Passing an unknown or not enabled module results in an ugly exception. This should rather be a proper error message.
* Another ugly exception is shown when trying to show statistics for a module without any gettext catalogs. A proper error message seems being more appropriate to me here as well :wink: 

Once done with it create a pull-request and I'll start with my final review.

**Comment by nilmerg** [comment]
Since https://github.com/Icinga/L10n, this is obsolete I'm afraid.
