### ISSUE TITLE
[dev.icinga.com #7149] Move testing related code to a module

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#998]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/7149

**Created by tgelf on 2014-09-09 08:52:10 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2015-03-31 08:51:09 +00:00 (in Redmine)_

---

Content may find it's place in the test module or in the test/php directory. Btw, I'd strongly suggest to reduce complexity in our BaseTestCase and re-evaluate FormTest and DbTests...

Cheers,
Thomas

**Comment by lippserd** [comment]
No progress has been made here. I'll close this issue because it's very old and we have no plans to work on it in the near future.
